elastic/apm-server

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/4b75f99ec4dc
---
<Actions>
<summary>Update to elastic/beats@4b75f99ec4dc</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 4b75f99ec4dc&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7543455111">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@4b75f99ec4dc

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b3a03e99baf5
---
<Actions>
<summary>Update to elastic/beats@b3a03e99baf5</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b3a03e99baf5&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7543455111">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@b3a03e99baf5

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/5d5afee8546c
---
<Actions>
<summary>Update to elastic/beats@daf66b1b3ba1</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh daf66b1b3ba1&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7557606818">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@5d5afee8546c

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.0-aarirsc2
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-aarirsc2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-aarirsc2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.0-aarirsc2

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-66d75d96-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7557640250">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.17-66d75d96

release.mk
Use the current version rather than the future one, so it reflects what the changes are about.
See https://github.com/elastic/apm-server/pull/12443#issuecomment-1896216384
=> ci(patch-release): use current version

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/7a2441915532
---
<Actions>
<summary>Update to elastic/beats@7a2441915532</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 7a2441915532&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7545660879">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@7a2441915532

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.0-08mvpdoi
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-08mvpdoi-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-08mvpdoi-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.0-08mvpdoi

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/4bc27d26ea69
---
<Actions>
<summary>Update to elastic/beats@4bc27d26ea69</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 4bc27d26ea69&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7571863868">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@4bc27d26ea69

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-knq1zsti
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-knq1zsti-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-knq1zsti-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-knq1zsti

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.0-pitatttq
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.0-pitatttq-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.0-pitatttq-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.0-pitatttq

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/74945355f943
---
<Actions>
<summary>Update to elastic/beats@74945355f943</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 74945355f943&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7585458761">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@74945355f943

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-36eb4463-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7585489359">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.17-36eb4463

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/49f905d02542
---
<Actions>
<summary>Update to elastic/beats@49f905d02542</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 49f905d02542&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7585458761">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@49f905d02542

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-l534sdis
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.0-l534sdis-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.0-l534sdis-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-l534sdis

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/0a722beac809
---
<Actions>
<summary>Update to elastic/beats@0a722beac809</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 0a722beac809&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7613099290">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@0a722beac809

NOTICE.txt, go.mod, go.sum, internal/beater/middleware/timeout_middleware_test.go
*Changeset*
* https://github.com/elastic/beats/commit/c23411acc04b
---
<Actions>
<summary>Update to elastic/beats@c23411acc04b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c23411acc04b&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7613099290">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@c23411acc04b

Makefile
It used to fail when running the linting, see https://github.com/elastic/apm-server/pull/12397\#issuecomment-1896261419
As agreed in [here](https://github.com/elastic/apm-server/pull/12462#issuecomment-1903091551), I disabled reviewdog if no lint entries. Otherwise grep will return `1` if no matches:
> EXIT STATUS
The grep utility exits with one of the following values:
0     One or more lines were selected.
1     No lines were selected.
>1    An error occurred.
=> ci(release): include Makefile

release.mk
I didn't test it out locally but now I did it
```bash
make patch-release RELEASE_VERSION=8.11.8 PROJECT_OWNER=v1v BASE_BRANCH=feature/patch-release
INFO: Create feature branch and update the versions. Target branch 8.11
::group::create-branch update-8.11.9
Switched to branch '8.11'
Switched to a new branch 'update-8.11.9'
::endgroup::
>> update-version
>> update-docs
>> update-version-makefile
>> update-version-legacy
...
```
=> release(patch): fix syntax error: unexpected end of file

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/630f62b55799
---
<Actions>
<summary>Update to elastic/beats@630f62b55799</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 630f62b55799&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7627637851">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@630f62b55799

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b2e2ecc36c54
---
<Actions>
<summary>Update to elastic/beats@b2e2ecc36c54</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b2e2ecc36c54&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7627637851">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@b2e2ecc36c54

release.mk
Remove leftover from https://github.com/elastic/apm-server/pull/12411
=> release: remove call to the deleted make goal

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/4e4f2d3839e3
---
<Actions>
<summary>Update to elastic/beats@4e4f2d3839e3</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 4e4f2d3839e3&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7642061022">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@4e4f2d3839e3

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/90228e66040f
---
<Actions>
<summary>Update to elastic/beats@90228e66040f</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 90228e66040f&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7642061022">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@90228e66040f

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.1-viuu0igj
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.1-viuu0igj-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.1-viuu0igj-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.1-viuu0igj

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-l5snflwr
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.0-l5snflwr-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.0-l5snflwr-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-l5snflwr

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/51f5cb4e4d23
---
<Actions>
<summary>Update to elastic/beats@6769ceec290b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6769ceec290b&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7669695512">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@51f5cb4e4d23

NOTICE.txt, changelogs/head.asciidoc, go.mod, go.sum
Bump apm-data to detect OTel messaging.{system,operation} for transactions
- Send a otel span as transaction with messaging.system or messaging.operation without messaging.destination. Ensure that `transaction.type` is `messaging`
https://github.com/elastic/apm-data/pull/204
=> Bump apm-data to detect OTel messaging.{system,operation} for transactions

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/cf731e633992
---
<Actions>
<summary>Update to elastic/beats@cf731e633992</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh cf731e633992&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7669695512">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@cf731e633992

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.18-1cc388da-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7698079610">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.18-1cc388da

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.1-mg2y3klg
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.1-mg2y3klg-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.1-mg2y3klg-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.1-mg2y3klg

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-yil7wib0
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-yil7wib0-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-yil7wib0-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-yil7wib0

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/374c05da46f7
---
<Actions>
<summary>Update to elastic/beats@cd8b58d8ad4a</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh cd8b58d8ad4a&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7669695512">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@374c05da46f7

systemtest/cmd/sendotlp/main.go
Add `-api-key` option to support api key auth in sendotlp.
This is particularly useful because sendotlp log exporter does not respect `$OTEL_EXPORTER_OTLP_HEADERS`.
=> sendotlp: Add support for api key auth

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.18-8136c1b9-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7713136900">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.18-8136c1b9

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/343847a093b9
---
<Actions>
<summary>Update to elastic/beats@343847a093b9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 343847a093b9&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7713103500">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@343847a093b9

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.1-lipljxnp
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.1-lipljxnp-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.1-lipljxnp-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.1-lipljxnp

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/8bac7d46af85
---
<Actions>
<summary>Update to elastic/beats@8bac7d46af85</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8bac7d46af85&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7727997966">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@8bac7d46af85

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.1-3x3y2wtd
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.1-3x3y2wtd-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.1-3x3y2wtd-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.1-3x3y2wtd

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/c7ec8f634ed6
---
<Actions>
<summary>Update to elastic/beats@c7ec8f634ed6</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c7ec8f634ed6&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7743233137">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@c7ec8f634ed6

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.18-84f8556d-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7743272461">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.18-84f8556d

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-por0bbe1
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.0-por0bbe1-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.0-por0bbe1-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-por0bbe1

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/eae57f95df94
---
<Actions>
<summary>Update to elastic/beats@eae57f95df94</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh eae57f95df94&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7743233137">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@eae57f95df94

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.1-jqpgs5zc
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.1-jqpgs5zc-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.1-jqpgs5zc-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.1-jqpgs5zc

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/63aa43c9b314
---
<Actions>
<summary>Update to elastic/beats@63aa43c9b314</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 63aa43c9b314&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7757704095">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@63aa43c9b314

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-c876301f
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-c876301f-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-c876301f-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-c876301f

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.1-6a15fcef
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.1-6a15fcef-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.1-6a15fcef-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.1-6a15fcef

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/aeb93a05c3f7
---
<Actions>
<summary>Update to elastic/beats@aeb93a05c3f7</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh aeb93a05c3f7&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7757704095">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@aeb93a05c3f7

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/6d4f1e6e2e42
---
<Actions>
<summary>Update to elastic/beats@6d4f1e6e2e42</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6d4f1e6e2e42&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7757704095">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@6d4f1e6e2e42

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/5e431f32119e
---
<Actions>
<summary>Update to elastic/beats@5e431f32119e</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 5e431f32119e&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7757704095">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@5e431f32119e

.github/workflows/update-dependabot-pr.yml
Use dependabot token because the workflow does not have access to actions secrets.
=> Use dependabot github token

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/0d7545b689a1
---
<Actions>
<summary>Update to elastic/beats@0d7545b689a1</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 0d7545b689a1&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7784359988">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@0d7545b689a1

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.18-c0dc75b4-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7757735496">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.18-c0dc75b4

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/84502d287440
---
<Actions>
<summary>Update to elastic/beats@84502d287440</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 84502d287440&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7785631840">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@84502d287440

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.1-f611ca6e
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.1-f611ca6e-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.1-f611ca6e-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.1-f611ca6e

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-2eea2ca0
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-2eea2ca0-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-2eea2ca0-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-2eea2ca0

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.18-8861f8b8-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7786474479">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.18-8861f8b8

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.18-18102b55-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7801702163">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.18-18102b55

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-f56d9bd5
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-f56d9bd5-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-f56d9bd5-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-f56d9bd5

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/df9694e1b625
---
<Actions>
<summary>Update to elastic/beats@df9694e1b625</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh df9694e1b625&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7801668834">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@df9694e1b625

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.1-6b6cce09
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.1-6b6cce09-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.1-6b6cce09-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.1-6b6cce09

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/1bc6e9b354e0
---
<Actions>
<summary>Update to elastic/beats@1bc6e9b354e0</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 1bc6e9b354e0&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7816760539">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@1bc6e9b354e0

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-c6fcd738
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-c6fcd738-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-c6fcd738-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-c6fcd738

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.1-135756ae
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.1-135756ae-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.1-135756ae-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.1-135756ae

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/7546ae1ceefa
---
<Actions>
<summary>Update to elastic/beats@7546ae1ceefa</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 7546ae1ceefa&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7821064868">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@7546ae1ceefa

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/01c93f09f360
---
<Actions>
<summary>Update to elastic/beats@01c93f09f360</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 01c93f09f360&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7821064868">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@01c93f09f360

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/2414d9579af9
---
<Actions>
<summary>Update to elastic/beats@2414d9579af9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 2414d9579af9&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7831563050">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@2414d9579af9

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-7ecbd6a2
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-7ecbd6a2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-7ecbd6a2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-7ecbd6a2

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/9db2cd179ac1
---
<Actions>
<summary>Update to elastic/beats@9db2cd179ac1</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 9db2cd179ac1&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7831563050">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@9db2cd179ac1

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.2-ae12c9ba
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.2-ae12c9ba-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.2-ae12c9ba-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.2-ae12c9ba

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/4c75049de8c9
---
<Actions>
<summary>Update to elastic/beats@4c75049de8c9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 4c75049de8c9&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7845743929">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@4c75049de8c9

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/e0722812561a
---
<Actions>
<summary>Update to elastic/beats@e0722812561a</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e0722812561a&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7845743929">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@e0722812561a

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.2-c93a0352
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.2-c93a0352-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.2-c93a0352-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.2-c93a0352

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-53e789c3-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7873673624">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.19-53e789c3

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d3cac73cfca8
---
<Actions>
<summary>Update to elastic/beats@d3cac73cfca8</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d3cac73cfca8&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7873630647">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d3cac73cfca8

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/7461af0a3239
---
<Actions>
<summary>Update to elastic/beats@7461af0a3239</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 7461af0a3239&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7873630647">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@7461af0a3239

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.2-5f8ffc93
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.2-5f8ffc93-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.2-5f8ffc93-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.2-5f8ffc93

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-e2cda7bd
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-e2cda7bd-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-e2cda7bd-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-e2cda7bd

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-8772c123-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7888457267">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.19-8772c123

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/c3cedcf912bf
---
<Actions>
<summary>Update to elastic/beats@c3cedcf912bf</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c3cedcf912bf&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7888424398">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@c3cedcf912bf

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d67bdbfb7eea
---
<Actions>
<summary>Update to elastic/beats@d67bdbfb7eea</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d67bdbfb7eea&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7888424398">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d67bdbfb7eea

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-7ad20c93
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.0-7ad20c93-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.0-7ad20c93-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-7ad20c93

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-c3e20ba6-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7903160988">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.19-c3e20ba6

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d32dda4f429a
---
<Actions>
<summary>Update to elastic/beats@d32dda4f429a</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d32dda4f429a&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7903115429">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d32dda4f429a

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/ecaf12cd07b5
---
<Actions>
<summary>Update to elastic/beats@ecaf12cd07b5</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ecaf12cd07b5&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7903115429">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@ecaf12cd07b5

.mergify.yml, CHANGELOG.asciidoc, changelogs/8.13.asciidoc, changelogs/head.asciidoc, cmd/intake-receiver/version.go, internal/version/version.go
Merge as soon as the GitHub checks are green.
=> 8.13: update docs, mergify, versions and changelogs

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-772867d3
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-772867d3-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-772867d3-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-772867d3

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/0b71acf2d6b4
---
<Actions>
<summary>Update to elastic/beats@0b71acf2d6b4</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 0b71acf2d6b4&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7917904356">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@0b71acf2d6b4

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/faabc0e8c79f
---
<Actions>
<summary>Update to elastic/beats@faabc0e8c79f</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh faabc0e8c79f&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7917904356">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@faabc0e8c79f

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.2-4fee8a94
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.2-4fee8a94-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.2-4fee8a94-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.2-4fee8a94

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/3924ac062523
---
<Actions>
<summary>Update to elastic/beats@3924ac062523</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 3924ac062523&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7932354152">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@3924ac062523

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-403a849e-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7932388159">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.19-403a849e

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/766136ebd865
---
<Actions>
<summary>Update to elastic/beats@766136ebd865</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 766136ebd865&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7932354152">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@766136ebd865

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-74aa7f3e-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7917937937">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.19-74aa7f3e

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.2-7bd62d94
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.2-7bd62d94-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.2-7bd62d94-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.2-7bd62d94

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/997b90ad8437
---
<Actions>
<summary>Update to elastic/beats@997b90ad8437</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 997b90ad8437&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7961506207">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@997b90ad8437

changelogs/8.12.asciidoc
Add 8.12.1 release notes
https://github.com/elastic/apm-server/compare/v8.12.0...v8.12.1
=> Add 8.12.1 release notes

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.2-0bde1b22
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.2-0bde1b22-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.2-0bde1b22-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.2-0bde1b22

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-fc9da510-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7975538463">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.19-fc9da510

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/8e7f15aac2c1
---
<Actions>
<summary>Update to elastic/beats@8e7f15aac2c1</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8e7f15aac2c1&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7975503928">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@8e7f15aac2c1

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d79af71f2d92
---
<Actions>
<summary>Update to elastic/beats@d79af71f2d92</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d79af71f2d92&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7975503928">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d79af71f2d92

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-466f28cb
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-466f28cb-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-466f28cb-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-466f28cb

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.2-bf518ba4
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.2-bf518ba4-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.2-bf518ba4-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.2-bf518ba4

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/6b3623b5f19d
---
<Actions>
<summary>Update to elastic/beats@6b3623b5f19d</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6b3623b5f19d&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7991088950">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@6b3623b5f19d

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-74d9fe02-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8006548050">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.19-74d9fe02

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/f3bc707d4ce0
---
<Actions>
<summary>Update to elastic/beats@f3bc707d4ce0</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh f3bc707d4ce0&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8006513591">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@f3bc707d4ce0

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/6fff6aa1b991
---
<Actions>
<summary>Update to elastic/beats@6fff6aa1b991</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6fff6aa1b991&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8006513591">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@6fff6aa1b991

docker-compose.yml, systemtest/ingest_test.go, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-74a79bf3
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-74a79bf3-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-74a79bf3-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-74a79bf3

apmpackage/apm/changelog.yml, cmd/intake-receiver/version.go, internal/version/version.go
=> 8.12.3: update docs

changelogs/8.12.asciidoc
=> docs: add 8.12.2 release notes

docker-compose.yml, systemtest/ingest_test.go, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-c44bedb9
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-c44bedb9-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-c44bedb9-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-c44bedb9

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b1c0c15c384e
---
<Actions>
<summary>Update to elastic/beats@b1c0c15c384e</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b1c0c15c384e&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8006513591">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@b1c0c15c384e

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/6dc03053c4eb
---
<Actions>
<summary>Update to elastic/beats@6dc03053c4eb</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6dc03053c4eb&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7991088950">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@6dc03053c4eb

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/2fc1cb57e0d4
---
<Actions>
<summary>Update to elastic/beats@2fc1cb57e0d4</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 2fc1cb57e0d4&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8021048494">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@2fc1cb57e0d4

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-d7334334
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-d7334334-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-d7334334-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-d7334334

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-6775ba34
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-6775ba34-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-6775ba34-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-6775ba34

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/2b64b95f2d42
---
<Actions>
<summary>Update to elastic/beats@2b64b95f2d42</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 2b64b95f2d42&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8021048494">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@2b64b95f2d42

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-9b33d64f-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8050979562">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.19-9b33d64f

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.2-af81666c
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.2-af81666c-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.2-af81666c-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.2-af81666c

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-e73731dc
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-e73731dc-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-e73731dc-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-e73731dc

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-496ca828
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-496ca828-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-496ca828-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-496ca828

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/0361e30247f8
---
<Actions>
<summary>Update to elastic/beats@0361e30247f8</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 0361e30247f8&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8050943045">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@0361e30247f8

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/7d49c3441a72
---
<Actions>
<summary>Update to elastic/beats@7d49c3441a72</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 7d49c3441a72&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8050943045">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@7d49c3441a72

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/1323c04e9242
---
<Actions>
<summary>Update to elastic/beats@1323c04e9242</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 1323c04e9242&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8050943045">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@1323c04e9242

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/475473de8f01
---
<Actions>
<summary>Update to elastic/beats@475473de8f01</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 475473de8f01&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8082445142">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@475473de8f01

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-b680863b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8082481666">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.19-d4a348d6

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-3e853527
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.0-bae8c4fa-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.0-bae8c4fa-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-3e853527

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-226c3ec4
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-8d2ed869-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-8d2ed869-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-226c3ec4

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.3-47841fb2
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.3-4ac1d971-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.3-4ac1d971-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.3-47841fb2

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b5c71e3bb6c2
---
<Actions>
<summary>Update to elastic/beats@b5c71e3bb6c2</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b5c71e3bb6c2&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8066802568">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@b5c71e3bb6c2

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/427526265d15
---
<Actions>
<summary>Update to elastic/beats@427526265d15</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 427526265d15&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8098064749">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@427526265d15

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-b395a473
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-b395a473-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-b395a473-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-b395a473

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.3-c580c40e
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-c580c40e-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.3-c580c40e-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.3-c580c40e

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-ca4c9a13
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-ca4c9a13-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-ca4c9a13-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-ca4c9a13

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/fd6688e9a644
---
<Actions>
<summary>Update to elastic/beats@fd6688e9a644</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh fd6688e9a644&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8098064749">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@fd6688e9a644

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-67f2fee7
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-67f2fee7-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-67f2fee7-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-67f2fee7

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.3-3f627ed1
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-3f627ed1-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.3-3f627ed1-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.3-3f627ed1

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-14244116
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-14244116-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-14244116-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-14244116

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/312fee4b03cc
---
<Actions>
<summary>Update to elastic/beats@312fee4b03cc</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 312fee4b03cc&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8113093923">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@312fee4b03cc

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/635781c808f3
---
<Actions>
<summary>Update to elastic/beats@635781c808f3</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 635781c808f3&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8113093923">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@635781c808f3

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-892e41b3
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-892e41b3-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-892e41b3-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-892e41b3

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.3-4d8adddd
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-4d8adddd-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.3-4d8adddd-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.3-4d8adddd

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/5f1e656e06fc
---
<Actions>
<summary>Update to elastic/beats@5f1e656e06fc</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 5f1e656e06fc&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8142302787">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@5f1e656e06fc

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-34a49bd9
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.0-34a49bd9-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.0-34a49bd9-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-34a49bd9

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/81c83c38d5b9
---
<Actions>
<summary>Update to elastic/beats@81c83c38d5b9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 81c83c38d5b9&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8142302787">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@81c83c38d5b9

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.3-b03f626a
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.3-b03f626a-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.3-b03f626a-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.3-b03f626a

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/94b5d1f840df
---
<Actions>
<summary>Update to elastic/beats@94b5d1f840df</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 94b5d1f840df&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8158383241">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@94b5d1f840df

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d23b4d336221
---
<Actions>
<summary>Update to elastic/beats@d23b4d336221</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d23b4d336221&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8158383241">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d23b4d336221

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-1dcb9209
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-1dcb9209-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-1dcb9209-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-1dcb9209

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-cd4b6257-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8251100382">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.19-cd4b6257

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.3-fec1a044
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.3-a6d09860-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.3-a6d09860-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.3-fec1a044

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/24f43404cc4e
---
<Actions>
<summary>Update to elastic/beats@4d5aa6de0e62</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 4d5aa6de0e62&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8282909579">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@24f43404cc4e

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/fac6a9350b6b
---
<Actions>
<summary>Update to elastic/beats@e486dcea834b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e486dcea834b&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8282909579">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@fac6a9350b6b

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-176a9dfa-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8282945394">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.19-176a9dfa

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-023068fa-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8298238051">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.19-023068fa

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/5676ad2fe875
---
<Actions>
<summary>Update to elastic/beats@5676ad2fe875</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 5676ad2fe875&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8298201506">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@5676ad2fe875

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d7f2c0c0b9cd
---
<Actions>
<summary>Update to elastic/beats@13f5d874f0f7</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 13f5d874f0f7&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8328821310">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d7f2c0c0b9cd

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.3-38b17954
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.3-068eda6a-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.3-068eda6a-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.3-38b17954

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/1b13c648feef
---
<Actions>
<summary>Update to elastic/beats@1b13c648feef</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 1b13c648feef&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8345310763">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@1b13c648feef

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-de4951fb
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-de4951fb-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-de4951fb-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-de4951fb

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.3-ef3d6214
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-ef3d6214-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.3-ef3d6214-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.3-ef3d6214

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-892adbf2
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-892adbf2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-892adbf2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-892adbf2

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-14d688f1
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-14d688f1-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-14d688f1-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-14d688f1

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d57e4d2c9999
---
<Actions>
<summary>Update to elastic/beats@d57e4d2c9999</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d57e4d2c9999&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8361123847">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d57e4d2c9999

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/22af217d8121
---
<Actions>
<summary>Update to elastic/beats@22af217d8121</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 22af217d8121&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8361123847">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@22af217d8121

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.3-f215049e
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.3-f215049e-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.3-f215049e-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.3-f215049e

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-c03b2a22
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-c03b2a22-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-c03b2a22-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-c03b2a22

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/62a1cb52c841
---
<Actions>
<summary>Update to elastic/beats@62a1cb52c841</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 62a1cb52c841&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8377140341">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@62a1cb52c841

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-e408206f-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8377188389">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.19-e408206f

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d99ae3e87255
---
<Actions>
<summary>Update to elastic/beats@d99ae3e87255</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d99ae3e87255&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8377140341">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d99ae3e87255

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/c91eaeecc669
---
<Actions>
<summary>Update to elastic/beats@c91eaeecc669</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c91eaeecc669&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8377140341">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@c91eaeecc669

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/cf3b4aac26f6
---
<Actions>
<summary>Update to elastic/beats@cf3b4aac26f6</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh cf3b4aac26f6&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8392282560">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@cf3b4aac26f6

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-0321523b
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-0321523b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-0321523b-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-0321523b

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/1ea9b367b3c0
---
<Actions>
<summary>Update to elastic/beats@1ea9b367b3c0</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 1ea9b367b3c0&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8392282560">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@1ea9b367b3c0

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.19-b95b312a-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8392318816">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.19-b95b312a

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/55321809127d
---
<Actions>
<summary>Update to elastic/beats@55321809127d</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 55321809127d&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8392282560">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@55321809127d

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-11aed950
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.0-11aed950-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.0-11aed950-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-11aed950

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/7e036b6a3f52
---
<Actions>
<summary>Update to elastic/beats@7e036b6a3f52</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 7e036b6a3f52&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8422208597">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@7e036b6a3f52

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.12.3-96ef37fe
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.3-96ef37fe-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.3-96ef37fe-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.12.3-96ef37fe

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/f8eceaac99fe
---
<Actions>
<summary>Update to elastic/beats@f8eceaac99fe</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh f8eceaac99fe&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8422208597">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@f8eceaac99fe

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-4e9e4428
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-4e9e4428-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-4e9e4428-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-4e9e4428

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/5750480ebf63
---
<Actions>
<summary>Update to elastic/beats@5750480ebf63</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 5750480ebf63&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8422208597">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@5750480ebf63

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/90a492c1339e
---
<Actions>
<summary>Update to elastic/beats@90a492c1339e</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 90a492c1339e&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8438177894">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@90a492c1339e

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/a1c292dc6514
---
<Actions>
<summary>Update to elastic/beats@a1c292dc6514</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a1c292dc6514&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8438177894">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@a1c292dc6514

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/9038179f814f
---
<Actions>
<summary>Update to elastic/beats@9038179f814f</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 9038179f814f&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8438177894">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@9038179f814f

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-433ba96e
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-433ba96e-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-433ba96e-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-433ba96e

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-4ba2d6fa
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-4ba2d6fa-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-4ba2d6fa-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.0-4ba2d6fa

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b55ba44a1831
---
<Actions>
<summary>Update to elastic/beats@b55ba44a1831</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b55ba44a1831&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8453935493">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@b55ba44a1831

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/48dcd6ab7512
---
<Actions>
<summary>Update to elastic/beats@48dcd6ab7512</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 48dcd6ab7512&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8482308265">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@48dcd6ab7512

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-20c1806a
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-20c1806a-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-20c1806a-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-20c1806a

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.1-6f55db03
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.1-6f55db03-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.1-6f55db03-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.1-6f55db03

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d41b4978ea7b
---
<Actions>
<summary>Update to elastic/beats@d41b4978ea7b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d41b4978ea7b&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8525016630">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d41b4978ea7b

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-f2b0327c
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-f2b0327c-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-f2b0327c-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-f2b0327c

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/fd74bf827c85
---
<Actions>
<summary>Update to elastic/beats@fd74bf827c85</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh fd74bf827c85&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8540959448">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@fd74bf827c85

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/0959d568d633
---
<Actions>
<summary>Update to elastic/beats@0959d568d633</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 0959d568d633&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8540959448">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@0959d568d633

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.1-24eaebbb
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.1-24eaebbb-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.1-24eaebbb-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.1-24eaebbb

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/ef48eb4e71ed
---
<Actions>
<summary>Update to elastic/beats@ef48eb4e71ed</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ef48eb4e71ed&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8556852765">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@ef48eb4e71ed

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/0ce396cba611
---
<Actions>
<summary>Update to elastic/beats@0ce396cba611</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 0ce396cba611&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8556852765">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@0ce396cba611

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-b2525d1c
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-b2525d1c-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-b2525d1c-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-b2525d1c

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.2-765b9793
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.2-765b9793-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.2-765b9793-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.2-765b9793

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/65ca2de7efaf
---
<Actions>
<summary>Update to elastic/beats@65ca2de7efaf</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 65ca2de7efaf&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8571772327">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@65ca2de7efaf

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/cba30347320f
---
<Actions>
<summary>Update to elastic/beats@cba30347320f</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh cba30347320f&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8571772327">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@cba30347320f

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/5947565307e3
---
<Actions>
<summary>Update to elastic/beats@5947565307e3</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 5947565307e3&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8602321225">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@5947565307e3

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-34b4df0a
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-34b4df0a-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-34b4df0a-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-34b4df0a

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/9dfe90921ad7
---
<Actions>
<summary>Update to elastic/beats@9dfe90921ad7</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 9dfe90921ad7&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8602321225">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@9dfe90921ad7

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/8efb36685ea9
---
<Actions>
<summary>Update to elastic/beats@8efb36685ea9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8efb36685ea9&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8617911381">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@8efb36685ea9

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/96b9b40eea9d
---
<Actions>
<summary>Update to elastic/beats@63fc0426f38d</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 63fc0426f38d&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8633449999">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@96b9b40eea9d

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/a3f7baece42f
---
<Actions>
<summary>Update to elastic/beats@a3f7baece42f</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a3f7baece42f&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8633449999">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@a3f7baece42f

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-540ac545
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-540ac545-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-540ac545-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-540ac545

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/aded3fc807f1
---
<Actions>
<summary>Update to elastic/beats@aded3fc807f1</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh aded3fc807f1&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8648885769">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@aded3fc807f1

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/2109070deb05
---
<Actions>
<summary>Update to elastic/beats@2109070deb05</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 2109070deb05&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8664057086">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@2109070deb05

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-cf1b0234
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-cf1b0234-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-cf1b0234-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-cf1b0234

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.3-19734ad9
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-19734ad9-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.3-19734ad9-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.3-19734ad9

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b9db63a64b36
---
<Actions>
<summary>Update to elastic/beats@b9db63a64b36</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b9db63a64b36&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8691415908">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@b9db63a64b36

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/11346e1253ad
---
<Actions>
<summary>Update to elastic/beats@11346e1253ad</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 11346e1253ad&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8707915687">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@11346e1253ad

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-29fdcf2a-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8707955799">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.21-29fdcf2a

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.3-b68daf90
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-b68daf90-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.3-b68daf90-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.3-b68daf90

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-e9b73307-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8724236814">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.21-e9b73307

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.3-3dc31fcb
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-3dc31fcb-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.3-3dc31fcb-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.3-3dc31fcb

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/4a5d903c48b7
---
<Actions>
<summary>Update to elastic/beats@4a5d903c48b7</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 4a5d903c48b7&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8724192233">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@4a5d903c48b7

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/ab27a657e4f1
---
<Actions>
<summary>Update to elastic/beats@ab27a657e4f1</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ab27a657e4f1&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8724192233">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@ab27a657e4f1

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-799c1dc0
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-799c1dc0-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-799c1dc0-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-799c1dc0

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.3-c9047748
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-c9047748-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.3-c9047748-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.3-c9047748

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b4ff53ce2b2d
---
<Actions>
<summary>Update to elastic/beats@b4ff53ce2b2d</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b4ff53ce2b2d&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8740215781">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@b4ff53ce2b2d

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-53490780-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8740256761">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.21-53490780

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/a6e3d7080051
---
<Actions>
<summary>Update to elastic/beats@a6e3d7080051</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a6e3d7080051&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8740215781">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@a6e3d7080051

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-318ae53b
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-318ae53b-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-318ae53b-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-318ae53b

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/ffd19c1ee383
---
<Actions>
<summary>Update to elastic/beats@ffd19c1ee383</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ffd19c1ee383&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8755628260">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@ffd19c1ee383

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.21-587bbe3b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8755664787">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.21-587bbe3b

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.3-c3270b70
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-c3270b70-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.3-c3270b70-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.3-c3270b70

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b04f48b102f7
---
<Actions>
<summary>Update to elastic/beats@b04f48b102f7</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b04f48b102f7&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8786292600">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@b04f48b102f7

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/990ef9a377df
---
<Actions>
<summary>Update to elastic/beats@990ef9a377df</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 990ef9a377df&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8786292600">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@990ef9a377df

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.3-22bed9d1
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-22bed9d1-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.3-22bed9d1-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.3-22bed9d1

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/c9428eb12f81
---
<Actions>
<summary>Update to elastic/beats@c9428eb12f81</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c9428eb12f81&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8786292600">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@c9428eb12f81

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d2fa7e98e51d
---
<Actions>
<summary>Update to elastic/beats@d2fa7e98e51d</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d2fa7e98e51d&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8802674440">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d2fa7e98e51d

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/4baab4c67bc9
---
<Actions>
<summary>Update to elastic/beats@4baab4c67bc9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 4baab4c67bc9&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8802674440">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@4baab4c67bc9

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/e6cae466ab81
---
<Actions>
<summary>Update to elastic/beats@e6cae466ab81</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e6cae466ab81&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8802674440">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@e6cae466ab81

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.3-94d3b00c
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-94d3b00c-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.3-94d3b00c-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.3-94d3b00c

changelogs/7.17.asciidoc
Similar to: https://github.com/elastic/ingest-docs/pull/1006
Closes: https://github.com/elastic/apm-server/issues/13031
=> Document fleet-server issue as known issue for 7.17.20

.github/workflows/prepare-release/action.yml
=> ci(7.17): fix composite action

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/4c04c1ad8631
---
<Actions>
<summary>Update to elastic/beats@4c04c1ad8631</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 4c04c1ad8631&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8940942081">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@4c04c1ad8631

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.3-76ce1a63
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.3-76ce1a63-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.3-76ce1a63-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.3-76ce1a63

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-c743e4c8
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-c743e4c8-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-c743e4c8-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-c743e4c8

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b24ddd14c936
---
<Actions>
<summary>Update to elastic/beats@b24ddd14c936</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b24ddd14c936&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8971250601">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@b24ddd14c936

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/25e90fd1feff
---
<Actions>
<summary>Update to elastic/beats@25e90fd1feff</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 25e90fd1feff&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8987668951">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@25e90fd1feff

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/8acc4f794513
---
<Actions>
<summary>Update to elastic/beats@8acc4f794513</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8acc4f794513&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8987668951">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@8acc4f794513

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/f4a984d21af6
---
<Actions>
<summary>Update to elastic/beats@f4a984d21af6</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh f4a984d21af6&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/8987668951">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@f4a984d21af6

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.4-cc6fca83
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.4-cc6fca83-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.4-cc6fca83-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.4-cc6fca83

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-177234da
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-177234da-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-177234da-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-177234da

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/55f71c4ba1ec
---
<Actions>
<summary>Update to elastic/beats@55f71c4ba1ec</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 55f71c4ba1ec&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9001978218">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@55f71c4ba1ec

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d1089d151aca
---
<Actions>
<summary>Update to elastic/beats@d1089d151aca</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d1089d151aca&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9001978218">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d1089d151aca

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b6a59d620eef
---
<Actions>
<summary>Update to elastic/beats@b6a59d620eef</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b6a59d620eef&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9001978218">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@b6a59d620eef

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/0f8b2ad7993c
---
<Actions>
<summary>Update to elastic/beats@0f8b2ad7993c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 0f8b2ad7993c&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9004049147">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@0f8b2ad7993c

cmd/intake-receiver/version.go, internal/version/version.go
=> Bump up version to 8.13.5

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/ca1b8f5b0ba5
---
<Actions>
<summary>Update to elastic/beats@ca1b8f5b0ba5</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ca1b8f5b0ba5&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9019224902">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@ca1b8f5b0ba5

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/7438a349d229
---
<Actions>
<summary>Update to elastic/beats@7438a349d229</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 7438a349d229&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9019224902">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@7438a349d229

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/edf456889886
---
<Actions>
<summary>Update to elastic/beats@edf456889886</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh edf456889886&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9019224902">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@edf456889886

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.4-056df8a2
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.4-056df8a2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.4-056df8a2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.4-056df8a2

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-fd69f4fd
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-fd69f4fd-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-fd69f4fd-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-fd69f4fd

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/74c52c2949d3
---
<Actions>
<summary>Update to elastic/beats@74c52c2949d3</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 74c52c2949d3&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9034130035">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@74c52c2949d3

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/3472c7c5e527
---
<Actions>
<summary>Update to elastic/beats@3472c7c5e527</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 3472c7c5e527&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9034130035">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@3472c7c5e527

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/a878b4927e9d
---
<Actions>
<summary>Update to elastic/beats@a878b4927e9d</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a878b4927e9d&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9034130035">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@a878b4927e9d

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-99ead9e9
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-99ead9e9-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-99ead9e9-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-99ead9e9

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-15ba0fb2
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-15ba0fb2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-15ba0fb2-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-15ba0fb2

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-f94896f6
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-f94896f6-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-f94896f6-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-f94896f6

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/c91503b4cb33
---
<Actions>
<summary>Update to elastic/beats@c91503b4cb33</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c91503b4cb33&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9065175729">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@c91503b4cb33

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/67e19a409d6c
---
<Actions>
<summary>Update to elastic/beats@67e19a409d6c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 67e19a409d6c&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9065175729">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@67e19a409d6c

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/e119c79a761a
---
<Actions>
<summary>Update to elastic/beats@e119c79a761a</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e119c79a761a&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9065175729">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@e119c79a761a

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/30e7239b3c7c
---
<Actions>
<summary>Update to elastic/beats@30e7239b3c7c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 30e7239b3c7c&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9081629905">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@30e7239b3c7c

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-a2355063
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-a2355063-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-a2355063-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-a2355063

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/3dd0dd177d73
---
<Actions>
<summary>Update to elastic/beats@3dd0dd177d73</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 3dd0dd177d73&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9081629905">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@3dd0dd177d73

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-0e5b6971
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-0e5b6971-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-0e5b6971-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-0e5b6971

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/6425cc045456
---
<Actions>
<summary>Update to elastic/beats@6425cc045456</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6425cc045456&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9081629905">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@6425cc045456

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/6b1ccbd05ab2
---
<Actions>
<summary>Update to elastic/beats@6b1ccbd05ab2</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6b1ccbd05ab2&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9098015090">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@6b1ccbd05ab2

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-28857d3f
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-28857d3f-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-28857d3f-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-28857d3f

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-526ba7a5
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-526ba7a5-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-526ba7a5-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-526ba7a5

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/52f0a8b74936
---
<Actions>
<summary>Update to elastic/beats@52f0a8b74936</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 52f0a8b74936&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9098015090">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@52f0a8b74936

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/3b269ef07657
---
<Actions>
<summary>Update to elastic/beats@3b269ef07657</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 3b269ef07657&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9114612216">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@3b269ef07657

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/f0a0338f62ca
---
<Actions>
<summary>Update to elastic/beats@f0a0338f62ca</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh f0a0338f62ca&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9114612216">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@f0a0338f62ca

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-c0a6b373
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-c0a6b373-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-c0a6b373-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-c0a6b373

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-201eb198
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-201eb198-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-201eb198-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-201eb198

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/fb400c5840b0
---
<Actions>
<summary>Update to elastic/beats@fb400c5840b0</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh fb400c5840b0&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9130250945">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@fb400c5840b0

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/bf138189db06
---
<Actions>
<summary>Update to elastic/beats@bf138189db06</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh bf138189db06&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9130250945">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@bf138189db06

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-05470747
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.5-05470747-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.5-05470747-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-05470747

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/8e2453ff2553
---
<Actions>
<summary>Update to elastic/beats@8e2453ff2553</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8e2453ff2553&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9130250945">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@8e2453ff2553

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-1a872dbc
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.15.0-1a872dbc-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.15.0-1a872dbc-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-1a872dbc

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-3f0620ae
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-3f0620ae-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-3f0620ae-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-3f0620ae

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/174c0b12d07a
---
<Actions>
<summary>Update to elastic/beats@174c0b12d07a</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 174c0b12d07a&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9160703233">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@174c0b12d07a

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/3da42136c753
---
<Actions>
<summary>Update to elastic/beats@3da42136c753</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 3da42136c753&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9176853733">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@3da42136c753

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/ba5fa061aabe
---
<Actions>
<summary>Update to elastic/beats@ba5fa061aabe</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ba5fa061aabe&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9176853733">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@ba5fa061aabe

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-ede8ab2b
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-ede8ab2b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-ede8ab2b-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-ede8ab2b

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-9bce1e63
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-9bce1e63-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-9bce1e63-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-9bce1e63

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d8072923498c
---
<Actions>
<summary>Update to elastic/beats@d8072923498c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d8072923498c&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9176853733">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d8072923498c

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-c5159767
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-c5159767-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-c5159767-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-c5159767

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/6124f596a273
---
<Actions>
<summary>Update to elastic/beats@6124f596a273</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6124f596a273&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9193725727">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@6124f596a273

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/0b125065e6aa
---
<Actions>
<summary>Update to elastic/beats@0b125065e6aa</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 0b125065e6aa&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9193725727">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@0b125065e6aa

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-bfa6e0c7
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-bfa6e0c7-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-bfa6e0c7-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-bfa6e0c7

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-3598a5d8
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-3598a5d8-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-3598a5d8-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-3598a5d8

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/8c8d4dc1c1e4
---
<Actions>
<summary>Update to elastic/beats@8c8d4dc1c1e4</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8c8d4dc1c1e4&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9210332503">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@8c8d4dc1c1e4

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/24e189184242
---
<Actions>
<summary>Update to elastic/beats@24e189184242</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 24e189184242&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9210332503">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@24e189184242

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-e7873a67
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-e7873a67-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-e7873a67-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-e7873a67

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-cdfa63ab
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.5-cdfa63ab-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.5-cdfa63ab-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-cdfa63ab

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-5fa6cf29
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-5fa6cf29-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-5fa6cf29-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-5fa6cf29

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-04e5793a
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-04e5793a-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-04e5793a-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-04e5793a

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/f8622fb08afc
---
<Actions>
<summary>Update to elastic/beats@f8622fb08afc</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh f8622fb08afc&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9225988854">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@f8622fb08afc

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d5bfebb8940d
---
<Actions>
<summary>Update to elastic/beats@d5bfebb8940d</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d5bfebb8940d&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9225988854">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d5bfebb8940d

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-61c3ba82
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-61c3ba82-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-61c3ba82-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-61c3ba82

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-dfb80c95
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-dfb80c95-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-dfb80c95-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-dfb80c95

.buildkite/package.yml
Enable the chainguard docker image generation.
DRA already uses Docker, so I thought it was required to enable it but it was already .
=> buildkite: create chainguard images

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-561c6014
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-561c6014-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-561c6014-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-561c6014

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/19499ae5ab94
---
<Actions>
<summary>Update to elastic/beats@19499ae5ab94</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 19499ae5ab94&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9256898333">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@19499ae5ab94

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-96dbea5b
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.5-96dbea5b-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.5-96dbea5b-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-96dbea5b

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/1022e35df783
---
<Actions>
<summary>Update to elastic/beats@1022e35df783</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 1022e35df783&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9256898333">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@1022e35df783

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/08f288389381
---
<Actions>
<summary>Update to elastic/beats@08f288389381</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 08f288389381&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9271721981">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@08f288389381

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/497f7edc4f4b
---
<Actions>
<summary>Update to elastic/beats@497f7edc4f4b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 497f7edc4f4b&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9271721981">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@497f7edc4f4b

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/f411b0624c17
---
<Actions>
<summary>Update to elastic/beats@f411b0624c17</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh f411b0624c17&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9271721981">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@f411b0624c17

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-04f3dd03
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-04f3dd03-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-04f3dd03-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-04f3dd03

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-67c2c600
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-67c2c600-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-67c2c600-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-67c2c600

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-ed654efd
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-ed654efd-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-ed654efd-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-ed654efd

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/35eccb8f5735
---
<Actions>
<summary>Update to elastic/beats@35eccb8f5735</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 35eccb8f5735&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9288466786">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@35eccb8f5735

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-c50a4390
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-c50a4390-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-c50a4390-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-c50a4390

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-1b4d655a
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-1b4d655a-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-1b4d655a-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-1b4d655a

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-e5f00eca
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-e5f00eca-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-e5f00eca-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-e5f00eca

.github/workflows/bump-golang.yml
Add condition to avoid notifying if success but only when failing 
=> github-actions: notify if failure only when bump-golang

.github/workflows/microbenchmark.yml
Avoid using Vault secrets and use GitHub secrets instead.
Avoid waiting for the build but let's the slack notifications be sent through Buildkite instead
=> github-action: use buildkite with GitHub tokens

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-1d20bcfe
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-1d20bcfe-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-1d20bcfe-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-1d20bcfe

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-44c17e84
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-44c17e84-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-44c17e84-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-44c17e84

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/470373611bda
---
<Actions>
<summary>Update to elastic/beats@470373611bda</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 470373611bda&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9304752263">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@470373611bda

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/98202e442820
---
<Actions>
<summary>Update to elastic/beats@98202e442820</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 98202e442820&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9288466786">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@98202e442820

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/6ee03ee04fb7
---
<Actions>
<summary>Update to elastic/beats@6ee03ee04fb7</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6ee03ee04fb7&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9304752263">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@6ee03ee04fb7

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-6c944218
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-6c944218-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-6c944218-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-6c944218

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-b3ff27eb
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-b3ff27eb-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-b3ff27eb-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-b3ff27eb

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-7a354205
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.0-7a354205-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.0-7a354205-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-7a354205

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d77596ace183
---
<Actions>
<summary>Update to elastic/beats@d77596ace183</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d77596ace183&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9320183577">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d77596ace183

NOTICE.txt, go.mod, go.sum
Includes fix "Remove item.Error.Reason for unavailable_shards_exception"
~~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)~~ to be included in main PR #13287 
=> Bump go-docappender to v1.1.1

NOTICE.txt, changelogs/8.14.asciidoc, go.mod, go.sum
Includes fix "Remove item.Error.Reason for unavailable_shards_exception"
backport to 8.14 for changelog. The actual 8.14 changes are included in #13286 
=> Bump go-docappender to v2.1.3

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/8cc85a2d59b6
---
<Actions>
<summary>Update to elastic/beats@8cc85a2d59b6</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8cc85a2d59b6&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9352530140">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@8cc85a2d59b6

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-5dfd9f77
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-5dfd9f77-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-5dfd9f77-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-5dfd9f77

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.22-0ffa86c5-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9352578649">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.22-0ffa86c5

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-aadf4dc6
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-aadf4dc6-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-aadf4dc6-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-aadf4dc6

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-9180a854
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.15.0-9180a854-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.15.0-9180a854-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-9180a854

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/de52d1434ea3
---
<Actions>
<summary>Update to elastic/beats@de52d1434ea3</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh de52d1434ea3&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9352530140">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@de52d1434ea3

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/4d4f1ced13fe
---
<Actions>
<summary>Update to elastic/beats@4d4f1ced13fe</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 4d4f1ced13fe&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9369477269">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@4d4f1ced13fe

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/217f5a626498
---
<Actions>
<summary>Update to elastic/beats@217f5a626498</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 217f5a626498&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9369477269">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@217f5a626498

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.22-fc4e6ec2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9369517530">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.22-fc4e6ec2

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-20996be4
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-20996be4-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-20996be4-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-20996be4

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-0eb8d6bf
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-0eb8d6bf-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-0eb8d6bf-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-0eb8d6bf

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/c46512f95b45
---
<Actions>
<summary>Update to elastic/beats@c46512f95b45</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c46512f95b45&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9369477269">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@c46512f95b45

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d23413676ebd
---
<Actions>
<summary>Update to elastic/beats@d23413676ebd</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d23413676ebd&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9386494896">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d23413676ebd

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-dd711047
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.5-dd711047-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.5-dd711047-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-dd711047

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-81c97bc2
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-81c97bc2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-81c97bc2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-81c97bc2

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-8dbc9634
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-8dbc9634-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-8dbc9634-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-8dbc9634

.buildkite/scripts/dra.sh
Cosmetic change to highligh in Buildkite the HTML report when uploading artifacts with the DRA automation
=> buildkite: create link with the DRA html report

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.5-50954ab2
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.5-50954ab2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.5-50954ab2-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.13.5-50954ab2

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/90f9e8f6e48e
---
<Actions>
<summary>Update to elastic/beats@90f9e8f6e48e</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 90f9e8f6e48e&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9403216732">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@90f9e8f6e48e

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-aa0ade8a
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-aa0ade8a-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-aa0ade8a-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-aa0ade8a

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-f18b4b35
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-f18b4b35-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-f18b4b35-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-f18b4b35

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/ff4b518ddcea
---
<Actions>
<summary>Update to elastic/beats@ff4b518ddcea</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ff4b518ddcea&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9419066870">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@ff4b518ddcea

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.0-a753d549
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.0-a753d549-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.0-a753d549-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.0-a753d549

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-725cdb43
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-725cdb43-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-725cdb43-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-725cdb43

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.1-99e97402
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.1-99e97402-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.1-99e97402-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.1-99e97402

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/de256b88f101
---
<Actions>
<summary>Update to elastic/beats@de256b88f101</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh de256b88f101&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9450733274">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@de256b88f101

apmpackage/apm/changelog.yml, apmpackage/apm/manifest.yml, changelogs/7.17.asciidoc, cmd/version.go
=> Add 7.17.22 release notes and bump version to 7.17.23

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-fd647d58
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-fd647d58-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-fd647d58-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-fd647d58

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.1-8b8a5a33
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.1-8b8a5a33-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.1-8b8a5a33-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.1-8b8a5a33

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/821ae189c19b
---
<Actions>
<summary>Update to elastic/beats@821ae189c19b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 821ae189c19b&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9484961736">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@821ae189c19b

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/60ba7bb46d03
---
<Actions>
<summary>Update to elastic/beats@60ba7bb46d03</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 60ba7bb46d03&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9484961736">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@60ba7bb46d03

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.1-49676bee
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.1-49676bee-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.1-49676bee-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.1-49676bee

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-d2070ed2
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-d2070ed2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-d2070ed2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-d2070ed2

.github/workflows/benchmarks.yml, .github/workflows/check-docker-compose.yml
Use GitHub secrets with IasC and avoid using Vault secrets path.
This is one of the few other PRs I'll be raising.
=> github-actions: slack bot and kibana benchmark

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/20fea92709ea
---
<Actions>
<summary>Update to elastic/beats@20fea92709ea</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 20fea92709ea&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9502011880">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@20fea92709ea

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/f9fec1e4ff85
---
<Actions>
<summary>Update to elastic/beats@f9fec1e4ff85</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh f9fec1e4ff85&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9502011880">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@f9fec1e4ff85

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/522cf448075a
---
<Actions>
<summary>Update to elastic/beats@522cf448075a</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 522cf448075a&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9518204793">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@522cf448075a

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-d4efed09
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.15.0-d4efed09-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.15.0-d4efed09-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-d4efed09

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-0ba21de0
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.2-0ba21de0-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.2-0ba21de0-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-0ba21de0

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/39a018c8c64b
---
<Actions>
<summary>Update to elastic/beats@39a018c8c64b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 39a018c8c64b&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9550000385">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@39a018c8c64b

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-0d7d4ba9
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.15.0-0d7d4ba9-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.15.0-0d7d4ba9-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-0d7d4ba9

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b398af8ccc99
---
<Actions>
<summary>Update to elastic/beats@b398af8ccc99</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b398af8ccc99&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9550000385">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@b398af8ccc99

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-0ad1343e
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.2-0ad1343e-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.2-0ad1343e-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-0ad1343e

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/8b197c8f1594
---
<Actions>
<summary>Update to elastic/beats@8b197c8f1594</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8b197c8f1594&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9567442935">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@8b197c8f1594

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/090ec6b342e7
---
<Actions>
<summary>Update to elastic/beats@090ec6b342e7</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 090ec6b342e7&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9567442935">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@090ec6b342e7

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-85d68b3b
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.2-85d68b3b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.2-85d68b3b-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-85d68b3b

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-72200925
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-72200925-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-72200925-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-72200925

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b1518d057809
---
<Actions>
<summary>Update to elastic/beats@b1518d057809</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b1518d057809&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9584261669">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@b1518d057809

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/2f10d0840326
---
<Actions>
<summary>Update to elastic/beats@2f10d0840326</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 2f10d0840326&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9584261669">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@2f10d0840326

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-b877ca2d
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.2-b877ca2d-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.2-b877ca2d-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-b877ca2d

.github/workflows/setup-cluster-env/action.yml
When I rolled out https://github.com/elastic/apm-server/pull/13441 I missed that the [vault github action created](https://github.com/elastic/apm-server/pull/13441/files#diff-1beedf873333c869b79a5ae9b868dde0123c9446f3483a2b113a0e9017d387f1L42) an environment variable called `AWS_PROFILE`. If not set then the smoke-tests fail.
```
Error: No valid credential sources found
with module.standalone_apm_server.provider["registry.terraform.io/hashicorp/aws"],
on ../../infra/terraform/modules/standalone_apm_server/provider.tf line 1, in provider "aws":
1: provider "aws" {
Please see https://registry.terraform.io/providers/hashicorp/aws
for more information about providing credentials.
Error: failed to refresh cached credentials, no EC2 IMDS role found,
operation error ec2imds: GetMetadata, failed …
```
=> github-actions: set AWS_PROFILE

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-d780a0f6-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9599832597">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-d780a0f6

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-ee48b214
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-ee48b214-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-ee48b214-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-ee48b214

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-d9e02e11
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.2-d9e02e11-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.2-d9e02e11-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-d9e02e11

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/44aeabb36206
---
<Actions>
<summary>Update to elastic/beats@44aeabb36206</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 44aeabb36206&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9599786420">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@44aeabb36206

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-93475c89
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-93475c89-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-93475c89-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-93475c89

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-36e48dc3
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.2-36e48dc3-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.2-36e48dc3-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-36e48dc3

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/99a6e8cf71e4
---
<Actions>
<summary>Update to elastic/beats@99a6e8cf71e4</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 99a6e8cf71e4&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9615672017">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@99a6e8cf71e4

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-802f0e3c
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.2-802f0e3c-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.2-802f0e3c-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-802f0e3c

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/40bfa06b9d60
---
<Actions>
<summary>Update to elastic/beats@40bfa06b9d60</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 40bfa06b9d60&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9647678386">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@40bfa06b9d60

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d2c4c2d7150c
---
<Actions>
<summary>Update to elastic/beats@d2c4c2d7150c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d2c4c2d7150c&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9647678386">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d2c4c2d7150c

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-021a3fba
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-021a3fba-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-021a3fba-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-021a3fba

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/5f64f090eea6
---
<Actions>
<summary>Update to elastic/beats@5f64f090eea6</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 5f64f090eea6&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9664866480">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@5f64f090eea6

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/14caf11a3a4e
---
<Actions>
<summary>Update to elastic/beats@14caf11a3a4e</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 14caf11a3a4e&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9664866480">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@14caf11a3a4e

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-d49753ad
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.2-d49753ad-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.2-d49753ad-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-d49753ad

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/c2b2983c1825
---
<Actions>
<summary>Update to elastic/beats@c2b2983c1825</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c2b2983c1825&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9682065062">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@c2b2983c1825

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/38b62b265182
---
<Actions>
<summary>Update to elastic/beats@38b62b265182</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 38b62b265182&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9682065062">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@38b62b265182

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-c0e0d013
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.15.0-c0e0d013-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.15.0-c0e0d013-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-c0e0d013

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-d7169439
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.2-d7169439-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.2-d7169439-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-d7169439

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-4ea59487-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9698991866">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-4ea59487

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-af44b0a5
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-af44b0a5-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-af44b0a5-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-af44b0a5

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-5c99b6cc
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.2-5c99b6cc-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.2-5c99b6cc-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-5c99b6cc

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/e1641ce57740
---
<Actions>
<summary>Update to elastic/beats@e1641ce57740</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e1641ce57740&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9698951545">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@e1641ce57740

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/8448a509433f
---
<Actions>
<summary>Update to elastic/beats@8448a509433f</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8448a509433f&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9698951545">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@8448a509433f

changelogs/8.14.asciidoc
=> 8.14.2: add release notes

.buildkite/hooks/pre-command
Use shared secrets in Buildkite. There are some other projects using it.
=> ci(buildkite): use shared secrets

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/cb0900496952
---
<Actions>
<summary>Update to elastic/beats@cb0900496952</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh cb0900496952&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9746556300">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@cb0900496952

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-770d7914
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.2-770d7914-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.2-770d7914-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-770d7914

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-5d6d1bc4
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-5d6d1bc4-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-5d6d1bc4-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-5d6d1bc4

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-2088c97b
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-2088c97b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-2088c97b-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-2088c97b

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-9786b1ff-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9763405961">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-9786b1ff

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-09792e49
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.2-09792e49-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.2-09792e49-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-09792e49

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/76a62ebf8946
---
<Actions>
<summary>Update to elastic/beats@76a62ebf8946</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 76a62ebf8946&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9763365586">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@76a62ebf8946

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/e9455e203842
---
<Actions>
<summary>Update to elastic/beats@e9455e203842</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e9455e203842&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9763365586">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@e9455e203842

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-3e9e1611-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9780292600">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-3e9e1611

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-0fc498d7
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.2-0fc498d7-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.2-0fc498d7-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-0fc498d7

cmd/intake-receiver/version.go, internal/version/version.go
=> 8.14.3: update versions

.ci/bump-golang.yml
The backports from main added a few go.mod files that were not needed. This is now reflecting what's actually in the 7.17 branch that it's potentially needed to be bumped with the automation.
=> updatecli(golang): update go.mod files to be bumped

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/c111789e3c61
---
<Actions>
<summary>Update to elastic/beats@c111789e3c61</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c111789e3c61&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9796502018">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@c111789e3c61

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/6517ed811b0e
---
<Actions>
<summary>Update to elastic/beats@6517ed811b0e</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6517ed811b0e&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9796502018">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@6517ed811b0e

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-1d1cdcd0-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9796532208">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-1d1cdcd0

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-90bfa704
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-90bfa704-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-90bfa704-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-90bfa704

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-d682129b
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.2-d682129b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.2-d682129b-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-d682129b

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/5a379fc1f3e0
---
<Actions>
<summary>Update to elastic/beats@5a379fc1f3e0</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 5a379fc1f3e0&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9796502018">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@5a379fc1f3e0

changelogs/8.14.asciidoc, changelogs/head.asciidoc
=> Add 8.14.3 Release Notes

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/31d3abd490ec
---
<Actions>
<summary>Update to elastic/beats@31d3abd490ec</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 31d3abd490ec&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9810209360">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@31d3abd490ec

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-af63ff6e
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.2-af63ff6e-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.2-af63ff6e-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-af63ff6e

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-010ec319-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9810241047">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-010ec319

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/9d3b98dd17fb
---
<Actions>
<summary>Update to elastic/beats@9d3b98dd17fb</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 9d3b98dd17fb&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9810209360">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@9d3b98dd17fb

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/6e97683404dd
---
<Actions>
<summary>Update to elastic/beats@6e97683404dd</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6e97683404dd&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9810209360">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@6e97683404dd

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/e40a406e6c42
---
<Actions>
<summary>Update to elastic/beats@e40a406e6c42</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e40a406e6c42&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9842003865">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@e40a406e6c42

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/85dbd4e62ba1
---
<Actions>
<summary>Update to elastic/beats@85dbd4e62ba1</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 85dbd4e62ba1&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9842003865">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@85dbd4e62ba1

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-8d3160b2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9842050892">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-8d3160b2

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/0c41eb73d556
---
<Actions>
<summary>Update to elastic/beats@0c41eb73d556</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 0c41eb73d556&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9842003865">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@0c41eb73d556

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.2-9ba1255f
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.2-9ba1255f-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.2-9ba1255f-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.2-9ba1255f

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-f9f83972-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9859491850">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-f9f83972

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/718199610453
---
<Actions>
<summary>Update to elastic/beats@718199610453</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 718199610453&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9859447458">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@718199610453

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/e1b593ffe820
---
<Actions>
<summary>Update to elastic/beats@e1b593ffe820</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e1b593ffe820&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9859447458">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@e1b593ffe820

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/032a4cfd5f3b
---
<Actions>
<summary>Update to elastic/beats@032a4cfd5f3b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 032a4cfd5f3b&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9859447458">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@032a4cfd5f3b

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.3-33f59ad2
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.3-33f59ad2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.3-33f59ad2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.3-33f59ad2

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-e9b4a2f9
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-e9b4a2f9-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-e9b4a2f9-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-e9b4a2f9

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-1a386dd5
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-1a386dd5-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-1a386dd5-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-1a386dd5

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-a9f3d4e7
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-a9f3d4e7-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-a9f3d4e7-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-a9f3d4e7

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.3-95e002dd
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.3-95e002dd-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.3-95e002dd-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.3-95e002dd

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/84836ea25463
---
<Actions>
<summary>Update to elastic/beats@84836ea25463</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 84836ea25463&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9876634575">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@84836ea25463

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/fda578f25ee8
---
<Actions>
<summary>Update to elastic/beats@fda578f25ee8</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh fda578f25ee8&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9876634575">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@fda578f25ee8

changelogs/8.14.asciidoc
8.14 changelog was broken due to formatting.
=> Fix 8.14 broken changelog

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/c3712b5956a8
---
<Actions>
<summary>Update to elastic/beats@c3712b5956a8</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c3712b5956a8&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9893795773">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@c3712b5956a8

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/7b35a7a5de93
---
<Actions>
<summary>Update to elastic/beats@7b35a7a5de93</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 7b35a7a5de93&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9893795773">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@7b35a7a5de93

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-8e262a3b
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-8e262a3b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-8e262a3b-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-8e262a3b

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.3-7222297b
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.3-7222297b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.3-7222297b-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.3-7222297b

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-0493bc2f-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9893836278">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-0493bc2f

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/ab1fdd368655
---
<Actions>
<summary>Update to elastic/beats@ab1fdd368655</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ab1fdd368655&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9909935291">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@ab1fdd368655

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-9cf398b8
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-9cf398b8-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-9cf398b8-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-9cf398b8

changelogs/8.15.asciidoc
Update link as 8.14.3 is released
=> Update 8.15 changelog diff link

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-14c86b06-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9909975320">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-14c86b06

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.4-5d9afc5f
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.4-5d9afc5f-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.4-5d9afc5f-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.4-5d9afc5f

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/aa5ec880ee71
---
<Actions>
<summary>Update to elastic/beats@aa5ec880ee71</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh aa5ec880ee71&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9909935291">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@aa5ec880ee71

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/5671cff8d143
---
<Actions>
<summary>Update to elastic/beats@5671cff8d143</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 5671cff8d143&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9909935291">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@5671cff8d143

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-892b6545
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-892b6545-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-892b6545-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-892b6545

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b3d0f3a78e5f
---
<Actions>
<summary>Update to elastic/beats@b3d0f3a78e5f</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b3d0f3a78e5f&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9941773448">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@b3d0f3a78e5f

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-e3a177e8-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9941821463">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-e3a177e8

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-70355f19
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-70355f19-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-70355f19-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-70355f19

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.4-ddd05c32
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.4-ddd05c32-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.4-ddd05c32-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.4-ddd05c32

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d6a8214de877
---
<Actions>
<summary>Update to elastic/beats@d6a8214de877</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d6a8214de877&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9941773448">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d6a8214de877

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/9ada51321919
---
<Actions>
<summary>Update to elastic/beats@9ada51321919</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 9ada51321919&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9959284469">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@9ada51321919

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d40a9e372858
---
<Actions>
<summary>Update to elastic/beats@d40a9e372858</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d40a9e372858&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9959284469">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d40a9e372858

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-d7bef85f
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-d7bef85f-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-d7bef85f-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-d7bef85f

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-bc431a00
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-bc431a00-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-bc431a00-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-bc431a00

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/cf49dc686fd0
---
<Actions>
<summary>Update to elastic/beats@cf49dc686fd0</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh cf49dc686fd0&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9959284469">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@cf49dc686fd0

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-3619a002-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9976675013">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-3619a002

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.4-cf4f2f99
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.4-cf4f2f99-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.4-cf4f2f99-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.4-cf4f2f99

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/4301c0a260aa
---
<Actions>
<summary>Update to elastic/beats@4301c0a260aa</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 4301c0a260aa&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9976624704">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@4301c0a260aa

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/8af2d57dac1c
---
<Actions>
<summary>Update to elastic/beats@8af2d57dac1c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8af2d57dac1c&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9976624704">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@8af2d57dac1c

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/d7449ebc87c2
---
<Actions>
<summary>Update to elastic/beats@d7449ebc87c2</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d7449ebc87c2&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9976624704">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@d7449ebc87c2

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/4e040097aa02
---
<Actions>
<summary>Update to elastic/beats@4e040097aa02</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 4e040097aa02&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9993894346">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@4e040097aa02

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/942f8c78573d
---
<Actions>
<summary>Update to elastic/beats@942f8c78573d</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 942f8c78573d&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9993894346">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@942f8c78573d

changelogs/8.14.asciidoc
=> docs: Tidy up 8.14 changelog

.buildkite/scripts/dra.sh, .buildkite/scripts/package.sh
I don't know what changed and it's being discussed internally.
But in the last successful run the build artifacts had following permissions:
```
-rw-rw-r-- 1 buildkite-agent ubuntu 25456161 Jul 17 17:40 apm-server-8.16.0-SNAPSHOT-aarch64.rpm
-rw-rw-r-- 1 buildkite-agent ubuntu 26256320 Jul 17 17:40 apm-server-8.16.0-SNAPSHOT-amd64.deb
-rw-rw-r-- 1 buildkite-agent ubuntu 24761842 Jul 17 17:40 apm-server-8.16.0-SNAPSHOT-arm64.deb
```
In the failing pipeline the permissions are:
```
-rw------- 1 buildkite-agent ubuntu 25510473 Jul 19 09:31 apm-server-8.16.0-SNAPSHOT-aarch64.rpm
-rw------- 1 buildkite-agent ubuntu 26255148 Jul 19 09:31 apm-server-8.16.0-SNAPSHOT-amd64.deb
-rw------- 1 buildkite-agent ubuntu 24761630 Jul 19 09:31 apm-server-8.16.0-SNAPSHOT-arm64.deb
```
This should change the …
=> DRA: fix permissions of build artifacts

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/1067b6c812cc
---
<Actions>
<summary>Update to elastic/beats@1067b6c812cc</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 1067b6c812cc&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/9993894346">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@1067b6c812cc

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/f3f772f6fe47
---
<Actions>
<summary>Update to elastic/beats@f3f772f6fe47</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh f3f772f6fe47&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10010120410">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@f3f772f6fe47

.buildkite/scripts/dra.sh
This can be removed again since the release of https://github.com/buildkite/agent/releases/tag/v3.75.1
=> DRA: Remove custom chmod

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.4-d0f2f673
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.4-d0f2f673-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.4-d0f2f673-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.4-d0f2f673

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-bc7f8bf6
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-bc7f8bf6-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-bc7f8bf6-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-bc7f8bf6

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-b31336e2
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-b31336e2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-b31336e2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-b31336e2

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-45566d1b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10061411823">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-45566d1b

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/dd671a6bcefb
---
<Actions>
<summary>Update to elastic/beats@dd671a6bcefb</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh dd671a6bcefb&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10061364932">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@dd671a6bcefb

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/dedfdc679e5b
---
<Actions>
<summary>Update to elastic/beats@dedfdc679e5b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh dedfdc679e5b&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10061364932">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@dedfdc679e5b

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.4-83a5d94e
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.4-83a5d94e-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.4-83a5d94e-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.4-83a5d94e

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-81e2e343-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10079139328">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-81e2e343

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-38912362
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-38912362-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-38912362-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-38912362

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-bc3d3719
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-bc3d3719-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-bc3d3719-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-bc3d3719

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/a9b85ce4631c
---
<Actions>
<summary>Update to elastic/beats@a9b85ce4631c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a9b85ce4631c&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10079092025">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@a9b85ce4631c

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/bce3b66cc8d9
---
<Actions>
<summary>Update to elastic/beats@bce3b66cc8d9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh bce3b66cc8d9&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10079092025">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@bce3b66cc8d9

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/5541971cc328
---
<Actions>
<summary>Update to elastic/beats@5541971cc328</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 5541971cc328&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10079092025">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@5541971cc328

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-9f5437f6
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-9f5437f6-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-9f5437f6-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-9f5437f6

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.4-6e08fc48
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.4-6e08fc48-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.4-6e08fc48-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.4-6e08fc48

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/e132ee9bdcfe
---
<Actions>
<summary>Update to elastic/beats@e132ee9bdcfe</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e132ee9bdcfe&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10096526408">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@e132ee9bdcfe

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-b3f8815c
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-b3f8815c-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-b3f8815c-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-b3f8815c

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.4-0a05d857
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.4-0a05d857-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.4-0a05d857-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.4-0a05d857

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-e485f1da
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-e485f1da-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-e485f1da-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-e485f1da

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-fdd97b45-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10113401627">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-fdd97b45

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/ad46ac5a34f6
---
<Actions>
<summary>Update to elastic/beats@ad46ac5a34f6</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ad46ac5a34f6&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10113360500">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@ad46ac5a34f6

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/8d3e96db92c8
---
<Actions>
<summary>Update to elastic/beats@8d3e96db92c8</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8d3e96db92c8&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10113360500">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@8d3e96db92c8

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-4647f73c
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.16.0-4647f73c-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.16.0-4647f73c-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-4647f73c

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-4b70dfd2
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-4b70dfd2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-4b70dfd2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-4b70dfd2

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/083f1dd3bc73
---
<Actions>
<summary>Update to elastic/beats@083f1dd3bc73</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 083f1dd3bc73&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10146769946">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@083f1dd3bc73

.github/workflows/update-dependabot-pr.yml
The script did not work because workflow steps are running with `-e` by default.
hence, the result cannot be captured with `$?`. 
Using subshell instead
=> dependbot: fix diff script

.github/workflows/update-dependabot-pr.yml
The previous fix did not work at https://github.com/elastic/apm-server/pull/13788.
The result was not captured correctly.
=> dependabot: fix diff script pt2

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/a4b0924467d3
---
<Actions>
<summary>Update to elastic/beats@a4b0924467d3</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a4b0924467d3&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10146769946">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@a4b0924467d3

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.23-26ee1cc2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10164848061">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.23-26ee1cc2

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.4-123956a8
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.4-123956a8-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.4-123956a8-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.4-123956a8

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-f0a5ddba
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.15.0-f0a5ddba-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.15.0-f0a5ddba-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-f0a5ddba

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-87b4ddb2
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-87b4ddb2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-87b4ddb2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-87b4ddb2

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/e5f17f983f8c
---
<Actions>
<summary>Update to elastic/beats@e5f17f983f8c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e5f17f983f8c&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10164806876">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@e5f17f983f8c

apmpackage/apm/changelog.yml, apmpackage/apm/manifest.yml, changelogs/7.17.asciidoc, cmd/version.go
=> Add 7.17.23 release notes and bump to 7.17.24

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-9491ea27
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-9491ea27-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-9491ea27-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-9491ea27

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-2a2d3093
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.16.0-2a2d3093-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.16.0-2a2d3093-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-2a2d3093

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/5bca5a133c69
---
<Actions>
<summary>Update to elastic/beats@5bca5a133c69</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 5bca5a133c69&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10182676773">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@5bca5a133c69

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/edf66a507cb2
---
<Actions>
<summary>Update to elastic/beats@edf66a507cb2</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh edf66a507cb2&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10182676773">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@edf66a507cb2

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.4-801c0969
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.4-801c0969-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.4-801c0969-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.4-801c0969

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-73e9a660
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-73e9a660-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-73e9a660-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-73e9a660

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/640f2de34ef6
---
<Actions>
<summary>Update to elastic/beats@640f2de34ef6</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 640f2de34ef6&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10200755029">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@640f2de34ef6

.github/workflows/ci.yml, systemtest/containers.go, testing/stack-monitoring.sh
=> Migrate docker-compose to docker compose

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/cd7285b6b8ae
---
<Actions>
<summary>Update to elastic/beats@cd7285b6b8ae</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh cd7285b6b8ae&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10217714289">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@cd7285b6b8ae

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.4-fc0488b9
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.4-fc0488b9-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.4-fc0488b9-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.4-fc0488b9

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-697eb961
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-697eb961-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-697eb961-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-697eb961

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/5d591f644b08
---
<Actions>
<summary>Update to elastic/beats@5d591f644b08</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 5d591f644b08&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10251205582">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@5d591f644b08

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/744485afb15b
---
<Actions>
<summary>Update to elastic/beats@744485afb15b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 744485afb15b&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10251205582">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@744485afb15b

.github/workflows/update-dependabot-pr.yml
In cases where the main branch was merged into the dependabot branch, the previous diff command would suggest that there is a diff even if there wasn't.
This should fix it. 🤞 
=> dependabot: fix command to determine the diff

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/07c6c949be84
---
<Actions>
<summary>Update to elastic/beats@07c6c949be84</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 07c6c949be84&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10268986009">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@07c6c949be84

changelogs/8.15.asciidoc
=> changelog: apm-aggregation labels bug

.github/workflows/update-dependabot-pr.yml
The workflow keeps creating empty commits. 
- Do a more explicit comparison in the if statement
- and add some debug output
=> dependabot: compare to actual output value and add debug step

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/fada07251b70
---
<Actions>
<summary>Update to elastic/beats@fada07251b70</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh fada07251b70&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10304538620">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@fada07251b70

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-47fa2a49
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.16.0-47fa2a49-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.16.0-47fa2a49-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-47fa2a49

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.0-5b8c47c1
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.0-5b8c47c1-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.0-5b8c47c1-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.0-5b8c47c1

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.4-3a06015a
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.14.4-3a06015a-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.14.4-3a06015a-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.4-3a06015a

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/f170d884096e
---
<Actions>
<summary>Update to elastic/beats@f170d884096e</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh f170d884096e&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10321369438">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@f170d884096e

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.14.4-41737d57
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.14.4-41737d57-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.14.4-41737d57-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.14.4-41737d57

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/cebcf1bbfeac
---
<Actions>
<summary>Update to elastic/beats@cebcf1bbfeac</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh cebcf1bbfeac&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10354347802">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@cebcf1bbfeac

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/94081ab34a69
---
<Actions>
<summary>Update to elastic/beats@94081ab34a69</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 94081ab34a69&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10354347802">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@94081ab34a69

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.1-95cb44ee
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.1-95cb44ee-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.1-95cb44ee-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.1-95cb44ee

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/79206dd8c1cd
---
<Actions>
<summary>Update to elastic/beats@79206dd8c1cd</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 79206dd8c1cd&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10372214622">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@79206dd8c1cd

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/85d1ec816568
---
<Actions>
<summary>Update to elastic/beats@85d1ec816568</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 85d1ec816568&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10390036463">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@85d1ec816568

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.1-292be5eb
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.1-292be5eb-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.1-292be5eb-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.1-292be5eb

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/f9a9369bc972
---
<Actions>
<summary>Update to elastic/beats@f9a9369bc972</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh f9a9369bc972&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10405855049">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@f9a9369bc972

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-fe676ba3
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-fe676ba3-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-fe676ba3-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-fe676ba3

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.1-ce14508c
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.1-ce14508c-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.1-ce14508c-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.1-ce14508c

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/531a97acfaf9
---
<Actions>
<summary>Update to elastic/beats@531a97acfaf9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 531a97acfaf9&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10421988734">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@531a97acfaf9

changelogs/8.14.asciidoc
There are extra lines in 8.14 changelog in 8.15 branch. Align it with the version in 8.14 and main.
=> [8.15] Fix broken 8.14 release notes

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/b9bfe1a7fbb3
---
<Actions>
<summary>Update to elastic/beats@b9bfe1a7fbb3</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b9bfe1a7fbb3&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10455822609">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@b9bfe1a7fbb3

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.1-d2032aa6
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.1-d2032aa6-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.1-d2032aa6-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.1-d2032aa6

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.1-2c141eda
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.1-2c141eda-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.1-2c141eda-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.1-2c141eda

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-233f996e
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.16.0-233f996e-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.16.0-233f996e-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-233f996e

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.1-379d17a0
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.1-379d17a0-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.1-379d17a0-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.1-379d17a0

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.24-e0c98212-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10492391598">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.24-e0c98212

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/60a2462c109c
---
<Actions>
<summary>Update to elastic/beats@60a2462c109c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 60a2462c109c&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10492349732">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@60a2462c109c

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.1-18f0c058
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.1-18f0c058-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.1-18f0c058-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.1-18f0c058

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-368aa682
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-368aa682-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-368aa682-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-368aa682

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/88c39ef43407
---
<Actions>
<summary>Update to elastic/beats@88c39ef43407</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 88c39ef43407&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10510607235">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@88c39ef43407

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/e09627fb5672
---
<Actions>
<summary>Update to elastic/beats@e09627fb5672</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e09627fb5672&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10510607235">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@e09627fb5672

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/e64ea44140d4
---
<Actions>
<summary>Update to elastic/beats@e64ea44140d4</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e64ea44140d4&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10527904442">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@e64ea44140d4

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.1-aba8b96c
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.15.1-aba8b96c-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.15.1-aba8b96c-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.1-aba8b96c

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.24-b1f4ff18-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10527943022">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.24-b1f4ff18

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/35a23d167b03
---
<Actions>
<summary>Update to elastic/beats@35a23d167b03</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 35a23d167b03&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10527904442">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@35a23d167b03

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-07587139
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-07587139-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-07587139-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-07587139

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-c5bcaeae
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-c5bcaeae-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-c5bcaeae-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-c5bcaeae

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.24-e395ff83-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10562201252">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.24-e395ff83

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/96b136a54066
---
<Actions>
<summary>Update to elastic/beats@96b136a54066</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 96b136a54066&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10562163709">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@96b136a54066

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.1-16cafb68
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.1-16cafb68-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.1-16cafb68-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.1-16cafb68

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-e5ab468c
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-e5ab468c-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-e5ab468c-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-e5ab468c

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.1-35befaba
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.1-35befaba-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.1-35befaba-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.1-35befaba

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-32bc94b7
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.16.0-32bc94b7-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.16.0-32bc94b7-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-32bc94b7

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.24-5417cd4d-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10599317329">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.24-5417cd4d

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.1-6ed69fc1
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.15.1-6ed69fc1-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.15.1-6ed69fc1-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.1-6ed69fc1

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.24-2d3bfa51-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10617652921">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.24-2d3bfa51

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.24-f6cb7d65-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10634901055">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.24-f6cb7d65

changelogs/8.15.asciidoc
Update changelog for 8.15.1 release.
=> changelog: add 8.15.1 entry

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.1-e010ad04
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.1-e010ad04-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.1-e010ad04-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.1-e010ad04

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-a3caaa65
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-a3caaa65-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-a3caaa65-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-a3caaa65

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.24-bb129799-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10669474671">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.24-bb129799

.github/workflows/bump-elastic-stack.yml, .github/workflows/bump-golang.yml, .github/workflows/check-docker-compose.yml, .github/workflows/smoke-tests-schedule.yml, .github/workflows/update-beats.yml
https://github.com/elastic/apm-pipeline-library/ is a deprecated repository and https://github.com/elastic/oblt-actions is the replacement.
=> github-actions: replace apm-pipeline-library actions for oblt-actions

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.24-5ffd9a45-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10685547845">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.24-5ffd9a45

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.1-67154674
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.1-67154674-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.1-67154674-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.1-67154674

cmd/intake-receiver/version.go, internal/version/version.go
Merge on request by the Release Manager.
=> 8.15.2: update versions

.ci/updatecli/values.d/scm.yml, updatecli-compose.yaml
<Actions>
<action id="90caa11f1dfddabddc2561998db84e0a9fc2d8c911a7910ab7307126e776be9f">
<h3>deps(updatecli/policy): bump &#34;ghcr.io/updatecli/policies/autodiscovery/updatecli&#34; Updatecli policy version</h3>
<details id="db669af634b75c7f298400f3b6c2aa8ba54998bac83e23d10ab4eaadc4b50ccf">
<summary>deps(updatecli/policy): bump &#34;ghcr.io/updatecli/policies/autodiscovery/updatecli&#34; Updatecli version policy</summary>
<p>change detected:&#xA;&#x9;* key &#34;$.policies[1].policy&#34; updated from &#34;ghcr.io/updatecli/policies/autodiscovery/updatecli:0.4.0@sha256:254367f5b1454fd6032b88b314450cd3b6d5e8d5b6c953eb242a6464105eb869&#34; to &#34;ghcr.io/updatecli/policies/autodiscovery/updatecli:0.5.0@sha256:df7fb3a9e3348a9749527edf867be1090f452f9ee0c2116aab6de39729850d53&#34;, in file …
=> deps(updatecli): bump all policies

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.24-f8a360d9-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10723006627">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.24-f8a360d9

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.2-e26b3970
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.2-e26b3970-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.2-e26b3970-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.2-e26b3970

CHANGELOG.asciidoc
Add back missing 8.15 changelog link
=> docs: Add back missing 8.15 changelog link

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.2-72deec01
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.2-72deec01-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.2-72deec01-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.2-72deec01

changelogs/7.17.asciidoc
=> changelod: add release notes for 7.17.24

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.25-84dcbf3c-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10814338669">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.25-84dcbf3c

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.2-c56c9001
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.2-c56c9001-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.2-c56c9001-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.2-c56c9001

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-2156c99d
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-2156c99d-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-2156c99d-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-2156c99d

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-bff94f3c
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.16.0-bff94f3c-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.16.0-bff94f3c-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-bff94f3c

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.25-2af1904e-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10833513711">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.25-2af1904e

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.2-eb081dc9
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.15.2-eb081dc9-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.15.2-eb081dc9-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.2-eb081dc9

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 9.0.0-5fdca544
---
<Actions>
<p>1 file(s) updated with &#34;$1:9.0.0-5fdca544-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 9.0.0-5fdca544-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 9.0.0-5fdca544

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-c6f183db
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.16.0-c6f183db-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.16.0-c6f183db-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-c6f183db

docker-compose.yml
<Actions>
<p>1 file(s) updated with &#34;$1:7.17.25-0a21543d-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10851486829">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Bump elastic stack version to 7.17.25-0a21543d

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.15.2-7f2cd899
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.15.2-7f2cd899-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.15.2-7f2cd899-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.15.2-7f2cd899

NOTICE.txt, go.mod, go.sum
*Changeset*
* https://github.com/elastic/beats/commit/29ccd4834f6c
---
<Actions>
<summary>Update to elastic/beats@29ccd4834f6c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 29ccd4834f6c&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/10886498802">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
=> [updatecli] Update to elastic/beats@29ccd4834f6c

docker-compose.yml, testing/infra/k8s/base/stack/apm-server.yaml, testing/infra/k8s/base/stack/elasticsearch.yaml, testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.16.0-874a7f05
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.16.0-874a7f05-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.16.0-874a7f05-SNAPSHOT&#34;:&#xA;&#x9;* …
=> [updatecli] Bump elastic stack version to 8.16.0-874a7f05

cmd/intake-receiver/version.go, internal/version/version.go
Merge on request by the Release Manager.
=> 8.15.3: update versions

changelogs/8.15.asciidoc
Update changelog for 8.15.2 release
=> changelog: 8.15.2 release

.github/workflows/add-to-docs-project.yml, .github/workflows/add-to-project.yml
No more finer-grained tokens but ephemeral tokens using a GH app
=> github-actions: use ephemeral tokens

Makefile, NOTICE.txt, go.mod, go.sum, internal/beatcmd/beat.go, internal/beatcmd/beat_test.go, internal/beatcmd/reloader.go, internal/beatcmd/reloader_test.go, internal/beater/beater_test.go, internal/beater/middleware/log_middleware.go, systemtest/monitoring_test.go, x-pack/apm-server/main.go, x-pack/apm-server/sampling/eventstorage/sharded_bench_test.go, x-pack/apm-server/sampling/eventstorage/storage_bench_test.go, x-pack/apm-server/sampling/eventstorage/storage_test.go, x-pack/apm-server/sampling/eventstorage/storage_whitebox_test.go, x-pack/apm-server/sampling/groups_test.go, x-pack/apm-server/sampling/processor_test.go, x-pack/apm-server/sampling/pubsub/pubsub_integration_test.go, x-pack/apm-server/sampling/pubsub/pubsub_test.go
Alternative to #14308
This reverts commit 7f85cd62d082b4ebfed9b43e753e926d59bd6e08.
Unblock https://github.com/elastic/apm-server/pull/14292 to fix https://github.com/elastic/apm-server/issues/14280. Reverting beats instead of
bumping beats to avoid https://github.com/elastic/apm-server/issues/14297. 
=> [8.x] Revert "feat: bump beats to latest 8.x commit (#14147)"

.mergify.yml
https://github.com/elastic/apm-server/pull/14392 will be the one addressing this type of PRs in the future, but meanwhile I created manually
=> mergify: add 8.16

changelogs/8.16.asciidoc
Add changelog entry for 8.16.1 release.
=> changelog: add changelog entry for 8.16.1

changelogs/8.15.asciidoc
=> changelog: add 8.15.5 entry

changelogs/7.17.asciidoc
Add changelog entry for 7.17.26 release
=> release: add changelog entry for 7.17.26

.mergify.yml
Enable backports for the 8.17 label
=> Add 8.17 to .mergify.yml

apmpackage/apm/changelog.yml, apmpackage/apm/manifest.yml, cmd/version.go
=> 7.17.27: update docs

.ci/scripts/bench.sh
* `g` installation uses https://raw.githubusercontent.com/stefanmaric/g/master/bin/install so it's not reproducible.
* `g` has not had any changes for over a year.
* https://github.com/andrewkroh/gvm/ is maintained and developed by Andrew who works at Elastic.
* https://github.com/andrewkroh/gvm/ is also used in other [places](https://github.com/elastic/apm-server/blob/2836114958d844c9862a63ea752a253399a505da/.buildkite/hooks/pre-command#L95-L106) for quite some time.
* Add retries so we can reduce the environmental issues we have faced when installing golang
- Have system tests been added to avoid …
=> ci(microbenchmark): use gvm instead of g with retries

changelogs/8.17.asciidoc
=> changelog: update missing 8.17 release notes

changelogs/8.17.asciidoc
=> changelog: update missing entry

changelogs/8.17.asciidoc
This PR manually coppies 8.17 changelogs into main branch, which was not created by the automation.
=> changelog: add 8.17 release notes to main

changelogs/8.17.asciidoc
This PR adds clarification to 8.17.0 release notes with regards to lifecycle management changes.
=> changelog: clarify lifecycle management 8.17.0 release notes

docs/spec/v2/span.json, systemtest/approvals/TestOTLPGRPCLogsClientIP.approved.json
Fix failing TestOTLPGRPCLogsClientIP test due to geoip changes
=> test: Fix failing TestOTLPGRPCLogsClientIP due to geoip

.github/workflows/benchmarks.yml
Fixes unexpected slowness (see https://github.com/elastic/apm-server/actions/runs/12845859205)
```
botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.
```
```
│ Error: configuring Terraform AWS Provider: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: 965f3755-14db-4dd7-b50c-c51ae59aa85b, api error ExpiredToken: The security token included in the request is expired
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 41, in provider "aws":
│   41: provider "aws" {
│ 
╵
make: *** [Makefile:96: destroy] Error 1
```
- Is it observable …
=> ci(benchmarks): increase role-duration AWS

testing/infra/terraform/modules/ec_deployment/outputs.tf
Chomp new line chars from the secret token file content introduced in https://github.com/elastic/apm-server/pull/15218.
https://github.com/elastic/apm-server/pull/15218
=> benchmarks: chopm apm_secret_token

.github/workflows/benchmarks.yml, .github/workflows/smoke-tests-ess.yml, .github/workflows/smoke-tests-os.yml, testing/infra/terraform/modules/ec_deployment/deployment.tf, testing/smoke/managed/main.tf, testing/smoke/supported-os/main.tf
Ubuntu latest GHA runner no longer comes with preinstalled terraform [see](https://github.com/elastic/apm-server/blob/main/.github/workflows/smoke-tests-os.yml#L24), so it has to be explicitly installed. This should resolve the failure of smoke-tests CI pipeline like [here](https://github.com/elastic/apm-server/actions/runs/12921469899).
=> smoke tests: setup tf action explicitly

testing/benchmark/main.tf, testing/infra/terraform/modules/moxy/main.tf, testing/infra/terraform/modules/moxy/variables.tf, testing/infra/terraform/modules/standalone_apm_server/main.tf, testing/infra/terraform/modules/standalone_apm_server/variables.tf, testing/smoke/managed/main.tf, testing/smoke/supported-os/main.tf
This PR reverts changes made in https://github.com/elastic/apm-server/pull/15078 which are causing the issues for smoke-tests pipeline https://github.com/elastic/apm-server/actions/runs/12937104670/job/36084296766#step:9:50. Making the tags be explicitly propagated in both benchmarks and smoke-tests pipelines again.
=> TF: restore explicit tags for apm_standalone module

internal/agentcfg/elasticsearch.go, internal/sourcemap/metadata_fetcher.go
clearscroll log should use Warnf instead of Warn.
=> Fix clearscroll request fmt string

changelogs/8.18.asciidoc
Remove an incorrect entry from 8.18 changelog. Pebble PR is not backported to any 8.x branch.
=> docs: Remove incorrect entry in 8.18 changelog

functionaltests/internal/ecclient/client.go
A minor change to link to the correct API being used to trigger restarts in Elastic Cloud.
=> functionaltests: document restart API

.github/workflows/functional-tests.yml
To prevent spamming our report channel, temporary disable notify step. Even if we are running this in separate branches, the workflow runs with the file present on `main` branch.
=> functionaltests: disable notify

changelogs/7.17.asciidoc
Add entry for 7.17.28 changelog.
=> changelog: add entry for 7.17.28

apmpackage/apm/changelog.yml, apmpackage/apm/manifest.yml, cmd/version.go
=> docs: update docs versions to 7.17.29

.github/workflows/smoke-tests-ess.yml
Run smoke-test-ess for 8.16 and 8.17 as we support 2 minors.
Part of #15844
=> Run smoke-tests-ess for 8.16 and 8.17

functionaltests/8_15_test.go, functionaltests/internal/esclient/client.go, functionaltests/internal/kbclient/client.go, functionaltests/utils_test.go
Functional tests failing due to ignored error.
Run functional test to verify.
=> functionaltest: Fix ignored error

changelogs/8.16.asciidoc
Add entry for 8.16.5 changelog.
=> changelog: add 8.16.5 entry

changelogs/8.17.asciidoc
Add entry for 8.17.3 changelog.
=> changelog: add 8.17.3 changelog entry

testing/smoke/supported-os/test.sh, testing/smoke/test_supported_os.sh
=> Fix Mergify/BP/8.16/PR-16035

changelogs/8.16.asciidoc
Add changelog entry for 8.16.6 release
=> changelog: add entry for 8.16.6

changelogs/8.17.asciidoc
=> changelog: add entry for 8.17.4

functionaltests/internal/esclient/client.go
Closes https://github.com/elastic/apm-server/issues/16372.
Run functionaltests with this branch: https://github.com/elastic/apm-server/actions/runs/14036537749.
=> functionaltests: Fix error logs query

changelogs/8.18.asciidoc
Add changelog for #16385. This PR should be backported to 8.18.
=> docs: Add changelog for drop and recreate badger mitigation bugfix

.github/workflows/docs-build.yml, .github/workflows/docs-cleanup.yml
We trust the elastic GH actions, and that can help us to ship new features faster
=> deps(gh-actions): use main for the elastic gh actions

changelogs/8.17.asciidoc
=> changelogs: add entry for 8.17.5

catalog-info.yaml
Run `7.17` DRA weekly to catch any breaking changes in the Unified Release before any releases.
- Run weekly instead of daily?
=> catalog-info: run 7.17 DRA weekly

changelogs/8.17.asciidoc
Make TBS drop loop bugfix changelog entry in 8.17.5 consistent with 8.18.0 one.
=> changelog: consistent entry for TBS drop loop fix in 8.17.5

cmd/intake-receiver/go.mod, functionaltests/go.mod, go.mod, systemtest/go.mod
=> bump golang to 1.24.2

docs/release-notes/index.md
- Add 9.0.1 changelog
- Change changelog id structure according to https://github.com/elastic/docs-content/issues/1152
=> changelog: add entry for 9.0.1

changelogs/8.18.asciidoc
Add changelog entry for 8.18.1 release.
=> changelog: add entry for 8.18.1

changelogs/8.18.asciidoc
Add changelog entry for upcoming 8.18.2 release
=> changelog: add entry for 8.18.2

.github/workflows/benchmarks-matrix.yml, .github/workflows/benchmarks.yml
- Add ESS region as `benchmarks` workflow input
- Add new workflow `benchmarks-matrix` to run `benchmarks` workflow from a matrix
=> ci: Add ESS region as benchmarks input, Add benchmarks matrix workflow

docs/release-notes/index.md
Update 9.0.3 release notes.
Merge after approval.
=> 9.0.3: update release notes

cmd/intake-receiver/version.go, internal/version/version.go
workflow wasn't run so do it manually
=> feat(9.0): bump version to 9.0.4

changelogs/8.17.asciidoc
Retroactively added missing 8.17.8 entry
=> Add 8.17.9 changelog entry

CHANGELOG.asciidoc, changelogs/8.19.asciidoc, changelogs/head.asciidoc
Add 8.19.0 release notes derived from https://github.com/elastic/apm-server/issues/17358
=> doc: add 8.19 changelog

docs/release-notes/known-issues.md
Update 9.1.0 and 8.19.0 unreachable APM Integration known issue post RCA in #17967
=> docs: Update 9.1 unreachable APM Integration known issues

integrationservertest/internal/gen/generator.go
Closes https://github.com/elastic/apm-server/issues/17703
Run workflow: https://github.com/elastic/apm-server/actions/runs/16796276535
=> iserver-test: Revert temp fix for fleet server issue

changelogs/8.19.asciidoc
A more user friendly description of the change in #17872
=> changelog: Update 8.19.1 entry

changelogs/8.19.asciidoc
=> Changelog: Add entry for 8.19.2 release

docs/release-notes/index.md
=> Changelog: Add notes for 9.1.2 release

docs/release-notes/index.md
Add missing changelog discovered in #18092
=> changelog: Add ca bundle change to 9.1.0

changelogs/8.19.asciidoc
Add missing changelog discovered in #18092
=> changelog: Add ca bundle change in 8.19.0

changelogs/8.18.asciidoc
Add missing changelog discovered in #18092
=> changelog: Add ca bundle change in 8.18.1

docs/release-notes/index.md
Release notes for 9.0.6 and missing 9.0.5.
=> add release notes 9.0.6

cmd/intake-receiver/version.go, internal/version/version.go
=> 9.1: Update version

changelogs/8.18.asciidoc
v8.18.6 changelog based on https://github.com/elastic/apm-server/compare/v8.18.5...8.18
=> Add changelog for v8.18.6

changelogs/8.18.asciidoc, changelogs/head.asciidoc
Add 8.18.8 release notes
https://github.com/elastic/apm-server/compare/v8.12.0...v8.12.1
=> changelog: Add 8.18.8 release notes

.github/workflows/integration-server-test.yml
Otherwise it won't report correctly the error if something goes wrong with preparing the context
=> ci: report failures if prepare job failed

docs/release-notes/index.md
Add release notes for the 9.1.5 patch release
=> Changelog: Add 9.1.5 release notes

docs/release-notes/deprecations.md, docs/release-notes/index.md
Update changelog for the 9.0.8.
=> changelog: add 9.0.8 and 9.0.7 release notes

cmd/intake-receiver/version.go, internal/version/version.go
As part of releasing `9.1.5` bump up the `9.1` branch to the next patch, `9.1.6`.
N/A
N/A
=> Bump up 9.1 branch to 9.1.6

cmd/intake-receiver/version.go, internal/version/version.go
As part of releasing `9.0.8` bump up the `9.0` branch to the next patch, `9.0.9`.
N/A
N/A
=> Bump up 9.0 branch to 9.0.9
