Jenkinsfile
- @jalvz spotted the current name of the stage and GitHub check might cause some confusion as the apm-server uses ITs too.
=> ci(jenkins): rename APM ITs to avoid any misleading

Makefile
Since we only backport bugfixes to 7.3, the code base differs to master.
=> Fix golint

Jenkinsfile
- GIT_SHA contains the git merge commit therefore it does not exist in the upstream repo.
- GIT_BASE_COMMIT contains the git commit from the upstream repo.
=> ci(jenkins): Fix environment variable used to calculate git commit

.ci/check-changelogs.groovy, Jenkinsfile
This reverts https://github.com/elastic/apm-server/pull/2633 and https://github.com/elastic/apm-server/pull/2617
- As long as we use the share step `gitCheckout` we might need to use the agent top-level to share the env variables between stages.
- It's not ideal but even though the changes were quite straight, its behavior was not as expected. 
- Let's keep the pipeline stable for now and we will figure out what's going on.
=> ci(jenkins): revert none agent

LICENSE.txt
- Update license text for repo.  (#2636)
=> [7.x] Update license text for repo. (#2636)

Jenkinsfile, script/jenkins/linux-test.sh, script/jenkins/unit-test.sh, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_integration.py, tests/system/test_integration_acm.py, tests/system/test_pipelines.py, tests/system/test_requests.py, tests/system/test_setup_index_management.py
This change reduces `INTEGRATION_TESTS=1 make system-tests` from ~8:30 mins on my machine to ~4:30 mins
The issue is that beats takes more than 0.1 seconds to index data on elasticsearch, so the refresh call was happening before the docs were inserted.
This change makes the refresh call actually effective.
~~Still, the whole suite runs locally in about 10 minutes; but the build on CI however takes easily 30 minutes, so we should look a bit into the Jenkins pipeline imo.~~
~~@elastic/observablt-robots any pointers on that above would be great. Are you aware of any points of contention? I inspected some pipeline logs top to bottom without reaching conclusion, but I feel there is a lot of scaffolding (git commands, make commands, docker downloads, etc)~~
On another note: I also feel that we …
=> speed up integration tests

Makefile
- remove empty folders (deleted deps) after beats update  (#2656)
=> [7.x] remove empty folders (deleted deps) after beats update (#2656)

.ci/jobs/apm-server-check-changelogs-mbp.yml, .ci/jobs/apm-server-mbp.yml
it will replace the generic context `continuous-integration/jenkins/*` for a fixed one that points to the name of the instance that generates the context `apm-ci`, it is important when we have have multiple multibranch jobs listening on a repo to avoid to overwrite contexts.
**Now**
**After**
=> ci(jenkins): Set GitHub notification context to apm-ci

docs/guide/apm-data-model.asciidoc
From https://github.com/elastic/apm-agent-dotnet/issues/423 
Similar to Java, we kept the url to `public-api.html#api-transaction-tags` - let us know in case we'd like to tackle that, but atm just to be on the safe side we only rename the text, the url remans.
=> [Docs] .NET - rename Tags to Labels

docs/configuration-rum.asciidoc, docs/rum.asciidoc
Simple docs on `sourcemapping.enabled`.
For #2488. Closes #2674.
Needs backport.
=> [docs] sourcemapping.enabled config

docs/copied-from-beats/outputconfig.asciidoc
This PR updates the output config documentation for Logstash. Closes #1631. These changes will also need to be made in elastic/beats.
**A preview of the following changes to `logstash-output.html` is available [here](http://apm-server_2691.docs-preview.app.elstc.co/guide/en/apm/server/master/logstash-output.html).**
* Replaces "The Beat" with "APM Server"
* Updates `@metadata` information
* Adds two sample logstash configs for APM users
Here is the logstash config I got to work with APM. It'd be great if someone with more logstash experience could take a look and recommend any improvements.
```conf
input {
beats {
port => 5044
}
}
filter {
if [@metadata][beat] == "apm" {
if [processor][event] == "sourcemap" {
mutate {
add_field => { "[@metadata][index]" => …
```
=> [docs] Update Logstash output documentation

beater/api/intake/handler.go, beater/api/intake/handler_test.go, beater/request/result_test.go
- Avoid nil errors in beater request results  (#2699)
=> [7.x] Avoid nil errors in beater request results (#2699)

beater/api/intake/handler.go, beater/api/intake/handler_test.go, beater/request/result_test.go
- Avoid nil errors in beater request results  (#2699)
=> [7.4] Avoid nil errors in beater request results (#2699)

beater/api/intake/handler.go, beater/api/intake/handler_test.go, beater/api/intake_rum_integration_test.go, beater/api/mux.go, beater/api/ratelimit/lru_cache.go, beater/api/ratelimit/lru_cache_test.go, beater/middleware/authorization_middleware.go, beater/middleware/authorization_middleware_test.go, beater/middleware/cors_middleware.go, beater/middleware/cors_middleware_test.go, beater/middleware/kill_switch_middleware.go, beater/middleware/kill_switch_middleware_test.go, beater/middleware/log_middleware.go, beater/middleware/log_middleware_test.go, beater/middleware/middleware.go, beater/middleware/middleware_test.go, beater/middleware/monitoring_middleware.go, beater/middleware/monitoring_middleware_test.go, beater/middleware/rate_limit_middleware.go, beater/middleware/recover_panic_middleware.go, beater/middleware/recover_panic_middleware_test.go, beater/middleware/request_time_middleware_test.go, beater/request/context.go
- make the rate limiter reusable  (#2706)
=> [7.x] make the rate limiter reusable (#2706)

docs/copied-from-beats/template-config.asciidoc
elastic/elasticsearch#45704  and elastic/stack-docs#464  moves the
cross-cluster replication (CCR) docs from the Elastic Stack Overview to
the Elasticsearch Reference Guide.
This updates any links pointing to the old Elastic Stack Overview docs.
We've set up redirects so these links won't fail in the meantime. This
just removes a step for users.
Don't merge this PR until the following PRs are merged:
=> [docs] Update link for "ccr-overview-beats" anchor

beater/api/config_agent_integration_test.go, beater/api/intake/handler.go, beater/api/intake/handler_test.go, beater/api/intake_rum_integration_test.go, beater/api/mux.go, beater/api/ratelimit/store.go, beater/api/ratelimit/store_test.go, beater/middleware/rate_limit_middleware.go, beater/request/context.go, processor/stream/processor.go
This PR tries to exemplify and materialize some observations I brought up in discussions during https://github.com/elastic/apm-server/pull/2706 and before:
* Avoid interface pollution: This removes one interface not needed. Doing so, the code is easier to navigate, and we test the actual code and not a mock.
* Follow Go idiomatic naming conventions: avoid non obvious acronyms and vague names like "managers" and such, which are more of a Java thing.
* Remove complex stateful functions: `handler.rateLimit` was making a rate limit call, plus returning a rate limiter if that was ok. There was also some redundant nil checking going on. Calling the limiter is now separated from getting one.
Incidentally, this is also less code to do the same thing and less dependencies per package (imports), …
=> Refactor rate limit logic

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, docs/configuration-rum.asciidoc
There was some confusion around the _comma separated list_, and since in yml it would also be valid to specify in the following format, it makes sense to just describe _a list_.
```
allow_origins:
- "foo"
- "bar"
```
cc @nachogiljaldo
=> [docs] make rum-allow-origins format clear

docs/guide/apm-doc-directory.asciidoc
=> [7.x] [docs] Fix typos (#2690)

docs/guide/apm-doc-directory.asciidoc
=> [7.4] [docs] Fix typos (#2690)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, docs/configuration-rum.asciidoc
- [docs] make rum-allow-origins format clear  (#2716)
=> [7.x] [docs] make rum-allow-origins format clear (#2716)

codecov.yml
We detected that Codecov does not always return accurate coverage measures on PRs, so after digging a little in the Codecov issues we found a configuration that works better for us.
After applying this configuration, we'd not see wrong coverage measures in the PRs.
=> ci(codecov): resolve PR coverage measures errors

docs/guide/agent-server-compatibility.asciidoc, docs/guide/install-and-run.asciidoc
Please confirm `3.x` works with APM Server `>= 6.6`
**MUST BE MERGED WITH elastic/apm-agent-nodejs#1443**
=> docs: update agent server compatibly for Node.js

docs/guide/agent-server-compatibility.asciidoc, docs/guide/install-and-run.asciidoc
=> [7.x][docs] Updates to Agent compat and links

docs/guide/agent-server-compatibility.asciidoc, docs/guide/install-and-run.asciidoc
=> [7.4][docs] Updates to Agent compat and links

docs/guide/agent-server-compatibility.asciidoc, docs/guide/install-and-run.asciidoc
=> [7.3][docs] Updates to Agent compat and links

docs/guide/agent-server-compatibility.asciidoc, docs/guide/install-and-run.asciidoc
=> [7.2][docs] Updates to Agent compat and links

docs/guide/agent-server-compatibility.asciidoc, docs/guide/install-and-run.asciidoc
=> [7.1][docs] Updates to Agent compat and links

docs/guide/agent-server-compatibility.asciidoc, docs/guide/install-and-run.asciidoc
=> [7.0][docs] Updates to Agent compat and links

.ci/check-changelogs.groovy, Jenkinsfile
- Let's reuse the top-level agent to reduce the number of fo requested agents and speed up just a bit the builds.
- Reset labels to be `linux && immutable` to help with what kind of OS is required to be used.
- Time improvements per Stage:
- From the very beginning to the build Linux stage used to take 7 mnts approx and 3 workers and now less than 5 minutes and just one worker.
- Release
=> ci(jenkins): reuse top level agent

.gitignore, agentcfg/cache.go, agentcfg/cache_test.go, agentcfg/fetch.go, agentcfg/fetch_test.go, agentcfg/model.go, agentcfg/model_test.go, beater/api/config/agent/handler.go, beater/api/config/agent/handler_test.go, beater/api/intake/handler.go, beater/api/intake/handler_test.go, beater/api/mux.go, beater/middleware/cors_middleware.go, beater/middleware/rate_limit_middleware.go, beater/middleware/rum_middleware.go, beater/request/context.go, changelogs/head.asciidoc, kibana/connecting_client.go, sourcemap/mapper.go, tests/system/apmserver.py, tests/system/test_integration_acm.py
fixes #2694, fixes elastic/apm-server#2630 , fixes elastic/apm-server#2646 
depends on https://github.com/elastic/kibana/pull/46995
required by https://github.com/elastic/apm-agent-rum-js/pull/439
=> agent config GA

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, changelogs/head.asciidoc, idxmgmt/ilm/config_test.go, idxmgmt/ilm/policy.go, idxmgmt/manager.go, idxmgmt/manager_test.go, tests/system/config/apm-server.yml.j2, tests/system/test_export.py, tests/system/test_setup_index_management.py
Changes the default ILM policy for all APM event types to rollover after 30 days OR 50gb, whichever limit is first hit. 
closes elastic/apm-server#2788
=> [ILM] Change default policies to 30day rollover

Makefile, _beats/libbeat/docs/version.asciidoc, docs/version.asciidoc
Update to 7.5 as upcoming release branch.
=> Update version information to 7.5

tests/system/test_integration_acm.py
This will skip them in Windows, as we don't have Elasticsearch and Kibana there.
=> Mark agent config tests as integration.

tests/system/test_integration_acm.py
- Mark agent config tests as integration.  (#2810)
=> [7.5] Mark agent config tests as integration. (#2810)

tests/system/test_integration_acm.py
- Mark agent config tests as integration.  (#2810)
=> [7.x] Mark agent config tests as integration. (#2810)

script/check_changelogs.py
After this change, the check changelogs test would ignore every changelog before 7.3
We have a job that will never succeed if we do not fix the changelogs or ignore them.
Closes #2789
=> fix: discard to check changelogs before 7.3

docs/guide/install-and-run.asciidoc
Updates a link to the new Ruby documentation. Required for https://github.com/elastic/apm-agent-ruby/issues/556.
=> [docs] update link to ruby docs

docs/guide/install-and-run.asciidoc
=> [7.x][docs] update link to ruby docs

docs/guide/install-and-run.asciidoc
=> [7.5][docs] update link to ruby docs

docs/guide/install-and-run.asciidoc
=> [7.4][docs] update link to ruby docs

docs/guide/install-and-run.asciidoc
Backports https://github.com/elastic/apm-server/pull/2829. Must be merged simultaneously.
=> [7.3][docs] update link to ruby docs

docs/guide/install-and-run.asciidoc
=> [7.2][docs] update link to ruby docs

docs/guide/install-and-run.asciidoc
=> [7.0][docs] update link to ruby docs

docs/version.asciidoc
Bumps the stack version attribute for the 6.8.4 release.
=> [DOCS] Bump docs for 6.8.4 release

docs/version.asciidoc
Bumps the stack version attribute for the 7.4.1 release.
=> [DOCS] Bump docs for 7.4.1 release

docs/version.asciidoc
This reverts commit 5cdfeef1e91d0ac4de10114e9fd22af10c40796e.
=> Revert "[DOCS] Bump docs to 6.8.4 release (#2838)"

docs/version.asciidoc
This reverts commit 5e3feeba0080d3fa8b7c3777bf0262fa89e34d44.
=> Revert "[DOCS] Bump docs to 7.4.1 release (#2837)"

docs/spec/request.json, model/error/generated/schema/error.go, model/transaction/generated/schema/transaction.go
Help defining how the `context.request.socket.remote_address` should be populated.
=> Add description to Intake API for remote_address

docs/copied-from-beats/https.asciidoc, docs/copied-from-beats/monitoring/monitoring-beats.asciidoc, docs/copied-from-beats/monitoring/monitoring-internal-collection.asciidoc, docs/copied-from-beats/monitoring/monitoring-metricbeat.asciidoc, docs/copied-from-beats/security/basic-auth.asciidoc, docs/copied-from-beats/security/securing-beats.asciidoc, docs/copied-from-beats/security/users.asciidoc, docs/copied-from-beats/template-config.asciidoc
Related to https://github.com/elastic/elasticsearch/issues/46880
This PR fixes a broken link to the security content in the Stack Overview, which has moved here: 
https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-roles.html#mapping-roles-file
=> [DOCS] Fixes link to role mapping

beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/OffRum.approved.json, beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/OffSourcemap.approved.json, beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_KillSwitchMiddleware/Off.approved.json, beater/api/intake/test_approved/integration/rum/TestRUMHandler_KillSwitchMiddleware/OffRum.approved.json, beater/api/mux.go, beater/middleware/kill_switch_middleware.go, beater/middleware/kill_switch_middleware_test.go, tests/system/test_integration_acm.py
- Clarify messages on 403 errors for each endpoint.  (#2869)
=> [7.x] Clarify messages on 403 errors for each endpoint. (#2869)

beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/OffRum.approved.json, beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/OffSourcemap.approved.json, beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_KillSwitchMiddleware/Off.approved.json, beater/api/intake/test_approved/integration/rum/TestRUMHandler_KillSwitchMiddleware/OffRum.approved.json, beater/api/mux.go, beater/middleware/kill_switch_middleware.go, beater/middleware/kill_switch_middleware_test.go, tests/system/test_integration_acm.py
- Clarify messages on 403 errors for each endpoint.  (#2869)
=> [7.5] Clarify messages on 403 errors for each endpoint. (#2869)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, changelogs/7.5.asciidoc, idxmgmt/feature.go, idxmgmt/ilm/config.go, idxmgmt/ilm/config_test.go, idxmgmt/manager.go, idxmgmt/manager_test.go
To avoid overwriting existing setups on every startup, a dedicated
config option is added. This is more consistent with other settings and
aligns better with cloud deployment.
related to elastic/apm-server#2240
cc @nachogiljaldo 
TODO:
=> [ILM] Add ilm.setup.overwrite config option.

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, changelogs/7.5.asciidoc, idxmgmt/feature.go, idxmgmt/ilm/config.go, idxmgmt/ilm/config_test.go, idxmgmt/manager.go, idxmgmt/manager_test.go
- [ILM] Add ilm.setup.overwrite config option.  (#2877)
=> [7.5] [ILM] Add ilm.setup.overwrite config option. (#2877)

magefile.go, script/jenkins/windows-build.ps1, script/jenkins/windows-test.ps1
Supersede #2864 and caused by https://github.com/elastic/apm-server/issues/2889
This is the implementation as stated in https://stackoverflow.com/a/20950421
which is `too` verbose and with some NativeCommandError messages as shown below:
=> [apm-ci] suppress the NativeCommandError in windows builds

docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/outputs/output-logstash.asciidoc, docs/copied-from-beats/repositories.asciidoc, docs/copied-from-beats/shared-docker.asciidoc, docs/copied-from-beats/shared-template-load.asciidoc, docs/guide/apm-data-model.asciidoc, docs/ilm-setup.asciidoc, docs/index.asciidoc, docs/storage-management.asciidoc, docs/version.asciidoc
Follow up to elastic/apm-server#2712 / elastic/apm-server#2735 
A second attempt at this as we need to include the shared version file in order to link to other areas of the stack. In this version, I've left an attribute in the `version.asciidoc` file named `doc-branch`. This attribute is **only** used to populate `beat_doc_branch`. All docs variables will come from shared versions file.
The following attributes are defined in the shared versions file:
```asciidoc
:version:                8.0.0
:bare_version:           8.0.0
:apm_server_version:     8.0.0
:branch:                 master
:major-version:          8.x
:prev-major-version:     7.x
:ecs_version:            1.2
:apm-go-branch:         1.x
:apm-java-branch:       1.x
:apm-rum-branch:        4.x
:apm-node-branch:       3.x …
```
=> [docs] Use shared docs file

ingest/pipeline/definition.json
Avoid unexpected infinite retries on pipeline failures due to internal callback handling, by defining failure handling on pipelines.
For the `geoip` pipeline the `client.ip` field will be removed on failure. The field has an `ip` mapping in Elasticsearch. Therefore ingesting the document in ES would fail, even if the pipeline error is ignored in case of a malformed IP address. Dropping the malformed field, ensures the document can be indexed. Information in `client.ip` is always duplicated from some other field, therefore no original information is lost. While there is some pre-processing in place to avoid malformed IP addresses, this is the only case that comes to my mind that could make the pipeline fail. 
For the `user_agent` pipeline failures are simply ignored. The …
=> Add failure handling to ingest pipelines.

ingest/pipeline/definition.json
- Add failure handling to ingest pipelines.  (#2896)
=> [7.5] Add failure handling to ingest pipelines. (#2896)

Jenkinsfile
The signature for isGitRegionMatch has been changed to support different comparators, such as glob or regexp. By default glob is the comparator.
This should be merged only once the library has been released. Likely sometime this week.
=> ci(jenkins): update argument

agentcfg/model.go, tests/system/test_integration_acm.py
Change RUM agent name from `base-js` to `js-base` for server check
on agent config management via RUM endpoint.
=> Fix RUM agent name to js-base.

agentcfg/model.go, tests/system/test_integration_acm.py
Change RUM agent name from `base-js` to `js-base` for server check
on agent config management via RUM endpoint.
Cherry-picked from #2911
=> Fix RUM agent name to js-base. (#2911)

agentcfg/model.go, tests/system/test_integration_acm.py
- Fix RUM agent name to js-base. (#2911)  (#2912)
=> [7.x] Fix RUM agent name to js-base. (#2911) (#2912)

agentcfg/cache_test.go, agentcfg/fetch_test.go, agentcfg/model.go, agentcfg/model_test.go, beater/api/config/agent/handler.go, beater/api/config/agent/handler_test.go
This is so agents can cache empty configurations, as they don't
necessarily inspect the contents of a response body to decide
whether they should process it, and just make a decision based on
the response code (304 vs 200).
Fixes elastic/apm-server#2916
=> Returns a sentinel value as Etag when there is no config in Kibana.

agentcfg/cache_test.go, agentcfg/fetch_test.go, agentcfg/model.go, agentcfg/model_test.go, beater/api/config/agent/handler.go, beater/api/config/agent/handler_test.go
- Returns a sentinel value as Etag when there is no config in Kibana.  (#2926)
=> [7.x] Returns a sentinel value as Etag when there is no config in Kibana. (#2926)

agentcfg/cache_test.go, agentcfg/fetch_test.go, agentcfg/model.go, agentcfg/model_test.go, beater/api/config/agent/handler.go, beater/api/config/agent/handler_test.go
- Returns a sentinel value as Etag when there is no config in Kibana.  (#2926)
=> [7.5] Returns a sentinel value as Etag when there is no config in Kibana. (#2926)

Makefile, _beats/libbeat/scripts/Makefile
-i flag given to go build is deprecated: https://github.com/golang/go/issues/24674
I also removed the `-i` flag given to `go test` because when running the tests, I had the same issue as the one I reported and the flag seems to do the same thing as it does for `go build`.
Fixes #2885
=> Makefile: Drop -i flag in GOBUILD_FLAGS or go test

changelogs/6.8.asciidoc, changelogs/7.0.asciidoc
=> [7.0] Sync changelog. (#2939)

changelogs/6.8.asciidoc, changelogs/7.0.asciidoc
Backports the following commits to 7.1:
=> [7.1] Sync changelog. (#2939)

changelogs/6.8.asciidoc, changelogs/7.0.asciidoc
=> [7.2] Sync changelog. (#2939)

changelogs/6.8.asciidoc, changelogs/7.0.asciidoc
=> [7.3] Sync changelog. (#2939)

changelogs/6.8.asciidoc, changelogs/7.0.asciidoc
=> [7.4] Sync changelog. (#2939)

changelogs/6.8.asciidoc, changelogs/7.0.asciidoc
=> [7.5] Sync changelog. (#2939)

changelogs/6.8.asciidoc, changelogs/7.0.asciidoc
=> [7.x] Sync changelog. (#2939)

changelogs/7.5.asciidoc
Must have whitespace before `{pull}` to render changelog links correctly.
=> docs: fix changelog link

changelogs/7.5.asciidoc
- docs: fix changelog link (#2950)
=> [7.5] docs: fix changelog link (#2950)

changelogs/7.5.asciidoc
- docs: fix changelog link (#2950)
=> [7.x] docs: fix changelog link (#2950)

idxmgmt/ilm/supporter_factory.go, idxmgmt/manager_test.go
When running APM Server `apm-server.ilm.setup.overwrite` was ignored and always set to the same value as `apm-server.ilm.setup.enabled`. 
fixes #2958
=> Fix: respect setting for overwriting ILM setup

idxmgmt/ilm/supporter_factory.go, idxmgmt/manager_test.go
- Fix: respect setting for overwriting ILM setup  (#2959)
=> [7.x] Fix: respect setting for overwriting ILM setup (#2959)

idxmgmt/ilm/supporter_factory.go, idxmgmt/manager_test.go
- Fix: respect setting for overwriting ILM setup  (#2959)
=> [7.5] Fix: respect setting for overwriting ILM setup (#2959)

docs/copied-from-beats/https.asciidoc, docs/copied-from-beats/monitoring/monitoring-internal-collection.asciidoc, docs/copied-from-beats/security/beats-system.asciidoc, docs/copied-from-beats/security/securing-beats.asciidoc
Related to https://github.com/elastic/elasticsearch/issues/46880
This PR fixes links to content that has moved from the Stack Overview to the Elasticsearch Reference.
In particular, it is related to the following broken links in https://github.com/elastic/stack-docs/pull/700
> 11:38:39 INFO:build_docs:Bad cross-document links:
11:38:39 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/server/master/beats-system-user.html:
11:38:39 INFO:build_docs:   - en/elastic-stack-overview/master/built-in-roles.html
11:38:39 INFO:build_docs:   - en/elastic-stack-overview/master/setting-up-authentication.html
11:38:39 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/server/master/monitoring-internal-collection.html:
11:38:39 INFO:build_docs:   - …
=> [DOCS] Fixes security links

.ci/check-changelogs.groovy, .ci/jobs/apm-server-check-changelogs-mbp.yml, .ci/jobs/apm-server-mbp.yml, .ci/jobs/defaults.yml, Jenkinsfile
Refactor the JJBB to:
- Store more builds
- Use git reference repo
=> ci(jenkins): change log rotation, use cached repo

beater/config/rum.go, elasticsearch/client.go, elasticsearch/config.go, elasticsearch/estest/client.go
This is required as it is now supported in libbeat. 
Fixes #2957.
=> Adds support for API Keys in the Elasticsearch client.

beater/config/rum.go, elasticsearch/client.go, elasticsearch/config.go, elasticsearch/estest/client.go
- Adds support for API Keys in the Elasticsearch client.  (#2989)
=> [7.x] Adds support for API Keys in the Elasticsearch client. (#2989)

Jenkinsfile
Shallow cloning and isGitRegionMatch are not compatible when the versions to compare are older than 5...
Now
=> ci(jenkins): support isGitRegionMatch

RELEASES.md
Updating docs now that the Server and all agents use shared version files (https://github.com/elastic/apm-server/issues/2692).
=> [docs] Update releases.md

docker-compose.yml, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_access.py, tests/system/test_export.py, tests/system/test_integration.py, tests/system/test_integration_acm.py, tests/system/test_integration_logging.py, tests/system/test_pipelines.py, tests/system/test_requests.py, tests/system/test_setup_index_management.py
A collection of testing updates extracted from #2799.  The most substantial change introduced makes tests wait for pipelines to load before running.  This uncovered a race in one test that is skipped for now.
=> Update system tests

docs/guide/apm-data-model.asciidoc
This fixes a broken link, which is causing the docs build to fail.
`set_tag` and it's anchor was removed from the APM Ruby docs with https://github.com/elastic/apm-agent-ruby/pull/645.
Plan to backport to 7.5 and 7.4.
=> [DOCS] Change Ruby APM `set_tags` link to `set_label`

docs/guide/apm-data-model.asciidoc
This fixes a broken link, which is causing the docs build to fail.
`set_tag` and it's anchor was removed from the APM Ruby docs with
https://github.com/elastic/apm-agent-ruby/pull/645.
7.5 backport of #3015
=> [DOCS] [7.5] Change Ruby APM `set_tags` link to `set_label`

docs/guide/apm-data-model.asciidoc
This fixes a broken link, which is causing the docs build to fail.
`set_tag` and it's anchor was removed from the APM Ruby docs with
https://github.com/elastic/apm-agent-ruby/pull/645.
7.4 backport of #3015
=> [DOCS] [7.4] Change Ruby APM `set_tags` link to `set_label`

docs/guide/page_header.html, docs/page_header.html
Explicitly set page_header.html for 6.8 so that the default notice can be updated for OOM versions.
Prerequisite for: elastic/docs#1528
=> [DOCS] Added older release notice.

TESTING.md, tests/system/apmserver.py, tests/system/test_setup_index_management.py
Extracted from experiments in #3003.  This disables idx mgmt setup teardown as a result of that investigation.
=> capture es diagnostics per DIAGNOSTIC_INTERVAL

beater/api/config/agent/handler.go, beater/api/config/agent/handler_test.go, changelogs/7.5.asciidoc, kibana/connecting_client.go, kibana/connecting_client_test.go, tests/kibana.go
=> Retry connection when Kibana version is not compatible.

beater/api/config/agent/handler.go, beater/api/config/agent/handler_test.go, changelogs/7.5.asciidoc, kibana/connecting_client.go, kibana/connecting_client_test.go, tests/kibana.go
- Retry connection when Kibana version is not compatible.  (#3031)
=> [7.5] Retry connection when Kibana version is not compatible. (#3031)

Makefile, _beats/libbeat/scripts/Makefile
- Makefile: Drop -i flag in GOBUILD_FLAGS or go test (#2906)
=> [7.x] Makefile: Drop -i flag in GOBUILD_FLAGS or go test (#2906)

TESTING.md, tests/system/apmserver.py, tests/system/test_setup_index_management.py
- capture es diagnostics per DIAGNOSTIC_INTERVAL (#3028)
=> [7.x] capture es diagnostics per DIAGNOSTIC_INTERVAL (#3028)

magefile.go
- Add mage packaging build and type filters (#3003)
=> [7.x] Add mage packaging build and type filters (#3003)

TESTING.md, tests/approvals/approvals.go, tests/system/apmserver.py, tests/system/error.approved.json, tests/system/spans.approved.json, tests/system/test_integration.py, tests/system/transaction.approved.json
Update tests/system/test_integration.py to use the approved/received approach used in integration tests. We've been writing the complete ES responses, doc IDs and all, to disk. We now write only the _source of each, and sort them by event IDs first.
We change the logic in tests/system in one commit without regenerating the approved files, to prove that the changes do no affect the existing comparisons. The approved files are then regenerated in a second commit, storing only the _source contents, and sorting docs by event ID.
There are a couple of changes to tests/approvals to support the above, as well as cleaning up a bit of tech debt:
- stop assuming that the received/approved files have a specific map structure, and just use `interface{}`
- only write the received data to disk if the …
=> tests: use approvals for system tests

docs/config-ownership.asciidoc, docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/shared-systemd.asciidoc, docs/getting-started-apm-server.asciidoc
**A preview of the documenation changes in this PR is available [here](http://apm-server_3027.docs-preview.app.elstc.co/diff)**.
Closes https://github.com/elastic/apm-server/issues/2865.
Still some "build" work that needs to be done before this can be merged, mostly in the beats repo.
This PR updates:
* [**Step 3: Start**](https://www.elastic.co/guide/en/apm/server/current/apm-server-starting.html)
* [**APM Serever and systemd**](https://www.elastic.co/guide/en/apm/server/current/running-with-systemd.html)
* The command reference documentation, which was linking to the incorrect Beats information.
=> [docs] systemd and config ownership improvements

Jenkinsfile
- ci(jenkins): cancel previous running builds (#2983)
=> [7.x] ci(jenkins): cancel previous running builds (#2983)

Jenkinsfile
- feat: enable DIAGNOSTIC_INTERVAL env var (#3032)
=> [7.x] feat: enable DIAGNOSTIC_INTERVAL env var (#3032)

Jenkinsfile, Makefile, docker-compose.yml
- feat: allow to set different test environments (#3054)
=> [7.x] feat: allow to set different test environments (#3054)

docs/config-ownership.asciidoc, docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/shared-systemd.asciidoc, docs/getting-started-apm-server.asciidoc
- [docs] systemd and config ownership improvements (#3027)
=> [7.5] [docs] systemd and config ownership improvements (#3027)

docs/config-ownership.asciidoc, docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/shared-systemd.asciidoc, docs/getting-started-apm-server.asciidoc
- [docs] systemd and config ownership improvements (#3027)
=> [7.x] [docs] systemd and config ownership improvements (#3027)

.ci/scripts/docker-get-logs.sh, Jenkinsfile, script/jenkins/linux-test.sh
- feat: grab docker container logs after run tests  (#2948)
=> [7.x] feat: grab docker container logs after run tests (#2948)

beater/beater.go, beater/server.go, beater/tracing.go, beater/tracing_test.go, tests/system/test_access.py
When the server is configured to send trace data
to itself, it will now create an entirely separate
muxer and HTTP server for the purpose.
This tracer muxer is configured to not require any
auth, and is not instrumented, so we can simplify
the "doNotTrace" request ignorer.
Closes #3051
=> beater: disable auth for self-instrumentation

beater/beater.go, beater/server.go, beater/tracing.go, beater/tracing_test.go, tests/system/test_access.py
- beater: disable auth for self-instrumentation  (#3083)
=> [7.x] beater: disable auth for self-instrumentation (#3083)

script/build_apm_docs.sh
Replaces the no longer needed `--asciidoctor` flag (on by default) with the new and shiny `--direct_html`. This removes docbook from our documentation builds. For https://github.com/elastic/docs/pull/1643.
=> [docs] Updates doc build script

docs/data-ingestion.asciidoc
Fixes incorrect name for output.elasticsearch.worker in documentation.
=> Fixes incorrect name for output.elasticsearch.worker

docs/data-ingestion.asciidoc
- Fixes incorrect name for output.elasticsearch.worker (#2887)
=> [7.5] Fixes incorrect name for output.elasticsearch.worker (#2887)

docs/data-ingestion.asciidoc
- Fixes incorrect name for output.elasticsearch.worker (#2887)
=> [7.x] Fixes incorrect name for output.elasticsearch.worker (#2887)

docs/ilm.asciidoc
- docs: fix ilm copy pasta (#3088)
=> [7.5] docs: fix ilm copy pasta (#3088)

docs/ilm.asciidoc
- docs: fix ilm copy pasta (#3088)
=> [7.x] docs: fix ilm copy pasta (#3088)

docs/secure-communication-agents.asciidoc
- docs: change client to apm-server (#3092)
=> [7.5] docs: change client to apm-server (#3092)

docs/secure-communication-agents.asciidoc
- docs: change client to apm-server (#3092)
=> [7.x] docs: change client to apm-server (#3092)

docs/spec/spans/span.json
The reference to the message json spec file from spans was invalid.
Thanks for pointing out the bug @mikker.
=> [intake] Fix reference to message json spec.

docs/spec/spans/span.json
- [intake] Fix reference to message json spec. (#3112)
=> [7.x] [intake] Fix reference to message json spec. (#3112)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml
Jaeger integration will be released as experimental feature, for following reasons:
* APM Server acting as Jaeger collector doesn't support probabilistic sampling. 
* No automated end-to-end system tests yet.
* Used [opentelemetry/opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector) library is in alpha state.
=> Add experimental flag to Jaeger integration

tests/system/config/apm-server.yml.j2, tests/system/test_monitoring.py
Add a system test that verifies the server can connect to the X-Pack Monitoring endpoint using the built-in "apm_system" user.
See https://github.com/elastic/apm-server/issues/2708
=> tests/system: basic smoke-test for monitoring

docs/copied-from-beats/outputs/console/docs/console.asciidoc, docs/copied-from-beats/outputs/fileout/docs/fileout.asciidoc, docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc, docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc, docs/copied-from-beats/outputs/redis/docs/redis.asciidoc
For https://github.com/elastic/apm-server/issues/2580.
Requires a PR in the Beats repo to persist the changes: https://github.com/elastic/beats/pull/15272.
---
This PR adds a paragraph to each output page explaining that the es output must be disabled first:
```
To use this output, edit the {beatname_uc} configuration file to disable the {es}
output by commenting it out...
```
It also clarifies that for apm-server, Logstash and Kafka `enabled` defaults to `false`. This is not the case for beats:
```
ifndef::apm-server[]
The default value is `true`.
endif::[]
ifdef::apm-server[]
The default value is `false`.
endif::[]
```
Finally, there is no redis, file, or console section in the `.yml` configuration files, so I've fixed wording that indicated there was.
=> [docs] Fix ambiguous *.output documentation

Makefile, testing/docker/elasticsearch/roles.yml, testing/docker/elasticsearch/users, testing/docker/elasticsearch/users_roles, tests/system/test_access.py
- [test] Use apm_server_user for API Key tests. (#3124)
=> [7.x] [test] Use apm_server_user for API Key tests. (#3124)

Makefile
- Ignore "should have comment" golint errors  (#3067)
=> [7.x] Ignore "should have comment" golint errors (#3067)

beater/middleware/log_middleware.go, beater/middleware/log_middleware_test.go, changelogs/head.asciidoc, tests/system/test_integration_logging.py
In the logging middleware, add `trace.id` and `transaction.id` fields if the request is being traced. If traced, reuse the transaction ID for the existing `request_id` field, rather than generating another UUID.
I have manually tested this with apm-integration-testing (using `--with-filebeat`), checking that a user can jump between the APM and Logs app in both directions.
Closes #3075
=> beater/middleware: add trace/log correlation

beater/api/profile/handler.go, beater/api/profile/handler_test.go
If messageType is specified, check that it has the
expected value for pprof. Otherwise we assume
pprof, and optimistically attempt to decode.
Closes elastic/apm-server#2954
=> beater/api/profile: fix pprof Content-Type

docs/copied-from-beats/docs/template-config.asciidoc
Users no longer need to set up soft deletes in Elasticsearch to replicate a Beats/APM index using cross-cluster replication.
This removes a related note in the APM documentation.
Relates to elastic/elasticsearch#50859.
Should backport to master, 7.x, 7.5, and 6.8
=> [DOCS] Remove outdated CCR note

docs/guide/cross-cluster-search.asciidoc, docs/guide/index.asciidoc, docs/guide/install-and-run.asciidoc
- [docs] Adds APM app cross cluster search documentation (#3089)
=> [7.x] [docs] Adds APM app cross cluster search documentation (#3089)

docs/copied-from-beats/outputs/console/docs/console.asciidoc, docs/copied-from-beats/outputs/fileout/docs/fileout.asciidoc, docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc, docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc, docs/copied-from-beats/outputs/redis/docs/redis.asciidoc
- [docs] Fix ambiguous *.output documentation (#3093)
=> [7.x] [docs] Fix ambiguous *.output documentation (#3093)

docs/copied-from-beats/docs/template-config.asciidoc
- [DOCS] Remove outdated CCR note (#3147)
=> [7.5] [DOCS] Remove outdated CCR note (#3147)

docs/copied-from-beats/outputs/console/docs/console.asciidoc, docs/copied-from-beats/outputs/fileout/docs/fileout.asciidoc, docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc, docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc, docs/copied-from-beats/outputs/redis/docs/redis.asciidoc
- [docs] Fix ambiguous *.output documentation (#3093)
=> [7.5] [docs] Fix ambiguous *.output documentation (#3093)

docs/copied-from-beats/docs/template-config.asciidoc
- [DOCS] Remove outdated CCR note (#3147)
=> [7.x] [DOCS] Remove outdated CCR note (#3147)

beater/api/config/agent/handler.go, beater/api/config/agent/handler_test.go, changelogs/7.5.asciidoc, kibana/connecting_client.go, kibana/connecting_client_test.go, tests/kibana.go
- Retry connection when Kibana version is not compatible.  (#3031)
=> [7.x] Retry connection when Kibana version is not compatible. (#3031)

tests/system/test_instrumentation.py
Couldn't easily figure out the reason for the test to be flaky, so skipping it for now as it prevents builds to hit the `release` stage, which has priority at the moment.
=> Skip flaky test for now

docs/guide/install-and-run.asciidoc
Fixes a merge conflict that I accidentally committed to the 7.5 docs yesterday in  https://github.com/elastic/apm-server/pull/3152. Closes https://github.com/elastic/apm-server/issues/3168. Thanks again @feenst.
=> [docs] Fix 7.5 merge conflict

changelogs/7.6.asciidoc
- Add changelog for 7.6  (#3167)
=> [7.x] Add changelog for 7.6 (#3167)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, elasticsearch/client.go
- Document api_key in apm-server.yml file (#3138)
=> [7.x] Document api_key in apm-server.yml file (#3138)

docs/guide/apm-data-model.asciidoc
- [DOCS] Change Ruby APM `set_tags` link to `set_label` (#3015)
=> [7.x] [DOCS] Change Ruby APM `set_tags` link to `set_label` (#3015)

docs/guide/apm-data-model.asciidoc
- [DOCS] Change Ruby APM `set_tags` link to `set_label` (#3015)
=> [7.6] [DOCS] Change Ruby APM `set_tags` link to `set_label` (#3015)

changelogs/6.8.asciidoc
`check_changelogs.py` now checks `6.8` (https://github.com/elastic/apm-server/pull/3174). The check is failing because `6.8.6` rns don't exist outside of that branch.
=> [docs] Add missing 6.8.6 release notes

RELEASES.md, script/check_changelogs.py
Update information about necessary steps to take for releases. 
@bmorelli25 I think you have been involved in the `check_changelogs.py` script - I updated it within this PR, please review my changes.
=> [docs] Update Release notes and changelog script

docs/copied-from-beats/docs/template-config.asciidoc
We've started recommending `append_fields` to help users customize their APM experience ([1](https://github.com/elastic/kibana/issues/48674#issuecomment-545342220)) ([2](https://discuss.elastic.co/t/searching-for-a-custom-made-header/200403/3)). This PR adds the experimental documentation to the APM Server Reference.
Needs a separate PR in beats. For(ish) https://github.com/elastic/kibana/issues/49070.
=> [docs] add append_fields to docs

changelogs/6.8.asciidoc
- docs: add missing 6.8.6 release notes (#3191)
=> [7.5] docs: add missing 6.8.6 release notes (#3191)

changelogs/6.8.asciidoc
- docs: add missing 6.8.6 release notes (#3191)
=> [7.6] docs: add missing 6.8.6 release notes (#3191)

changelogs/6.8.asciidoc
- docs: add missing 6.8.6 release notes (#3191)
=> [7.x] docs: add missing 6.8.6 release notes (#3191)

beater/beater.go, beater/onboarding.go, beater/onboarding_test.go, beater/server.go, beater/server_test.go
- Rewrite TestNotifyUpServerDown to use "setupServer", simplifying the test and removing an intermittent panic.
- Rename to TestOnboarding. I have no idea what the old name was meant to indicate.
- Rewrite onboarding to use publisher.
Closes #3203
=> beater: rewrite flaky test

beater/beater.go, beater/onboarding.go, beater/onboarding_test.go, beater/server.go, beater/server_test.go
- beater: rewrite flaky test  (#3204)
=> [7.6] beater: rewrite flaky test (#3204)

docs/copied-from-beats/docs/template-config.asciidoc
- docs: add append_fields to docs (#3190)
=> [7.5] docs: add append_fields to docs (#3190)

docs/copied-from-beats/docs/template-config.asciidoc
- docs: add append_fields to docs (#3190)
=> [7.x] docs: add append_fields to docs (#3190)

docs/copied-from-beats/docs/template-config.asciidoc
- docs: add append_fields to docs (#3190)
=> [7.6] docs: add append_fields to docs (#3190)

Jenkinsfile
It fixes some regular expressions to work with the new implementation of `isGitRegionMatch` step.
After merging, all PRs with changes in the regexp specified will trigger the release stage.
```
"^_beats.*",
"^apm-server.yml",
"^apm-server.docker.yml",
"^magefile.go",
"^ingest.*",
"^packaging.*",
"^tests/packaging.*",
"^vendor/github.com/elastic/beats.*"
```
closes https://github.com/elastic/apm-server/issues/3181
=> fix: trigger on _beats changes

beater/authorization/apikey.go, beater/authorization/apikey_test.go, cmd/apikey.go, elasticsearch/client.go, elasticsearch/client_test.go, elasticsearch/estest/client.go, elasticsearch/security_api_test.go, model/stacktrace_frame_test.go, sourcemap/es_store_test.go, sourcemap/test/es_client.go
Elasticsearch operations that use "doRequest" will now
return an *elasticsearch.Error if the server responds
with a status code > 299. The error type can be used
for special handling of certain status codes, such as
401 Unauthorized when performing _has_privileges checks.
The API Key auth code is updated to cache 401 responses
using this type and `errors.As`, checking for 401s.
Similarly, the apikey CLI subcommand now checks for 404s
specifically for ignoring failed privilege deletions.
Fixes https://github.com/elastic/apm-server/issues/3215
=> Introduce elasticsearch.Error

beater/authorization/apikey.go, beater/authorization/apikey_test.go, cmd/apikey.go, elasticsearch/client.go, elasticsearch/client_test.go, elasticsearch/estest/client.go, elasticsearch/security_api_test.go, model/stacktrace_frame_test.go, sourcemap/es_store_test.go, sourcemap/test/es_client.go
- Introduce elasticsearch.Error  (#3218)
=> [7.6] Introduce elasticsearch.Error (#3218)

beater/authorization/apikey.go, beater/authorization/apikey_test.go, cmd/apikey.go, elasticsearch/client.go, elasticsearch/client_test.go, elasticsearch/estest/client.go, elasticsearch/security_api_test.go, model/stacktrace_frame_test.go, sourcemap/es_store_test.go, sourcemap/test/es_client.go
- Introduce elasticsearch.Error  (#3218)
=> [7.x] Introduce elasticsearch.Error (#3218)

changelogs/7.5.asciidoc
Do not merge until release day.
Adds `7.5.2` release notes and rearranges the order of the jump table to match prior versions. Needs to be ported to `7.6` and `master`.
=> [docs][7.5] 7.5.2 release notes

changelogs/7.5.asciidoc
- [docs][7.5] 7.5.2 release notes #3219 (#3223)
=> [7.6] [docs][7.5] 7.5.2 release notes #3219 (#3223)

changelogs/7.5.asciidoc
- [docs][7.5] 7.5.2 release notes #3219 (#3223)
=> [7.x] [docs][7.5] 7.5.2 release notes #3219 (#3223)

script/update_beats.sh
It adds a `git fetch --all` before to checkout the Beats branch.
It allows us to use commits for any branch or remote ref that we have configured in our `git` config as Beats version (e.g commit PRs using the git ref +refs/pull/*/head:refs/remotes/origin/pr/*)
related to https://github.com/elastic/beats/pull/15631 and https://github.com/elastic/beats/issues/13371
=> chore: fetch all remotes before to checkout the branch

tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_export.py, tests/system/test_instrumentation.py, tests/system/test_integration.py
- tests/system: attempt to speed up tests  (#3202)
=> [7.6] tests/system: attempt to speed up tests (#3202)

beater/authorization/builder.go, beater/authorization/builder_test.go, beater/config/api_key.go, beater/config/api_key_test.go, beater/config/config_test.go, tests/system/test_access.py
Avoid overly long caching of potentially expired or invalidated API Keys by decreasing cache duration from 5 minutes to 1 minute. 
fixes elastic/apm-server#3237
=> decrease API Key cache time to one minute

beater/authorization/builder.go, beater/authorization/builder_test.go, beater/config/api_key.go, beater/config/api_key_test.go, beater/config/config_test.go, tests/system/test_access.py
- decrease API Key cache time to one minute (#3238)
=> [7.6] decrease API Key cache time to one minute (#3238)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml
- Add experimental flag to API Key feature (#3240)
=> [7.6] Add experimental flag to API Key feature (#3240)

tests/system/test_access.py, tests/system/test_instrumentation.py
Get rid of using lstrip for removing trailing `ApiKey `. The matching does not consider character order, but strips away everything until the first non-matching character. This can lead to removing starting characters from the actual API Key.
Eg:
`"Key ApiApiKey foo".lstrip("ApiKey ")` -> `foo`
`"ApiKey eVY1MTAyOEJEZ".lstrip("ApiKey ")` -> `VY1MTAyOEJEZ`
=> [test] Fix flaky self instrumentation system test

beater/authorization/builder.go, beater/authorization/builder_test.go, beater/config/api_key.go, beater/config/api_key_test.go, beater/config/config_test.go, tests/system/test_access.py
- decrease API Key cache time to one minute (#3238)
=> [7.x] decrease API Key cache time to one minute (#3238)

cmd/apikey.go, elasticsearch/security_api.go, tests/system/test_access.py, tests/system/test_apikey.py
- Remove creation of APM provileges.  (#3251)
=> [7.6] Remove creation of APM provileges. (#3251)

docs/copied-from-beats/docs/command-reference.asciidoc, docs/secure-communication-agents.asciidoc, docs/ssl-input-short.asciidoc
Adds Agent/Server API key documentation:
* Updates the command reference to include the `apikey` command.
* Adds a configuration reference for the new `api_key` config options.
* Adds a walkthrough for enabling, configuring, and setting API keys.
**[An HTML preview is available here](http://apm-server_3212.docs-preview.app.elstc.co/guide/en/apm/server/master/secure-communication-agents.html)**.
To do:
* A PR is required in Beats to persist these changes.
* The links to Agent documentation will need to be updated closer to release time.
Closes https://github.com/elastic/apm-server/issues/3033.
=> [docs] Server/Agent API key documentation

docs/copied-from-beats/docs/command-reference.asciidoc, docs/secure-communication-agents.asciidoc, docs/ssl-input-short.asciidoc
- [docs] Server/Agent API key documentation (#3212)
=> [7.x] [docs] Server/Agent API key documentation (#3212)

docs/copied-from-beats/docs/command-reference.asciidoc, docs/secure-communication-agents.asciidoc, docs/ssl-input-short.asciidoc
- [docs] Server/Agent API key documentation (#3212)
=> [7.6] [docs] Server/Agent API key documentation (#3212)

docs/redirects.asciidoc
Backport to `7.x`, `7.6`, `7.5`, `6.8`.
=> [docs] Update apm-contrib link for dashboards

docs/redirects.asciidoc
- [docs] Update apm-contrib link for dashboardds (#3257)
=> [7.6] [docs] Update apm-contrib link for dashboardds (#3257)

docs/redirects.asciidoc
- [docs] Update apm-contrib link for dashboardds (#3257)
=> [7.x] [docs] Update apm-contrib link for dashboardds (#3257)

docs/redirects.asciidoc
- [docs] Update apm-contrib link for dashboardds (#3257)
=> [7.5] [docs] Update apm-contrib link for dashboardds (#3257)

changelogs/head.asciidoc, x-pack/apm-server/cmd/root.go, x-pack/apm-server/cmd/root_test.go
`enroll` technically succeeded but had no use.  Removing it is considered a bug fix and less confusing than just deprecating it.
fixes #3230
=> remove enroll command

changelogs/7.7.asciidoc, x-pack/apm-server/cmd/root.go, x-pack/apm-server/cmd/root_test.go
- remove enroll command (#3270)
=> [7.x] remove enroll command (#3270)

docs/configuring.asciidoc, docs/getting-started-apm-server.asciidoc, docs/jaeger-support.asciidoc
First draft of Jaeger integration documentation. Closes https://github.com/elastic/apm-server/issues/3123.
Open for suggestions if anyone can think of a better place for this documentation to live. Also, it'd be great to have some sort of settings reference so we can get rid of some of the noise from guides like this. It'd need to happen in Beats first, thought. I'll talk to DeDe.
**[An HTML preview is available here](http://apm-server_3269.docs-preview.app.elstc.co/guide/en/apm/server/master/jaeger.html)**.
=> [docs] Add Jaeger documentation

docs/configuring.asciidoc, docs/getting-started-apm-server.asciidoc, docs/jaeger-support.asciidoc
- [docs] Add Jaeger documentation (#3269)
=> [7.x] [docs] Add Jaeger documentation (#3269)

docs/configuring.asciidoc, docs/getting-started-apm-server.asciidoc, docs/jaeger-support.asciidoc
- [docs] Add Jaeger documentation (#3269)
=> [7.6] [docs] Add Jaeger documentation (#3269)

docs/agent-configuration.asciidoc, docs/events-api.asciidoc, docs/intake-api.asciidoc, docs/server-info.asciidoc, docs/sourcemap-api.asciidoc
Closes https://github.com/elastic/apm-server/issues/3109.
* "Intake API" --> "API"
* "Events API" --> "Events intake API"
* Other cleanup as these files haven't been touched in a while.
=> [docs] Rename intake API

docs/agent-configuration.asciidoc, docs/events-api.asciidoc, docs/intake-api.asciidoc, docs/server-info.asciidoc, docs/sourcemap-api.asciidoc
- [docs] Rename intake API (#3283)
=> [7.6] [docs] Rename intake API (#3283)

docs/agent-configuration.asciidoc, docs/events-api.asciidoc, docs/intake-api.asciidoc, docs/server-info.asciidoc, docs/sourcemap-api.asciidoc
- [docs] Rename intake API (#3283)
=> [7.x] [docs] Rename intake API (#3283)

changelogs/7.6.asciidoc
Just noticed that this is pointing to the wrong PR. Backport to `7.x`, `7.6`.
=> [docs] Fix link to PR for breaking change

beater/authorization/builder.go
IsAuthorizationConfigured has no side effects for any of the implementations, so there's no point in calling it.
=> beater/authorization: remove unnecessary code

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/api/mux.go, beater/config/config_test.go, beater/config/instrumentation_test.go, beater/config/rum.go, beater/middleware/cors_middleware.go, beater/middleware/cors_middleware_test.go, changelogs/head.asciidoc
The configurable list is appended to Content-Type, Content-Encoding and Accept, which are allways included.
Closes #2497
=> Make list of Access-Control-Allow-Headers configurable.

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/api/mux.go, beater/config/config_test.go, beater/config/rum.go, beater/middleware/cors_middleware.go, beater/middleware/cors_middleware_test.go
- Make list of Access-Control-Allow-Headers configurable. (#3299)
=> [7.x] Make list of Access-Control-Allow-Headers configurable.

beater/api/intake/handler_test.go, beater/api/mux.go, beater/config/instrumentation_test.go, elasticsearch/client.go, processor/stream/package_tests/error_attrs_test.go, processor/stream/package_tests/metadata_attrs_test.go, processor/stream/package_tests/metricset_attrs_test.go, processor/stream/package_tests/span_attrs_test.go, processor/stream/package_tests/transaction_attrs_test.go, processor/stream/processor.go, processor/stream/processor_test.go
This contains the minimum set of changes for  https://github.com/elastic/apm-server/issues/2905.
Supersedes #3254
=> Separate event decoders.

changelogs/7.6.asciidoc
- [docs] Remove 7.6 breaking change (#3295)
=> [7.6] [docs] Remove 7.6 breaking change (#3295)

changelogs/7.6.asciidoc
- [docs] Remove 7.6 breaking change (#3295)
=> [7.x] [docs] Remove 7.6 breaking change (#3295)

beater/api/intake/handler_test.go, beater/api/mux.go, processor/stream/package_tests/error_attrs_test.go, processor/stream/package_tests/metadata_attrs_test.go, processor/stream/package_tests/metricset_attrs_test.go, processor/stream/package_tests/span_attrs_test.go, processor/stream/package_tests/transaction_attrs_test.go, processor/stream/processor.go, processor/stream/processor_test.go
- Separate event decoders.  (#3297)
=> [7.x] Separate event decoders. (#3297)

beater/api/mux.go, beater/api/mux_config_agent_test.go, beater/config/config.go, beater/config/config_test.go, kibana/connecting_client.go, kibana/connecting_client_test.go
- strip trailing slashes from kibana host configuration (#3277)
=> [7.x] strip trailing slashes from kibana host configuration (#3277)

beater/config/config.go
- adapt kibana host strip to new api (#3290)
=> [7.x] adapt kibana host strip to new api (#3290)

beater/authorization/builder.go
- beater/authorization: remove unnecessary code  (#3306)
=> [7.x] beater/authorization: remove unnecessary code (#3306)

script/update_beats.sh
This will cause our tests to keep working when Beats migrates to Python 3.
Closes #3001 (following recommendation from https://github.com/elastic/apm-server/issues/3001#issuecomment-582459881) 
This expects #3318 to be taken on.
=> Stop syncing _beats/libbeat/tests/system/beat/ in beat updates.

script/update_beats.sh
- Stop syncing _beats/libbeat/tests/system/beat/ in beat updates.  (#3320)
=> [7.6] Stop syncing _beats/libbeat/tests/system/beat/ in beat updates. (#3320)

script/update_beats.sh
- Stop syncing _beats/libbeat/tests/system/beat/ in beat updates.  (#3320)
=> [7.x] Stop syncing _beats/libbeat/tests/system/beat/ in beat updates. (#3320)

docs/jaeger-support.asciidoc
Adds a warning explaining that Jaeger is not yet available on Cloud.
~~- [ ] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).~~
~~- [ ] My code follows the style guidelines of this project (run `make check-full` for static code checks and linting)~~
~~- [ ] New and existing [**unit** tests](https://github.com/elastic/apm-server/blob/master/TESTING.md) pass locally with my changes~~
N/A
N/A
=> [docs] Add note about Jaeger availability on Cloud

docs/jaeger-support.asciidoc
- docs: add jaeger cloud note (#3329)
=> [7.x] docs: add jaeger cloud note (#3329)

docs/jaeger-support.asciidoc
- docs: add jaeger cloud note (#3329)
=> [7.6] docs: add jaeger cloud note (#3329)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/config/api_key.go, beater/config/api_key_test.go, beater/config/config_test.go, changelogs/head.asciidoc, elasticsearch/config.go
When configuring an Elasticsearch instance for API Key usage, Elasticsearch default values should be merged with the custom configuration.
At the moment default values are not merged as soon as any of the `apm-server.api_key.elasticsearch.*` options is configured, which is unexpected behavior and not aligned with how other configuration options are merged with default values. 
This PR changes the behavior to use default options where no dedicated configuration option is provided. This change also allows to add the `required` flag for the Elasticsearch `host` option again, as now the host is always set by default.  …
=> Merge default values with custom API Key Elasticsearch settings

Jenkinsfile
A way to avoid glitches when there are issues to access the public docker registry.
```
docker build -t golang-mage --build-arg GO_VERSION=1.13.8 src/github.com/elastic/apm-server/.ci/docker/golang-mage
Sending build context to Docker daemon   2.56kB
Step 1/7 : ARG GO_VERSION=1.13.8
Step 2/7 : FROM golang:${GO_VERSION}
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
For such, it will retry to build the docker image up to 3 times with some sleep between 2 to 5 seconds.
##
Run the pipeline and cross fingers
=> ci(jenkins): retry build docker image up to 3 times with some sleep

beater/config/config_test.go, beater/config/rum.go
- Merge ES default values to Sourcmeap configuration. (#3355)
=> [7.x] Merge ES default values to Sourcmeap configuration. (#3355)

docs/configuration-rum.asciidoc, docs/configuring-ingest.asciidoc, docs/guide/apm-release-notes.asciidoc
This PR adds links to the [Elasticsearch Geo IP processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/geoip-processor.html) when it's mentioned in the APM Server documentation.
=> [docs] Link to ES Geo IP processor

docker-compose.yml, tests/system/apmserver.py
This is part of the Makefile rewrite.
System test configuration ($ES_URL, etc.) is now defined in the top-level docker-compose.yml. This enables direct use of "docker-compose" commands, rather than having to go through the Makefile. Later we'll remove the test-related variables from the Makefile.
The system tests have been updated in a couple of places to use the same defaults as defined in the top-level docker-compose.yml. The idea is to optimise for use of the docker-compose.yml in the apm-server repo, and not what's in apm-integration-testing, enabling more consistency in our testing.
~- [ ] New and existing [**unit** …
=> Add system test environment variable defaults to docker-compose.yml

Makefile, magefile.go, script/jenkins/windows-build.ps1, script/jenkins/windows-test.ps1
This is part of the Makefile rewrite.
Stop using the common "update" target and move more logic into "mage update". In particular, build fields.yml, include/fields.go, and docs/fields.asciidoc from magefile. This is in line with how other beats do it now.
Since we're not using the common update target, we won't create _meta/kibana.generated any more. AFAICS this isn't needed, as we don't ship dashboards with apm-server, and index patterns are generated dynamically. Hence, update packaging to exclude this directory. …
=> magefile: use mage to build fields assets

docker-compose.yml, tests/system/apmserver.py
- Add system test environment variable defaults to docker-compose.yml (#3369)
=> [7.x] Add system test environment variable defaults to docker-compose.yml (#3369)

.ci/scripts/docker-get-logs.sh, .gitignore, Makefile, tests/Dockerfile
Create a non-root user for running "make system-tests" inside docker-compose. By default the UID will be 1000, but this can be overridden by running "make docker-compose.override.yml".
This target is also triggered by "make system-tests-environment", so existing workflows should not be affected. The file will not be touched if it already exists, to enable modifying the file for other configuration overrides.
Also, I removed the defunct `start-env` and `stop-env` targets, which reference a non-existent tests/docker-compose.yml file.
~- [ ] New and existing [**unit** tests](https://github.com/elastic/apm-server/blob/master/TESTING.md) pass locally …
=> docker-compose: run system tests as non-root user

agentcfg/fetch.go, agentcfg/fetch_test.go, beater/api/config/agent/handler.go, beater/api/config/agent/handler_test.go, changelogs/head.asciidoc, kibana/connecting_client.go, kibana/connecting_client_test.go, tests/kibana.go, vendor/github.com/elastic/beats/libbeat/kibana/client.go
This adds elastic apm instrumentation to the kibana client, and adds context passing to all client methods.
This change allows to gain more insights into outgoing requests to Kibana, as part of the Agent Configuration endpoint. For the moment it adds instrumentation to the APM Server code only, but once [the instrumentation is also added to beats](https://github.com/elastic/beats/pull/16427), the `apmhttp` auto-instrumentation can be leveraged for outgoing calls. 
closes #3185
Start APM Server with `rum` and `kibana` enabled, and start the Elastic Stack. Make a request to the agent config endpoint, e.g. `curl -i …
=> Instrument kibana client with apm go agent

docs/guide/apm-data-model.asciidoc, docs/storage-management.asciidoc
Currently, we have definitions for [`transactions`](https://www.elastic.co/guide/en/apm/get-started/7.6/transactions.html) and [`spans`](https://www.elastic.co/guide/en/apm/get-started/7.6/transactions.html), but not for `stack frames`. This can make understanding the [APM Storage management guide](https://www.elastic.co/guide/en/apm/server/current/sizing-guide.html) difficult. This PR adds a definition for stack frames to the APM data model page, and the Storage management page.
Closes https://github.com/elastic/apm-server/issues/2329.
=> [docs] Explain stack frames

docs/configuration-rum.asciidoc, docs/configuring-ingest.asciidoc, docs/guide/apm-release-notes.asciidoc
- docs: link to {ref} GeoIP processor (#3377)
=> [7.5] docs: link to {ref} GeoIP processor (#3377)

docs/configuration-rum.asciidoc, docs/configuring-ingest.asciidoc, docs/guide/apm-release-notes.asciidoc
- docs: link to {ref} GeoIP processor (#3377)
=> [7.x] docs: link to {ref} GeoIP processor (#3377)

docs/configuration-rum.asciidoc, docs/configuring-ingest.asciidoc, docs/guide/apm-release-notes.asciidoc
- docs: link to {ref} GeoIP processor (#3377)
=> [7.6] docs: link to {ref} GeoIP processor (#3377)

agentcfg/fetch.go, agentcfg/fetch_test.go, beater/api/config/agent/handler.go, beater/api/config/agent/handler_test.go, elasticsearch/client.go, kibana/connecting_client.go, kibana/connecting_client_test.go, tests/kibana.go
- Instrument kibana client with apm go agent (#3359)
=> [7.x] Instrument kibana client with apm go agent (#3359)

changelogs/7.6.asciidoc
- Update changelog to 7.6.1 changes (#3397)
=> [7.6] Update changelog to 7.6.1 changes (#3397)

changelogs/7.6.asciidoc
- Update changelog to 7.6.1 changes (#3397)
=> [7.x] Update changelog to 7.6.1 changes (#3397)

tests/system/apmserver.py, tests/system/test_integration_acm.py, tests/system/test_monitoring.py
Fix agent config system tests:
- adjust to the new Kibana server API routes (https://github.com/elastic/kibana/pull/57767)
- use the admin user for cleaning up indices before tests. We recently changed to using "apm_server_user" by default, and attempts to clean up the ACM index were silently failing, leaving behind data between tests which would cause tests to fail
~- [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~ (no user facing changes)
`make system-tests`
Closes https://github.com/elastic/apm-server/issues/3396
=> tests/system: fix agent config tests

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/authorization/header.go, beater/config/jaeger.go, beater/jaeger/common.go, beater/jaeger/grpc.go, beater/jaeger/grpc_test.go, beater/jaeger/server.go, beater/jaeger/server_test.go, beater/middleware/authorization_middleware.go, changelogs/7.7.asciidoc, docs/jaeger-support.asciidoc, testdata/jaeger/batch_0_authorization.json, tests/system/config/apm-server.yml.j2, tests/system/jaeger_batch_0_auth_tag_removed.approved.json, tests/system/jaeger_batch_0_authorization.approved.json, tests/system/test_jaeger.py
- beater/jaeger: introduce "auth_tag" configuration (#3394)
=> [7.x] beater/jaeger: introduce "auth_tag" configuration (#3394)

.ci/scripts/docker-get-logs.sh, .gitignore, Makefile, tests/Dockerfile
- docker-compose: run system tests as non-root user (#3373)
=> [7.x] docker-compose: run system tests as non-root user (#3373)

_beats/testing/environments/snapshot-oss.yml, _beats/testing/environments/snapshot.yml, tests/system/apmserver.py, tests/system/test_integration_acm.py, tests/system/test_monitoring.py
- tests/system: fix agent config tests (#3400)
=> [7.x] tests/system: fix agent config tests (#3400)

Makefile
Add the `mage` binary back into $PATH for release-manager. In the Makefile we use a compiled magefile, but now also build the mage binary and add it to $PATH just for the release target.
- `rm $(which mage)`
- `make release`
Closes #3417
=> Makefile: add "mage" back to $PATH

docs/ssl-input-settings.asciidoc
Two settings refer to `apm-server.enabled`, instead of `apm-server.ssl.enabled`.
Document changes only
=> [docs] Current SSL settings refer to missing object

TESTING.md, docker-compose.yml
This PR add support to filtering tests in the dockerised version of the system tests (`make docker-system-tests`), which is possible in the regular way of running tests (`make system-tests`)
In order to check this new behavior, please run:
```shell
$ make docker-system-tests SYSTEM_TEST_TARGET=./tests/system/test_integration.py:SourcemappingIntegrationTest.test_backend_error
```
It was not until I ran `make check-full` and the `fields.yml` file was auto-generated at the root directory that the tests started to pass.
=> fix: support filtering tests in the Docker system tests

tests/system/test_tls.py
There is a single test that checks that a non-HTTPS request throws an Exception (see TestSSLEnabledNoClientVerificationTest.test_http_fails), which started to fail in random manner after the upgrade to Python3.
To avoid that the `requests` library reuses connections, we want to encapsulate the requests for this tests in a specific HTTP Session object, so that they are treated as new requests, with their own configuration.
Please run the dockerised version of the tests, which starts up the runtime dependencies (elasticsearch and kibana):
```shell
$ make docker-system-tests SYSTEM_TEST_TARGET=./tests/system/test_tls.py:TestSSLEnabledNoClientVerificationTest.test_http_fails
```
- Closes #3420
=> fix: use a dedicated HTTP Session for the request

tests/system/test_tls.py
- fix: use a dedicated HTTP Session for the request (#3431)
=> [7.x] fix: use a dedicated HTTP Session for the request (#3431)

docs/ssl-input-settings.asciidoc
Forward ports the following commit to master:
* Current SSL settings refer to missing object (#3412)
cc @JohannesMahne , @bmorelli25
=> [master] [docs] Current SSL settings refer to missing object (#3412)

docs/ssl-input-settings.asciidoc
Forward ports the following commit to `7.x`:
* Current SSL settings refer to missing object (#3412)
=> Current SSL settings refer to missing object (#3412)

docs/agent-configuration.asciidoc
Previously, Only `GET` was mentioned in the [Agent Config API documentation](https://www.elastic.co/guide/en/apm/server/7.6/agent-configuration-api.html). This adds API documentation explaining how to poll Agent config via APM Server with a `POST` request.
~~- [ ] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).~~
~~- [ ] My code follows the style guidelines of this project (run `make check-full` for static code checks and linting)~~
~~- [ ] I have rebased my changes on top of the latest master branch~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] New and existing [**unit** …
=> [docs] Add API documentation for Agent config POST

Makefile
Bring back system tests in Docker execution, as because of #3427, the `SYSTEM_TEST_TARGET` environment variable was not populated in the Makefile causing the tests not to be run.
Please run tests as in the CI with `make update docker-system-tests`
- Relates #3427
- Closes #3436
=> fix: Run system tests in docker

Makefile, TESTING.md, docker-compose.yml
Backport #3427 and #3439 to 7.x
=> [7.x] Backport Dockerised system tests improvements

Jenkinsfile
Otherwise, the 1.0.6 is broken as some configuration was changed sometime ago.
=> ci(jenkins): use current tag

script/common.bash
Enable verbose Mage output, so we can more easily diagnose errors in CI. For example, in https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/master/381/pipeline/86 we can see
> [2020-03-10T06:07:10.609Z] Error: some files are not up-to-date. Run 'mage fmt update' then review and commit the changes. Modified: [NOTICE.txt]
But we don't know what the diff is, which might help us understand what caused the problem. By enabling verbose output in Mage, we'll see the diff.
~- [ ] I have …
=> ci: enable verbose mage output in CI

tests/system/test_tls.py
We are going to verify that the code is CURLE_HTTP_RETURNED_ERROR (22): This is returned if CURLOPT_FAILONERROR is set TRUE and the HTTP server returns an error code that is >= 400.
~~- [ ] I have made corresponding changes to the documentation~~
Run:
```shell
$  make docker-system-tests SYSTEM_TEST_TARGET=./tests/system/test_tls.py:TestSSLEnabledNoClientVerificationTest.test_http_fails
```
- Closes #3420
=> fix: use curl as a subprocess to hit the HTTP endpoint

.ci/docker/golang-mage/Dockerfile
- Fix CI Dockerfile paths for go get (#3454)
=> [7.x] Fix CI Dockerfile paths for go get (#3454)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, docs/ssl-input-settings.asciidoc, tests/system/test_tls.py
Update docs and tests to reflect TLS 1.3 as one of the defaults for APM Server SSL input settings.
- ~[ ] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).~
- ~[ ] My code follows the style guidelines of this project (run `make check-full` for static code checks and linting)~
- ~[ ] I have rebased my changes on top of the latest master branch~
- ~[ ] I have made corresponding changes to the documentation~
- ~[ ] I have added tests that prove my fix is effective or that my feature works~
- ~[ ] New and existing [**unit** tests](https://github.com/elastic/apm-server/blob/master/TESTING.md) pass locally with my changes~
-~[ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~
This only …
=> Add TLS 1.3 to input default protocols

script/generate_notice.py
In case the locale is something other than UTF-8,
force the encoding to "utf-8" when reading license
and notice files, in generate_notice.py.
- `rm -f NOTICE.txt && make notice`
- `rm -f NOTICE.txt && LANG=C make notice`
None.
=> script: force UTF-8 encoding when reading licenses

Makefile
When rsync'ing testing/environments from libbeat,
ignore the source permissions. Files in the module
cache are read-only, leading the files added to our
tree to be read-only, causing pain when updating beats.
`make update-beats`
None.
=> Makefile: ignore testing/environments source perms

script/generate_notice.py
- script: force UTF-8 encoding when reading licenses (#3470)
=> [7.x] script: force UTF-8 encoding when reading licenses (#3470)

.ci/docker/golang-mage/Dockerfile
- Fix CI Dockerfile paths for go get (#3454)
=> [7.6] Fix CI Dockerfile paths for go get (#3454)

tests/system/test_tls.py
Follow up on #3435 to also support TLS 1.3 in tests ensuring client cert auth is handled correctly.
- ~[ ] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).~ 
- ~[ ] My code follows the style guidelines of this project (run `make check-full` for static code checks and linting)~ 
- ~[ ] I have rebased my changes on top of the latest master branch~ 
- ~[ ] I have made corresponding changes to the documentation~ 
- ~[ ] I have added tests that prove my fix is effective or that my feature works~ 
- ~[ ] New and existing [**unit** tests](https://github.com/elastic/apm-server/blob/master/TESTING.md) pass locally with my changes~ 
- ~[ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~
No …
=> Update client cert auth tests to TLS 1.3

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, docs/ssl-input-settings.asciidoc, tests/system/test_tls.py
- Add TLS 1.3 to input default protocols (#3464)
=> [7.x] Add TLS 1.3 to input default protocols (#3464)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, docs/ssl-input-settings.asciidoc, tests/system/test_access.py
- Add TLS 1.3 to input default protocols (#3464)
=> [7.6] Add TLS 1.3 to input default protocols (#3464)

docs/agent-configuration.asciidoc
- docs: Add agent config POST documentation (#3375)
=> [7.6] docs: Add agent config POST documentation (#3375)

docs/agent-configuration.asciidoc
- docs: Add agent config POST documentation (#3375)
=> [7.x] docs: Add agent config POST documentation (#3375)

docs/guide/apm-data-model.asciidoc, docs/storage-management.asciidoc
- [docs] Explain stack frames (#3376)
=> [7.6] [docs] Explain stack frames (#3376)

docs/guide/apm-data-model.asciidoc, docs/storage-management.asciidoc
- [docs] Explain stack frames (#3376)
=> [7.x] [docs] Explain stack frames (#3376)

docs/copied-from-beats/docs/command-reference.asciidoc, docs/copied-from-beats/docs/https.asciidoc, docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc, docs/copied-from-beats/docs/monitoring/shared-monitor-config-legacy.asciidoc, docs/copied-from-beats/docs/output-cloud.asciidoc, docs/copied-from-beats/docs/outputconfig.asciidoc, docs/copied-from-beats/docs/outputs-list.asciidoc, docs/copied-from-beats/docs/repositories.asciidoc, docs/copied-from-beats/docs/security/api-keys.asciidoc, docs/copied-from-beats/docs/security/basic-auth.asciidoc, docs/copied-from-beats/docs/security/users.asciidoc, docs/copied-from-beats/docs/shared-ssl-config.asciidoc, docs/copied-from-beats/docs/shared-systemd.asciidoc, docs/copied-from-beats/docs/template-config.asciidoc, docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc, docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc, docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc, docs/copied-from-beats/outputs/redis/docs/redis.asciidoc
This PR pulls in documentation changes from the Beats repo, and adapts some of the changes for APM Server. A follow-up PR will be opened in the Beats repo to persist the necessary changes.
A lot of these changes aren't noteworthy -- this looks to be mostly small changes and some attribute refactoring.
For https://github.com/elastic/apm-server/issues/3458
=> docs: Update documentation from Beats

tests/system/test_apikey_cmd.py
When passing an argument value that starts with a dash to a CLI tool it will be interpreted as a flag instead of a string value, e.g. `-xyz` would be interpreted as `--xyz`, when passed in as e.g. 
`--id -xyz` instead of `--id=-xyz`.
Instead of running `./apm-server apikey info --id -DB06HAB0_bchW-gz4zt` it should be run as `./apm-server apikey info --id="-DB06HAB0_bchW-gz4zt"`.
This PR adapts the python system tests accordingly to avoid test flakyness wherever a value that might start with a dash is passed in to the apikey tests.
~- [ ] I have made corresponding …
=> Fix flaky test for apikey info by id

tests/system/test_apikey_cmd.py
- Fix flaky test for apikey info by id (#3495)
=> [7.x] Fix flaky test for apikey info by id (#3495)

agentcfg/cache_test.go, agentcfg/fetch.go, agentcfg/fetch_test.go, agentcfg/model.go, agentcfg/model_test.go, beater/api/config/agent/handler.go, beater/jaeger/common.go, beater/jaeger/grpc.go, beater/jaeger/grpc_test.go, beater/jaeger/server.go, beater/jaeger/server_test.go, processor/otel/consumer.go, tests/system/config/apm-server.yml.j2, tests/system/jaegergrpc/main.go, tests/system/test_jaeger.py
- [Jaeger] Add gRPC sampling endpoint (#3490)
=> [7.x] [Jaeger] Add gRPC sampling endpoint (#3490)

.ci/docker/golang-mage/Dockerfile, Jenkinsfile, script/jenkins/build.sh, script/jenkins/package.sh, script/jenkins/test-install-packages.sh
- Install modules into build directory for CI (#3456)
=> [7.x] Install modules into build directory for CI (#3456)

docs/guide/apm-data-model.asciidoc
This PR updates links from the APM Overview to the RUM JS agent. These links are broken in the 5.x release of the RUM agent, and need to be fixed before documentation can be built.
While at it, I also updated the Go Agent, so that we don't run into the same problem come release time.
Because this fix is related to an Agent release, the fix needs to be backported further than normal: `7.x`, `7.6`, `7.5`, `7.4`.
For the 5.x release: https://github.com/elastic/docs/pull/1769.
=> [docs] Update RUM and GO Agent labels

docs/guide/apm-data-model.asciidoc
- docs: update agent tags to labels (#3501)
=> [7.6] docs: update agent tags to labels (#3501)

docs/guide/apm-data-model.asciidoc
- docs: update agent tags to labels (#3501)
=> [7.x] docs: update agent tags to labels (#3501)

docs/guide/apm-data-model.asciidoc
- docs: update agent tags to labels (#3501)
=> [7.4] docs: update agent tags to labels (#3501)

docs/guide/apm-data-model.asciidoc
- docs: update agent tags to labels (#3501)
=> [7.5] docs: update agent tags to labels (#3501)

docs/guide/agent-server-compatibility.asciidoc
Adds Agent Server compatibility for version 5.x of the APM RUM Agent
For https://github.com/elastic/apm-agent-rum-js/issues/501
=> docs: Update agent server compatibility for RUM Agent

docs/guide/agent-server-compatibility.asciidoc
- docs: Update agent server compatibility for RUM Agent (#3451)
=> [7.x] docs: Update agent server compatibility for RUM Agent (#3451)

docs/guide/agent-server-compatibility.asciidoc
- docs: Update agent server compatibility for RUM Agent (#3451)
=> [7.6] docs: Update agent server compatibility for RUM Agent (#3451)

docs/guide/agent-server-compatibility.asciidoc
- docs: Update agent server compatibility for RUM Agent (#3451)
=> [7.5] docs: Update agent server compatibility for RUM Agent (#3451)

docs/guide/agent-server-compatibility.asciidoc
- docs: Update agent server compatibility for RUM Agent (#3451)
=> [7.4] docs: Update agent server compatibility for RUM Agent (#3451)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/config/config.go, beater/config/config_test.go, docs/ssl-input-settings.asciidoc, tests/system/test_tls.py
- Changing TLS client_authentication default and cleaning up docs (#3500)
=> [7.x] Changing TLS client_authentication default and cleaning up docs (#3500)

Jenkinsfile, script/jenkins/package-docker-snapshot.sh
Being able to run the hey apm for the given PR when using the commment `jenkins run hey-apm tests please`
Use the GitHub comment and wait for the GitHub check `Hey-Apm` that will cause:
- A github check
- Trigger a build
- Docker image generated an used in the hey-apm pipeline: See [this](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-hey-test-benchmark/detail/apm-hey-test-benchmark/239/pipeline#step-137-log-27)
Caused by https://github.com/elastic/hey-apm/issues/146
Depends on https://github.com/elastic/hey-apm/pull/154 and https://github.com/elastic/hey-apm/pull/155
=> ci(jenkins): run hey-apm with github comment

beater/api/mux.go, beater/api/mux_intake_rum_test.go
- Require a minimum version in the RUM V3 handler. (#3513)
=> [7.x] Require a minimum version in the RUM V3 handler. (#3513)

beater/jaeger/server_test.go, beater/onboarding.go, changelogs/7.7.asciidoc, model/error/event.go, model/error/event_test.go, model/metricset/event.go, model/metricset/event_test.go, model/profile/profile.go, model/profile/profile_test.go, model/sourcemap/payload.go, model/sourcemap/payload_test.go, model/span/event.go, model/span/event_test.go, model/stacktrace.go, model/stacktrace_test.go, model/transaction/event.go, model/transaction/event_test.go, processor/asset/sourcemap/package_tests/processor_test.go, processor/asset/sourcemap/package_tests/test_processor.go, processor/otel/consumer_test.go, processor/stream/package_tests/intake_test_processor.go, processor/stream/processor_test.go, publish/pub.go, sourcemap/store.go, sourcemap/store_test.go, transform/transform.go
- all: propagate context through Transformables (#3515)
=> [7.x] all: propagate context through Transformables (#3515)

processor/stream/benchmark_test.go
This fixes a panic in processor/stream benchmarks, by setting the recently introduced metadata schema field in the Processor type.
See https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/master/401/pipeline/#step-208-log-470:
```
[2020-03-20T07:08:41.373Z] panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[2020-03-20T07:08:41.373Z] 	panic: runtime error: invalid memory address or nil pointer dereference
[2020-03-20T07:08:41.373Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe91c8a]
[2020-03-20T07:08:41.373Z] 
[2020-03-20T07:08:41.373Z] goroutine 36 [running]:
[2020-03-20T07:08:41.373Z] github.com/santhosh-tekuri/jsonschema.(*Schema).ValidateInterface.func1(0xc0000f7920)
[2020-03-20T07:08:41.373Z] …
```
=> processor/stream: fix panic in benchmarks

docs/getting-started-apm-server.asciidoc, docs/guide/install-and-run.asciidoc
- docs: switch to standard ess trial links (#3514)
=> [7.x] docs: switch to standard ess trial links (#3514)

docs/getting-started-apm-server.asciidoc, docs/guide/install-and-run.asciidoc
- docs: switch to standard ess trial links (#3514)
=> [7.6] docs: switch to standard ess trial links (#3514)

.ci/scripts/build-darwin.sh, .ci/scripts/test-darwin.sh, Jenkinsfile
Build and test the APM Server on Mac since it is a supported platform.
Within the CI
- Enable pyenv to install python3 in the CI Workers.
- Use wrapper to install the go version in the OSX CI Worker, this is a requirement, then call the build and test scripts for Linux.
=> ci(jenkins): support OSX builds

.ci/scripts/build-darwin.sh, .ci/scripts/test-darwin.sh, Jenkinsfile
- ci(jenkins): support OSX build and tests (#3522)
=> [7.x] ci(jenkins): support OSX build and tests (#3522)

changelogs/6.8.asciidoc, script/check_changelogs.py
This PR syncs the 6.8.7 CL (https://github.com/elastic/apm-server/pull/3409) and removes `7.5` from the list of `SUPPORTED_VERSIONS` in `check_changelogs.py`.
=> docs: sync changelogs and remove 7.5 from check_changelogs

docs/configure-kibana-endpoint.asciidoc, docs/jaeger-support.asciidoc
Adds documentation for Jaeger sampling, including limitations and caveats.
For https://github.com/elastic/apm-server/issues/3487.
PR: https://github.com/elastic/apm-server/pull/3490.
=> [docs] Add jaeger sampling docs

changelogs/6.8.asciidoc
- docs: sync changelogs and remove 7.5 from check_changelogs (#3531)
=> [7.x] docs: sync changelogs (#3531)

changelogs/6.8.asciidoc
- docs: sync changelogs and remove 7.5 from check_changelogs (#3531)
=> [7.6] docs: sync changelogs (#3531)

docs/configure-kibana-endpoint.asciidoc, docs/jaeger-support.asciidoc
- docs: add jaeger sampling docs (#3493)
=> [7.x] docs: add jaeger sampling docs (#3493)

docs/secure-communication-agents.asciidoc
Solves https://github.com/elastic/apm-agent-dotnet/issues/464. 
Link secure communication related configs for .NET.
=> [Doc] Add .NET Config links to Secure communication with APM Agents

docs/secure-communication-agents.asciidoc
- Update secure-communication-agents.asciidoc (#3538)
=> [7.6] Update secure-communication-agents.asciidoc (#3538)

beater/config/config_test.go, beater/config/instrumentation.go, beater/config/instrumentation_test.go, beater/server.go
This backports some minor changes from `master` to `7.x` to keep diffs smal. 
=> [7.x] Fix minor diff to master

changelogs/7.7.asciidoc
- Add changelog for 7.7 (#3547)
=> [7.x] Add changelog for 7.7 (#3547)

beater/api/asset/sourcemap/handler.go, beater/api/config/agent/handler.go, beater/api/expvar.go, beater/api/intake/handler.go, beater/api/mux.go, beater/api/profile/handler.go, beater/api/root/handler.go, beater/jaeger/grpc.go, beater/jaeger/http.go, beater/middleware/monitoring_middleware_test.go, beater/request/result_test.go, changelogs/head.asciidoc, decoder/req_decoder.go, model/error/event.go, model/metricset/event.go, model/sourcemap/payload.go, model/span/event.go, model/transaction/event.go
Extend the `/debug/vars` handler to publish all metrics from the default libbeat/monitoring registry, like libbeat does when you start the beat with `-httpprof`:
https://github.com/elastic/beats/blob/d5289fc39baf183ddc26a79f8ccef180a720c8b1/libbeat/service/service.go#L130-L153
The reason for doing this is so we can access pipeline metrics, e.g. to check if the server has events in its queue (https://github.com/elastic/apm-server/issues/3520#issuecomment-603110428).
- `apm-server -E apm-server.expvar.enabled=true`
- `curl http://localhost:8200/debug/vars`
- Make sure "libbeat.output.*" and "apm-server.*" metrics are reported, as well as …
=> Report all libbeat/monitoring metrics in /debug/vars 

docs/spec/transactions/rum_v3_mark.json, docs/spec/transactions/rum_v3_transaction.json, model/transaction/event.go, model/transaction/event_test.go, model/transaction/generated/schema/rum_v3_transaction.go, processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
- Spec out transaction marks for RUM V3 (#3526)
=> [7.x] Spec out transaction marks for RUM V3 (#3526)

.ci/docker/Makefile
The golang-mage Docker image is built daily and push to our internal registry, due latest changes on the Dockerfile the tests start failing. This PR fixes the build and test process.
```
hub pr checkout 3563
make -C .ci/docker all-tests
```
=> fix: ci build and test of the golang-mage docker image

beater/api/asset/sourcemap/handler.go, beater/api/profile/handler.go, beater/onboarding.go, model/config.go, model/error/event.go, model/error/event_test.go, model/metricset/event.go, model/metricset/event_test.go, model/profile/profile_test.go, model/span/event.go, model/span/event_test.go, model/transaction/event.go, model/transaction/event_test.go, processor/otel/consumer.go, processor/stream/package_tests/intake_test_processor.go, processor/stream/processor.go, transform/transform.go
Introduce the model.Input type to pass additional context to decoders, containing:
- the raw decoded JSON input
- the "request time", i.e. the time at which the input was received
- decoding configuration -- temporarily, until we have a configurable Decoder type
RequestTime has been removed from transform.Context, and the decoders are now responsible for setting the Timestamp on the model types according to the input semantics.
In a follow-up, I would do the same thing for Metadata: add a Metadata field to model.Input, which would be initialised to the stream metadata value, and remove transform.Context's Metadata field.
The motivation behind these changes is to make the model types complete and self contained, and creating a clear separation of logic between decoding and transformation: …
=> Introduce model.Input for decoding

model/error/event.go, model/error/event_test.go, model/metricset/event.go, model/metricset/event_test.go, model/span/event.go, model/span/event_test.go, model/transaction/event.go, model/transaction/event_test.go, processor/stream/processor.go
Remove the input error parameter from the top-level model types' Decode functions. This is a non-idiomatic pattern which leads to less than ideal performance due to repeatedly checking errors rather than the idiomatic approach of checking once and bailing out early. The input error is always nil in practice for the modified decoders.
I've left the other decoders alone for now, as that's a much bigger change. We should address those as part of https://github.com/elastic/apm-server/issues/3551.
`make test`
None
=> model/...: remove error parameter from decoders

changelogs/7.6.asciidoc
There are only two non-doc commits since 7.6.1. @simitt, they're both yours. Are either worth of a changelog entry?
* Fix CI Dockerfile paths for go get (#3454) (#3471) 
* [7.6] Add TLS 1.3 to input default protocols (#3464) (#3469)
=> [7.6] docs: 7.6.2 release notes

changelogs/6.8.asciidoc, changelogs/7.6.asciidoc, script/check_changelogs.py
* Syncs `7.6.2` and `6.8.8` changelogs.
* Adds `7.7` to `check_changelogs.py`.
=> docs: Sync changelog and add 7.7 to check_changelogs.py

changelogs/6.8.asciidoc, changelogs/7.6.asciidoc
* docs: 6.8.8 release notes (#3529)
* docs: 7.6.2 changelog (#3530)
=> [7.x] docs: Sync changelog

changelogs/6.8.asciidoc, changelogs/7.6.asciidoc
* docs: 6.8.8 release notes (#3529)
* docs: 7.6.2 changelog (#3530)
=> [7.7] docs: Sync changelog

changelogs/6.8.asciidoc
* docs: 6.8.8 release notes (#3529)
=> [7.6] docs: Sync changelog

docs/secure-communication-agents.asciidoc
All Agents now have API key documentation. This PR updates the linking from APM Server --> APM Agent to make it easier for users to configure API keys.
Links still need to be added in the following Agent References:
=> docs: Update agent links for API keys

docs/guide/apm-doc-directory.asciidoc
This PR fixes an outstanding _to do_ in the doc directory. Previously, the doc directory linked directly to the self installation page for APM Server. It now links to the [getting started page](https://www.elastic.co/guide/en/apm/server/7.6/getting-started-apm-server.html), which highlights the different methods of installing APM Server.
=> docs: Cloud first doc directory

docs/secure-communication-agents.asciidoc
- docs: update agent links for API keys (#3590)
=> [7.x] docs: update agent links for API keys (#3590)

docs/secure-communication-agents.asciidoc
- docs: update agent links for API keys (#3590)
=> [7.7] docs: update agent links for API keys (#3590)

docs/secure-communication-agents.asciidoc
- docs: update agent links for API keys (#3590)
=> [7.6] docs: update agent links for API keys (#3590)

docs/guide/apm-doc-directory.asciidoc
- docs: cloud first doc directory (#3591)
=> [7.x] docs: cloud first doc directory (#3591)

docs/guide/apm-doc-directory.asciidoc
- docs: cloud first doc directory (#3591)
=> [7.7] docs: cloud first doc directory (#3591)

docs/guide/apm-doc-directory.asciidoc
- docs: cloud first doc directory (#3591)
=> [7.6] docs: cloud first doc directory (#3591)

docs/configuration-rum.asciidoc
This PR adds the `allow_headers` configuration to the RUM config reference in APM Server. ~Additional documentation in the RUM Reference tbd.~
~For~ Closes https://github.com/elastic/apm-server/issues/3578.
=> docs: Add RUM allow_headers configuration

docs/configuration-rum.asciidoc
- docs: Add RUM allow_headers configuration (#3592)
=> [7.x] docs: Add RUM allow_headers configuration (#3592)

docs/configuration-rum.asciidoc
- docs: Add RUM allow_headers configuration (#3592)
=> [7.7] docs: Add RUM allow_headers configuration (#3592)

beater/api/intake/test_approved/InvalidEvent.approved.json, beater/api/intake/test_approved/InvalidMetadata.approved.json, beater/api/profile/handler.go, model/error/event.go, model/error/event_test.go, model/metadata/metadata.go, model/metadata/metadata_test.go, model/metricset/event.go, model/span/event.go, model/span/event_test.go, model/transaction/event.go, model/transaction/event_test.go, processor/stream/package_tests/error_attrs_test.go, processor/stream/processor.go, processor/stream/test_approved_stream_result/testIntegrationResultInvalidEvent.approved.json, processor/stream/test_approved_stream_result/testIntegrationResultInvalidMetadata.approved.json, tests/system/test_integration_logging.py, tests/system/test_requests.py, validation/validator.go
Move JSON-Schema validation into the model decoders, and unexpose the compiled JSON Schema objects.
This started out as something much simpler, moving the common validation code in decoders up to processor/stream, in response to https://github.com/elastic/apm-server/pull/3570#discussion_r400187492. I ended up going this route instead because:
- moving the validation into the decoder itself, moving us closer to more efficient [combined validation/decoding](https://github.com/elastic/apm-server/issues/3551)
- processor/stream shouldn't really care that much about the event structure; when we implement the above point, we'll no longer be operating on a map anyway
This change also removes a source of possible skew between validation and decoders, by ensuring the decoder cannot operate on …
=> model/...: encapsulate schema validation

docs/jaeger-support.asciidoc
Fix a typo in the Jaeger docs. We _do_ remove the auth tag before indexing, so that we don't record secrets.
=> docs: fix typo in Jaeger docs

beater/api/mux.go, beater/api/mux_intake_rum_test.go
- Revert "Require a minimum version in the RUM V3 handler." (#3610)
=> [7.x] Revert "Require a minimum version in the RUM V3 handler." (#3610)

docs/jaeger-support.asciidoc
- docs: fix typo in Jaeger docs (#3607)
=> [7.7] docs: fix typo in Jaeger docs (#3607)

docs/jaeger-support.asciidoc
- docs: fix typo in Jaeger docs (#3607)
=> [7.x] docs: fix typo in Jaeger docs (#3607)

docs/configuration-process.asciidoc, docs/configuration-rum.asciidoc, docs/configuring-ingest.asciidoc, docs/upgrading-to-77.asciidoc, docs/upgrading.asciidoc
* Adds documentation for the new `apm_remove_span_metadata` processor
* Cleans up the original **Parse data using ingest node pipelines** documentation, and adds definitions for the four default processors in the `apm` pipeline
* Adds an **Upgrade to APM Server version 7.7** guide. This walks through the upgrade caveat that @simitt explains in https://github.com/elastic/apm-server/pull/3446#issuecomment-605875117.
* Cleans up the RUM configuration ingest pipeline information. Instead, users are directed to the updated `configuring-ingest` documentation.
I don't quite understand [this](https://github.com/elastic/apm-server/issues/3441#issue-576922757) statement:
> One important caveat is that users with an output other than Elasticsearch need to run setup against Elasticsearch to load the …
=> docs: Update pipeline and processor docs for 7.7

.ci/packer_cache.sh
I initially was tempted to add a retry/sleep command to wrap the packaging stage but it looks like it might cause some other issues, such as the workspace being reused (maybe go doesn't like it) and a bit hard to maintain. 
This is a bit more elegant, based on the packer-cache approach that we use for other projects. 
It will cache the required docker images for the packaging stage in the CI since those docker images are pulled from the docker registry everytime a build is triggered by the master branch. It will help to speed up the builds and avoid any kind of environmental issues with `500` errors.
```
[2020-04-06T12:00:22.040Z] ec813748fdd2: Waiting
[2020-04-06T12:00:22.040Z] docker: Error response from daemon: received unexpected HTTP status: 500 Internal Server Error. …
```
=> packer: cache docker images

docs/configuration-process.asciidoc, docs/configuration-rum.asciidoc, docs/configuring-ingest.asciidoc, docs/upgrading-to-77.asciidoc, docs/upgrading.asciidoc
- docs: update pipeline and processor docs (#3593)
=> [7.7] docs: update pipeline and processor docs (#3593)

docs/configuration-process.asciidoc, docs/configuration-rum.asciidoc, docs/configuring-ingest.asciidoc, docs/upgrading-to-77.asciidoc, docs/upgrading.asciidoc
- docs: update pipeline and processor docs (#3593)
=> [7.x] docs: update pipeline and processor docs (#3593)

model/field/rum_v3_mapping.go
Modify `model/field.Mapper` (and InverseMapper) to stop creating closures, which cause both allocation and CPU overhead. Instead, check `shortFieldNames` and return a different static function depending on its value. Because we call field mappers frequently, this has a noticeable impact on micro-benchmarks.
I've added a benchmark for DecodeMetadata in a separate branch (https://github.com/axw/apm-server/tree/benchmark-metadata-old), as part of https://github.com/elastic/apm-server/pull/3618. I pulled the commit into that branch to compare:
```
name              old time/op    new time/op    delta
DecodeMetadata-8    9.74µs ± 5%    8.93µs ± 2%  -8.40%  (p=0.008 n=5+5)
name              old alloc/op   new alloc/op   delta
DecodeMetadata-8    1.31kB ± 0%    1.26kB ± 0%  -3.66%  (p=0.008 …
```
=> model/field: avoid closures

docs/configuring-output-after.asciidoc
Docs says:
> Fields are optional tags that can be added to any output.
https://www.elastic.co/guide/en/apm/server/7.6/configuring-output.html#libbeat-configuration-fields
Which makes me expect an APM server configuration like the following:
```yml
#-------------------------- Elasticsearch output --------------------------
output.elasticsearch:
hosts: ["localhost:9200"]
fields: {project: "myproject", instance-id: "574734885120952459"}
```
But actually field cannot be placed under a specific output, otherwise `fields` don't get send to it.
Instead, it's necessary to define `fields` under the root configuration like the following:
```yml
fields: {project: "myproject", instance-id: "574734885120952459"}
#-------------------------- Elasticsearch output -------------------------- …
```
=> [Doc] Improvements for APM fields

docs/configuring-output-after.asciidoc
- docs: improvements for APM fields (#3608)
=> [7.7] docs: improvements for APM fields (#3608)

docs/configuring-output-after.asciidoc
- docs: improvements for APM fields (#3608)
=> [7.6] docs: improvements for APM fields (#3608)

beater/api/asset/sourcemap/handler.go, beater/api/profile/handler.go, beater/onboarding.go, model/config.go, model/error/event.go, model/error/event_test.go, model/metricset/event.go, model/metricset/event_test.go, model/profile/profile_test.go, model/span/event.go, model/span/event_test.go, model/transaction/event.go, model/transaction/event_test.go, processor/otel/consumer.go, processor/stream/package_tests/intake_test_processor.go, processor/stream/processor.go, transform/transform.go
- Introduce model.Input for decoding (#3570)
=> [7.x] Introduce model.Input for decoding (#3570)

model/error/event.go, model/error/event_test.go, model/metricset/event.go, model/metricset/event_test.go, model/span/event.go, model/span/event_test.go, model/transaction/event.go, model/transaction/event_test.go, processor/stream/processor.go
- model/...: remove error parameter from decoders (#3571)
=> [7.x] model/...: remove error parameter from decoders (#3571)

beater/api/intake/test_approved/InvalidEvent.approved.json, beater/api/intake/test_approved/InvalidMetadata.approved.json, beater/api/profile/handler.go, model/error/event.go, model/error/event_test.go, model/metadata/metadata.go, model/metadata/metadata_test.go, model/metricset/event.go, model/span/event.go, model/span/event_test.go, model/transaction/event.go, model/transaction/event_test.go, processor/stream/package_tests/error_attrs_test.go, processor/stream/processor.go, processor/stream/test_approved_stream_result/testIntegrationResultInvalidEvent.approved.json, processor/stream/test_approved_stream_result/testIntegrationResultInvalidMetadata.approved.json, tests/system/test_integration_logging.py, tests/system/test_requests.py, validation/validator.go
- model/...: encapsulate schema validation (#3594)
=> [7.x] model/...: encapsulate schema validation (#3594)

beater/api/asset/sourcemap/handler.go, beater/api/config/agent/handler.go, beater/api/expvar.go, beater/api/intake/handler.go, beater/api/mux.go, beater/api/profile/handler.go, beater/api/root/handler.go, beater/jaeger/grpc.go, beater/jaeger/http.go, beater/middleware/monitoring_middleware_test.go, beater/request/result_test.go, decoder/req_decoder.go, model/error/event.go, model/metricset/event.go, model/sourcemap/payload.go, model/span/event.go, model/transaction/event.go
- Report all libbeat/monitoring metrics in /debug/vars  (#3550)
=> [7.x] Report all libbeat/monitoring metrics in /debug/vars  (#3550)

model/field/rum_v3_mapping.go
- model/field: rewrite to avoid closure allocation (#3619)
=> [7.x] model/field: rewrite to avoid closure allocation (#3619)

docs/guide/apm-doc-directory.asciidoc
- docs: update links to apm app reference (#3643)
=> [7.7] docs: update links to apm app reference (#3643)

docs/guide/apm-doc-directory.asciidoc
- docs: update links to apm app reference (#3643)
=> [7.x] docs: update links to apm app reference (#3643)

beater/config/api_key.go, beater/config/rum.go, model/metadata/system.go, model/metricset/event.go, model/metricset/event_test.go, model/metricset/mapstr.go, model/modeldecoder/metricset.go, model/modeldecoder/metricset_test.go
There are a few smallish changes here bundled together, in support of transaction duration aggregations (https://github.com/elastic/apm-server/issues/3485).
Summary:
- export `metadata.System.Hostname`, so its value can be used in aggregation keys
- add `metricset.Transaction.{Result,Root}` fields, to use in aggregation keys
- add `metricset.Sample.{Counts,Values}` fields, for indexing histogram metrics
- use non-pointer fields for `metricset.Metricset` and related types to simplify usage, and reduce allocations
Note that the added fields are only added to the model types, and not the intake API. That will come later, as part of https://github.com/elastic/apm-server/issues/3195.
~- [ ] I have updated …
=> model: enhancements to support transaction aggregations

model/span.go
- model: fix span.transformations metric name (#3674)
=> [7.x] model: fix span.transformations metric name (#3674)

agentcfg/model.go, agentcfg/model_test.go, beater/jaeger/grpc.go, changelogs/head.asciidoc, model/error_test.go, model/span_test.go
When using central config in combination with Jaeger for sampling, the config never shows as having been applied in the Kibana UI. This PR adds a query option when sending a request to Kibana, allowing the APM Server to indicate that agent configuration is applied by the agent.
* Test together with https://github.com/elastic/kibana/pull/63967; right now that means check out the PR branch and [start Kibana local](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#setting-up-your-development-environment)
* Create agent configuration in Kibana
* Run a jaeger agent pointing to the APM Server as collector …
=> Add appliedByAgent flag to agentcfg query.

magefile.go
- suggest make instead (#3680)
=> [7.x] suggest make instead (#3680)

agentcfg/model.go, agentcfg/model_test.go, beater/jaeger/grpc.go
Change agent configuration management query paramert from `applied_by_agent` to `mark_as_applied_by_agent` as suggested in https://github.com/elastic/kibana/pull/63967#discussion_r412963447
see https://github.com/elastic/apm-server/pull/3677
related to https://github.com/elastic/kibana/pull/63967
=> Change name for mark_as_applied_by_agent config option

agentcfg/model.go, agentcfg/model_test.go, beater/jaeger/grpc.go, model/error_test.go, model/span_test.go
- Add appliedByAgent flag to agentcfg query. (#3677)
=> [7.x] Add appliedByAgent flag to agentcfg query. (#3677)

tests/system/apmserver.py, tests/system/es_helper.py, tests/system/kibana.py, tests/system/test_integration_acm.py, tests/system/test_jaeger.py
Use the Kibana APM app's [Agent Configuration API](https://www.elastic.co/guide/en/kibana/master/agent-config-api.html) to delete agent config instead of deleting documents in the Elasticsearch index directly.
`make system-tests`
Fixes https://github.com/elastic/apm-server/issues/3688
=> tests/system: use Kibana REST API to cleanup ACM

agentcfg/model.go, agentcfg/model_test.go, beater/jaeger/grpc.go
- Change name for mark_as_applied_by_agent config option (#3681)
=> [7.x] Change name for mark_as_applied_by_agent config option (#3681)

tests/system/apmserver.py, tests/system/es_helper.py, tests/system/kibana.py, tests/system/test_integration_acm.py, tests/system/test_jaeger.py
- tests/system: use Kibana REST API to cleanup ACM (#3690)
=> [7.x] tests/system: use Kibana REST API to cleanup ACM (#3690)

go.mod, go.sum, x-pack/apm-server/aggregation/txmetrics/aggregator.go
- aggregation/txmetrics: optimise for concurrent writers (#3691)
=> [7.x] aggregation/txmetrics: optimise for concurrent writers (#3691)

.gitignore, beater/beater.go, tests/system/kibana.py
- Remove a duplicated call to close the default tracer (#3703)
=> [7.x] Remove a duplicated call to close the default tracer (#3703)

docs/configuration-process.asciidoc
Docs show "hosts" in configuration instead of correct "host".
* Customer in ticket 519251 noted when using "hosts" APM server only listened on localhost (the default) instead of the configured URL.
* I do find it odd that "host" would be the parameter when the value appears to be an array (in square brackets, that is.)
* I found example config lists "host"
[example config](Example in repo shows correct 'host' parameter: https://github.com/elastic/apm-server/blob/71a6cc116a344d7e89f46999ab0727028b517d21/apm-server.yml#L5-L7)
~~- [ ] My code follows the style guidelines of this project (run `make check-full` for static code checks and linting)~~
~~- [ ] I have rebased my changes on top of the latest master branch~~
~~- [ ] I have added tests that prove my fix is effective or that my feature …
=> Correct apm-server.host in configuration process example

docs/configuration-process.asciidoc
Cherry-picks https://github.com/elastic/apm-server/pull/3649 to `7.x`.
=> docs: correct apm-server.host in configuration process example (#3649)

docs/spec/context.json, docs/spec/http_response.json, docs/spec/message.json, docs/spec/metadata.json, docs/spec/process.json, docs/spec/request.json, docs/spec/rum_v3_context.json, docs/spec/rum_v3_metadata.json, docs/spec/rum_v3_service.json, docs/spec/service.json, docs/spec/system.json, docs/spec/tags.json, docs/spec/timestamp_epoch.json, docs/spec/timestamp_rfc3339.json, docs/spec/transactions/rum_v3_transaction.json, model/error/generated/schema/error.go, model/error/generated/schema/rum_v3_error.go, model/metadata/generated/schema/metadata.go, model/metadata/generated/schema/rum_v3_metadata.go, model/metricset/generated/schema/metricset.go, model/metricset/generated/schema/rum_v3_metricset.go, model/span/generated/schema/rum_v3_span.go, model/span/generated/schema/span.go, model/transaction/generated/schema/rum_v3_transaction.go, model/transaction/generated/schema/transaction.go
Bad ids are confusing the PHP schema validator: https://github.com/swaggest/php-json-schema
This fixes it.
=> Fix typo in spec ids

docs/spec/context.json, docs/spec/http_response.json, docs/spec/message.json, docs/spec/metadata.json, docs/spec/process.json, docs/spec/request.json, docs/spec/rum_v3_context.json, docs/spec/rum_v3_metadata.json, docs/spec/rum_v3_service.json, docs/spec/service.json, docs/spec/system.json, docs/spec/tags.json, docs/spec/timestamp_epoch.json, docs/spec/timestamp_rfc3339.json, docs/spec/transactions/rum_v3_transaction.json, model/error/generated/schema/error.go, model/error/generated/schema/rum_v3_error.go, model/metadata/generated/schema/metadata.go, model/metadata/generated/schema/rum_v3_metadata.go, model/metricset/generated/schema/metricset.go, model/metricset/generated/schema/rum_v3_metricset.go, model/span/generated/schema/rum_v3_span.go, model/span/generated/schema/span.go, model/transaction/generated/schema/rum_v3_transaction.go, model/transaction/generated/schema/transaction.go
- Fix typo in spec ids (#3713)
=> [7.x] Fix typo in spec ids (#3713)

docs/guide/apm-data-model.asciidoc
This PR links the APM Overview's [dropped span](https://www.elastic.co/guide/en/apm/get-started/current/transaction-spans.html#dropped-spans) documentation to each agent's `transaction_max_spans` configuration documentation (L52-L57).
I also decided to update the rest of the content on the page while I had the file open.
http://apm-server_3708.docs-preview.app.elstc.co/diff
Closes https://github.com/elastic/apm/issues/126.
=> docs: link to max spans config

docs/guide/apm-data-model.asciidoc
- docs: link to max spans config (#3708)
=> [7.6] docs: link to max spans config (#3708)

docs/guide/apm-data-model.asciidoc
- docs: link to max spans config (#3708)
=> [7.7] docs: link to max spans config (#3708)

docs/guide/apm-data-model.asciidoc
- docs: link to max spans config (#3708)
=> [7.x] docs: link to max spans config (#3708)

NOTICE.txt, changelogs/head.asciidoc, docs/spec/spans/rum_v3_span.json, docs/spec/spans/span.json, docs/spec/transactions/rum_v3_transaction.json, docs/spec/transactions/transaction.json, model/modeldecoder/span_test.go, model/modeldecoder/transaction_test.go, model/span/generated/schema/rum_v3_span.go, model/span/generated/schema/span.go, model/transaction/generated/schema/rum_v3_transaction.go, model/transaction/generated/schema/transaction.go
Until now the APM Server would accept negative transaction and span durations, which does not make sense. We should reject negative durations, so we don't record junk data.
Recording negative durations would impact our ability to use HDRHistogram in percentile aggregations: https://github.com/elastic/kibana/pull/64758.
I hacked the Go agent to allow it to send negative durations, set the duration to -1, and observed a schema validation error. Normally the Go agent does not allow this; it uses negative values as a sentinel for setting duration based on `now-start`.
Closes https://github.com/elastic/kibana/pull/64758
=> docs/spec: require duration >= 0

docs/guide/apm-data-model.asciidoc
This PR fixes a bug in the metadata overview that condensed three tables into an unformatted mess. It also refreshes the metadata content.
http://apm-server_3278.docs-preview.app.elstc.co/diff
Before:
After:
Closes https://github.com/elastic/apm-server/issues/3719.
=> docs: fix bug in metadata docs

NOTICE.txt, docs/spec/spans/rum_v3_span.json, docs/spec/spans/span.json, docs/spec/transactions/rum_v3_transaction.json, docs/spec/transactions/transaction.json, model/modeldecoder/span_test.go, model/modeldecoder/transaction_test.go, model/span/generated/schema/rum_v3_span.go, model/span/generated/schema/span.go, model/transaction/generated/schema/rum_v3_transaction.go, model/transaction/generated/schema/transaction.go
- docs/spec: require duration >= 0 (#3721)
=> [7.x] docs/spec: require duration >= 0 (#3721)

beater/beater.go, beater/config/config.go, beater/config/config_test.go, beater/config/sampling.go, beater/test_approved_es_documents/TestDropNonSampledTransactions.approved.json, publish/pub.go, sampling/sampling.go, sampling/sampling_test.go, tests/system/config/apm-server.yml.j2, tests/system/drop_unsampled_transactions.approved.json, tests/system/keep_unsampled_transactions.approved.json, tests/system/test_aggregation.py, tests/system/test_sampling.py
- Configuration for dropping non-sampled transactions (#3702)
=> [7.x] Configuration for dropping non-sampled transactions (#3702)

model/modeldecoder/field/rum_v3_mapping.go, processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
=> [7.x] fix typo in subtype (#3747)

NOTICE.txt, _meta/beat.yml, apm-server.docker.yml, apm-server.yml, docs/copied-from-beats/docs/loggingconfig.asciidoc, go.mod, go.sum, magefile.go, testing/environments/docker/elasticsearch/kerberos/init.sh, testing/environments/docker/elasticsearch/kerberos/installkdc.sh, testing/environments/docker/elasticsearch_kerberos/Dockerfile, testing/environments/docker/elasticsearch_kerberos/config/kdc.conf.template, testing/environments/docker/elasticsearch_kerberos/config/krb5.conf, testing/environments/docker/elasticsearch_kerberos/config/krb5.conf.template, testing/environments/docker/elasticsearch_kerberos/healthcheck.sh, testing/environments/docker/elasticsearch_kerberos/scripts/addprinc.sh, testing/environments/docker/elasticsearch_kerberos/scripts/addprincs.sh, testing/environments/docker/elasticsearch_kerberos/scripts/installkdc.sh, testing/environments/docker/elasticsearch_kerberos/start.sh, testing/environments/docker/kafka/Dockerfile, testing/environments/docker/kerberos_kdc/Dockerfile, testing/environments/local.yml
Updates to latest beats changes in `7.x` branch, major changes that are pulled in:
* [change how `apm-server.yml` file is built](https://github.com/elastic/beats/pull/18212)
This PR only adds minimal required changes to be compatible with newly introduced way of building `yml` configuration files. Since libbeat now has a dedicated template file per section, we could change our process and start pulling in templates from libbeat again instead of manually syncing them, but this is out of scope for this update.
* [introduce `logging.ecs` option](https://github.com/elastic/beats/pull/18262) to enable logging with minimal fieldset for ECS
~- [ ] I have added tests that prove my fix is …
=> [7.x]  Update beats framework to 553c92eeff2d 

model/batch.go, model/modeldecoder/error.go, model/modeldecoder/error_test.go, model/modeldecoder/metricset.go, model/modeldecoder/metricset_test.go, model/modeldecoder/span.go, model/modeldecoder/span_test.go, model/modeldecoder/transaction.go, model/modeldecoder/transaction_test.go, processor/otel/consumer.go, processor/stream/processor.go
Change the model.Batch type to store slices of
pointers, rather than structs. This enables us
to reuse the model.Batch (with the new Reset
method), and also avoids some memory copying
in modeldecoder (i.e. where it was decoding to
a heap allocated object, and then copying to
slice element when dereferencing).
In the future we might want to revert to storing
slices of structs, but only when we can safely
reuse a batch. i.e. pool model.Batch objects,
recycling once the publisher has transformed the
model objects to beat.Events.
benchstat, comparing to master:
```
name                                          old time/op    new time/op    delta
BackendProcessor/heavy.ndjson/NoRateLimit-12    31.4ms ± 2%    28.9ms ± 4%   -7.98%  (p=0.008 n=5+5)
name …
```
=> Fix performance degradation

docs/data-ingestion.asciidoc
Minor fix that closes https://github.com/elastic/apm-server/issues/3460.
=> docs: Remove outdated 7.0 update

docs/jaeger-support.asciidoc
This PR adds an example and updates the Jaeger `auth_tag` documentation. I have a couple of questions that I'll add as comments.
I tested this feature with apm-integration-testing:
**APM Server:**
```
./scripts/compose.py start 7.7 \
--apm-server-opt apm-server.jaeger.grpc.enabled=true \
--apm-server-opt apm-server.jaeger.grpc.auth_tag=authorization \
--apm-server-opt apm-server.secret_token=qwerty1234
```
**Jaeger Agent:**
```
docker run --rm -it --name jaeger-agent --network apm-integration-testing -p6831:6831/udp \
-e REPORTER_GRPC_HOST_PORT=apm-server:14250 \
-e AGENT_TAGS="authorization=Bearer qwerty1234" \
jaegertracing/jaeger-agent:latest
```
**Jaeger Hotrod demo:**
```
docker run --rm -it --network apm-integration-testing \
-e JAEGER_AGENT_HOST=jaeger-agent \
-e …
```
=> docs: Update Jaeger auth

docs/guide/apm-data-model.asciidoc
- docs: refresh metadata content (#3728)
=> [7.x] docs: refresh metadata content (#3728)

docs/guide/apm-data-model.asciidoc
- docs: refresh metadata content (#3728)
=> [7.7] docs: refresh metadata content (#3728)

docs/guide/apm-data-model.asciidoc
- docs: refresh metadata content (#3728)
=> [7.6] docs: refresh metadata content (#3728)

Jenkinsfile
The GitHub PR comment has been enabled recently, so there is only one place now to get a highlevel view what the CI build looks like. In order to enhance the build status, let's see if we can aggregate the results from the APM-ITs within the main pipeline.
Run the `apm-integration-testing` test selector pipeline in the parallel stage rather than asynchronous. What does it mean? Pipeline needs to wait for the outcome from the `apm-integration-testing` to be able to aggregate the results in the PR comment
Depends on https://github.com/elastic/apm-integration-testing/pull/835
From 3150 tests (See [latest build](https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/master/lastBuild/testReport/))
To 3356 tests (See [this build](https://apm-ci.elastic.co/job/apm-server/job/apm-server-m …
=> ci: aggregate downstream test results

docs/jaeger-support.asciidoc
- docs: jaeger auth (e7057e53)
=> [7.7] docs: jaeger auth (e7057e53)

docs/jaeger-support.asciidoc
- docs: jaeger auth (e7057e53)
=> [7.8] docs: jaeger auth (e7057e53)

docs/jaeger-support.asciidoc
- docs: jaeger auth (e7057e53)
=> [7.x] docs: jaeger auth (e7057e53)

agentcfg/fetch.go, beater/api/config/agent/handler.go, beater/api/config/agent/handler_test.go
- Clarify error message when unauthorized Kibana connection (#3753)
=> [7.x] Clarify error message when unauthorized Kibana connection (#3753)

Makefile
Update Make `update-beats-module` target to run `go list -m -f {{.Dir}} ...` in the shell command, rather than in Make as a [shell function](https://www.gnu.org/software/make/manual/html_node/Shell-Function.html), to avoid premature expansion. …
=> Makefile: fix update-beats-module

Makefile
- Makefile: fix update-beats-module (#3785)
=> [7.x] Makefile: fix update-beats-module (#3785)

Makefile
- Makefile: fix update-beats-module (#3785)
=> [7.8] Makefile: fix update-beats-module (#3785)

agentcfg/fetch.go, beater/api/config/agent/handler.go, beater/api/config/agent/handler_test.go
- Clarify error message when unauthorized Kibana connection (#3753)
=> [7.8] Clarify error message when unauthorized Kibana connection (#3753)

NOTICE.txt, go.mod, go.sum
Update the `go-elasticsearch` dependency to the `7.8` branch.
`make test`
=> [7.8] go es

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, docs/copied-from-beats/docs/loggingconfig.asciidoc, docs/copied-from-beats/docs/shared-kerberos-config.asciidoc, docs/copied-from-beats/docs/shared-ssl-config.asciidoc, docs/copied-from-beats/docs/shared-systemd.asciidoc, docs/copied-from-beats/docs/shared-template-load.asciidoc, docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc, docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc, docs/copied-from-beats/outputs/redis/docs/redis.asciidoc
This PR updates the shared Beats documentation. It also adds documentation for Kerberos, including proposed changes to APM Server's yml config files in 1cb76a6. Based on https://github.com/elastic/beats/pull/16871 and https://github.com/elastic/beats/pull/17927, kerberos settings have been added to the Elasticsearch output, Kafka output, and X-pack Monitoring sections of those files.
For https://github.com/elastic/observability-dev/issues/833.
=> docs: Update documentation copied from Beats

elasticsearch/config_test.go
Additions to libbeat config are not checked. Beats added Kerberos auth support, which we should mirror in our client (#3794). To make sure we keep on top of libbeat config changes, we should update the test to add a list of known fields in libbeat's config that we explicitly don't mirror.
~- [ ] Elastic Cloud Enterprise …
=> elasticsearch: add known unhandled libbeat config to test

elasticsearch/config_test.go
- elasticsearch: add known unhandled libbeat config (#3800)
=> [7.x] elasticsearch: add known unhandled libbeat config (#3800)

beater/beater.go, beater/beater_test.go, beater/server.go, beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json, beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json, beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json, beater/tracing_test.go, main.go, x-pack/apm-server/cmd/root_test.go, x-pack/apm-server/main.go
Rather than passing in a RunServerFunc to CreatorParams,
pass in a function that can wrap a RunServerFunc. This
enables us to run the tracer server with an overridden reporter,
such as the one provided by the transaction histogram
aggregator.
We unexport beater.RunServer to ensure wrappers do not
mistakenly call it directly, rather than going through the
RunServerFunc provided to them.
~- [ ] …
=> beater: CreatorParams.RunServer -> WrapRunServer

beater/beater.go, beater/beater_test.go, beater/server.go, beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json, beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json, beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json, beater/tracing_test.go, main.go, x-pack/apm-server/cmd/root_test.go, x-pack/apm-server/main.go
- beater: CreatorParams.RunServer -> WrapRunServer (#3803)
=> [7.x] beater: CreatorParams.RunServer -> WrapRunServer (#3803)

docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
- docs: update links to logstash getting started (#3807)
=> [7.8] docs: update links to logstash getting started (#3807)

docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
- docs: update links to logstash getting started (#3807)
=> [7.x] docs: update links to logstash getting started (#3807)

docs/breaking-changes.asciidoc, docs/copied-from-beats/docs/outputs-list.asciidoc, docs/copied-from-beats/docs/shared-kerberos-config.asciidoc, docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc, docs/upgrading-to-65.asciidoc, docs/upgrading-to-70.asciidoc, docs/upgrading-to-77.asciidoc, docs/upgrading.asciidoc
* Fixes a broken doc structure introduced by the new Kerberos docs. See https://github.com/elastic/beats/pull/18677 for more information.
* Fixes a problem with the heading levels of the Upgrade section that caused content to be nested incorrectly in the TOC.
=> docs: Update kerberos and upgrading docs

docs/breaking-changes.asciidoc, docs/copied-from-beats/docs/outputs-list.asciidoc, docs/copied-from-beats/docs/shared-kerberos-config.asciidoc, docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc, docs/upgrading-to-65.asciidoc, docs/upgrading-to-70.asciidoc, docs/upgrading-to-77.asciidoc, docs/upgrading.asciidoc
- docs: Update kerberos and upgrading docs (#3810)
=> [7.x] docs: Update kerberos and upgrading docs (#3810)

docs/breaking-changes.asciidoc, docs/copied-from-beats/docs/outputs-list.asciidoc, docs/copied-from-beats/docs/shared-kerberos-config.asciidoc, docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc, docs/upgrading-to-65.asciidoc, docs/upgrading-to-70.asciidoc, docs/upgrading-to-77.asciidoc, docs/upgrading.asciidoc
- docs: Update kerberos and upgrading docs (#3810)
=> [7.8] docs: Update kerberos and upgrading docs (#3810)

script/are_kibana_saved_objects_updated.py, script/update_kibana_objects.py
Make `scripts/jenkins/sync.sh` work again.
`make are-kibana-objects-updated`
https://github.com/elastic/kibana/issues/65629
=> Update index pattern path

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/api/mux.go, beater/config/rum.go, beater/middleware/response_headers_middleware.go, beater/middleware/response_headers_middleware_test.go
- Support custom response headers for RUM endpoints (#3820)
=> [7.x] Support custom response headers for RUM endpoints (#3820)

x-pack/apm-server/aggregation/txmetrics/aggregator.go
Stop grouping metrics by the full User-Agent string. That was a terrible idea. We'll need to parse User-Agent and include the browser name, and any other things we want to group by in the UI. …
=> aggregation/txmetrics: don't group on user-agent

x-pack/apm-server/aggregation/txmetrics/aggregator.go
- aggregation/txmetrics: don't group on user-agent (#3848)
=> [7.x] aggregation/txmetrics: don't group on user-agent (#3848)

changelogs/6.8.asciidoc
- docs: Sync changelogs (#3844)
=> [7.7] docs: Sync changelogs (#3844)

changelogs/6.8.asciidoc, changelogs/7.7.asciidoc
- docs: Sync changelogs (#3844)
=> [7.8] docs: Sync changelogs (#3844)

changelogs/6.8.asciidoc, changelogs/7.7.asciidoc
- docs: Sync changelogs (#3844)
=> [7.x] docs: Sync changelogs (#3844)

model/modeldecoder/context_test.go, model/modeldecoder/metricset_test.go, utility/data_fetcher.go, utility/data_fetcher_test.go
- Include field name in decoding errors (#3866)
=> [7.x] Include field name in decoding errors (#3866)

docs/breaking-changes.asciidoc, docs/guide/agent-server-compatibility.asciidoc, docs/guide/apm-breaking-changes.asciidoc, docs/upgrading-to-70.asciidoc
- docs: update greater than equal to symbol (#3890)
=> [7.8] docs: update greater than equal to symbol (#3890)

docs/breaking-changes.asciidoc, docs/guide/agent-server-compatibility.asciidoc, docs/guide/apm-breaking-changes.asciidoc, docs/upgrading-to-70.asciidoc
- docs: update greater than equal to symbol (#3890)
=> [7.x] docs: update greater than equal to symbol (#3890)

docs/copied-from-beats/docs/command-reference.asciidoc, docs/copied-from-beats/docs/shared-docker.asciidoc
=> [7.x] [DOCS] Fixes license management link (#3893)

docs/copied-from-beats/docs/command-reference.asciidoc, docs/copied-from-beats/docs/shared-docker.asciidoc
=> [7.8] [DOCS] Fixes license management link (#3893)

docs/copied-from-beats/docs/command-reference.asciidoc, docs/copied-from-beats/docs/shared-docker.asciidoc
=> [7.7] [DOCS] Fixes license management link (#3893)

docs/copied-from-beats/docs/command-reference.asciidoc, docs/copied-from-beats/docs/shared-docker.asciidoc
=> [7.6] [DOCS] Fixes license management link (#3893)

docs/copied-from-beats/docs/command-reference.asciidoc, docs/copied-from-beats/docs/shared-docker.asciidoc
=> [7.5] [DOCS] Fixes license management link (#3893)

.ci/jobs/apm-server.yml
Fix the issue with Jenkins folders without a description
=> [jjbb]: folder description is required

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, docs/ilm-reference.asciidoc, docs/ilm.asciidoc, idxmgmt/ilm/config.go, idxmgmt/ilm/config_test.go, idxmgmt/ilm/supporter_factory.go, tests/system/config/apm-server.yml.j2, tests/system/test_setup_index_management.py
- ILM: restrict customization of alias to suffix. (#3905)
=> [7.x] ILM: restrict customization of alias to suffix. (#3905)

processor/stream/result.go, processor/stream/result_test.go
Instead of printing the full document, only print the message as error string when validation errors occur while processing streaming events. The full document is still returned to the calling agent in the response body. 
Start APM Server and send malformed document to the server, observe that …
=> Only log error message instead of full document body when validation error occurs

processor/stream/result.go, processor/stream/result_test.go
- [logging] avoid logging processing error documents (#3917)
=> [7.x] [logging] avoid logging processing error documents (#3917)

processor/stream/result.go, processor/stream/result_test.go
- [logging] avoid logging processing error documents (#3917)
=> [7.8] [logging] avoid logging processing error documents (#3917)

model/metricset.go, model/metricset_test.go, tests/system/rum_transaction_histogram_metrics.approved.json, tests/system/transaction_histogram_metrics.approved.json, x-pack/apm-server/aggregation/txmetrics/aggregator.go, x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
- aggregation/txmetrics: set timeseries.instance (#3904)
=> [7.x] aggregation/txmetrics: set timeseries.instance (#3904)

docs/copied-from-beats/docs/https.asciidoc, docs/copied-from-beats/docs/security/basic-auth.asciidoc, docs/copied-from-beats/docs/security/users.asciidoc
Updates links to pages that have moved out of the Stack Overview, since that book will be retired after 7.4.
https://github.com/elastic/apm-server/pull/3893
https://github.com/elastic/docs/pull/1870
=> [DOCS] Fixes Stack Overview links

docs/copied-from-beats/docs/https.asciidoc, docs/copied-from-beats/docs/security/basic-auth.asciidoc, docs/copied-from-beats/docs/security/users.asciidoc
- [DOCS] Fixes Stack Overview links (#3925)
Fixes the following broken links:
```
16:32:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/server/7.7/beats-basic-auth.html:
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.7/elasticsearch-security.html
16:32:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/server/7.7/feature-roles.html:
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.7/built-in-roles.html
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.7/elasticsearch-security.html
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.7/security-privileges.html
16:32:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/server/7.7/securing-communication-elasticsearch.html:
16:32:51 …
```
=> [7.7] [DOCS] Fixes Stack Overview links (#3925)

docs/copied-from-beats/docs/https.asciidoc, docs/copied-from-beats/docs/security/basic-auth.asciidoc, docs/copied-from-beats/docs/security/users.asciidoc
- [DOCS] Fixes Stack Overview links (#3925)
Fixes the following broken links:
```
16:32:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/server/7.8/securing-communication-elasticsearch.html:
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.8/elasticsearch-security.html
16:32:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/server/current/securing-communication-elasticsearch.html:
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.8/elasticsearch-security.html
```
=> [7.8] [DOCS] Fixes Stack Overview links (#3925)

docs/copied-from-beats/docs/https.asciidoc, docs/copied-from-beats/docs/security/basic-auth.asciidoc, docs/copied-from-beats/docs/security/users.asciidoc
- [DOCS] Fixes Stack Overview links (#3925)
Fixes the following broken links:
```
16:32:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/server/7.6/beats-basic-auth.html:
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.6/elasticsearch-security.html
16:32:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/server/7.6/feature-roles.html:
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.6/built-in-roles.html
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.6/elasticsearch-security.html
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.6/security-privileges.html
16:32:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/server/7.6/securing-communication-elasticsearch.html:
16:32:51 …
```
=> [7.6] [DOCS] Fixes Stack Overview links (#3925)

docs/copied-from-beats/docs/https.asciidoc, docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc, docs/copied-from-beats/docs/monitoring/monitoring-metricbeat.asciidoc, docs/copied-from-beats/docs/security/basic-auth.asciidoc, docs/copied-from-beats/docs/security/users.asciidoc
- [DOCS] Fixes Stack Overview links (#3925)
Fixes the following broken links:
```
16:32:51 INFO:build_docs:Bad cross-document links:
16:32:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/server/7.5/beats-basic-auth.html:
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.5/elasticsearch-security.html
16:32:51 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/server/7.5/feature-roles.html:
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.5/built-in-roles.html
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.5/built-in-users.html
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.5/elasticsearch-security.html
16:32:51 INFO:build_docs:   - en/elastic-stack-overview/7.5/security-privileges.html
16:32:51 …
```
=> [7.5] [DOCS] Fixes Stack Overview links (#3925)

docs/copied-from-beats/docs/security/users.asciidoc
For https://github.com/elastic/docs/pull/1870.
Fixes:
```
12:12:14 INFO:build_docs:Bad cross-document links:
12:12:14 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/server/7.5/feature-roles.html:
12:12:14 INFO:build_docs:   - en/elastic-stack-overview/7.5/built-in-roles.html
12:12:14 INFO:build_docs:   - en/elastic-stack-overview/7.5/built-in-users.html
```
=> docs: fix two remaining links

docs/jaeger-reference.asciidoc, docs/jaeger-support.asciidoc, model/transaction.go, processor/otel/consumer.go, processor/otel/consumer_test.go, processor/otel/test_approved/transaction_jaeger_sampling_rate.approved.json, x-pack/apm-server/aggregation/txmetrics/aggregator.go, x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
- Extrapolate Jaeger transaction count from reported sampling rate (#3722)
=> [7.x] Extrapolate Jaeger transaction count from reported sampling rate (#3722)

beater/api/intake/handler.go, beater/api/profile/handler.go, beater/middleware/request_metadata_middleware.go, beater/middleware/request_metadata_middleware_test.go, beater/request/context.go, beater/request/context_test.go, beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json, docs/data/elasticsearch/generated/metricsets.json, model/modeldecoder/metadata.go, model/modeldecoder/metadata_test.go, model/modeldecoder/metricset.go, model/modeldecoder/transaction_test.go, processor/stream/benchmark_test.go, processor/stream/package_tests/intake_test_processor.go, processor/stream/package_tests/metadata_attrs_test.go, processor/stream/processor.go, processor/stream/processor_test.go, processor/stream/test_approved_es_documents/testIntakeIntegrationInvalidEvent.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationInvalidJSONEvent.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationMetadataNullValues.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json, processor/stream/test_approved_es_documents/testIntakeRUMV3Errors.approved.json, processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json, tests/system/metricset.approved.json
- Refactor metadata enrichment and fix bug in v3 Intake (#3943)
=> [7.x] Refactor metadata enrichment and fix bug in v3 Intake (#3943)

changelogs/6.8.asciidoc, script/check_changelogs.py
This PR adds release notes for version `6.8.11` of APM Server and updates the `check_changelogs.py` script.
=> [docs] 6.8.11 release notes

changelogs/6.8.asciidoc
- [docs] 6.8.11 release notes (#3952)
=> [7.x] [docs] 6.8.11 release notes (#3952)

changelogs/6.8.asciidoc
- [docs] 6.8.11 release notes (#3952)
=> [7.8] [docs] 6.8.11 release notes (#3952)

changelogs/6.8.asciidoc
- [docs] 6.8.11 release notes (#3952)
=> [6.8] [docs] 6.8.11 release notes (#3952)

.ci/check-changelogs.groovy
It removes the corn trigger form the check changelogs job.
Currently,  check changelogs job runs on a daily basis, every day it fails, only 4-6 days a week it does not fail, and it is OK. This job should be pass only when the changelog is updated so on dates near to the release. Because of that, I've asked to disable the corn and move to use it manually when it is needed.
=> ci: remove cron trigger from the check changelog job

beater/config/config_test.go
Update tests to ensure ssl.{certificate,key} are specified
if ssl is enabled. Beats now ensures certificate and key
are both specified for server TLS configuration; this PR
is a prerequisite to updating our libbeat dependency.
~- [ ] Elastic Cloud on …
=> beater/config: fix TLS config tests

script/common.bash, script/gimme/LICENSE, script/gimme/gimme
Vendor https://github.com/travis-ci/gimme (v1.5.4), rather than fetching it from GitHub. This should help improve resilience to GitHub flakiness.
~- [ ] Elastic Cloud …
=> script: vendor gimme

processor/otel/consumer.go, processor/otel/consumer_test.go, processor/otel/test_approved/span_jaeger_messaging.approved.json
- Use peer.hostname for destination.address if peer.address is not given (#3969)
=> [7.x] Use peer.hostname for destination.address if peer.address is not given (#3969)

changelogs/7.8.asciidoc
This PR adds release notes for 7.8.1. The only commit of note is https://github.com/elastic/apm-server/pull/3917, but there's no changelog entry so it has been excluded.
A note about the service maps issue has been added to the [Kibana release notes](https://www.elastic.co/guide/en/kibana/current/release-notes-7.8.1.html).
=> docs: 7.8.1 release notes

changelogs/7.8.asciidoc
- docs: 7.8.1 release notes (#3980)
=> [7.x] docs: 7.8.1 release notes (#3980)

changelogs/7.8.asciidoc
- docs: 7.8.1 release notes (#3980)
=> [7.9] docs: 7.8.1 release notes (#3980)

changelogs/7.8.asciidoc
- docs: 7.8.1 release notes (#3980)
=> [7.8] docs: 7.8.1 release notes (#3980)

docs/guide/install-and-run.asciidoc
To accommodate including the **Install and run** content in the Observability docs, this PR updates an internal link to external.
Related PR: elastic/observability-docs#16
=> [DOCS] Update internal link to external

docs/guide/install-and-run.asciidoc
- [DOCS] Update internal link to external (#3976)
=> [7.9] [DOCS] Update internal link to external (#3976)

docs/guide/install-and-run.asciidoc
- [DOCS] Update internal link to external (#3976)
=> [7.x] [DOCS] Update internal link to external (#3976)

docs/guide/apm-release-notes.asciidoc
Just updates the link to the new Security documentation. Will open PRs for the new terminology later...
Related to https://github.com/elastic/docs/pull/1898
=> [Docs]Fix broken links to the SIEM documentation

docs/guide/apm-release-notes.asciidoc
- docs: Fix broken links to the SIEM documentation (#3990)
=> [7.x] docs: Fix broken links to the SIEM documentation (#3990)

docs/guide/apm-release-notes.asciidoc
- docs: Fix broken links to the SIEM documentation (#3990)
=> [7.9] docs: Fix broken links to the SIEM documentation (#3990)

docs/breaking-changes.asciidoc, docs/upgrading.asciidoc
- docs: clean up upgrading content (#3979)
=> [7.x] docs: clean up upgrading content (#3979)

docs/breaking-changes.asciidoc, docs/upgrading.asciidoc
- docs: clean up upgrading content (#3979)
=> [7.9] docs: clean up upgrading content (#3979)

docs/breaking-changes.asciidoc, docs/upgrading.asciidoc
- docs: clean up upgrading content (#3979)
=> [7.8] docs: clean up upgrading content (#3979)

docs/copied-from-beats/docs/output-cloud.asciidoc, docs/copied-from-beats/docs/outputs-list.asciidoc, docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc, docs/error-indices.asciidoc, docs/exploring-es-data.asciidoc, docs/metricset-indices.asciidoc, docs/sourcemap-indices.asciidoc, docs/span-indices.asciidoc, docs/transaction-indices.asciidoc
In a nutshell, this PR updates all references to default indices in the APM Server documentation. Here's a detailed list of the changes:
Changes from https://github.com/elastic/beats/pull/20074:
* Renames the "Elastic Cloud" output documentation to "Elasticsearch Service". It updates all terminology and adds tracking links to the ESS product page. It also moves the ESS output documentation to the top of the output list.
* Updates the Elasticsearch output documentation for APM Server. Specifically, it updates the `index` and `indices` default pattern for ILM and non-ILM use-cases. (https://github.com/elastic/apm-server/issues/3870).
* Updates the Elasticsearch output documentation examples for Beats and APM Server. There was a lot of duplication between the [ES …
=> docs: Updates to default index names

docs/guide/install-and-run.asciidoc
This PR adds tagged regions to accommodate content reuse in the Observability docs.
=> [DOCS] Add tagged regions for content reuse

docs/guide/install-and-run.asciidoc
- [DOCS] Add tagged regions for content reuse (#4006)
=> [7.9] [DOCS] Add tagged regions for content reuse (#4006)

docs/guide/install-and-run.asciidoc
- [DOCS] Add tagged regions for content reuse (#4006)
=> [7.x] [DOCS] Add tagged regions for content reuse (#4006)

docs/copied-from-beats/docs/output-cloud.asciidoc, docs/copied-from-beats/docs/outputs-list.asciidoc, docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc, docs/error-indices.asciidoc, docs/exploring-es-data.asciidoc, docs/metricset-indices.asciidoc, docs/sourcemap-indices.asciidoc, docs/span-indices.asciidoc, docs/transaction-indices.asciidoc
- docs: Updates to default index names (#4003)
=> [7.9] docs: Updates to default index names (#4003)

docs/copied-from-beats/docs/output-cloud.asciidoc, docs/copied-from-beats/docs/outputs-list.asciidoc, docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc, docs/error-indices.asciidoc, docs/exploring-es-data.asciidoc, docs/metricset-indices.asciidoc, docs/sourcemap-indices.asciidoc, docs/span-indices.asciidoc, docs/transaction-indices.asciidoc
- docs: Updates to default index names (#4003)
=> [7.x] docs: Updates to default index names (#4003)

.ci/check-packages.groovy
This corrects an error discovered in the newly provisioned pipeline to smoke test the package installation for apm-server:
https://apm-ci.elastic.co/job/apm-server/job/apm-server-check-packages/1/console
=> Prep golang env for package build test

.ci/check-packages.groovy
Fix which applies only to the packaging pipeline
=> Remove specific branch name from packaging job

tests/system/test_pipelines.py
Since the uap-core regexes were updated in
https://github.com/elastic/elasticsearch/pull/59697,
MacOS user-agents are now parsed differently.
Update our test to match the change. …
=> tests/system: update user-agent pipline test

tests/system/test_pipelines.py
- tests/system: update user-agent pipline test (#4018)
=> [7.9] tests/system: update user-agent pipline test (#4018)

NOTICE.txt, go.mod, go.sum
Update modules for 7.9:
- elastic/beats@ab4198642341
- elastic/go-elasticsearch@5d4e304087d6
=> Update beats and go-elasticsearch

docs/version.asciidoc
This PR bumps the version from `6.8.10` --> `6.8.11`.
**Do not merge until release day.**
=> [docs] 6.8.11 version bump

docs/guide/distributed-tracing.asciidoc, docs/guide/opentracing.asciidoc, docs/guide/troubleshooting.asciidoc
- docs: Add agent troubleshooting links (#4024)
=> [7.x] docs: Add agent troubleshooting links (#4024)

docs/guide/distributed-tracing.asciidoc, docs/guide/opentracing.asciidoc, docs/guide/troubleshooting.asciidoc
- docs: Add agent troubleshooting links (#4024)
=> [7.9] docs: Add agent troubleshooting links (#4024)

docs/guide/apm-data-model.asciidoc, docs/guide/distributed-tracing.asciidoc, docs/guide/opentracing.asciidoc, docs/guide/troubleshooting.asciidoc
- docs: Add agent troubleshooting links (#4024)
- docs: fix bug in metadata docs (#3728)
=> [7.8] docs: Add agent troubleshooting links (#4024)

.ci/check-packages.groovy
Uses the Darwin worker now that we have the requisite software installed on the Darwin worker.
=> Use Darwin worker for packaging test job

CHANGELOG.asciidoc, changelogs/7.9.asciidoc, docs/breaking-changes.asciidoc, docs/guide/apm-breaking-changes.asciidoc, docs/guide/apm-release-notes.asciidoc, docs/release-notes.asciidoc
- [docs] 7.9 release notes and breaking changes (#4033)
=> [7.x] [docs] 7.9 release notes and breaking changes (#4033)

docs/guide/apm-release-notes.asciidoc
- [Docs]Replaces SIEM terminology (#4047)
=> [7.x] [Docs]Replaces SIEM terminology (#4047)

docs/guide/apm-release-notes.asciidoc
- [Docs]Replaces SIEM terminology (#4047)
=> [7.9] [Docs]Replaces SIEM terminology (#4047)

.ci/check-packages.groovy
This attempts to work around cases where the Py2 installation with Brew is not functional.
=> Apply Py2 fix for OS X for packaging tests

docs/guide/apm-release-notes.asciidoc
Fixes a link that breaks when this content is pulled into the stack docs.
=> [docs] Fix OpenTelemetry link in release highlights

changelogs/7.9.asciidoc, docs/guide/apm-release-notes.asciidoc, docs/guide/opentelemetry-elastic.asciidoc
- Merge pull request #4042 from bmorelli25/7.9-release-highlights (#4042)
=> [7.x] [docs] Add 7.9 release highlights (#4042)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, docs/ssl-input-settings.asciidoc
Setting a TLS certificate/key pair in apm-server.yml is a
common exercise, as users want to secure communications between
agents and server.
Configuring TLS client certificate authentication (mTLS)
is an uncommon requirement, and unsupported by most agents.
Users occasionally set `ssl.certificate_authorities` without
understanding the impact (makes client cert auth required),
and without needing to.
Because `ssl.certificate_authorities` is mostly for edge cases,
let's remove it from apm-server.yml and just document it in the
elastic.co docs. This will hopefully minimise accidental
configuration.
~- [ ] logging (add log lines, choose appropriate …
=> Remove ssl.certificate_authorities from apm-server.yml

systemtest/apikeycmd_test.go
Ensure API Keys beginning with hyphens are not interpreted as CLI flags. See #3495
Fixes #4062
=> systemtest: fix API Key system test

agentcfg/cache_test.go, beater/authorization/privilege_test.go, decoder/stream_decoder.go, decoder/stream_decoder_test.go, model/metadata_test.go, processor/stream/package_tests/intake_test_processor.go, processor/stream/package_tests/metadata_attrs_test.go, processor/stream/processor.go
Refactor `NDSJONStreamReader` to decode bytes from reader into any given struct instead of creating and returning a `map[string]interface{}`. This is a precondition for decoding directly into models instead of map structs and further on for reusing the structs.
~- [ ] metrics and monitoring (create issue for Kibana team to add metrics to visualizations, e.g. [Kibana#44001]~(https://github.com/elastic/kibana/issues/44001))
~- [ ] …
=> Refactor decoder to take stuct as parameter instead of creating and returning map struct

NOTICE.txt, changelogs/head.asciidoc, elasticsearch/client.go, elasticsearch/client_test.go, elasticsearch/config.go, elasticsearch/config_test.go, elasticsearch/estest/client.go, go.mod, go.sum
Honour the `elasticsearch.headers` config for `api_key` and `source_mapping`. I haven't updated `apm-server.yml` for now because this config is for unusual use cases. I would defer updating the config file or docs until users request the feature.
Update the go-elasticsearch/v8 module to add support for passing "global headers".
See https://github.com/elastic/apm-server/issues/4089
Closes https://github.com/elastic/apm-server/issues/4089
=> elasticsearch: honour "headers" config

beater/beater.go, publish/acker.go, publish/pub.go, publish/pub_test.go, tests/system/test_aggregation.py, x-pack/apm-server/aggregation/txmetrics/aggregator.go, x-pack/apm-server/aggregation/txmetrics/aggregator_test.go, x-pack/apm-server/main.go
- Flush aggregator on shutdown (#3971)
=> [7.x] Flush aggregator on shutdown (#3971)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, docs/ssl-input-settings.asciidoc
- Remove ssl.certificate_authorities from apm-server.yml (#4058)
=> [7.x] Remove ssl.certificate_authorities from apm-server.yml (#4058)

NOTICE.txt, agentcfg/cache_test.go, beater/authorization/privilege_test.go, beater/config/config_test.go, go.mod, go.sum
Update beats to bring in system test fixes and kibana custom headers (#4065).
See #4087
#4065
=> Update beats framework to 89a7faf4ad5e (7.9)

publish/acker.go, publish/pub_test.go
- publish: fix shutdown timeout handling (#4075)
=> [7.x] publish: fix shutdown timeout handling (#4075)

NOTICE.txt, elasticsearch/client.go, elasticsearch/client_test.go, elasticsearch/config.go, elasticsearch/config_test.go, elasticsearch/estest/client.go, go.mod, go.sum
- elasticsearch: honour "headers" config (#4090)
=> [7.9] elasticsearch: honour "headers" config (#4090)

beater/middleware/log_middleware.go, beater/middleware/log_middleware_test.go
- beater/middleware: log event.duration (#4030)
=> [7.x] beater/middleware: log event.duration (#4030)

NOTICE.txt, go.mod, go.sum
Update beats to bring in https://github.com/elastic/beats/pull/20753
`PLATFORMS=linux/amd64 TYPES=docker mage package`
Should build a ubi8-minimal based image: …
=> Update beats framework to 74b9d4a0e53a (7.x)

beater/beater.go, beater/telemetry.go, beater/telemetry_test.go, idxmgmt/supporter_factory.go
- Add telemetry for apm-server configuration (#4055)
=> [7.x] Add telemetry for apm-server configuration (#4055)

beater/config/aggregation.go, beater/config/aggregation_test.go, beater/config/config.go, beater/config/config_test.go, tests/system/config/apm-server.yml.j2, tests/system/test_sampling.py, x-pack/apm-server/aggregation/txmetrics/aggregator.go, x-pack/apm-server/aggregation/txmetrics/aggregator_test.go, x-pack/apm-server/main.go
- Refactor transaction metrics aggregation, rename config (#4083)
=> [7.x] Refactor transaction metrics aggregation, rename config (#4083)

tests/Dockerfile
Copy in approvaltest/go.mod (and systemtest/go.mod for good measure)
to fix `go mod download` at the top level. Also run `go mod download`
for the sub-modules, to speed up repeat runs of docker-system-tests. …
=> tests: fix docker-system-tests

x-pack/apm-server/aggregation/spanmetrics/aggregator.go, x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
Add Span.Outcome to the aggregation key, and include
outcome in the metrics produced. This enables the UI
to calculate edge error rates.
Send some exit spans with …
=> aggregation/spanmetrics: add `event.outcome`

model/metricset.go, model/metricset_test.go, tests/system/rum_transaction_histogram_metrics.approved.json, tests/system/transaction_histogram_metrics.approved.json, x-pack/apm-server/aggregation/txmetrics/aggregator.go, x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
- aggregation/txmetrics: include transaction outcome (#4110)
=> [7.x] aggregation/txmetrics: include transaction outcome (#4110)

beater/config/aggregation.go, beater/config/config_test.go, x-pack/apm-server/aggregation/spanmetrics/aggregator.go, x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go, x-pack/apm-server/aggregation/txmetrics/aggregator.go, x-pack/apm-server/main.go
Add `apm-server.aggregation.service_destinations.max_groups` config, controlling the maximum number of metric groups to recorded each interval. The default value of 10000 should be high enough that it won't be reached under typical circumstances; this control exists to guard against faulty or malicious agents.
I've also increased the default value of `apm-server.aggregation.transactions.max_groups` from 1000 to 10000, which should bring us to the low MBs in terms of max memory usage, while still working for large environments.
~- [ ] documentation~ (no docs yet, should be done separately)
~- [ ] logging (add log lines, choose appropriate log …
=> aggregation/spanmetrics: add max_groups config

.ci/docker/Makefile, .gitignore
Docker image requires some files in the specific folder, let's copy them
```bash
$ make -C .ci/docker all-tests
```
Caused by #4112
=> [CI][docker] prepare required context

model/stacktrace.go
fixes #4119
Remove unnecessary log line for source mapping and change potentially interesting log line from warning to debug level. …
=> Change sourcemap logging

systemtest/apikeycmd_test.go
- systemtest: fix API Key system test (#4063)
=> [7.x] systemtest: fix API Key system test (#4063)

go.mod, log/selectors.go, x-pack/apm-server/sampling/pubsub/config.go, x-pack/apm-server/sampling/pubsub/config_test.go, x-pack/apm-server/sampling/pubsub/pubsub.go, x-pack/apm-server/sampling/pubsub/pubsub_integration_test.go, x-pack/apm-server/sampling/pubsub/pubsub_test.go
Introduce a new package which provides a type for
publishing and subscribing to sampled trace IDs.
This is currently implemented using an imperfect
method of search_after on _seq_no. In the future,
once it eventuates, we should use the [Changes API](https://github.com/elastic/elasticsearch/issues/1242).
~- [ ] Elastic …
=> sampling/pubsub: new package for coordination

processor/otel/consumer.go, processor/otel/consumer_test.go, processor/otel/test_approved/jaeger_sampling_rate.approved.json
- processor/otel: set Span.RepresentativeCount (#4116)
=> [7.x] processor/otel: set Span.RepresentativeCount (#4116)

x-pack/apm-server/aggregation/spanmetrics/aggregator.go, x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
- aggregation/spanmetrics: add event.outcome (#4118)
=> [7.x] aggregation/spanmetrics: add event.outcome (#4118)

processor/otel/consumer.go, processor/otel/consumer_test.go, processor/otel/test_approved/consume_span.approved.json, processor/otel/test_approved/jaeger_sampling_rate.approved.json, processor/otel/test_approved/metadata_jaeger-no-language.approved.json, processor/otel/test_approved/metadata_jaeger-version.approved.json, processor/otel/test_approved/metadata_jaeger.approved.json, processor/otel/test_approved/metadata_jaeger_full-traceid.approved.json, processor/otel/test_approved/metadata_jaeger_minimal.approved.json, processor/otel/test_approved/metadata_minimal.approved.json, processor/otel/test_approved/span_jaeger_http.approved.json, processor/otel/test_approved/span_jaeger_http_status_code.approved.json, processor/otel/test_approved/transaction_jaeger_custom.approved.json, processor/otel/test_approved/transaction_jaeger_full.approved.json, processor/otel/test_approved/transaction_jaeger_no_attrs.approved.json, processor/otel/test_approved/transaction_jaeger_type_component.approved.json, processor/otel/test_approved/transaction_jaeger_type_messaging.approved.json, processor/otel/test_approved/transaction_jaeger_type_request.approved.json, processor/otel/test_approved/transaction_jaeger_type_request_result.approved.json, testdata/jaeger/batch_0.approved.json
- processor/otel: set outcome from status code (#4127)
=> [7.x] processor/otel: set outcome from status code (#4127)

beater/config/aggregation.go, beater/config/config_test.go, x-pack/apm-server/aggregation/spanmetrics/aggregator.go, x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go, x-pack/apm-server/aggregation/txmetrics/aggregator.go, x-pack/apm-server/main.go
- aggregation/spanmetrics: add max_groups config (#4131)
=> [7.x] aggregation/spanmetrics: add max_groups config (#4131)

NOTICE.txt, go.mod, go.sum, x-pack/apm-server/sampling/eventstorage/codec.go, x-pack/apm-server/sampling/eventstorage/jsoncodec.go, x-pack/apm-server/sampling/eventstorage/logger.go, x-pack/apm-server/sampling/eventstorage/sharded.go, x-pack/apm-server/sampling/eventstorage/sharded_bench_test.go, x-pack/apm-server/sampling/eventstorage/storage.go, x-pack/apm-server/sampling/eventstorage/storage_bench_test.go, x-pack/apm-server/sampling/eventstorage/storage_test.go
- sampling/eventstorage: introduce event storage (#4108)
=> [7.x] sampling/eventstorage: introduce event storage (#4108)

go.mod, log/selectors.go, x-pack/apm-server/sampling/pubsub/config.go, x-pack/apm-server/sampling/pubsub/config_test.go, x-pack/apm-server/sampling/pubsub/pubsub.go, x-pack/apm-server/sampling/pubsub/pubsub_integration_test.go, x-pack/apm-server/sampling/pubsub/pubsub_test.go
- sampling/pubsub: new package for coordination (#4139)
=> [7.x] sampling/pubsub: new package for coordination (#4139)

Jenkinsfile
Packaging is something that changes infrequently,
but takes a significant amount of time. Instead of
running it in every build, just run it when Beats
is updated or explicitly requested via a comment.
~- [ ] Elasticsearch …
=> ci: only run Package on Beats update or comment

docs/copied-from-beats/docs/command-reference.asciidoc, docs/feature-roles.asciidoc, docs/secure-communication-agents.asciidoc
- docs: Add required privileges for using API Keys (#4130)
=> [7.9] docs: Add required privileges for using API Keys (#4130)

docs/copied-from-beats/docs/command-reference.asciidoc, docs/feature-roles.asciidoc, docs/secure-communication-agents.asciidoc
- docs: Add required privileges for using API Keys (#4130)
=> [7.x] docs: Add required privileges for using API Keys (#4130)

beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json, beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json, model/modeldecoder/span.go, model/modeldecoder/span_test.go, model/modeldecoder/transaction.go, model/modeldecoder/transaction_test.go, processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json, processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
- Derive outcome from the HTTP status code when available (#4165)
=> [7.x] Derive outcome from the HTTP status code when available (#4165)

Makefile
- Makefile: fix golint target (#4183)
=> [7.x] Makefile: fix golint target (#4183)

systemtest/elasticsearch.go
Fix intermittent CI issues like the following, by retrying ILM policy deletion.
```
[2020-09-10T09:24:20.117Z] === RUN   TestTransactionAggregationShutdown
[2020-09-10T09:24:20.117Z]     elasticsearch.go:120: [400 Bad Request] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Cannot delete policy [apm-rollover-30-days]. It is in use by one or more indices: [apm-8.0.0-error-000001]"}],"type":"illegal_argument_exception","reason":"Cannot delete policy [apm-rollover-30-days]. It is in use by one or more indices: [apm-8.0.0-error-000001]"},"status":400}
```
~- [ ] logging (add log lines, choose appropriate …
=> systemtest: retry deleting ILM policy

systemtest/elasticsearch.go
- systemtest: retry deleting ILM policy (#4186)
=> [7.x] systemtest: retry deleting ILM policy (#4186)

changelogs/head.asciidoc, processor/otel/consumer.go, processor/otel/consumer_test.go, processor/otel/test_approved/metadata_jaeger.approved.json
De-dot metadata labels, like we do for span attributes, to prevent indexing errors caused by our `labels_*` dynamic mapping rules.
1. Enable Jaeger intake
2. Instrument an application with Jaeger, run it with `JAEGER_TAGS=abc.def=123` set (or however process tags are set for the …
=> processor/otel: de-dot metadata labels

processor/otel/consumer.go, processor/otel/consumer_test.go, processor/otel/test_approved/metadata_jaeger.approved.json
- processor/otel: de-dot metadata labels (#4191)
=> [7.9] processor/otel: de-dot metadata labels (#4191)

beater/api/profile/handler_test.go, beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json, docs/spec/cloud.json, docs/spec/metadata.json, docs/spec/rum_v3_metadata.json, model/metadata/generated/schema/metadata.go, model/metadata/generated/schema/rum_v3_metadata.go, model/modeldecoder/metadata_test.go, processor/stream/package_tests/metadata_attrs_test.go, testdata/profile/metadata.json, tests/json_schema.go
- Fix metadata.service.* fields requirements in json schema (#4142)
=> [7.x] Fix metadata.service.* fields requirements in json schema (#4142)

script/jenkins/linux-test.sh
Build apm-server outside of the tests so that the build time isn't included in test timeout. This is particularly important on older branches, where the Docker image may not have cached the module dependencies.
~- [ ] …
=> ci: build apm-server before running systemtests

script/jenkins/linux-test.sh
- ci: build apm-server before running systemtests (#4195)
=> [7.x] ci: build apm-server before running systemtests (#4195)

.ci/check-packages.groovy
This is a minor fix for the packaging pipeline. It aligns the Jenkins pipeline with the correct version of OpenSSL on the OS X workers:
```
worker-c07yx0vrjyvy:openssl mp$ ls -l /usr/local/Cellar/openssl
total 0
drwxr-xr-x  13 elastic  staff  416 Aug 30  2019 1.0.2s
```
=> Use installed version of openssl in packaging tests

processor/otel/consumer.go, processor/otel/consumer_test.go, processor/otel/test_approved/metadata_jaeger.approved.json
- processor/otel: de-dot metadata labels (#4191)
=> [7.x] processor/otel: de-dot metadata labels (#4191)

.ci/check-packages.groovy
After discussion with @v1v we decided to move this job back to a bare metal worker which should be safe and alleviate potential problems with the Python environment on OS X workers.
=> [CI] Swing package tests to bare metal worker

.ci/check-packages.groovy
This removes commands from the job now that we are using bare-metal workers.
=> [CI] Remove OSX-specific commands from packaging pipeline

.ci/check-packages.groovy
This should hopefully fix the errors with Unicode on the packaging tests: https://apm-ci.elastic.co/job/apm-server/job/apm-server-check-packages/23/console
=> [ci] Set UTF-8 for package testing job

systemtest/aggregation_test.go, systemtest/apmservertest/config.go, systemtest/approvals/TestRUMXForwardedFor.approved.json, systemtest/estest/search.go, systemtest/instrumentation_test.go, systemtest/jaeger_test.go, systemtest/monitoring_test.go, systemtest/onboarding_test.go, systemtest/rum_test.go, systemtest/sampling_test.go
Add a system test to ensure X-Forwarded-For is parsed and used for `client.ip`, which is subsequently used for geoIP enrichment.
I've introduced an `estest.Client.ExpectDocs` method to reduce boilerplate around waiting for docs to be indexed, and updated existing tests to use it.
~- [ ] Elastic Cloud Enterprise …
=> systemtest: add test for RUM & X-Forwarded-For

x-pack/apm-server/sampling/groups.go, x-pack/apm-server/sampling/groups_test.go, x-pack/apm-server/sampling/reservoir.go, x-pack/apm-server/sampling/reservoir_test.go
- sampling: add trace group sampling reservoirs (#4182)
=> [7.x] sampling: add trace group sampling reservoirs (#4182)

sampling/sampling.go, sampling/sampling_test.go
- sampling: fix keep_unsampled processor (#4215)
=> [7.x] sampling: fix keep_unsampled processor (#4215)

docs/guide/cross-cluster-search.asciidoc
CCS content is being moved from Kibana to Elasticsearch. This PR updates a link from APM Server to unblock https://github.com/elastic/kibana/pull/77909.
=> docs: point to new CCS content

docs/guide/cross-cluster-search.asciidoc
- docs: point to new CCS content (#4219)
=> [7.x] docs: point to new CCS content (#4219)

docs/guide/cross-cluster-search.asciidoc
- docs: point to new CCS content (#4219)
=> [7.9] docs: point to new CCS content (#4219)

changelogs/7.9.asciidoc
This PR adds release notes for `7.9.2`:
```
==== Bug fixes
* De-dot metadata labels set from process and resource tags to prevent indexing errors {pull}4193[4193]
```
=> docs: 7.9.2 release notes

script/generate_notice.py
- script/generate_notice: add UBI to third-party CSV (#4237)
=> [7.x] script/generate_notice: add UBI to third-party CSV (#4237)

changelogs/7.9.asciidoc
- docs: 7.9.2 release notes (#4227) (#4244)
=> [7.x] docs: 7.9.2 release notes (#4227) (#4244)

model/modeldecoder/modeldecodertest/populator.go, model/modeldecoder/modeldecodertest/stream_decoder.go, model/modeldecoder/modeldecodertest/testdata.go, model/modeldecoder/rumv3/metadata_test.go, model/modeldecoder/rumv3/model_test.go, model/modeldecoder/rumv3/transaction_test.go, model/modeldecoder/v2/decoder.go, model/modeldecoder/v2/metadata_test.go, model/modeldecoder/v2/model.go, model/modeldecoder/v2/model_generated.go, model/modeldecoder/v2/model_test.go, model/modeldecoder/v2/transaction_test.go
This PR fixes a small bug and extends the functionality of the modeldecoder test logic, which uncovered also a bug in the model (using `interface` instead of `mapstr` for some json objects).
* fix small bug in model definition for objects
* fix bug in populator test logic
* restructure validation tests to make them easier extensible for future events
without repetition
I created the PR as draft PR as it is based off of https://github.com/elastic/apm-server/pull/4258, therefore the reviewer can ignore the first commit and focus on the second commit (https://github.com/elastic/apm-server/commit/b35897bf360df9fd0d323b9507e9e789dfd48690).
Apart from the unmerged base this PR is ready for review. 
~- [ ] I have signed the [Contributor License …
=> Decoder v2 tests

model/modeldecoder/generator/cmd/main.go, model/modeldecoder/generator/generator.go, model/modeldecoder/generator/struct.go, model/modeldecoder/v2/decoder.go, model/modeldecoder/v2/error_test.go, model/modeldecoder/v2/model.go, model/modeldecoder/v2/model_generated.go, model/modeldecoder/v2/model_test.go, model/modeldecoder/v2/span_test.go
- Decoder v2: add errors and spans (#4260)
=> [7.x] Decoder v2: add errors and spans (#4260)

docs/error-api.asciidoc, docs/example-intake-events.asciidoc, docs/index.asciidoc, docs/metadata-api.asciidoc, docs/metricset-api.asciidoc, docs/span-api.asciidoc, docs/transaction-api.asciidoc
- docs: update event intake API docs (#4246)
=> [7.9] docs: update event intake API docs (#4246)

docs/error-api.asciidoc, docs/example-intake-events.asciidoc, docs/index.asciidoc, docs/metadata-api.asciidoc, docs/metricset-api.asciidoc, docs/span-api.asciidoc, docs/transaction-api.asciidoc
- docs: update event intake API docs (#4246)
=> [7.x] docs: update event intake API docs (#4246)

systemtest/estest/search.go, systemtest/sampling_test.go
Wait for the expected number of docs to appear, rather than just waiting for a single one.
`cd systemtest && go test -v`
Closes elastic/apm-server#4247
=> systemtest: fix flaky TestKeepUnsampled test

docs/fields.asciidoc
- docs: Update field ref with ECS icon (#4272)
=> [7.x] docs: Update field ref with ECS icon (#4272)

docs/fields.asciidoc
- docs: Update field ref with ECS icon (#4272)
=> [7.10] docs: Update field ref with ECS icon (#4272)

docs/fields.asciidoc
- docs: Update field ref with ECS icon (#4272)
=> [7.9] docs: Update field ref with ECS icon (#4272)

NOTICE.txt, go.mod, go.sum
Created with 
```
go mod edit -replace github.com/dgraph-io/badger/v2=github.com/elastic/badger/v2@v2.2007.2-beats
go build
make notice
```
relates to https://github.com/elastic/beats/pull/21613
=> [7.10] use beats-patched badger

beater/api/intake/test_approved/InvalidEvent.approved.json, beater/api/intake/test_approved/InvalidJSONMetadata.approved.json, model/modeldecoder/v2/decoder.go, processor/stream/test_approved_stream_result/testIntegrationResultInvalidEvent.approved.json, processor/stream/test_approved_stream_result/testIntegrationResultInvalidJSONMetadata.approved.json
Avoid logging any input information on decode error.
APM Server should not log APM agent data on decode errors, it should log as much information as possible to identify the root cause for the failure though. 
https://github.com/json-iterator/go adds input information as context to the error message, which should not be logged. Error information is added hierarchically, but errors are not wrapped, so there is no good way of unwrapping and only keeping the _outer part_ of the error message. 
A possibility I looked into was to use `jsoniter.RegisterTypeDecoderFunc(string, func(ptr unsafe.Pointer, iter *Iterator)` for registering a decoder wrapper for every custom struct, reusing the default json-iter struct decoder, while being able to access and manipulate the `iter.Error` after decoding. …
=> decoder v2: redact input information from decode error

beater/api/intake/test_approved/InvalidEvent.approved.json, beater/api/intake/test_approved/InvalidJSONMetadata.approved.json, model/modeldecoder/v2/decoder.go, processor/stream/test_approved_stream_result/testIntegrationResultInvalidEvent.approved.json, processor/stream/test_approved_stream_result/testIntegrationResultInvalidJSONMetadata.approved.json
- decoder v2: redact input information from decode error (#4286)
=> [7.10] decoder v2: redact input information from decode error (#4286)

docs/guide/obs-integrations.asciidoc
Due to build failures on the [Kibana docs PR](https://github.com/elastic/kibana/pull/79978), this PR updates the link to the Logs app content. 
This update gives us the opportunity to link directly to the Logs app content in the Observability guide, rather than to the new content in the Kibana PR. 
https://github.com/elastic/kibana/pull/79978
=> [DOCS] Update link to Logs app content

systemtest/apmservertest/logs.go, systemtest/apmservertest/server.go
Configure ECS logging, as it is the future of our logging.
Increase the log level to debug, for debugging test failures.
`cd systemtest && go test -v`
None.
=> systemtest: use ECS logging

changelogs/7.9.asciidoc, idxmgmt/supporter.go, idxmgmt/supporter_test.go
A regression was introduced when pulling in libbeat changes from elastic/beats#18854. Libbeat no longer guarantees lower case index names for all outputs, but rather moved the implementation to the standard index manager. APM Server implements its own index manager but did not apply changes when upgrading to libbeat changes. 
This PR fixes the regression by ensuring index names are lowercased when derived from the `event`, and from the `meta`  `alias` or `index` information.   
~- [ ] metrics and monitoring (create issue for Kibana team to add metrics to …
=> fix: ensure ES index names are lowercase

changelogs/7.9.asciidoc, idxmgmt/supporter.go, idxmgmt/supporter_test.go
- fix: ensure ES index names are lowercase (#4295)
=> [7.x] fix: ensure ES index names are lowercase (#4295)

changelogs/7.9.asciidoc, idxmgmt/supporter.go, idxmgmt/supporter_test.go
- fix: ensure ES index names are lowercase (#4295)
=> [7.10] fix: ensure ES index names are lowercase (#4295)

beater/beater.go, beater/config/config.go, beater/config/config_test.go, beater/config/sampling.go, beater/server.go, systemtest/apmservertest/config.go, systemtest/estest/search.go, systemtest/sampling_test.go, x-pack/apm-server/aggregation/spanmetrics/aggregator.go, x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go, x-pack/apm-server/aggregation/txmetrics/aggregator.go, x-pack/apm-server/aggregation/txmetrics/aggregator_test.go, x-pack/apm-server/main.go, x-pack/apm-server/sampling/processor_test.go
Introduce configuration for tail-based sampling, and switch it on. Added a system test which runs two apm-server instances, and shows that tail-sampling works across them.
The configuration is only for testing/development, and is almost certainly going to change before we release anything. Documentation will come later once we've finalised things.
~- [ ] metrics and monitoring (create issue for Kibana team to add metrics to visualizations, e.g. [Kibana#44001](https://github.com/elastic/kibana/issues/44001))~ (later)
~- [ ] telemetry~ (later)
Run apm-server with `-E apm-server.sampling.tail.enabled`. If multiple servers are …
=> Integrate tail-based sampling

systemtest/estest/search.go, systemtest/sampling_test.go
- systemtest: fix flaky TestKeepUnsampled test (#4274)
=> [7.x] systemtest: fix flaky TestKeepUnsampled test (#4274)

systemtest/estest/search.go, systemtest/sampling_test.go
- systemtest: fix flaky TestKeepUnsampled test (#4274)
=> [7.10] systemtest: fix flaky TestKeepUnsampled test (#4274)

changelogs/7.9.asciidoc, idxmgmt/supporter.go, idxmgmt/supporter_test.go
- fix: ensure ES index names are lowercase (#4295)
=> [7.9] fix: ensure ES index names are lowercase (#4295)

changelogs/head.asciidoc, log/ratelimit.go, log/ratelimit_test.go, systemtest/sampling_test.go, x-pack/apm-server/aggregation/txmetrics/aggregator.go, x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Log a warning when the transaction group limit is reached.
This logging is rate limited to once every minute, to avoid
flooding the logs due to high throughput of unique transaction
groups.
- Run apm-server with `apm-server.aggregation.txmetrics.enabled=true`
- Send transactions with unique names in a loop
- Observe that the server will log a warning, but only once per minute
None.
=> aggregation/txmetrics: log warning when group limit is reached

Jenkinsfile
- [CI] run everything for branches/tags (#4308)
=> [7.9] [CI] run everything for branches/tags (#4308)

model/modeldecoder/modeldecodertest/populator.go, model/modeldecoder/rumv3/decoder.go, model/modeldecoder/rumv3/metadata_test.go, model/modeldecoder/rumv3/model_test.go, model/modeldecoder/rumv3/transaction_test.go, model/modeldecoder/v2/decoder.go, model/modeldecoder/v2/error_test.go, model/modeldecoder/v2/metadata_test.go, model/modeldecoder/v2/model_test.go, model/modeldecoder/v2/span_test.go, model/modeldecoder/v2/transaction_test.go
Ensure referenced memory is not used by other entity when input model is reused
Add tests ensuring that reused input model does not accidentially lead to shared memory between two model instances. 
While on it, add some small improvements in the test `populator`.
~- [ ] …
=> Add decoder v2 test for memory reuse

model/modeldecoder/modeldecodertest/populator.go, model/modeldecoder/rumv3/decoder.go, model/modeldecoder/rumv3/metadata_test.go, model/modeldecoder/rumv3/model_test.go, model/modeldecoder/rumv3/transaction_test.go, model/modeldecoder/v2/decoder.go, model/modeldecoder/v2/error_test.go, model/modeldecoder/v2/metadata_test.go, model/modeldecoder/v2/model_test.go, model/modeldecoder/v2/span_test.go, model/modeldecoder/v2/transaction_test.go
- Add decoder v2 test for memory reuse (#4314)
=> [7.x] Add decoder v2 test for memory reuse (#4314)

processor/otel/consumer.go, processor/otel/consumer_test.go, processor/otel/test_approved/transaction_jaeger_full.approved.json
- Use service.version for Metadata.Service.Version when converting a Jaeger span (#4061)
=> [7.10] Use service.version for Metadata.Service.Version when converting a Jaeger span (#4061)

processor/otel/consumer.go, processor/otel/consumer_test.go, processor/otel/test_approved/transaction_jaeger_full.approved.json
- Use service.version for Metadata.Service.Version when converting a Jaeger span (#4061)
=> [7.x] Use service.version for Metadata.Service.Version when converting a Jaeger span (#4061)

model/modeldecoder/modeldecodertest/populator.go, model/modeldecoder/rumv3/decoder.go, model/modeldecoder/rumv3/metadata_test.go, model/modeldecoder/rumv3/model_test.go, model/modeldecoder/rumv3/transaction_test.go, model/modeldecoder/v2/decoder.go, model/modeldecoder/v2/error_test.go, model/modeldecoder/v2/metadata_test.go, model/modeldecoder/v2/model_test.go, model/modeldecoder/v2/span_test.go, model/modeldecoder/v2/transaction_test.go
- Add decoder v2 test for memory reuse (#4314)
=> [7.10] Add decoder v2 test for memory reuse (#4314)

changelogs/7.9.asciidoc, idxmgmt/ilm/config.go, idxmgmt/ilm/config_test.go, tests/system/config/apm-server.yml.j2
Ensure ILM custom index suffixes are lowercased to ensure templates and indices in ES can be created. 
configure APM Server to setup ILM with index-suffixes that are …
=> fix: ensure ES index names are lowercase for ILM

changelogs/7.9.asciidoc, idxmgmt/ilm/config.go, idxmgmt/ilm/config_test.go, tests/system/config/apm-server.yml.j2
- fix: ensure ES index names are lowercase for ILM (#4322)
=> [7.x] fix: ensure ES index names are lowercase for ILM (#4322)

changelogs/7.9.asciidoc, idxmgmt/ilm/config.go, idxmgmt/ilm/config_test.go, tests/system/config/apm-server.yml.j2
- fix: ensure ES index names are lowercase for ILM (#4322)
=> [7.9] fix: ensure ES index names are lowercase for ILM (#4322)

changelogs/7.9.asciidoc, idxmgmt/ilm/config.go, idxmgmt/ilm/config_test.go, tests/system/config/apm-server.yml.j2
- fix: ensure ES index names are lowercase for ILM (#4322)
=> [7.10] fix: ensure ES index names are lowercase for ILM (#4322)

docs/spec/spans/span.json, model/span/generated/schema/span.go
- fix: add type information to span.context.service (#4331)
=> [7.x] fix: add type information to span.context.service (#4331)

NOTICE.txt, beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json, beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json, beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json, beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json, beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json, beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json, beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json, beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json, beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json, beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json, docs/fields.asciidoc, go.mod, go.sum, testing/environments/latest.yml, tests/system/es_helper.py
Run `make update-beats` to bump the version to 7.9.4. …
=> [7.9] Bump version to 7.9.4 (make update-beats)

CHANGELOG.asciidoc, changelogs/6.8.asciidoc, changelogs/7.10.asciidoc, changelogs/head.asciidoc, docs/release-notes.asciidoc
I messed up on https://github.com/elastic/apm-server/pull/4337. Sorry! Fixing in this PR by adding `7.10` RNs to `master` and moving the thank you note from `HEAD` to `7.10`.
=> docs: sync changelogs (take two)

CHANGELOG.asciidoc, changelogs/6.8.asciidoc, changelogs/7.10.asciidoc
Backports:
* docs: 6.8.12 release notes (#4080)
* docs: sync changelogs take two (#4341)
=> [7.x] Backport release note sync

changelogs/6.8.asciidoc, changelogs/7.10.asciidoc
- docs: sync changelogs take two (#4341) 
- [7.x] Backport release note sync (#4342)
=> [7.10] Backport release note sync (#4341)

changelogs/6.8.asciidoc
Backports:
* docs: 6.8.12 release notes (#4080)
* docs: sync changelogs take two (#4341)
=> [7.9] Backport release note sync #4342

systemtest/estest/search.go
ExpectMinDocs should use MinHitsCondition with the supplied `min` parameter, rather than using NonEmptyCondition.
This should fix some of the flakiness in system tests.
This bug would explain failures such as in https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/PR-4328/11/pipeline:
```
=== RUN   TestKeepUnsampled/true
[2020-10-27T04:02:19.341Z]     sampling_test.go:65: 
[2020-10-27T04:02:19.341Z]         	Error Trace:	sampling_test.go:65
[2020-10-27T04:02:19.342Z]         	Error:      	"[{apm-8.0.0-transaction-000001 0mU3aHUB96GvjGMlwl-W %!s(float64=0.2876821) map[@timestamp:2020-10-27T04:01:23.978Z agent:map[name:go version:0.0.0] ecs:map[version:1.6.0] event:map[ingested:2020-10-27T04:01:26.166263922Z outcome:unknown] host:map[architecture:i386 …
```
=> systemtest/estest: fix ExpectMinDocs

processor/stream/package_tests/intake_test_processor.go, processor/stream/package_tests/metricset_attrs_test.go
When [switching to v2 metricset decoder,](https://github.com/elastic/apm-server/pull/4333) the package tests have not been changed accordingly, which is fixed by this PR.
Note: sending samples where `value: null` is now allowed. 
The new decoder checks whether or not a struct value is set by checking if any of its attributes is set. When the required attribute is the only one and it is missing the struct itself is reported as not set, therefore the struct itself is ignored and no error is raised. 
no manual tests required, the PR only touches tests. 
part of #3551
=> decoder v2: adapt metricset package tests

changelogs/7.10.asciidoc, idxmgmt/ilm/config.go, idxmgmt/ilm/config_test.go, idxmgmt/ilm/supporter_factory_test.go
When configuring `ilm.setup.require_policy:false` the customized policy name has been ignored. This fixes the issue
by ensuring the policy name is added to the ILM setup.
The regression was introduced with #3826 …
=> fix: respect configured policyname for ILM

processor/stream/package_tests/intake_test_processor.go, processor/stream/package_tests/metricset_attrs_test.go
- decoder v2: adapt metricset package tests (#4338)
=> [7.x] decoder v2: adapt metricset package tests (#4338)

changelogs/7.10.asciidoc, idxmgmt/ilm/config.go, idxmgmt/ilm/config_test.go, idxmgmt/ilm/supporter_factory_test.go
- fix: respect configured policyname for ILM (#4354)
=> [7.x] fix: respect configured policyname for ILM (#4354)

changelogs/7.10.asciidoc, idxmgmt/ilm/config.go, idxmgmt/ilm/config_test.go, idxmgmt/ilm/supporter_factory_test.go
- fix: respect configured policyname for ILM (#4354)
=> [7.10] fix: respect configured policyname for ILM (#4354)

systemtest/sampling_test.go, x-pack/apm-server/main.go, x-pack/apm-server/sampling/processor.go, x-pack/apm-server/sampling/processor_test.go
Log rate-limited warnings when the maximum number of
dynamic services is reached, causing root transactions
(indirectly, related trace events) to be dropped as a result.
Also, add some monitoring: record the number of events
(transactions and spans) that the tail-sampler has processed,
stored (locally), or explicitly dropped. Report the current LSM
and value log size for Badger. Report the current number of
dynamic service groups.
~- [ ] telemetry~ (config telemetry coming in a followup)
- Run server with monitoring and tail-sampling enabled, with a simple catch-all policy (e.g. only `sample_rate` defined)
- Send 1002 …
=> sampling: add logging and monitoring

docs/configure-kibana-endpoint.asciidoc, docs/configuring.asciidoc, docs/copied-from-beats/docs/outputs-list.asciidoc, docs/transaction-metrics.asciidoc
- docs: Transaction metrics reference (#4345)
=> [7.10] docs: Transaction metrics reference (#4345)

docs/configure-kibana-endpoint.asciidoc, docs/configuring.asciidoc, docs/copied-from-beats/docs/outputs-list.asciidoc, docs/transaction-metrics.asciidoc
- docs: Transaction metrics reference (#4345)
=> [7.x] docs: Transaction metrics reference (#4345)

docs/index.asciidoc
Fixes four links in the Events API intake docs by adding a missing "v".
Closes https://github.com/elastic/apm-server/issues/4372
=> docs: fix bad GitHub links

docs/index.asciidoc
- docs: fix GitHub links (#4375)
=> [7.9] docs: fix GitHub links (#4375)

docs/index.asciidoc
- docs: fix GitHub links (#4375)
=> [7.10] docs: fix GitHub links (#4375)

docs/index.asciidoc
- docs: fix GitHub links (#4375)
=> [7.x] docs: fix GitHub links (#4375)

docs/guide/apm-breaking-changes.asciidoc, docs/guide/index.asciidoc, docs/guide/redirects.asciidoc, docs/upgrading.asciidoc
- docs: remove apm whats new (#4385)
=> [7.x] docs: remove apm whats new (#4385)

docs/guide/apm-breaking-changes.asciidoc, docs/guide/index.asciidoc, docs/guide/redirects.asciidoc, docs/upgrading.asciidoc
- docs: remove apm whats new (#4385)
=> [7.10] docs: remove apm whats new (#4385)

systemtest/approvals/TestServiceDestinationAggregation.approved.json, x-pack/apm-server/aggregation/spanmetrics/aggregator.go, x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
- Add agent name to span/edge metrics. (#4389)
=> [7.10] Add agent name to span/edge metrics. (#4389)

docs/guide/apm-data-model.asciidoc
The `addLabel` API is deprecated in favour of `setLabel` (see https://github.com/elastic/apm-agent-java/pull/1449).
The link is valid, only it will now link to the documentation of `addLabel`, but we will backport our documentation update very soon.
=> Changing addLabel to setLabel

Jenkinsfile
There is no default value for ONLY_DOCS, so only on PR has a value, this makes no stage is run. This PR fix the issue by setting a default value for ONLY_DOCS
=> fix: set default value for ONLY_DOCS env var

Jenkinsfile
- fix: set default value for ONLY_DOCS env var (#4395)
=> [7.10] fix: set default value for ONLY_DOCS env var (#4395)

Jenkinsfile
- fix: set default value for ONLY_DOCS env var (#4395)
=> [7.x] fix: set default value for ONLY_DOCS env var (#4395)

Jenkinsfile
Upload artifacts if PRs to another location.
Upload artifacts to the commit-id folder then the beats-tester pipeline can consume them in another follow up if required
This will allow us to solve the issue of consuming artifacts when there is an uploading process in another build
I triggered manually the [build#2](https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/PR-4400/2/) which caused the package generation as shown below (WIP)
=> Use commit id and pr subfolder in the bucket

docs/breaking-changes.asciidoc
- docs: add missing breaking changes (#4405)
=> [7.x] docs: add missing breaking changes (#4405)

docs/breaking-changes.asciidoc
- docs: add missing breaking changes (#4405)
=> [7.10] docs: add missing breaking changes (#4405)

Jenkinsfile
These are the current GitHub comment triggers
* run tests
* jenkins run tests
* jenkins run the tests
* jenkins run the tests please
* run hey-apm tests
* jenkins run hey-apm tests
* jenkins run the hey-apm tests
* jenkins run the hey-apm tests please
* run package tests
* jenkins run package tests
* jenkins run the package tests
* jenkins run the package tests please
I will keep those for backwards compatibility, but I will add the new simple ones we are using, that are easy to remember
* `/test`
* `/package`
* `/hey-apm`
=> ci: add simper comment triggers

systemtest/elasticsearch.go
In systemtest.CleanupElasticsearch we attempt to the delete ILM policy
in a loop, to account for delayed removal of dependants (template, etc.)
We've seen in some tests (TestTransactionAggregationShutdown) that this
function is causing test timeouts, with the culprit being the loop/`time.Sleep`.
Let's log the error message to see what it doesn't exit.
~- [ ] Elasticsearch …
=> systemtest: log ILM policy deletion errors

Jenkinsfile
- ci: add simper comment triggers (#4399)
=> [7.10] ci: add simper comment triggers (#4399)

Jenkinsfile
- ci: add simper comment triggers (#4399)
=> [7.x] ci: add simper comment triggers (#4399)

docs/guide/apm-release-notes.asciidoc
Had to rewind time for this fix. Fixes a broken link introduced in the `1.7` release of the .NET agent.
Related: https://github.com/elastic/apm-agent-dotnet/pull/1036
=> [7.8] docs: Fix broken .NET agent link

changelogs/7.10.asciidoc, model/modeldecoder/v2/model.go, model/modeldecoder/v2/model_generated.go
The max length requirement was removed when switching to the new decoder logic.
~- [ ] Elasticsearch Service …
=> fix: Add maxLen=1024 requirement to metadata.system.container.id

script/jenkins/package-docker-snapshot.sh
Backport a script to build and push the docker images.
```
[2020-11-12T11:46:39.152Z] + ./script/jenkins/package-docker-snapshot.sh e657ca888bd349ba144f67b6c7347c3b3be3fbea docker.elastic.co/observability-ci/apm-server
[2020-11-12T11:46:39.152Z] /var/lib/jenkins/workspace/apm-server_apm-server-mbp_7.10/src/github.com/elastic/apm-server@tmp/durable-6d65a9b0/script.sh: 1: /var/lib/jenkins/workspace/apm-server_apm-server-mbp_7.10/src/github.com/elastic/apm-server@tmp/durable-6d65a9b0/script.sh: ./script/jenkins/package-docker-snapshot.sh: not found
script returned exit code 127
```
=> fix: backport package-docker-snapshot.sh script

x-pack/apm-server/sampling/config.go, x-pack/apm-server/sampling/config_test.go, x-pack/apm-server/sampling/groups.go, x-pack/apm-server/sampling/processor.go, x-pack/apm-server/sampling/processor_bench_test.go, x-pack/apm-server/sampling/processor_test.go, x-pack/apm-server/sampling/pubsub/pubsubtest/client.go
- sampling: introduce event processor (#4241)
=> [7.x] sampling: introduce event processor (#4241)

systemtest/apmservertest/logs.go, systemtest/apmservertest/server.go
- systemtest: use ECS logging (#4301)
=> [7.x] systemtest: use ECS logging (#4301)

elasticsearch/bulk.go, elasticsearch/client.go, x-pack/apm-server/sampling/config.go, x-pack/apm-server/sampling/config_test.go, x-pack/apm-server/sampling/pubsub/config.go, x-pack/apm-server/sampling/pubsub/config_test.go, x-pack/apm-server/sampling/pubsub/pubsub.go, x-pack/apm-server/sampling/pubsub/pubsub_integration_test.go, x-pack/apm-server/sampling/pubsub/pubsub_test.go, x-pack/apm-server/sampling/pubsub/pubsubtest/client.go
- sampling: use apm-server/elasticsearch.Client (#4285)
=> [7.x] sampling: use apm-server/elasticsearch.Client (#4285)

systemtest/aggregation_test.go, systemtest/go.sum, systemtest/monitoring_test.go, x-pack/apm-server/aggregation/txmetrics/aggregator.go, x-pack/apm-server/aggregation/txmetrics/aggregator_test.go, x-pack/apm-server/main.go
- aggregation/txmetrics: add monitoring (#4287)
=> [7.x] aggregation/txmetrics: add monitoring (#4287)

beater/beater.go, beater/config/config.go, beater/config/config_test.go, beater/config/sampling.go, beater/server.go, systemtest/apmservertest/config.go, systemtest/estest/search.go, systemtest/sampling_test.go, x-pack/apm-server/aggregation/spanmetrics/aggregator.go, x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go, x-pack/apm-server/aggregation/txmetrics/aggregator.go, x-pack/apm-server/aggregation/txmetrics/aggregator_test.go, x-pack/apm-server/main.go, x-pack/apm-server/sampling/processor_test.go
- Integrate tail-based sampling (#4300)
=> [7.x] Integrate tail-based sampling (#4300)

x-pack/apm-server/sampling/processor_test.go
TestProcessLocalTailSampling would sometimes fail due to a timing issue, where a sampling decision may be made part way through processing a batch of events. This is fixed by starting the processor after processing events (i.e. adding events to reservoirs, and storing in local storage).
~- [ ] Elastic Cloud Enterprise …
=> sampling: fix flaky TestProcessLocalTailSampling

beater/config/config_test.go, model/modeldecoder/generator/jsonschema_test.go, script/generate_notice.py, tests/system/apmserver.py, tests/system/libbeat_paths.py, tests/system/test_tls.py, x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
autopep8 will move imports to the top of the file
if they come after statements. Move the sys.path
magic to another file so we can preserve import
ordering.
- Run …
=> Format code, change tests/system to avoid breakage

docs/spec/v2/metricset.json, model/modeldecoder/generator/jsonschema.go, model/modeldecoder/generator/map.go
Handle map value rules without requiring patternProperties in
JSON Schema.
When value rules (e.g. inputTypesVals) are specified, but no
patternKeys rule is specified, then nest the generated schema
under additionalProperties.
This will enable us to remove the patternKeys rules from labels,
tags, etc. when moving label key sanitization into the server,
without dropping label value validation.
~- …
=> modeldecoder/generator: enable additionalProperties subschema

processor/stream/package_tests/error_attrs_test.go, processor/stream/package_tests/metadata_attrs_test.go, processor/stream/package_tests/metricset_attrs_test.go, processor/stream/package_tests/span_attrs_test.go, processor/stream/package_tests/transaction_attrs_test.go, tests/json_schema.go
These tests are redundant with the new modeldecoder code, where we test the generated validation logic directly.
`make test` …
=> package_tests: remove validation tests

systemtest/approvals/TestServiceDestinationAggregation.approved.json, x-pack/apm-server/aggregation/spanmetrics/aggregator.go, x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
- Add agent name to span/edge metrics. (#4389)
=> [7.x] Add agent name to span/edge metrics. (#4389)

systemtest/elasticsearch.go
- systemtest: log ILM deletion errors (#4419)
=> [7.x] systemtest: log ILM deletion errors (#4419)

changelogs/7.10.asciidoc
- docs: sync 7.10.1 changelog (#4483)
This PR ended up only being a blank line as the content mostly existed in 7.x already.
=> [7.x] docs: sync 7.10.1 changelog (#4483)

systemtest/approvals/TestRUMErrorSourcemapping.approved.json, systemtest/rum_test.go, tests/system/test_integration_sourcemap.py
Just migrating one for now, to simplify the R&D into moving source mapping to ingest node.
There were two identical (except for the names) Python system tests; I removed both. I suppose the "changed_index" test was meant to do something different, but right now it's just dead weight.
~- [ ] Elastic Cloud Enterprise …
=> systemtest: migrate one sourcemap test to Go

systemtest/estest/search.go
- systemtest/estest: fix ExpectMinDocs (#4353)
=> [7.x] systemtest/estest: fix ExpectMinDocs (#4353)

log/ratelimit.go, log/ratelimit_test.go, systemtest/sampling_test.go, x-pack/apm-server/aggregation/txmetrics/aggregator.go, x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
- aggregation/txmetrics: log warning when group limit is reached (#4313)
=> [7.x] aggregation/txmetrics: log warning when group limit is reached (#4313)
