elastic/apm-server

- systemtest/elasticsearch.go
- systemtest.CleanupElasticsearch: refresh indices (#4434)
> [7.x] systemtest.CleanupElasticsearch: refresh indices (#4434)

- systemtest/sampling_test.go
- x-pack/apm-server/main.go
- x-pack/apm-server/sampling/processor.go
- x-pack/apm-server/sampling/processor_test.go
- sampling: add logging and monitoring (#4346)
> [7.x] sampling: add logging and monitoring (#4346)

- beater/beater.go
- beater/telemetry.go
- beater/telemetry_test.go
- systemtest/sampling_test.go
- beater: telemetry for tail-based sampling config (#4360)
> [7.x] beater: telemetry for tail-based sampling config (#4360)

- x-pack/apm-server/sampling/processor_test.go
- sampling: fix flaky TestProcessLocalTailSampling (#4451)
> [7.x] sampling: fix flaky TestProcessLocalTailSampling (#4451)

- x-pack/apm-server/sampling/eventstorage/sharded.go
- x-pack/apm-server/sampling/eventstorage/storage.go
- x-pack/apm-server/sampling/processor.go
- x-pack/apm-server/sampling/processor_test.go
- sampling: prevent duplicate publication of remotely tail-sampled trace events (#4438)
> [7.x] sampling: prevent duplicate publication of remotely tail-sampled trace events (#4438)

- NOTICE.txt
- docs/spec/rumv3/error.json
- docs/spec/rumv3/span.json
- docs/spec/rumv3/transaction.json
- docs/spec/v2/error.json
- docs/spec/v2/span.json
- model/modeldecoder/generator/jsonschema.go
The properties for array items should be tested under "items", not added directly to the array object.
???
Talk to @russcam 
Closes #4515
> docs/spec: fix JSON Schema for arrays of objects

- docs/spec/v2/metricset.json
- model/modeldecoder/generator/jsonschema.go
- model/modeldecoder/generator/map.go
- modeldecoder/generator: enable additionalProperties subschema (#4464)
> [7.x] modeldecoder/generator: enable additionalProperties subschema (#4464)

- processor/stream/package_tests/error_attrs_test.go
- processor/stream/package_tests/metadata_attrs_test.go
- processor/stream/package_tests/metricset_attrs_test.go
- processor/stream/package_tests/span_attrs_test.go
- processor/stream/package_tests/transaction_attrs_test.go
- tests/json_schema.go
- package_tests: remove validation tests (#4467)
> [7.x] package_tests: remove validation tests (#4467)

- model/modeldecoder/generator/jsonschema_test.go
- script/generate_notice.py
- tests/system/apmserver.py
- tests/system/libbeat_paths.py
- tests/system/test_tls.py
- Format code, change tests/system to avoid breakage (#4459)
> [7.x] Format code, change tests/system to avoid breakage (#4459)

- Jenkinsfile
The CI is failing on PRs for branch 7.x, the cause is three environment variables undefined on the release stage.
- ~[ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~
- ~[ ] documentation~
- ~[ ] logging (add log lines, choose appropriate log selector, etc.)~
- ~[ ] metrics and monitoring (create issue for Kibana team to add metrics to visualizations, e.g. [Kibana#44001]~(https://github.com/elastic/kibana/issues/44001))
- ~[ ] automated tests (add tests for the code changes, all [**unit** tests](https://github.com/elastic/apm-server/blob/master/TESTING.md) pass locally)~
- ~[ ] telemetry~
- ~[ ] Elasticsearch Service (https://cloud.elastic.co)~
- ~[ ] Elastic Cloud Enterprise …
> fix: missing environment variables

- beater/beater.go
- beater/config/integration.go
- publish/pub.go
- systemtest/approvals/TestDataStreamsEnabled/true.approved.json
> [7.x] Wire agent config (#4486)

- _meta/beat.yml
- apm-server.docker.yml
- apm-server.yml
- beater/middleware/log_middleware.go
- beater/middleware/log_middleware_test.go
- cmd/root.go
- docs/copied-from-beats/docs/loggingconfig.asciidoc
- systemtest/export_test.go
- systemtest/logging_test.go
- tests/system/apmserver.py
- tests/system/config/apm-server.yml.j2
- tests/system/test_integration_acm.py
- tests/system/test_jaeger.py
- Ensure ECS compliant logging when enabled. (#3829)
> [7.x] Ensure ECS compliant logging when enabled. (#3829)

- docs/spec/rumv3/error.json
- docs/spec/rumv3/span.json
- docs/spec/rumv3/transaction.json
- docs/spec/v2/error.json
- docs/spec/v2/span.json
- model/modeldecoder/generator/jsonschema.go
- docs/spec: fix JSON Schema for arrays of objects (#4516)
> [7.x] docs/spec: fix JSON Schema for arrays of objects (#4516)

- systemtest/approvals/TestRUMErrorSourcemapping.approved.json
- systemtest/rum_test.go
- tests/system/test_integration_sourcemap.py
- systemtest: migrate one sourcemap test to Go (#4488)
> [7.x] systemtest: migrate one sourcemap test to Go (#4488)

- docs/guide/apm-data-model.asciidoc
- [docs] Fix typo in Node.js addLabels method name (#4556)
> [7.11] [docs] Fix typo in Node.js addLabels method name (#4556)

- docs/guide/apm-data-model.asciidoc
- [docs] Fix typo in Node.js addLabels method name (#4556)
> [7.10] [docs] Fix typo in Node.js addLabels method name (#4556)

- docs/guide/apm-data-model.asciidoc
- [docs] Fix typo in Node.js addLabels method name (#4556)
> [7.x] [docs] Fix typo in Node.js addLabels method name (#4556)

- docs/guide/opentelemetry-elastic.asciidoc
While spinning up Elastic's OpenTelemetry integration, I noticed the link to `opentelemetry-collector-contrib` was incorrect. This PR fixes the link.
> docs: fix link to otel-contrib

- apmpackage/apm/0.1.0/manifest.yml
Fix the integration package `secret_token` setting, changing its type to "string" rather than "bool".
1. Install the package, and check that a text entry is shown for "Secret token" on the integration settings page in Fleet. Leave the setting empty.
2. Assign the package to a policy, add an agent
3. Observe that no secret token is required (e.g. via the healthcheck endpoint)
4. Set a non-empty value for the secret token
5. Restart elastic-agent
6. Observe that a secret token is now requied
Closes #4572
> apmpackage: change secret_token to string

- docs/guide/opentelemetry-elastic.asciidoc
> [7.10] docs: fix repo link (#4578)

- docs/guide/opentelemetry-elastic.asciidoc
> [7.11] docs: fix repo link (#4578)

- docs/guide/opentelemetry-elastic.asciidoc
> [7.x] docs: fix repo link (#4578)

- cmd/apikey.go
- elasticsearch/security_api.go
The ES InvalidateApiKey API does not support param `id` anymore. Switch to using `ids` instead.
Related https://github.com/elastic/elasticsearch/pull/66671
Do NOT backport this to `7.x` as ES only introduced the `ids` parameter in `7.10`.
Ideally we would derive the used Elasticsearch version and adapt the parameter accordingly. There exists already an issue to [ensure ES client 8.0 can work with 7.x ES](https://github.com/elastic/apm-server/issues/2975), which would be a bigger change and needs more discussion how to tackle this. For now this fixes functionality and system tests in master.
* Run `apm-server apikey invalidate --id "123"` cmd …
> fix: invalidating API Keys against ES master

- changelogs/7.10.asciidoc
- changelogs/7.11.asciidoc
Creates the 7.10.2 release notes with "no significant changes" per https://github.com/elastic/apm-server/commits/7.10.
> docs: add 7.10.2 release notes

- NOTICE.txt
- go.mod
- go.sum
Update go-elasticsearch client to use the `7.11` branch
> Update go-elasticsearch client to 7.11 branch

- docs/breaking-changes.asciidoc
- docs/guide/apm-breaking-changes.asciidoc
- docs: 7.11 breaking changes (#4600)
> [7.11] docs: 7.11 breaking changes (#4600)

- docs/breaking-changes.asciidoc
- docs/guide/apm-breaking-changes.asciidoc
- docs: 7.11 breaking changes (#4600)
> [7.x] docs: 7.11 breaking changes (#4600)

- docs/guide/troubleshooting.asciidoc
- docs/troubleshooting.asciidoc
Until we have a unified location for APM documentation, we maintain troubleshooting docs in a bunch of different places. This PR adds additional links to make it easier for users to find all of our troubleshooting guides, regardless of the page they google into.
> docs: link to other troubleshooting guides

- beater/beater.go
- beater/telemetry.go
- beater/telemetry_test.go
Record the static/root config separately from
apm-server config, the latter of which may be
dynamic in the future (i.e. due to Fleet policy
updates).
1. Run server with monitoring enabled
2. Check telemetry is recorded
Preparation for https://github.com/elastic/apm-server/issues/4376
> beater: separate recording static/dynamic config

- beater/acker.go
- beater/beater.go
- publish/pub.go
In the future we will start and stop multiple publishers.
To avoid blocking the publisher.Stop method unnecessarily
during a config reload, move event ACKing to beater.
1. Run APM Server with a shutdown timeout configured
2. Stop Elasticsearch
3. Send some events
4. Shutdown APM Server, check that the shutdown timeout is honoured
Preparation for https://github.com/elastic/apm-server/issues/4376
> beater: move event ACKer from publisher to beater

- docs/guide/troubleshooting.asciidoc
- docs/troubleshooting.asciidoc
- docs: link to other troubleshooting guides (#4608)
> [7.10] docs: link to other troubleshooting guides (#4608)

- docs/guide/troubleshooting.asciidoc
- docs/troubleshooting.asciidoc
- docs: link to other troubleshooting guides (#4608)
> [7.11] docs: link to other troubleshooting guides (#4608)

- docs/guide/troubleshooting.asciidoc
- docs/troubleshooting.asciidoc
- docs: link to other troubleshooting guides (#4608)
> [7.x] docs: link to other troubleshooting guides (#4608)

- beater/beater.go
- beater/beater_test.go
In the beater tests when we start a server,
we have been relying on the onboarding doc
to be published which contains the listening
address. We use the listening address in
tests to send requests to the server.
When the server runs with data streams enabled
it does not publish an onboarding document.
In order to unit test this mode we need to
stop relying on onboarding docs. This change
switches over to extracting the listening
address from logs, similar to how it is done
in systemtest.
It is possible to configure logp such that the
root logger (and loggers derived from it) are
observable in tests, but this would not work
with parallel tests. Instead, we introduce a
means of injecting a logger into the beater.
`make test`
Required to unit test changes related to …
> beater: stop relying on onboarding in tests

- sourcemap/es_store.go
- sourcemap/es_store_test.go
- sourcemap/test/es_client.go
- fix: avoid panic when sourcemap doc does not contain hit (#4619)
> [7.x] fix: avoid panic when sourcemap doc does not contain hit (#4619)

- apmpackage/apm/0.1.0/data_stream/app_metrics/manifest.yml
- apmpackage/apm/0.1.0/data_stream/error_logs/manifest.yml
- apmpackage/apm/0.1.0/data_stream/internal_metrics/manifest.yml
- apmpackage/apm/0.1.0/data_stream/profile_metrics/manifest.yml
- apmpackage/apm/0.1.0/data_stream/traces/manifest.yml
This won't have any effect until we release a new registry version (soon), but we can get it merged in the meanwhile.
Pre-requisite for https://github.com/elastic/apm-server/issues/4492
> Add dataset_is_prefix field to manifest files

- Makefile
- beater/http.go
- script/autopep8_all.sh
- script/check_goimports.sh
- script/generate_notice.py
- script/goimports.sh
Introduce Makefile targets to check formatting without making changes, and add those targets to the `make check` target. This should simplify checking formatting prior to pushing changes, could be run as a pre-push hook, and avoid reliance on CI for picking up such errors.
1. Modify some Go code to be improperly formatted
2. Run `make check`, it should fail
3. Run `make fmt`, it should fix the formatting
4. Run `make check`, it should no longer fail
5. Modify some Python code to be improperly formatted, repeat steps 2-4
Replaces https://github.com/elastic/apm-server/pull/4456
> Makefile: add check-fmt target

- x-pack/apm-server/sampling/config.go
- x-pack/apm-server/sampling/processor.go
- x-pack/apm-server/sampling/processor_test.go
Fix TestStorageGC by disabling GC (by setting a long interval) while storing events to drive up the vlog size. Enable it only after multiple vlog files have been written. This ensures that GC doesn't remove files while we're still writing, causing the test to never have multiple vlog files.
Also, make the Badger value log file size configurable, so tests can override it with a smaller size.
`go test -race ./x-pack/apm-server/sampling`
Closes #4651
> sampling: fix TestStorageGC

- docs/spec/v2/error.json
- docs/spec/v2/metricset.json
- docs/spec/v2/span.json
- docs/spec/v2/transaction.json
- model/modeldecoder/v2/model.go
Tags were renamed to Labels on the agent side years ago, but it's not super obvious that labels go to `"tags"` in the intake API.
I'm open to better ways to word this addition -- the important thing is that now if you do a Find for `labels`, something actually shows up. :)
> Add note about tags vs labels to json schemas

- docs/spec/v2/error.json
- docs/spec/v2/metricset.json
- docs/spec/v2/span.json
- docs/spec/v2/transaction.json
- model/modeldecoder/v2/model.go
* Add note about tags vs labels to json schemas (#4675)
> [7.x] Add note about tags vs labels to json schemas (#4675)

- systemtest/fleet_test.go
Check error in test to avoid surprises later on.
`cd systemtest && go test -v -run Fleet`
None.
> systemtest: fix missing error check

- beater/beater.go
- beater/config/integration.go
- beater/config/integration_test.go
- beater/server_test.go
If the config received from Elastic Agent/Fleet does not contain an "apm-server" section, return an error. If we don't check, then in this unusual scenario the server will panic when attempting to merge into integration config's (nil pointer) APMServer field.
~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~ (not yet user-facing)
Frankly I don't know how I got into this situation, but Fleet (in Kibana) stopped adding the "apm-server" section into policies. If you can get that to happen, then run an Agent with the APM integration, and check that it fails cleanly rather than panicking.
None.
> beater: ensure Fleet config contains 'apm-server'

- Jenkinsfile
The sendBenchmarks step provides its own Go environment, this moves the step outside the Go Docker container.
closes https://github.com/elastic/apm-server/issues/4662
> ci: fix benchmark stage

- docs/guide/opentelemetry-elastic.asciidoc
- docs: bump Otel ex to otel-java-agent 0.15.0 and otel-collector-contrib 0.19.0 (#4676)
> [7.11] docs: bump Otel ex to otel-java-agent 0.15.0 and otel-collector-contrib 0.19.0 (#4676)

- docs/guide/opentelemetry-elastic.asciidoc
- docs: bump Otel ex to otel-java-agent 0.15.0 and otel-collector-contrib 0.19.0 (#4676)
> [7.x] docs: bump Otel ex to otel-java-agent 0.15.0 and otel-collector-contrib 0.19.0 (#4676)

- docs/guide/opentelemetry-elastic.asciidoc
- docs: bump Otel ex to otel-java-agent 0.15.0 and otel-collector-contrib 0.19.0 (#4676)
> docs: bump Otel to otel-java-agent 0.15.0 and otel-collector-contrib 0.19.0 (#4676)

- Jenkinsfile
- ci: fix benchmark stage (#4672)
> [7.x] ci: fix benchmark stage (#4672)

- Jenkinsfile
- ci: fix benchmark stage (#4672)
> [7.10] ci: fix benchmark stage (#4672)

- Jenkinsfile
- ci: fix benchmark stage (#4672)
> [7.11] ci: fix benchmark stage (#4672)

- systemtest/fleet_test.go
- systemtest/fleettest/client.go
- systemtest/fleettest/error.go
https://github.com/elastic/kibana/issues/90544 is causing the system test to respond with 404 Not Found, despite the policy existing and being successfully deleted.
Update the test to temporarily expect a 404 response to avoid failing all our builds. Once the Kibana bug is resolved this will start failing, and we can again check that no error is returned.
`cd systemtest && go test -v -run Fleet`
Closes https://github.com/elastic/apm-server/issues/4692
> systemtest: compensate for Fleet API bug

- docs/guide/apm-breaking-changes.asciidoc
This PR updates renames the tagged section for the 7.10 breaking changes, since otherwise it appears in both 7.10 and 7.11 docs.
> [DOCS] Make tagged sections for breaking changes unique

- changelogs/7.9.asciidoc
- docs/release-notes.asciidoc
- docs: Add 7.9 cloud metadata known issue (#4691)
> [7.x] docs: Add 7.9 cloud metadata known issue (#4691)

- changelogs/7.9.asciidoc
- docs/release-notes.asciidoc
- docs: Add 7.9 cloud metadata known issue (#4691)
> [7.11] docs: Add 7.9 cloud metadata known issue (#4691)

- changelogs/7.9.asciidoc
- docs/release-notes.asciidoc
- docs: Add 7.9 cloud metadata known issue (#4691)
> [7.10] docs: Add 7.9 cloud metadata known issue (#4691)

- changelogs/7.9.asciidoc
- docs: Add 7.9 cloud metadata known issue (#4691)
> [7.9] docs: Add 7.9 cloud metadata known issue (#4691)

- changelogs/6.8.asciidoc
Adds release notes for `6.8.14`: No significant changes.
> docs: add release notes for 6.8.14

- changelogs/6.8.asciidoc
- docs: add release notes for 6.8.14 (#4697)
> [7.x] docs: add release notes for 6.8.14 (#4697)

- changelogs/6.8.asciidoc
- docs: add release notes for 6.8.14 (#4697)
> [7.11] docs: add release notes for 6.8.14 (#4697)

- changelogs/6.8.asciidoc
- docs: add release notes for 6.8.14 (#4697)
> [7.10] docs: add release notes for 6.8.14 (#4697)

- changelogs/6.8.asciidoc
- docs: add release notes for 6.8.14 (#4697)
> [6.8] docs: add release notes for 6.8.14 (#4697)

- Makefile
The Makefile runs various Go commands as part of variable expansions, for example to identify the beats module and to determine $GOOS. This only works if Go is installed on the machine already.
To better support machines that do not have Go installed, and to avoid running builds with mixed versions of Go, run `./script/run_with_go_ver` in the Makefile to force the use of the Go version defined in .go_version for all targets, shell invocations, and subprocesses. This ensures also ensures we can build on machines that do not have Go installed already.
`make`
None.
> Makefile: always use .go_version

- beater/api/mux.go
- beater/api/mux_config_agent_test.go
- beater/api/mux_intake_backend_test.go
- beater/api/mux_intake_rum_test.go
- beater/api/mux_root_test.go
- beater/api/mux_sourcemap_handler_test.go
- beater/api/mux_test.go
- beater/api/root/handler.go
- beater/api/root/handler_test.go
- beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
- beater/beater_test.go
- beater/beatertest/monitoring.go
- beater/http.go
- beater/middleware/monitoring_middleware_test.go
- beater/server.go
- beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
- beater/tracing.go
- publish/pub.go
We have been using the libbeat version in the root handler,
which may not be the same as the apm-server version since
we maintain our own version now. This PR injects the apm-server
version into the root handler so it can be returned.
In the publisher code, we had hard-coded the major version
number. Less problematic, but I have changed this to parse the
full version to extract the major version number.
In the Elasticsearch client we still use the libbeat version for
determining the major version number. I think this is OK because
we should never have different *major* version of libbeat in
APM Server, for the time being at least.
Finally: instead of using the libbeat version in integration tests,
use a hard-coded version of "1.2.3" so we don't have to change
approval files each time we …
> Use the apm-server version everywhere*

- apmpackage/apm/0.1.0/_dev/docs/README.template.md
- apmpackage/apm/0.1.0/agent/input/template.yml.hbs
- apmpackage/apm/0.1.0/docs/README.md
- apmpackage/apm/0.1.0/manifest.yml
- changelogs/head.asciidoc
Add config options to `apmpackage` for currently supported config options on ESS. This only adds options that make sense to support when run by Elastic Agent. There is currently no out-of-the-box way to group the options, although it would be nice to introduce e.g. a `rum` and `security` section. 
@jalvz and @axw I'd appreciate feedback regarding the wording and the config options themselves. 
Currently supported in ESS, that are left out:
not supported by Agent:
* `apm-server.register.ingest.pipeline.*`
* `apm-server.rum.source_mapping.*`
* `apm-server.ilm`
* `setup.template` 
* `logging.*` (only `logging.level` is supported - per agent, not per input though)
not deemed to be necessary:
* `apm-server.agent.config.cache.expiration`
* `max_procs`
* Check out the APM-Integration-Testing and …
> [apmpackage] Add config options supported in ESS

- processor/otel/consumer_test.go
Add a unit test to show the mapping from span status codes to transaction/span outcome and transaction result.
Closes #4716
> processor/otel: add unit test for span status

- changelogs/7.11.asciidoc
- docs: add 7.11.1 release notes (#4727)
> [7.11] docs: add 7.11.1 release notes (#4727)

- beater/beater.go
- beater/telemetry.go
- beater/telemetry_test.go
- beater: separate recording static/dynamic config (#4609)
> [7.x] beater: separate recording static/dynamic config (#4609)

- beater/acker.go
- beater/beater.go
- publish/pub.go
- beater: move event ACKer from publisher to beater (#4617)
> [7.x] beater: move event ACKer from publisher to beater (#4617)

- docs/secure-communication-agents.asciidoc
> [7.9] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)

- docs/secure-communication-agents.asciidoc
> [7.8] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)

- docs/secure-communication-agents.asciidoc
> [7.x] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)

- docs/secure-communication-agents.asciidoc
> [7.11] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)

- docs/secure-communication-agents.asciidoc
> [7.10] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)

- docs/secure-communication-agents.asciidoc
> [7.7] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)

- docs/secure-communication-agents.asciidoc
> [7.6] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)

- docs/secure-communication-agents.asciidoc
> [7.4] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)

- docs/secure-communication-agents.asciidoc
> [7.3] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)

- docs/secure-communication-agents.asciidoc
> [7.2] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)

- docs/secure-communication-agents.asciidoc
> [7.5] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)

- beater/beater.go
- beater/beater_test.go
- beater: stop relying on onboarding in tests (#4622)
> [7.x] beater: stop relying on onboarding in tests (#4622)

- docs/secure-communication-agents.asciidoc
Readds the .NET `ServerUrl` link that was removed in https://github.com/elastic/apm-server/pull/4746. Backport to `7.2`.
> docs: readds .NET link

- docs/secure-communication-agents.asciidoc
> [7.x] docs: readds .NET link (#4764)

- docs/secure-communication-agents.asciidoc
> [7.11] docs: readds .NET link (#4764)

- docs/secure-communication-agents.asciidoc
> [7.10] docs: readds .NET link (#4764)

- docs/secure-communication-agents.asciidoc
> [7.2] docs: readds .NET link (#4764)

- NOTICE.txt
- go.mod
- go.sum
- update elasticsearch client versions (#4293)
> [7.x] update elasticsearch client versions (#4293)

- x-pack/apm-server/sampling/config.go
- x-pack/apm-server/sampling/processor.go
- x-pack/apm-server/sampling/processor_test.go
- sampling: fix TestStorageGC (#4656)
> [7.x] sampling: fix TestStorageGC (#4656)

- model/metricset.go
- model/metricset_test.go
- systemtest/aggregation_test.go
- systemtest/approvals/TestTransactionAggregation.approved.json
- systemtest/approvals/TestTransactionAggregationShutdown.approved.json
- systemtest/estest/search.go
- Add a _doc_count field for single-histogram metricsets (#4647)
> [7.x] Add a _doc_count field for single-histogram metricsets (#4647)

- Makefile
- beater/config/config_test.go
- beater/http.go
- publish/pub_test.go
- script/autopep8_all.sh
- script/check_goimports.sh
- script/generate_notice.py
- script/goimports.sh
- systemtest/apikeycmd_test.go
- x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
- Makefile: add check-fmt target (#4654)
> [7.x] Makefile: add check-fmt target (#4654)

- beater/acker.go
- beater/beater.go
- beater/beater_test.go
- beater/server_test.go
- systemtest/approvals/TestDataStreamsEnabled/true.approved.json
- systemtest/elasticsearch.go
- beater: add support for config reloading (#4623)
> [7.x] beater: add support for config reloading (#4623)

- beater/beater.go
- beater/config/integration.go
- beater/config/integration_test.go
- beater/server_test.go
- beater: ensure Fleet config contains 'apm-server' (#4684)
> [7.x] beater: ensure Fleet config contains 'apm-server' (#4684)

- apmpackage/apm/0.1.0/data_stream/app_metrics/fields/ecs.yml
- apmpackage/apm/0.1.0/data_stream/app_metrics/fields/fields.yml
- apmpackage/apm/0.1.0/data_stream/error_logs/fields/ecs.yml
- apmpackage/apm/0.1.0/data_stream/error_logs/fields/fields.yml
- apmpackage/apm/0.1.0/data_stream/internal_metrics/fields/ecs.yml
- apmpackage/apm/0.1.0/data_stream/internal_metrics/fields/fields.yml
- apmpackage/apm/0.1.0/data_stream/profile_metrics/fields/ecs.yml
- apmpackage/apm/0.1.0/data_stream/profile_metrics/fields/fields.yml
- apmpackage/apm/0.1.0/data_stream/traces/fields/ecs.yml
- apmpackage/apm/0.1.0/data_stream/traces/fields/fields.yml
- apmpackage/cmd/gen-package/field.go
- Add missing fields properties (#4611)
> [7.x] Add missing fields properties (#4611)

- apmpackage/README.md
- script/copy_package.py
- Script to automatically copy and bump package version in the storage … (#4595)
> [7.x] Script to automatically copy and bump package version in the storage … (#4595)

- script/autopep8_all.sh
> [7.x] fix make fmt (#4659)

- x-pack/apm-server/sampling/groups.go
- x-pack/apm-server/sampling/groups_test.go
- x-pack/apm-server/sampling/processor.go
- x-pack/apm-server/sampling/processor_test.go
- sampling: match policies in the given order (#4685)
> [7.x] sampling: match policies in the given order (#4685)

- Makefile
- Makefile: always use .go_version (#4710)
> [7.x] Makefile: always use .go_version (#4710)

- .ci/scripts/docker-get-logs.sh
- Jenkinsfile
- ci: set proper parameters for the tar step (#4696)
> [7.11] ci: set proper parameters for the tar step (#4696)

- .ci/scripts/docker-get-logs.sh
- Jenkinsfile
- ci: set proper parameters for the tar step (#4696)
> [7.10] ci: set proper parameters for the tar step (#4696)

- apmpackage/apm/0.1.0/data_stream/sampled_traces/elasticsearch/ilm/default_policy.json
- apmpackage/apm/0.1.0/data_stream/sampled_traces/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/0.1.0/data_stream/sampled_traces/fields/base-fields.yml
- apmpackage/apm/0.1.0/data_stream/sampled_traces/fields/ecs.yml
- apmpackage/apm/0.1.0/data_stream/sampled_traces/fields/fields.yml
- apmpackage/apm/0.1.0/data_stream/sampled_traces/manifest.yml
- apmpackage/cmd/gen-package/genfields.go
- apmpackage/cmd/gen-package/main.go
- beater/beater.go
- beater/server.go
- systemtest/elasticsearch.go
- systemtest/estest/search.go
- systemtest/monitoring_test.go
- systemtest/sampling_test.go
- x-pack/apm-server/main.go
- x-pack/apm-server/sampling/config.go
- x-pack/apm-server/sampling/config_test.go
- x-pack/apm-server/sampling/processor.go
- x-pack/apm-server/sampling/processor_test.go
- x-pack/apm-server/sampling/pubsub/config.go
- x-pack/apm-server/sampling/pubsub/config_test.go
- x-pack/apm-server/sampling/pubsub/datastream.go
- x-pack/apm-server/sampling/pubsub/pubsub.go
- x-pack/apm-server/sampling/pubsub/pubsub_integration_test.go
- x-pack/apm-server/sampling/pubsub/pubsub_test.go
- sampling: use a data stream for sampled trace docs (#4707)
> [7.x] sampling: use a data stream for sampled trace docs (#4707)

- beater/api/mux.go
- beater/api/mux_config_agent_test.go
- beater/api/mux_intake_backend_test.go
- beater/api/mux_intake_rum_test.go
- beater/api/mux_root_test.go
- beater/api/mux_sourcemap_handler_test.go
- beater/api/mux_test.go
- beater/api/root/handler.go
- beater/api/root/handler_test.go
- beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
- beater/beater_test.go
- beater/beatertest/monitoring.go
- beater/http.go
- beater/middleware/monitoring_middleware_test.go
- beater/server.go
- beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
- beater/tracing.go
- publish/pub.go
- Use the apm-server version everywhere* (#4725)
> [7.x] Use the apm-server version everywhere* (#4725)

- beater/api/mux.go
- beater/api/mux_config_agent_test.go
- beater/api/mux_intake_backend_test.go
- beater/api/mux_intake_rum_test.go
- beater/api/mux_root_test.go
- beater/api/mux_sourcemap_handler_test.go
- beater/api/mux_test.go
- beater/api/root/handler.go
- beater/api/root/handler_test.go
- beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
- beater/beater_test.go
- beater/beatertest/monitoring.go
- beater/http.go
- beater/middleware/monitoring_middleware_test.go
- beater/server.go
- beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
- beater/tracing.go
- publish/pub.go
- Use the apm-server version everywhere* (#4725)
> [7.12] Use the apm-server version everywhere* (#4725)

- apmpackage/apm/0.1.0/data_stream/sampled_traces/elasticsearch/ilm/default_policy.json
- apmpackage/apm/0.1.0/data_stream/sampled_traces/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/0.1.0/data_stream/sampled_traces/fields/base-fields.yml
- apmpackage/apm/0.1.0/data_stream/sampled_traces/fields/ecs.yml
- apmpackage/apm/0.1.0/data_stream/sampled_traces/fields/fields.yml
- apmpackage/apm/0.1.0/data_stream/sampled_traces/manifest.yml
- apmpackage/cmd/gen-package/genfields.go
- apmpackage/cmd/gen-package/main.go
- beater/beater.go
- beater/server.go
- systemtest/elasticsearch.go
- systemtest/estest/search.go
- systemtest/monitoring_test.go
- systemtest/sampling_test.go
- x-pack/apm-server/main.go
- x-pack/apm-server/sampling/config.go
- x-pack/apm-server/sampling/config_test.go
- x-pack/apm-server/sampling/processor.go
- x-pack/apm-server/sampling/processor_test.go
- x-pack/apm-server/sampling/pubsub/config.go
- x-pack/apm-server/sampling/pubsub/config_test.go
- x-pack/apm-server/sampling/pubsub/datastream.go
- x-pack/apm-server/sampling/pubsub/pubsub.go
- x-pack/apm-server/sampling/pubsub/pubsub_integration_test.go
- x-pack/apm-server/sampling/pubsub/pubsub_test.go
- sampling: use a data stream for sampled trace docs (#4707)
> [7.12] sampling: use a data stream for sampled trace docs (#4707)

- beater/beater.go
- beater/config/config_test.go
- beater/config/sampling.go
- beater/config/sampling_test.go
- x-pack/apm-server/sampling/config.go
- x-pack/apm-server/sampling/config_test.go
- x-pack/apm-server/sampling/processor_test.go
- sampling: require a default policy (#4729)
> [7.x] sampling: require a default policy (#4729)

- beater/beater.go
- beater/config/config_test.go
- beater/config/sampling.go
- beater/config/sampling_test.go
- x-pack/apm-server/sampling/config.go
- x-pack/apm-server/sampling/config_test.go
- x-pack/apm-server/sampling/processor_test.go
- sampling: require a default policy (#4729)
> [7.12] sampling: require a default policy (#4729)

- apmpackage/apm/0.1.0/data_stream/app_metrics/manifest.yml
- apmpackage/apm/0.1.0/data_stream/error_logs/manifest.yml
- apmpackage/apm/0.1.0/data_stream/internal_metrics/manifest.yml
- apmpackage/apm/0.1.0/data_stream/profile_metrics/manifest.yml
- apmpackage/apm/0.1.0/data_stream/traces/manifest.yml
- Add dataset_is_prefix field to manifest files (#4653)
> [7.x] Add dataset_is_prefix field to manifest files (#4653)

- apmpackage/apm/0.1.0/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/0.1.0/data_stream/app_metrics/manifest.yml
- model/metricset.go
- model/metricset_test.go
- processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationMinimalService.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json
- Rename dataset to avoid ambiguous index pattern generation (#4669)
> [7.12] Rename dataset to avoid ambiguous index pattern generation (#4669)

- apmpackage/apm/0.1.0/_dev/docs/README.template.md
- apmpackage/apm/0.1.0/docs/README.md
- beater/api/config/agent/handler_test.go
- beater/api/mux.go
- beater/beater.go
- beater/config/config.go
- beater/config/integration.go
- beater/config/rum.go
- beater/config/rum_test.go
- beater/jaeger/server.go
- beater/server.go
- cmd/apikey.go
- go.sum
- kibana/connecting_client.go
- kibana/connecting_client_test.go
- Wire kibana config from fleet (#4670)
> [7.12] Wire kibana config from fleet (#4670)

- apmpackage/apm/0.1.0/_dev/docs/README.template.md
- apmpackage/apm/0.1.0/docs/README.md
- beater/api/config/agent/handler_test.go
- beater/api/mux.go
- beater/beater.go
- beater/config/config.go
- beater/config/integration.go
- beater/config/rum.go
- beater/config/rum_test.go
- beater/jaeger/server.go
- beater/server.go
- cmd/apikey.go
- go.sum
- kibana/connecting_client.go
- kibana/connecting_client_test.go
- Wire kibana config from fleet (#4670)
> [7.x] Wire kibana config from fleet (#4670)

- apmpackage/apm/0.1.0/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/0.1.0/data_stream/app_metrics/manifest.yml
- model/metricset.go
- model/metricset_test.go
- processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationMinimalService.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json
- Rename dataset to avoid ambiguous index pattern generation (#4669)
> [7.x] Rename dataset to avoid ambiguous index pattern generation (#4669)

- apmpackage/apm/0.1.0/data_stream/app_metrics/manifest.yml
- apmpackage/apm/0.1.0/data_stream/error_logs/manifest.yml
- apmpackage/apm/0.1.0/data_stream/internal_metrics/manifest.yml
- apmpackage/apm/0.1.0/data_stream/profile_metrics/manifest.yml
- apmpackage/apm/0.1.0/data_stream/traces/manifest.yml
- Add dataset_is_prefix field to manifest files (#4653)
> [7.12] Add dataset_is_prefix field to manifest files (#4653)

- beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/DataStreams.approved.json
- beater/api/mux.go
- beater/api/mux_sourcemap_handler_test.go
- Disable sourcemap upload endpoint when data streams enabled (#4735)
> [7.12] Disable sourcemap upload endpoint when data streams enabled (#4735)

- beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/DataStreams.approved.json
- beater/api/mux.go
- beater/api/mux_sourcemap_handler_test.go
- Disable sourcemap upload endpoint when data streams enabled (#4735)
> [7.x] Disable sourcemap upload endpoint when data streams enabled (#4735)

- apmpackage/apm/0.1.0/manifest.yml
- systemtest/fleet_test.go
- systemtest/fleettest/client.go
- systemtest/fleettest/helpers.go
- systemtest/fleettest/types.go
- apmpackage: disallow multiple "apm" integrations (#4694)
> [7.12] apmpackage: disallow multiple "apm" integrations (#4694)

- apmpackage/apm/0.1.0/manifest.yml
- systemtest/fleet_test.go
- systemtest/fleettest/client.go
- systemtest/fleettest/helpers.go
- systemtest/fleettest/types.go
- apmpackage: disallow multiple "apm" integrations (#4694)
> [7.x] apmpackage: disallow multiple "apm" integrations (#4694)

- docs/tab-widgets/distributed-trace-receive.asciidoc
- docs/tab-widgets/distributed-trace-send.asciidoc
This PR updates PHP agent section of [Manual distributed tracing docs](https://www.elastic.co/guide/en/apm/get-started/master/distributed-tracing.html#_manual_distributed_tracing) to sync up with changes introduced in [elastic/apm-agent-php PR #357 - Simplify API for manual passing of distributed tracing data](https://github.com/elastic/apm-agent-php/pull/357).
> Update PHP agent section of Manual distributed tracing docs

- docs/guide/apm-release-notes.asciidoc
- docs/secure-communication-agents.asciidoc
- docs/version.asciidoc
For https://github.com/elastic/docs/pull/2072.
> [7.3] Update documentation links to .NET agent

- docs/tab-widgets/distributed-trace-receive.asciidoc
- docs/tab-widgets/distributed-trace-send.asciidoc
- docs: Update PHP agent manual distributed tracing docs (#4862)
> [7.x] docs: Update PHP agent manual distributed tracing docs (#4862)

- docs/tab-widgets/distributed-trace-receive.asciidoc
- docs/tab-widgets/distributed-trace-send.asciidoc
- docs: Update PHP agent manual distributed tracing docs (#4862)
> [7.12] docs: Update PHP agent manual distributed tracing docs (#4862)

- Jenkinsfile
Use an ARM worker in the CI to validate the build and UTs.
By default it runs only when merge to master.
It can be triggered on a PR basis:
* with the GitHub comment `/arm` or `jenkins run the arm tests`
* with the UI if enabling the `arm_ci` parameter.
- ~~[ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~~
- ~~[ ] Documentation has been updated~~
- ~~Is it observable through the addition of either **logging** or **metrics**?~~
- ~~Is its use being published in **telemetry** to enable product improvement?~~
- ~~Have system tests been added to avoid regression?~~
Within the CI
> [CI][arm] build and unit tests

- script/copy_package.py
- Exclude png files from find command (#4896)
> [7.12] Exclude png files from find command (#4896)

- systemtest/fleet_test.go
- do not swallow error (#4867)
> [7.x] do not swallow error (#4867)

- script/copy_package.py
- Exclude png files from find command (#4896)
> [7.x] Exclude png files from find command (#4896)

- systemtest/fleet_test.go
- do not swallow error (#4867)
> [7.12] do not swallow error (#4867)

- beater/otlp/grpc.go
When running beater in parallel tests (TestPublishIntegration), beater/otlp code was sometimes panicking due to a race to register metrics in the global monitoring registry.
`cd beater && go test -failfast -count=100 -run Integration`
Fixes https://github.com/elastic/apm-server/issues/4889
> beater/otlp: fix panic in parallel tests

- beater/otlp/grpc.go
- beater/otlp: fix panic in parallel tests (#4911)
> [7.x] beater/otlp: fix panic in parallel tests (#4911)

- beater/otlp/grpc.go
- beater/otlp: fix panic in parallel tests (#4911)
> [7.12] beater/otlp: fix panic in parallel tests (#4911)

- apmpackage/apm/0.1.0/manifest.yml
https://github.com/elastic/kibana/pull/93585
Yaml parser gets confused when default value of package metadata starts with `*` without being put in quotes. The fix is to put all default values starting with an asterisk as `'"*"'`. 
Note: I wasn't able to manually test as the elastic agent image is currently broken. It is a minor change though, so I suggest we move forward with this and test once the elastic agent is fixed. 
Start Elastic Agent and Fleet, and 
* install APM integration to an agent policy.
* edit policy and try to enter a string starting with `*` without quotes -> should lead to error
* edit policy and try to enter a string starting with `*` in  quotes -> should work
related to #https://github.com/elastic/kibana/pull/93585
> [fleet] add quotes to special char default value

- apmpackage/apm/0.1.0/manifest.yml
backports #4917 
--- 
[fleet] add quotes to special char default value (#4917)
related to #https://github.com/elastic/kibana/pull/93585
> [7.x][fleet] add quotes to special char default value (#4917)

- apmpackage/apm/0.1.0/manifest.yml
backports #4917 
---
[fleet] add quotes to special char default value (#4917)
related to #https://github.com/elastic/kibana/pull/93585
> [7.12] [fleet] add quotes to special char default value (#4917)

- Jenkinsfile
Filter on x86 arch
ARM64 arch will be enabled sooner than later so let's prepare the CI pipelines for that
> [CI] Use MacOS for x86_64

- model/context.go
- model/modeldecoder/rumv3/decoder.go
- model/modeldecoder/rumv3/error_test.go
- model/modeldecoder/rumv3/transaction_test.go
- model/modeldecoder/v2/decoder.go
- model/modeldecoder/v2/error_test.go
- model/modeldecoder/v2/transaction_test.go
- model/span.go
- model/span_test.go
- processor/otel/builder.go
- processor/otel/consumer.go
- processor/otel/consumer_test.go
Ports and HTTP status codes should always be
positive, so use zero as a sentinel value to
indicate omission in order to remove a pointer.
Non-functional change, run the tests.
None.
> model: de-pointer several integer fields

- model/batch.go
- model/error.go
- model/error_test.go
- model/metricset.go
- model/metricset_test.go
- model/profile.go
- model/profile_test.go
- model/span.go
- model/span_test.go
- model/transaction.go
- model/transaction_test.go
Rather than having each model type create a slice only to append it to another slice, append to that slice directly. Cuts out some unnecessary allocations.
Also, I have renamed and unexported the `Transform` methods on the event types to clarify that they are no longer transformed directly, but only ever through a `model.Batch`.
None.
> model: append events on transformation

- beater/beater.go
- model/modelprocessor/chained.go
Move the chained model.BatchProcessor out to model/modelprocessor, to make it reusable.
None.
> Move chained processor to model/modelprocessor

- apmpackage/apm/0.1.0/manifest.yml
Update apm package to use types supported by the [package-spec](https://github.com/elastic/package-spec/blob/master/versions/1/data_stream/manifest.spec.yml#L50-L55)
* `text` over `string` 
* `integer` over `int` 
fixes #https://github.com/elastic/package-storage/issues/1011
> [fleet] Fix apm package types

- changelogs/7.11.asciidoc
Adds `7.11.2` release notes. I don't see anything in the [commit history](https://github.com/elastic/apm-server/commits/7.11) that warrants a note.
> docs: add 7.11.2 release notes

- changelogs/7.11.asciidoc
- docs: add 7.11.2 release notes (#4936)
> [7.11] docs: add 7.11.2 release notes (#4936)

- changelogs/7.11.asciidoc
- docs: add 7.11.2 release notes (#4936)
> [7.12] docs: add 7.11.2 release notes (#4936)

- systemtest/fleettest/client.go
Fleet has apparently changed how enrollment API Keys should be queried, I suppose because of the move to store them in dedicated indices for Fleet Server. Update system tests to match.
cd systemtest && go test -v -run FleetIntegration
> systemtest: fix query for enrollment API Keys

- beater/api/mux.go
- beater/beater.go
- beater/config/config.go
- beater/config/config_test.go
Introduce hidden config for development and performance analysis:
- apm-server.pprof.enabled (default: false)
Adds the "/debug/pprof" endpoint to the server's
main HTTP server. This can be used instead of the
"--httpprof" flag, to enable working with a single
port.
- apm-server.pprof.block_profile_rate (default: 0)
If >0, sets the block profile rate. See
https://golang.org/pkg/runtime/#SetBlockProfileRate
- apm-server.pprof.mem_profile_rate (default: 0)
If >0, sets the memory allocation profile rate. See
`MemProfileRate` at https://golang.org/pkg/runtime/#pkg-variables
- apm-server.pprof.mutex_profile_rate (default: 0)
If >0, sets the mutex profile rate. See
https://golang.org/pkg/runtime/#SetMutexProfileFraction
These config do not support hot-reloading, and will only work when passed in …
> beater: add pprof-related config

- changelogs/7.12.asciidoc
- docs/breaking-changes.asciidoc
- docs/guide/apm-breaking-changes.asciidoc
- docs/release-notes.asciidoc
Inits 7.12 breaking changes plus a few small fixes for release notes.
Backport with https://github.com/elastic/apm-server/pull/4858/.
> docs: init 7.12 bcs and rns

- CHANGELOG.asciidoc
- changelogs/7.12.asciidoc
- docs/breaking-changes.asciidoc
- docs/guide/apm-breaking-changes.asciidoc
- docs/release-notes.asciidoc
This PR backports https://github.com/elastic/apm-server/pull/4858 and https://github.com/elastic/apm-server/pull/4959.
> [7.x] docs: 7.12 release notes

- docs/apm-package/apm-integration.asciidoc
- docs/apm-package/configure.asciidoc
- docs/apm-package/data-streams.asciidoc
- docs/apm-package/input-apm.asciidoc
- docs/copied-from-beats/docs/howto/load-index-templates.asciidoc
- docs/copied-from-beats/docs/template-config.asciidoc
- docs/getting-started-apm-server.asciidoc
Addresses most of the to-dos in the APM integration docs for `7.12`. For now, this information is **very** basic.
For https://github.com/elastic/apm-server/issues/4494.
> docs: Add additional APM integration information

- docs/apm-package/apm-integration.asciidoc
- docs/apm-package/configure.asciidoc
- docs/apm-package/data-streams.asciidoc
- docs/apm-package/input-apm.asciidoc
- docs/copied-from-beats/docs/howto/load-index-templates.asciidoc
- docs/copied-from-beats/docs/template-config.asciidoc
- docs/getting-started-apm-server.asciidoc
- docs: Add additional APM integration information (#4969)
> [7.12] docs: Add additional APM integration information (#4969)

- docs/apm-package/apm-integration.asciidoc
- docs/apm-package/configure.asciidoc
- docs/apm-package/data-streams.asciidoc
- docs/apm-package/input-apm.asciidoc
- docs/copied-from-beats/docs/howto/load-index-templates.asciidoc
- docs/copied-from-beats/docs/template-config.asciidoc
- docs/getting-started-apm-server.asciidoc
- docs: Add additional APM integration information (#4969)
> [7.x] docs: Add additional APM integration information (#4969)

- changelogs/6.8.asciidoc
- docs: add 6.8.15 release notes (#4974)
> docs: add 6.8.15 release notes (#4974)

- changelogs/6.8.asciidoc
- docs: add 6.8.15 release notes (#4974) (#4978)
> [7.12] docs: add 6.8.15 release notes (#4974) (#4978)

- changelogs/6.8.asciidoc
- docs: add 6.8.15 release notes (#4974) (#4978)
> [7.x] docs: add 6.8.15 release notes (#4974) (#4978)

- .mergify.yml
Enable [backports](https://docs.mergify.io/actions/backport.html) with [mergify](https://docs.mergify.io/index.html) for:
- 7.x branch with the label `v7.13.0`
- 7.12 branch with the label `v7.12.0`
If any conflicts the PRs are created with the label `conflict` in addition a comment will be added with the actions to be done in order to fix the conflicts locally and push to the branch.
`Mergify` provides different mechanism to interact with PRs and automate certain process.
Backports to 7.x -> https://github.com/elastic/apm-pipeline-library/pull/995
Merges to master -> https://github.com/elastic/apm-pipeline-library/pull/994
* There is an initiative to automate the GitHub labels creation in each obs11 repo -> https://github.com/elastic/apm-pipeline-library/pull/886
* Closes …
> feat: add support for auto-backports

- _meta/beat.yml
- apm-server.docker.yml
- apm-server.yml
- apmpackage/apm/0.1.0/agent/input/template.yml.hbs
- apmpackage/apm/0.1.0/manifest.yml
- beater/api/config/agent/handler.go
- beater/api/config/agent/handler_test.go
- beater/api/mux.go
- beater/beater.go
- beater/config/config.go
- beater/config/config_test.go
- docs/configuration-process.asciidoc
- model/modelprocessor/environment.go
- model/modelprocessor/environment_test.go
- systemtest/apmservertest/config.go
- systemtest/environment_test.go
- transform/transform.go
- x-pack/apm-server/main.go
- Introduce a configurable default service environment (#4861)
> [7.x] Introduce a configurable default service environment (#4861)

- systemtest/apmservertest/config.go
- systemtest/apmservertest/server_test.go
- systemtest/elasticsearch.go
- systemtest/monitoring_test.go
- systemtest/apmservertest: console output in tests (#4897)
> [7.x] systemtest/apmservertest: console output in tests (#4897)

- Jenkinsfile
- [CI] Use MacOS for x86_64 (#4923)
> [7.x] [CI] Use MacOS for x86_64 (#4923)

- beater/config/aggregation.go
- beater/config/config_test.go
- systemtest/sampling_test.go
- Enable transaction aggregation by default (#4882)
> [7.x] Enable transaction aggregation by default (#4882)

- processor/otel/consumer.go
- processor/otel/consumer_test.go
- processor/otel/exceptions.go
- processor/otel/exceptions_test.go
- processor/otel/test_approved/span_jaeger_http.approved.json
- processor/otel: translate OpenTelemetry exceptions (#4876)
> [7.x] processor/otel: translate OpenTelemetry exceptions (#4876)

- beater/beater.go
- model/modelprocessor/chained.go
- Move chained processor to model/modelprocessor (#4925)
> [7.x] Move chained processor to model/modelprocessor (#4925)

- beater/api/mux.go
- beater/middleware/timeout_middleware.go
- beater/middleware/timeout_middleware_test.go
- beater/request/result.go
- beater/request/result_test.go
- Merge pull request #4918 from stuartnelson3/translate-context-canceled-timeouts (#4918)
> [7.x] Merge pull request #4918 from stuartnelson3/translate-context-canceled-timeouts (#4918)

- apmpackage/apm/0.1.0/docs/README.md
- beater/beater.go
- beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
- docs/data/elasticsearch/generated/metricsets.json
- model/modelprocessor/metricsetname.go
- model/modelprocessor/metricsetname_test.go
- systemtest/approvals/TestApprovedMetrics.approved.json
- systemtest/approvals/TestOTLPGRPCMetrics.approved.json
- systemtest/metrics_test.go
- tests/system/metricset.approved.json
- tests/system/test_integration.py
- Set metricset.name for breakdown metrics (#4910)
> [7.x] Set metricset.name for breakdown metrics (#4910)

- docs/common-problems.asciidoc
This PR adds information on the PHP agent's internal queue–or lack thereof. Did a quick once-over on the rest of the content while I was here.
Closes https://github.com/elastic/apm-server/issues/5003.
> docs: add php agent queue info

- docs/common-problems.asciidoc
- docs: add php agent queue info (#5007)
> [7.x] docs: add php agent queue info (#5007)

- docs/common-problems.asciidoc
- docs: add php agent queue info (#5007)
> [7.12] docs: add php agent queue info (#5007)

- beater/interceptors/logging.go
- beater/interceptors/logging_test.go
- beater/interceptors/metrics.go
- beater/interceptors/metrics_test.go
- beater/jaeger/common.go
- beater/jaeger/grpc.go
- beater/jaeger/grpc_test.go
- beater/jaeger/http.go
- beater/jaeger/http_test.go
- beater/jaeger/server.go
- beater/otlp/grpc.go
- beater/otlp/grpc_test.go
- beater/request/result.go
- beater/server.go
- systemtest/logging_test.go
- utility/ip_test.go
- utility/remoteaddr.go
- add logging to jaeger and otlp gRPC calls (#4934)
> [7.x] add logging to jaeger and otlp gRPC calls (#4934)

- beater/api/mux.go
- beater/beater.go
- beater/config/config.go
- beater/config/config_test.go
- beater: add pprof-related config (#4954)
> [7.x] beater: add pprof-related config (#4954)

- processor/otel/consumer.go
- processor/otel/consumer_test.go
- processor/otel: set default RepresentativeCount (#4976)
> [7.x] processor/otel: set default RepresentativeCount (#4976)

- beater/interceptors/logging.go
- beater/interceptors/logging_test.go
- beater/interceptors/metadata.go
- beater/interceptors/metadata_test.go
- beater/otlp/clientmetadata.go
- beater/otlp/clientmetadata_test.go
- beater/server.go
- model/modelprocessor/hostname.go
- model/modelprocessor/metadata.go
- model/modelprocessor/nodename.go
- systemtest/logging_test.go
- systemtest/otlp_test.go
- Set client.ip for iOS agent (#4975)
> [7.x] Set client.ip for iOS agent (#4975)

- Makefile
- ingest/pipeline/definition.json
- ingest/pipeline/definition.yml
- ingest/pipeline/generate.go
- ingest/pipeline/register.go
- ingest/pipeline: convert ingest pipeline to YAML (#4977)
> [7.x] ingest/pipeline: convert ingest pipeline to YAML (#4977)

- docs/data/elasticsearch/generated/errors.json
- docs/data/elasticsearch/generated/transactions.json
- systemtest/approvals/TestRUMErrorSourcemapping.approved.json
- systemtest/approvals/TestRUMXForwardedFor.approved.json
- tests/system/error.approved.json
- tests/system/kibana.py
- tests/system/transaction.approved.json
Fix Python-based system tests due to several recent changes:
- Kibana now has a different response structure for listing agent config (API only used in system tests, no backwards compatibility issue for APM Server)
- Add `user_agent.device.type` to approvals, which is now added by the `user_agent` ingest processor
`make system-tests`
None.
> tests/system: fix system tests

- beater/interceptors/logging.go
Make sure we create a new shadowed "logger" variable,
rather than reassigning to the "logger" param passed
into the interceptor. Otherwise, each request will add
duplicate fields to an ever-growing list of fields.
Send multiple gRPC requests to APM Server, with logging enabled. Make sure there are no duplicate fields in any request's log entry. (If you run a load generator, it'll become apparent pretty quickly as the terminal fills up with logs!)
None.
> beater/interceptors: don't reassign shared logger

- docs/guide/agent-server-compatibility.asciidoc
- docs: update agent/server compat for ruby (#5036)
> [7.12] docs: update agent/server compat for ruby (#5036)

- docs/guide/agent-server-compatibility.asciidoc
- docs: update agent/server compat for ruby (#5036)
> [7.x] docs: update agent/server compat for ruby (#5036)

- .mergify.yml
The Mergify check on PRs never goes green in the GitHub UI, which makes it difficult to tell whether a PR is ready to merge.
Add the `merged` attribute -> https://docs.mergify.io/conditions/#attributes
> [mergify] run the check after the PR gets merged

- docker-compose.yml
- systemtest/elasticsearch.go
Set `action.destructive_requires_name=false` in docker-compose.yml for Elastisearch, to allow wildcard deletions.
Non-functional change, check that system tests pass.
https://github.com/elastic/elasticsearch/issues/61074
> docker-compose.yml: allow wildard deletes

- apmpackage/apm/0.2.0/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/0.2.0/data_stream/error_logs/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/0.2.0/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/0.2.0/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/0.2.0/data_stream/traces/elasticsearch/ingest_pipeline/default.json
- changelogs/head.asciidoc
- ingest/pipeline/definition.json
- ingest/pipeline/definition.yml
`apm_ingest_timestamp` should always come first, ensuring
`event.ingested` is set as early as possible in the ingest
pipeline. This is in line with beats modules, and the ECS
definition of `event.ingested`.
1. Run APM Server with a clean Elasticsearch
2. Check that the "apm" pipeline installed by APM Server calls "apm_ingest_timestamp" first
None.
> ingest: make apm_ingest_timestamp first pipeline

- .ci/update-json-schema.groovy
Folder to filter was not pointing to the right location. Therefore the automation to create PRs was not linking the original commit.
For instance:
```
git  --no-pager log --pretty=format:'* https://github.com/elastic/apm-server/commit/%h %s' \
5c2e4cb387e14b8a4707c8f2a349f0452fae72c5...HEAD \
--follow -- spec
```
produces nothing, while the new change produces:
```
git  --no-pager log --pretty=format:'* https://github.com/elastic/apm-server/commit/%h %s' \      
5c2e4cb387e14b8a4707c8f2a349f0452fae72c5...HEAD \
--follow -- docs/spec
* https://github.com/elastic/apm-server/commit/f787691a Support for ingesting user.domain (#5067)% 
```
> ci: use the specs relative location

- docs/secure-communication-agents.asciidoc
- docs/ssl-input.asciidoc
`v1.9.0` introduces the `ServerCert` config option in the .NET agent. This PR links to these new docs.
Closes https://github.com/elastic/apm-agent-dotnet/issues/1188.
> docs: Link to .NET `ServerCert` docs

- docs/secure-communication-agents.asciidoc
- docs/ssl-input.asciidoc
- docs: Link to .NET ServerCert docs (#5078)
> [7.12] docs: Link to .NET ServerCert docs (#5078)

- docs/secure-communication-agents.asciidoc
- docs/ssl-input.asciidoc
- docs: Link to .NET ServerCert docs (#5078)
> [7.x] docs: Link to .NET ServerCert docs (#5078)

- changelogs/head.asciidoc
- cmd/apikey.go
- elasticsearch/security_api.go
- systemtest/apikeycmd_test.go
Add `application: "apm"` in the metadata of API Keys created by APM Server, so they can later be identified as having been created by/for APM. The metadata must not be used for auth; it is purely for informational purposes.
Metadata will be shown when running `apm-server apikey info` with the `--json` flag, but not in the default text format.
1. Create an API Key with `apm-server apikey create`
2. Run `apm-server apikey info --json --id <id-from-step-1>`, check the metadata shows `{"application": "apm"}`
https://github.com/elastic/apm-server/issues/3461
https://github.com/elastic/kibana/issues/77966
> Add metadata to API Keys created by server

- idxmgmt/ilm/config.go
- idxmgmt/ilm/config_test.go
ES index names need to be lowercased, but the lowercasing happens too early at the moment. This PR moves it until after variable parts have been resolved. This is especially important when users want to configure dates and times in their index names. 
Configure a `apm-server.ilm.setup.mapping` section that contains a `index_suffix` with a variable part and some uppercase string, and ensure that the lowercasing happens after the variable has been resolved, for example:
```
apm-server.ilm.setup.mapping:
- event_type: "error"
policy_name: "apm-error"
index_suffix: "MyTest-%{+yyyy.MM.dd}"
```
should result in an index called `apm-8.0.0-error-mytest-2021.04.14-000001` in ES.
> [ilm] Apply lowercasing after resolving variables

- _meta/beat.yml
- apm-server.docker.yml
- apm-server.yml
- changelogs/head.asciidoc
- docs/secure-communication-agents.asciidoc
Remove the experimental label from API Key auth.
N/A
#3461
> docs: remove experimental label from API Key auth

- .mergify.yml
Now that https://github.com/Mergifyio/mergify-engine/pull/2364 has been merged (thanks @v1v!), we can set a title template for backport PRs.
When using https://github.com/sqren/backport we would get PR titles prefixed with the target branch, which we all rather liked. Let's bring that back.
> mergify: prefix PR title with target branch

- .mergify.yml
`base` is the _source_ branch, and there doesn't seem to be an attribute for the target branch. Just hardcode target branch name for now.
> mergify: hardcode target branch name

- systemtest/apmservertest/config.go
- systemtest/containers.go
- systemtest/fleet_test.go
- systemtest/fleettest/client.go
In the Fleet integration system test, bootstrap Fleet Server and then run the APM integration on a separate Elastci Agent that enrolls with the Fleet Server.
Closes #5075
> systemtest: use Fleet Server

- docker-compose.yml
Remove XPACK_FLEET_AGENTS_KIBANA_HOST, now that we're using Fleet Server in system tests.
Closes #5114
> docker-compose: fix kibana config

- systemtest/containers.go
- systemtest/fleet_test.go
- systemtest/go.mod
Fix the recording of mapped ports for Elastic Agent containers. Instead of iterating the mapped ports, which may have multiple addresses (IPv4, IPv6), record a map of exposed to mapped ports using the host IP.
N/A
> systemtest: fix exposed port mapping

- changelogs/7.12.asciidoc
- docs: add 7.12.1 release notes (#5124)
> [7.12] docs: add 7.12.1 release notes (#5124)

- changelogs/7.12.asciidoc
- docs: add 7.12.1 release notes (#5124)
> [7.x] docs: add 7.12.1 release notes (#5124)

- docker-compose.yml
- systemtest/containers.go
- systemtest/fleet_test.go
Define a fleet-server service in docker-compose.yml which can be reused across tests, and avoiding the need to run (more) ephemeral fleet-server containers per test. This minimises the pollution of the Fleet Agents list, and simplifies systemtest code.
I've also removed the special 404 status code handling in unenrolling agents, which has been fixed upstream.
https://github.com/elastic/kibana/issues/90544
> systemtest: add fleet-server to docker-compose.yml

- CHANGELOG.asciidoc
- changelogs/7.13.asciidoc
- docs/release-notes.asciidoc
- create 7.13 changelog (3ec1c48b)
> [7.13] create 7.13 changelog (3ec1c48b)

- CHANGELOG.asciidoc
- changelogs/7.13.asciidoc
- docs/release-notes.asciidoc
- create 7.13 changelog (3ec1c48b)
> [7.x] create 7.13 changelog (3ec1c48b)

- docs/apm-package/apm-integration.asciidoc
The `apm_user` role has been updated to include `read` and `view_index_metadata` privileges on data stream indices. This PR removes a previous limitation that stated incompatibility between the `apm_user` role and data streams.
Additional changes have been opened to explain the deprecation of `apm_user` and workarounds for APM users. See https://github.com/elastic/observability-docs/issues/516 for more information.
> docs: remove apm_user limitation

- docs/apm-package/apm-integration.asciidoc
- docs: remove apm_user limitation (#5172)
> [7.x] docs: remove apm_user limitation (#5172)

- docs/apm-package/apm-integration.asciidoc
- docs: remove apm_user limitation (#5172)
> [7.13] docs: remove apm_user limitation (#5172)

- docker-compose.yml
[start_time:Wed, 28 Apr 2021 12:19:28 GMT, release_branch:master, prefix:, end_time:Wed, 28 Apr 2021 17:10:30 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-4fa04b7f, build_duration_seconds:17462]
> [automation] update elastic stack version for testing 8.0.0-4fa04b7f

- Makefile
Update BEATS_VERSION. Having it set to 7.x means the `check-docker-compose` target fails.
> Makefile: fix beats branch for 7.13

- docker-compose.yml
[start_time:Thu, 29 Apr 2021 12:13:38 GMT, release_branch:master, prefix:, end_time:Thu, 29 Apr 2021 17:05:35 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-dec8157c, build_duration_seconds:17517]
> [automation] update elastic stack version for testing 8.0.0-dec8157c

- .mergify.yml
- [mergify] assign the original author (#5069)
> [7.13] [mergify] assign the original author (#5069)

- .mergify.yml
- [mergify] assign the original author (#5069)
> [7.x] [mergify] assign the original author (#5069)

- .mergify.yml
- mergify: prefix PR title with target branch (#5103)
> [7.x] mergify: prefix PR title with target branch (#5103)

- .mergify.yml
- mergify: prefix PR title with target branch (#5103)
> [7.13] mergify: prefix PR title with target branch (#5103)

- .mergify.yml
- mergify: hardcode target branch name (#5106)
> [7.x] mergify: hardcode target branch name (#5106)

- .mergify.yml
- mergify: hardcode target branch name (#5106)
> [7.13] mergify: hardcode target branch name (#5106)

- .mergify.yml
Backport the mergify changes in https://github.com/elastic/apm-server/commit/0d0885df08d45c51b3a496e4ec5c6e0d4cd60b53#diff-6a30e47dd51449847422017b16878889b848f6602ac56d5a2e67ce8a19afade2
> [7.x] mergify: add backports for 7.13/7.14

- .mergify.yml
- [7.x] mergify: add backports for 7.13/7.14 (#5201)
> [7.13] [7.x] mergify: add backports for 7.13/7.14 (#5201)

- docker-compose.yml
[start_time:Sun, 2 May 2021 12:15:28 GMT, release_branch:master, prefix:, end_time:Sun, 2 May 2021 16:46:39 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-6babd951, build_duration_seconds:16271]
> [automation] update elastic stack version for testing 8.0.0-6babd951

- docker-compose.yml
[start_time:Mon, 3 May 2021 00:16:04 GMT, release_branch:7.13, prefix:, end_time:Mon, 3 May 2021 04:48:55 GMT, manifest_version:2.0.0, version:7.13.0-SNAPSHOT, branch:7.13, build_id:7.13.0-b1b3acd6, build_duration_seconds:16371]
> [automation] update elastic stack version for testing 7.13.0-b1b3acd6

- docker-compose.yml
[start_time:Mon, 3 May 2021 12:14:53 GMT, release_branch:master, prefix:, end_time:Mon, 3 May 2021 17:03:28 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-def4e64e, build_duration_seconds:17315]
> [automation] update elastic stack version for testing 8.0.0-def4e64e

- docker-compose.yml
[start_time:Mon, 3 May 2021 05:11:57 GMT, release_branch:7.x, prefix:, end_time:Mon, 3 May 2021 09:46:48 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-90e98b59, build_duration_seconds:16491]
> [automation] update elastic stack version for testing 7.14.0-90e98b59

- docker-compose.yml
[start_time:Mon, 3 May 2021 12:14:48 GMT, release_branch:7.13, prefix:, end_time:Mon, 3 May 2021 17:13:18 GMT, manifest_version:2.0.0, version:7.13.0-SNAPSHOT, branch:7.13, build_id:7.13.0-809d7988, build_duration_seconds:17910]
> [automation] update elastic stack version for testing 7.13.0-809d7988

- systemtest/aggregation_test.go
- systemtest/elasticsearch.go
- systemtest/estest/client.go
- systemtest/estest/search.go
- Increase the max retries and backoff for Elasticsearch request, to gracefully handle 503 errors due to cluster and index initialisation.
- Increase the default `estest.Client` request loop timeout from 10 seconds up to 1 minute.
- Declare `estest.Client.ExpectDocs` to be a test helper to make sure it is not indicated as the culprit in a test failure.
- Use `testing.TB.Fatal` instead of `testing.TB.Error` when search requests return an error in `ExpectMinDocs, so we don't continue on in the test with empty results
Stabilising system tests.
> systemtest: increase max retries for Elasticsearch

- docker-compose.yml
[start_time:Tue, 4 May 2021 15:08:59 GMT, release_branch:7.13, prefix:, end_time:Tue, 4 May 2021 20:06:23 GMT, manifest_version:2.0.0, version:7.13.0-SNAPSHOT, branch:7.13, build_id:7.13.0-e9675cbf, build_duration_seconds:17844]
> [automation] update elastic stack version for testing 7.13.0-e9675cbf

- docker-compose.yml
[start_time:Wed, 5 May 2021 12:23:45 GMT, release_branch:master, prefix:, end_time:Wed, 5 May 2021 16:54:23 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-cbe7788c, build_duration_seconds:16238]
> [automation] update elastic stack version for testing 8.0.0-cbe7788c

- docker-compose.yml
[start_time:Wed, 5 May 2021 12:13:10 GMT, release_branch:7.13, prefix:, end_time:Wed, 5 May 2021 18:02:53 GMT, manifest_version:2.0.0, version:7.13.0-SNAPSHOT, branch:7.13, build_id:7.13.0-683cb8f3, build_duration_seconds:20983]
> [automation] update elastic stack version for testing 7.13.0-683cb8f3

- docker-compose.yml
[start_time:Wed, 5 May 2021 05:16:44 GMT, release_branch:7.x, prefix:, end_time:Wed, 5 May 2021 10:14:58 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-5b4d7537, build_duration_seconds:17894]
> [automation] update elastic stack version for testing 7.14.0-5b4d7537

- docker-compose.yml
[start_time:Thu, 6 May 2021 12:24:37 GMT, release_branch:master, prefix:, end_time:Thu, 6 May 2021 21:15:08 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-ee8c8ba6, build_duration_seconds:31831]
> [automation] update elastic stack version for testing 8.0.0-ee8c8ba6

- docker-compose.yml
[start_time:Thu, 6 May 2021 05:20:40 GMT, release_branch:7.x, prefix:, end_time:Thu, 6 May 2021 10:30:52 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-8ba10577, build_duration_seconds:18612]
> [automation] update elastic stack version for testing 7.14.0-8ba10577

- docker-compose.yml
[start_time:Thu, 6 May 2021 12:13:55 GMT, release_branch:7.13, prefix:, end_time:Thu, 6 May 2021 17:07:12 GMT, manifest_version:2.0.0, version:7.13.0-SNAPSHOT, branch:7.13, build_id:7.13.0-299fd1b5, build_duration_seconds:17597]
> [automation] update elastic stack version for testing 7.13.0-299fd1b5

- docker-compose.yml
[start_time:Fri, 7 May 2021 12:59:27 GMT, release_branch:master, prefix:, end_time:Fri, 7 May 2021 19:34:17 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-e64ed7d4, build_duration_seconds:23690]
> [automation] update elastic stack version for testing 8.0.0-e64ed7d4

- docker-compose.yml
[start_time:Sat, 8 May 2021 05:24:22 GMT, release_branch:7.x, prefix:, end_time:Sat, 8 May 2021 10:08:18 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-7d5ea6dc, build_duration_seconds:17036]
> [automation] update elastic stack version for testing 7.14.0-7d5ea6dc

- docker-compose.yml
[start_time:Mon, 10 May 2021 12:23:33 GMT, release_branch:7.13, prefix:, end_time:Mon, 10 May 2021 17:22:11 GMT, manifest_version:2.0.0, version:7.13.0-SNAPSHOT, branch:7.13, build_id:7.13.0-65952c7d, build_duration_seconds:17918]
> [automation] update elastic stack version for testing 7.13.0-65952c7d

- docker-compose.yml
[start_time:Mon, 10 May 2021 05:22:28 GMT, release_branch:7.x, prefix:, end_time:Mon, 10 May 2021 10:29:56 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-e8048b9e, build_duration_seconds:18448]
> [automation] update elastic stack version for testing 7.14.0-e8048b9e

- .ci/jobs/apm-server-check-changelogs-mbp.yml
- .ci/jobs/apm-server-mbp.yml
- .ci/jobs/update-json-schema.yml
Avoid builds for the bump automation branches since there will be PR if there are new changes.
> [jjbb] avoid building the update stack branches

- NOTICE.txt
- go.mod
- go.sum
Update beats repo to include the arm64 related packaging fix from https://github.com/elastic/beats/pull/25679
> Update to elastic/beats@7d75d02b1f0c

- docker-compose.yml
[start_time:Thu, 13 May 2021 12:14:26 GMT, release_branch:7.13, prefix:, end_time:Thu, 13 May 2021 17:03:29 GMT, manifest_version:2.0.0, version:7.13.0-SNAPSHOT, branch:7.13, build_id:7.13.0-6647b45b, build_duration_seconds:17343]
> [automation] update elastic stack version for testing 7.13.0-6647b45b

- docker-compose.yml
[start_time:Sun, 16 May 2021 05:23:36 GMT, release_branch:7.x, prefix:, end_time:Sun, 16 May 2021 10:21:12 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-c3a960d1, build_duration_seconds:17856]
> [automation] update elastic stack version for testing 7.14.0-c3a960d1

- docker-compose.yml
[start_time:Sun, 16 May 2021 12:14:04 GMT, release_branch:7.13, prefix:, end_time:Sun, 16 May 2021 17:00:16 GMT, manifest_version:2.0.0, version:7.13.0-SNAPSHOT, branch:7.13, build_id:7.13.0-4317ae2c, build_duration_seconds:17172]
> [automation] update elastic stack version for testing 7.13.0-4317ae2c

- docker-compose.yml
[start_time:Mon, 17 May 2021 12:27:09 GMT, release_branch:master, prefix:, end_time:Mon, 17 May 2021 22:10:17 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-bd957996, build_duration_seconds:34988]
> [automation] update elastic stack version for testing 8.0.0-bd957996

- docker-compose.yml
[start_time:Mon, 17 May 2021 05:23:52 GMT, release_branch:7.x, prefix:, end_time:Mon, 17 May 2021 11:43:17 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-c4ef352d, build_duration_seconds:22765]
> [automation] update elastic stack version for testing 7.14.0-c4ef352d

- docker-compose.yml
[start_time:Mon, 17 May 2021 12:15:11 GMT, release_branch:7.13, prefix:, end_time:Mon, 17 May 2021 16:53:14 GMT, manifest_version:2.0.0, version:7.13.0-SNAPSHOT, branch:7.13, build_id:7.13.0-6a007525, build_duration_seconds:16683]
> [automation] update elastic stack version for testing 7.13.0-6a007525

- changelogs/head.asciidoc
- x-pack/apm-server/aggregation/txmetrics/aggregator.go
- x-pack/apm-server/sampling/processor.go
See https://github.com/elastic/apm-server/issues/5276
1. Run apm-server on a 32-bit system with `-E http.enabled=true`
2. Ingest data
3. curl http://localhost:5066/stats
4. Make sure it doesn't panic
Closes https://github.com/elastic/apm-server/issues/5276
> aggregation/txmetrics: fix alignment for 32-bit

- changelogs/7.13.asciidoc
- docs/breaking-changes.asciidoc
- docs/guide/apm-breaking-changes.asciidoc
* Fixes typo in the ~7.10~ 7.13 release notes
* Adds code highlighting for fields
* Adds empty breaking changes section
> docs: fix release note typo; add breaking changes

- changelogs/7.13.asciidoc
- docs/breaking-changes.asciidoc
- docs/guide/apm-breaking-changes.asciidoc
- docs: fix release note typo; add breaking changes (#5281)
> [7.13] docs: fix release note typo; add breaking changes (#5281)

- changelogs/7.13.asciidoc
- docs/breaking-changes.asciidoc
- docs/guide/apm-breaking-changes.asciidoc
- docs: fix release note typo; add breaking changes (#5281)
> [7.x] docs: fix release note typo; add breaking changes (#5281)

- docker-compose.yml
[start_time:Wed, 19 May 2021 00:16:02 GMT, release_branch:master, prefix:, end_time:Wed, 19 May 2021 04:54:46 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-cd20b01b, build_duration_seconds:16724]
> [automation] update elastic stack version for testing 8.0.0-cd20b01b

- docker-compose.yml
[start_time:Tue, 18 May 2021 05:17:40 GMT, release_branch:7.x, prefix:, end_time:Tue, 18 May 2021 10:44:43 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-406b0128, build_duration_seconds:19623]
> [automation] update elastic stack version for testing 7.14.0-406b0128

- docker-compose.yml
[start_time:Tue, 18 May 2021 12:14:44 GMT, release_branch:7.13, prefix:, end_time:Tue, 18 May 2021 21:56:39 GMT, manifest_version:2.0.0, version:7.13.0-SNAPSHOT, branch:7.13, build_id:7.13.0-a26c8524, build_duration_seconds:34915]
> [automation] update elastic stack version for testing 7.13.0-a26c8524

- docker-compose.yml
[start_time:Wed, 19 May 2021 05:24:07 GMT, release_branch:7.x, prefix:, end_time:Wed, 19 May 2021 10:08:59 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-b278d172, build_duration_seconds:17092]
> [automation] update elastic stack version for testing 7.14.0-b278d172

- docker-compose.yml
[start_time:Wed, 19 May 2021 00:15:13 GMT, release_branch:7.13, prefix:, end_time:Wed, 19 May 2021 05:19:28 GMT, manifest_version:2.0.0, version:7.13.0-SNAPSHOT, branch:7.13, build_id:7.13.0-bdae1adb, build_duration_seconds:18255]
> [automation] update elastic stack version for testing 7.13.0-bdae1adb

- tests/packaging/package_test.go
The "Package" CI stage is failing because we're trying to run 32-bit code on 64-bit systems, which libbeat no longer allows. Disable package tests for everything exception amd64/x86_64. Later we can remove these tests entirely, and rely on beats-tester for smoke testing packages.
N/A
https://github.com/elastic/apm-server/issues/5274
> tests/packaging: run package tests on x86_64 only

- docker-compose.yml
[start_time:Thu, 20 May 2021 00:17:29 GMT, release_branch:master, prefix:, end_time:Thu, 20 May 2021 05:40:46 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-753d8b9f, build_duration_seconds:19397]
> [automation] update elastic stack version for testing 8.0.0-753d8b9f

- docker-compose.yml
[start_time:Fri, 21 May 2021 00:16:28 GMT, release_branch:7.13, prefix:, end_time:Fri, 21 May 2021 04:48:03 GMT, manifest_version:2.0.0, version:7.13.0-SNAPSHOT, branch:7.13, build_id:7.13.0-878a5a45, build_duration_seconds:16295]
> [automation] update elastic stack version for testing 7.13.0-878a5a45

- docker-compose.yml
[start_time:Thu, 20 May 2021 05:22:15 GMT, release_branch:7.x, prefix:, end_time:Thu, 20 May 2021 10:05:12 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-a9c3399b, build_duration_seconds:16977]
> [automation] update elastic stack version for testing 7.14.0-a9c3399b

- docker-compose.yml
[start_time:Sun, 23 May 2021 12:25:11 GMT, release_branch:master, prefix:, end_time:Sun, 23 May 2021 18:33:38 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-8c8922fb, build_duration_seconds:22107]
> [automation] update elastic stack version for testing 8.0.0-8c8922fb

- docker-compose.yml
[start_time:Sun, 23 May 2021 12:16:12 GMT, release_branch:7.13, prefix:, end_time:Sun, 23 May 2021 17:30:06 GMT, manifest_version:2.0.0, version:7.13.0-SNAPSHOT, branch:7.13, build_id:7.13.0-d325823f, build_duration_seconds:18834]
> [automation] update elastic stack version for testing 7.13.0-d325823f

- changelogs/6.8.asciidoc
Adds 6.8.16 release notes. No new commits since the last release.
> docs: add 6.8.16 release notes

- docs/guide/opentelemetry-elastic.asciidoc
* Remove experimental limitation from native OTLP
* Remove self-managed limitation from native OTLP (per https://github.com/elastic/apm/issues/212)
* Move native OTLP above elastic exporter to encourage use
* Move tab-widget code to the bottom of the page
> docs: Encourage native OpenTelemetry intake use

- docker-compose.yml
[start_time:Mon, 24 May 2021 12:15:52 GMT, release_branch:master, prefix:, end_time:Mon, 24 May 2021 16:51:55 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-394043ad, build_duration_seconds:16563]
> [automation] update elastic stack version for testing 8.0.0-394043ad

- docker-compose.yml
[start_time:Tue, 25 May 2021 00:13:42 GMT, release_branch:7.13, prefix:, end_time:Tue, 25 May 2021 04:51:38 GMT, manifest_version:2.0.0, version:7.13.0-SNAPSHOT, branch:7.13, build_id:7.13.0-b10ff4f4, build_duration_seconds:16676]
> [automation] update elastic stack version for testing 7.13.0-b10ff4f4

- changelogs/head.asciidoc
- model/modeldecoder/nullable/nullable.go
Fix decoding of timestamps on 32-bit systems. Rather than decoding as 32-bit or 64-bit depending on the host architecture, always decode as 64-bit.
Lazy: `GOARCH=386 go test -v ./model/modeldecoder/v2/`
Better: install apm-server on a 32-bit VM and send it some data.
Closes https://github.com/elastic/apm-server/issues/5307
> model/modeldecoder: fix 32-bit timestamp decoding

- agentcfg/fetch_test.go
- beater/api/config/agent/handler_test.go
- beater/jaeger/grpc_test.go
- kibana/kibanatest/kibana.go
- Move tests.MockKibanaClient to its own package (#5273)
> [7.x] Move tests.MockKibanaClient to its own package (#5273)

- docs/guide/agent-server-compatibility.asciidoc
I'm not sure how to change RUM's first column background color to gray, but this will fix the broken box with the right columns' order from left to right
> [DOC] Fixing broken box for RUM

- docs/guide/agent-server-compatibility.asciidoc
- Fixing broken box for RUM (#5295)
> [7.13] Fixing broken box for RUM (#5295)

- docs/guide/agent-server-compatibility.asciidoc
- Fixing broken box for RUM (#5295)
> [7.x] Fixing broken box for RUM (#5295)

- docker-compose.yml
Set the SERVER_HOST environment variable for kibana in docker-compose to avoid being broken by issues like https://github.com/elastic/kibana/issues/100533
> docker-compose: explicitly set kibana host

- docker-compose.yml
[start_time:Tue, 25 May 2021 12:21:23 GMT, release_branch:master, prefix:, end_time:Tue, 25 May 2021 17:04:51 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-5197c308, build_duration_seconds:17008]
> [automation] update elastic stack version for testing 8.0.0-5197c308

- docker-compose.yml
[start_time:Tue, 25 May 2021 05:19:07 GMT, release_branch:7.x, prefix:, end_time:Tue, 25 May 2021 09:55:35 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-9eca24b7, build_duration_seconds:16588]
> [automation] update elastic stack version for testing 7.14.0-9eca24b7

- docker-compose.yml
[start_time:Wed, 26 May 2021 05:26:20 GMT, release_branch:7.x, prefix:, end_time:Wed, 26 May 2021 10:07:36 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-f385fee6, build_duration_seconds:16876]
> [automation] update elastic stack version for testing 7.14.0-f385fee6

- docker-compose.yml
[start_time:Wed, 26 May 2021 13:43:47 GMT, release_branch:7.13, prefix:, end_time:Wed, 26 May 2021 18:36:15 GMT, manifest_version:2.0.0, version:7.13.1-SNAPSHOT, branch:7.13, build_id:7.13.1-66aca119, build_duration_seconds:17548]
> [automation] update elastic stack version for testing 7.13.1-66aca119

- changelogs/head.asciidoc
- x-pack/apm-server/sampling/processor.go
- x-pack/apm-server/sampling/processor_test.go
- x-pack/apm-server/sampling/pubsub/position.go
- x-pack/apm-server/sampling/pubsub/pubsub.go
- x-pack/apm-server/sampling/pubsub/pubsub_integration_test.go
- x-pack/apm-server/sampling/pubsub/pubsub_test.go
- x-pack/apm-server/sampling/pubsub/pubsubtest/client.go
Currently, the tail-sampling sampled trace ID subscriber will resume searching from the beginning of each index when the server is restarted. This could be quite expensive in heavy environments. To address this issue, this PR makes the subscriber resumable across restarts.
We introduce `sampling/pubsub.Position`, which holds information about the subscriber's "position" in the sampled traces data stream. Internally this holds a map of indices to observed `_seq_no` values. `pubsub.Pubsub.SubscribeSampledTraceIDs` now accepts a channel to which it will send the subscriber's position when it changes.
The `sampling.Processor` will now persist the subsciber's position to disk in the tail-sampling local storage directory, in a file called "subscriber_position.json". When the processor starts it …
> sampling: persist subscriber position

- docker-compose.yml
[start_time:Thu, 27 May 2021 12:15:35 GMT, release_branch:master, prefix:, end_time:Thu, 27 May 2021 16:56:01 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-3dd1a25d, build_duration_seconds:16826]
> [automation] update elastic stack version for testing 8.0.0-3dd1a25d

- docker-compose.yml
[start_time:Thu, 27 May 2021 05:14:35 GMT, release_branch:7.x, prefix:, end_time:Thu, 27 May 2021 09:56:32 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-d593413f, build_duration_seconds:16917]
> [automation] update elastic stack version for testing 7.14.0-d593413f

- docker-compose.yml
[start_time:Thu, 27 May 2021 12:13:09 GMT, release_branch:7.13, prefix:, end_time:Thu, 27 May 2021 17:10:28 GMT, manifest_version:2.0.0, version:7.13.1-SNAPSHOT, branch:7.13, build_id:7.13.1-b3918c55, build_duration_seconds:17839]
> [automation] update elastic stack version for testing 7.13.1-b3918c55

- _beats/dev-tools/common.bash
Fix a typo introduced in https://github.com/elastic/apm-server/pull/5333. I took the liberty of changing it to install to `~/.gvm/gvm` rather than `/usr/local/bin/gvm`.
> Fix gvm installation

- _meta/beat.yml
- apm-server.docker.yml
- apm-server.yml
Since this is predominantly existing for use by
elastic-agent/fleet, exposing this as manual
configuration in the .yml file is not necessary.
Non-functional change
> remove agent_config sample configuration

- docker-compose.yml
[start_time:Sun, 30 May 2021 05:15:16 GMT, release_branch:7.x, prefix:, end_time:Sun, 30 May 2021 09:49:56 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-62d7f45e, build_duration_seconds:16480]
> [automation] update elastic stack version for testing 7.14.0-62d7f45e

- docker-compose.yml
[start_time:Sun, 30 May 2021 12:15:21 GMT, release_branch:7.13, prefix:, end_time:Sun, 30 May 2021 17:19:53 GMT, manifest_version:2.0.0, version:7.13.1-SNAPSHOT, branch:7.13, build_id:7.13.1-1ba26435, build_duration_seconds:18272]
> [automation] update elastic stack version for testing 7.13.1-1ba26435

- docker-compose.yml
[start_time:Fri, 28 May 2021 12:15:30 GMT, release_branch:master, prefix:, end_time:Fri, 28 May 2021 16:46:28 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-68ee0bbd, build_duration_seconds:16258]
> [automation] update elastic stack version for testing 8.0.0-68ee0bbd

- docker-compose.yml
[start_time:Mon, 31 May 2021 05:15:22 GMT, release_branch:7.x, prefix:, end_time:Mon, 31 May 2021 09:56:04 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-631ae8b8, build_duration_seconds:16842]
> [automation] update elastic stack version for testing 7.14.0-631ae8b8

- docker-compose.yml
[start_time:Mon, 31 May 2021 12:13:36 GMT, release_branch:7.13, prefix:, end_time:Mon, 31 May 2021 16:50:16 GMT, manifest_version:2.0.0, version:7.13.1-SNAPSHOT, branch:7.13, build_id:7.13.1-e4c670b7, build_duration_seconds:16600]
> [automation] update elastic stack version for testing 7.13.1-e4c670b7

- agentcfg/fetch.go
- beater/api/config/agent/handler.go
- beater/api/config/agent/handler_test.go
- beater/api/mux.go
- beater/api/mux_intake_rum_test.go
- beater/api/mux_sourcemap_handler_test.go
- beater/authorization/builder.go
- beater/authorization/builder_test.go
- beater/beater.go
- beater/beater_test.go
- beater/config/agentconfig.go
- beater/config/api_key.go
- beater/config/api_key_test.go
- beater/config/config.go
- beater/config/config_test.go
- beater/config/expvar.go
- beater/config/instrumentation.go
- beater/config/instrumentation_test.go
- beater/config/kibana.go
- beater/config/pprof.go
- beater/config/register.go
- beater/config/rum.go
- beater/config/sampling.go
- beater/http.go
- beater/middleware/rate_limit_middleware.go
- beater/telemetry.go
- processor/stream/processor_test.go
- x-pack/apm-server/main.go
- remove some "setup" methods, set default values before unpacking
- unexport DefaultKibanaAgentConfig
- de-pointer various config fields to avoid the need for nil-pointer checks, and rely on default values; remove "IsEnabled" methods in favour of setting default values for Enabled fields and accessing those directly
- move various config types into their own files
- remove dead validator code
Setting up for implementing https://github.com/elastic/apm-server/issues/5347
> Tidy up beater/config

- docker-compose.yml
[start_time:Tue, 1 Jun 2021 05:14:58 GMT, release_branch:7.x, prefix:, end_time:Tue, 1 Jun 2021 09:56:18 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-bdd01eb6, build_duration_seconds:16880]
> [automation] update elastic stack version for testing 7.14.0-bdd01eb6

- docker-compose.yml
[start_time:Wed, 2 Jun 2021 00:14:47 GMT, release_branch:7.13, prefix:, end_time:Wed, 2 Jun 2021 04:53:59 GMT, manifest_version:2.0.0, version:7.13.1-SNAPSHOT, branch:7.13, build_id:7.13.1-b438d0e4, build_duration_seconds:16752]
> [automation] update elastic stack version for testing 7.13.1-b438d0e4

- docker-compose.yml
[start_time:Fri, 4 Jun 2021 00:15:21 GMT, release_branch:7.13, prefix:, end_time:Fri, 4 Jun 2021 04:44:39 GMT, manifest_version:2.0.0, version:7.13.2-SNAPSHOT, branch:7.13, build_id:7.13.2-56fcd1bc, build_duration_seconds:16158]
> [automation] update elastic stack version for testing 7.13.2-56fcd1bc

- docker-compose.yml
[start_time:Thu, 3 Jun 2021 05:14:39 GMT, release_branch:7.x, prefix:, end_time:Thu, 3 Jun 2021 09:44:53 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-983e13ea, build_duration_seconds:16214]
> [automation] update elastic stack version for testing 7.14.0-983e13ea

- docker-compose.yml
[start_time:Sun, 6 Jun 2021 05:15:53 GMT, release_branch:7.x, prefix:, end_time:Sun, 6 Jun 2021 09:52:44 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-bb1ffc77, build_duration_seconds:16611]
> [automation] update elastic stack version for testing 7.14.0-bb1ffc77

- docker-compose.yml
[start_time:Mon, 7 Jun 2021 00:15:04 GMT, release_branch:7.13, prefix:, end_time:Mon, 7 Jun 2021 04:50:49 GMT, manifest_version:2.0.0, version:7.13.2-SNAPSHOT, branch:7.13, build_id:7.13.2-f9522f62, build_duration_seconds:16545]
> [automation] update elastic stack version for testing 7.13.2-f9522f62

- docker-compose.yml
[start_time:Mon, 7 Jun 2021 12:13:58 GMT, release_branch:7.13, prefix:, end_time:Mon, 7 Jun 2021 17:00:16 GMT, manifest_version:2.0.0, version:7.13.2-SNAPSHOT, branch:7.13, build_id:7.13.2-ce511058, build_duration_seconds:17178]
> [automation] update elastic stack version for testing 7.13.2-ce511058

- docker-compose.yml
[start_time:Tue, 8 Jun 2021 00:15:17 GMT, release_branch:7.13, prefix:, end_time:Tue, 8 Jun 2021 05:07:39 GMT, manifest_version:2.0.0, version:7.13.2-SNAPSHOT, branch:7.13, build_id:7.13.2-a3fd10d8, build_duration_seconds:17542]
> [automation] update elastic stack version for testing 7.13.2-a3fd10d8

- docker-compose.yml
[start_time:Wed, 9 Jun 2021 12:15:33 GMT, release_branch:7.13, prefix:, end_time:Wed, 9 Jun 2021 16:58:10 GMT, manifest_version:2.0.0, version:7.13.2-SNAPSHOT, branch:7.13, build_id:7.13.2-e9f2bb70, build_duration_seconds:16957]
> [automation] update elastic stack version for testing 7.13.2-e9f2bb70

- docker-compose.yml
[start_time:Wed, 9 Jun 2021 05:19:02 GMT, release_branch:7.x, prefix:, end_time:Wed, 9 Jun 2021 19:33:30 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-28665d9b, build_duration_seconds:51268]
> [automation] update elastic stack version for testing 7.14.0-28665d9b

- docker-compose.yml
[start_time:Thu, 10 Jun 2021 12:14:50 GMT, release_branch:7.13, prefix:, end_time:Thu, 10 Jun 2021 17:02:54 GMT, manifest_version:2.0.0, version:7.13.2-SNAPSHOT, branch:7.13, build_id:7.13.2-66efaded, build_duration_seconds:17284]
> [automation] update elastic stack version for testing 7.13.2-66efaded

- docker-compose.yml
[start_time:Sun, 13 Jun 2021 12:15:43 GMT, release_branch:7.13, prefix:, end_time:Sun, 13 Jun 2021 16:58:30 GMT, manifest_version:2.0.0, version:7.13.2-SNAPSHOT, branch:7.13, build_id:7.13.2-34e8ddd9, build_duration_seconds:16967]
> [automation] update elastic stack version for testing 7.13.2-34e8ddd9

- systemtest/containers.go
- systemtest/fleet_test.go
Due to some changes in elastic-agent (https://github.com/elastic/beats/pull/24817), injection of the apm-server binary became ineffective and we have been running system tests with the published artifacts.
Artifacts (such as the apm-server) are now unpacked into state/data/install/<artifact>. The state/data/install directory is expected to be owned by the elastic-agent user, so we can no longer bind mount the apm-server binary. Instead, we now create a custom Docker image and copy in the apm-server and apm-server.yml files.
> systemtest: fix apm-server binary injection

- docker-compose.yml
[start_time:Mon, 14 Jun 2021 12:15:13 GMT, release_branch:7.13, prefix:, end_time:Mon, 14 Jun 2021 17:03:28 GMT, manifest_version:2.0.0, version:7.13.2-SNAPSHOT, branch:7.13, build_id:7.13.2-f55bee50, build_duration_seconds:17295]
> [automation] update elastic stack version for testing 7.13.2-f55bee50

- docker-compose.yml
Existing default health check in the package-registry timeout after 30 seconds. See https://github.com/elastic/package-registry/blob/master/Dockerfile#L37
But the docker container takes a bit longer than 30 seconds therefore the health check reports unhealthy and the system tests cannot be executed.
For instance, the build number 996 in the master branch failed and the docker logs for the package-registry container can be seen [here](https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/master/996/artifact/docker-info/c3660573cbe9.log/*view*/), in a nutshell the package manifest took 36 to be loaded:
```
2021/06/14 15:48:08 system              	    0.13.3	/packages/snapshot/system/0.13.3
2021/06/14 15:48:08 traefik             	     0.2.0	/packages/snapshot/traefik/0.2.0 …
```
> Override healthcheck for the package-registry docker container for running the system tests

- magefile.go
TestPackages uses dependencies that are only defined in beats go.mod/go.sum, but as we're running it from apm-server it tries
to use apm-server's go.mod/go.sum. Make sure we use the one in beats.
> magefile: use beats/go.mod for TestPackages

- docker-compose.yml
[start_time:Wed, 16 Jun 2021 07:01:19 GMT, release_branch:master, prefix:, end_time:Wed, 16 Jun 2021 11:44:04 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-943ef2c0, build_duration_seconds:16965]
> [automation] update elastic stack version for testing 8.0.0-943ef2c0

- changelogs/head.asciidoc
- internal/.otel_collector_mixin/otlptext/mixin.go
- internal/otel_collector/otlptext/mixin.go
- processor/otel/consumer.go
- processor/otel/consumer_test.go
- processor/otel/metrics.go
- processor/otel/metrics_test.go
Add debug logging of OpenTelemetry traces and metrics payloads. We transform the spans, so it may be useful to log the original payload when transformation goes awry.
1. Run `apm-server -e -d otel`
2. Send OpenTelemetry traces and metrics
3. Check that the payloads are logged
4. Run again without debug selectors, check that payloads are not logged
Closes https://github.com/elastic/apm-server/issues/5431
> processor/otel: add debug logging of payloads

- docker-compose.yml
[start_time:Mon, 21 Jun 2021 12:14:44 GMT, release_branch:7.13, prefix:, end_time:Mon, 21 Jun 2021 16:55:50 GMT, manifest_version:2.0.0, version:7.13.3-SNAPSHOT, branch:7.13, build_id:7.13.3-6b02e37f, build_duration_seconds:16866]
> [automation] update elastic stack version for testing 7.13.3-6b02e37f

- docker-compose.yml
[start_time:Wed, 23 Jun 2021 00:15:26 GMT, release_branch:7.13, prefix:, end_time:Wed, 23 Jun 2021 04:50:58 GMT, manifest_version:2.0.0, version:7.13.3-SNAPSHOT, branch:7.13, build_id:7.13.3-87af5e25, build_duration_seconds:16532]
> [automation] update elastic stack version for testing 7.13.3-87af5e25

- beater/api/intake/handler.go
- beater/api/intake/handler_test.go
- systemtest/rum_test.go
Copy the batch processor in the closure before copying, to avoid wrapping it multiple times.
Enable RUM, send 200 RUM events over 10 requests - make sure this completes without triggering the rate limiter.
None, fixes bug introduced in https://github.com/elastic/apm-server/pull/5492
> beater/api/intake: fix rate limiting

- apmpackage/apm/agent/input/template.yml.hbs
this is no longer needed in fleet policies
This was supposed to be removed already but somehow was not.
Confirm the value is not rendered in fleet policies when running kibana pointing at a version of package-registry that has been [updated with these changes](https://github.com/elastic/apm-server/tree/master/apmpackage#update--fix-a-package)
> remove sourcemap es api key

- docker-compose.yml
[start_time:Wed, 23 Jun 2021 12:14:32 GMT, release_branch:7.13, prefix:, end_time:Wed, 23 Jun 2021 17:04:39 GMT, manifest_version:2.0.0, version:7.13.3-SNAPSHOT, branch:7.13, build_id:7.13.3-280f3dca, build_duration_seconds:17407]
> [automation] update elastic stack version for testing 7.13.3-280f3dca

- docker-compose.yml
[start_time:Thu, 24 Jun 2021 12:15:07 GMT, release_branch:7.13, prefix:, end_time:Thu, 24 Jun 2021 16:59:06 GMT, manifest_version:2.0.0, version:7.13.3-SNAPSHOT, branch:7.13, build_id:7.13.3-9167705c, build_duration_seconds:17039]
> [automation] update elastic stack version for testing 7.13.3-9167705c

- docker-compose.yml
[start_time:Mon, 28 Jun 2021 00:15:48 GMT, release_branch:7.13, prefix:, end_time:Mon, 28 Jun 2021 04:54:10 GMT, manifest_version:2.0.0, version:7.13.3-SNAPSHOT, branch:7.13, build_id:7.13.3-ce6a5891, build_duration_seconds:16702]
> [automation] update elastic stack version for testing 7.13.3-ce6a5891

- docker-compose.yml
- systemtest/approvals/TestFleetIntegration.approved.json
[start_time:Thu, 24 Jun 2021 05:14:20 GMT, release_branch:7.x, prefix:, end_time:Thu, 24 Jun 2021 09:53:40 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.x, build_id:7.14.0-25663e85, build_duration_seconds:16760]
> [automation] update elastic stack version for testing 7.14.0-25663e85

- docker-compose.yml
[start_time:Tue, 29 Jun 2021 00:15:28 GMT, release_branch:7.13, prefix:, end_time:Tue, 29 Jun 2021 04:53:45 GMT, manifest_version:2.0.0, version:7.13.3-SNAPSHOT, branch:7.13, build_id:7.13.3-6b302f39, build_duration_seconds:16697]
> [automation] update elastic stack version for testing 7.13.3-6b302f39

- systemtest/instrumentation_test.go
Disable the TestAPMServerProfiling system test, which intermittently times out. This is an experimental feature; we should fix the test if/when we proceed with the feature.
Closes https://github.com/elastic/apm-server/issues/5322
> systemtest: disable profiling tests

- kibana/send_config.go
- kibana/send_config_test.go
Remove the config options that are set by cloud allocator (not by user) and that are not supported in the integration. 
See [supported user settings](https://www.elastic.co/guide/en/cloud/current/ec-manage-apm-settings.html#ec-apm-settings).
Create deployment in shared ECE environment and ensure that none of these options shows up as unsupported when triggering the migration.
follow up on https://github.com/elastic/apm-server/issues/5377
> [cloud] Remove cloud defaults from user settings sent to Kibana

- docs/secure-communication-agents.asciidoc
- Update secure-communication-agents.asciidoc (#5379)
> [7.x] Update secure-communication-agents.asciidoc (#5379)

- sourcemap/store_test.go
use same ctx.WithTimeout in server and request.
previously we were using a separate ctx.
fixes https://github.com/elastic/apm-server/issues/5571
Non-functional change
> fix flaky test

- docker-compose.yml
[start_time:Mon, 28 Jun 2021 12:23:10 GMT, release_branch:master, prefix:, end_time:Mon, 28 Jun 2021 17:12:26 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-e1177df4, build_duration_seconds:17356]
> [automation] update elastic stack version for testing 8.0.0-e1177df4

- docker-compose.yml
[start_time:Tue, 29 Jun 2021 12:14:51 GMT, release_branch:7.13, prefix:, end_time:Tue, 29 Jun 2021 16:58:11 GMT, manifest_version:2.0.0, version:7.13.3-SNAPSHOT, branch:7.13, build_id:7.13.3-db555786, build_duration_seconds:17000]
> [automation] update elastic stack version for testing 7.13.3-db555786

- x-pack/apm-server/sampling/processor.go
- x-pack/apm-server/sampling/pubsub/pubsub.go
- x-pack/apm-server/sampling/pubsub/pubsub_integration_test.go
- x-pack/apm-server/sampling/pubsub/pubsub_test.go
Revise the pubsub API so that the PublishSampledTraceIDs method is long-lived and accepts a channel of trace IDs. This brings PublishSampledTraceIDs closer to the API of SubscribeSampledTraceIDs, and ensures we properly close the BulkIndexer used by the publisher when it exits.
Also, fix a race in the pubsub tests. We now write HTTP response from the handler goroutine rather than in another goroutine which waits for the request. This avoids a race in the existing test code, where the client receives the response and closes the connection, causing the server's handler context to be cancelled before the handler returns.
Closes https://github.com/elastic/apm-server/issues/5493
Closes https://github.com/elastic/apm-server/issues/5480
> sampling/pubsub: minor fixes

- sourcemap/store_test.go
The test was failing because the dial attempt would
sometimes timeout and return a different error.
Change the test to first wait for the request to be
received by the server, and then check that context
cancellation is honoured. We do this by explicitly
cancelling the context, rather than using a timeout.
Closes https://github.com/elastic/apm-server/issues/5549
> sourcemap: fix flaky test

- docker-compose.yml
[start_time:Wed, 30 Jun 2021 00:15:28 GMT, release_branch:7.13, prefix:, end_time:Wed, 30 Jun 2021 04:57:04 GMT, manifest_version:2.0.0, version:7.13.3-SNAPSHOT, branch:7.13, build_id:7.13.3-421443ae, build_duration_seconds:16896]
> [automation] update elastic stack version for testing 7.13.3-421443ae

- docker-compose.yml
[start_time:Wed, 30 Jun 2021 00:25:00 GMT, release_branch:master, prefix:, end_time:Wed, 30 Jun 2021 05:16:45 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-6a0cf37e, build_duration_seconds:17505]
> [automation] update elastic stack version for testing 8.0.0-6a0cf37e

- docker-compose.yml
[start_time:Wed, 30 Jun 2021 12:16:03 GMT, release_branch:7.13, prefix:, end_time:Wed, 30 Jun 2021 17:13:44 GMT, manifest_version:2.0.0, version:7.13.3-SNAPSHOT, branch:7.13, build_id:7.13.3-dbdefa2a, build_duration_seconds:17861]
> [automation] update elastic stack version for testing 7.13.3-dbdefa2a

- NOTICE.txt
- cmd/version.go
- go.mod
- go.sum
Bump apm-server version on 7.x to 7.15.0, and update beats to the latest commit on the 7.x branch.
libbeat still reports 7.14.0, as https://github.com/elastic/beats/pull/26621 hasn't yet been merged.
> Update to elastic/beats@0de1d8d7ec4b, bump to 7.15.0

- .mergify.yml
Update mergify config to add the v7.15.0 backport rule and update the v7.14.0 rule.
> Update mergify with 7.15 backport rule

- docker-compose.yml
[start_time:Sun, 4 Jul 2021 12:15:17 GMT, release_branch:7.14, prefix:, end_time:Sun, 4 Jul 2021 16:55:11 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-e1afed34, build_duration_seconds:16794]
> [automation] update elastic stack version for testing 7.14.0-e1afed34

- docker-compose.yml
[start_time:Sun, 4 Jul 2021 12:24:30 GMT, release_branch:master, prefix:, end_time:Sun, 4 Jul 2021 17:07:18 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-08d745df, build_duration_seconds:16968]
> [automation] update elastic stack version for testing 8.0.0-08d745df

- docs/secure-communication-agents.asciidoc
Fix typo in docs related to testing API Keys. The Elasticsearch API is `/_security/_authenticate`, not `/_security/_authentication`.
> docs: fix typo

- apmpackage/apm/manifest.yml
Add missing RUM vars to apmpackage manifest. The variables are already part of the template. 
Configure regexes in APM integration and ensure that matching stacktraces are not considered when ingesting data. 
follow up on #4528
> Add missing RUM vars to apmpackage manifest

- changelogs/7.13.asciidoc
Adds 7.13.3 release notes.
**Reviewers**: Should https://github.com/elastic/apm-server/pull/5506 be noted?
> docs: add 7.13.3 release notes

- changelogs/6.8.asciidoc
Cherry picks https://github.com/elastic/apm-server/pull/5597 to 6.8.
> [6.8] docs: add 6.8.17 release notes

- .ci/scripts/windows-test.ps1
We run the Python system tests on Windows, but almost all of them are skipped because we run them without the stack containers. What remains is a handful of trivial tests, so I don't think it's worth running them at all.
> Stop running python system tests on Windows

- systemtest/agentconfig.go
- systemtest/apmservertest/config.go
- systemtest/apmservertest/server.go
- systemtest/auth_test.go
- systemtest/instrumentation_test.go
- systemtest/jaeger_test.go
- systemtest/otlp_test.go
- systemtest/rum_test.go
Update system tests to use `apm-server.auth.*` config, in preparation of adding anonymous access support. We also extend the TestAuth tests to cover RUM, remove the RUM-specific test, and enhance the RUM agent config test to check the results are properly restricted.
Extracted from https://github.com/elastic/apm-server/pull/5623
Adds a `systemtest.CreateAgentConfig` function, which can be used in https://github.com/elastic/apm-server/issues/5487
> systemtest: use new auth config

- changelogs/head.asciidoc
- x-pack/apm-server/main.go
- x-pack/apm-server/main_test.go
When the server's policy changes, the server will internally stop and restart various workers, and re-register monitoring related to those workers. We must remove the existing monitoring vars first, to avoid panicking on re-registration.
1. Run apm-server with Fleet
2. Modify the policy (e.g. toggle RUM on/off)
3. Check that apm-server continues to run, picking up the new config
Fixes https://github.com/elastic/apm-server/issues/5665
> Don't panic re-registering monitoring functions

- .mergify.yml
- RELEASES.md
Change the labels used for triggering backports to explicitly specify the target branch name.
This avoids an issue where "v7.14.0" creates backports for 7.x, and then when we update mergify to have "v7.14.0" backport to 7.14 redundant backport PRs are created.
https://github.com/elastic/apm-server/pull/5669
https://github.com/elastic/apm-server/pull/5668
https://github.com/elastic/apm-server/pull/5667
...
> mergify: change backport trigger labels

- docs/guide/apm-doc-directory.asciidoc
- docs/guide/overview.asciidoc
- docs/guide/troubleshooting.asciidoc
- docs: free and open terminology (#5641)
> [7.x] docs: free and open terminology (#5641)

- docs/guide/apm-doc-directory.asciidoc
- docs/guide/overview.asciidoc
- docs/guide/troubleshooting.asciidoc
- docs: free and open terminology (#5641)
> [7.13] docs: free and open terminology (#5641)

- docs/guide/apm-doc-directory.asciidoc
- docs/guide/overview.asciidoc
- docs/guide/troubleshooting.asciidoc
- docs: free and open terminology (#5641)
> [7.14] docs: free and open terminology (#5641)

- .ci/jobs/apm-server-check-changelogs-mbp.yml
- .ci/jobs/apm-server-check-packages-mbp.yml
- .ci/jobs/defaults.yml
- .ci/jobs/update-beats-mbp.yml
First step to automate the update-beats proces.
For such, there will be a new Multibranch pipeline:
- which runs on a daily basis for the master branch by default.
- PRs won't be triggered by default, but in case of any changes in the scripts, this could be tested manually through the Jenkins UI.
Then, the pipeline with the automation will be created.
https://github.com/elastic/apm-server/issues/4941
> [JJBB] for the update-beats

- apmpackage/apm/agent/input/template.yml.hbs
- apmpackage/apm/changelog.yml
- apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/manifest.yml
- systemtest/fleet_test.go
- systemtest/fleettest/types.go
- systemtest/kibana.go
- systemtest/main_test.go
Bump the integration package version, and update it to use `apm-server.auth.*` config. This is a prerequisite for updating the package for anonymous auth support (https://github.com/elastic/apm-server/pull/5623).
Split some of the Fleet/Elastic Agent setup out of the system test `TestFleetIntegration`, into a separate function which can be reused. There's also a fix to the package policy creation to set defaults correctly, to avoid integration editor UI errors such as https://github.com/elastic/kibana/issues/105384.
Test that secret token and API Key auth continue to work in the Fleet integration.
https://github.com/elastic/apm-server/pull/5623
> Bump integration to 0.4.0, use apm-server.auth config

- docker-compose.yml
[start_time:Tue, 13 Jul 2021 15:16:27 GMT, release_branch:master, prefix:, end_time:Tue, 13 Jul 2021 19:50:19 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-2f008f4a, build_duration_seconds:16432]
> [automation] update elastic stack version for testing 8.0.0-2f008f4a

- docker-compose.yml
[start_time:Tue, 13 Jul 2021 15:18:39 GMT, release_branch:7.14, prefix:, end_time:Tue, 13 Jul 2021 20:02:29 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-c78a4632, build_duration_seconds:17030]
> [automation] update elastic stack version for testing 7.14.0-c78a4632

- apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
- apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
- apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
- apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
- apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
- apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.json
- beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
- ingest/pipeline/definition.json
- ingest/pipeline/definition.yml
- model/span.go
- model/span_test.go
- processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
- systemtest/ingest_test.go
For spans, we copy `destination.address` to `destination.ip` if the value is a valid IPv4 or IPv6 address. Move this from model transformation to the Elasticsearch ingest pipeline, to remove logic from model transformation code.
Send some spans to APM Server with destination address set, and check that `destination.address` is copied (or not) to `destination.ip` depending on whether it is a valid IPv4 or IPv6 address.
https://github.com/elastic/apm-server/issues/3565
> Move setting of destination.ip to ingest pipeline

- kibana/send_config.go
- kibana/send_config_test.go
Fix: Remove the wrong rum rate limit setting and send the correct one instead. 
See #5656
follow up on #5656
> Fix: remove unsupported rum rate limit key

- docs/guide/opentelemetry-elastic.asciidoc
- Document AWS Lambda OpenTelemetry support (#5674)
> [7.x] Document AWS Lambda OpenTelemetry support (#5674)

- docs/guide/opentelemetry-elastic.asciidoc
- Document AWS Lambda OpenTelemetry support (#5674)
> [7.14] Document AWS Lambda OpenTelemetry support (#5674)

- beater/api/profile/convert.go
- beater/api/profile/handler.go
- beater/api/profile/handler_test.go
- model/apmevent.go
- model/batch.go
- model/error.go
- model/error_test.go
- model/metricset.go
- model/metricset_test.go
- model/modelprocessor/environment_test.go
- model/modelprocessor/metadata.go
- model/profile.go
- model/profile_test.go
- model/span.go
- model/span_test.go
- model/transaction.go
- model/transaction_test.go
Change `model.APMEvent` to map to a single `beat.Event`, so we can later move common event properties such as "Metadata" up to the `APMEvent` type, and map `APMEvent` programatically.
The only one that did not already was `model.PprofPofile`. We redefine this as `model.ProfileSample`, which describes
a single profile sample, and move the conversion of pprof profiles to a batch of profile samples to the HTTP handler.
https://github.com/elastic/apm-server/issues/4410
https://github.com/elastic/apm-server/issues/4120
https://github.com/elastic/apm-server/issues/3565
> model: make APMEvents 1:1 with beat.Events

- processor/otel/consumer.go
- processor/otel/consumer_test.go
- processor/otel/metadata.go
- processor/otel/metadata_test.go
- systemtest/approvals/TestOTLPGRPCTraces.approved.json
- systemtest/otlp_test.go
If an unhandled array attribute is found in resource attributes, store that as a label like we do with span attributes.
Also, handle array attributes when translating to Elastic spans and not just transactions.
Send a trace with OTLP with array attributes at both the resource and span level, and ensure they are recorded as labels.
Fixes https://github.com/elastic/apm-server/issues/5663
> processor/otel: record array resource attributes

- beater/request/context.go
- beater/request/context_pool.go
- beater/request/context_test.go
- changelogs/head.asciidoc
After completing a request, immediately reset the context so we don't hold onto memory while the context in the memory pool.
When resetting request context, call mime/multipart.Form.RemoveAll to remove temporary files created for storing uploaded source maps. Although net/http does this at the end of a request, it does so on the original net/http.Request. This does not work when the request is copied (e.g. using Request.WithContext), which we do in various middleware.
1. Upload a source map that is greater than 32MB in size
2. Check that no "multipart-*" files are left behind in /tmp
Fixes https://github.com/elastic/apm-server/issues/5689
> beater/request: clear multpart.Form on reset

- docker-compose.yml
[start_time:Wed, 14 Jul 2021 12:15:47 GMT, release_branch:7.14, prefix:, end_time:Wed, 14 Jul 2021 16:54:14 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-11e92b49, build_duration_seconds:16707]
> [automation] update elastic stack version for testing 7.14.0-11e92b49

- docker-compose.yml
[start_time:Wed, 14 Jul 2021 12:24:09 GMT, release_branch:master, prefix:, end_time:Wed, 14 Jul 2021 17:05:38 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-52a5431f, build_duration_seconds:16889]
> [automation] update elastic stack version for testing 8.0.0-52a5431f

- processor/otel/consumer.go
- processor/otel/consumer_test.go
- processor/otel/metadata.go
- processor/otel/metadata_test.go
We were mistakenly handling the new `net.host.*` attributes as resource attributes, whereas they should be span attributes. These fields describe a network connection which will be specific to an operation (span), and not the service (resource) performing that operation.
`net.host.connection_type` has been updated to `net.host.connection.type`, per the spec change.
When https://github.com/elastic/apm-agent-ios/pull/46 lands, run a program instrumented with the iOS agent, and check that the information is indexed into `network.*` fields and not as labels. The only field that should show up as a label is `net.host.connection.subtype`, which is not …
> processor/otel: handle net.host.* as span attributes

- docker-compose.yml
[start_time:Wed, 14 Jul 2021 05:17:54 GMT, release_branch:7.x, prefix:, end_time:Wed, 14 Jul 2021 09:55:47 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.x, build_id:7.15.0-588e7872, build_duration_seconds:16673]
> [automation] update elastic stack version for testing 7.15.0-588e7872

- agentcfg/reporter.go
- apmpackage/apm/docs/README.md
- beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
- docs/data/elasticsearch/generated/metricsets.json
- model/metricset.go
- model/metricset_test.go
- model/modeldecoder/rumv3/decoder.go
- model/modeldecoder/rumv3/metricset_test.go
- model/modeldecoder/rumv3/transaction_test.go
- model/modeldecoder/v2/decoder.go
- model/modeldecoder/v2/metricset_test.go
- model/modelprocessor/metricsetname.go
- model/modelprocessor/metricsetname_test.go
- processor/otel/metrics.go
- processor/otel/metrics_test.go
- processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationMinimalService.approved.json
- processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
- systemtest/approvals/TestApprovedMetrics.approved.json
- systemtest/approvals/TestServiceDestinationAggregation.approved.json
- systemtest/approvals/TestTransactionAggregation.approved.json
- systemtest/approvals/TestTransactionAggregationShutdown.approved.json
- systemtest/metrics_test.go
- tests/system/metricset.approved.json
- x-pack/apm-server/aggregation/spanmetrics/aggregator.go
- x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
- x-pack/apm-server/aggregation/txmetrics/aggregator.go
- x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
A few smallish changes to the `model.Metricset` type, for future-proofing. The goal is to make the type suitable for generating transformation to `beat.Events` logic later, while making the type better suited to protobuf definition in the short term.
`model.Metricset.Samples` is now a map, instead of a slice of named metrics, and the metrics fields are added as flat dotted field namess rather than hierarchical objects.
In the future we will send the samples map as-is (with values, type, and unit) to Elasticsearch and perform transformation to top-level metrics fields and dynamic templates completely in the ingest pipeline.
`model.Sample` is now called `model.MetricsetSample`, to clarify its relationship with `model.Metricset`.
We no longer set "_doc_count" in transformation; this is now …
> Restructure model.Metricset

- beater/beater.go
- model/error.go
- model/error_test.go
- model/modeldecoder/rumv3/error_test.go
- model/modeldecoder/v2/error_test.go
- model/modelprocessor/groupingkey.go
- model/modelprocessor/groupingkey_test.go
- processor/otel/test_approved/span_jaeger_http.approved.json
- processor/otel/test_approved/transaction_jaeger_full.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationMetadataNullValues.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationMinimalService.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationRumErrors.approved.json
- processor/stream/test_approved_es_documents/testIntakeRUMV3Errors.approved.json
- testdata/jaeger/batch_0.approved.json
- testdata/jaeger/batch_1.approved.json
Move error grouping key calculation out of model transformation into a model processor, so we can generate transformation code. "grouping_key" has disappeared from many of the test approval files, as they run without the model processors. Note that the system tests approvals have not changed.
> Move grouping key calculation to model processor

- changelogs/7.13.asciidoc
> [7.13] docs: add 7.13.4 cl (#5756)

- changelogs/7.13.asciidoc
> [7.14] docs: add 7.13.4 cl (#5756)

- changelogs/7.13.asciidoc
> [7.x] docs: add 7.13.4 cl (#5756)

- model/modeldecoder/rumv3/decoder.go
- model/modeldecoder/v2/decoder.go
- model/transaction.go
- model/transaction_test.go
- processor/otel/consumer.go
- processor/otel/exceptions_test.go
- processor/otel/test_approved/transaction_jaeger_full.approved.json
- sampling/sampling.go
- sampling/sampling_test.go
- testdata/jaeger/batch_0.approved.json
- tests/system/jaeger_batch_0_auth_tag_removed.approved.json
- tests/system/jaeger_batch_0_authorization.approved.json
- x-pack/apm-server/sampling/processor.go
- x-pack/apm-server/sampling/processor_test.go
`model.Transaction.Sampled` is no longer a pointer type.
Now we always set the `Sampled` flag when instantiating
the `Transaction` object. If an Elastic APM agent does
not report "sampled", then we now set the value to true
when decoding the event, rather than at transformation
time. OTel/Jaeger agents only ever send sampled events,
so in processor/otel we always set Sampled to true.
#4120
#3565
> model: de-pointer Transaction.Sampled

- apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/apm_data_stream_migration.json
- apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/apm_data_stream_migration.json
- apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/apm_data_stream_migration.json
- apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/apm_data_stream_migration.json
- apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/apm_data_stream_migration.json
- changelogs/head.asciidoc
- ingest/pipeline/definition.json
- ingest/pipeline/definition.yml
- systemtest/elasticsearch.go
- systemtest/ingest_test.go
Introduce a new ingest pipeline, `apm_data_stream_migration`, which can be used in a reindex operation to set data_stream fields on events and route them to appropriate data streams.
1. Run apm-server standalone, send some data of various types
2. Install the "apm" integration (no need to add it to an agent/policy etc., just need the index templates to be created)
3. Reindex `apm-*` using this pipeline, excluding `processor.event: onboarding`
4. Check the events have `data_stream.*` fields added, and they are routed to the correct data streams
Closes https://github.com/elastic/apm-server/issues/4854
> ingest: introduce apm_data_stream_migration

- docker-compose.yml
[start_time:Wed, 21 Jul 2021 00:24:20 GMT, release_branch:master, prefix:, end_time:Wed, 21 Jul 2021 04:43:25 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-1e9bea0f, build_duration_seconds:15545]
> [automation] update elastic stack version for testing 8.0.0-1e9bea0f

- docker-compose.yml
[start_time:Tue, 20 Jul 2021 05:17:57 GMT, release_branch:7.x, prefix:, end_time:Tue, 20 Jul 2021 09:43:05 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.x, build_id:7.15.0-c23a5439, build_duration_seconds:15908]
> [automation] update elastic stack version for testing 7.15.0-c23a5439

- docker-compose.yml
[start_time:Tue, 20 Jul 2021 12:16:00 GMT, release_branch:7.14, prefix:, end_time:Tue, 20 Jul 2021 17:05:53 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-cff72e71, build_duration_seconds:17393]
> [automation] update elastic stack version for testing 7.14.0-cff72e71

- docker-compose.yml
[start_time:Wed, 21 Jul 2021 12:17:25 GMT, release_branch:master, prefix:, end_time:Wed, 21 Jul 2021 16:52:14 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-a6334483, build_duration_seconds:16489]
> [automation] update elastic stack version for testing 8.0.0-a6334483

- docker-compose.yml
[start_time:Wed, 21 Jul 2021 05:14:22 GMT, release_branch:7.14, prefix:, end_time:Wed, 21 Jul 2021 10:07:26 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-803ff817, build_duration_seconds:17584]
> [automation] update elastic stack version for testing 7.14.0-803ff817

- docker-compose.yml
[start_time:Wed, 21 Jul 2021 05:27:16 GMT, release_branch:7.x, prefix:, end_time:Wed, 21 Jul 2021 09:47:57 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.x, build_id:7.15.0-192e1003, build_duration_seconds:15641]
> [automation] update elastic stack version for testing 7.15.0-192e1003

- .ci/scripts/update-beats.sh
- .gitignore
- Makefile
- README.md
As discussed offline, this should help to automate the bump even for a change in the go-version. Similar to what it was done in https://github.com/elastic/apm-server/pull/5754
`make update-beats`
but you need to use a specific git commit that can run the above as expected:
```
git revert 375aa84ce88f2bdf2710d292426ab74ffa2db7f4
make update-beats
```
produces:
```diff
diff --git a/.go-version b/.go-version
index de646d2fc..0d92a1028 100644
--- a/.go-version
+++ b/.go-version
@@ -1 +1 @@
-1.16.6
+1.16.5
diff --git a/Dockerfile b/Dockerfile
index 7f149bd08..dd107742b 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM golang:1.16.6
+FROM golang:1.16.5
MAINTAINER Nicolas Ruflin <ruflin@elastic.co>
RUN set -x && \
diff --git a/NOTICE.txt b/NOTICE.txt
index ddba22ae4..69a550aef …
```
> chore: update-beats goal to bump the go version

- docs/apm-package/apm-integration.asciidoc
- docs/apm-package/configure.asciidoc
- docs/apm-package/data-streams.asciidoc
- docs/apm-package/input-apm.asciidoc
- Document data streams migration limitations (#5771)
> [7.x] Document data streams migration limitations (#5771)

- docs/apm-package/apm-integration.asciidoc
- docs/apm-package/configure.asciidoc
- docs/apm-package/data-streams.asciidoc
- docs/apm-package/input-apm.asciidoc
- Document data streams migration limitations (#5771)
> [7.14] Document data streams migration limitations (#5771)

- model/error.go
- model/error_test.go
- model/labels.go
- model/modeldecoder/modeldecoderutil/exception.go
- model/modeldecoder/modeldecoderutil/labels.go
- model/modeldecoder/rumv3/decoder.go
- model/modeldecoder/rumv3/error_test.go
- model/modeldecoder/v2/decoder.go
- model/modeldecoder/v2/error_test.go
When modeldecoder decodes numbers and stores them in `interface{}` fields, it has been storing them as `json.Numbers` and we would later convert these to numbers during model transformation. As this logic is specific to how `modeldecoder` decodes, and not to any other inputs (e.g. OTLP), move this "normalisation" logic to `modeldecoder`.
#4120
#3565
> Move model value normalisation to modeldecoder

- docker-compose.yml
[start_time:Thu, 22 Jul 2021 00:24:11 GMT, release_branch:master, prefix:, end_time:Thu, 22 Jul 2021 04:56:35 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-1aed0c4f, build_duration_seconds:16344]
> [automation] update elastic stack version for testing 8.0.0-1aed0c4f

- docker-compose.yml
[start_time:Thu, 22 Jul 2021 05:14:36 GMT, release_branch:7.x, prefix:, end_time:Thu, 22 Jul 2021 09:55:17 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.x, build_id:7.15.0-5e783247, build_duration_seconds:16841]
> [automation] update elastic stack version for testing 7.15.0-5e783247

- docker-compose.yml
[start_time:Sun, 25 Jul 2021 12:25:15 GMT, release_branch:master, prefix:, end_time:Sun, 25 Jul 2021 17:28:04 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-cdc598b1, build_duration_seconds:18169]
> [automation] update elastic stack version for testing 8.0.0-cdc598b1

- docker-compose.yml
[start_time:Sun, 25 Jul 2021 05:17:29 GMT, release_branch:7.x, prefix:, end_time:Sun, 25 Jul 2021 10:41:09 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.x, build_id:7.15.0-514bcfaf, build_duration_seconds:19420]
> [automation] update elastic stack version for testing 7.15.0-514bcfaf

- docker-compose.yml
[start_time:Sun, 25 Jul 2021 12:14:54 GMT, release_branch:7.14, prefix:, end_time:Sun, 25 Jul 2021 18:01:28 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-0ce5c542, build_duration_seconds:20794]
> [automation] update elastic stack version for testing 7.14.0-0ce5c542

- docker-compose.yml
[start_time:Mon, 26 Jul 2021 05:16:08 GMT, release_branch:7.x, prefix:, end_time:Mon, 26 Jul 2021 10:55:18 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.x, build_id:7.15.0-6e66e5d1, build_duration_seconds:20350]
> [automation] update elastic stack version for testing 7.15.0-6e66e5d1

- docker-compose.yml
[start_time:Mon, 26 Jul 2021 16:13:08 GMT, release_branch:7.14, prefix:, end_time:Mon, 26 Jul 2021 21:42:18 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-de25a427, build_duration_seconds:19750]
> [automation] update elastic stack version for testing 7.14.0-de25a427

- docker-compose.yml
[start_time:Tue, 27 Jul 2021 12:38:22 GMT, release_branch:master, prefix:, end_time:Tue, 27 Jul 2021 18:02:53 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-571dad33, build_duration_seconds:19471]
> [automation] update elastic stack version for testing 8.0.0-571dad33

- docker-compose.yml
[start_time:Tue, 27 Jul 2021 05:25:15 GMT, release_branch:7.x, prefix:, end_time:Tue, 27 Jul 2021 10:38:16 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.x, build_id:7.15.0-bd471fd6, build_duration_seconds:18781]
> [automation] update elastic stack version for testing 7.15.0-bd471fd6

- x-pack/apm-server/sampling/eventstorage/codec.go
- x-pack/apm-server/sampling/eventstorage/jsoncodec.go
- x-pack/apm-server/sampling/eventstorage/sharded.go
- x-pack/apm-server/sampling/eventstorage/sharded_bench_test.go
- x-pack/apm-server/sampling/eventstorage/storage.go
- x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
- x-pack/apm-server/sampling/eventstorage/storage_test.go
- x-pack/apm-server/sampling/processor.go
- x-pack/apm-server/sampling/processor_test.go
Update the tail-based sampling package to read and write model.APMEvents, rather than model.Transactions and model.Spans.
This is in preparation for moving "metadata" up to APMEvent.
There is a breaking change to the tail-based sampling event storage: the "meta" byte used for identifying trace events is 'e', where we previously used 'T' for transactions and 'S' for spans. This feature is not yet GA, is not yet documented, and there will be further breaking changes; hence it is not highlighted in the changelog.
N/A
#4120
> sammpling: refactor to read/write model.APMEvents

- beater/api/intake/handler.go
- model/modeldecoder/rumv3/decoder.go
- model/modeldecoder/rumv3/error_test.go
- model/modeldecoder/rumv3/metadata_test.go
- model/modeldecoder/rumv3/metricset_test.go
- model/modeldecoder/rumv3/transaction_test.go
- model/modeldecoder/v2/decoder.go
- model/modeldecoder/v2/error_test.go
- model/modeldecoder/v2/metadata_test.go
- model/modeldecoder/v2/metricset_test.go
- model/modeldecoder/v2/span_test.go
- model/modeldecoder/v2/transaction_test.go
- processor/stream/benchmark_test.go
- processor/stream/processor.go
- processor/stream/processor_test.go
Modify the model/modeldecoder API such Decode function decode events into a model.Batch. This is another precursor to moving metadata up to APMEvent, where we will need to decode into an APMEvent rather than the nested event types (model.Transaction, etc.)
This change also enables us to remove the rumv3.Transaction exception, and have rumv3 add multiple events directly to the batch in the case of transactions with nested spans and metricsets. This in turn simplifies processor/stream.
#4120
#3565
> model/modeldecoder: decode events into model.Batch

- docker-compose.yml
[start_time:Tue, 27 Jul 2021 12:25:03 GMT, release_branch:7.14, prefix:, end_time:Tue, 27 Jul 2021 17:44:40 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-cd696777, build_duration_seconds:19177]
> [automation] update elastic stack version for testing 7.14.0-cd696777

- docker-compose.yml
[start_time:Wed, 28 Jul 2021 12:13:57 GMT, release_branch:master, prefix:, end_time:Wed, 28 Jul 2021 17:42:05 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-ae1e1c3b, build_duration_seconds:19688]
> [automation] update elastic stack version for testing 8.0.0-ae1e1c3b

- docker-compose.yml
[start_time:Wed, 28 Jul 2021 05:18:30 GMT, release_branch:7.x, prefix:, end_time:Wed, 28 Jul 2021 10:47:41 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.x, build_id:7.15.0-2cefb6a4, build_duration_seconds:19751]
> [automation] update elastic stack version for testing 7.15.0-2cefb6a4

- docker-compose.yml
[start_time:Wed, 28 Jul 2021 16:25:28 GMT, release_branch:7.14, prefix:, end_time:Wed, 28 Jul 2021 22:19:35 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-9fdd79d4, build_duration_seconds:21247]
> [automation] update elastic stack version for testing 7.14.0-9fdd79d4

- docker-compose.yml
[start_time:Thu, 29 Jul 2021 12:24:41 GMT, release_branch:master, prefix:, end_time:Thu, 29 Jul 2021 17:23:10 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-cf3e6139, build_duration_seconds:17909]
> [automation] update elastic stack version for testing 8.0.0-cf3e6139

- docker-compose.yml
[start_time:Thu, 29 Jul 2021 12:14:57 GMT, release_branch:7.14, prefix:, end_time:Thu, 29 Jul 2021 17:35:26 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-56a8365b, build_duration_seconds:19229]
> [automation] update elastic stack version for testing 7.14.0-56a8365b

- sourcemap/es_store.go
- sourcemap/fleet_store.go
- sourcemap/fleet_store_test.go
- sourcemap/store.go
These changes support fetching sourcemaps from one of many fleet servers. It sends the request to all the fleet servers in parallel and returns the first successful response.
I've made some adjustments to the `fleetStore` struct to keep a map of the `(service.name, service.version, bundle.filepath)` combinations to the `sourcemap.url`. I've also added a separate slice to store the list of base fleet server addresses, which represent the configured protocol with the host and port of a given fleet server.
The full url is constructed when the sourcemap is fetched using a base fleet server url and the sourcemap url (path).
Closes #5514 
Taking the test plan from https://github.com/elastic/apm-server/pull/5410:
Run elasticsearch and multiple elastic-agents in fleet mode. 2 or 3 should be …
> [sourcemaps] Support multiple fleet addresses when requesting a sourcemap

- .ci/scripts/update-beats.sh
When running `make update-beats`, it is possible for fields to change. When this happens, we'll need to `git add` the following additional files:
- include/fields.go
- x-pack/apm-server/fields.go
- docs/fields.asciidoc
See https://github.com/elastic/apm-server/pull/5834
N/A
None
> update-beats: git add fields updates

- sourcemap/fleet_store_test.go
Fix data race in TestFleetFetch: as there are two servers, one may update hasAuth concurrently with the test checking the value.
Change the way the auth header is checked to be similar to how the header would be checked in a real fleet-server, and respond with 401 if the auth header is invalid. Since we wait for a valid response, we can be sure the header has been checked.
`go test -v -race -count=50 -failfast -run TestFleetFetch`
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/PR-5840/2/tests/
> sourcemap: fix data race in test

- docker-compose.yml
[start_time:Sun, 1 Aug 2021 12:24:00 GMT, release_branch:7.14, prefix:, end_time:Sun, 1 Aug 2021 18:03:20 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-8d3ee29d, build_duration_seconds:20360]
> [automation] update elastic stack version for testing 7.14.0-8d3ee29d

- go.mod
- go.sum
- tools.go
- tools/go.mod
- tools/go.sum
Apparently these ones are required by CI to be in the top-level go.mod file. I'll see if we can fix that, but for now here we go.
Broken build: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/PR-5848/1/pipeline/185/
> Move some tools back to top-level go.mod

- changelogs/6.8.asciidoc
- changelogs/7.0.asciidoc
- docs: add 6.8.18 release notes (#5861)
> [7.14] docs: add 6.8.18 release notes (#5861)

- sourcemap/fleet_store_test.go
- sourcemap: fix data race in test (#5842)
> [7.x] sourcemap: fix data race in test (#5842)

- changelogs/6.8.asciidoc
- changelogs/7.0.asciidoc
- docs: add 6.8.18 release notes (#5861)
> [7.x] docs: add 6.8.18 release notes (#5861)

- docs/guide/opentelemetry-elastic.asciidoc
- Added AWS Lambda Node.js instructions (#5780)
> [7.14] Added AWS Lambda Node.js instructions (#5780)

- docs/guide/opentelemetry-elastic.asciidoc
- Added AWS Lambda Node.js instructions (#5780)
> [7.x] Added AWS Lambda Node.js instructions (#5780)

- CHANGELOG.asciidoc
- changelogs/7.13.asciidoc
- changelogs/7.14.asciidoc
- changelogs/8.0.asciidoc
- docs/breaking-changes.asciidoc
- docs/guide/apm-breaking-changes.asciidoc
- docs/release-notes.asciidoc
This PR moves certain release notes from `8.0.0-alpha1` to `7.14.0`.
@axw I think I messed up in https://github.com/elastic/apm-server/pull/5802. 
This PR _should_ update [stack-docs](https://github.com/elastic/stack-docs/tree/master/docs/en/install-upgrade) when backported to 7.14.
> docs: add 7.14 release notes

- docker-compose.yml
[start_time:Mon, 2 Aug 2021 05:15:54 GMT, release_branch:7.14, prefix:, end_time:Mon, 2 Aug 2021 10:52:51 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-28f3035b, build_duration_seconds:20217]
> [automation] update elastic stack version for testing 7.14.0-28f3035b

- docker-compose.yml
[start_time:Mon, 2 Aug 2021 00:15:51 GMT, release_branch:master, prefix:, end_time:Mon, 2 Aug 2021 05:40:31 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-93ecf1d0, build_duration_seconds:19480]
> [automation] update elastic stack version for testing 8.0.0-93ecf1d0

- docs/apm-package/data-streams.asciidoc
This PR updates the data stream naming scheme for the APM integration. Closes https://github.com/elastic/observability-docs/issues/842.
The readme file does not need to be updated, but additional changes in the observability-docs repo are necessary (https://github.com/elastic/observability-docs/pull/946).
> docs: update data streams naming

- docs/apm-package/data-streams.asciidoc
- docs: update data streams naming (#5859)
> [7.x] docs: update data streams naming (#5859)

- docs/apm-package/data-streams.asciidoc
- docs: update data streams naming (#5859)
> [7.14] docs: update data streams naming (#5859)

- docs/common-problems.asciidoc
- docs/getting-started-apm-server.asciidoc
- docs/guide/agent-server-compatibility.asciidoc
- docs/guide/apm-data-model.asciidoc
- docs/guide/apm-doc-directory.asciidoc
- docs/guide/opentracing.asciidoc
- docs/guide/troubleshooting.asciidoc
- docs/secure-communication-agents.asciidoc
- docs/tab-widgets/configure-agent.asciidoc
- docs/tab-widgets/distributed-trace-receive-widget.asciidoc
- docs/tab-widgets/distributed-trace-receive.asciidoc
- docs/tab-widgets/distributed-trace-send-widget.asciidoc
- docs/tab-widgets/distributed-trace-send.asciidoc
- docs/tab-widgets/install-agents-widget.asciidoc
- docs/tab-widgets/install-agents.asciidoc
- docs/troubleshooting.asciidoc
- docs/version.asciidoc
- docs: add iOS agent links (#5634)
> [7.14] docs: add iOS agent links (#5634)

- docs/transaction-metrics.asciidoc
Update apm-server.aggregation.transactions.* docs:
- `enabled` defaults to true since 7.13
- `max_groups` defaults to 10000 since 7.10
- `rum.user_agent.lru_size` was dropped (I forget when)
Also change some of the wording around the purpose of these metrics:
they are primarily about reducing storage costs, not improving query
performance. The latter is expected to eventually be the case, but
has not yet been proven and is not hte primary goal.
> docs: update transaction metrics

- apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
- apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/apm_error_grouping_name.json
- apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
- apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/apm_error_grouping_name.json
- apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
- apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/apm_error_grouping_name.json
- apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
- apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/apm_error_grouping_name.json
- apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
- apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/apm_error_grouping_name.json
- changelogs/head.asciidoc
- ingest/pipeline/definition.json
- ingest/pipeline/definition.yml
Fix compatibility with older Elasticsearch versions:
- don't use set.copy_from, it's not supported before 7.11
- don't use convert, converting IPs was only added in 7.13
Run apm-server with 7.0.0
Closes https://github.com/elastic/apm-server/issues/5786
Closes https://github.com/elastic/apm-server/issues/5807
> ingest/pipeline: fix compat with old Elasticsearch

- docker-compose.yml
[start_time:Tue, 3 Aug 2021 05:14:18 GMT, release_branch:7.14, prefix:, end_time:Tue, 3 Aug 2021 10:32:43 GMT, manifest_version:2.0.0, version:7.14.0-SNAPSHOT, branch:7.14, build_id:7.14.0-1738ccc6, build_duration_seconds:19105]
> [automation] update elastic stack version for testing 7.14.0-1738ccc6

- beater/beater.go
- beater/server_test.go
Use reload.ReloadableList, rather than cfgfile.NewRunnerList.
cfgfile.NewRunnerList forces a restart every time the config
changes, which we want to move away from.
https://github.com/elastic/apm-server/issues/5039
> beater: implement reload.ReloadableList directly

- docker-compose.yml
[start_time:Tue, 3 Aug 2021 00:26:44 GMT, release_branch:master, prefix:, end_time:Tue, 3 Aug 2021 05:39:32 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-0c340354, build_duration_seconds:18768]
> [automation] update elastic stack version for testing 8.0.0-0c340354

- docker-compose.yml
[start_time:Wed, 4 Aug 2021 12:24:23 GMT, release_branch:master, prefix:, end_time:Wed, 4 Aug 2021 17:50:56 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-4c35f443, build_duration_seconds:19593]
> [automation] update elastic stack version for testing 8.0.0-4c35f443

- docker-compose.yml
[start_time:Thu, 5 Aug 2021 12:25:30 GMT, release_branch:master, prefix:, end_time:Thu, 5 Aug 2021 17:45:02 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-e8455215, build_duration_seconds:19172]
> [automation] update elastic stack version for testing 8.0.0-e8455215

- docker-compose.yml
[start_time:Thu, 5 Aug 2021 12:15:13 GMT, release_branch:7.14, prefix:, end_time:Thu, 5 Aug 2021 17:29:19 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-22366df8, build_duration_seconds:18846]
> [automation] update elastic stack version for testing 7.14.1-22366df8

- changelogs/head.asciidoc
- x-pack/apm-server/aggregation/spanmetrics/aggregator.go
- x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
Update spanmetrics to take into account composite spans, using the composite span count and duration. Like non-composite spans, these are also multiplied by the "representative count", i.e. the inverse sampling ratio.
1. Send some composite spans to the server
2. Check that the span metrics have the expected count and duration sum
Closes https://github.com/elastic/apm-server/issues/5595
> aggregation/spanmetrics: handle composite spans

- docs/common-problems.asciidoc
- docs/getting-started-apm-server.asciidoc
- docs/guide/agent-server-compatibility.asciidoc
- docs/guide/apm-data-model.asciidoc
- docs/guide/apm-doc-directory.asciidoc
- docs/guide/opentracing.asciidoc
- docs/guide/troubleshooting.asciidoc
- docs/secure-communication-agents.asciidoc
- docs/tab-widgets/configure-agent.asciidoc
- docs/tab-widgets/distributed-trace-receive-widget.asciidoc
- docs/tab-widgets/distributed-trace-receive.asciidoc
- docs/tab-widgets/distributed-trace-send-widget.asciidoc
- docs/tab-widgets/distributed-trace-send.asciidoc
- docs/tab-widgets/install-agents-widget.asciidoc
- docs/tab-widgets/install-agents.asciidoc
- docs/troubleshooting.asciidoc
- docs/version.asciidoc
- docs: add iOS agent links (#5634)
> [7.x] docs: add iOS agent links (#5634)

- docker-compose.yml
[start_time:Sun, 8 Aug 2021 12:14:46 GMT, release_branch:7.14, prefix:, end_time:Sun, 8 Aug 2021 17:43:13 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-8dd23e93, build_duration_seconds:19707]
> [automation] update elastic stack version for testing 7.14.1-8dd23e93

- docker-compose.yml
[start_time:Mon, 9 Aug 2021 05:16:05 GMT, release_branch:7.14, prefix:, end_time:Mon, 9 Aug 2021 10:33:32 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-899a999b, build_duration_seconds:19047]
> [automation] update elastic stack version for testing 7.14.1-899a999b

- x-pack/apm-server/sampling/pubsub/pubsub_test.go
Simplify the pubsub tests by implementing a mock Elasticsearch HTTP server. This replaces the circuitous (and error prone) method of having an HTTP server that sends requests to a channel to be handled synchronously. Now the requests are handled directly in the mock server, with behaviour injected by the test through callbacks.
Fixes `TestSubscribeSampledTraceIDs`, which has been intermittently timing out in CI.
Closes https://github.com/elastic/apm-server/issues/5708
> sampling/pubsub: fix flaky test

- beater/api/mux.go
- beater/api/mux_config_agent_test.go
- beater/api/mux_test.go
- beater/http.go
- beater/server.go
- beater/tracing.go
- changelogs/head.asciidoc
- systemtest/agentconfig_test.go
If Fleet-managed, apm-server should not return 403 Forbidden just because there's no agent config. Add the "kill switch" middleware only if the server is _not_ Fleet-managed, and has no Kibana config. Extend the agent config system test to cover Fleet.
There is some light refactoring to inject a common `auth.Authenticator` and `model.BatchProcessor` into both the HTTP mux and gRPC services.
1. Create a fresh cluster, add APM integration to an Elastic Agent
2. Query agent config. It should not return 403 Forbidden.
None.
> beater/api/mux: fix Fleet agent config enablement

- docker-compose.yml
[start_time:Tue, 10 Aug 2021 12:14:34 GMT, release_branch:7.14, prefix:, end_time:Tue, 10 Aug 2021 17:41:24 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-a5e22cba, build_duration_seconds:19610]
> [automation] update elastic stack version for testing 7.14.1-a5e22cba

- docker-compose.yml
[start_time:Tue, 10 Aug 2021 05:24:14 GMT, release_branch:7.x, prefix:, end_time:Tue, 10 Aug 2021 10:42:03 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.x, build_id:7.15.0-83f2fe8a, build_duration_seconds:19069]
> [automation] update elastic stack version for testing 7.15.0-83f2fe8a

- docker-compose.yml
[start_time:Wed, 11 Aug 2021 12:23:59 GMT, release_branch:7.14, prefix:, end_time:Wed, 11 Aug 2021 20:48:54 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-5a4d121c, build_duration_seconds:30295]
> [automation] update elastic stack version for testing 7.14.1-5a4d121c

- beater/beater.go
- beater/config/data_streams.go
- beater/server_test.go
- beater/waitintegration.go
- docs/configuration-process.asciidoc
Extend `data_streams.wait_for_integration` to use either Kibana or Elasticsearch queries, depending on what is configured.
If Kibana config is defined, and Kibana can be successfully queried, then it will be used. Otherwise if the Elasticsearch output is configured, Elasticsearch queries will be made to check the presence of index templates which imply the integration has been installed.
See https://github.com/elastic/apm-server/pull/5928; run with and without `apm-server.kibana` config.
#5914
> Wait for integration using Elasticsearch queries

- docker-compose.yml
[start_time:Thu, 12 Aug 2021 12:13:53 GMT, release_branch:7.14, prefix:, end_time:Thu, 12 Aug 2021 17:35:37 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-3af02427, build_duration_seconds:19304]
> [automation] update elastic stack version for testing 7.14.1-3af02427

- docker-compose.yml
[start_time:Thu, 12 Aug 2021 05:15:12 GMT, release_branch:7.x, prefix:, end_time:Thu, 12 Aug 2021 10:46:24 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.x, build_id:7.15.0-ba42231a, build_duration_seconds:19872]
> [automation] update elastic stack version for testing 7.15.0-ba42231a

- docs/apm-package/apm-integration.asciidoc
- docs/sourcemap-api.asciidoc
- docs/sourcemaps.asciidoc
This PR makes it clear that users running the APM integration need to use the Kibana endpoint and not the APM Server endpoint to upload source maps.
It also removes an out of date reference to the current version of the APM integration.
> docs: add source map upload notes

- docs/apm-package/apm-integration.asciidoc
- docs/sourcemap-api.asciidoc
- docs/sourcemaps.asciidoc
- docs: add sourcemap upload notes (#5935)
> [7.14] docs: add sourcemap upload notes (#5935)

- docs/apm-package/apm-integration.asciidoc
- docs/sourcemap-api.asciidoc
- docs/sourcemaps.asciidoc
- docs: add sourcemap upload notes (#5935)
> [7.x] docs: add sourcemap upload notes (#5935)

- docker-compose.yml
[start_time:Fri, 13 Aug 2021 12:14:55 GMT, release_branch:7.14, prefix:, end_time:Fri, 13 Aug 2021 17:40:22 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-c6219279, build_duration_seconds:19527]
> [automation] update elastic stack version for testing 7.14.1-c6219279

- docker-compose.yml
[start_time:Fri, 13 Aug 2021 21:29:36 GMT, release_branch:master, prefix:, end_time:Sat, 14 Aug 2021 03:05:43 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-2e89a578, build_duration_seconds:20167]
> [automation] update elastic stack version for testing 8.0.0-2e89a578

- apmpackage/apm/data_stream/app_metrics/fields/base-fields.yml
- apmpackage/apm/data_stream/app_metrics/fields/ecs.yml
- apmpackage/apm/data_stream/app_metrics/fields/fields.yml
- apmpackage/apm/data_stream/app_metrics/manifest.yml
- apmpackage/apm/data_stream/error_logs/fields/base-fields.yml
- apmpackage/apm/data_stream/error_logs/fields/ecs.yml
- apmpackage/apm/data_stream/error_logs/fields/fields.yml
- apmpackage/apm/data_stream/error_logs/manifest.yml
- apmpackage/apm/data_stream/internal_metrics/fields/base-fields.yml
- apmpackage/apm/data_stream/internal_metrics/fields/ecs.yml
- apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
- apmpackage/apm/data_stream/internal_metrics/manifest.yml
- apmpackage/apm/data_stream/profile_metrics/fields/base-fields.yml
- apmpackage/apm/data_stream/profile_metrics/fields/ecs.yml
- apmpackage/apm/data_stream/profile_metrics/fields/fields.yml
- apmpackage/apm/data_stream/profile_metrics/manifest.yml
- apmpackage/apm/data_stream/sampled_traces/fields/base-fields.yml
- apmpackage/apm/data_stream/sampled_traces/manifest.yml
- apmpackage/apm/data_stream/traces/fields/base-fields.yml
- apmpackage/apm/data_stream/traces/fields/ecs.yml
- apmpackage/apm/data_stream/traces/fields/fields.yml
- apmpackage/apm/data_stream/traces/manifest.yml
- apmpackage/apm/docs/README.md
- apmpackage/cmd/gen-package/field.go
- apmpackage/cmd/gen-package/gendocs.go
- apmpackage/cmd/gen-package/genfields.go
- changelogs/head.asciidoc
Fix integration package index template mappings by copying the full field hierarchy to the integration package, instead of just flattened leaf fields. Copying only leaf fields means we miss inherited group properties such as `dynamic`.
- set a default `dynamic` property for each data stream mapping
- add `ecs.version` to base fields
1. Install the integration
2. Run apm-server with data streams (e.g. `-E apm-server.data_streams.enabled=true`)
3. Send some HTTP transactions with request headers, check that APM Server indexes them successfully
4. Check that the request headers are not indexed
https://github.com/elastic/apm-server/issues/5707
> apmpackage: copy full field hierarchy

- docker-compose.yml
[start_time:Tue, 17 Aug 2021 12:14:25 GMT, release_branch:7.14, prefix:, end_time:Tue, 17 Aug 2021 18:00:45 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-904a8260, build_duration_seconds:20780]
> [automation] update elastic stack version for testing 7.14.1-904a8260

- docker-compose.yml
[start_time:Tue, 17 Aug 2021 12:14:32 GMT, release_branch:7.x, prefix:, end_time:Tue, 17 Aug 2021 17:52:06 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.x, build_id:7.15.0-4b8a78a4, build_duration_seconds:20254]
> [automation] update elastic stack version for testing 7.15.0-4b8a78a4

- docker-compose.yml
[start_time:Tue, 17 Aug 2021 12:18:33 GMT, release_branch:master, prefix:, end_time:Tue, 17 Aug 2021 19:52:36 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-7e122dd9, build_duration_seconds:27243]
> [automation] update elastic stack version for testing 8.0.0-7e122dd9

- docker-compose.yml
[start_time:Wed, 18 Aug 2021 12:15:22 GMT, release_branch:7.14, prefix:, end_time:Wed, 18 Aug 2021 17:41:57 GMT, manifest_version:2.0.0, version:7.14.1-SNAPSHOT, branch:7.14, build_id:7.14.1-a6cb01c7, build_duration_seconds:19595]
> [automation] update elastic stack version for testing 7.14.1-a6cb01c7

- docker-compose.yml
[start_time:Wed, 18 Aug 2021 00:16:38 GMT, release_branch:master, prefix:, end_time:Wed, 18 Aug 2021 06:17:23 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-fa246295, build_duration_seconds:21645]
> [automation] update elastic stack version for testing 8.0.0-fa246295

- docker-compose.yml
[start_time:Thu, 19 Aug 2021 12:22:30 GMT, release_branch:master, prefix:, end_time:Thu, 19 Aug 2021 18:56:12 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-8ac8c039, build_duration_seconds:23622]
> [automation] update elastic stack version for testing 8.0.0-8ac8c039

- docker-compose.yml
[start_time:Thu, 19 Aug 2021 15:10:49 GMT, release_branch:7.x, prefix:, end_time:Fri, 20 Aug 2021 01:49:26 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-ab6de48d, build_duration_seconds:38317]
> [automation] update elastic stack version for testing 7.16.0-ab6de48d

- docker-compose.yml
[start_time:Thu, 19 Aug 2021 17:21:47 GMT, release_branch:7.15, prefix:, end_time:Thu, 19 Aug 2021 23:10:40 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-e06b4078, build_duration_seconds:20933]
> [automation] update elastic stack version for testing 7.15.0-e06b4078

- docker-compose.yml
[start_time:Sun, 22 Aug 2021 05:23:39 GMT, release_branch:7.x, prefix:, end_time:Sun, 22 Aug 2021 11:29:31 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-2d73c7e8, build_duration_seconds:21952]
> [automation] update elastic stack version for testing 7.16.0-2d73c7e8

- docker-compose.yml
[start_time:Sun, 22 Aug 2021 17:24:20 GMT, release_branch:7.15, prefix:, end_time:Sun, 22 Aug 2021 23:11:16 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-a7c04a10, build_duration_seconds:20816]
> [automation] update elastic stack version for testing 7.15.0-a7c04a10

- docker-compose.yml
[start_time:Fri, 20 Aug 2021 00:17:43 GMT, release_branch:master, prefix:, end_time:Fri, 20 Aug 2021 06:36:07 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-56a61c29, build_duration_seconds:22704]
> [automation] update elastic stack version for testing 8.0.0-56a61c29

- .ci/check-packages.groovy
It can't override the environment variable defined in the environment `{}` block, therefore let's use a different approach and add more debug traces.
In the CI
Supersedes https://github.com/elastic/apm-server/pull/6009
> [CI]: use setEnvVar instead of global env variable

- docs/configure-kibana-endpoint.asciidoc
Closes https://github.com/elastic/apm-server/issues/3479. This issue was mostly resolved in https://github.com/elastic/apm-server/pull/3799, which added privilege docs [here](https://www.elastic.co/guide/en/apm/server/current/privileges-agent-central-config.html), but as stated in elastic/apm-server#3479, some kind of docs (a link in this case) in [Configure the Kibana endpoint](https://github.com/elastic/apm-server/pull/3799) seems helpful. This PR adds that link.
> docs: link to APM Server central config privileges

- docs/configure-kibana-endpoint.asciidoc
- docs: link to req’d privs (#5976)
> [7.14] docs: link to req’d privs (#5976)

- docs/configure-kibana-endpoint.asciidoc
- docs: link to req’d privs (#5976)
> [7.x] docs: link to req’d privs (#5976)

- docs/configuration-rum.asciidoc
- docs: add rum response_headers (#5954)
> [7.x] docs: add rum response_headers (#5954)

- docs/configuration-rum.asciidoc
- docs: add rum response_headers (#5954)
> [7.14] docs: add rum response_headers (#5954)

- docs/configuration-rum.asciidoc
- docs: add rum response_headers (#5954)
> [7.15] docs: add rum response_headers (#5954)

- model/apmevent.go
- model/apmevent_test.go
- model/error.go
- model/modeldecoder/rumv3/decoder.go
- model/modeldecoder/rumv3/metadata_test.go
- model/modeldecoder/rumv3/transaction_test.go
- model/modeldecoder/v2/decoder.go
- model/modeldecoder/v2/metadata_test.go
- model/span.go
- model/span_test.go
- model/trace.go
- model/transaction.go
- processor/otel/exceptions_test.go
- processor/otel/metadata_test.go
- processor/otel/traces.go
- processor/otel/traces_test.go
- x-pack/apm-server/sampling/eventstorage/sharded_bench_test.go
- x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
- x-pack/apm-server/sampling/eventstorage/storage_test.go
- x-pack/apm-server/sampling/groups.go
- x-pack/apm-server/sampling/groups_test.go
- x-pack/apm-server/sampling/processor.go
- x-pack/apm-server/sampling/processor_bench_test.go
- x-pack/apm-server/sampling/processor_test.go
Introduce type `model.Trace` and field `model.APMEvent.Trace`, replacing `{Error,Span,Transaction}.TraceID`. This will make it more straightforward to include `trace.id` in log events, for https://github.com/elastic/apm-server/issues/4715.
https://github.com/elastic/apm-server/issues/4410
https://github.com/elastic/apm-server/issues/4120
https://github.com/elastic/apm-server/issues/4715
> Introduce model.Trace

- docker-compose.yml
[start_time:Mon, 23 Aug 2021 05:15:50 GMT, release_branch:7.x, prefix:, end_time:Mon, 23 Aug 2021 11:11:54 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-c3b80e7b, build_duration_seconds:21364]
> [automation] update elastic stack version for testing 7.16.0-c3b80e7b

- docker-compose.yml
[start_time:Tue, 24 Aug 2021 16:40:40 GMT, release_branch:7.x, prefix:, end_time:Tue, 24 Aug 2021 23:00:32 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-13c65289, build_duration_seconds:22792]
> [automation] update elastic stack version for testing 7.16.0-13c65289

- docker-compose.yml
[start_time:Sun, 29 Aug 2021 17:26:06 GMT, release_branch:7.15, prefix:, end_time:Sun, 29 Aug 2021 23:10:32 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-0211404a, build_duration_seconds:20666]
> [automation] update elastic stack version for testing 7.15.0-0211404a

- docker-compose.yml
[start_time:Sun, 29 Aug 2021 12:25:05 GMT, release_branch:master, prefix:, end_time:Sun, 29 Aug 2021 18:40:11 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-1efff7fc, build_duration_seconds:22506]
> [automation] update elastic stack version for testing 8.0.0-1efff7fc

- docker-compose.yml
[start_time:Sun, 29 Aug 2021 05:24:25 GMT, release_branch:7.x, prefix:, end_time:Sun, 29 Aug 2021 11:46:42 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-d17acf1e, build_duration_seconds:22937]
> [automation] update elastic stack version for testing 7.16.0-d17acf1e

- docker-compose.yml
[start_time:Mon, 30 Aug 2021 12:16:13 GMT, release_branch:master, prefix:, end_time:Mon, 30 Aug 2021 18:16:11 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-78724554, build_duration_seconds:21598]
> [automation] update elastic stack version for testing 8.0.0-78724554

- docker-compose.yml
[start_time:Mon, 30 Aug 2021 05:19:03 GMT, release_branch:7.x, prefix:, end_time:Mon, 30 Aug 2021 11:58:36 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-978c8c33, build_duration_seconds:23973]
> [automation] update elastic stack version for testing 7.16.0-978c8c33

- docker-compose.yml
[start_time:Mon, 30 Aug 2021 17:25:41 GMT, release_branch:7.15, prefix:, end_time:Tue, 31 Aug 2021 00:03:23 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-1649f9c1, build_duration_seconds:23862]
> [automation] update elastic stack version for testing 7.15.0-1649f9c1

- changelogs/7.14.asciidoc
- docs: add 7.14.1 release notes (#6083)
> [7.15] docs: add 7.14.1 release notes (#6083)

- changelogs/7.14.asciidoc
- docs: add 7.14.1 release notes (#6083)
> [7.x] docs: add 7.14.1 release notes (#6083)

- docker-compose.yml
[start_time:Tue, 31 Aug 2021 05:24:19 GMT, release_branch:7.x, prefix:, end_time:Tue, 31 Aug 2021 12:00:51 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-8a18fe34, build_duration_seconds:23792]
> [automation] update elastic stack version for testing 7.16.0-8a18fe34

- docker-compose.yml
[start_time:Tue, 31 Aug 2021 00:21:10 GMT, release_branch:7.15, prefix:, end_time:Tue, 31 Aug 2021 06:21:23 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-caca3588, build_duration_seconds:21613]
> [automation] update elastic stack version for testing 7.15.0-caca3588

- changelogs/7.14.asciidoc
- docs: add 7.14.1 release notes (#6083)
> [7.14] docs: add 7.14.1 release notes (#6083)

- magefile.go
Fix the Package target. I accidentally removed the dependency on `beats/dev-tools/mage.Package` in https://github.com/elastic/apm-server/pull/6101/files#diff-520109d035a196d29d0a86e9c4e6c98e98abf056141b84df68c0d48167b87b25L178
> magefile: fix Package target

- apmpackage/apm/changelog.yml
- apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/data_stream/internal_metrics/manifest.yml
- apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.json
- apmpackage/apm/manifest.yml
- changelogs/head.asciidoc
Sort internal metrics by @timestamp, to speed up time range queries.
1. Install the package
2. Check that `metrics-apm.internal@settings` defines `index.sort` settings
https://github.com/elastic/apm-server/issues/5505
> apmpackage: sort internal metrics data stream

- docker-compose.yml
[start_time:Tue, 7 Sep 2021 00:24:48 GMT, release_branch:7.15, prefix:, end_time:Tue, 7 Sep 2021 06:30:43 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-b8b8307a, build_duration_seconds:21955]
> [automation] update elastic stack version for testing 7.15.0-b8b8307a

- docker-compose.yml
[start_time:Sat, 4 Sep 2021 05:24:03 GMT, release_branch:7.x, prefix:, end_time:Sat, 4 Sep 2021 11:48:38 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-a96d8aa5, build_duration_seconds:23075]
> [automation] update elastic stack version for testing 7.16.0-a96d8aa5

- changelogs/head.asciidoc
- processor/otel/traces.go
Deprecate interpreting `service.version` as a span tag. We'll remove this in 8.0, and from then on instrumentation will have to use tracer tags (Jaeger) or resource attributes (OTel).
https://github.com/elastic/apm-server/pull/4061 added support for setting `service.version` via Jaeger span tags. In retrospect, we should not have done this; service version should be coming through as a tracer tag, as it applies to the service as a whole and not individual spans.
N/A
https://github.com/elastic/apm-server/pull/6114#issuecomment-913274016
> processor/otel: deprecate `service.version` span tag

- apmpackage/apm/manifest.yml
Update the integration package's release status to GA. Update the required Kibana version while we're at it.
1. Navigate to the integrations UI in Kibana, install the APM integration
2. Check that it does not have an experimental badge like in the following screenshot
https://github.com/elastic/apm-server/issues/4636
> apmpackage: mark package as GA

- beater/api/mux.go
- beater/api/mux_test.go
- beater/api/root/handler.go
- beater/api/root/handler_test.go
- beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
- beater/beater.go
- beater/beater_test.go
- beater/checkintegration.go
- beater/config/config.go
- beater/config/config_test.go
- beater/server.go
- beater/server_test.go
- beater/tracing.go
- beater/waitready.go
- changelogs/head.asciidoc
- elasticsearch/backoff_test.go
- elasticsearch/client.go
- elasticsearch/config.go
- elasticsearch/license.go
- sourcemap/es_store.go
- sourcemap/es_store_test.go
- sourcemap/processor_test.go
- systemtest/apmservertest/server.go
- systemtest/sampling_test.go
- x-pack/apm-server/main.go
- x-pack/apm-server/main_test.go
- x-pack/apm-server/sampling/pubsub/pubsubtest/client.go
When configured for standalone+data streams, we wait for the integration to be installed. This is now checked asynchronously, blocking Elasticsearch client requests rather than the server starting up. This allows events to be received, processed, and enqueued, but not indexed until the integration is installed. The tail-based sampling license check has been moved to this new wait loop, and uses the go-elasticsearch client to fetch the license instead of libbeat.
We add a "NewElasticsearchClient" function to beater.ServerParams, which should be used to construct `elasticsearch.Clients` wherever the client may be used to perform indexing operations. The elasticsearch package API has been simplified, and some unit tests removed as a result.
Package beater tests now have the option of …
> Add "waitReady" preconditions for Elasticsearch clients

- docker-compose.yml
[start_time:Wed, 8 Sep 2021 00:26:05 GMT, release_branch:7.15, prefix:, end_time:Wed, 8 Sep 2021 07:05:07 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-f15c4154, build_duration_seconds:23942]
> [automation] update elastic stack version for testing 7.15.0-f15c4154

- docker-compose.yml
[start_time:Wed, 8 Sep 2021 05:16:11 GMT, release_branch:7.x, prefix:, end_time:Wed, 8 Sep 2021 11:43:49 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-468522bc, build_duration_seconds:23258]
> [automation] update elastic stack version for testing 7.16.0-468522bc

- docker-compose.yml
[start_time:Thu, 9 Sep 2021 17:25:55 GMT, release_branch:7.15, prefix:, end_time:Thu, 9 Sep 2021 23:54:49 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-4efca5cc, build_duration_seconds:23334]
> [automation] update elastic stack version for testing 7.15.0-4efca5cc

- beater/beater.go
- changelogs/head.asciidoc
- cmd/root.go
- docs/configuration-process.asciidoc
- docs/configuring-ingest.asciidoc
- docs/getting-started-apm-server.asciidoc
- docs/ilm-reference.asciidoc
- docs/ilm.asciidoc
- idxmgmt/manager.go
- idxmgmt/manager_test.go
- idxmgmt/supporter_factory.go
- idxmgmt/supporter_factory_test.go
Log warnings when index management config is explicitly configured in standalone mode, and print a warning message when users run `apm-server setup`.
Also, remove old check for `setup.dashboards` config in beater.
1. Run `apm-server setup`, should print out a warning message.
2. Run `apm-server`, should not print any warnings (no custom config)
3. Run `apm-server -E apm-server.ilm.enabled=true`, should log a warning about the config being deprecated
4. Run `apm-server -E apm-server.data_streams.enabled=true`, should not log any warnings
Closes https://github.com/elastic/apm-server/issues/5914
> Add deprecation warnings about ES setup

- docker-compose.yml
[start_time:Sun, 12 Sep 2021 12:25:06 GMT, release_branch:master, prefix:, end_time:Sun, 12 Sep 2021 18:12:00 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-6b488890, build_duration_seconds:20814]
> [automation] update elastic stack version for testing 8.0.0-6b488890

- docker-compose.yml
[start_time:Sun, 12 Sep 2021 05:15:44 GMT, release_branch:7.x, prefix:, end_time:Sun, 12 Sep 2021 11:42:48 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-fbd5fab2, build_duration_seconds:23224]
> [automation] update elastic stack version for testing 7.16.0-fbd5fab2

- docker-compose.yml
[start_time:Sun, 12 Sep 2021 00:14:15 GMT, release_branch:7.15, prefix:, end_time:Sun, 12 Sep 2021 06:29:01 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-a59055d8, build_duration_seconds:22486]
> [automation] update elastic stack version for testing 7.15.0-a59055d8

- docs/jaeger-reference.asciidoc
- docs/jaeger-support.asciidoc
- docs/transaction-metrics.asciidoc
Remove the experimental status from Jaeger and transaction metrics features.
> docs: promote jaeger & transaction metrics to GA

- docker-compose.yml
[start_time:Mon, 13 Sep 2021 17:26:11 GMT, release_branch:7.15, prefix:, end_time:Mon, 13 Sep 2021 23:23:34 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-d48cd6f3, build_duration_seconds:21443]
> [automation] update elastic stack version for testing 7.15.0-d48cd6f3

- docker-compose.yml
[start_time:Mon, 13 Sep 2021 05:14:31 GMT, release_branch:7.x, prefix:, end_time:Mon, 13 Sep 2021 11:50:59 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-f4fa0a64, build_duration_seconds:23788]
> [automation] update elastic stack version for testing 7.16.0-f4fa0a64

- model/error.go
- model/error_test.go
- model/modeldecoder/rumv3/error_test.go
- model/modeldecoder/v2/error_test.go
Remove the Parent field from model.Exception, and set it only during transformation to beats events. This field exists purely for the benefit of reconstructing the hierarchy in Kibana, so it does not need to be in the server's in-memory data model.
N/A
#4120
> model: remove Exception.Parent

- docs/configuration-anonymous.asciidoc
- docs/configuration-rum.asciidoc
document how `client.ip` is derived for ratelimiting anonymous events
~~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~~
non-functional change
closes #6153
> document how ratelimit client.ip is derived

- docker-compose.yml
[start_time:Tue, 14 Sep 2021 05:24:03 GMT, release_branch:7.x, prefix:, end_time:Tue, 14 Sep 2021 11:48:41 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-b40a7e80, build_duration_seconds:23078]
> [automation] update elastic stack version for testing 7.16.0-b40a7e80

- docker-compose.yml
[start_time:Tue, 14 Sep 2021 00:25:37 GMT, release_branch:7.15, prefix:, end_time:Tue, 14 Sep 2021 06:05:15 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-4d52e36a, build_duration_seconds:20378]
> [automation] update elastic stack version for testing 7.15.0-4d52e36a

- docs/guide/opentelemetry-elastic.asciidoc
Backport OTel limitation docs changes from https://github.com/elastic/apm-server/pull/6122 to 7.15, excluding those related to span events
> docs: update OTel limitations

- docker-compose.yml
[start_time:Wed, 15 Sep 2021 00:17:37 GMT, release_branch:master, prefix:, end_time:Wed, 15 Sep 2021 06:21:00 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-da75ec54, build_duration_seconds:21803]
> [automation] update elastic stack version for testing 8.0.0-da75ec54

- docker-compose.yml
[start_time:Wed, 15 Sep 2021 05:25:24 GMT, release_branch:7.x, prefix:, end_time:Wed, 15 Sep 2021 11:39:10 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-63cdb007, build_duration_seconds:22426]
> [automation] update elastic stack version for testing 7.16.0-63cdb007

- docker-compose.yml
[start_time:Wed, 15 Sep 2021 17:21:52 GMT, release_branch:7.15, prefix:, end_time:Wed, 15 Sep 2021 23:16:49 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-1bab4292, build_duration_seconds:21297]
> [automation] update elastic stack version for testing 7.15.0-1bab4292

- docker-compose.yml
[start_time:Thu, 16 Sep 2021 17:17:01 GMT, release_branch:7.15, prefix:, end_time:Thu, 16 Sep 2021 22:55:35 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-353cd7d4, build_duration_seconds:20314]
> [automation] update elastic stack version for testing 7.15.0-353cd7d4

- docker-compose.yml
[start_time:Sun, 19 Sep 2021 17:25:11 GMT, release_branch:7.15, prefix:, end_time:Sun, 19 Sep 2021 23:15:42 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-bc82566e, build_duration_seconds:21031]
> [automation] update elastic stack version for testing 7.15.0-bc82566e

- .mergify.yml
Notify PR contributors about the backport policy.
This policy will notify what are the different backport options and tag the PR with the `backport-skip`.
We can think about enforcing this rule to do not allow merges but for the time being, what do you think?
See https://github.com/elastic/apm-pipeline-library/pull/1281#issuecomment-922766344 and https://github.com/elastic/apm-pipeline-library/pull/1281#event-5327050151
> [mergify] add backport policy and default label

- .mergify.yml
The backport policy should only apply for PRs targeting the master branch.
> [mergify] backport policy for the master branch only

- docker-compose.yml
[start_time:Mon, 20 Sep 2021 05:24:22 GMT, release_branch:7.x, prefix:, end_time:Mon, 20 Sep 2021 11:45:00 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-3f2f8446, build_duration_seconds:22838]
> [automation] update elastic stack version for testing 7.16.0-3f2f8446

- docker-compose.yml
[start_time:Mon, 20 Sep 2021 17:24:33 GMT, release_branch:7.15, prefix:, end_time:Mon, 20 Sep 2021 23:19:14 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-5ab1fe99, build_duration_seconds:21281]
> [automation] update elastic stack version for testing 7.15.0-5ab1fe99

- changelogs/7.14.asciidoc
- docs: 7.14.2 release notes (#6195)
> [7.x] docs: 7.14.2 release notes (#6195)

- changelogs/6.8.asciidoc
- docs: 6.8.19 release notes (#6194)
> [7.15] docs: 6.8.19 release notes (#6194)

- changelogs/6.8.asciidoc
- docs: 6.8.19 release notes (#6194) (#6209)
> [7.x] docs: 6.8.19 release notes (#6194) (#6209)

- CHANGELOG.asciidoc
- changelogs/7.14.asciidoc
- changelogs/7.15.asciidoc
- docs/release-notes.asciidoc
- docs: prepare release notes (#6178)
> [7.15] docs: prepare 7.15 release notes (#6178)

- CHANGELOG.asciidoc
- changelogs/7.14.asciidoc
- changelogs/7.15.asciidoc
- docs/release-notes.asciidoc
- docs: prepare release notes (#6178)
> [7.x] docs: prepare 7.15 release notes (#6178)

- docs/guide/apm-breaking-changes.asciidoc
Update APM Overview breaking changes to match the breaking changes merged in https://github.com/elastic/apm-server/pull/6178 and init 7.16 breaking changes.
> docs: update APM Overview breaking changes

- docker-compose.yml
[start_time:Tue, 21 Sep 2021 19:56:10 GMT, release_branch:7.15, prefix:, end_time:Wed, 22 Sep 2021 01:34:56 GMT, manifest_version:2.0.0, version:7.15.0-SNAPSHOT, branch:7.15, build_id:7.15.0-28b0107a, build_duration_seconds:20326]
> [automation] update elastic stack version for testing 7.15.0-28b0107a

- docs/breaking-changes.asciidoc
- docs/guide/apm-breaking-changes.asciidoc
Fixes links from the 7.15 breaking changes.
> docs: fix 7.15 breaking changes

- docker-compose.yml
[start_time:Wed, 22 Sep 2021 12:25:51 GMT, release_branch:master, prefix:, end_time:Thu, 23 Sep 2021 02:07:09 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-aa012679, build_duration_seconds:49278]
> [automation] update elastic stack version for testing 8.0.0-aa012679

- docker-compose.yml
[start_time:Wed, 22 Sep 2021 05:22:09 GMT, release_branch:7.x, prefix:, end_time:Wed, 22 Sep 2021 11:49:10 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-51a7a70c, build_duration_seconds:23221]
> [automation] update elastic stack version for testing 7.16.0-51a7a70c

- docker-compose.yml
[start_time:Wed, 22 Sep 2021 21:27:32 GMT, release_branch:7.15, prefix:, end_time:Thu, 23 Sep 2021 03:39:09 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-f9f656c4, build_duration_seconds:22297]
> [automation] update elastic stack version for testing 7.15.1-f9f656c4

- apmpackage/apm/changelog.yml
- apmpackage/apm/data_stream/app_metrics/elasticsearch/ilm/default_policy.json
- apmpackage/apm/data_stream/error_logs/elasticsearch/ilm/default_policy.json
- apmpackage/apm/data_stream/internal_metrics/elasticsearch/ilm/default_policy.json
- apmpackage/apm/data_stream/profile_metrics/elasticsearch/ilm/default_policy.json
- apmpackage/apm/data_stream/traces/elasticsearch/ilm/default_policy.json
Remove the warm phase from installed ILM policies. Having a warm phase by default means that even small deployments in ESS, with autoscaling enabled, will autoscale up a warm tier Elasticsearch after 30 days. That's not desirable/cost effective for small deployments.
1. Install APM integration
2. Check that none of the installed ILM policies have a warm phase
Closes https://github.com/elastic/apm-server/issues/6170
> apmpackage: remove warm phase from ILM policies

- docker-compose.yml
[start_time:Thu, 23 Sep 2021 17:00:54 GMT, release_branch:master, prefix:, end_time:Thu, 23 Sep 2021 22:30:51 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-61c5a306, build_duration_seconds:19797]
> [automation] update elastic stack version for testing 8.0.0-61c5a306

- docker-compose.yml
[start_time:Thu, 23 Sep 2021 17:05:38 GMT, release_branch:7.x, prefix:, end_time:Thu, 23 Sep 2021 23:29:48 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-70330f11, build_duration_seconds:23050]
> [automation] update elastic stack version for testing 7.16.0-70330f11

- docker-compose.yml
[start_time:Thu, 23 Sep 2021 17:23:03 GMT, release_branch:7.15, prefix:, end_time:Fri, 24 Sep 2021 00:14:59 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-de1fe33e, build_duration_seconds:24716]
> [automation] update elastic stack version for testing 7.15.1-de1fe33e

- docker-compose.yml
[start_time:Sun, 26 Sep 2021 17:24:52 GMT, release_branch:7.15, prefix:, end_time:Sun, 26 Sep 2021 23:07:42 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-5f9d0364, build_duration_seconds:20570]
> [automation] update elastic stack version for testing 7.15.1-5f9d0364

- docker-compose.yml
[start_time:Sun, 26 Sep 2021 05:25:48 GMT, release_branch:7.x, prefix:, end_time:Sun, 26 Sep 2021 11:21:29 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-4cbd636a, build_duration_seconds:21341]
> [automation] update elastic stack version for testing 7.16.0-4cbd636a

- .ci/update-beats.groovy
Add `backport-skip` label for certain projects that use the automated bump process
Avoid missing backport labels in the notifications
Caused by https://github.com/elastic/apm-server/pull/6186
> [bump][automation] skip backports for the automation

- docker-compose.yml
[start_time:Mon, 27 Sep 2021 22:05:34 GMT, release_branch:master, prefix:, end_time:Tue, 28 Sep 2021 04:14:41 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-9d408327, build_duration_seconds:22147]
> [automation] update elastic stack version for testing 8.0.0-9d408327

- docker-compose.yml
[start_time:Mon, 27 Sep 2021 22:17:58 GMT, release_branch:7.15, prefix:, end_time:Tue, 28 Sep 2021 04:57:19 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-34ec300e, build_duration_seconds:23961]
> [automation] update elastic stack version for testing 7.15.1-34ec300e

- docker-compose.yml
[start_time:Tue, 28 Sep 2021 17:19:42 GMT, release_branch:7.15, prefix:, end_time:Tue, 28 Sep 2021 23:12:42 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-56129787, build_duration_seconds:21180]
> [automation] update elastic stack version for testing 7.15.1-56129787

- docker-compose.yml
[start_time:Tue, 28 Sep 2021 15:06:30 GMT, release_branch:master, prefix:, end_time:Wed, 29 Sep 2021 00:59:20 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-aef26e82, build_duration_seconds:35570]
> [automation] update elastic stack version for testing 8.0.0-aef26e82

- docker-compose.yml
[start_time:Wed, 29 Sep 2021 17:19:58 GMT, release_branch:7.15, prefix:, end_time:Wed, 29 Sep 2021 23:07:08 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-f3d0455b, build_duration_seconds:20830]
> [automation] update elastic stack version for testing 7.15.1-f3d0455b

- docker-compose.yml
[start_time:Wed, 29 Sep 2021 05:24:06 GMT, release_branch:7.x, prefix:, end_time:Wed, 29 Sep 2021 11:17:22 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-f67263fd, build_duration_seconds:21196]
> [automation] update elastic stack version for testing 7.16.0-f67263fd

- beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationTransactionsHugeTraces.approved.json
- changelogs/7.15.asciidoc
- docs/data/elasticsearch/generated/errors.json
- docs/data/elasticsearch/generated/transactions.json
- model/apmevent_test.go
- model/http.go
- processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationTransactionsHugeTraces.approved.json
- systemtest/approvals/TestTransactionDroppedSpansStatsTransaction.approved.json
- tests/system/error.approved.json
- tests/system/transaction.approved.json
Ensure de-dotting `http.request.body.original`, allowing to run ingest processor logic on the field. 
* Add apm ingest processor to apm ingest pipelien, parsing the `http.request.body.original`, for example as the one mentioned in the [discuss entry](https://discuss.elastic.co/t/apm-capture-body-is-broken-after-upgrading-from-7-14-0-to-7-15-0/285300/2)
* Index data with the request body 
* Ensure that the ingest processor is applied. 
fixes elastic/apm-server#6255
> fix: Dedot http.request.body.original

- docker-compose.yml
[start_time:Thu, 30 Sep 2021 05:14:08 GMT, release_branch:7.x, prefix:, end_time:Thu, 30 Sep 2021 11:20:18 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-806be5a9, build_duration_seconds:21970]
> [automation] update elastic stack version for testing 7.16.0-806be5a9

- docker-compose.yml
[start_time:Thu, 30 Sep 2021 00:15:06 GMT, release_branch:7.15, prefix:, end_time:Thu, 30 Sep 2021 06:33:47 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-a28dd8b0, build_duration_seconds:22721]
> [automation] update elastic stack version for testing 7.15.1-a28dd8b0

- beater/beater.go
- beater/test_approved_es_documents/TestPublishIntegrationTransactionsHugeTraces.approved.json
- docs/spec/v2/transaction.json
- model/modeldecoder/v2/decoder.go
- model/modeldecoder/v2/model.go
- model/modeldecoder/v2/model_generated.go
- model/modeldecoder/v2/transaction_test.go
- model/modelprocessor/dropped_spans_stats.go
- model/transaction.go
- model/transaction_test.go
- processor/stream/test_approved_es_documents/testIntakeIntegrationTransactionsHugeTraces.approved.json
- systemtest/approvals/TestTransactionDroppedSpansStatsTransaction.approved.json
- x-pack/apm-server/aggregation/spanmetrics/aggregator.go
- x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
Removes the `dropped_spans_stats.{type,subtype}` fields from the intake
API and sets the `model.APMEvent.Transaction.DroppedSpansStats` to `nil`
after the metricsets have been created for the `dropped_spans_stats`.
Introduces a new `modelprocessor.DroppedSpansStatsDiscarder` since we do
not want to send the `model.APMEvent.Transaction.DroppedSpansStats` to
the published and store it in Elasticsearch, since the only use for the
field is the process the relevant metricsets for spans that are dropped.
To allow any processors before the new processor is run, it is appended
just before the publisher.
- ~[ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~
The system tests cover the base usage, but to test this change:
1. `make && docker compose …
> dropped_spans_stats: Remove `type`, `subtype` fields

- docker-compose.yml
[start_time:Sun, 3 Oct 2021 05:24:19 GMT, release_branch:7.x, prefix:, end_time:Sun, 3 Oct 2021 11:11:48 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.x, build_id:7.16.0-76e5f71e, build_duration_seconds:20849]
> [automation] update elastic stack version for testing 7.16.0-76e5f71e

- Jenkinsfile
Fixes the GitHub issue comment regex, that had an extra `)`
Let's ensure the comments work as expected
`/test` worked fine
`/package` worked fine
> ci: fix comment issue regex

- beater/beater.go
- beater/server_test.go
Watch libbeat output config changes, and restart the beater with updated config. This enables us to propagate the Elasticsearch output config to tail-based sampling when running under Fleet.
~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~ (non user facing change)
Can't be manually tested yet, needs UI for configuring tail-sampling policies.
#5490
> beater: watch output config changes

- docker-compose.yml
[start_time:Tue, 5 Oct 2021 00:15:03 GMT, release_branch:7.15, prefix:, end_time:Tue, 5 Oct 2021 06:20:28 GMT, manifest_version:2.0.0, version:7.15.1-SNAPSHOT, branch:7.15, build_id:7.15.1-c5b3409f, build_duration_seconds:21925]
> [automation] update elastic stack version for testing 7.15.1-c5b3409f

- docker-compose.yml
[start_time:Sun, 31 Oct 2021 05:17:30 GMT, release_branch:7.16, prefix:, end_time:Sun, 31 Oct 2021 11:16:28 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-66ccea1a, build_duration_seconds:21538]
> [automation] update elastic stack version for testing 7.16.0-66ccea1a

- docker-compose.yml
[start_time:Sun, 31 Oct 2021 17:30:04 GMT, release_branch:7.15, prefix:, end_time:Sun, 31 Oct 2021 23:30:29 GMT, manifest_version:2.0.0, version:7.15.2-SNAPSHOT, branch:7.15, build_id:7.15.2-fecae5f4, build_duration_seconds:21625]
> [automation] update elastic stack version for testing 7.15.2-fecae5f4

- beater/beater.go
- changelogs/head.asciidoc
- cmd/root.go
- cmd/root_test.go
- publish/pub.go
Block use of libbeat processors in apm-server. They have never been formally supported; now they are more explicitly unsupported.
Run apm-server with `-E processors=[add_cloud_metadata:{}]`, check that it exits with an error indicating that processors are unsupported.
Closes #5991
> cmd: disallow libbeat processors

- docs/legacy/guide/apm-breaking-changes.asciidoc
- docs/legacy/tab-widgets/configure-server.asciidoc
- docs/legacy/upgrading-to-70.asciidoc
- docs/legacy/upgrading.asciidoc
Just a few more links to fix:
```
18:36:10 INFO:build_docs:Bad cross-document links:
18:37:04 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/7.16/release-notes-7.0.html contains broken links to:
18:37:04 INFO:build_docs:   - en/apm/get-started/7.16/breaking-7.0.0.html
18:37:04 INFO:build_docs:   - en/apm/server/7.16/breaking-changes.html
18:37:04 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/8.0/release-notes-7.0.html contains broken links to:
18:37:04 INFO:build_docs:   - en/apm/get-started/8.0/breaking-7.0.0.html
18:37:04 INFO:build_docs:   - en/apm/server/8.0/breaking-changes.html
18:37:04 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/current/release-notes-7.0.html contains broken links to:
18:37:04 INFO:build_docs:   - …
```
> docs: fix three more links

- beater/config/aggregation.go
- beater/config/config.go
- beater/config/config_test.go
- changelogs/head.asciidoc
- docs/legacy/transaction-metrics.asciidoc
- systemtest/aggregation_test.go
- systemtest/apmservertest/config.go
- systemtest/sampling_test.go
- x-pack/apm-server/main.go
- x-pack/apm-server/main_test.go
Completely removes the `apm-server.aggregation.transactions.enabled`
configuration settings and changes the `apm-server` to always aggregate
transaction metrics.
1. `docker-compose up -d`
2. `make`
3. `./apm-server -E apm-server.aggregation.transactions.enabled=false -E output.elasticsearch.username=admin -E output.elasticsearch.password=changeme -e`
4. `curl -H "Content-type: application/x-ndjson" --data-binary @testdata/intake-v2/transactions.ndjson http://localhost:8200/intake/v2/events`
5. Go to Kibana Dev Tools and validate that transaciton metrics were ingested:
```javascript
GET *metric*/_search
{
"_source": [false], 
"fields": [
"transaction.duration.*"
], 
"query": {
"exists": {
"field": "transaction.duration.histogram"
}
}
}
```
There should be 4 results and all of them must …
> Remove `apm-server.aggregation.transactions.enabled`

- docker-compose.yml
[start_time:Mon, 1 Nov 2021 00:15:49 GMT, release_branch:7.15, prefix:, end_time:Mon, 1 Nov 2021 06:32:25 GMT, manifest_version:2.0.0, version:7.15.2-SNAPSHOT, branch:7.15, build_id:7.15.2-5325c15b, build_duration_seconds:22596]
> [automation] update elastic stack version for testing 7.15.2-5325c15b

- systemtest/approvals/TestCompressedSpans.approved.json
- systemtest/huge_traces_test.go
Ensure the order of documents approved by TestCompressedSpans is deterministic, by using known timestamps and IDs. These are used when sorting the documents.
N/A
https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/PR-6499/2/testReport/github/com_elastic_apm-server_systemtest/Build_and_Test___System_and_Environment_Tests___TestCompressedSpans/
> systemtest: use deterministic IDs and timestamps

- beater/beater.go
- beater/beater_test.go
- cmd/root.go
- cmd/root_test.go
- publish/pub.go
- publish/pub_test.go
- systemtest/otlp_test.go
Fixes a bug which prevented the libbeat pipeline client from using the
`drop_event` processor we use to drop events with `processor.event: log`
set, when data streams are disabled.
1. Start APM Server in standalone mode with data_streams disabled.
2. Send an OTLP span with an event.
3. Verify that no log events are indexed (`processor.event: log`)
OR
1. `cd systemtest && go test -v -count=1 -run TestOTLPGRPCTraces/data_streams_disabled .`
2. Navigate to [Kibana dev tools](http://localhost:5601/app/dev_tools#/console)
3. Ensure that the following query returns:
```javascript
GET apm-*,traces-apm*,logs-apm*/_search
{
"_source": [false],
"fields": [
"processor.event"
], 
"query": {
"match": {
"trace.id": "d2acbef8b37655e48548fd9d61ad6114"
}
}
}
```
```javascript
{
"took" : 5,
"timed_out" : …
```
> publisher: Allow processor use within apm-server

- docker-compose.yml
[start_time:Mon, 1 Nov 2021 00:16:56 GMT, release_branch:8.0, prefix:, end_time:Mon, 1 Nov 2021 06:48:58 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-6b50534b, build_duration_seconds:23522]
> [automation] update elastic stack version for testing 8.0.0-6b50534b

- docker-compose.yml
[start_time:Wed, 3 Nov 2021 05:16:32 GMT, release_branch:7.16, prefix:, end_time:Wed, 3 Nov 2021 16:07:27 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-c51d3b71, build_duration_seconds:39055]
> [automation] update elastic stack version for testing 7.16.0-c51d3b71

- systemtest/approvals.go
- systemtest/approvals/TestCompressedSpans.approved.json
- systemtest/approvals/TestOTLPGRPCTraces/data_streams_enabled.approved.json
- systemtest/approvals/TestRUMRoutingIntegration.approved.json
Don't indicate a document is less than another just because one field is less -- all preceding sort fields must be equal.
N/A
None
> systemtest: fix sorting in approvals

- systemtest/agentconfig_test.go
Adds retrying logic when the response from fleet-server returns `io.EOF`
up to 10 times, with a retry timer of 500 Milliseconds.
1. `go test -v -count=10 -run TestAgentConfig .`
2. Check that `agentconfig_test.go:127: fleet returned EOF on read, retry 1/10...` appears on the output and the test ultimately pass.
> systemtest: `queryAgentConfig` retry on `io.EOF`

- changelogs/head.asciidoc
- docs/spec/rumv3/error.json
- docs/spec/v2/error.json
- model/modeldecoder/rumv3/decoder.go
- model/modeldecoder/rumv3/error_test.go
- model/modeldecoder/rumv3/model.go
- model/modeldecoder/rumv3/model_generated.go
- model/modeldecoder/v2/decoder.go
- model/modeldecoder/v2/error_test.go
- model/modeldecoder/v2/model.go
- model/modeldecoder/v2/model_generated.go
Fixes #6529
I added unit tests
> Added support for transaction.name in an error object to the intake API

- docker-compose.yml
[start_time:Thu, 4 Nov 2021 05:25:26 GMT, release_branch:7.16, prefix:, end_time:Thu, 4 Nov 2021 11:30:00 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-68781827, build_duration_seconds:21874]
> [automation] update elastic stack version for testing 7.16.0-68781827

- docker-compose.yml
[start_time:Thu, 4 Nov 2021 00:15:53 GMT, release_branch:8.0, prefix:, end_time:Thu, 4 Nov 2021 06:44:00 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-fc3570a9, build_duration_seconds:23287]
> [automation] update elastic stack version for testing 8.0.0-fc3570a9

- docker-compose.yml
[start_time:Tue, 9 Nov 2021 05:15:09 GMT, release_branch:7.16, prefix:, end_time:Tue, 9 Nov 2021 11:11:46 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-df026734, build_duration_seconds:21397]
> [automation] update elastic stack version for testing 7.16.0-df026734

- apmpackage/apm/changelog.yml
- apmpackage/apm/manifest.yml
- systemtest/helpers_test.go
Updates the APM Package version to 8.0.0 since it was not updated when
the 7.16.0 release got pushed, and after we published the apm package
`8.0.0-dev1` to staging, the tests started installing that version of
the package instead of relying on the local package since the remote
version was higher.
Run `go test -v -run TestRUMXForwardedFor .`, verify it doesn't fail.
Closes #6562
Introduced by https://github.com/elastic/package-storage/pull/2728
> package: Update version to 8.0.0

- .ci/jobs/apm-server-check-changelogs-mbp.yml
- .ci/jobs/apm-server-mbp.yml
- .ci/jobs/update-json-schema.yml
Tidy up the Jenkisn Multibranch pipelines with only the active branches and release branches. In other words, all the automation with `mergify`, `dependabot` or the `bump automation` should not be added as branches.
> [jjbb] list for release and active branches

- .ci/jobs/apm-server-check-changelogs-mbp.yml
- .ci/jobs/apm-server-check-packages-mbp.yml
- .ci/jobs/apm-server-mbp.yml
Tidy up the Jenkisn Multibranch pipelines with only the active branches and release branches. In other words, all the automation with `mergify`, `dependabot` or the `bump automation` should not be added as branches.
Similar to https://github.com/elastic/apm-server/pull/6561 but with a different regex, otherwise the branches are not reported :/
> [jjbb] add regex for the active branches

- systemtest/kibana.go
`systemtest.TestTailSampling` has been failing with errors like:
```
2021/11/12 05:31:37 Container is ready id: d7064c092de5 image: elastic-agent-systemtest:8.1.0-49c447b0-SNAPSHOT
kibana.go:141: 
Error Trace:	kibana.go:141
fleet_test.go:104
sampling_test.go:69
Error:      	Received unexpected error:
There is already a package with the same name
Test:       	TestTailSampling
```
Initially we thought this was flakiness in our tests, then thought maybe it was a concurrency issue in CI. Actually, it's due to a functional change in Fleet: with https://github.com/elastic/kibana/pull/115212 package policy names must not be globally unique, not just unique within their agent policy.
We now ensure package policy names we generate are globally unique by including the agent policy name.
~- [ ] …
> systemtest: ensure unique package policy names

- apmpackage/apm/data_stream/rum_traces/fields/fields.yml
- apmpackage/apm/data_stream/traces/fields/fields.yml
- apmpackage/apm/docs/README.md
- beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
- beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
- changelogs/head.asciidoc
- model/apmevent.go
- model/modeldecoder/rumv3/decoder.go
- model/modeldecoder/v2/decoder.go
- model/modeldecoder/v2/span_test.go
- model/span.go
- model/span_test.go
- processor/otel/test_approved/span_jaeger_http.approved.json
- processor/otel/test_approved/span_jaeger_http_status_code.approved.json
- processor/otel/test_approved/span_jaeger_https_default_port.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationInvalidEvent.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationInvalidJSONEvent.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationOpenTelemetryBridge.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationRumTransactions.approved.json
- processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
- processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
- systemtest/approvals/TestNoMatchingSourcemap.approved.json
- systemtest/approvals/TestRUMRoutingIntegration.approved.json
- systemtest/approvals/TestRUMSpanSourcemapping.approved.json
Drop deprecated `span.{start,http}` fields:
- `span.start.us` is not used by the UI
- `span.http.*` fields have been copied to ECS field sets, `http.*` and `url.*`, since 7.14
A minor change to the UI is required to pick up the ECS fields: https://github.com/elastic/kibana/pull/118485
1. Send some RUM transactions and spans, check the spans have no `span.start.us` field
2. Send some HTTP client spans, check they have no `span.http.*` fields
Closes https://github.com/elastic/apm-server/issues/5995
Closes https://github.com/elastic/apm-server/issues/6000
> Drop deprecated `span.{start,http}` fields

- beater/config/auth.go
- beater/config/auth_test.go
- beater/config/config_test.go
- changelogs/head.asciidoc
Automatically sets `auth.anonymous.enabled=true` when `rum.enabled=true`
~- [] Documentation has been updated~
1. `docker-compose up -d`
2. `make`
3. `./apm-server -e -E output.elasticsearch.username=admin -E output.elasticsearch.password=changeme -E apm-server.rum.enabled=true -E apm-server.auth.secret_token=abc`
4. Verify that `anonymous access enabled for RUM` appears in the logs.
Closes #6570
> config: Enable `auth.anonymous` when `rum.enabled`

- docker-compose.yml
[start_time:Sun, 14 Nov 2021 05:15:42 GMT, release_branch:7.16, prefix:, end_time:Sun, 14 Nov 2021 11:19:04 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-27f0a6d6, build_duration_seconds:21802]
> [automation] update elastic stack version for testing 7.16.0-27f0a6d6

- docker-compose.yml
[start_time:Sun, 14 Nov 2021 12:16:59 GMT, release_branch:master, prefix:, end_time:Sun, 14 Nov 2021 18:22:23 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-e547d04a, build_duration_seconds:21924]
> [automation] update elastic stack version for testing 8.1.0-e547d04a

- docker-compose.yml
[start_time:Sun, 14 Nov 2021 17:25:09 GMT, release_branch:7.15, prefix:, end_time:Sun, 14 Nov 2021 23:22:39 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-b30acc1a, build_duration_seconds:21450]
> [automation] update elastic stack version for testing 7.15.3-b30acc1a

- .ci/scripts/windows-build.ps1
- .ci/scripts/windows-test.ps1
We only build the apm-server binary and run unit tests on Windows. Python is not needed, so stop installing it -- this should reduce build flakiness.
> ci: don't install python on Windows

- docker-compose.yml
[start_time:Mon, 15 Nov 2021 00:15:55 GMT, release_branch:8.0, prefix:, end_time:Mon, 15 Nov 2021 06:34:41 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-0357b4f0, build_duration_seconds:22726]
> [automation] update elastic stack version for testing 8.0.0-0357b4f0

- docker-compose.yml
[start_time:Mon, 15 Nov 2021 00:28:26 GMT, release_branch:master, prefix:, end_time:Mon, 15 Nov 2021 06:53:06 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-14029b3d, build_duration_seconds:23080]
> [automation] update elastic stack version for testing 8.1.0-14029b3d

- docker-compose.yml
[start_time:Mon, 15 Nov 2021 00:15:15 GMT, release_branch:7.15, prefix:, end_time:Mon, 15 Nov 2021 06:04:34 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-781c0f9a, build_duration_seconds:20959]
> [automation] update elastic stack version for testing 7.15.3-781c0f9a

- beater/beater.go
- elasticsearch/config.go
- elasticsearch/config_test.go
- model/modelindexer/bulk_indexer.go
- model/modelindexer/indexer.go
- model/modelindexer/indexer_test.go
- x-pack/apm-server/main.go
- x-pack/apm-server/sampling/config.go
- x-pack/apm-server/sampling/config_test.go
- x-pack/apm-server/sampling/pubsub/config.go
- x-pack/apm-server/sampling/pubsub/pubsub.go
- x-pack/apm-server/sampling/pubsub/pubsub_test.go
Backports the following commits to 7.16:
- modelindexer: add support for gzip compression (#6449)
> [7.16] modelindexer: add support for gzip compression (#6449)

- changelogs/head.asciidoc
- model/modelindexer/bulk_indexer.go
- model/modelindexer/indexer_test.go
Fix a bug in modelindexer's bulk response decoder. We need to skip over unknown/unhandled fields, e.g. ingest_took. This field is not specified in the go-elasticsearch bulk response type, so we don't handle it.
1. Run apm-server with `-E output.elasticsearch.experimental=true`
2. Send events
3. Check logs for modelindexer errors
None
> model/modelindexer: skip unknown response fields

- docker-compose.yml
[start_time:Tue, 16 Nov 2021 16:01:23 GMT, release_branch:7.16, prefix:, end_time:Tue, 16 Nov 2021 22:02:26 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-1af90c36, build_duration_seconds:21663]
> [automation] update elastic stack version for testing 7.16.0-1af90c36

- docker-compose.yml
[start_time:Tue, 16 Nov 2021 12:23:33 GMT, release_branch:master, prefix:, end_time:Tue, 16 Nov 2021 18:43:36 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-a31f3b73, build_duration_seconds:22803]
> [automation] update elastic stack version for testing 8.1.0-a31f3b73

- docker-compose.yml
[start_time:Tue, 16 Nov 2021 17:23:12 GMT, release_branch:7.15, prefix:, end_time:Tue, 16 Nov 2021 23:21:46 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-a6aad1c6, build_duration_seconds:21514]
> [automation] update elastic stack version for testing 7.15.3-a6aad1c6

- changelogs/head.asciidoc
- model/modelindexer/indexer.go
- model/modelindexer/indexer_test.go
Update the timestamp format used for encoding `@timestamp` so it includes fractional seconds, with millisecond precision.
1. Run apm-server `-E output.elasticsearch.experimental=true`
2. Check that indexed docs' `@timestamp` fields have a fractional seconds component
https://github.com/elastic/apm-server/issues/6360
> modelindexer: fix @timestamp format

- docker-compose.yml
[start_time:Wed, 17 Nov 2021 05:13:59 GMT, release_branch:7.16, prefix:, end_time:Wed, 17 Nov 2021 11:16:29 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-705b02ff, build_duration_seconds:21750]
> [automation] update elastic stack version for testing 7.16.0-705b02ff

- docker-compose.yml
[start_time:Wed, 17 Nov 2021 12:27:01 GMT, release_branch:master, prefix:, end_time:Wed, 17 Nov 2021 18:38:56 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-11229697, build_duration_seconds:22315]
> [automation] update elastic stack version for testing 8.1.0-11229697

- docker-compose.yml
[start_time:Wed, 17 Nov 2021 00:21:35 GMT, release_branch:8.0, prefix:, end_time:Wed, 17 Nov 2021 06:52:20 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-83e38099, build_duration_seconds:23445]
> [automation] update elastic stack version for testing 8.0.0-83e38099

- .github/pull_request_template.md
- apmpackage/apm/changelog.yml
Updates the `apmpackage` changelog to include the latest changes, also
updating the PR template to include a note to update the changelog file
when changes have been made to the `apmpackage` folder.
N/A
N/A
> docs: Update apmpackage changelog and PR template

- docker-compose.yml
[start_time:Thu, 18 Nov 2021 12:15:58 GMT, release_branch:master, prefix:, end_time:Thu, 18 Nov 2021 18:23:56 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-875ad7e2, build_duration_seconds:22078]
> [automation] update elastic stack version for testing 8.1.0-875ad7e2

- docker-compose.yml
[start_time:Thu, 18 Nov 2021 05:13:19 GMT, release_branch:7.16, prefix:, end_time:Thu, 18 Nov 2021 11:00:22 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-3a1031bc, build_duration_seconds:20823]
> [automation] update elastic stack version for testing 7.16.0-3a1031bc

- docker-compose.yml
[start_time:Thu, 18 Nov 2021 00:14:03 GMT, release_branch:8.0, prefix:, end_time:Thu, 18 Nov 2021 06:32:27 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-1160a953, build_duration_seconds:22704]
> [automation] update elastic stack version for testing 8.0.0-1160a953

- Makefile
- apmpackage/apm/changelog.yml
- apmpackage/apm/manifest.yml
Adds a check to `check-package` which ensures the apm-server and package
versions are equal, otherwise returns with an error.
N/A
Closes #6571
> package: Verify APM server/package versions match

- docker-compose.yml
[start_time:Sun, 21 Nov 2021 17:22:39 GMT, release_branch:7.15, prefix:, end_time:Sun, 21 Nov 2021 23:37:11 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-2ab3d0ac, build_duration_seconds:22472]
> [automation] update elastic stack version for testing 7.15.3-2ab3d0ac

- docker-compose.yml
[start_time:Mon, 22 Nov 2021 17:14:15 GMT, release_branch:7.15, prefix:, end_time:Mon, 22 Nov 2021 23:30:29 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-4c145d2b, build_duration_seconds:22574]
> [automation] update elastic stack version for testing 7.15.3-4c145d2b

- docker-compose.yml
[start_time:Mon, 22 Nov 2021 14:41:43 GMT, release_branch:master, prefix:, end_time:Mon, 22 Nov 2021 21:03:42 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-14a0128f, build_duration_seconds:22919]
> [automation] update elastic stack version for testing 8.1.0-14a0128f

- model/labels.go
- model/modeldecoder/modeldecoderutil/labels.go
- processor/otel/traces.go
Adds some godoc comments to the `LabelValue` and `NumericLabelValue` and
removes the `MaybeSet` method.
Non functional change.
Follow up from #6682
> model: Add comments, Remove MaybeSet from labels

- changelogs/head.asciidoc
- processor/otel/metrics.go
- processor/otel/metrics_test.go
Filter out metric samples with values that cannot be represented in Elasticsearch.
See https://github.com/elastic/apm-server/issues/6641
Closes https://github.com/elastic/apm-server/issues/6641
> Filter out NaN and +/-Inf metric data points

- docker-compose.yml
[start_time:Tue, 23 Nov 2021 05:15:24 GMT, release_branch:7.16, prefix:, end_time:Tue, 23 Nov 2021 11:07:55 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-8c304116, build_duration_seconds:21151]
> [automation] update elastic stack version for testing 7.16.0-8c304116

- docker-compose.yml
[start_time:Tue, 23 Nov 2021 00:15:48 GMT, release_branch:8.0, prefix:, end_time:Tue, 23 Nov 2021 06:11:01 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-28ef013c, build_duration_seconds:21313]
> [automation] update elastic stack version for testing 8.0.0-28ef013c

- docker-compose.yml
[start_time:Tue, 23 Nov 2021 17:23:30 GMT, release_branch:7.15, prefix:, end_time:Tue, 23 Nov 2021 23:33:38 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-c1618cb4, build_duration_seconds:22208]
> [automation] update elastic stack version for testing 7.15.3-c1618cb4

- docker-compose.yml
[start_time:Tue, 23 Nov 2021 12:20:13 GMT, release_branch:master, prefix:, end_time:Tue, 23 Nov 2021 18:39:27 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-d173e6ad, build_duration_seconds:22754]
> [automation] update elastic stack version for testing 8.1.0-d173e6ad

- docker-compose.yml
[start_time:Wed, 24 Nov 2021 05:14:01 GMT, release_branch:7.16, prefix:, end_time:Wed, 24 Nov 2021 11:04:16 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-5227689d, build_duration_seconds:21015]
> [automation] update elastic stack version for testing 7.16.0-5227689d

- docker-compose.yml
[start_time:Wed, 24 Nov 2021 17:22:58 GMT, release_branch:7.15, prefix:, end_time:Wed, 24 Nov 2021 23:40:01 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-ba00df8f, build_duration_seconds:22623]
> [automation] update elastic stack version for testing 7.15.3-ba00df8f

- docker-compose.yml
[start_time:Wed, 24 Nov 2021 12:17:00 GMT, release_branch:master, prefix:, end_time:Wed, 24 Nov 2021 19:04:55 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-1c3bdf27, build_duration_seconds:24475]
> [automation] update elastic stack version for testing 8.1.0-1c3bdf27

- docker-compose.yml
[start_time:Wed, 24 Nov 2021 00:18:17 GMT, release_branch:8.0, prefix:, end_time:Wed, 24 Nov 2021 07:11:58 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-ca68b68a, build_duration_seconds:24821]
> [automation] update elastic stack version for testing 8.0.0-ca68b68a

- docker-compose.yml
[start_time:Thu, 25 Nov 2021 05:12:53 GMT, release_branch:7.16, prefix:, end_time:Thu, 25 Nov 2021 10:59:38 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-58c0cae7, build_duration_seconds:20805]
> [automation] update elastic stack version for testing 7.16.0-58c0cae7

- docker-compose.yml
[start_time:Thu, 25 Nov 2021 00:18:01 GMT, release_branch:8.0, prefix:, end_time:Thu, 25 Nov 2021 06:22:02 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-89da64e1, build_duration_seconds:21841]
> [automation] update elastic stack version for testing 8.0.0-89da64e1

- docker-compose.yml
[start_time:Thu, 25 Nov 2021 12:25:38 GMT, release_branch:master, prefix:, end_time:Thu, 25 Nov 2021 18:46:36 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-a48471bd, build_duration_seconds:22858]
> [automation] update elastic stack version for testing 8.1.0-a48471bd

- docker-compose.yml
[start_time:Thu, 25 Nov 2021 17:16:20 GMT, release_branch:7.15, prefix:, end_time:Thu, 25 Nov 2021 23:06:05 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-57b973bf, build_duration_seconds:20985]
> [automation] update elastic stack version for testing 7.15.3-57b973bf

- docker-compose.yml
[start_time:Sun, 28 Nov 2021 12:25:23 GMT, release_branch:master, prefix:, end_time:Sun, 28 Nov 2021 18:36:19 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-3307da9c, build_duration_seconds:22256]
> [automation] update elastic stack version for testing 8.1.0-3307da9c

- docker-compose.yml
[start_time:Fri, 26 Nov 2021 05:13:21 GMT, release_branch:7.16, prefix:, end_time:Fri, 26 Nov 2021 11:09:47 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-19916e4d, build_duration_seconds:21386]
> [automation] update elastic stack version for testing 7.16.0-19916e4d

- docker-compose.yml
[start_time:Sun, 28 Nov 2021 17:14:57 GMT, release_branch:7.15, prefix:, end_time:Sun, 28 Nov 2021 23:15:11 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-e51e78d3, build_duration_seconds:21614]
> [automation] update elastic stack version for testing 7.15.3-e51e78d3

- docker-compose.yml
[start_time:Sun, 28 Nov 2021 00:15:19 GMT, release_branch:8.0, prefix:, end_time:Sun, 28 Nov 2021 06:46:30 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-94dc1348, build_duration_seconds:23471]
> [automation] update elastic stack version for testing 8.0.0-94dc1348

- docker-compose.yml
[start_time:Mon, 29 Nov 2021 05:12:58 GMT, release_branch:7.16, prefix:, end_time:Mon, 29 Nov 2021 11:02:17 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-4a83af8d, build_duration_seconds:20959]
> [automation] update elastic stack version for testing 7.16.0-4a83af8d
