elastic/apm-server

docker-compose.yml

[start_time:Thu, 1 Jul 2021 00:15:09 GMT, release_branch:master, prefix:, end_time:Thu, 1 Jul 2021 04:51:31 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-abbf7c2f, build_duration_seconds:16582]

[automation] update elastic stack version for testing 8.0.0-abbf7c2f

---

changelogs/6.8.asciidoc

docs: add 6.8.17 release notes

---

cmd/version.go

Update to version 7.13.4

---

docs/guide/opentelemetry-elastic.asciidoc

Document AWS Lambda OpenTelemetry support.
ℹ️  Documentation to monitor Python, and Node.js functions will be added soon. cc @michaelhyatt .
Test the following AWS Lambda Java + Terraform example : https://github.com/cyrille-leclerc/my-serverless-shopping-cart

Document AWS Lambda OpenTelemetry support

---

docs/guide/opentelemetry-elastic.asciidoc

- Document AWS Lambda OpenTelemetry support (#5674)

[master] Document AWS Lambda OpenTelemetry support (#5674)

---

beater/api/asset/sourcemap/handler.go
beater/api/asset/sourcemap/sourcemap.go
beater/api/asset/sourcemap/sourcemap_test.go

Reserve model for event types, not auxiliary documents like this.
#4410
#4120
#3565

Move Sourcemap from model to sourcemap handler

---

Jenkinsfile
script/common.bash

This is an automatic backport of pull request #5624 done by [Mergify](https://mergify.io).
Cherry-pick of 91fa57617b9055e0e85caf2eede5c6ad60655259

[7.14] chore: use withMageEnv step (backport #5624)

---

changelogs/7.13.asciidoc

docs: add 7.13.4 release notes

---

cmd/version.go

Update to version 7.13.5

---

docs/guide/opentelemetry-elastic.asciidoc

I added instructions similar to Cyrille's describing the Node.js Lambda setup.

Added AWS Lambda Node.js instructions

---

docs/guide/opentelemetry-elastic.asciidoc

- Added AWS Lambda Node.js instructions (#5780)

[master] Added AWS Lambda Node.js instructions (#5780)

---

NOTICE.txt
go.mod
go.sum

Update with libbeat and beats packaging.

[automation] update libbeat and beats packaging

---

docs/apm-package/apm-input-settings.asciidoc
docs/apm-package/input-apm.asciidoc
docs/configuration-anonymous.asciidoc
docs/configuration-rum.asciidoc
docs/configuring.asciidoc
docs/data-ingestion.asciidoc
docs/secure-communication-agents.asciidoc

Adds documentation for anonymous authentication for both APM Server standalone and the APM integration.
* New [Anonymous authentication config](https://apm-server_5930.docs-preview.app.elstc.co/guide/en/apm/server/master/configuration-anonymous.html)
* Updated [RUM config](https://apm-server_5930.docs-preview.app.elstc.co/guide/en/apm/server/master/configuration-rum.html)
* Paragraph in [Secure communication with APM agents](https://apm-server_5930.docs-preview.app.elstc.co/guide/en/apm/server/master/secure-communication-agents.html)
* Updated [APM input settings](https://apm-server_5930.docs-preview.app.elstc.co/guide/en/apm/server/master/input-apm.html)
* Agent configuration docs updated in https://github.com/elastic/kibana/pull/108285.
Closes …

docs: Anonymous authentication

---

docs/apm-package/apm-input-settings.asciidoc
docs/apm-package/input-apm.asciidoc
docs/configuration-anonymous.asciidoc
docs/configuration-rum.asciidoc
docs/configuring.asciidoc
docs/data-ingestion.asciidoc
docs/secure-communication-agents.asciidoc

- docs: Anonymous authentication (#5930)

[7.x] docs: Anonymous authentication (#5930)

---

.mergify.yml

Update the backport behavior to backport to `7.15`.

Update mergify to 7.15

---

NOTICE.txt
go.mod
go.sum

update beats after the version bump

[7.15] update beats

---

systemtest/approvals/TestRUMXForwardedFor.approved.json

Update system test approval due to geoIP change.
None

systemtest: fix approval due to geoIP change

---

NOTICE.txt
go.mod
go.sum

Closes https://github.com/elastic/apm-server/issues/6068

Update to elastic/beats@35665f93fa06

---

cmd/version.go

bump version to 7.14.2

---

NOTICE.txt
go.mod
go.sum

Update to elastic/beats@7feae9e117c3

---

docker-compose.yml

[start_time:Mon, 13 Sep 2021 00:25:00 GMT, release_branch:master, prefix:, end_time:Mon, 13 Sep 2021 06:50:17 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-64718381, build_duration_seconds:23117]

[automation] update elastic stack version for testing 8.0.0-64718381

---

apmpackage/apm/README.template.md
apmpackage/apm/docs/README.md
apmpackage/apm/manifest.yml

Switch from `experimental` to `beta` in alignment with the APM UI.

Move from experimental to beta for apmpackage 0.4.0

---

docker-compose.yml

[start_time:Mon, 20 Sep 2021 19:26:05 GMT, release_branch:master, prefix:, end_time:Tue, 21 Sep 2021 01:32:40 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:master, build_id:8.0.0-c8bb0791, build_duration_seconds:21995]

[automation] update elastic stack version for testing 8.0.0-c8bb0791

---

changelogs/7.14.asciidoc

- docs: 7.14.2 release notes (#6195)

[7.15] docs: 7.14.2 release notes (#6195)

---

changelogs/6.8.asciidoc

- docs: 6.8.19 release notes (#6194) (#6209)

[master] docs: 6.8.19 release notes (#6194) (#6209)

---

systemtest/approvals/TestCompressedSpans.approved.json
systemtest/go.mod
systemtest/huge_traces_test.go

Adds a new test which asserts that compressed spans are received by the
`apm-server`.

systemtest: Add `TestCompressedSpans` test

---

changelogs/7.0.asciidoc
docs/legacy/breaking-changes.asciidoc

For https://github.com/elastic/observability-docs/issues/1073.

docs: final link fixes

---

apmpackage/apm/changelog.yml
apmpackage/apm/manifest.yml

update apmpackage version so we can release to snapshot/staging
non-functional change
https://github.com/elastic/obs-dc-team/issues/629#issue-1043900691

update apmpackage version

---

beater/beater.go

Pass an `elasticsearch.Client` constructor into the modelindexer constructor, to ensure it gets a client which blocks until the integration is ready.
1. Run apm-server with `-E output.elasticsearch.experimental=true -E apm-server.data_streams.enabled=true`
2. Make sure the integration is _not_ installed, remove all APM index templates
3. Send some events
4. No events should be indexed
5. Install integration
6. Send more events
7. Events should be indexed
https://github.com/elastic/apm-server/issues/6360

beater: ensure modelindexer waits for integration

---

docs/sourcemap-api.asciidoc

Our APM Engineering explained the logic of source map abs_path matching: 
abs_path will match based on the following: 
1. bundle_filepath="http://localhost/static/js/bundle.js" // having full URL matching, if it's not the case, then move to step 2) 
2. bundle_filepath="/static/js/bundle.js" // only the path without URL part, if it's not the case then source map will not be applied correctly

Update RUM source map absolute path logic

---

apmpackage/apm/changelog.yml
apmpackage/apm/manifest.yml
cmd/version.go

[7.16] Bump version to `7.16.1`

---

cmd/version.go

Bump version to 7.16.2

---

changelogs/7.16.asciidoc

* Add 7.16.1 release notes
* Add GA note to 7.16.0 release notes

docs: add 7.16.1 release notes

---

changelogs/6.8.asciidoc
changelogs/7.16.asciidoc

Release notes were already published to current documentation in https://github.com/elastic/apm-server/pull/6875 and https://github.com/elastic/apm-server/pull/6874. This PR cherry-picks the changes to master and provides an opportunity for the dev team to ensure everything looks good. If I made an error, let me know :)

docs: 7.16.1 and 6.8.21 release notes

---

beater/config/aggregation_test.go
beater/config/helper.go
beater/config/helper_test.go
beater/jaeger/server_test.go
beater/otlp/grpc_test.go
beater/server_test.go
systemtest/jaeger_test.go
systemtest/logging_test.go

[7.17] fix linter deprecations

---

changelogs/6.8.asciidoc
changelogs/7.16.asciidoc

Backports the following commits to 7.17:
- Cherry pick release notes (#6897)

[7.17] Cherry pick release notes (#6897)

---

.ci/check-packages.groovy

Update the version used in the packaging job.

7.16 packages

---

NOTICE.txt

Updates the `notice.txt` file to the current year so the CI checks pass.
N/A
N/A

notice: Update notice to 2022

---

docker-compose.yml

[7.16] Update stack to `7.16.3-980486b6-SNAPSHOT`

---

apmpackage/README.md

Update apmpackage dev docs to match current reality.

apmpackage: update instruction in README

---

changelogs/6.8.asciidoc
changelogs/7.16.asciidoc
changelogs/8.0.asciidoc
changelogs/head.asciidoc

Adds release notes:
I'll backport this manually since I added everything in one commit.

docs: add release notes

---

apmpackage/apm/_dev/build/docs/README.md

Updates the APM integration readme and removes old limitations that do
not apply anymore.
N/A
Closes #7069

integration: Update README

---

systemtest/containers.go

I think at some point in the past there was a separate image for fleet-server, and we separately pulled the elastic-agent image. Fleet-server now (at least) runs under elastic-agent, so we can use the exact same image and avoid a network trip.
This should help to reduce intermittent failures due to docker.elastic.co availability, or other network issues. Ideally, after running `docker-compose up` the system tests should pass without an internet connection.

systemtest: don't pull elastic-agent image

---

apmpackage/apm/manifest.yml
systemtest/kibana.go

Add defaults to the apmpackage for TBS

apmpackage: set default values for tbs

---

NOTICE.txt
go.mod
go.sum
systemtest/go.mod
systemtest/go.sum

Update indirect dependency on `containerd` to `1.5.9`. 
no manual testing required; dependabot alert should go away after merging this

Fix containerd vulnerabilities by updating to newer version

---

Makefile

Update the update-beats branch to 8.1.

Makefile: fix 8.1 beats branch

---

docker-compose.yml
testing/docker/kibana/kibana.yml

Cherry pick c0758bf1866fc55b1d928a5d667813bf3e85d190 from main to 8.1.

[8.1] preconfigure fleet-server policy

---

apmpackage/apm/changelog.yml
cmd/version.go

8.0.1 version update

---

.ci/update-beats.groovy

Proactively sent a notification when something bad happening with the update-beats automation. Notify when the update-beats automation created a Pull Request (maybe this is not needed...)

ci: notify update status by email/slack

---

apmpackage/cmd/genpackage/pipelines.go
systemtest/ingest_test.go

Don't overwrite `transaction.duration.us` or `span.duration.us` if they are set, as otherwise old versions of APM Server cannot send events to newer versions of the ingest pipeline, which is expected to happen.
1. Install the integration
2. Run APM Server 8.1.0 (i.e. an older version which sets the `<event>.duration.us` fields directly), send some events
3. Check that the events are indexed with non-zero durations
None. apm-integration-testing has been failing on 8.0 and 8.1 branches, …

ingest: don't overwrite <event>.duration.us

---

Makefile

We're moving the responsibility of building this from release-manager to APM Server's CI.
N/A
None

Makefile: build dependencies.csv

---

NOTICE.txt
beater/auth/apikey_test.go
beater/auth/authenticator_test.go
beater/beater_test.go
beater/checkintegration.go
elasticsearch/bulk.go
elasticsearch/client.go
go.mod
go.sum
model/modelindexer/indexer.go
model/modelindexer/indexer_test.go
sourcemap/elasticsearch_test.go
x-pack/apm-server/sampling/pubsub/pubsub_test.go
x-pack/apm-server/sampling/pubsub/pubsubtest/client.go

Update go-elasticsearch dependency to current `8.1` branch https://github.com/elastic/go-elasticsearch/commit/bc3eb8ef52eac56170cfab53c6074a9714e0d376
This requires some code changes, that have been introduced to `main` in https://github.com/elastic/apm-server/pull/7156/ but not be backported.

[8.1] update go elasticsearch

---

apmpackage/apm/changelog.yml
cmd/version.go

version bump 8.0.1->8.0.2

---

changelogs/8.0.asciidoc

docs: Remove coming tag for 8.0.1

---

go.mod
go.sum
systemtest/go.mod
systemtest/go.sum

Make Dependabot be quiet. (The issues don't affect APM Server production code.)
N/A
None

Update module deps

---

apmpackage/apm/changelog.yml
cmd/version.go

Bump 8.1.2

---

magefile.go

See https://github.com/elastic/beats/pull/29585

Update magefile for universal Darwin binaries

---

docs/aws-lambda-extension.asciidoc

* For https://github.com/elastic/apm-aws-lambda/pull/158.
* Requires https://github.com/elastic/apm-aws-lambda/pull/160/files

docs: update aws-lambda-extension.asciidoc

---

.mergify.yml

Updates the mergify configuration for `8.2`.

release: Add 8.2 backport configuration

---

Makefile
NOTICE.txt
go.mod
go.sum

Updates the Makefile beats branches and ran `make update-beats`

[8.2] Update to elastic/beats@5bc07ca71cf7

---

changelogs/8.1.asciidoc

Move the gzip writer fix to the correct category.

8.1.2 release notes: fix category

---

apmpackage/apm/changelog.yml
cmd/version.go

Bump 8.1.3

---

.ci/packaging.groovy

Prepare the dependencies file for staging

dra: prepare staging

---

docker-compose.yml

[start_time:Mon, 11 Apr 2022 12:19:48 GMT, release_branch:master, prefix:, end_time:Mon, 11 Apr 2022 17:10:40 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-2c8f9574, build_duration_seconds:17452]

[automation] update elastic stack version for testing 8.3.0-2c8f9574

---

changelogs/8.1.asciidoc

Adds the release notes for the upcoming 8.1.3 release.

[8.1] Add `8.1.3` release notes

---

docker-compose.yml

[start_time:Fri, 15 Apr 2022 00:14:33 GMT, release_branch:master, prefix:, end_time:Fri, 15 Apr 2022 04:50:37 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-55ba6f37, build_duration_seconds:16564]

[automation] update elastic stack version for testing 8.3.0-55ba6f37

---

docs/open-telemetry.asciidoc

Changed the URL to point at v0.24 instead of 0.23

Updated link to the new tag with the update

---

apmpackage/apm/changelog.yml
cmd/version.go

bump version to 8.1.4

---

apmpackage/apm/changelog.yml
apmpackage/apm/manifest.yml
cmd/version.go

bump version to 7.17.4

---

CHANGELOG.asciidoc
changelogs/8.2.asciidoc
changelogs/head.asciidoc
docs/apm-breaking.asciidoc

Adds 8.2.0 release notes and breaking changes.

docs: 8.2.0 release notes

---

apmpackage/apm/changelog.yml
cmd/intake-receiver/version.go
cmd/version.go

8.2.1 version bump

---

.mergify.yml

Attempt to fix auto-merges for beats-update PRs

mergify: Attempt auto-merge fix for beats-update

---

systemtest/huge_traces_test.go

results are coming back in a random order, so sort
them before comparing to the stored approved
result.
closes #7114
```
make build-package
docker-compose up -d
cd systemtests
go test -v -run TestCompressedSpans -failfast -count=100
```

sort results for TestCompressedSpans

---

docker-compose.yml

[start_time:Thu, 12 May 2022 12:14:39 GMT, release_branch:master, prefix:, end_time:Thu, 12 May 2022 20:54:06 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-b85385ff, build_duration_seconds:31167]

[automation] update elastic stack version for testing 8.3.0-b85385ff

---

docker-compose.yml

[start_time:Thu, 19 May 2022 00:14:06 GMT, release_branch:master, prefix:, end_time:Thu, 19 May 2022 04:19:11 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-a55286cc, build_duration_seconds:14705]

[automation] update elastic stack version for testing 8.3.0-a55286cc

---

changelogs/7.17.asciidoc

Adds release notes for 7.17.4.

docs: 7.17.4 release notes

---

apmpackage/apm/changelog.yml
apmpackage/apm/manifest.yml
cmd/version.go

[7.17] release: Bump version to `7.17.5`

---

apmpackage/apm/changelog.yml
cmd/intake-receiver/version.go
cmd/version.go

[8.2] release: Bump version to 8.2.3

---

dev_docs/trace_metrics.md

Add developer docs describing trace metrics aggregation.
N/A
Closes #7647

dev_docs: add trace metrics aggregation

---

docker-compose.yml

[start_time:Tue, 7 Jun 2022 00:16:17 GMT, release_branch:master, prefix:, end_time:Tue, 7 Jun 2022 04:21:27 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-b8fce3f8, build_duration_seconds:14710]

[automation] update elastic stack version for testing 8.4.0-b8fce3f8

---

docker-compose.yml

[start_time:Fri, 10 Jun 2022 00:15:24 GMT, release_branch:master, prefix:, end_time:Fri, 10 Jun 2022 04:45:28 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-a27cbcfa, build_duration_seconds:16204]

[automation] update elastic stack version for testing 8.4.0-a27cbcfa

---

docker-compose.yml

[start_time:Mon, 13 Jun 2022 00:14:44 GMT, release_branch:8.3, prefix:, end_time:Mon, 13 Jun 2022 04:40:53 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-db012561, build_duration_seconds:15969]

[automation] update elastic stack version for testing 8.3.0-db012561

---

docker-compose.yml

[start_time:Mon, 13 Jun 2022 00:14:14 GMT, release_branch:master, prefix:, end_time:Mon, 13 Jun 2022 04:20:05 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-3bedeef4, build_duration_seconds:14751]

[automation] update elastic stack version for testing 8.4.0-3bedeef4

---

docker-compose.yml

[start_time:Wed, 15 Jun 2022 00:13:58 GMT, release_branch:master, prefix:, end_time:Wed, 15 Jun 2022 04:40:55 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-40cff009, build_duration_seconds:16017]

[automation] update elastic stack version for testing 8.4.0-40cff009

---

docker-compose.yml

[start_time:Wed, 15 Jun 2022 12:14:33 GMT, release_branch:8.3, prefix:, end_time:Wed, 15 Jun 2022 16:52:58 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-fe62331f, build_duration_seconds:16705]

[automation] update elastic stack version for testing 8.3.0-fe62331f

---

docker-compose.yml

[start_time:Thu, 16 Jun 2022 00:14:47 GMT, release_branch:master, prefix:, end_time:Thu, 16 Jun 2022 04:24:56 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-5e6770b1, build_duration_seconds:15009]

[automation] update elastic stack version for testing 8.4.0-5e6770b1

---

docker-compose.yml

[start_time:Mon, 20 Jun 2022 00:14:27 GMT, release_branch:master, prefix:, end_time:Mon, 20 Jun 2022 04:17:38 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-b13123ee, build_duration_seconds:14591]

[automation] update elastic stack version for testing 8.4.0-b13123ee

---

Makefile

Enable build for arm64 arch
Run `make` on arm64

Build apm-server binary for darwin/arm64

---

docs/upgrading-to-8.x.asciidoc

* For https://github.com/elastic/apm-server/issues/8252.

docs: Fix "upgrade" bug

---

docker-compose.yml

[start_time:Thu, 23 Jun 2022 12:14:12 GMT, release_branch:master, prefix:, end_time:Thu, 23 Jun 2022 16:35:54 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-722a7d79, build_duration_seconds:15702]

[automation] update elastic stack version for testing 8.4.0-722a7d79

---

changelogs/7.17.asciidoc

[7.17] docs: add 7.17.5 release notes

---

docker-compose.yml

[start_time:Fri, 24 Jun 2022 12:15:00 GMT, release_branch:master, prefix:, end_time:Fri, 24 Jun 2022 16:42:38 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-210dd487, build_duration_seconds:16058]

[automation] update elastic stack version for testing 8.4.0-210dd487

---

apmpackage/apm/changelog.yml
apmpackage/apm/manifest.yml
cmd/version.go

bump version to 7.17.6

---

docker-compose.yml

[start_time:Thu, 30 Jun 2022 12:14:14 GMT, release_branch:master, prefix:, end_time:Thu, 30 Jun 2022 16:33:00 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-3d206b5d, build_duration_seconds:15526]

[automation] update elastic stack version for testing 8.4.0-3d206b5d

---

apmpackage/apm/changelog.yml
cmd/intake-receiver/version.go
cmd/version.go

[8.3] Bump version to 8.3.2

---

docker-compose.yml

[start_time:Mon, 4 Jul 2022 00:15:23 GMT, release_branch:master, prefix:, end_time:Mon, 4 Jul 2022 04:37:22 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-3ad82aa8, build_duration_seconds:15719]

[automation] update elastic stack version for testing 8.4.0-3ad82aa8

---

docker-compose.yml

[start_time:Mon, 4 Jul 2022 12:16:14 GMT, release_branch:master, prefix:, end_time:Mon, 4 Jul 2022 17:02:59 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-03bd6f3f, build_duration_seconds:17205]

[automation] update elastic stack version for testing 8.4.0-03bd6f3f

---

docker-compose.yml

[start_time:Tue, 5 Jul 2022 12:17:52 GMT, release_branch:master, prefix:, end_time:Tue, 5 Jul 2022 17:41:38 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-533f1e30, build_duration_seconds:19426]

[automation] update elastic stack version for testing 8.4.0-533f1e30

---

changelogs/8.3.asciidoc
changelogs/head.asciidoc

Adds 8.3.1 release notes. Mention the introduced TBS storage limit fix.

docs: add 8.3.2 release notes

---

docker-compose.yml

[start_time:Wed, 6 Jul 2022 00:15:11 GMT, release_branch:master, prefix:, end_time:Wed, 6 Jul 2022 05:19:25 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-d0a4da44, build_duration_seconds:18254]

[automation] update elastic stack version for testing 8.4.0-d0a4da44

---

docker-compose.yml

[start_time:Mon, 11 Jul 2022 00:15:20 GMT, release_branch:8.3, prefix:, end_time:Mon, 11 Jul 2022 04:59:34 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-385d4fdb, build_duration_seconds:17054]

[automation] update elastic stack version for testing 8.3.3-385d4fdb

---

docker-compose.yml

[start_time:Sun, 10 Jul 2022 12:14:29 GMT, release_branch:master, prefix:, end_time:Sun, 10 Jul 2022 16:52:30 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-dd98ded4, build_duration_seconds:16681]

[automation] update elastic stack version for testing 8.4.0-dd98ded4

---

docker-compose.yml

[start_time:Mon, 11 Jul 2022 12:15:42 GMT, release_branch:master, prefix:, end_time:Mon, 11 Jul 2022 16:53:35 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-164d9a10, build_duration_seconds:16673]

[automation] update elastic stack version for testing 8.4.0-164d9a10

---

docker-compose.yml

[start_time:Tue, 12 Jul 2022 12:14:45 GMT, release_branch:master, prefix:, end_time:Tue, 12 Jul 2022 16:51:42 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-00048b66, build_duration_seconds:16617]

[automation] update elastic stack version for testing 8.4.0-00048b66

---

docker-compose.yml

[start_time:Thu, 14 Jul 2022 00:14:48 GMT, release_branch:8.3, prefix:, end_time:Thu, 14 Jul 2022 04:31:09 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-fba30f71, build_duration_seconds:15381]

[automation] update elastic stack version for testing 8.3.3-fba30f71

---

docker-compose.yml

[start_time:Fri, 15 Jul 2022 00:14:35 GMT, release_branch:master, prefix:, end_time:Fri, 15 Jul 2022 04:54:08 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-3cd57abb, build_duration_seconds:16773]

[automation] update elastic stack version for testing 8.4.0-3cd57abb

---

docker-compose.yml

[start_time:Thu, 14 Jul 2022 12:18:37 GMT, release_branch:8.3, prefix:, end_time:Thu, 14 Jul 2022 17:06:49 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-f93ba5f4, build_duration_seconds:17292]

[automation] update elastic stack version for testing 8.3.3-f93ba5f4

---

.ci/smoke-tests.groovy

Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
* Run the following [Jenkins job](https://apm-ci.elastic.co/job/apm-server/job/smoke-tests-mbp/view/change-requests/job/PR-8682/) with `6.8` as version.
* Validate the failure report in the slack channel.
* Run the following [Jenkins job](https://apm-ci.elastic.co/job/apm-server/job/smoke-tests-mbp/view/change-requests/job/PR-8682/) with `latest` as version.
* Validate that no reported failure is present in the slack channel. …

Add failure report for smoketests

---

.mergify.yml
apmpackage/apm/changelog.yml
cmd/intake-receiver/version.go
internal/version/version.go

bump version to `8.5` after setting up the `8.4` branch

bump version to 8.5

---

docker-compose.yml

[start_time:Wed, 27 Jul 2022 07:02:31 GMT, release_branch:master, prefix:, end_time:Wed, 27 Jul 2022 12:07:51 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-60171339, build_duration_seconds:18320]

[automation] update elastic stack version for testing 8.4.0-60171339

---

docker-compose.yml

[start_time:Wed, 27 Jul 2022 07:09:19 GMT, release_branch:8.3, prefix:, end_time:Wed, 27 Jul 2022 13:37:37 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-8631d33c, build_duration_seconds:23298]

[automation] update elastic stack version for testing 8.3.3-8631d33c

---

apmpackage/apm/changelog.yml
cmd/intake-receiver/version.go
cmd/version.go

bump version to 8.3.4

---

docker-compose.yml

[start_time:Wed, 3 Aug 2022 00:15:44 GMT, release_branch:8.3, prefix:, end_time:Wed, 3 Aug 2022 04:54:02 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-a15c6beb, build_duration_seconds:16698]

[automation] update elastic stack version for testing 8.3.4-a15c6beb

---

.ci/scripts/check-beats-version.sh

Should be BRANCH_NAME, not BRANCH_VERSION.

.ci: fix check-beats-version

---

docker-compose.yml

[start_time:Wed, 10 Aug 2022 12:15:43 GMT, release_branch:8.4, prefix:, end_time:Wed, 10 Aug 2022 17:19:16 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-c17572db, build_duration_seconds:18213]

[automation] update elastic stack version for testing 8.4.0-c17572db

---

Makefile

The module may not exist on disk at the time the variable is evaluated, so defer fetching the beats directory until after downloading the module.

Defer beats directory evaluation

---

docker-compose.yml

[start_time:Tue, 16 Aug 2022 12:15:36 GMT, release_branch:8.4, prefix:, end_time:Tue, 16 Aug 2022 19:17:51 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-aff0df12, build_duration_seconds:25335]

[automation] update elastic stack version for testing 8.4.0-aff0df12

---

docker-compose.yml

[start_time:Wed, 17 Aug 2022 12:16:21 GMT, release_branch:8.3, prefix:, end_time:Wed, 17 Aug 2022 17:48:01 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-e23a59c6, build_duration_seconds:19900]

[automation] update elastic stack version for testing 8.3.4-e23a59c6

---

changelogs/8.4.asciidoc
docs/release-notes.asciidoc

A small collection of fixes to the 8.4 release notes. No content changes so I'll ping obs-docs for review. If an APM dev sees this though, feel free to drop in 😄.

docs: update 8.4 release notes

---

apmpackage/apm/changelog.yml
cmd/intake-receiver/version.go
internal/version/version.go

Prepare for the release of 8.4.0 (to be merged post release)

Bump version to 8.4.1

---

apmpackage/apm/changelog.yml
cmd/intake-receiver/version.go
internal/version/version.go

bump version to 8.4.2

---

TESTING.md

- Add a brief mention of how to build the apm-server binary, using `make` and using `go build` directly
- Replace deprecated `benchcmp` example with `benchstat`
- Remove mentions of hey-apm

TESTING.md: add mention of how to build

---

internal/processor/otel/metrics_test.go

The `TestConsumeMetrics` test is intermittently failing due to the comparison function being incomplete, causing sort order to be non-deterministic.
`cd internal/processor/otel && go test -v -run ConsumeMetrics\$ -failfast -count=100`
None

Fix cmpopts.SortSlices function

---

x-pack/apm-server/profiling/collector.go

We'd like to have data to introspect the ingestion of profiling documents into Elasticsearch via the Bulk Indexer.
Some logging failure messages have been enriched to speed up investigation, and metrics have been added to calculate the error rate of ingested documents per data type.
- Is it observable through the addition of either **logging** or **metrics**? ✅ 
Start the local stack with `docker-compose up -d`, run APM locally with `systemtest/cmd/runapm` and see the metrics in the `metrics-*` data view
#9005

metrics to introspect profiling collection

---

docker-compose.yml

[start_time:Thu, 15 Sep 2022 00:16:21 GMT, release_branch:8.4, prefix:, end_time:Thu, 15 Sep 2022 04:55:32 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-36096067, build_duration_seconds:16751]

[automation] update elastic stack version for testing 8.4.2-36096067

---

testing/benchmark/README.md

Removed unnecessary slack reporting docs

chore: benchmarks: remove slar reporting docs

---

apmpackage/apm/changelog.yml
cmd/intake-receiver/version.go
internal/version/version.go

Prepare for the release of 8.4.2

Bump version to 8.4.3

---

systemtest/approvals/TestServiceMetricsAggregation.approved.json
x-pack/apm-server/aggregation/servicemetrics/aggregator.go
x-pack/apm-server/aggregation/servicemetrics/aggregator_test.go

This to ensure proper bucket counts as discovered on
https://github.com/elastic/kibana/pull/140868

Add _doc_count to Service metrics

---

docker-compose.yml

[start_time:Tue, 20 Sep 2022 22:44:15 GMT, release_branch:8.4, prefix:, end_time:Wed, 21 Sep 2022 03:19:03 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-c8bcc0ff, build_duration_seconds:16488]

[automation] update elastic stack version for testing 8.4.3-c8bcc0ff

---

apmpackage/apm/changelog.yml
cmd/intake-receiver/version.go
internal/version/version.go

bump version to 8.6.0

---

docker-compose.yml

[start_time:Thu, 22 Sep 2022 00:16:04 GMT, release_branch:8.4, prefix:, end_time:Thu, 22 Sep 2022 04:44:16 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-72a0900d, build_duration_seconds:16092]

[automation] update elastic stack version for testing 8.4.3-72a0900d

---

internal/beater/otlp/clientmetadata.go
internal/beater/otlp/clientmetadata_test.go

Adds the android agent to the logic of setting client IP in client metadata.

Added android for client IP mapping

---

docker-compose.yml

[start_time:Sun, 25 Sep 2022 12:16:28 GMT, release_branch:8.4, prefix:, end_time:Sun, 25 Sep 2022 17:07:38 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-f2e1ac46, build_duration_seconds:17470]

[automation] update elastic stack version for testing 8.4.3-f2e1ac46

---

systemtest/profiling_test.go

Fixes #9266 
- Is it observable through the addition of either **logging** or **metrics**? N/A
- Is its use being published in **telemetry** to enable product improvement? N/A
- Have system tests been added to avoid regression? ✅ 
You can run the previously failing test with 
```
go test -v  -run '^TestProfiling$' ./...
```
#9266 #9244

test: improve Profiling, wait for gRPC server to be up

---

docker-compose.yml

[start_time:Thu, 6 Oct 2022 12:15:40 GMT, release_branch:8.4, prefix:, end_time:Thu, 6 Oct 2022 17:02:10 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-ac374c4b, build_duration_seconds:17190]

[automation] update elastic stack version for testing 8.4.4-ac374c4b

---

docker-compose.yml

[start_time:Mon, 10 Oct 2022 12:16:20 GMT, release_branch:8.4, prefix:, end_time:Mon, 10 Oct 2022 17:57:12 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-221d2ff4, build_duration_seconds:20452]

[automation] update elastic stack version for testing 8.4.4-221d2ff4

---

CHANGELOG.asciidoc
docs/release-notes.asciidoc

Follow up to https://github.com/elastic/apm-server/pull/9171.

docs: add 8.5 release notes link and include statement

---

docker-compose.yml

[start_time:Thu, 13 Oct 2022 12:16:41 GMT, release_branch:8.4, prefix:, end_time:Thu, 13 Oct 2022 17:40:37 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-fdf1902b, build_duration_seconds:19436]

[automation] update elastic stack version for testing 8.4.4-fdf1902b

---

internal/model/modelindexer/indexer.go
internal/model/modelindexer/indexer_test.go

Remove all mutexes from `ProcessBatch`, making it impossible for `ProcessBatch` to block `Close`. Now if `Close` is called while `ProcessBatch` is blocked waiting to enqueue an item, `ProcessBatch` will return `ErrClosed`.
N/A
None

modelindexer: don't allow Close to be blocked

---

apmpackage/apm/changelog.yml
apmpackage/apm/manifest.yml
cmd/version.go

bump version to 7.17.8

---

.ci/bump-stack-version.sh

Don't just sed them, commit them.

.ci: commit k8s changes in bump-stack-version

---

docs/common-problems.asciidoc

Updates doc link to match changes in https://github.com/elastic/observability-docs/pull/2334. 
https://github.com/elastic/observability-docs/pull/2334

[docs] Update link to agent monitoring docs

---

.github/ISSUE_TEMPLATE/test-plan.md
dev_docs/RELEASES.md

Make the manual plan test issue creation a bit more streamlined

github: Add test plan template issue

---

.ci/benchmarks.groovy
.ci/scripts/download-png-from-kibana.sh

Version parameter was mistakenly removed from PNG POST URL 
Now it's back and the post URL job params are now clear

Benchmark CI: Returned version parameter to PNG POST URL

---

systemtest/approvals.go
systemtest/approvals/TestIngestPipelineDataStreamMigration.approved.json

Fixes flaky test
N/A
Closes #9579

systemtest: Fix `TestTransactionAggregation` test

---

testing/benchmark/main.tf

benchmark: Fix merge tags source

---

apmpackage/apm/changelog.yml
cmd/intake-receiver/version.go
internal/version/version.go

bump version to 8.5.3

---

changelogs/8.5.asciidoc

It looks like one more bug fix made it into the 8.5.2 release. This PR updates the release notes.

Add bugfix to 8.5.2 release notes

---

changelogs/8.5.asciidoc

Adds the 8.5.3 release notes. There is only one notable commit.
This PR should be cherrypicked to main and backported after merging.

[8.5] docs: 8.5.3 release notes

---

x-pack/apm-server/main.go

From 16MB to 4MB. This not only reduces memory usage spikes (from >1GB to <350MB in my most heavy testing push-symbols workload) but results in faster overall processing and smoother operation.
This configuration change is synergistic with go-elasticsearch memory leak fixes that will be part of the `8.6.0` release.

Universal Profiling: Reduce go-elasticsearch per-worker buffer size

---

.gitattributes
.gitignore
Makefile
dev_docs/otel.md
packaging/docker/Dockerfile

Fixes some fallout from removing internal/otel_collector.

Remove dangling refs to internal/otel_collector

---

changelogs/8.6.asciidoc
changelogs/head.asciidoc

- Adds changelog for 8.6
- Updates current changelog (for 8.7) with the relevant PRs

Add changelog for 8.6 and update recent changelog

---

Makefile
apm-server.yml
dev_docs/TESTING.md
docs/apm-input-settings.asciidoc
docs/legacy/guide/docker-compose.yml
internal/beater/config/config.go
packaging/docker/Dockerfile
packaging/ironbank/Dockerfile
systemtest/cmd/sendotlp/main.go
systemtest/loadgen/config/config.go
testing/apmsoak/terraform.tfvars.example
testing/stack-monitoring.sh

Closes https://github.com/elastic/apm-server/issues/9749

feat: change APM Server default host to 127.0.0.1

---

Makefile
testing/smoke/lib.sh

smoke: Fix failing tests on CI

---

packaging/ironbank/Dockerfile
packaging/ironbank/hardening_manifest.yaml

Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
* Update ironbank base image to ubi 8.7

Update ironbank base image to ubi 8.7

---

systemtest/aggregation_test.go
systemtest/jaeger_test.go

systemtest: Fix `TestJaegerGRPCMuxed` flaky tests

---

apmpackage/apm/changelog.yml
cmd/intake-receiver/version.go
internal/version/version.go

8.6 version bump

---

internal/beater/checkintegration.go

Adds check of `service_destination` and `service` aggregation templates while checking for installed integration during pre-condition check.
APM-Server should be able to startup and ingest data correctly.
#9926 and #9960

Update precondition check to include all index templates

---

internal/agentcfg/kibana.go
internal/agentcfg/kibana_test.go
internal/beater/api/config/agent/handler_test.go
internal/beater/server.go

Closes https://github.com/elastic/apm-server/issues/9929

refactor: fix agentcfg kibana fetcher panic on nil client

---

internal/agentcfg/elasticsearch.go

Rate limit agentcfg per-request logging to avoid spamming the logs
N/A
N/A

Rate limit agentcfg per-request logging

---

changelogs/8.6.asciidoc
cmd/intake-receiver/version.go
internal/version/version.go

- version bump
- add changelog entry for bugfix

8.6 bump version

---

changelogs/8.6.asciidoc

update 8.6.1 changelog

---

systemtest/sampling_test.go

newAPMIntegration is taking a huge amount of time. If need more than one we can create them in parallel to reduce test time.
TestTailSampling time went from 62s to 37s

test: create apmintegration in parallel in TestTailSampling

---

changelogs/7.17.asciidoc

7.17.9 release notes

---

systemtest/aggregation_test.go

Add system test for non-default rollup interval hidden data stream
N/A
N/A
Closes #10093

systemtest: Add test for hidden data stream

---

x-pack/apm-server/aggregation/servicesummarymetrics/aggregator.go
x-pack/apm-server/aggregation/servicetxmetrics/aggregator.go
x-pack/apm-server/aggregation/spanmetrics/aggregator.go
x-pack/apm-server/aggregation/txmetrics/aggregator.go
x-pack/apm-server/main.go

Ensure that aggregator comments are up to date and consistent

Update names and comments for aggregations

---

x-pack/apm-server/aggregation/txmetrics/aggregator.go

maxGroups and maxServices will be different by default since #10157
N/A
N/A
Follow up on #10157

Fix txmetrics space make size

---

CHANGELOG.asciidoc
changelogs/8.7.asciidoc
docs/release-notes.asciidoc

Update changelog for 8.7 release (#10186)

---

.ci/bump-elastic-stack-snapshot.yml

required for mergify, so it can merge automatically

updatecli: use automation label

---

changelogs/8.6.asciidoc
cmd/intake-receiver/version.go
internal/version/version.go

- bump versoin
- add changelog entry for bugfix:  #10247

bump version to 8.6.3

---

testing/smoke/supported-os/main.tf
testing/smoke/supported-os/test.sh

Closes https://github.com/elastic/apm-server/issues/9717

feat: add support for rhel 9

---

docs/data/elasticsearch/generated/errors.json
docs/data/elasticsearch/generated/transactions.json
tests/system/error.approved.json
tests/system/transaction.approved.json

CI is failing and new PRs can't be merged.
Update approved documents to fix failing test.

test: update approved documents and fix integration tests

---

systemtest/elasticsearch.go

https://github.com/elastic/apm-server/pull/10228 was automerged even though the lint job failed. 
Fix linter issues

lint: solve linter issues

---

changelogs/8.7.asciidoc

Group the many changes that have been made related to aggregation metrics into dedicated subsections for better readability. 
closes https://github.com/elastic/apm-server/issues/10223

docs: Group aggregation metric changes into subsections

---

testing/apmsoak/main.tf
testing/apmsoak/variables.tf
testing/infra/terraform/modules/soaktest_workers/README.md
testing/infra/terraform/modules/soaktest_workers/main.tf
testing/infra/terraform/modules/soaktest_workers/systemd.tpl
testing/infra/terraform/modules/soaktest_workers/variables.tf

Update apmsoak configs to use recently introduced flags

apmsoak: update configs with new flags

---

docs/apm-breaking.asciidoc

Use more asserting language to avoid concerning users.

docs: be more assertive about new ES output

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/fleet-server.yaml
testing/infra/k8s/base/stack/kibana.yaml
testing/infra/k8s/overlays/local/kustomization.yaml

<Actions>
<action id="3ef71a06b617bc3234991cb182d3b7e1de6d4a24cf94340479262ec939ded95a">
</details>
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.7.1-e95716f1

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/fleet-server.yaml
testing/infra/k8s/base/stack/kibana.yaml
testing/infra/k8s/overlays/local/kustomization.yaml

<Actions>
<action id="e28bf3abefd752471f88ab1e4c66b670cea263da9646eccf8206c8908c2450b1">
</details>
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.7.1-1bebafa7

---

CHANGELOG.asciidoc
changelogs/8.7.asciidoc
changelogs/8.8.asciidoc
changelogs/head.asciidoc
docs/release-notes.asciidoc

Updated changelogs for 8.8 release.

Update changelog for 8.8 release

---

changelogs/7.17.asciidoc

Adds a section for the upcoming `7.17.10` release.

Add 7.17.10 changelog entry

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.0-00fd5dad
---
<Actions>
<action id="3630dfb2b597981389e4d2665a2ab4d653701ebfacaaf75467867d026f565481">
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.8.0-00fd5dad

---

.github/workflows/terraform-fmt.yml
testing/rally-cloud/main.tf

Following this comment: https://github.com/elastic/apm-server/pull/10637#discussion_r1180021907, this adds a GH Action check which runs `terraform fmt` on every terraform file, if any changed. And expects the diff to be clean (if any file is changed by the command, it means they have formatting issues).
This is a CI change, there are no functional changes.
The CI run should pass.
N/A

Terraform fmt

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.0-ebff07ec
---
<Actions>
<action id="f3477000c9aaf3b48b2684c65c2eb5ef7af62e0755ba0091bb334cc3decf9cf4">
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.8.0-ebff07ec

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/fleet-server.yaml
testing/infra/k8s/base/stack/kibana.yaml
testing/infra/k8s/overlays/local/kustomization.yaml

<Actions>
<action id="49dab35c9e476c88669aba3276f15740aa646f242f89961d4d15e5185a3472eb">
</details>
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.7.1-79685088

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-a2c79020
---
<Actions>
<action id="e4a152a9ac27930d16daebcf4e4f6ef0552687f613fe4082bed3358cd78ddec2">
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.9.0-a2c79020

---

apmpackage/apm/changelog.yml
cmd/intake-receiver/version.go
internal/version/version.go

To be merged after tag for 8.7.1 is cut

Bump up version for 8.7.2

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/fleet-server.yaml
testing/infra/k8s/base/stack/kibana.yaml
testing/infra/k8s/overlays/local/kustomization.yaml

<Actions>
<action id="8a7bd11ac0efd81d661fa7fabf6366e58a723235dd83bfb8438f0446e16d1aef">
</details>
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.7.1-2ea32c14

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/fleet-server.yaml
testing/infra/k8s/base/stack/kibana.yaml
testing/infra/k8s/overlays/local/kustomization.yaml

<Actions>
<action id="721c41ae283f835eac41f4c25cc89d5dd12e49284f0a266431be12247a91a489">
</details>
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.7.2-a5f8cdcb

---

apm-server.docker.yml
apm-server.yml
docs/legacy/configuration-process.asciidoc

Update apm-server config files with new tbs settings and list them in the config option page.
Closes https://github.com/elastic/apm-server/issues/10718

docs: document TBS config options for standalone apm server

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/25e882fcd496
---
<Actions>
<action id="c8e69ca436302b69770e3c7caeca93fa481e302d0a2614cf19d4db64d2e0d014">
<summary>Update to elastic/beats@25e882fcd496</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@25e882fcd496

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/fleet-server.yaml
testing/infra/k8s/base/stack/kibana.yaml
testing/infra/k8s/overlays/local/kustomization.yaml

<Actions>
<action id="8398b6170cf407f92a2bb43d018c102199ce530fd60f3d907fd73d3ad49b8cce">
</details>
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.7.2-848575be

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/9ef3f48d6439
---
<Actions>
<action id="d04d8f61ff847729f251bbf81ff2060b6a159a035f24a29b5ddfcc07078b7a75">
<summary>Update to elastic/beats@9ef3f48d6439</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@9ef3f48d6439

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/c722b96b8eab
---
<Actions>
<action id="b931feef3d05f76c4b4dbacd405a7f3f136941523290a629f63c45be49186cf7">
<summary>Update to elastic/beats@c722b96b8eab</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@c722b96b8eab

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/fleet-server.yaml
testing/infra/k8s/base/stack/kibana.yaml
testing/infra/k8s/overlays/local/kustomization.yaml

<Actions>
<action id="4997ef3d69f438835cdc7c20339a37727d51ef4696ac7c3d7a3b8522fdf378b5">
</details>
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.7.2-dd4c72f2

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/6197765d1e81
---
<Actions>
<action id="b7faaeda45c65f8b31cb428d2b967c29d15797c771a126fc6b1834288cb3ffc0">
<summary>Update to elastic/beats@6197765d1e81</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@6197765d1e81

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-58c0f379
---
<Actions>
<action id="49f0122bf3f495995bf17141e13915ab31e5677b27bb7320343472454076ad31">
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.9.0-58c0f379

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/0e5b2a64cfb3
---
<Actions>
<action id="59bb1d9d30112a93563f1b8a596865ebeac0b7ca76fd561a2526cd36ecbbb09d">
<summary>Update to elastic/beats@0e5b2a64cfb3</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@0e5b2a64cfb3

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/d34fe8343555
---
<Actions>
<action id="428e32160592f21e00eacb95a9c941bafb1157ec9229621abe6a1a92131dba7c">
<summary>Update to elastic/beats@d34fe8343555</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@d34fe8343555

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/b4294ab92ef4
---
<Actions>
<action id="6337fc76424b85b11566aac547e418d4a95b371d892ea5924f04d7aa37ccbf9f">
<summary>Update to elastic/beats@b4294ab92ef4</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@b4294ab92ef4

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/e2bfb2f42219
---
<Actions>
<action id="f163c97026d4b486a2043fe442045ac8fbcc524832df2b201ed1cc02b14f6cac">
<summary>Update to elastic/beats@e2bfb2f42219</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@e2bfb2f42219

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/5c48e5eb27ac
---
<Actions>
<action id="916b431ae8e00a0adbe1ee0dcf8ad513526ba2a4305cbe3afaa3484e5c58a191">
<summary>Update to elastic/beats@5c48e5eb27ac</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@5c48e5eb27ac

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/b4411de255fa
---
<Actions>
<action id="5d611ee2159d964212a2f0b318652c479876288dca589d41848ada3b45722845">
<summary>Update to elastic/beats@b4411de255fa</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@b4411de255fa

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/a1e637c25f53
---
<Actions>
<action id="a902c18a29d72c8a7e4818a69302207d4f25a1e0c94c55991727b314d3b02f4e">
<summary>Update to elastic/beats@a1e637c25f53</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@a1e637c25f53

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/7e4022f28e31
---
<Actions>
<action id="02683fda107f5eff00844aa73dad158caac391da0b011ad578a0918d5ff8928a">
<summary>Update to elastic/beats@7e4022f28e31</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@7e4022f28e31

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/7899ad97cffd
---
<Actions>
<action id="29a0918bedb552160547462f6a8d587d089b1bf4f20a87cdf54a3e610df58185">
<summary>Update to elastic/beats@a720b253936c</summary>
</details>
</action>
<action id="668a045f947ca67a8dfb14973ab36ba7f8a2c8e9e49e2d15ce3d225a2782147e">
<summary>Update to elastic/beats@7899ad97cffd</summary>
</details>
</action>
</Actions>
---
<ul>
<li>If you close this pullrequest, Updatecli …

[updatecli] Update to elastic/beats@7899ad97cffd

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/d0a51dc496a0
---
<Actions>
<action id="24aa8683d5c8e3e8bad4cd74185a6e3ac529eff1f08890ecde77ab6f353511d4">
<summary>Update to elastic/beats@d0a51dc496a0</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@d0a51dc496a0

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/fleet-server.yaml
testing/infra/k8s/base/stack/kibana.yaml
testing/infra/k8s/overlays/local/kustomization.yaml

<Actions>
<action id="3b9bf5ddb1b1095823c3f8f82159428a9d6ccc053bffdf339facf26ba10e29c0">
</details>
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.7.2-99e4ac2a

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-5aea1178
---
<Actions>
<action id="efcd33e87715421cce2b79957632356683877a9cfa6ec0edc1986d7f1ed595ae">
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.9.0-5aea1178

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/fb25982c80fb
---
<Actions>
<action id="41e45c294da47224ca30b4bfcabcdd6a39d8604ed7c94e76ac510d602f04cd28">
<summary>Update to elastic/beats@fb25982c80fb</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@fb25982c80fb

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/c71317ddf6d8
---
<Actions>
<action id="32ef454dd509f3b608f95fd3ab5c87dfd97578032d823c1aa62e8117697795a8">
<summary>Update to elastic/beats@c71317ddf6d8</summary>
</details>
</action>
<action id="59e748431491adefb0087b31b85f36650a6a9c7e540afbbf1f0066a248c2f080">
<summary>Update to elastic/beats@5dac5002330e</summary>
</details>
</action>
</Actions>
---
<ul>
<li>If you close this pullrequest, Updatecli …

[updatecli] Update to elastic/beats@c71317ddf6d8

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/e46d240db404
---
<Actions>
<action id="a3aba56fe53bb4d45e3295e4b83a090d08e9271440fb41f1161706ae8e8f24c4">
<summary>Update to elastic/beats@e46d240db404</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@e46d240db404

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/fleet-server.yaml
testing/infra/k8s/base/stack/kibana.yaml
testing/infra/k8s/overlays/local/kustomization.yaml

<Actions>
<action id="3c11b0dd8e3e812b4027d3bc17b79e8ff8b645be646f5894dda7e8a5c863e71d">
</details>
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.7.2-738acb99

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/6f4fe0447d18
---
<Actions>
<action id="985cd9421dee19b200d8c157ab5ee78f82bfdcad9998a28a1139928b475267a4">
<summary>Update to elastic/beats@6f4fe0447d18</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@6f4fe0447d18

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/f61de34d214c
---
<Actions>
<action id="ed5f160cfc565aa941443c56b010844ef4777b77957ddd34e0eb984530398980">
<summary>Update to elastic/beats@f61de34d214c</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@f61de34d214c

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/f8f25adc8af2
---
<Actions>
<action id="41c4300fbb3863bdc1c16a07727d2f444065d231e05ee88cb2ff43dd257e22bb">
<summary>Update to elastic/beats@f8f25adc8af2</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@f8f25adc8af2

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/21b0e47bc927
---
<Actions>
<action id="0d3ad5e4317abed98ff3b90fefb7fce2a871e0e846b6f1052d749cee4ec2244e">
<summary>Update to elastic/beats@21b0e47bc927</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@21b0e47bc927

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/fleet-server.yaml
testing/infra/k8s/base/stack/kibana.yaml
testing/infra/k8s/overlays/local/kustomization.yaml

<Actions>
<action id="3e2576aff265869cb80adffa781b6fa5c1d92a26e13ccb44889e70d17b1dacb8">
</details>
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.7.2-34fb9774

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/d72111f04922
---
<Actions>
<action id="cadda842ef21ff3e2e440d7b746c3b77f1a02f5e79fd859c4f1d3c5b91066372">
<summary>Update to elastic/beats@d72111f04922</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@d72111f04922

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/fleet-server.yaml
testing/infra/k8s/base/stack/kibana.yaml
testing/infra/k8s/overlays/local/kustomization.yaml

<Actions>
<action id="73d9f04d94116e12e181fa4ab63f523c5c05849d89d215a848c7e6a34c422ba9">
</details>
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.7.2-3ff44d96

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/caba30cdcf8a
---
<Actions>
<action id="f01b3d9c6a29fdb42cd76143accc3fad83b7fbd94739e4b2f4a545c26f9b18ef">
<summary>Update to elastic/beats@caba30cdcf8a</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@caba30cdcf8a

---

apmpackage/apm/changelog.yml
apmpackage/apm/data_stream/service_destination_interval_metrics/fields/fields.yml

Add `service.language.name` to service destination mapping to align with other aggregations. There will be no change to actual aggregation implementation yet.

Add service.language.name to service destination mapping

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/8d1a114394ae
---
<Actions>
<action id="3c479dc410cd86757c3e759e14fc67ada3fe303c0321d75a9e46ade234ad8773">
<summary>Update to elastic/beats@8d1a114394ae</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@8d1a114394ae

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/e0f69a5992aa
---
<Actions>
<action id="bddc50d8a3cdb732aa1f3d6acf608d5cbbbbaf2d023f1c89cd54ffce3343a6be">
<summary>Update to elastic/beats@e0f69a5992aa</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@e0f69a5992aa

---

docs/legacy/redirects.asciidoc

Reopening https://github.com/elastic/apm-server/pull/10891 to target `8.8`

docs: redirects for removed pages

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/5a0ed0bdd1c0
---
<Actions>
<action id="589f96438f6984dada3cbca80651b75f342b7d67b490e41c09c1e149b356c42b">
<summary>Update to elastic/beats@5a0ed0bdd1c0</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@5a0ed0bdd1c0

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/fleet-server.yaml
testing/infra/k8s/base/stack/kibana.yaml
testing/infra/k8s/overlays/local/kustomization.yaml

<Actions>
<action id="5921ca4c6739c3d791baaf82db6ca7facd0817aa024fc703c4f78627ac5d96e9">
</details>
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.7.2-3e95e75d

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/fleet-server.yaml
testing/infra/k8s/base/stack/kibana.yaml
testing/infra/k8s/overlays/local/kustomization.yaml

<Actions>
<action id="f04715d1b1de5065c8ba8af8d9964ac25bcddc9d56298c926229f109670d2bcb">
</details>
</details>
</details>
</action>
</Actions>
---
<ul> …

[updatecli] Bump elastic stack version to 8.7.2-81170f47

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/7eb4a224cc99
---
<Actions>
<action id="557ed4981cd13006c3de20058d5ccf2e2fe285ee14370068430c3cfe94cb0ed5">
<summary>Update to elastic/beats@7eb4a224cc99</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@7eb4a224cc99

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/6fddf7cda98f
---
<Actions>
<action id="86347c73e6274b5549273d46788c8ad3afa1919b572334d2a1d451e5a5ce51b5">
<summary>Update to elastic/beats@6fddf7cda98f</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@6fddf7cda98f

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/9edc37365249
---
<Actions>
<action id="b60db63156c7b345b0d6650258b7c6c1365cf46b771416f1a91d6a373f661790">
<summary>Update to elastic/beats@9edc37365249</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@9edc37365249

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/949d713359fe
---
<Actions>
<action id="7345434617e06b0b1dc136fdc46f493a17ce0b7eb78b11a30d5a07fd698c6553">
<summary>Update to elastic/beats@949d713359fe</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@949d713359fe

---

docs/data/elasticsearch/generated/errors.json
docs/data/elasticsearch/generated/transactions.json
tests/system/error.approved.json
tests/system/transaction.approved.json

Update system test approvals due to geoIP database change.
N/A
None

tests/system: update approvals

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/a8aeb843af85
---
<Actions>
<action id="39b6f07ae8fd9db879054c7bea59f267f7e8111bfb0b844bd44b6b68831a1f05">
<summary>Update to elastic/beats@a8aeb843af85</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@a8aeb843af85

---

cmd/intake-receiver/version.go
internal/version/version.go

No change in apmpackage changelog since apmpackage is unchanged.

Bump version to 8.8.2

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/a1bf8b879792
---
<Actions>
<action id="f5140b0767df9bb160b8ed7c9595b05d825cdf8ff75bdf7a087cde50c9302c60">
<summary>Update to elastic/beats@a1bf8b879792</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@a1bf8b879792

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/0672e11390f6
---
<Actions>
<action id="1af86f66bbd9c86881a6260fded2376f7f92d75c9e48e6bd48315d97e85ab53a">
<summary>Update to elastic/beats@0672e11390f6</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@0672e11390f6

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/e9d8e83d5e01
---
<Actions>
<action id="42621d48b219280ed87ed00088e6bdc2dbbd794f680c8da70d635453dc3709e8">
<summary>Update to elastic/beats@e9d8e83d5e01</summary>
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …

[updatecli] Update to elastic/beats@e9d8e83d5e01

---

NOTICE.txt
go.mod
go.sum
internal/beater/api/intake/handler.go
internal/beater/api/intake/handler_test.go
internal/beater/api/mux.go
internal/model/modelprocessor/nop.go

Migrate handlers to protobuf models, remove the protobatchprocessor compatibility layer completely.
Blocked by https://github.com/elastic/apm-server/pull/10978
Blocked by https://github.com/elastic/apm-data/pull/62
Related to https://github.com/elastic/apm-data/issues/52

feat: migrate handler to modelpb and prepare for decoder migration

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-473a43eb
---
<Actions>
<action id="276baecc050af9aff2a44589071193aa88e1ac9fea150858e3a4d790b08e4049">
</details> …

[updatecli] Bump elastic stack version to 8.9.0-473a43eb

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/8d2283f163f3
---
<Actions>
<action id="14d018372b54a1630707bdc41c911b33e9ee324ba3b1e0a7120d65f9136904dc">
<summary>Update to elastic/beats@8d2283f163f3</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8d2283f163f3&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@8d2283f163f3

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/601ee04b47a5
---
<Actions>
<action id="02bde4381309a53bfa10ecd413397444e93c771b671fcce0986611d3cc07e90d">
<summary>Update to elastic/beats@601ee04b47a5</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 601ee04b47a5&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@601ee04b47a5

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.2-6bda6fd3
---
<Actions>
<action id="1774b352b2a7ec98f314e59d16e08549b3af41c6524e2b33c3d56d45f7994838">
</details> …

[updatecli] Bump elastic stack version to 8.8.2-6bda6fd3

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-27e9c674
---
<Actions>
<action id="64a4ec4fa3fad05ed426efef604c9d03a9bf386fa48f5e3d676ace3cc0179f15">
</details> …

[updatecli] Bump elastic stack version to 8.9.0-27e9c674

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/342ec74bcece
---
<Actions>
<action id="5d8a5cbd5fc5408059f53818e09b152b8e899629475eca8c7d1256f049d97671">
<summary>Update to elastic/beats@342ec74bcece</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 342ec74bcece&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@342ec74bcece

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-0032a096
---
<Actions>
<action id="0ceda9e6b4eb543080ad841396ce7750560ecde975f8e505bb8e91ce27b04b36">
</details> …

[updatecli] Bump elastic stack version to 8.9.0-0032a096

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.2-c9f8756a
---
<Actions>
<action id="f9060d92b824b9247f3ac354d80544963027ab3ea7c67071a519fea39cda3763">
</details> …

[updatecli] Bump elastic stack version to 8.8.2-c9f8756a

---

docker-compose.yml

<Actions>
<action id="0400546c5f86edfb68f497af629634fd90047711bfb50545cf3293de2c65740c">
</details>
</action>
<action id="2b19d7051c63c86a00bcfa0603594cc3547b1d8e40444c9a2d82ed6b3105b656">
</details>
</action>
<action id="467a66aad629ecb5a43f01d8a09ee9ec1fa468dc0a0b563ed4e02bc899e1a800">
<summary>Update …

[updatecli] Bump elastic stack version to 7.17.11-57933c35

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.2-363ffebd
---
<Actions>
<action id="80fdf6eb102104f934f34efc9ec5aaadeae07e8308696258ca7a1b4633056adf">
</details> …

[updatecli] Bump elastic stack version to 8.8.2-363ffebd

---

.mergify.yml
apmpackage/apm/changelog.yml
cmd/intake-receiver/version.go
internal/version/version.go

The bot didn't work :(
Bumping the version manually

build: manually bump version to 8.10.0

---

Makefile

build: set BEATS_VERSION to 8.9

---

NOTICE.txt
go.mod
go.sum

[8.9] fix: bump apm-data for structpb conversion (backport #11058)

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-86c33b9d
---
<Actions>
<action id="fa7feb3038e6b25e187be106ebc0dc40f238546bf040c512c5d7bba79b4f2f79">
</details> …

[updatecli] Bump elastic stack version to 8.9.0-86c33b9d

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.2-c7e9ae2e
---
<Actions>
<action id="b814d62189905487e6153d6965ba006103e9faa0520cdc2d7d33dff533e2742a">
</details> …

[updatecli] Bump elastic stack version to 8.8.2-c7e9ae2e

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/7317d97ae71c
---
<Actions>
<action id="b2fb6edc5894ae6b1b839a328f417216ec204e5defc4ff386405d9d1c6bc3957">
<summary>Update to elastic/beats@7317d97ae71c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 7317d97ae71c&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@7317d97ae71c

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.2-652417ba
---
<Actions>
<action id="8a0276ecec02f640fcae98534155d9ca3dfac3c3d8060e9f5094c30b21744c05">
</details> …

[updatecli] Bump elastic stack version to 8.8.2-652417ba

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-a51cd5d0
---
<Actions>
<action id="d552838da397b40e955b4d03c79aab7628510a805bc51ae08de9542a58026902">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-a51cd5d0

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-46e5f4bc
---
<Actions>
<action id="03f1123d7f02a0e6b6554d952dd1b3b0337a83587778f989dc3156c0a7d2aa84">
<p>Updated to content &#34;&#34; in file &#34;testing/infra/k8s/base/stack/elasticsearch.yaml&#34;&#xA;&#xA;Updated to content &#34;&#34; in file &#34;testing/infra/k8s/base/stack/kibana.yaml&#34;&#xA;&#xA;Updated to content &#34;&#34; in file &#34;testing/infra/k8s/base/stack/apm-server.yaml&#34;&#xA;</p>
</details> …

[updatecli] Bump elastic stack version to 8.9.0-46e5f4bc

---

testing/smoke/lib.sh

The JSON response is not ordered correctly. The code was returning 7.17.9 despite the latest version being 7.17.11

test: update smoke test script to retrieve the correct latest patch version

---

testing/rally/track.json

When running force-merge after rally tests, this change ensures we merge the data into a single segment, to provide more stable test results.
See https://esrally.readthedocs.io/en/stable/track.html#force-merge
Run the rally-cloud test suite.
* #10716

Set max-num-segments to 1 in rally config

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/92c6b2370e46
---
<Actions>
<action id="17df71306fb00e29b49621414904cdc7e3b030158d531caab6164b5849ee0235">
<summary>Update to elastic/beats@92c6b2370e46</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 92c6b2370e46&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@92c6b2370e46

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.2-33f1abe8
---
<Actions>
<action id="8dfb3c4f4070c715c870558d94c85dc97b6f861b0c30d9e35dd1b8fb931c2a63">
</details> …

[updatecli] Bump elastic stack version to 8.8.2-33f1abe8

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/36bcc4312e3c
---
<Actions>
<action id="1a726f123f71f4a8179b610611e31c03879d976b17e4a4e5c32252a1332feb18">
<summary>Update to elastic/beats@36bcc4312e3c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 36bcc4312e3c&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@36bcc4312e3c

---

NOTICE.txt
go.mod
go.sum

build: bump apm-data for performance work

---

NOTICE.txt
go.mod
go.sum

build: bump apm-data for performance work (backport #11084)

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-efd868fc
---
<Actions>
<action id="e6ae68e163a6ff6ed827873e3c89c984f647c06418ea2ea02ccc322cf5163fed">
</details> …

[updatecli] Bump elastic stack version to 8.9.0-efd868fc

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-9fc07504
---
<Actions>
<action id="7529d684615d1ad40ecda0445fc87714b101b168eacd0d6431d80568fc1eeb1e">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-9fc07504

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.2-438a24ff
---
<Actions>
<action id="99330c3180fc953fb8acdc078904fd5e3d5b6629500bc8c9431fc529ac4f885f">
</details> …

[updatecli] Bump elastic stack version to 8.8.2-438a24ff

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/533b3052573d
---
<Actions>
<action id="3701bf47c131bb8f9f0b8316b99df466bd24c0841dda018bc1d2705c06f6b2cb">
<summary>Update to elastic/beats@533b3052573d</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 533b3052573d&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@533b3052573d

---

apmpackage/apm/changelog.yml

Add back missing apmpackage changelog for #10937 
#10937

Add 7.17.11 apmpackage changelog

---

changelogs/7.17.asciidoc

Adds the 7.17.11 release notes. I didn't notice anything noteworthy in the commits. Please double-check and **merge** this PR if everything looks good (because I can't merge).

Add 7.17.11 release notes

---

cmd/intake-receiver/version.go
internal/version/version.go

No change in apmpackage changelog since apmpackage is unchanged.

Bump version to 8.8.3

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.2-41f17f3c
---
<Actions>
<action id="78f1071c59021796df7287de286708dae3dd1f03c389f968676a42b2a62d8dc9">
</details> …

[updatecli] Bump elastic stack version to 8.8.2-41f17f3c

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-759b2cb2
---
<Actions>
<action id="1da1fb67d3df5eae369bca5ed236398ceaf2e98999c938fba16b56afb03b6731">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-759b2cb2

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-bbb2ee5d
---
<Actions>
<action id="cbf78f65d23c29c03c55ada26d03dfcda2b75476587d8c3afbee159104b85899">
</details> …

[updatecli] Bump elastic stack version to 8.9.0-bbb2ee5d

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/f333d2549ddc
---
<Actions>
<action id="23cb1452fe9bfa7d65ee739c896a3a4b6e06d69c041f5764b76a4213d30a6552">
<summary>Update to elastic/beats@f333d2549ddc</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh f333d2549ddc&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@f333d2549ddc

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-18649b44
---
<Actions>
<action id="a93d4e7871c9a5c79cbc1ae42119dd670a0529762b660f971ce00c374dea36d9">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-18649b44

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.2-ba369b11
---
<Actions>
<action id="2ff2314e6f117f01bbb274b85d0dcf8b321969b6bd40043f2b65ab34e2bdb4b4">
</details> …

[updatecli] Bump elastic stack version to 8.8.2-ba369b11

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/cf6d82889687
---
<Actions>
<action id="3e32d5c69d49038084e6a0baee023f66e97d7e970bf4a22d8e3585f6997eac7b">
<summary>Update to elastic/beats@cf6d82889687</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh cf6d82889687&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@cf6d82889687

---

.github/workflows/benchmarks.yml
testing/benchmark/outputs.tf

Add links to benchmark dashboard and admin console.

ci: improve debuggability of benchmarks

---

changelogs/head.asciidoc
internal/agentcfg/elasticsearch.go
internal/agentcfg/elasticsearch_test.go
internal/beater/beater.go
internal/beater/server.go

This is the equivalent of #11116, but agent config periodic refreshes.
There are unit tests. I also ran apm-server locally using tilt with self-instrumentation enabled.
* https://github.com/elastic/apm-dev/issues/1014

Add transaction for agent config periodic refresh

---

README.md
docker-compose.yml

It took me a bit too long to figure out how to run the service locally. So this doc change aims to make it better.
This is a doc change.

Improve docs for running locally

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-024bad78
---
<Actions>
<action id="7d90af12c94a8e4369551d64b7372f95bda259324bd3c1b4e9a7e162701ebc3c">
</details> …

[updatecli] Bump elastic stack version to 8.9.0-024bad78

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.3-1f4ea904
---
<Actions>
<action id="2765cb0bf37818a004d717fc2817a6d03c62b78ce39548ebaab86ccf9055ad7c">
</details> …

[updatecli] Bump elastic stack version to 8.8.3-1f4ea904

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.3-dcc440f7
---
<Actions>
<action id="ae62e606a8ea439b442e8dc533bbbfe90b4d0410a813b98b1a37d3e8f6647778">
</details> …

[updatecli] Bump elastic stack version to 8.8.3-dcc440f7

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/e20a8d447b63
---
<Actions>
<action id="80284cca135dedf0c5c3fc5b159b824f0e92be120636c701a3b8a75df56fc800">
<summary>Update to elastic/beats@e20a8d447b63</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e20a8d447b63&#34;</p>
</details>
</action>
<action id="963f9f349a7e3ad8bccbb3e8613dd390046507fe3c473db4fe7c7d923d2dd0c4">
<summary>Update to elastic/beats@f17da7415aed</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh f17da7415aed&#34;</p>
</details>
</action>
</Actions>
---
<table> …

[updatecli] Update to elastic/beats@e20a8d447b63

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-0d099cfb
---
<Actions>
<action id="d95c846c403a02056a5409d1af04cea54318b86bff72f5fba438464e31ab00d6">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-0d099cfb

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.3-9428e7c2
---
<Actions>
<action id="a933ca50b5139b5f5028fee8f3f56f2705849d5b3fee799a9638e5500409df43">
</details> …

[updatecli] Bump elastic stack version to 8.8.3-9428e7c2

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/06990e3e8821
---
<Actions>
<action id="9434c94ddb028e3ea734322fa4a04a7f8b86e261fd905d380693abf968aaa159">
<summary>Update to elastic/beats@06990e3e8821</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 06990e3e8821&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@06990e3e8821

---

internal/beater/beater.go
internal/model/modelprocessor/tracer.go
internal/model/modelprocessor/tracer_test.go

This work actually comes from a slight misunderstanding of how async ingestion works (I assumed the batch processor was the async process).
I still decided to open a PR, as it provides more visibility into the running processors within each request.
This is unit-tested.

Setup tracer processor

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/2b2623c88db4
---
<Actions>
<action id="049a828fc0a126c42481b9daccdccccc31f468148817a6088c4f6d75be98567e">
<summary>Update to elastic/beats@2b2623c88db4</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 2b2623c88db4&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@2b2623c88db4

---

NOTICE.txt
go.mod
go.sum

Bump go-docappender for allocation improvements 
We bump to an unreleased version since this is main and we want to validate the impact on the nightly benchmarks

build: bump go-docappender for allocation improvements

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-89405a28
---
<Actions>
<action id="1a36dff725e324f8fe71e1ceeb324f3bf198687fa1b59dc4959f378e8a718090">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-89405a28

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.3-193fc993
---
<Actions>
<action id="060140a5eeb96d446254de8153c2ae78f2f81485d2913c96c0f235932460cbe6">
</details> …

[updatecli] Bump elastic stack version to 8.8.3-193fc993

---

docker-compose.yml

Made with ❤️️ by updatecli
https://github.com/elastic/apm-server/pull/11068 is bugged
Bump manually

chore: Updated to content "7.17.12-a5bf8147" in file "docker-compose.yml"

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-daadfd9e
---
<Actions>
<action id="4e5f8fc8bb03218b62982f95da9b56a774a506cbe49d9fdb0c16faefd10a6fb5">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-daadfd9e

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-a302929e
---
<Actions>
<action id="64a4ec34edbaec11d6bcbe6758447981e6333f526b207ae3e11b03e59c7b3b21">
</details> …

[updatecli] Bump elastic stack version to 8.9.0-a302929e

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.3-b2365b79
---
<Actions>
<action id="d0d1681bc3aacf38e5ca75a0e42835208cc888a0b213fd2c2f6c2a742aeabfa3">
</details> …

[updatecli] Bump elastic stack version to 8.8.3-b2365b79

---

NOTICE.txt
go.mod
internal/beater/beater.go

I configured the apmotel tracer, but forgot the metrics provider.

Configure metrics provider to send data to the elastic agent

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-84ebde23
---
<Actions>
<action id="da87b32f65f991823c2148a1052d46c23887444f5e7a7dc3661bcd38a32c747e">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-84ebde23

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/56b6aebf766e
---
<Actions>
<action id="2c8f7f15823cd8d3ba9e49448e177af0a21f88a00206e920611f06ddd72d839c">
<summary>Update to elastic/beats@56b6aebf766e</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 56b6aebf766e&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@56b6aebf766e

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-464beb1d
---
<Actions>
<action id="94b489e037b05c27176e0e1224202a4b2df2a10d35f50809a3f1edd6eee7b386">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-464beb1d

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-905e99b1
---
<Actions>
<action id="ef5a54efcffbb88013e2190e5b6f9e5341abd79b920835a120e21f1394d7ea54">
</details> …

[updatecli] Bump elastic stack version to 8.9.0-905e99b1

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.3-40270fd0
---
<Actions>
<action id="99ca267ae142796357c01d53dd0835d5bc38df51305906f8a99aeca29b015c3e">
</details> …

[updatecli] Bump elastic stack version to 8.8.3-40270fd0

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/58759691549d
---
<Actions>
<action id="f5524d30cdb2432cacd5689ea1a2ea26fa4743eb4b5f5d790364b7b628ad0c9c">
<summary>Update to elastic/beats@58759691549d</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 58759691549d&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@58759691549d

---

docker-compose.yml

<Actions>
<action id="dbf5bfa87b32b7f61bd797753637de159ea723e462c8ddf37cc3ff802e5bebb2">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.12-08fbe972

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.3-a6972ae1
---
<Actions>
<action id="0d0c5c168fc69d088e1f29bb3c9f3ead18606235167f18149577c145d235afa9">
</details> …

[updatecli] Bump elastic stack version to 8.8.3-a6972ae1

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.3-91900d44
---
<Actions>
<action id="f733617c064a2d8a8560a435d4eb986a386078eabef725e64d35ed90572bd779">
</details> …

[updatecli] Bump elastic stack version to 8.8.3-91900d44

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-c2848ab2
---
<Actions>
<action id="f9a96a7c34fb99499dcdded81a3eae0df2ffb2a3a3e021767770556c34316b3c">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-c2848ab2

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-446d2070
---
<Actions>
<action id="ec4f7cf4b3212ed63e34463ad241c19b56b60a8b84af2eed6196d2161997add2">
</details> …

[updatecli] Bump elastic stack version to 8.9.0-446d2070

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/97e8feb645ef
---
<Actions>
<action id="84b46f68310a5d502873c6a19bcbaaad8788e6612304a182cf28ea43a7292a91">
<summary>Update to elastic/beats@97e8feb645ef</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 97e8feb645ef&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@97e8feb645ef

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-164e5e60
---
<Actions>
<action id="31416eca563becd6392829560a151b9b852b28bdfc8b371c73145fd6794b456c">
</details> …

[updatecli] Bump elastic stack version to 8.9.0-164e5e60

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-506cd98d
---
<Actions>
<action id="c3b46ec7a64de223f7825ef3204a6162c69859bba8b50ce7d3e85700347d67ae">
<p>Updated to content &#34;&#34; in file &#34;testing/infra/k8s/base/stack/kibana.yaml&#34;&#xA;&#xA;Updated to content &#34;&#34; in file &#34;testing/infra/k8s/base/stack/apm-server.yaml&#34;&#xA;&#xA;Updated to content &#34;&#34; in file &#34;testing/infra/k8s/base/stack/elasticsearch.yaml&#34;&#xA;</p>
</details> …

[updatecli] Bump elastic stack version to 8.10.0-506cd98d

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-4b9e2fa6
---
<Actions>
<action id="bfa02cfc038eb63bbc9b2325769dde1f50d2706e4bcb8ea291ba433bc56764d6">
</details> …

[updatecli] Bump elastic stack version to 8.9.0-4b9e2fa6

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-1f4b0cd0
---
<Actions>
<action id="bb61ed7121c43ad67b154e49c7f3ae19b9a6a5cda685bd567b05a494a7234288">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-1f4b0cd0

---

docker-compose.yml

<Actions>
<action id="39fead19568d8540c877c0175059bbed4953c769ca43c0155594a2dc51df0aac">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.12-624c085e

---

changelogs/7.17.asciidoc

Adds the 7.17.12 release notes.

[7.17] Add 7.17.12 release notes

---

apmpackage/apm/changelog.yml
apmpackage/apm/manifest.yml
cmd/version.go

build: bump version 7.17.13

---

apmpackage/apm/changelog.yml
cmd/intake-receiver/version.go
internal/version/version.go

build: bump version 8.9.1

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-235feca2
---
<Actions>
<action id="15809025a1a09689fb7aed4d2974e117ad2c18337ab2ffe61c5e2115dc9a98d3">
<p>Updated to content &#34;&#34; in file &#34;testing/infra/k8s/base/stack/elasticsearch.yaml&#34;&#xA;&#xA;Updated to content &#34;&#34; in file &#34;testing/infra/k8s/base/stack/kibana.yaml&#34;&#xA;&#xA;Updated to content &#34;&#34; in file &#34;testing/infra/k8s/base/stack/apm-server.yaml&#34;&#xA;</p>
</details> …

[updatecli] Bump elastic stack version to 8.10.0-235feca2

---

docker-compose.yml

<Actions>
<action id="176e08164cfbbb55b31497c372fa7bdd9ec0570e6d1606f639e7fe100c11da1f">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.12-7c1d40f1

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.0-6b15bb32
---
<Actions>
<action id="3386a5f20b888e7748f68b4de7e29221f47c189c9c6e3bb47f29b4b16e702ae3">
</details> …

[updatecli] Bump elastic stack version to 8.9.0-6b15bb32

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-439345ab
---
<Actions>
<action id="d6a234f205f6417151cb976d135cc5e288a7e8bce52b4196ab0e752165a121fb">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-439345ab

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-ec4cafa5
---
<Actions>
<action id="a4403f9723f1060efb34032ef34d71352590187affc13ca336144a183179bae9">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-ec4cafa5

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.8.3-e0b5ba55
---
<Actions>
<action id="270335c26b42dce552ad60d3061a090a5a349b9f11a27939e07427e9e46476d8">
</details> …

[updatecli] Bump elastic stack version to 8.8.3-e0b5ba55

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.1-44a814f0
---
<Actions>
<action id="ed5b40780977cc65f5a7cdf7043bf36f56b686da03d8cc1d29698ee26beee7f8">
</details> …

[updatecli] Bump elastic stack version to 8.9.1-44a814f0

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.1-a0629552
---
<Actions>
<action id="8894f075eb15fbb59aa85c8043c8b5348260c4b6bbd7b543508a06de91471bbd">
</details> …

[updatecli] Bump elastic stack version to 8.9.1-a0629552

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-ed2e01b4
---
<Actions>
<action id="81301f62ca10f408dfa9d25e9d0c8d05e9028a4c9564df9f56f87de80e0b817b">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-ed2e01b4

---

docker-compose.yml

<Actions>
<action id="269cd58b2ec85a2eaea7e185729dd2e94ad8a95d1db05260bfef835999685236">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.13-19dc27d2

---

docker-compose.yml

<Actions>
<action id="ad23ee24ee7dedde0b1969d03d7fddf10e9b132f440beea2ef28c1edfac16633">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.13-7f46ddb9

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.1-40dca293
---
<Actions>
<action id="04b2d804980b971c4e23b5fca4a6dc9b9e6ca2e9f680bb18031d438e6434327c">
</details> …

[updatecli] Bump elastic stack version to 8.9.1-40dca293

---

docker-compose.yml

<Actions>
<action id="47cc1a4c4a6b2fbbb894181679438996d4a01de5fe10ef8897c95b5b3a2a786d">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.13-f0591b59

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.1-762162ce
---
<Actions>
<action id="f2212451579ce1120c9051d7285c0ef32e186a2c2592bdd4a6bf3e780bfd391b">
</details> …

[updatecli] Bump elastic stack version to 8.9.1-762162ce

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-2619e48b
---
<Actions>
<action id="40c190f8a3c4c0674ea9e5ee05155b73a2007d25556bc16f7bc1c2e7e1edeaff">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-2619e48b

---

NOTICE.txt
go.mod
go.sum
x-pack/apm-server/aggregation/servicesummarymetrics/aggregator_test.go
x-pack/apm-server/aggregation/servicetxmetrics/aggregator.go
x-pack/apm-server/aggregation/servicetxmetrics/aggregator_test.go
x-pack/apm-server/aggregation/spanmetrics/aggregator.go
x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
x-pack/apm-server/aggregation/txmetrics/aggregator.go
x-pack/apm-server/aggregation/txmetrics/aggregator_test.go

Bump apm-data so that it's easier to test changes in the library 

build: bump apm-data

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-4047f652
---
<Actions>
<action id="5df8c68af27579df8e4f3ee7c4b6678f6ec8201bceee1bf7be6c1f0f6c966776">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-4047f652

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.1-6c14de65
---
<Actions>
<action id="40d24ef0618b63e143aa21348a7255f0baf5e24e9f014a23191c444e31b0af8f">
</details> …

[updatecli] Bump elastic stack version to 8.9.1-6c14de65

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.1-d46182aa
---
<Actions>
<action id="b82be1ed81a02727442b618233cbaba89ca78d36020c6a6d5672555a01d3b2bc">
</details> …

[updatecli] Bump elastic stack version to 8.9.1-d46182aa

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.1-afb401d4
---
<Actions>
<action id="b01c9b25c8f60b13243719c576d23eed91c7c86320a71cf68abe3109425f0106">
</details> …

[updatecli] Bump elastic stack version to 8.9.1-afb401d4

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-46c2dc52
---
<Actions>
<action id="ed4e2d000a01ab9347c3902169d3f8fd1a63c92814a1d641cf399a6cec5edafd">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-46c2dc52

---

docker-compose.yml

<Actions>
<action id="a3dc52965e66b7d28fad837540e9ddd34c4efe8074fd89ec114fb2cb4cca4ee7">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.13-1882ecdc

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-22c6ae41
---
<Actions>
<action id="95fd16b018cfa023f94f6400ec9622df56e0e17f032ef890d030f177f3f1647f">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-22c6ae41

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.1-975bdf3e
---
<Actions>
<action id="6a9964aa2621447f16a11dce7ec036172badedcbbf31c2c59d50df0a8f389256">
</details> …

[updatecli] Bump elastic stack version to 8.9.1-975bdf3e

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/4506e55d50f9
---
<Actions>
<action id="ea283f454461ca42e2e21aa34eb00cf8eaa2c0e01d13b96ea90299e87a3f7445">
<summary>Update to elastic/beats@4506e55d50f9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 4506e55d50f9&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@4506e55d50f9

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.1-456ef5ad
---
<Actions>
<action id="68426df925a30db428ce17a564bb0410a8f40ab83bb675d8aeef616343e88eb4">
</details> …

[updatecli] Bump elastic stack version to 8.9.1-456ef5ad

---

NOTICE.txt
go.mod
go.sum
x-pack/apm-server/aggregation/lsm.go

Add aggregation overflow logging. To be merged after https://github.com/elastic/apm-aggregation/pull/87 and rebase.

Add back aggregation overflow logging

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-8527fe43
---
<Actions>
<action id="4174e3689a9873713a3caa8c693ce01e83df39946c9a10baa6833baae8d12795">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-8527fe43

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.1-162a595c
---
<Actions>
<action id="2b3e0b12a58f30b238485bb2a1d5acc4fef5f65015b9b8cee74cac8b0ee9a48f">
</details> …

[updatecli] Bump elastic stack version to 8.9.1-162a595c

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/59529de17b77
---
<Actions>
<action id="c8f84cf21192177803e7724c29e569f440f16345f3c517e9ec9b31ae8c2052e1">
<summary>Update to elastic/beats@59529de17b77</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 59529de17b77&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@59529de17b77

---

catalog-info.yaml

use `apm-server-package` name rather than `apm-server`
In BK itself

catalog-info: change BK name

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/138e623c02ed
---
<Actions>
<action id="bf86052ec213a502969cc0ecdb16f45e7fadc21faa4f4cafa065a439f6743a6d">
<summary>Update to elastic/beats@138e623c02ed</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 138e623c02ed&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@138e623c02ed

---

Makefile
cmd/intake-receiver/version.go
internal/version/version.go

Fix incorrect version created by automation.
Related: https://github.com/elastic/observability-robots/issues/1798

Fix incorrect version

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-bd3f3b15
---
<Actions>
<action id="4e02b92e9f52774d902bafbc0678567e8b047acd2ae830f42a86861d9ad29eb6">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-bd3f3b15

---

changelogs/head.asciidoc

Update changelog to reflect that all aggregations now share the same MaxServices limit. e.g. if MaxServices is 10, service A sending traces means that there can only be 9 more services sending traces or logs or errors.

changelog: Aggregations share MaxServices

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-96e4cccf
---
<Actions>
<action id="28002d6010b7ed1692ba3ba19f3cf9c85d51b8ae340189d7c3cff866ef9956de">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-96e4cccf

---

docker-compose.yml

<Actions>
<action id="048aa157dfc94697b64ad2cb3e2b82e9637d418883fcb888a2fa46da365b1be4">
</details>
</action>
<action id="2d5a652fb5aaf3689f7f7e75c4354ecdc9192871e3a984cffc737edb7788cf88">
</details>
</action>
<action id="da7b82df3cf9bd48d75f5c70d3afc366a69f130d1ce05cb7187e0ae28973 …

[updatecli] Bump elastic stack version to 7.17.13-dde9c3ba

---

.buildkite/scripts/dra.sh

buildkite: branches are not pull requests

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.1-f33bc992
---
<Actions>
<action id="0f3771f76bef18082e940fe31315914b3aff787ed02c385af3e5d74a1068bb72">
<p>Updated to content &#34;&#34; in file &#34;testing/infra/k8s/base/stack/elasticsearch.yaml&#34;&#xA;&#xA;Updated to content &#34;&#34; in file &#34;testing/infra/k8s/base/stack/kibana.yaml&#34;&#xA;&#xA;Updated to content &#34;&#34; in file &#34;testing/infra/k8s/base/stack/apm-server.yaml&#34;&#xA;</p>
</details> …

[updatecli] Bump elastic stack version to 8.9.1-f33bc992

---

.github/workflows/ci-docs.yml

https://github.com/elastic/apm-server/commit/3d44b64fe61db4eb4684cf5995dbc38c484acf68 changed the mergify merge queue requirements when the Jenkins Github check was removed and included the GitHub checks but it didn't change the `ci-docs` to accommodate the new requirements.
As a consequence the merge-queue in Mergify gets stuck when PRs are only docs related changes.

actions: fix the mergify auto-merge when docs

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.2-f4929e8e
---
<Actions>
<action id="77754a3b03805aa430920adef74835802e0c03d800d45ff5e679e3f22bebfaee">
</details> …

[updatecli] Bump elastic stack version to 8.9.2-f4929e8e

---

docker-compose.yml

<Actions>
<action id="9cc06f1f2e9843d63fc3ff2b72f22c08698cc8aef1ed496e23ea607d52762985">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.13-9cee84e3

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/8903b1f77e7f
---
<Actions>
<action id="277f589a96818f19c9cdcd753c62c31a5135aa9c5239b61febe1a3db87c8da10">
<summary>Update to elastic/beats@8903b1f77e7f</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8903b1f77e7f&#34;</p>
</details>
</action>
<action id="dc588482c71c7dbfc85a47f513a2d72718fba705217868bf1c50605cb08b86cf">
<summary>Update to elastic/beats@66c616eda801</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 66c616eda801&#34;</p>
</details>
</action>
</Actions>
---
<table> …

[updatecli] Update to elastic/beats@8903b1f77e7f

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/ecc82aa39843
---
<Actions>
<action id="27ef8d7571819d74e51c6d007d3fe05d0b44244798fbe394dfe85072517d811d">
<summary>Update to elastic/beats@ecc82aa39843</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ecc82aa39843&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@ecc82aa39843

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/c79df0b21c21
---
<Actions>
<action id="be5386b29c1794314216ef3d304f51b0e4edb6692628e09fd3e869e9d70f6d65">
<summary>Update to elastic/beats@c79df0b21c21</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c79df0b21c21&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@c79df0b21c21

---

.github/workflows/ci.yml

Enable tests to run on `ubuntu-latest`
In the CI itself

action: run tests on Ubuntu

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-6bf877e8
---
<Actions>
<action id="bb9f53d4431a2db1f198b28cdf39394b2f425b88b3f98d3aeeb5a1fc83978b91">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-6bf877e8

---

docker-compose.yml

<Actions>
<action id="cdb5a5cc08b49aa094fb3a543fbfd81c8a372f45fcc747ce56af47717c70b598">
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.13-7e207efe

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-73e185bf
---
<Actions>
<action id="110c0da066e48712cf58ed12a2d72aa53d32b2b7846e3d9fbcbeff88b7a2ab08">
</details> …

[updatecli] Bump elastic stack version to 8.11.0-73e185bf

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.2-8eb52857
---
<Actions>
<action id="1c1582296d831382dd5a40ce78699393ccf5936845539276c46246773f44356c">
</details> …

[updatecli] Bump elastic stack version to 8.9.2-8eb52857

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-322e3ef7
---
<Actions>
<action id="f166eb4cb5ba2b74ae4d27c0963bba3c4f7f960eff2cde099a560daeae01fc69">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-322e3ef7

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/c341e06736e3
---
<Actions>
<action id="1328176351eb24fa10f76feb9c2b9bf47dcfaf1a61efc8c5a0bcd3463b306a9c">
<summary>Update to elastic/beats@c341e06736e3</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c341e06736e3&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@c341e06736e3

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-76b03348
---
<Actions>
<action id="18e3d3b027e480f9fb2b5840f7b7f92653636b7c8440a5bbd67991bf9c1f0f22">
</details> …

[updatecli] Bump elastic stack version to 8.11.0-76b03348

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-edf31268
---
<Actions>
<action id="3b145051cb89405cb740d10ceab0d4fdcab47f24ba4ed1a3d0c3e87b6a2b5133">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-edf31268

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.2-1a569074
---
<Actions>
<action id="d903697b09dbae4e9685c3e38d03a429e6a34ea232713f19b3be12761b52bb22">
</details> …

[updatecli] Bump elastic stack version to 8.9.2-1a569074

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/3d4705d7220f
---
<Actions>
<action id="5bb387780bb6dc4cf6ee2a09bcd8744166c5852b463b6779e971d9cfc94e5f24">
<summary>Update to elastic/beats@3d4705d7220f</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 3d4705d7220f&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@3d4705d7220f

---

.github/workflows/README.md
README.md

A highlight level overview what the CI does
Remove Jenkins badges and enable Buildkite badge
NA
NA

docs: explain what the CI does

---

.github/workflows/benchmarks.yml

We want to be able to run the agent and OTLP benchmarks separately, to ensure they don't impact each other.
Trigger the action with this PR's branch.
https://github.com/elastic/apm-server/actions/workflows/benchmarks.yml
* 7842

Allow specifying benchmarks to run

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-3ddff50a
---
<Actions>
<action id="8ec9d1c950058eef367ecd333cccb565b9405eb74de22518be0fb1419da71d34">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-3ddff50a

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-ba1a8c0f
---
<Actions>
<action id="09739b988834d3f3a8b85a028cfc89fb1c7ac294e3a86fd730daa81a5bb7d6c0">
</details> …

[updatecli] Bump elastic stack version to 8.11.0-ba1a8c0f

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.2-fe004c3f
---
<Actions>
<action id="b879044645b88aa7187fedfbccb9c3b2cb232f275efe343e9754d17cdfb0c5b7">
</details> …

[updatecli] Bump elastic stack version to 8.9.2-fe004c3f

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/fd98e2b885a0
---
<Actions>
<action id="867b66f1113c77793c979264af5cef5e100f961fda598d833dc829941345e68d">
<summary>Update to elastic/beats@fd98e2b885a0</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh fd98e2b885a0&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@fd98e2b885a0

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/a182bafd7c1e
---
<Actions>
<action id="4a293cee6cfa39652601b0fe2b0fcbc5d7b922dec5ba46dc8890f3cf806ce4b2">
<summary>Update to elastic/beats@a182bafd7c1e</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a182bafd7c1e&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@a182bafd7c1e

---

testing/benchmark/system-profiles/32BGx2zone.tfvars

We're using this system profile for #7842. So I'm adding it to the main branch for documentation and ease of use in later runs.
Run a benchmark with this PR.

Add 32gb benchmark system profile

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.9.2-a804d52d
---
<Actions>
<action id="5fd765a9e252bc8eb0d29508517b100ac148895683ac0eb874b92b14775ad933">
</details> …

[updatecli] Bump elastic stack version to 8.9.2-a804d52d

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-16180d4a
---
<Actions>
<action id="319803282e1ad6d46f124941b0f3d5ae154303ace1a08bd026e0c3d6f9ab8c15">
</details> …

[updatecli] Bump elastic stack version to 8.11.0-16180d4a

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-b58178d3
---
<Actions>
<action id="0456d97261f28b3f2a37b056f01167f0ca1d6a4be6fa5a6f9abac0436257e52d">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-b58178d3

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/0971da859b06
---
<Actions>
<action id="7589c2e2c5876c28a7823c86e1a3cdb7514220b507f12db84739ed1db9ccad0b">
<summary>Update to elastic/beats@0971da859b06</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 0971da859b06&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@0971da859b06

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/55edac538c60
---
<Actions>
<action id="ccaa11fdd21136d5e4977d9a66fe70f6ab19f0be33e98837ce00cd725fd30669">
<summary>Update to elastic/beats@55edac538c60</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 55edac538c60&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@55edac538c60

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-e6a0cfad
---
<Actions>
<action id="5ef468f827c39f4887c602a275d17bcbbd83977614a31278472c05fe1694eac3">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-e6a0cfad

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-1e5443be
---
<Actions>
<action id="276530322163a430ed6d738dc1655f2f0b4eb9ff5a3a1fcb9633ad15c8a2a7b2">
</details> …

[updatecli] Bump elastic stack version to 8.11.0-1e5443be

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/4f6eae0ea385
---
<Actions>
<action id="9a6a2f662d206690dd793411d482fb44826415f4dabed079d7460954ec277f36">
<summary>Update to elastic/beats@4f6eae0ea385</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 4f6eae0ea385&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@4f6eae0ea385

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/eef9598ea110
---
<Actions>
<action id="367df888acee70dc00b95da8ffdf6a701cc6e123023b7b5d2423c63393acfe1e">
<summary>Update to elastic/beats@eef9598ea110</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh eef9598ea110&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@eef9598ea110

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-8369a13a
---
<Actions>
<action id="45894a2af9c6539fdaa07fd523d5d101c16e4a1dcf48d92744ae5c743abf7515">
</details> …

[updatecli] Bump elastic stack version to 8.11.0-8369a13a

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/c23978a8de52
---
<Actions>
<action id="426de963bba31e5f24a18dc710483cb1f0fbd86baf3d73b4e82e33ea2a079904">
<summary>Update to elastic/beats@c23978a8de52</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c23978a8de52&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@c23978a8de52

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/a6bae85b20b8
---
<Actions>
<action id="ebee6f5b3b01ed7d8d7b99e990013601c0512d9f87dff38b995c1fb566914c8e">
<summary>Update to elastic/beats@a6bae85b20b8</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a6bae85b20b8&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@a6bae85b20b8

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-fc582a97
---
<Actions>
<action id="049b6c90827128af1de9a6a76cad67240978fa72e894547bec7446d2728483e4">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-fc582a97

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/b017e506dc26
---
<Actions>
<action id="ae9c8a8e64cf27d8cd7d225bfe8c39c922bfb391cc9c30236556be9fd08a6ecd">
<summary>Update to elastic/beats@b017e506dc26</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b017e506dc26&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@b017e506dc26

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/ab2f67d7ee4e
---
<Actions>
<action id="e2a50ebf4e1080d70b6714455760593aa8268bb2b30f024abe4691e9796fc113">
<summary>Update to elastic/beats@ab2f67d7ee4e</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ab2f67d7ee4e&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@ab2f67d7ee4e

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-e4344f1d
---
<Actions>
<action id="6885e13467f27c06d889aeb999a75f31bb16653165bf6900fe93106b6a2c6205">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-e4344f1d

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-e6822a57
---
<Actions>
<action id="6fa995e945a0d18973b08118237cfcfec178c2c8fb57b7c5fddbb897e50746e9">
</details> …

[updatecli] Bump elastic stack version to 8.11.0-e6822a57

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/62873ab51c9c
---
<Actions>
<action id="8c6c5b594c74c061f60181045daaaaff4f7c19beda13553d637c00017ac5a4dc">
<summary>Update to elastic/beats@62873ab51c9c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 62873ab51c9c&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@62873ab51c9c

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/3b02b8a82a5a
---
<Actions>
<action id="d31c6a2cab416150054e17e58159bb31f5568f2e8e7c8afa14f1be08382b5a36">
<summary>Update to elastic/beats@3b02b8a82a5a</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 3b02b8a82a5a&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@3b02b8a82a5a

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-32daf5de
---
<Actions>
<action id="d353435c40ea1948ce22686f717912c5929c3fc5e3e2dc467a5311a698f289e0">
</details> …

[updatecli] Bump elastic stack version to 8.11.0-32daf5de

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-befeb0ae
---
<Actions>
<action id="977668405c8eaa312cb439143f3f9c2ef24e5d0417a495c59f5ebcf8159c81fd">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-befeb0ae

---

docs/api-config.asciidoc
docs/api-events.asciidoc
docs/api-info.asciidoc
docs/api-jaeger.asciidoc
docs/api-otlp.asciidoc
docs/api.asciidoc

preview link: https://apm-server_11592.docs-preview.app.elstc.co/guide/en/apm/guide/master/api.html
Closes https://github.com/elastic/apm-server/issues/11066.

Document all the APIs

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-fa76ee05
---
<Actions>
<action id="c1e23e77713694993d26ff603d196faf05c93019e4e602255191bcd1d57ce98d">
</details> …

[updatecli] Bump elastic stack version to 8.10.0-fa76ee05

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-3ae53e7a
---
<Actions>
<action id="a5e7ed74abac8ec46740a03e7b0b23274bdc40379b96037b96864cb1aedf19f7">
</details> …

[updatecli] Bump elastic stack version to 8.11.0-3ae53e7a

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/8d3aa9126c15
---
<Actions>
<action id="561f289e676d9031819f92644f8060459810d0d79ce7c5bf150c73dc24f5e9aa">
<summary>Update to elastic/beats@8d3aa9126c15</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8d3aa9126c15&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@8d3aa9126c15

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-f3e0fdd8
---
<Actions>
<action id="2378f8cb74924c756505703c0e75652014bcc85fd93be757801eaab86f95ed29">
<p>1 file(s) updated with &#34;$1:8.10.0-f3e0fdd8-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.0-f3e0fdd8-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.0-f3e0fdd8

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/80ed33b8cc69
---
<Actions>
<action id="d96b35cb0a2fe5f29424c91a05f85b6464c93e45391e8223ac33fb866c9c7fbb">
<summary>Update to elastic/beats@80ed33b8cc69</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 80ed33b8cc69&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@80ed33b8cc69

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-0d7477b6
---
<Actions>
<action id="27ae7bccab2ca9fac2c7fdc23beb3a45f91d715dab8ef766fadc16660cba51d3">
<p>3 file(s) updated with &#34;version: 8.11.0-0d7477b6-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.0-0d7477b6-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-0d7477b6

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/95be378c22fa
---
<Actions>
<action id="a8cc8501b723559eb3dab074d4cc41b8d7439c13700e2a0fb20f9b855e2bf8e5">
<summary>Update to elastic/beats@95be378c22fa</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 95be378c22fa&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@95be378c22fa

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-f8bc4ebc
---
<Actions>
<action id="c6013e11fe1b3f68ef8845df4a6d3913d224cd42ff55d859823ed5b1df2ce6e1">
<p>1 file(s) updated with &#34;$1:8.11.0-f8bc4ebc-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-f8bc4ebc-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-f8bc4ebc

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/8e7e2065c73b
---
<Actions>
<action id="b3965dad47d7cc56694e8702f6c45b4f5f81479e5450ed3bd096174b4d4a28c0">
<summary>Update to elastic/beats@8e7e2065c73b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8e7e2065c73b&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@8e7e2065c73b

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-7dab12da
---
<Actions>
<action id="aa2a1e38b8c4dc4edd15a11c87e5540ae5a29efdab6d0b8b17248a205a3734a2">
<p>1 file(s) updated with &#34;$1:8.11.0-7dab12da-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-7dab12da-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-7dab12da

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.0-516050d7
---
<Actions>
<action id="b4362bd742ea103a770dfa9b102757980dc27097fbd3eb907fdb94ab7d820cb3">
<p>1 file(s) updated with &#34;$1:8.10.0-516050d7-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.0-516050d7-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.0-516050d7

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/b7d1f806f6ec
---
<Actions>
<action id="bdb4aedb43b30c0c89cc8b2b75c5a10dba9bc661e80ddf5764a0d9e91f8208d2">
<summary>Update to elastic/beats@b7d1f806f6ec</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b7d1f806f6ec&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@b7d1f806f6ec

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-58bca18d
---
<Actions>
<action id="0c12996a7bb1ccbae63a2b3e58252c7db8f65acb590bcacf56781fee62ea224f">
<p>1 file(s) updated with &#34;$1:8.11.0-58bca18d-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-58bca18d-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-58bca18d

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/73774d544927
---
<Actions>
<action id="fe068af2b38db4dfed0071efba72fe584cfdcbad8497fb46e0567948cf1ccb1f">
<summary>Update to elastic/beats@73774d544927</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 73774d544927&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@73774d544927

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-f9ab12e0
---
<Actions>
<action id="30767b189c31c5f50e9cd85db80cc38508153eb1de2e4c9f8f8d6f2865eb7271">
<p>1 file(s) updated with &#34;$1:8.11.0-f9ab12e0-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-f9ab12e0-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-f9ab12e0

---

changelogs/8.10.asciidoc

Adds 8.10.1 changelog. No significant changes.

Add 8.10.1 changelog

---

changelogs/8.10.asciidoc

Fix missing changelog line in #11656 

Add missing changelog line to 8.10.asciidoc

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.1-1dffad09
---
<Actions>
<action id="77846efe5f4a61dd60a874e7dc36ef6a4707e7615cf2d9f83c1fdf5970aace17">
<p>3 file(s) updated with &#34;version: 8.10.1-1dffad09-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.10.1-1dffad09-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.1-1dffad09

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-2b227d89
---
<Actions>
<action id="716bd9e2fabbefbbb3b15a9262cea921251bc8cd89d25098be513037405b3eac">
<p>3 file(s) updated with &#34;version: 8.11.0-2b227d89-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.0-2b227d89-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-2b227d89

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/b4f7abe549d9
---
<Actions>
<action id="cb7707cde679b77cd01e7a963b2db4a478c393651ddd93f505b5fd69e381c3d8">
<summary>Update to elastic/beats@b4f7abe549d9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b4f7abe549d9&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@b4f7abe549d9

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-f88f1d11
---
<Actions>
<action id="2869f99fe2a5920cf38c2907f7d5d440f6a195b66d3a005e8e93b6280ef6af49">
<p>1 file(s) updated with &#34;$1:8.11.0-f88f1d11-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-f88f1d11-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-f88f1d11

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/ccfa54a3b000
---
<Actions>
<action id="b70eaa2d0be32d1d2a65d8f54975933130f261eee0447747fe7f18127a406a99">
<summary>Update to elastic/beats@ccfa54a3b000</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ccfa54a3b000&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@ccfa54a3b000

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.2-9d743908
---
<Actions>
<action id="3bb1dc89206543c8bccc8bf41386c89783f6fd5eacc77f754df1875f847883e6">
<p>1 file(s) updated with &#34;$1:8.10.2-9d743908-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.2-9d743908-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.2-9d743908

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/480bccf4f042
---
<Actions>
<action id="974182ee576146545f296077f66a3fef58bc5aa5b38f5652dde6cff8cec8b4a3">
<summary>Update to elastic/beats@480bccf4f042</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 480bccf4f042&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@480bccf4f042

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/5da74528be00
---
<Actions>
<action id="6b5858e3925192fa757707fba13f4e993cb8eb30267f60e4d3efad9f46024ae5">
<summary>Update to elastic/beats@5da74528be00</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 5da74528be00&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@5da74528be00

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.2-d38be4c2
---
<Actions>
<action id="15702b22812b3827f3a95c1a5b8c3c96e8ed2cc430f91a2c618237c34cca385d">
<p>3 file(s) updated with &#34;version: 8.10.2-d38be4c2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.10.2-d38be4c2-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.2-d38be4c2

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-91824658
---
<Actions>
<action id="b030746794e625751603d64eecbe128d47433ae79956f8f1267d193d481757fd">
<p>1 file(s) updated with &#34;$1:8.11.0-91824658-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-91824658-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-91824658

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/24c3388ed6d8
---
<Actions>
<action id="02fe1419c96b62033d4c129c4897a77b04b74c6901b621543fd37bf9a88a73e8">
<summary>Update to elastic/beats@24c3388ed6d8</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 24c3388ed6d8&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@24c3388ed6d8

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.2-10b341e4
---
<Actions>
<action id="a71b4d310be1d7b8bfcb7e51baa186cdbeba373bf9cd28f6a71fa8a926f8f9d1">
<p>1 file(s) updated with &#34;$1:8.10.2-10b341e4-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.2-10b341e4-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.2-10b341e4

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-6aa5b988
---
<Actions>
<action id="1309326db738cc6967b4682e9a4fa16bb69eb57c3fcb61f4d52195061a4b8b5f">
<p>1 file(s) updated with &#34;$1:8.11.0-6aa5b988-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-6aa5b988-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-6aa5b988

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/513ace48f5f0
---
<Actions>
<action id="d23d067614f907a1ef6eacea7eacf16c0e2b4ce62e676558c3fb4f5d9632396f">
<summary>Update to elastic/beats@513ace48f5f0</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 513ace48f5f0&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@513ace48f5f0

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-c47419c4
---
<Actions>
<action id="0b36d477178f850e4c9e5a7bb3815edad4b3735b19c916213ca1067be32ab5dd">
<p>1 file(s) updated with &#34;$1:8.11.0-c47419c4-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-c47419c4-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-c47419c4

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-abc4d077
---
<Actions>
<action id="01b26decf50e0016e44a01921391a0490b1b45abacacea8464e5919fdc3db927">
<p>1 file(s) updated with &#34;$1:8.11.0-abc4d077-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-abc4d077-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-abc4d077

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.3-aa09190a
---
<Actions>
<action id="ec48b81309301736af54dd92140509247aef0d6775c5511a39ab44443c7fd2ca">
<p>3 file(s) updated with &#34;version: 8.10.3-aa09190a-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.10.3-aa09190a-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.3-aa09190a

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/b9a47516c7c4
---
<Actions>
<action id="7005da34709367df7d8ed035af04b9bbb005e852756805dc5f691a037b4318f4">
<summary>Update to elastic/beats@964ba2226d27</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 964ba2226d27&#34;</p>
</details>
</action>
<action id="a34755776174885a132c28354321fc9a34554dae0a816070f310433a3c3162d5">
<summary>Update to elastic/beats@b9a47516c7c4</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b9a47516c7c4&#34;</p>
</details>
</action>
</Actions>
---
<table> …

[updatecli] Update to elastic/beats@b9a47516c7c4

---

changelogs/head.asciidoc

Add back missing PR link in changelog

changelog: Fix missing PR link

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/90407307dae6
---
<Actions>
<action id="f9cf09f2dfcccfa62dc60a919549520b3d39000e9e2f1dc8d7953d49fb4c8200">
<summary>Update to elastic/beats@90407307dae6</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 90407307dae6&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@90407307dae6

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-6faed5c7
---
<Actions>
<action id="6eace9d62cd9d025bc7a888759af89e186b816e04e18b042706541f01b5dc2a1">
<p>1 file(s) updated with &#34;$1:8.11.0-6faed5c7-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-6faed5c7-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-6faed5c7

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.3-345ef27d
---
<Actions>
<action id="d69284f73e5428dfab1bea19c02fb27286c25441149181f3c0a3608ba2d5d3d5">
<p>1 file(s) updated with &#34;$1:8.10.3-345ef27d-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.3-345ef27d-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.3-345ef27d

---

docker-compose.yml

<Actions>
<action id="44f5dbce9d2ea4b2d9ea726b01f88a7eb3795c434d8f371734ab619e4f34c312">
<p>1 file(s) updated with &#34;$1:7.17.14-ca136f74-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
<action id="be5c198ce26bd71c417cb5a58c094c7c348211b8ecf23ab6c5e1960aa3c48619">
<p>1 file(s) updated with &#34;$1:7.17.14-ca772d6f-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
<action …

[updatecli] Bump elastic stack version to 7.17.14-ca772d6f

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-b2ac6b4d
---
<Actions>
<action id="c9afde8974782646717b29a1d0af80f6a1fabf7273403d0d381b76d56a35b942">
<p>3 file(s) updated with &#34;version: 8.11.0-b2ac6b4d-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.0-b2ac6b4d-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-b2ac6b4d

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.3-a4520544
---
<Actions>
<action id="92c9c6dabeb9213bc580d9f1b4f7569ae289457f934f5afa06b3695a3d008b41">
<p>1 file(s) updated with &#34;$1:8.10.3-a4520544-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.3-a4520544-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.3-a4520544

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/58db08f2bf76
---
<Actions>
<action id="2058d5f368eef3409f9f1fe9922f9f7b22652161a41abc32e5bdf72fae64b046">
<summary>Update to elastic/beats@58db08f2bf76</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 58db08f2bf76&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@58db08f2bf76

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-10db2ffc
---
<Actions>
<action id="638fbfeffbdb2d41db72c55fe316b3be458221d31a65c558ac4b8fae2562beb3">
<p>1 file(s) updated with &#34;$1:8.11.0-10db2ffc-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-10db2ffc-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-10db2ffc

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.3-8e865fb7
---
<Actions>
<action id="3e88d120c6398339da78429522bae36a9184fc25823c5d761ee38fed45ff8bdd">
<p>1 file(s) updated with &#34;$1:8.10.3-8e865fb7-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.3-8e865fb7-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.3-8e865fb7

---

docker-compose.yml

<Actions>
<action id="8b8d713ffcf68fbb4b32e78211c7b17b7c82b67c0180e43e7d981751d0cbe3df">
<p>1 file(s) updated with &#34;$1:7.17.14-a1357ca2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.14-a1357ca2

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.3-0a467303
---
<Actions>
<action id="c663f2799270663a7b2d901884a137d2b926cdd564fff60e90b1f63d41d9fa49">
<p>3 file(s) updated with &#34;version: 8.10.3-0a467303-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.10.3-0a467303-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.3-0a467303

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/483d344b0cea
---
<Actions>
<action id="dd01fa92a776761a4e38453fa2dba6fb7a265ccb5840785efe232f4ac1c47800">
<summary>Update to elastic/beats@483d344b0cea</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 483d344b0cea&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@483d344b0cea

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/49cc14d35d5e
---
<Actions>
<action id="45cf0bc995dd329e77ad166a498ef4d1f21674805ba3f63dccb31ae1124cc1ab">
<summary>Update to elastic/beats@231e93a6d20e</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 231e93a6d20e&#34;</p>
</details>
</action>
<action id="f48278a301aa6706b1154981d53a823f5001d5d6c04e03218a5dc84666ea62d5">
<summary>Update to elastic/beats@49cc14d35d5e</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 49cc14d35d5e&#34;</p>
</details>
</action>
</Actions>
---
<table> …

[updatecli] Update to elastic/beats@49cc14d35d5e

---

systemtest/approvals/TestIntake/Errors.approved.json
systemtest/approvals/TestIntake/Events.approved.json
systemtest/approvals/TestIntake/Transactions.approved.json
systemtest/approvals/TestIntake/TransactionsHugeTraces.approved.json
systemtest/approvals/TestOTLPGRPCLogsClientIP.approved.json

Fix geoip changes that cause systemtest failures

systemtest: Fix geoip changes

---

docker-compose.yml

<Actions>
<action id="e404ffe2ac165a2279d5e3fd61b1f85150859ba6afb707c3f748290b6b73b38b">
<p>1 file(s) updated with &#34;$1:7.17.14-78860399-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.14-78860399

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/c1918b0509c8
---
<Actions>
<action id="e89c6e7ba1f0b897502c0d3ccf8e59ecd7c9b93dfe75c0cc851857620e24ee4b">
<summary>Update to elastic/beats@c1918b0509c8</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c1918b0509c8&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@c1918b0509c8

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/ea73410c20ec
---
<Actions>
<action id="00e10d5edb34bff4b606f4cc8eeba1589646100f07b3f842c1707fea324f7ecd">
<summary>Update to elastic/beats@428fd2f98451</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 428fd2f98451&#34;</p>
</details>
</action>
<action id="646cdafca4725e46bcc128f8e8f9d0c19d5868c0cadd8ef8fa8934788e8cb87d">
<summary>Update to elastic/beats@ea73410c20ec</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ea73410c20ec&#34;</p>
</details>
</action>
<action …

[updatecli] Update to elastic/beats@ea73410c20ec

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.3-75e0d7cb
---
<Actions>
<action id="85a14843cac6d73dbe189f3ccb531ec913f6530eba2c31fdfce331ff63b1e570">
<p>3 file(s) updated with &#34;version: 8.10.3-57d6bd70-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.10.3-57d6bd70-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.3-75e0d7cb

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/b301d3278d75
---
<Actions>
<action id="a7a50fdfcbf5979589553d72c37d15b336013ef74ce8057414eaf19de3a8a00d">
<summary>Update to elastic/beats@b301d3278d75</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b301d3278d75&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@b301d3278d75

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/37113021c2d2
---
<Actions>
<action id="1eb90e8dbf5e283c01ad091721740438bd2baa8ba68a06c43b077a56054e3602">
<summary>Update to elastic/beats@37113021c2d2</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 37113021c2d2&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@37113021c2d2

---

packaging/ironbank/hardening_manifest.yaml

https://github.com/elastic/apm-server/pull/11780 partially bumped the version to 8.8 but there was another file to be updated

ironbank: update hardening to 8.8

---

docker-compose.yml

<Actions>
<action id="c1bb9dbfcfc5f59005da24f9fbefbda73dfb6de8973ad80814726dd3f93c59b5">
<p>1 file(s) updated with &#34;$1:7.17.14-a522fb9c-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.14-a522fb9c

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/e4bb7549a25c
---
<Actions>
<action id="6a1ad9635171cb6d15eaf9a19d6e43f1dcc0a50de4d970ae18b5f681cc6ec59f">
<summary>Update to elastic/beats@e4bb7549a25c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e4bb7549a25c&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@e4bb7549a25c

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/7877074cc606
---
<Actions>
<action id="7be9489b0f3b647b7f7189e23eabbc62099d18a46a8ce54930a205335a774ce6">
<summary>Update to elastic/beats@7877074cc606</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 7877074cc606&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@7877074cc606

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-dfefa400
---
<Actions>
<action id="e5289271f737dbd84499b83f8fe1d0f362683f44f235bb26213ddc0b37a56312">
<p>3 file(s) updated with &#34;version: 8.11.0-dfefa400-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.0-dfefa400-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-dfefa400

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.3-17f9519a
---
<Actions>
<action id="32aa2d10a62f631efecf5d9b9533d32605739e943c3b658b74e6c0e5f08c313f">
<p>1 file(s) updated with &#34;$1:8.10.3-17f9519a-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.3-17f9519a-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.3-17f9519a

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/b25934a799d9
---
<Actions>
<action id="43d7e68766d59eaf00ea55d4eb4c89b5f8fdc1304bba994de5f869b8937083c3">
<summary>Update to elastic/beats@b25934a799d9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b25934a799d9&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@b25934a799d9

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/a4f8aa1ae6af
---
<Actions>
<action id="4286feead9b2c0be428565c5adfba9e802d2e351f19c4921fe0f157394960df8">
<summary>Update to elastic/beats@a4f8aa1ae6af</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a4f8aa1ae6af&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@a4f8aa1ae6af

---

cmd/intake-receiver/version.go
internal/version/version.go

Preparing in advance for `8.10.3` release.

Bump up version to 8.10.4

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/04a0022641d9
---
<Actions>
<action id="fe5ff67b3f4c3135a741cbf52d8a470ed76fc456e80e5aa609115e45c894b7a8">
<summary>Update to elastic/beats@04a0022641d9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 04a0022641d9&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@04a0022641d9

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/332917dbd4c8
---
<Actions>
<action id="608aea12190a5a2f822a0d96331a205c46ecdcf27a88ba7c512587cd6c3b5df0">
<summary>Update to elastic/beats@332917dbd4c8</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 332917dbd4c8&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@332917dbd4c8

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/73303ae8c759
---
<Actions>
<action id="be311b1a87895332f677dc5f761cd690f1dda4badfe81b5067b078eb80a2fd6d">
<summary>Update to elastic/beats@73303ae8c759</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 73303ae8c759&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@73303ae8c759

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.3-35c43be1
---
<Actions>
<action id="acbe9505e0c0e9de06779abbcb057b748c74add54574f4e5a2be33ceced7287c">
<p>1 file(s) updated with &#34;$1:8.10.3-35c43be1-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.3-35c43be1-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.3-35c43be1

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-4acbdbb1
---
<Actions>
<action id="48dd6e3f6749a5f12e479878c60bcc3a74a90839241a0d81dc5075eae29ce60c">
<p>1 file(s) updated with &#34;$1:8.11.0-4acbdbb1-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-4acbdbb1-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-4acbdbb1

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-3a221f77
---
<Actions>
<action id="2954148999a2e63b3912f917e87b0e7814a90a9fb399dbdba4850bc90dd978ed">
<p>1 file(s) updated with &#34;$1:8.12.0-3a221f77-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-3a221f77-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-3a221f77

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/093757b9eca6
---
<Actions>
<action id="ab51acd55ae437139a56a473fbd21561079a1981c8a67d2f41193c351950b4fc">
<summary>Update to elastic/beats@093757b9eca6</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 093757b9eca6&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@093757b9eca6

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-60b804d4
---
<Actions>
<action id="56b7f3188313f1d43205565a4fd0a66d66508d2171befa78c6735a227a7beefd">
<p>1 file(s) updated with &#34;$1:8.11.0-60b804d4-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-60b804d4-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-60b804d4

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.4-b2fddf0a
---
<Actions>
<action id="839935182d7a2b6d3b53045f4d5ab3bd353271ffe4b9ec1912dea032e0ad96a3">
<p>1 file(s) updated with &#34;$1:8.10.4-b2fddf0a-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.4-b2fddf0a-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.4-b2fddf0a

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-1a1295ff
---
<Actions>
<action id="c2c5b3b423b44038c29928111e5d6eefe6c995cbeecc5e217cc225adb968d302">
<p>1 file(s) updated with &#34;$1:8.12.0-1a1295ff-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-1a1295ff-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-1a1295ff

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/e322104a8cc2
---
<Actions>
<action id="8ac18e02a82fb0cf7ce888dffe660dcf37e1b499e9bd83058465889c75982794">
<summary>Update to elastic/beats@e322104a8cc2</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e322104a8cc2&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@e322104a8cc2

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/276935866238
---
<Actions>
<action id="e03342b0a3ec7a91c6d83a2fe17bdcb81a9375f478fd0c7c9e5186ab2543e67a">
<summary>Update to elastic/beats@276935866238</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 276935866238&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@276935866238

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/10b198c985eb
---
<Actions>
<action id="9dcdda89f871299c98cac336ed5ba3a02825916dd9517704fdd8a25dfb6e87fe">
<summary>Update to elastic/beats@10b198c985eb</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 10b198c985eb&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@10b198c985eb

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/89030c0055c9
---
<Actions>
<action id="fa1e598180b3af0d9ff6c5c4de831d8b4d7ebe49c8c459b6c6c0bbae50ea74b7">
<summary>Update to elastic/beats@89030c0055c9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 89030c0055c9&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@89030c0055c9

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/8a707127fb2b
---
<Actions>
<action id="f4b4eef32985bd5c1f0c120aabcf7f5eb4865f13fd56721cc299980317b095ee">
<summary>Update to elastic/beats@8a707127fb2b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8a707127fb2b&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@8a707127fb2b

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.4-df8d75ce
---
<Actions>
<action id="774cc179dd702372c902fdf71f08f7b108a3859c0141bb15ce344714e0f0298a">
<p>1 file(s) updated with &#34;$1:8.10.4-df8d75ce-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.4-df8d75ce-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.4-df8d75ce

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-cb808527
---
<Actions>
<action id="ce02c348bce518fea97a9047b48ad58ea5d88103eb6607768e572be4d3c44f24">
<p>3 file(s) updated with &#34;version: 8.12.0-cb808527-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.0-cb808527-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-cb808527

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-820fdcd6
---
<Actions>
<action id="5d8c77e69900836da0d16e78726519d14ed0282a2881990281a2b0fd1fbc9e9d">
<p>1 file(s) updated with &#34;$1:8.11.0-820fdcd6-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-820fdcd6-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-820fdcd6

---

docker-compose.yml

<Actions>
<action id="10e5c19ba99741f800a1954151ccd360f24231bdba4eb538a0ef3e45008de3f2">
<p>1 file(s) updated with &#34;$1:7.17.15-a0c3fd00-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
<action id="35d9f44d9c50eb2ca962bc0517873bfee72ffcee2b82e86b01ac2cedc857afc5">
<p>1 file(s) updated with &#34;$1:7.17.15-e89ddad5-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
<action …

[updatecli] Bump elastic stack version to 7.17.15-a0c3fd00

---

changelogs/8.10.asciidoc
changelogs/head.asciidoc

Please merge if this PR looks correct.

Add 8.10.4 release notes

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/6be0d18448bb
---
<Actions>
<action id="742691bb15ff01ec84398aeb0245ae69181ba0580f6c4140eee8b1c4167297f0">
<summary>Update to elastic/beats@6be0d18448bb</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6be0d18448bb&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@6be0d18448bb

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/f17aa541281a
---
<Actions>
<action id="fbf70c6738885d05ccc6987f9e2ce4fa3f211b1b2867db10f3244725131a6182">
<summary>Update to elastic/beats@f17aa541281a</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh f17aa541281a&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@f17aa541281a

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-1359bda9
---
<Actions>
<action id="f2298bef5e57b4eec9c542099e5b9d30f6561f818796bbab9dcd5d0ff35525f7">
<p>1 file(s) updated with &#34;$1:8.12.0-1359bda9-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-1359bda9-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-1359bda9

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.4-945697b8
---
<Actions>
<action id="670f535ab91e553a987e40b2c15f0f99bf80f8743f0611c923ec8d076097f480">
<p>1 file(s) updated with &#34;$1:8.10.4-945697b8-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.4-945697b8-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.4-945697b8

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-48d7ee6d
---
<Actions>
<action id="b7b5086ae6a1418fdda9c453107769e8b0e890adc37e4ded7546335c2523918b">
<p>3 file(s) updated with &#34;version: 8.11.0-48d7ee6d-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.0-48d7ee6d-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-48d7ee6d

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/29482b585059
---
<Actions>
<action id="98e340fd1f5355adc05c9ee617025ef6d0598eb7e305240f87884e159969c340">
<summary>Update to elastic/beats@29482b585059</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 29482b585059&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@29482b585059

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-6b5c9b80
---
<Actions>
<action id="e8a708d26a53aa51031ebb48d829419aeea0778ab695f8949a6694d662cd8f78">
<p>1 file(s) updated with &#34;$1:8.11.0-6b5c9b80-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-6b5c9b80-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-6b5c9b80

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/54416d5c7908
---
<Actions>
<action id="aeae2faf31421b4bc39e66aa82ed29150e2bd102292976eee9f9c58805187db8">
<summary>Update to elastic/beats@54416d5c7908</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 54416d5c7908&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@54416d5c7908

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.4-ba5798e3
---
<Actions>
<action id="88b631cc1db5f86b6ee4ab3fa4eb0e8790cc332ee9fb4a3417d4ef5e59fb3fff">
<p>1 file(s) updated with &#34;$1:8.10.4-ba5798e3-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.4-ba5798e3-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.4-ba5798e3

---

docker-compose.yml

<Actions>
<action id="36a0fdda9ad8545a2e21dbc74c0b4b3867384ee4c288b94605c5d81ae3ab47f0">
<p>1 file(s) updated with &#34;$1:7.17.15-310ac563-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.15-310ac563

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.5-fede41a8
---
<Actions>
<action id="8fb4164676e56f572836339b112c7007a9f40d3b20bb4ed40d5f6f995414e03c">
<p>1 file(s) updated with &#34;$1:8.10.5-fede41a8-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.5-fede41a8-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.5-fede41a8

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-50f754c3
---
<Actions>
<action id="4cfa90c8e9bad242aaa19996b0413b0024556ebe2539f7953ef41daa61790bfa">
<p>1 file(s) updated with &#34;$1:8.11.0-50f754c3-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-50f754c3-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-50f754c3

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/d3c42ef75b93
---
<Actions>
<action id="6324d582cc4e171de9a6ff7ff52748598badc1ce2f33113792209d7b31194a3d">
<summary>Update to elastic/beats@d3c42ef75b93</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d3c42ef75b93&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@d3c42ef75b93

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/79ea0204fbb0
---
<Actions>
<action id="22e47e8a7cd36ec110cefd0fce3d5059e620ba222fb8718773be5389258f2482">
<summary>Update to elastic/beats@79ea0204fbb0</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 79ea0204fbb0&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@79ea0204fbb0

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/63af3b695af1
---
<Actions>
<action id="3688e58931083ec5d6c280368fa4656d9a89e4052c8199e28e24e36510de2ad7">
<summary>Update to elastic/beats@63af3b695af1</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 63af3b695af1&#34;</p>
</details>
</action>
<action id="a071f42afb4e6aee8fcc09937c465128e4ff7aaf3813544d8696d15277bcb5d8">
<summary>Update to elastic/beats@5a2ea7b63bf5</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 5a2ea7b63bf5&#34;</p>
</details>
</action>
</Actions>
---
<table> …

[updatecli] Update to elastic/beats@63af3b695af1

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-64ca6348
---
<Actions>
<action id="fd2e185a039ca9d75734772776ac72fb31303a11524dbca4410df4f50facf018">
<p>3 file(s) updated with &#34;version: 8.11.0-64ca6348-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.0-64ca6348-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-64ca6348

---

docker-compose.yml

<Actions>
<action id="c84caaa19a659ee9df207099ca0bb56e67b7b430a5d5c782b9834f8d00905d91">
<p>1 file(s) updated with &#34;$1:7.17.15-ae1f480c-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.15-ae1f480c

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.5-69d64a75
---
<Actions>
<action id="41a8e5e67fdb9c1e57434338928cac8667b7a2894ad127e1cba52d1862b87e97">
<p>1 file(s) updated with &#34;$1:8.10.5-69d64a75-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.5-69d64a75-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.5-69d64a75

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.5-0028f476
---
<Actions>
<action id="bf75347569ace929b0802b7dd138465a731eaf8f82f853bff65d4708ef73e26f">
<p>1 file(s) updated with &#34;$1:8.10.5-0028f476-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.5-0028f476-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.5-0028f476

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-129ce746
---
<Actions>
<action id="1ebb28e35f93f3dcdadc9132cdb39eb25c0bc66a6dbc33246d464a48b392f6bb">
<p>1 file(s) updated with &#34;$1:8.12.0-129ce746-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-129ce746-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-129ce746

---

docker-compose.yml

<Actions>
<action id="37bc8e5389fc82cdfa7f9d561e45806915c7d8a0784584843a9b5481ad613ab9">
<p>1 file(s) updated with &#34;$1:7.17.15-3f916b1e-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.15-3f916b1e

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/a0e7f5d7b830
---
<Actions>
<action id="2b460625ac357124534dbc2b730ea531081fda5887bb59cc7fbf44f838d7b801">
<summary>Update to elastic/beats@a0e7f5d7b830</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a0e7f5d7b830&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@a0e7f5d7b830

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/74c241a959eb
---
<Actions>
<action id="8db286acb3aad99c3222101f337b37f42efc9155f7f2b1dfa22580f23740d9f7">
<summary>Update to elastic/beats@74c241a959eb</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 74c241a959eb&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@74c241a959eb

---

changelogs/8.10.asciidoc

Add changelog for https://github.com/elastic/apm-data/issues/44

changelog: add entry for datastream changes in 8.10

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.5-b919c0d9
---
<Actions>
<action id="8447eb83169dce5f5223bf8c02f205e7276f52aaf37b939a4464791e3d74db2c">
<p>1 file(s) updated with &#34;$1:8.10.5-b919c0d9-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.5-b919c0d9-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.5-b919c0d9

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-f8ea8c6e
---
<Actions>
<action id="a1b34e0864a349896afe065f65131cf249f8e964384449e37fe79a198254489a">
<p>1 file(s) updated with &#34;$1:8.11.0-f8ea8c6e-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-f8ea8c6e-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-f8ea8c6e

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-0f0dbad4
---
<Actions>
<action id="a08f1abbbfb6ccabbb4557d1d92794478f9afb547e67320a6c9443130b4e3e88">
<p>3 file(s) updated with &#34;version: 8.12.0-0f0dbad4-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.0-0f0dbad4-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-0f0dbad4

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/455461486c59
---
<Actions>
<action id="a9f82bda949c923aad847b3ed46982e7391885de917bc65cb04c7029ec22e9c0">
<summary>Update to elastic/beats@455461486c59</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 455461486c59&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@455461486c59

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/127703245317
---
<Actions>
<action id="faa0834f3d037c15414bd9218a759ad16bcfc269fddd641d1ef5e4d0e685ffd1">
<summary>Update to elastic/beats@127703245317</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 127703245317&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@127703245317

---

packaging.mk
tools/notice/dependencies.csv.tmpl

https://github.com/elastic/apm-server/pull/11785 bumped the version for the ironbank.
- https://oss-dependencies.elastic.co/red-hat-universal-base-image-minimal/9/ubi-minimal-9-source.tar.gz is not available, but no clue how the dependencies work in this particular case

ubi9: update the reference as done with the ironbank

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-26e5e008
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.0-26e5e008-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-26e5e008-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-26e5e008

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-75139b44-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.15-75139b44

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/fe32436b2e80
---
<Actions>
<summary>Update to elastic/beats@fe32436b2e80</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh fe32436b2e80&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@fe32436b2e80

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/703ecffa54dd
---
<Actions>
<summary>Update to elastic/beats@703ecffa54dd</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 703ecffa54dd&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@703ecffa54dd

---

.mergify.yml

This will help with the auto-merge

mergify: add backport label for the 7.17 backports

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/fd0446ff94e9
---
<Actions>
<summary>Update to elastic/beats@fd0446ff94e9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh fd0446ff94e9&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@fd0446ff94e9

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-6c3c780b
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.0-6c3c780b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.0-6c3c780b-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-6c3c780b

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-f9668451
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-f9668451-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-f9668451-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-f9668451

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/88d866bae9fd
---
<Actions>
<summary>Update to elastic/beats@88d866bae9fd</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 88d866bae9fd&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@88d866bae9fd

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/d792f05bb5b0
---
<Actions>
<summary>Update to elastic/beats@d792f05bb5b0</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d792f05bb5b0&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@d792f05bb5b0

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/ee864b52d115
---
<Actions>
<summary>Update to elastic/beats@ee864b52d115</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ee864b52d115&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@ee864b52d115

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-fa958a90
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-fa958a90-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-fa958a90-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-fa958a90

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/bb2793eab632
---
<Actions>
<summary>Update to elastic/beats@bb2793eab632</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh bb2793eab632&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@bb2793eab632

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/27792cfd5166
---
<Actions>
<summary>Update to elastic/beats@27792cfd5166</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 27792cfd5166&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@27792cfd5166

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.5-4e5678b2
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.10.5-4e5678b2-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.5-4e5678b2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.5-4e5678b2

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-bb5042c3
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.0-bb5042c3-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.0-bb5042c3-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-bb5042c3

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/edde82d12e28
---
<Actions>
<summary>Update to elastic/beats@edde82d12e28</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh edde82d12e28&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@edde82d12e28

---

changelogs/8.11.asciidoc
docs/apm-breaking.asciidoc

A few small updates for the 8.11 release notes.

8.11 release note updates

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/4f36168c91dc
---
<Actions>
<summary>Update to elastic/beats@b42c6bbc55d6</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b42c6bbc55d6&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@4f36168c91dc

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-c46e14f4-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.15-c46e14f4

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.5-2cbba330
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.10.5-7673c4c2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.10.5-7673c4c2-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.5-2cbba330

---

.buildkite/scripts/dra.sh
packaging/ironbank/Dockerfile.tmpl
packaging/ironbank/hardening_manifest.yaml.tmpl

As long as elastic/beats uses 8.8 we cannot use ubi9
Let's revert the changes in 7.17 since it's the only branch using the elastic/beats packaging system.
For such I reverted:
*  Revert "[7.17] ironbank: ubi9:9.2 (backport #11785) (#11813)"
This reverts commit f382bd625d6e26a80b28788b82aa21e25733a70e.
* Revert "fix: correct base Docker image names (#11926) (#11928)"
This reverts commit 93f5b98387da4e89bc7da03992bf6e3914995cb4.
* Revert "dra: rename ubi8 for ubi9 (#11990)"
This reverts commit 68aaf6ffdc986aef7a85b8ed77b2dcd9c6f30cd8.

ironbank: remove support for ubi9

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.5-d6b719a1
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.10.5-d6b719a1-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.5-d6b719a1-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.5-d6b719a1

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/496457dc0ce3
---
<Actions>
<summary>Update to elastic/beats@496457dc0ce3</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 496457dc0ce3&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@496457dc0ce3

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/b41cd433340f
---
<Actions>
<summary>Update to elastic/beats@b41cd433340f</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh b41cd433340f&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@b41cd433340f

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.5-952c31ce
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.10.5-952c31ce-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.5-952c31ce-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.5-952c31ce

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/d3facc808d2b
---
<Actions>
<summary>Update to elastic/beats@d3facc808d2b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d3facc808d2b&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@d3facc808d2b

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/48e0660ff060
---
<Actions>
<summary>Update to elastic/beats@48e0660ff060</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 48e0660ff060&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@48e0660ff060

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-d4bb1214
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.11.0-d4bb1214-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.0-d4bb1214-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-d4bb1214

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-982e299a-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.15-982e299a

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/d8a7c7b9c29c
---
<Actions>
<summary>Update to elastic/beats@d8a7c7b9c29c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh d8a7c7b9c29c&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@d8a7c7b9c29c

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.0-c2c48f8b
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.11.0-c2c48f8b-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.0-c2c48f8b-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.0-c2c48f8b

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.5-5c458ac8
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.10.5-5c458ac8-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.10.5-5c458ac8-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.5-5c458ac8

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-3dc13f24-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.15-3dc13f24

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/1765a9722b39
---
<Actions>
<summary>Update to elastic/beats@1765a9722b39</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 1765a9722b39&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@1765a9722b39

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.10.5-b9ae0cc2
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.10.5-b9ae0cc2-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.10.5-b9ae0cc2-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.10.5-b9ae0cc2

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/2ad905809b7c
---
<Actions>
<summary>Update to elastic/beats@2ad905809b7c</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 2ad905809b7c&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@2ad905809b7c

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/475eaf5784b4
---
<Actions>
<summary>Update to elastic/beats@475eaf5784b4</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 475eaf5784b4&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@475eaf5784b4

---

docs/shared-docker.asciidoc

Base image changed since #11778. Update docs accordingly.
Follow up on #12014

docs: Update base image to 22.04

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-82adb10b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.15-82adb10b

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-e209a10a-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.15-e209a10a

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-af34bce7-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Bump elastic stack version to 7.17.15-af34bce7

---

docker-compose.yml
systemtest/approvals/TestOTLPGRPCLogsClientIP.approved.json
systemtest/otlp_test.go
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.1-c8848943
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.11.1-d2280b84-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.1-d2280b84-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.1-c8848943

---

apmpackage/apm/changelog.yml
apmpackage/apm/manifest.yml
cmd/version.go

Bump version to 7.17.16

---

cmd/intake-receiver/version.go
internal/version/version.go

Bump version to 8.11.2

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.1-2f6a8ab6
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.1-2f6a8ab6-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.1-2f6a8ab6-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.1-2f6a8ab6

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.15-aad9f113-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6851776778">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Bump elastic stack version to 7.17.15-aad9f113

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/9f93f932e9ae
---
<Actions>
<summary>Update to elastic/beats@28152d53e32b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 28152d53e32b&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6851743661">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@9f93f932e9ae

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/f059c4bebc29
---
<Actions>
<summary>Update to elastic/beats@918d3dff67d7</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 918d3dff67d7&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6851743661">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@f059c4bebc29

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-9a986274
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.0-cf2c16a7-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.0-cf2c16a7-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-9a986274

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/0f6417808f30
---
<Actions>
<summary>Update to elastic/beats@8caea63dca5f</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8caea63dca5f&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …

[updatecli] Update to elastic/beats@0f6417808f30

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/921dedec8f7d
---
<Actions>
<summary>Update to elastic/beats@921dedec8f7d</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 921dedec8f7d&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6865423103">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@921dedec8f7d

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/9cf9d4058976
---
<Actions>
<summary>Update to elastic/beats@9cf9d4058976</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 9cf9d4058976&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6865423103">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@9cf9d4058976

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.2-a8fca3bd
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-a8fca3bd-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.2-a8fca3bd-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.2-a8fca3bd

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-82c28a25
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.0-628b3b84-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.0-628b3b84-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-82c28a25

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/0f656292d196
---
<Actions>
<summary>Update to elastic/beats@0f656292d196</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 0f656292d196&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6879018826">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@0f656292d196

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/473f7197f840
---
<Actions>
<summary>Update to elastic/beats@473f7197f840</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 473f7197f840&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6879018826">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@473f7197f840

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.2-e0eeeb99
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-e0eeeb99-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.2-e0eeeb99-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.2-e0eeeb99

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-95c51018-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6892558012">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Bump elastic stack version to 7.17.16-95c51018

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-c18d0d89
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-c18d0d89-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-c18d0d89-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-c18d0d89

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/23fc9409c3e3
---
<Actions>
<summary>Update to elastic/beats@23fc9409c3e3</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 23fc9409c3e3&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6892524009">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@23fc9409c3e3

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/7ace47d4cb0d
---
<Actions>
<summary>Update to elastic/beats@7ace47d4cb0d</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 7ace47d4cb0d&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6892524009">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@7ace47d4cb0d

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/c686ca76cc2e
---
<Actions>
<summary>Update to elastic/beats@c686ca76cc2e</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c686ca76cc2e&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6905598384">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@c686ca76cc2e

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/5a65bf6bac47
---
<Actions>
<summary>Update to elastic/beats@5a65bf6bac47</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 5a65bf6bac47&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6905598384">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@5a65bf6bac47

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-35e3b343
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-35e3b343-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-35e3b343-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-35e3b343

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.2-dc2c1eb6
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-dc2c1eb6-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.2-dc2c1eb6-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.2-dc2c1eb6

---

.buildkite/package.yml

Notify when something bad happens when running the `DRA` process (Daily Releasable Artifacts) to the oblt-robots team.
In the CI itself

buildkite: notify the robots team if any failures too

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.2-b3ae3a61
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-b3ae3a61-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.2-b3ae3a61-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.2-b3ae3a61

---

packaging/ironbank/Dockerfile
packaging/ironbank/hardening_manifest.yaml

Bump the ubi:9 version to `9.3` as requested

ironbank: use ubi:9.3

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/3a79899c43d0
---
<Actions>
<summary>Update to elastic/beats@3a79899c43d0</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 3a79899c43d0&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6931877916">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@3a79899c43d0

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/8e63e2cd1f3e
---
<Actions>
<summary>Update to elastic/beats@e49c19384fb9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e49c19384fb9&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6945614843">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@8e63e2cd1f3e

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/886d078ba1f0
---
<Actions>
<summary>Update to elastic/beats@886d078ba1f0</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 886d078ba1f0&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6945614843">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@886d078ba1f0

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.2-01f6d366
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-01f6d366-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.2-01f6d366-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.2-01f6d366

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-03cd24d7-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6971388173">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Bump elastic stack version to 7.17.16-03cd24d7

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-456fee42-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/6982266197">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Bump elastic stack version to 7.17.16-456fee42

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-ffcb407a-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7006838884">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Bump elastic stack version to 7.17.16-ffcb407a

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/c1fdb00da13d
---
<Actions>
<summary>Update to elastic/beats@a590ba4b2769</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a590ba4b2769&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7006804969">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@c1fdb00da13d

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.2-a6202097
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.11.2-2c7cf905-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.2-2c7cf905-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.2-a6202097

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/07f52c4280e5
---
<Actions>
<summary>Update to elastic/beats@07f52c4280e5</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 07f52c4280e5&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7020614520">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@07f52c4280e5

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.2-8c8386ee
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.11.2-8c8386ee-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.2-8c8386ee-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.2-8c8386ee

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-d6c4164b
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-d6c4164b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-d6c4164b-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-d6c4164b

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-ec4853e4
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-ec4853e4-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-ec4853e4-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-ec4853e4

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.2-1b4759d3
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-1b4759d3-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.2-1b4759d3-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.2-1b4759d3

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/6f32513e5037
---
<Actions>
<summary>Update to elastic/beats@6f32513e5037</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6f32513e5037&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7034424699">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@6f32513e5037

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/b30a5ec82af0
---
<Actions>
<summary>Update to elastic/beats@1f282b0db89f</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 1f282b0db89f&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7088419884">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@b30a5ec82af0

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-33e8d7e1
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-33e8d7e1-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-33e8d7e1-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-33e8d7e1

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.16-9916f602-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7102587785">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Bump elastic stack version to 7.17.16-9916f602

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.2-9debce77
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.2-9debce77-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.2-9debce77-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.2-9debce77

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-9bbde39d
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.0-zx3xz97i-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.0-zx3xz97i-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-9bbde39d

---

docker-compose.yml
systemtest/approvals/TestOTLPGRPCLogsClientIP.approved.json
systemtest/otlp_test.go
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.3-dce3355e
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.11.2-5d5f3e59-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.2-5d5f3e59-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.3-dce3355e

---

CHANGELOG.asciidoc
changelogs/8.12.asciidoc

Move head.asciidoc to 8.12.asciidoc

docs: Update changelogs for 8.12 release

---

systemtest/approvals/TestIntake/Errors.approved.json
systemtest/approvals/TestIntake/Events.approved.json
systemtest/approvals/TestIntake/Transactions.approved.json
systemtest/approvals/TestIntake/TransactionsHugeTraces.approved.json

Update approvals as geo ip changes to fix system test.

Fix geo ip approval changes

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-3faaf80d
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.0-8db20ea5-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.0-8db20ea5-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-3faaf80d

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-bde01754
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-bde01754-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-bde01754-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-bde01754

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-0d7c3f79
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-0d7c3f79-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-0d7c3f79-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-0d7c3f79

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.4-eb79a552
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.11.4-d6b1ea5a-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.4-d6b1ea5a-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.4-eb79a552

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-7f0b87e8-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7289783713">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Bump elastic stack version to 7.17.17-13e2edc2

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/b38ef4827c1e
---
<Actions>
<summary>Update to elastic/beats@088c21fd045a</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 088c21fd045a&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7289755469">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@b38ef4827c1e

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.13.0-vqaxdghw
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.0-vqaxdghw-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.0-vqaxdghw-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.13.0-vqaxdghw

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.4-8b9cf48f
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-8b9cf48f-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.4-8b9cf48f-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.4-8b9cf48f

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-f615e8a5-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7322608643">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Bump elastic stack version to 7.17.17-6c067840

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-514f2280-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7330535320">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Bump elastic stack version to 7.17.17-514f2280

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/dea4afd59f78
---
<Actions>
<summary>Update to elastic/beats@9e5569622dcf</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 9e5569622dcf&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7330517090">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@dea4afd59f78

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/7c70c5a3c743
---
<Actions>
<summary>Update to elastic/beats@a4aee9ac8162</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a4aee9ac8162&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7330517090">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@7c70c5a3c743

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/8a20bd2b137a
---
<Actions>
<summary>Update to elastic/beats@8a20bd2b137a</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 8a20bd2b137a&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7322593261">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@8a20bd2b137a

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.4-4f9102a1
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.11.4-e0baf42b-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.4-e0baf42b-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.4-4f9102a1

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.13.0-qvykcic3
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.0-p7cya7tg-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.0-p7cya7tg-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.13.0-qvykcic3

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-01443900
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.0-fab43f98-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.0-fab43f98-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-01443900

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-e8c03076
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.0-e8c03076-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.0-e8c03076-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-e8c03076

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.4-b057e528
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-b057e528-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.4-b057e528-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.4-b057e528

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-ae5188ce-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7339468650">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Bump elastic stack version to 7.17.17-ae5188ce

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/f7467f59d14b
---
<Actions>
<summary>Update to elastic/beats@f7467f59d14b</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh f7467f59d14b&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7337538755">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@f7467f59d14b

---

NOTICE.txt
apm-server.docker.yml
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/24ef01141ea2
---
<Actions>
<summary>Update to elastic/beats@24ef01141ea2</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 24ef01141ea2&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7337538755">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@24ef01141ea2

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-2df616a6
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-2df616a6-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-2df616a6-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-2df616a6

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.13.0-4aavtlfc
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.0-4aavtlfc-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.0-4aavtlfc-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.13.0-4aavtlfc

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.4-33860d30
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.11.4-33860d30-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.4-33860d30-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.4-33860d30

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-2e4b288d-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7348787217">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Bump elastic stack version to 7.17.17-2e4b288d

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/6f7cd75cd72e
---
<Actions>
<summary>Update to elastic/beats@6f7cd75cd72e</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6f7cd75cd72e&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7348766690">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@6f7cd75cd72e

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/ac1e16c327ae
---
<Actions>
<summary>Update to elastic/beats@ac1e16c327ae</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ac1e16c327ae&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7348766690">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@ac1e16c327ae

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/ea5e055ea1b1
---
<Actions>
<summary>Update to elastic/beats@ea5e055ea1b1</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ea5e055ea1b1&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7357657687">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@ea5e055ea1b1

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.13.0-4f8l51qr
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-4f8l51qr-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-4f8l51qr-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.13.0-4f8l51qr

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-32d47279
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-32d47279-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-32d47279-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-32d47279

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.4-c3b12837
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.11.4-c3b12837-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.4-c3b12837-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.4-c3b12837

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/2c25fb8ca824
---
<Actions>
<summary>Update to elastic/beats@2c25fb8ca824</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 2c25fb8ca824&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7357657687">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@2c25fb8ca824

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/5043c444b12f
---
<Actions>
<summary>Update to elastic/beats@54c0506947fe</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 54c0506947fe&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7387215947">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@5043c444b12f

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/a1ef36366d21
---
<Actions>
<summary>Update to elastic/beats@a1ef36366d21</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a1ef36366d21&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7378131782">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@a1ef36366d21

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.4-41fcbc39
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.11.4-05ba2d97-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.4-05ba2d97-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.4-41fcbc39

---

apm-server.docker.yml
docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-9947ebf0
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.12.0-6cebaffd-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.12.0-6cebaffd-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-9947ebf0

---

NOTICE.txt

Update NOTICE.txt year

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/6f192c01ef19
---
<Actions>
<summary>Update to elastic/beats@6f192c01ef19</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 6f192c01ef19&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7398845516">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@6f192c01ef19

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/246adc20a0f9
---
<Actions>
<summary>Update to elastic/beats@246adc20a0f9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 246adc20a0f9&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7398845516">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@246adc20a0f9

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/09baa1b9bac9
---
<Actions>
<summary>Update to elastic/beats@09baa1b9bac9</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 09baa1b9bac9&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7398845516">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@09baa1b9bac9

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.4-c8acd73b
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-c8acd73b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.4-c8acd73b-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.4-c8acd73b

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-2335225c
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-2335225c-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-2335225c-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-2335225c

---

NOTICE.txt
docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.13.0-toucn398
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.0-p45l43ib-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.0-p45l43ib-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.13.0-toucn398

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-a87bc5c4
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-a87bc5c4-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-a87bc5c4-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-a87bc5c4

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.4-02032cc3
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.11.4-02032cc3-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.11.4-02032cc3-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.4-02032cc3

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/7d5284a232dc
---
<Actions>
<summary>Update to elastic/beats@7d5284a232dc</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 7d5284a232dc&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7423333596">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@7d5284a232dc

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.4-25ab7bee
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-25ab7bee-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.4-25ab7bee-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.4-25ab7bee

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.4-8881462e
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-8881462e-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.4-8881462e-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.4-8881462e

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/95f0f85a3edd
---
<Actions>
<summary>Update to elastic/beats@95f0f85a3edd</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 95f0f85a3edd&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7449196420">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@95f0f85a3edd

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/61337102fc51
---
<Actions>
<summary>Update to elastic/beats@61337102fc51</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 61337102fc51&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7449196420">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@61337102fc51

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/57f0435123e0
---
<Actions>
<summary>Update to elastic/beats@57f0435123e0</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 57f0435123e0&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7462798891">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@57f0435123e0

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/e9372ad9ab1f
---
<Actions>
<summary>Update to elastic/beats@e9372ad9ab1f</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh e9372ad9ab1f&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7462798891">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@e9372ad9ab1f

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.13.0-8upz6ftd
---
<Actions>
<p>3 file(s) updated with &#34;version: 8.13.0-8upz6ftd-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;</p>
</details>
<p>1 file(s) updated with &#34;$1:8.13.0-8upz6ftd-SNAPSHOT&#34;:&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.13.0-8upz6ftd

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.11.4-3f013fd4
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.11.4-3f013fd4-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.11.4-3f013fd4-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.11.4-3f013fd4

---

systemtest/approvals/TestOTLPGRPCLogsClientIP.approved.json

Update geoip approvals to fix failing systemtest

[8.11] systemtest: Update geoip approvals

---

cmd/intake-receiver/version.go
internal/version/version.go

Updates docs versions to 8.11.5.

docs: update docs versions 8.11.5

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/2f45bbdd4f1f
---
<Actions>
<summary>Update to elastic/beats@2f45bbdd4f1f</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 2f45bbdd4f1f&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7530624021">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@2f45bbdd4f1f

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/10b1f7a03aa0
---
<Actions>
<summary>Update to elastic/beats@10b1f7a03aa0</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh 10b1f7a03aa0&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7530624021">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@10b1f7a03aa0

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/a10ace565d03
---
<Actions>
<summary>Update to elastic/beats@a10ace565d03</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a10ace565d03&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7530624021">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@a10ace565d03

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.13.0-sq0d327c
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-sq0d327c-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-sq0d327c-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/kibana.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.13.0-sq0d327c

---

docker-compose.yml
testing/infra/k8s/base/stack/apm-server.yaml
testing/infra/k8s/base/stack/elasticsearch.yaml
testing/infra/k8s/base/stack/kibana.yaml

Bump elastic stack version to 8.12.0-k08v7bga
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.12.0-k08v7bga-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.12.0-k08v7bga-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …

[updatecli] Bump elastic stack version to 8.12.0-k08v7bga

---

NOTICE.txt
go.mod
go.sum

*Changeset*
* https://github.com/elastic/beats/commit/a1cb25125664
---
<Actions>
<summary>Update to elastic/beats@a1cb25125664</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh a1cb25125664&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7543455111">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Update to elastic/beats@a1cb25125664

---

docker-compose.yml

<Actions>
<p>1 file(s) updated with &#34;$1:7.17.17-f603656b-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7543485039">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …

[updatecli] Bump elastic stack version to 7.17.17-f603656b
