README.md, TESTING.md
- proper linking within the _README_ file
- linking to beats test description from _TESTING_ and only giving a very short summary for APM Server testing, hence how to run the tests is all based on and coform with the beats framework.
=> Improve Documentation.

CHANGELOG.asciidoc, _meta/fields.common.yml, docs/data/elasticsearch/error.json, docs/data/elasticsearch/transaction.json, docs/data/intake-api/generated/error/payload.json, docs/data/intake-api/generated/transaction/payload.json, docs/fields.asciidoc, docs/spec/context.json, processor/error/package_tests/TestProcessErrorFull.approved.json, processor/error/schema.go, processor/transaction/package_tests/TestProcessTransactionFull.approved.json, processor/transaction/schema.go, tests/data/valid/error/payload.json, tests/data/valid/transaction/payload.json
After thinking about this for a while, I really don't see why we want to store the status message. So I'd like to suggest that we refactor the `request.status` object which used look like this:
```json
"status": {
"code": 200,
"message": "OK"
}
```
To instead simply be a number and look like this:
```json
"status_code": 200
```
Thoughts?
=> Refactor request.status object to request.status_code number

_meta/kibana/default/dashboard/apm-dashboards.json
This PR updates the dashboards to the latest version. In this update the response time charts for TSVB use the new duration formatter instead of relying on a calculation. This also fixes a few broken links and changes the default index pattern to `apm-server-*`.
=> Update Dashboards to Latest Version

docs/api.asciidoc, docs/elasticsearch-docs.asciidoc, docs/error-api.asciidoc, docs/index.asciidoc, docs/index_pattern.asciidoc, docs/transaction-api.asciidoc
Run `make docs` didn't work with the previous structure. I mainly fixed titles etc. to be a valid asciidoc format for our doc build. It is not the intention to fix the doc structure in this PR but being able to start with the doc build integration which requires a green doc build to start with.
=> Fix docs to have a valid doc build

tests/fields.go
Fixed two swallowed errors in the fields.go file in the tests package.
=> Fix swallowed errors in tests package

CHANGELOG.asciidoc, docs/data/elasticsearch/error.json, docs/fields.asciidoc, processor/error/_meta/fields.yml, processor/error/event.go, processor/error/event_test.go, processor/error/package_tests/TestProcessErrorFull.approved.json, processor/error/package_tests/TestProcessErrorMininmalPayloadException.approved.json, processor/error/package_tests/TestProcessErrorMininmalPayloadLog.approved.json, processor/error/package_tests/json_schema_test.go, processor/error/payload_test.go
Renamed to unify names in the ES data model and in the UI.
closes #82
=> Rename `error.checksum` to `error.grouping_key`.

tests/json_schema_test.go
json_schema_test.go was missing an assert on a defined error.
=> Fix swallowed error in tests package

processor/error/package_tests/TestProcessErrorFull.approved.json, processor/error/package_tests/TestProcessErrorMininmalPayloadException.approved.json, processor/error/package_tests/TestProcessErrorMininmalPayloadLog.approved.json, processor/transaction/package_tests/TestProcessTransactionEmpty.approved.json, processor/transaction/package_tests/TestProcessTransactionFull.approved.json, processor/transaction/package_tests/TestProcessTransactionMinimalPayload.approved.json, processor/transaction/package_tests/TestProcessTransactionMinimalTrace.approved.json, processor/transaction/package_tests/TestProcessTransactionNull.approved.json, tests/approvals.go
with the beat.Event introduction, we no longer put @timestamp in the generated documents, but we should still test timestamps
=> Include timestamp in approval tests

Dockerfile
Before this change I was getting this error on OSX.
```
Step 5/10 : RUN mkdir -p $apm-server_PATH
---> Running in 503d035a8229
mkdir: invalid option -- 's'
Try 'mkdir --help' for more information.
```
=> fix env causing mkdir: invalid option

beater/server.go, processor/error/processor_test.go, processor/registry.go, processor/transaction/processor_test.go, script/output_data/output_data.go
Renames registry getter methods to follow go naming.
@ruflin
Fixes #74
=> Rename registry getter methods

NOTICE, _beats/dev-tools/generate_notice.py, _beats/dev-tools/packer/platforms/centos/run.sh.j2, _beats/dev-tools/packer/platforms/debian/run.sh.j2, _beats/libbeat/_meta/config.reference.yml, _beats/libbeat/_meta/config.yml, _beats/libbeat/tests/system/beat/beat.py, _beats/script/build_docs.sh, _beats/testing/environments/5x.yml, _beats/testing/environments/latest.yml, apm-server.reference.yml, apm-server.yml, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_integration.py, vendor/github.com/elastic/beats/libbeat/cloudid/cloudid.go, vendor/github.com/elastic/beats/libbeat/cmd/export/template.go, vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go, vendor/github.com/elastic/beats/libbeat/outputs/codec/format/format.go, vendor/github.com/elastic/beats/libbeat/outputs/redis/client.go, vendor/github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata/indexing.go, vendor/github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata/kubernetes.go, vendor/github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata/podwatcher.go, vendor/github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata/types.go, vendor/github.com/elastic/beats/libbeat/template/config.go, vendor/github.com/elastic/beats/libbeat/template/field.go, vendor/github.com/elastic/beats/libbeat/template/load.go, vendor/github.com/elastic/beats/libbeat/template/template.go, vendor/vendor.json
Important Changes / Additions:
* Add support for cloud id. See https://github.com/elastic/beats/pull/4964 for more details. This could simplify the onboard for users that use apm-server with the Cloud in the future.
* Be able to overwrite index pattern in the index template. See https://github.com/elastic/beats/pull/4769 for more details. This allows to clean up our system tests.
=> Update beats to bd6981d

CHANGELOG.asciidoc, beater/server.go, processor/error/benchmark_test.go, processor/error/package_tests/processor_test.go, processor/error/processor.go, processor/processor.go, processor/transaction/benchmark_test.go, processor/transaction/package_tests/processor_test.go, processor/transaction/processor.go, processor/validator.go, processor/validator_test.go, script/output_data/output_data.go, tests/approvals.go, tests/fields.go, tests/system/test_integration.py
Fixes #96.
Tests were updated so they reuse processors, like we do in the actual server code.
=> Seperate Processors and Payloads

CHANGELOG.asciidoc, beater/beater.go, beater/server.go, beater/server_test.go, tests/system/apmserver.py
Current behaviour is e.g. that apm-server can happily start with a port already used. 
In such case a socket cannot be opened and the apm-server stays up without complaint, albeit not being able to accept requests.
This makes the apm-server to finish with an error when the underlying http server connection fails.
=> Make apm-server to fail fast

beater/server.go
In production I expect a log message on the error level that I have to do something. For our 400 response no changes are needed on the server as the problem is potentially on the agent side.
Now only if 500 happens an error is logged, all other are logged on debug level if enabled. Otherwise the production log could be flooded with error messages because of invalid requests or tokens which can be pretty normal if the server has a public API.
=> Improve logging for production

beater/server.go, processor/error/payload.go, processor/error/processor.go, processor/transaction/payload.go, processor/transaction/processor.go
This is a first take at adding metrics to the APM server. This is a basic set of metrics to get stats for requests, response and processor internals. We should adjust, add and modify these metrics over time when we see which ones are valuable in production, which ones are not and which ones are missing. This only sets the foundation.
These metrics can be later used to be shipped for monitoring. To access the metrics right now start apm-server as following:
```
./apm-server -e -E http.enabled=true
```
Then you can access the metrics under http://localhost:5066/stats?pretty
Closes https://github.com/elastic/apm-server/issues/99
=> Introduce metrics to apm-server

tests/system/apmserver.py, tests/system/test_integration.py
For the system tests with es, first the apm-server was started and then the index and the template were cleaned up. This leaded to a race where the apm-server loaded the template but it was directly removed again which made some of the tests flaky.
A small tweak was made to the integration tests. The documents are loaded in multiple batches, means when the index exists not necessarly all docs are in. A very short is wait to get all documents available. This does work most of the time and speeds up tests. Assuming not all documents are in the tests still work, but the wait time until the index is refreshed is a bit longer and depends on Elasticsearch.
=> Fix system tests setup order

_meta/beat.yml, apm-server.reference.yml, apm-server.yml, beater/beater.go, beater/config.go, beater/pub.go, beater/server.go, beater/server_test.go
This solution uses an intermediate go-routine accepting batches of events from the http handlers and forwarding these as single events to the beats publisher pipeline. The events are forwarded with infinite retrying enabled. Sending events to the go-routine's channel fails immediately if the channel is full. In this case a 503 response will be returned to the agent.
=> Attempt at generating a 503 if queue is full

CHANGELOG.asciidoc, _meta/fields.common.yml, beater/beater.go, beater/client.go, beater/onboarding.go, beater/onboarding_test.go, beater/server_test.go, docs/fields.asciidoc, processor/error/package_tests/fields_test.go, processor/error/package_tests/json_schema_test.go, processor/transaction/package_tests/fields_test.go, processor/transaction/package_tests/json_schema_test.go, tests/system/test_integration.py
For the UI an onboarding doc is needed to see when the server is actually started. A doc is pushed with the field `up: true` and the `@timestamp` when it was pushed. This happens on each startup.
The code checks that the HTTP Server is running and as soon as this is the case, sends the doc.
This PR takes over the previous work from #110
=> Push onboarding doc on startup

_beats/libbeat/docs/version.asciidoc, cmd/root.go
Because of the libbeat dependency apm-server was built with 6.0.0-beta1 instead of 7.0.0-alpha1 from master. This is a manual fix which will be automated in a follow up PR.
=> Fix apm-server build

beater/beater_test.go, beater/server.go
This adds a dummy output instead of the Elasticsearch output that you'd use in the real world. For inputting data, the tests skips the network layer and input data directly in the http server from the test.
Different size payloads are created to see how the apm-server performance scales with different size payloads for transactions and errors.
Instructions on how to run them is included.
```
$ go test beater/*.go -run=XXX -bench=. -cpuprofile=cpu.out -args -e
-d *
BenchmarkTransactionsEndToEnd100Entries-8     	     200	   8354740 ns/op
--- BENCH: BenchmarkTransactionsEndToEnd100Entries-8
beater_test.go:101: Using payload size: 68823
beater_test.go:101: Using payload size: 68823
beater_test.go:101: Using payload size: 68823
BenchmarkErrorsEndToEnd100Entries-8           	     200	   8011345 …
```
=> Simple benchmark tests which almost tests end to end.

Makefile, NOTICE, _beats/dev-tools/packer/platforms/debian/run.sh.j2, _beats/dev-tools/packer/version.yml, _beats/libbeat/_meta/kibana/default/index-pattern/libbeat.json, _beats/libbeat/docs/version.asciidoc, _beats/libbeat/scripts/Makefile, _beats/libbeat/scripts/migrate_beat_config_1_x_to_5_0.py, _beats/update.sh, cmd/root.go, vendor/github.com/elastic/beats/libbeat/cfgfile/reload.go, vendor/github.com/elastic/beats/libbeat/publisher/pipeline/batch.go, vendor/github.com/elastic/beats/libbeat/publisher/pipeline/controller.go, vendor/github.com/elastic/beats/libbeat/publisher/pipeline/monitoring.go, vendor/github.com/elastic/beats/libbeat/publisher/pipeline/output.go, vendor/github.com/elastic/beats/libbeat/publisher/pipeline/pipeline.go, vendor/github.com/elastic/beats/libbeat/publisher/pipeline/retry.go, vendor/github.com/elastic/beats/libbeat/template/field.go, vendor/github.com/elastic/beats/libbeat/template/fields.go, vendor/github.com/elastic/beats/libbeat/template/template.go, vendor/github.com/elastic/beats/libbeat/version/version.go, vendor/vendor.json
A small trick is applied to still get beats code from the 6.x branch but have the versions from the 6.0 branch. The two required files are fetched seperately. The changes were made in the code instead of modifying the two files manually to be able to just run `make update-beats` also in the future without overwriting it again.
=> Update beats to 1ee5c9 in 6.0 branch

cmd/root.go
The correct version is automatically inherited from beats. As our master branch depends on the beats master branch again, having our own version in here is not needed anymore.
=> Remove fixed version from apm-server

docs/spec/errors/error.json, docs/spec/transactions/transaction.json, processor/error/schema.go, processor/transaction/schema.go, tests/json_schema_test.go, tests/system/test_requests.py
=> Use format instead of a regex in json schema to validate timestamps 

docs/spec/errors/error.json, docs/spec/transactions/transaction.json, processor/error/schema.go, processor/transaction/schema.go, tests/data/invalid/error/invalid_timestamp2.json, tests/data/invalid/transaction/invalid_timestamp2.json, tests/json_schema_test.go, tests/system/test_requests.py
This complements `date-format` used for proper date validation with a `Z$` regex to make sure that timezone offsets are not allowed (as per spec)
=> Don't allow timezone offsets for timestamps

beater/pub.go
In benchmarks (we've not reproduced this outside, yet), we sometimes get a full-queue even though we've using a "null" output. This happens because the go scheduler is not running the go routines that take events out of the queue as much time as we'd like it to. By introducing a one second timeout, this is an attempt at giving the go runtime some time to run those go routines some time to run. 
I'm not a big fan of the UX of taking an extra second to return a 503 to the user in the case where the queue is really full, but it might be the best solution for now.
=> Ensure libbeat infrastructure has time to run before returning 503

_meta/fields.common.yml, docs/fields.asciidoc, tests/fields.go
To be aligned with documentation of other non-indexed fields and to
avoid unwanted side effects in indexing, remove `context.db` from fields.yml.
=> Remove non-indexed entry from fields.yml.

README.md
Running the additional cmd can be removed again, once all necessary files from
beats are created with the build cmd or checked in into git.
=> Update Readme to run `make update` for apm-server.

CHANGELOG.asciidoc
- Remove `git_ref` #158 
- Remove `context.db` from fields.yml #159.
@sqren , @vanjacosic please have a look - I hope this does not break anything on your side.
@simianhacker I removed the `git_ref` info from the dashboards and checked them afterwards, so I don't expect dashboard related issues.
=> Add changes to changelog.

beater/server.go, beater/server_test.go
WriteHeader(code) needs to be called after headers are set.
closes #167.
=> Fix wrong content-type in response.

beater/server.go
+ Logs `202` responses with debug level
+ Fixes monitoring counting (503 were counted as valid _and_ invalid)
+ Removes unused param and named return args from method
+ Removes duplicated messages from errors (eg: something like "data validation error" is already in the original error, there is no need to wrap it)
+ Simplifies code a bit
=> Minor logging fixes

Makefile
Only Info, Warning and Errors should be printed, instead of every
command.
=> Avoid cmd output from Makefile.

docs/index.asciidoc
The text in the square brackets in the `include::` statements have no function. It's the main headline of the included files that are used in the menu, and not this text.
=> Clean up docs index

docs/index.asciidoc
This adds the following notice to the top of the index.asciidoc page if viewed on GitHub:
I had to write the URL in full instead of using asciidoc references as those are not resolved when the asciidoc is rendered by GitHub.
=> Add link to official documentation when viewing docs on GitHub

docs/guide/apm-getting-started.asciidoc
Fixed command to import dashboards, added compatibility section and temporarily updated the binary download link, so users can use this getting started article from now on.
=> Fixed curl import and added Compatibility section

docs/guide/apm-getting-started.asciidoc
This PR does the following:
- Adds ID's to all headlines
- Removes `$` from all bash scripts
- Adds line breaks after all commas and periods (maybe a little too aggressive, but at least consistent)
- Break up long bash commands into multiple lines
- Add blank line after all headlines
- Remove double blank lines
=> Clean up asciidoc style in getting started guide

README.md
Instead of maintaining two Getting Started guides, this PR just updates the one in the README.md to point to the one in the online docs.
=> Update Getting Started in README.md

docs/guide/page_header.html
The header for preliminary docs was missing for the getting started guide for APM.
=> Add preliminary header to get started documents.

_meta/kibana/default/dashboard/apm-dashboards_v5.6.json
This PR add a 5.6 compatible dashboard. This is required because the savedSearch definitions in Kibana change the format of the URL along with the saved object definitions.
=> Adding 5.6 compatible dashboards

docs/guide/index.asciidoc
The command contained the `_meta` directory as this is needed when loading directly from the repository. When download the binary the _meta directory does not exist.
=> Fix command for loading dashboards in docs

tests/agent/python/Dockerfile
I just merged the `feature/elastic-apm` branch into master on the opbeans repo, making this switch unnecessary.
=> opbeans master is now configured for elastic, no need to switch branch

beater/config_test.go, beater/server_test.go
* Add tests for configuration handling.
* Fix bug for check wheterh SSL is enabled.
As a first attempt to add and cleanup tests in the beater module I quickly added some tests to the config. If I remember the logic, whether or not SSL should be enabled, correctly then I found a bug in the current checks.
=> Add tests for beater config.

docs/guide/index.asciidoc
@makwarth , @ruflin this is a follow up for changing the docs. Unfortunately the changes in PR #147 were applied to a file that does not exist anymore, since we moved it to the docs folder. 
The thing that I am not certain of is how to actually pass in `user` and `password` for x-pack secured systems.
@ruflin can you help out here? I tried all listed config options..
=> Change docs for automatic loading of dashboards.

beater/handlers_test.go, processor/processor.go
Hi @simitt and @jalvz .  Per our discussion, I was playing around with a fail delay in isAuthorized(). I ultimately decided that such a delay could actually cause more problems than it would prevent in the case of a highly parallel attack (tying up goroutines).  But I'd already written up the unit tests for that function, so feel free to use them if you want.
Thanks,
Jim
=> Add isAuthorized unit tests

script/jenkins/update-beats.sh
Run testsuite when beats framework is updated to ensure compatibility with the beats framework.
This gets triggered after a PR is merged into `beats` `master` or `release` branch, see https://github.com/elastic/infra/pull/3006, and allows to get rid of the dependency in `beats` (https://github.com/elastic/beats/pull/5099).
=> Add test for updating beats framework.

docs/guide/index.asciidoc
Add note that Kibaan-6.0.0-rc1 is required for dashboards.
=> Update docs for dashboards Kibana compatibility.

docs/configuring.asciidoc, docs/copied-from-beats/repositories.asciidoc, docs/copied-from-beats/running-on-docker.asciidoc, docs/index.asciidoc, docs/installing.asciidoc, docs/overview.asciidoc
Reorganized into two steps: installing + configuring and running.
Closes https://github.com/elastic/apm-server/issues/210
Relies on https://github.com/elastic/beats/pull/5460.
=> Added docs on docker and repositories

docs/copied-from-beats/version.asciidoc, docs/index.asciidoc
The change is necessary as the folder outside of `docs` is not available by default.
=> Move beats dependency inside docs folder.

docs/guide/index.asciidoc
Revert commit for documenting how to load dashboards.
Add note that rc1 of Kibana is required for the dashboards to work properly.
=> Add note for dashboards

NOTICE.txt, _meta/beat.reference.yml, _meta/beat.yml, apm-server.reference.yml, apm-server.yml, beater/config.go, beater/handlers.go, beater/handlers_test.go, beater/server_test.go, tests/system/config/apm-server.yml.j2, tests/system/test_requests.py, vendor/github.com/hashicorp/golang-lru/2q.go, vendor/github.com/hashicorp/golang-lru/LICENSE, vendor/github.com/hashicorp/golang-lru/README.md, vendor/github.com/hashicorp/golang-lru/arc.go, vendor/github.com/hashicorp/golang-lru/lru.go, vendor/github.com/hashicorp/golang-lru/simplelru/lru.go, vendor/golang.org/x/time/LICENSE, vendor/golang.org/x/time/PATENTS, vendor/golang.org/x/time/rate/rate.go, vendor/golang.org/x/time/rate/rate_go16.go, vendor/golang.org/x/time/rate/rate_go17.go, vendor/vendor.json
This is cherry-picked from https://github.com/elastic/apm-server/pull/207, which is somewhat old so after merging it doesn't look much like it anymore.
The main goal of this is to add per IP rate limiting. 
Approach in #207 with `context.Wait` is smart, but it becomes hairy when you need one `ctx` per IP, a call to `Allow` is much simpler. 
Main functional difference is that in #207, is that if the bucket is refilled with a token within `readTimeout` seconds, then the request goes trough; in here it gets rejected right away.
I don't consider this a substantial difference.
For now, i also got rid of the burst to avoid over-configuration.
=> Rate limiter per IP for frontend agents

_beats/dev-tools/packer/version.yml
This commit bumps the version on the apm-server artifact to 6.0.0.
=> Bump version to 6.0.0

_meta/beat.reference.yml, apm-server.reference.yml, beater/config.go, beater/handlers.go, beater/server_test.go, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_requests.py
This allows users to configure a valid origin, so that the apm-server won't accept requests from different origins. It handles preflight OPTIONS as per CORS spec.
It makes it possible to specify a list of allowed origins as well as `*` for any origin.
=> Backport to 6.0: support OPTIONS method needed for preflight browser requests (#244)

tests/system/test_requests.py
eg: https://beats-ci.elastic.co/job/elastic+apm-server+pull-request+multijob-windows/349/beat=apm-server,label=windows/testReport/junit/test_requests/SecureTest/test_https_ok/
=> disable urllib warnings so that it doesn't break tests with unexpected exit code 2

docs/spec/app.json, docs/spec/app_core.json, processor/error/package_tests/json_schema_test.go, processor/error/schema.go, processor/transaction/package_tests/json_schema_test.go, processor/transaction/schema.go, tests/common.go, tests/json_schema.go, tests/json_schema_test.go
I took a stab at trying to split the app core values out in a simple way.
The advantage that i see in of this approach is that:
* We're still testing the actual production json schemas. I think this is quite important.
* The `$ref` logic only needs to exist in `inline_schemas.go` (was duplicate in `flattenJsonKeys` before)
* We get to keep `TestJsonSchemaKeywordLimitation`
* `flattenJsonKeys` stays simple - doesn't deal with json specs
the cons:
* `flattenSchemaNames` know about `allOf` now (+5 lines)
Lets discuss IRL
=> App core split

tests/system/test_requests.py
urllib3 might or might not be vendored inside requests, this disables urllib warnings in any case to keep CI happy.
=> Disable (vendored) urllib3 warnings

processor/error/package_tests/processor_test.go, processor/transaction/package_tests/processor_test.go, tests/approvals.go, tests/scripts/approvals.go
Allow to ignore defined keys when comparing two files with approvals.
=> Add ignored key list to approval check.

tests/system/apmserver.py, tests/system/test_requests.py
This is needed so windows tests don't break with an unexpected exit code.
This might happen inside the test, or during tearDown, so disabling needs to happen for the whole class.
urllib3 might or might not be vendored inside the requests package.
=> Disable urllib3 ssl warnings (again) at class level.

tests/agent/nodejs/express/app.js
Use the new maxQueueSize instead of the flushInterval.
This will flush the queue instantly instead of after one second
=> Improve Node.js agent test

script/jenkins/update-beats.sh
In case the go version gets updated in beats, the check on Jenkins still runs on the old version. With this fix the go version is set again after updating to beats, before running the checks.
=> Use updated go version in update-beats jenkins check.

Makefile
Fixed: The message printed would have the wrong git commit hash.
=> Fix "update beats" message.

docs/copied-from-beats/version.asciidoc
Reverts elastic/apm-server#322
This was too early. Docs are being built from this branch and there's no 6.0.1 yet.
=> Revert "Update docs build to 6.0.1."

CHANGELOG.asciidoc, docs/data/elasticsearch/trace.json, docs/fields.asciidoc, processor/transaction/_meta/fields.yml, processor/transaction/package_tests/TestProcessTransactionFull.approved.json, processor/transaction/package_tests/TestProcessTransactionMinimalTrace.approved.json, processor/transaction/package_tests/TestProcessTransactionNullValues.approved.json, processor/transaction/package_tests/json_schema_test.go, processor/transaction/payload_test.go, processor/transaction/trace.go, processor/transaction/trace_test.go
implements #291 
note: this will break kibana UI badly
=> move trace.transaction_id to trace.transaction.id

vendor/vendor.json
Those packages were still mentioned in the govendor file, but the packages aren't vendored and no where used.
=> Remove unused govendor entries.

tests/system/apmserver.py, tests/system/test_integration.py
This fixes the currently failing tests for the `6.x` branch, by increasing the timeout for server startup and ensuring clean startup by deleting index and template at setup. 
Should be backported to `6.1` afterwards.
=> Fix index and template deletion for testing.

docs/installing-on-windows.asciidoc, docs/installing.asciidoc
Tested instructions for installing on windows.
The instructions are more or less copied from https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation.html
=> Added instructions for installing on Windows.

CHANGELOG.asciidoc, docs/data/elasticsearch/error.json, docs/data/elasticsearch/span.json, docs/data/intake-api/generated/error/payload.json, docs/data/intake-api/generated/transaction/null_values.json, docs/data/intake-api/generated/transaction/payload.json, docs/spec/stacktrace_frame.json, model/stacktrace_frame.go, model/stacktrace_frame_test.go, processor/error/package_tests/TestProcessErrorFull.approved.json, processor/error/schema.go, processor/transaction/package_tests/TestProcessTransactionFull.approved.json, processor/transaction/schema.go, tests/data/valid/error/payload.json, tests/data/valid/transaction/null_values.json, tests/data/valid/transaction/payload.json
=> rename in_app to library_frame, reversing meaning

beater/server.go, cmd/root.go
In #396 I introduced a bug where the index name contained invalid characters
that were added to the global version.
=> do not change version globally, just print it on startup

docs/security.asciidoc
The asciidoc reference was incorrect, so it wasn't resolving. As a result, there is missing text in the published doc.
Note that the doc build does not flag missing asciidoc attributes as errors.  There's an issue open in the docs repo, but there's no resolution on it yet: https://github.com/elastic/docs/issues/220
=> Fix attribute to resolve link to agents ref

docs/configuring.asciidoc, docs/guide/index.asciidoc
Closes #387.
APM Server docs:
Getting started guide:
=> Document setting user+pwd in config file

.gitattributes
from the docs:
Run 3-way file level merge for text files, but take lines from both
versions, instead of leaving conflict markers. This tends to leave the
added lines in the resulting file in random order and the user should
verify the result. Do not use this if you do not understand the
implications.
=> use merge=union for changelog

CHANGELOG.asciidoc, beater/handlers.go, beater/handlers_test.go
before:
```
{"error":"Decoding error: Data read error: unexpected EOF"}
```
after:
```
{"error":"while decoding: data read error: http: request body too large"}
```
closes #438
=> report more detail on max data size error

processor/error/event.go, processor/error/event_test.go, processor/error/package_tests/TestProcessErrorFull.approved.json, processor/error/package_tests/TestProcessErrorNullValues.approved.json, processor/error/payload_test.go
if nothing else is available
closes #402
=> consider exception or log message for grouping key

CHANGELOG.asciidoc, docs/data/elasticsearch/transaction.json, docs/data/intake-api/generated/transaction/null_values.json, docs/data/intake-api/generated/transaction/payload.json, docs/fields.asciidoc, docs/spec/transactions/transaction.json, processor/transaction/_meta/fields.yml, processor/transaction/event.go, processor/transaction/event_test.go, processor/transaction/package_tests/TestProcessTransactionFull.approved.json, processor/transaction/schema.go, tests/data/valid/transaction/null_values.json, tests/data/valid/transaction/payload.json
=> Support dropped span_count on transactions.

CHANGELOG.asciidoc, Makefile, _beats/dev-tools/packer/readme.md.j2, script/update_beats.sh
This moves control of `_beats/dev-tools/packer/readme.md.j2` into the apm repo rather than trying to templatize it under beats.  README ends up as:
```
Sends events to Elasticsearch or Logstash
To get started with apm-server, you need to set up Elasticsearch on your localhost first. After that, start apm-server with:
./apm-server -c apm-server.yml -e
This will start apm-server and send the data to your Elasticsearch instance. To load the dashboards for apm-server into Kibana, run:
./apm-server setup -e
For further steps visit the [Getting started](https://www.elastic.co/guide/en/apm/get-started/master/) guide.
Visit [Elastic.co Docs](https://www.elastic.co/guide/en/apm/server/master/) for the full apm-server documentation.
```
closes #356
=> update readme doc urls

script/update_beats.sh, script/update_govendor_deps.py
fixes #450.  Adds 45 seconds to `make update-beats` on my machine.
includes 2 bug fixes too introduced in #449:
* `#!/usr/bin/env bash -ex` is not portable apparently, switched to `env bash` and a `set -ex`
* `BEATS_VERSION` specification only worked for branches
=> update beats' deps too

beater/handlers.go, utility/handlers.go
Initial work on streamlining logging and moving towards structured logging.
beats introduced structured logging. The fact that we output JSON on the command line was part of this and it's already merged in beats.
This PR only deals with what we can control in APM Server. I'm looking into if we can use a key-value style instead of the JSON when started with `-e`.
With this, we will always log something like this for each request:
```
2018-01-05T16:19:39.317+0100	INFO	[request]	beater/handlers.go:137	handled request	{"request_id": "180acb9f-2128-4955-97e6-2485b6330d8c", "response_code": 200, "method": "GET", "URL": "/healthcheck", "content_length": 0, "remote_address": "127.0.0.1", "user_agent": "Go-http-client/1.1"}
```
Errors get another line:
```
2018-01-05T16:19:52.433+0100	ERROR …
```
=> Streamline logging

beater/beater.go, beater/beater_test.go, beater/config.go, beater/config_test.go, beater/handlers.go, beater/onboarding.go, beater/onboarding_test.go, beater/server.go, beater/server_test.go
* Add config tests
* Change handling to not overwrite default config values.
The `defaultConfig` is only used once in production code. However, adding the config tests revealed that the beater currently changes the `defaultConfig` when [unpacking the ucfg](https://github.com/simitt/apm-server/blob/master/beater/beater.go#L19).
This change avoids having the `defaultConfig` overwritten, which could lead to issues in the future when used after initializing the beat.
=> Avoid overwriting default config of beat.

beater/beater.go, beater/beater_test.go, beater/config.go, beater/config_test.go, beater/handlers.go, beater/onboarding.go, beater/onboarding_test.go, beater/server.go, beater/server_test.go
- Avoid overwriting default config of beat.  (#464)
=> [6.x] Avoid overwriting default config of beat. (#464)

beater/beater.go, beater/onboarding_test.go, beater/server.go, beater/server_test.go
Inspired by #466, this doesn't perfectly resolve that, but makes it even less likely.  This does resolve issues running `server_test`s while port 8200 is already in use - that currently hangs until `waitForServer` times out.  It also eliminates suspected issues from opening a random port, closing it, and immediately reopening it via `randomAddr()`.
=> create listener separate from starting server

_meta/beat.reference.yml, apm-server.reference.yml, beater/beater_test.go, beater/config.go, beater/config_test.go, sourcemap/accessor.go, sourcemap/accessor_test.go, sourcemap/cache.go, sourcemap/cache_test.go, sourcemap/mapper.go
- Cleanup sourcemap config.  (#475)
=> [6.x] Cleanup sourcemap config. (#475)

beater/beater.go, beater/onboarding_test.go, beater/server.go, beater/server_test.go
* create listener separate from starting server (#474)
=> [6.x] create listener separate from starting server (#474)

_meta/beat.reference.yml, apm-server.reference.yml, beater/beater_test.go, beater/config.go, beater/config_test.go, beater/handlers.go, model/stacktrace_frame.go, model/stacktrace_frame_test.go, processor/error/package_tests/TestProcessErrorFrontendMinified.approved.json, processor/error/package_tests/TestProcessErrorFrontendNoSmap.approved.json, processor/error/package_tests/processor_test.go, processor/processor.go, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_integration.py
- Detect library_frames for frontend stacktraces.  (#481)
=> [6.x] Detect library_frames for frontend stacktraces. (#481)

CHANGELOG.asciidoc, model/stacktrace.go, model/stacktrace_test.go, processor/error/event_test.go, processor/error/package_tests/TestProcessErrorFrontendMinified.approved.json, processor/error/payload_test.go, processor/transaction/span_test.go
Allow using transformed stack trace frame values for calculation.
Right now we change the values of stacktrace frames in the `Transform` method, but as the `stacktrace` doesn't hold pointer references to the stacktrace frames the changed values are not available for the `error` objects holding `stacktraces`. This leads to the usage of the wrong frame information, in case it was changed, as e.g. for sourcemapping.
=> Use Stacktrace Frame pointers.

CHANGELOG.asciidoc, model/stacktrace.go, model/stacktrace_test.go, processor/error/event_test.go, processor/error/package_tests/TestProcessErrorFrontendMinified.approved.json, processor/error/payload_test.go, processor/transaction/span_test.go
- Use Stacktrace Frame pointers.  (#485)
=> [6.x] Use Stacktrace Frame pointers. (#485)

_meta/fields.common.yml, docs/fields.asciidoc, docs/spec/context.json, docs/spec/transactions/mark.json, processor/error/schema.go, processor/transaction/_meta/fields.yml, processor/transaction/schema.go
- Add type to description for `context.tags`, `transaction.marks`.  (#493)
=> [6.x] Add type to description for `context.tags`, `transaction.marks`. (#493)

script/update_govendor_deps.py
- Fix beats-update script to return when up-to-date.  (#490)
=> [6.x] Fix beats-update script to return when up-to-date. (#490)

processor/error/package_tests/TestProcessErrorFrontendNoSmap.approved.json, sourcemap/id.go, sourcemap/mapper.go
- Put single quotes around smap error values.  (#487)
=> [6.x] Put single quotes around smap error values. (#487)

CHANGELOG.asciidoc, _meta/beat.reference.yml, apm-server.reference.yml, beater/beater_test.go, beater/config.go, beater/handlers.go, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_integration.py, tests/system/test_requests.py
Primarily for use with the [metricbeat golang module](https://www.elastic.co/guide/en/beats/metricbeat/6.1/metricbeat-module-golang.html).
=> optionally expose expvar

CHANGELOG.asciidoc
Removed duplicate: 
* Support for `transaction.marks` {pull}430[430]
And added whitespace to "Increase default 'ConcurrentRequests .." to fix rendering.
=> Minor fixes to changelog

docs/version.asciidoc
This PR updates the "doc-branch" attribute value from "6.x" to "6.2".
=> [DOCS] Updated doc-branch version

Makefile
now that apm ci is split out from beats, use the direct apm-server dep
=> override TESTIFY_TOOL_REPO

beater/pub.go
- Fix panic when exiting under load  (#556)
=> [6.x] Fix panic when exiting under load (#556)

LICENSE.txt
- Update License to 2018  (#558)
=> [6.x] Update License to 2018 (#558)

_meta/fields.common.yml, docs/data/elasticsearch/error.json, docs/data/elasticsearch/transaction.json, docs/data/intake-api/generated/error/payload.json, docs/data/intake-api/generated/transaction/payload.json, docs/fields.asciidoc, docs/spec/process.json, model/process.go, processor/error/package_tests/TestProcessErrorFull.approved.json, processor/error/schema.go, processor/transaction/package_tests/TestProcessTransactionFull.approved.json, processor/transaction/schema.go, tests/data/valid/error/payload.json, tests/data/valid/transaction/payload.json
- Add `process.ppid` as optional field.  (#557)
=> [6.x] Add `process.ppid` as optional field. (#557)

CHANGELOG.asciidoc
- Adapt changelog to add optional process.ppid  (#564)
=> [6.x] Adapt changelog to add optional process.ppid (#564)

README.md, TESTING.md, tests/docker-compose.yml
- Update manual testing guide and docker-compose.  (#555)
=> [6.x] Update manual testing guide and docker-compose. (#555)

beater/pub.go
- Fix panic when exiting under load  (#556)
=> [6.2] Fix panic when exiting under load (#556)

CHANGELOG.asciidoc, model/stacktrace_frame.go, model/stacktrace_frame_test.go, processor/error/event.go, processor/error/event_test.go, processor/error/package_tests/TestProcessErrorFrontend.approved.json, processor/error/package_tests/TestProcessErrorFrontendMinifiedSmap.approved.json, processor/error/package_tests/TestProcessErrorFrontendNoSmap.approved.json, processor/error/package_tests/processor_test.go
- Change error.culprit after successful source mapping.  (#520)
=> [6.x] Change error.culprit after successful source mapping. (#520)

docs/copied-from-beats/debugging.asciidoc, docs/copied-from-beats/getting-help.asciidoc, docs/index.asciidoc, docs/troubleshooting.asciidoc
- Add troubleshooting section to docs.  (#551)
=> [6.x] Add troubleshooting section to docs. (#551)

docs/copied-from-beats/debugging.asciidoc, docs/copied-from-beats/getting-help.asciidoc, docs/index.asciidoc, docs/troubleshooting.asciidoc
- Add troubleshooting section to docs.  (#551)
=> [6.2] Add troubleshooting section to docs. (#551)

CHANGELOG.asciidoc, beater/beater.go
Introduce a flag and a mutex in the beater so that we can't stop the server before assigning it (ie. read before write)
fixes #514
=> Fix panic when a signal is delivered before the server is instantiated

docs/frontend.asciidoc
I accidentially removed the link to sourcemaps with a previous docs update.
=> Re-add sourcemap description.

docs/frontend.asciidoc
- Re-add sourcemap description.  (#595)
=> [6.x] Re-add sourcemap description. (#595)

docs/frontend.asciidoc
- Re-add sourcemap description.  (#595)
=> [6.2] Re-add sourcemap description. (#595)

docs/guide/index.asciidoc, docs/index.asciidoc
- Fix broken link and remove beta label  (#596)
=> [6.2] Fix broken link and remove beta label (#596)

docs/guide/index.asciidoc, docs/index.asciidoc
- Fix broken link and remove beta label  (#596)
=> [6.x] Fix broken link and remove beta label (#596)

docs/guide/index.asciidoc, docs/index.asciidoc, docs/version.asciidoc
- Set :branch: to :doc-branch: from version.asciidoc  (#601)
=> [6.x] Set :branch: to :doc-branch: from version.asciidoc (#601)

docs/guide/index.asciidoc, docs/index.asciidoc, docs/version.asciidoc
- Set :branch: to :doc-branch: from version.asciidoc  (#601)
=> [6.2] Set :branch: to :doc-branch: from version.asciidoc (#601)

docs/guide/index.asciidoc
- Attempt at fixing docs failure  (#611)
=> [6.x] Attempt at fixing docs failure (#611)

docs/guide/index.asciidoc
- Attempt at fixing docs failure  (#611)
=> [6.2] Attempt at fixing docs failure (#611)

docs/guide/page_header.html, docs/page_header.html
I hope this is the correct approach for fixing something directly on a version branch
=> docs: fix typo in 6.1 doc page header

CONTRIBUTING.md
Content have not been changed, only line breaks. This makes future diffs more useful and follows our documentation guidelines used in our regular docs.
=> Add line breaks after punctuation in CONTRIBUTING.md

Makefile
make docs without removing '/build' first behaves in a unexpected way
=> target for clean and docs together

docs/index.asciidoc
fixes #627 
Fixed: 
released atm:
=> Fix broken doc links.

docs/index.asciidoc
- Fix broken doc links.  (#628)
=> [6.x] Fix broken doc links. (#628)

docs/index.asciidoc
- Fix broken doc links.  (#628)
=> [6.2] Fix broken doc links. (#628)

docs/guide/index.asciidoc
- Fix broken links in apm getting started (#632)
=> [6.x] Fix broken links in apm getting started

docs/guide/index.asciidoc
- Fix broken links in apm getting started (#632)
=> [6.2] Fix broken links in apm getting started

CONTRIBUTING.md, README.md
- document code contribution workflow  (#590)
- Add line breaks after punctuation in CONTRIBUTING.md  (#619)
=> [6.x] document code contribution workflow (#590) | Add line breaks after punctuation in CONTRIBUTING.md (#619)

docs/copied-from-beats/getting-help.asciidoc, docs/index.asciidoc, docs/troubleshooting.asciidoc
- Update docs copied from beats to use variables.  (#591)
=> [6.x] Update docs copied from beats to use variables. (#591)

_meta/beat.reference.yml, apm-server.reference.yml, beater/beater_test.go, beater/config.go, beater/handlers.go, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_integration.py, tests/system/test_requests.py
- optionally expose expvar 
* add changelog and config file entries (#509)
=> [6.x] optionally expose expvar (#509)

beater/client.go, beater/handlers.go, beater/onboarding.go, beater/server.go, model/stacktrace_frame.go, processor/error/payload.go, processor/sourcemap/payload.go, processor/transaction/payload.go, sourcemap/accessor.go, sourcemap/cache.go
- remove deprecated usages of logp  (#583)
=> [6.x] remove deprecated usages of logp (#583)

sourcemap/elasticsearch.go, sourcemap/mapper.go, tests/system/apmserver.py, tests/system/test_integration.py
- Log a warning for sourcemap uploads and fetches with duplicated caching keys  (#610)
=> [6.x] Log a warning for sourcemap uploads and fetches with duplicated caching keys (#610)

CHANGELOG.asciidoc, docs/data/intake-api/generated/error/frontend.json, model/stacktrace_frame.go, model/stacktrace_frame_test.go, model/stacktrace_test.go, processor/error/package_tests/TestProcessErrorFrontend.approved.json, processor/error/package_tests/TestProcessErrorFrontendMinifiedSmap.approved.json, tests/data/valid/error/frontend.json
Persist original values when
* applying source mapping
* setting library_frame indicator
by storing original values within `original` namespace.
Ensure transform operation is idempotent,
by using original values if applied multiple times.
implements #566
=> Keep original values when transforming.

CHANGELOG.asciidoc, _meta/beat.reference.yml, _meta/beat.yml, apm-server.reference.yml, apm-server.yml, beater/beater.go, beater/beater_test.go, beater/config.go, beater/config_test.go, beater/handlers.go, beater/onboarding_test.go, beater/server_test.go, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_integration.py
- Send sourcemap docs to own index by default.  (#582)
=> [6.x] Send sourcemap docs to own index by default. (#582)

docs/copied-from-beats/getting-help.asciidoc, docs/index.asciidoc, docs/troubleshooting.asciidoc
- Update docs copied from beats to use variables.  (#591)
=> [6.2] Update docs copied from beats to use variables. (#591)

docs/guide/index.asciidoc
- docs: fix missing app -> service renames  (#660)
=> [6.x] docs: fix missing app -> service renames (#660)

docs/guide/index.asciidoc
- docs: fix missing app -> service renames  (#660)
=> [6.2] docs: fix missing app -> service renames (#660)

docs/copied-from-beats/dashboardsconfig.asciidoc
Describe that `setup.dashboards.index`
only works for >= 6.0
closes #519 
As elastic/beats#6197 was merged, I updated it also in apm-server.
=> Add note to docs for dashboard loading.

NOTICE.txt, _beats/testing/environments/args.yml, _beats/testing/environments/docker/kibana/Dockerfile, vendor/github.com/elastic/beats/libbeat/monitoring/report/elasticsearch/elasticsearch.go, vendor/vendor.json
fixes test setup that relied on older 6.2 elastic stack snapshots
=> Update beats framework to 7dd818f

_beats/testing/environments/args.yml
since 7.0.0-alpha1 builds are currently having an issue
=> temporarily test against es 6.2.2

model/process.go, model/service.go, model/stacktrace_frame.go, model/system.go, processor/error/event.go, processor/error/package_tests/TestProcessErrorNullValues.approved.json, processor/error/payload.go, processor/error/processor.go, processor/processor.go, processor/sourcemap/payload.go, processor/sourcemap/processor.go, processor/transaction/event.go, processor/transaction/event_test.go, processor/transaction/package_tests/TestProcessTransactionNullValues.approved.json, processor/transaction/payload.go, processor/transaction/payload_test.go, processor/transaction/processor.go, processor/transaction/span.go, utility/doc_mapping.go, utility/map_str_enhancer.go, utility/map_str_enhancer_test.go
* get rid of docMapper for memory improvement
* refactor enhancer utility method
* adapt transaction spans to be an []*Span instead of []Span
Memory measurements using:
```
var mem runtime.MemStats
runtime.ReadMemStats(&mem)
h2 := mem.HeapAlloc / 1024
l.Infof("HEAP Transform middle : %v", h2)
ttt := pa.transform(p.config) 
runtime.ReadMemStats(&mem)
h3 := mem.HeapAlloc / 1024
l.Infof("HEAP Transform after: %v, %v", h3, h3-h2)
```
Running APM Server with turned off GC `GOGC=off ./apm-server` to see how much memory is allocated for the `pa.transform(p.config)` action leads to following results, comparing this branch to `master`:
* [Transaction Test example](https://github.com/elastic/apm-server/blob/master/tests/data/valid/transaction/payload.json), decoded size 56 KB:
`master`: 43KB …
=> Refactor Event creation and enhancer utility method.

decoder/decoder.go, decoder/decoder_test.go
- accept application/json; charset=UTF-8 as contentType in the request, fixes #676 (#677)
=> [6.x] accept application/json; charset=UTF-8 as contentType in the request, fixes #676

CHANGELOG.asciidoc
- "Rotate" changelog and add new entry (#677)
=> [6.x] "Rotate" changelog and add new entry

CHANGELOG.asciidoc, docs/spec/context.json, docs/spec/errors/error.json, docs/spec/process.json, docs/spec/stacktrace_frame.json, docs/spec/transactions/span.json, docs/spec/transactions/transaction.json, docs/spec/user.json, processor/error/schema.go, processor/transaction/schema.go, tests/json_schema_test.go
In most cases where type: number has been used in the json schema files,
floating point numbers are not neccessary.
This change allows automated tools like the jsonschema2pojo converter to
generate Integer instead of Double fields.
In these instances, I didn't change `number` to `integer`:
```
transactions/Mark.patternProperties
transactions/Span.duration
transactions/Span.start
transactions/Transaction.duration
```
=> Use type integer instead of number where applicable

CHANGELOG.asciidoc, docs/data/intake-api/generated/error/frontend.json, model/stacktrace_frame.go, model/stacktrace_frame_test.go, model/stacktrace_test.go, processor/error/package_tests/TestProcessErrorFrontend.approved.json, processor/error/package_tests/TestProcessErrorFrontendMinifiedSmap.approved.json, tests/data/valid/error/frontend.json
- Keep original values when transforming.  (#647)
=> [6.x] Keep original values when transforming. (#647)

CHANGELOG.asciidoc, docs/spec/context.json, docs/spec/errors/error.json, docs/spec/process.json, docs/spec/stacktrace_frame.json, docs/spec/transactions/span.json, docs/spec/transactions/transaction.json, docs/spec/user.json, processor/error/schema.go, processor/transaction/schema.go, tests/json_schema_test.go
- Use type integer instead of number where applicable (#641)
=> [6.x] Use type integer instead of number where applicable

CHANGELOG.asciidoc, docs/spec/process.json, docs/spec/stacktrace_frame.json, processor/error/schema.go, processor/transaction/schema.go
- Set array item types to string (#651)
=> [6.x] Set array item types to string

.gitignore, docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/keystore.asciidoc, docs/setting-up-and-running.asciidoc
=> document and git-ignore the new keystore provided by beats

model/service.go, model/stacktrace_frame.go, processor/error/event.go, processor/error/event_test.go, processor/error/payload_test.go
This reverts commit 4feb3b5b0f487a93dee087a026f88259dfd7b8cf.
According to discussions on PR #688 .
=> Revert "Use embedded structs over nested structs. (#688)"

beater/beater.go, beater/beater_test.go, beater/pub.go, beater/server.go, beater/server_test.go
Fixes #671
This uses the `apm-server.shutdown_timeout` config option to wait for the events buffer to drain, instead of as a timeout for the HTTP server. The HTTP server is closed immediately, instead.
=> graceful shutdown of apm server

CHANGELOG.asciidoc, docs/data/intake-api/generated/error/payload.json, docs/spec/errors/error.json, processor/error/package_tests/TestProcessErrorFull.approved.json, processor/error/schema.go, tests/data/valid/error/payload.json, tests/system/error.approved.json
Adds more flexibility to support custom log levels,
while ES mapping is still keyword.
closes #665
=> Remove enum for error.log.level

CHANGELOG.asciidoc, docs/data/intake-api/generated/error/payload.json, docs/spec/errors/error.json, processor/error/package_tests/TestProcessErrorFull.approved.json, processor/error/schema.go, tests/data/valid/error/payload.json, tests/system/error.approved.json
- Remove enum for error.log.level  (#712)
=> [6.x] Remove enum for error.log.level (#712)

CHANGELOG.asciidoc, _meta/beat.yml, apm-server.yml, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_integration.py
- Push transactions and errors to different indices, fixes #279 (f33412d)
- Add missing changelog entry for indices separation (#721)
=> [6.x] Push transactions and errors to different indices, fixes #279

CHANGELOG.asciidoc, beater/beater.go, beater/beater_test.go, beater/pub.go, beater/server.go, beater/server_test.go
- graceful shutdown of apm server  (#704)
- update changelog (#728)
=> [6.x] graceful shutdown of apm server (#704)

CHANGELOG.asciidoc, beater/config.go, beater/handlers.go
=> [6.x] Follow up on #731 (#738)

CHANGELOG.asciidoc, _meta/beat.reference.yml, apm-server.reference.yml, beater/config.go
- update/sync configuration defaults  (#748)
=> [6.x] update/sync configuration defaults (#748)

docs/copied-from-beats/loggingconfig.asciidoc
- Resolve attrs in docs example.  (#661)
=> [6.x] Resolve attrs in docs example. (#661)

.gitignore, docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/keystore.asciidoc, docs/setting-up-and-running.asciidoc
- document and git-ignore the new keystore provided by beats (#618)
=> [6.x] document and git-ignore the new keystore provided by beats

Makefile, beater/server.go
=> [6.x] use libbeat version (#659)

docs/sourcemaps.asciidoc
- Improve sourcemap docs  (#771)
=> [6.x] Improve sourcemap docs (#771)

CHANGELOG.asciidoc, _meta/beat.yml, apm-server.yml, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_integration.py
This creates a seperate index for `spans`
rather than storing them in the same index as transactions.
closes #734
=> Split indices by `processor.event` instead of `name`.

beater/server_test.go
even with room for error, this has not been passing consistently across platforms.  Disabling for now.
=> disable conn limit test

CHANGELOG.asciidoc, _meta/beat.yml, apm-server.yml, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_integration.py
- Split indices by `processor.event` instead of `name`.  (#774)
=> [6.x] Split indices by `processor.event` instead of `name`. (#774)

decoder/decoder.go, decoder/decoder_test.go, docs/data/intake-api/generated/transaction/minimal_span.json, processor/error/event.go, processor/transaction/package_tests/TestProcessTransactionMinimalSpan.approved.json, tests/data/valid/transaction/minimal_span.json, tests/loader/loader.go, utility/data_fetcher.go, utility/map_str_enhancer.go
- handle large integers in json  (#783)
=> [6.x] handle large integers in json (#783)

Makefile, NOTICE.txt, _beats/dev-tools/generate_notice.py, _beats/vendor/vendor.json, script/update_beats.sh
instead of beats version at time it pulled in transitive version.  No other transitive deps provide this information at this time.
`_beats/dev-tools/generate_notice.py` is already updated in beats
closes #460
=> use transitive dep versions in NOTICE

docs/spec/request.json, processor/error/schema.go, processor/transaction/schema.go
- Clarify semantics of request.url.raw  (#785)
=> [6.x] Clarify semantics of request.url.raw (#785)

Makefile
- target for clean and docs together (make docs without removing '/build' first behaves in a unexpected way)  (#624)
=> [6.x] target for clean and docs together (make docs without removing '/build' first behaves in a unexpected way) (#624)

Makefile
The current description is: `Sends events to Elasticsearch or Logstash`.
That shows up in:
* rpm & deb package description
* top of the generated `README.md` file bundled with all distributions
=> update description used in packaging

CHANGELOG.asciidoc, _meta/beat.reference.yml, apm-server.reference.yml, beater/beater.go, beater/beater_test.go, beater/server_test.go, docs/guide/index.asciidoc, model/system.go, model/system_test.go
with `apm-server.host=unix:/path`
closes #689
=> listen on unix domain socket

utility/ip.go, utility/ip_test.go
- reduce ExtractIP allocations  (#821)
=> [6.x] reduce ExtractIP allocations (#821)

_meta/beat.reference.yml, apm-server.reference.yml, beater/config.go, beater/server.go, beater/server_test.go, vendor/golang.org/x/net/netutil/listen.go, vendor/vendor.json
- limit number of new connections to accept simultaneously  (#751)
- disable conn limit test (#781)
=> [6.x] limit number of new connections to accept simultaneously (#751)

Makefile, NOTICE.txt, _beats/dev-tools/generate_notice.py, _beats/dev-tools/set_docs_version, _beats/vendor/vendor.json, script/generate_notice_overrides.py, script/update_beats.sh, vendor/github.com/elastic/beats/NOTICE.txt, vendor/github.com/elastic/beats/libbeat/cmd/instance/metrics.go, vendor/github.com/elastic/beats/libbeat/cmd/instance/metrics_common.go, vendor/github.com/elastic/beats/libbeat/cmd/instance/metrics_other.go, vendor/github.com/elastic/beats/libbeat/common/cli/cli.go, vendor/github.com/elastic/beats/libbeat/common/file/file_other.go, vendor/github.com/elastic/beats/libbeat/common/file/file_windows.go, vendor/github.com/elastic/beats/libbeat/metric/system/process/process.go, vendor/vendor.json
- target for clean and docs together (#624)
- use transitive dep versions in NOTICE (#790)
- override revision for missed subpackages (#797)
- update description used in packaging (#807)
=> [6.2] Update beats framework to 1122568

CHANGELOG.asciidoc, _meta/beat.reference.yml, apm-server.reference.yml, beater/beater.go, beater/beater_test.go, beater/server_test.go, docs/guide/index.asciidoc, model/system.go, model/system_test.go
- listen on unix domain socket  (#768)
=> [6.x] listen on unix domain socket (#768)

CHANGELOG.asciidoc, docs/data/intake-api/generated/error/minimal_payload_exception.json, docs/data/intake-api/generated/error/minimal_payload_log.json, docs/data/intake-api/generated/transaction/minimal_payload.json, docs/spec/errors/error.json, docs/spec/transactions/transaction.json, processor/error/event.go, processor/error/package_tests/TestProcessErrorMinimalPayloadException.approved.json, processor/error/package_tests/TestProcessErrorMinimalPayloadLog.approved.json, processor/error/package_tests/processor_test.go, processor/error/schema.go, processor/transaction/event.go, processor/transaction/package_tests/TestProcessTransactionAugmented.approved.json, processor/transaction/package_tests/TestProcessTransactionAugmentedMerge.approved.json, processor/transaction/package_tests/TestProcessTransactionFrontend.approved.json, processor/transaction/package_tests/TestProcessTransactionMinimalPayload.approved.json, processor/transaction/package_tests/processor_test.go, processor/transaction/schema.go, tests/data/invalid/error/no_timestamp.json, tests/data/invalid/transaction/no_timestamp.json, tests/data/valid/error/minimal_payload_exception.json, tests/data/valid/error/minimal_payload_log.json, tests/data/valid/transaction/augmented_payload_frontend.json, tests/data/valid/transaction/augmented_payload_frontend_no_context.json, tests/data/valid/transaction/frontend.json, tests/data/valid/transaction/minimal_payload.json, tests/json_schema_test.go, utility/data_fetcher.go, utility/data_fetcher_test.go
- makes timestamp optional  (#819)
=> [6.x] makes timestamp optional (#819)

docs/setting-up-and-running.asciidoc
Link for config file reference was broken in several places.
=> Fixed link to the config file format in the beats reference.

docs/setting-up-and-running.asciidoc
- Fix link to beats platform reference  (#614)
=> [6.x] Fix link to beats platform reference (#614)

Makefile, docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/keystore.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/repositories.asciidoc, docs/copied-from-beats/security/basic-auth.asciidoc, docs/copied-from-beats/security/securing-beats.asciidoc, docs/copied-from-beats/security/tls.asciidoc, docs/copied-from-beats/security/user-access.asciidoc, docs/copied-from-beats/shared-directory-layout.asciidoc, docs/copied-from-beats/shared-docker.asciidoc, docs/copied-from-beats/shared-env-vars.asciidoc, docs/copied-from-beats/shared-path-config.asciidoc, docs/copied-from-beats/shared-ssl-config.asciidoc, docs/copied-from-beats/shared-template-load.asciidoc, docs/copied-from-beats/template-config.asciidoc, docs/setting-up-and-running.asciidoc, script/copy-docs.py
Add script that
* copies all docs from a local beats folder that are currently listed in the `docs/copied-from-beats/`  folder
* (removed: temporary fixes inconsistencies between beats and apm-server documentation (e.g. removing the monitoring section).)
*  run `make docs` afterwards.
You can trigger the script by running `make update-beats-docs`. 
Please verify the generated documentation afterwards. In case new files are linked, the `make docs` command should fail and you need to manually resolve issues. 
(update info)
=> Update docs copied from beats.

docs/guide/index.asciidoc
Adds a new section to docs/guide/index.asciidoc
explaining the various reasons for the APM server
being a separate component
Closes: https://github.com/elastic/apm-server/issues/602
cc @roncohen
=> docs/guide: Added docs

tests/system/apmserver.py, tests/system/test_integration.py, tests/system/test_requests.py
- Allow system tests to be run from any directory  (#835)
- Allow other tests to be run from any directory  (#837)
=> [6.x] Allow system tests to be run from any directory (#835) | Allow other tests to be run from any directory (#837)

NOTICE.txt, _beats/libbeat/scripts/Makefile, _beats/libbeat/scripts/generate_fields_docs.py, _beats/libbeat/tests/system/beat/beat.py, _beats/libbeat/tests/system/beat/compose.py, docs/fields.asciidoc, vendor/github.com/elastic/beats/libbeat/common/mapstr.go, vendor/github.com/elastic/beats/libbeat/common/safemapstr/safemapstr.go, vendor/vendor.json
* removes `github.com/elastic/beats/libbeat/kibana/`, retaining `github.com/elastic/beats/libbeat/kibana` (no trailing slash)
=> Update beats framework to 88911e7

beater/handlers.go, processor/error/processor.go, processor/sourcemap/processor.go, processor/transaction/processor.go
If expvar is enabled, additionally expose apm-server
monitoring metrics via configured expvar endpoint.
=> Expose apm-server metrics via expvar

beater/handlers.go, processor/error/processor.go, processor/sourcemap/processor.go, processor/transaction/processor.go
- Expose apm-server metrics via expvar  (#861)
=> [6.x] Expose apm-server metrics via expvar (#861)

CHANGELOG.asciidoc, beater/handlers.go, beater/handlers_test.go, processor/error/processor.go, processor/transaction/processor.go
- Add monitoring for agents and all response codes and reasons  (#862)
=> [6.x] Add monitoring for agents and all response codes and reasons (#862)

decoder/decoder.go
=> [6.x] Monitor req sizes (#868)

CHANGELOG.asciidoc, beater/beater.go, beater/config.go, beater/server_test.go
=> listen on default port 8200 if unspecified

CHANGELOG.asciidoc
=> [6.x] rotate changelog (#877)

CHANGELOG.asciidoc, beater/beater.go, beater/config.go, beater/server_test.go
- listen on default port 8200 if unspecified  (#886)
=> [6.x] listen on default port 8200 if unspecified (#886)

Makefile, vendor/vendor.json
- update github.com/elastic/beats/libbeat/kibana vendoring  (#897)
=> [6.x] update github.com/elastic/beats/libbeat/kibana vendoring (#897)

Makefile, vendor/vendor.json
- update github.com/elastic/beats/libbeat/kibana vendoring  (#897)
=> [6.3] update github.com/elastic/beats/libbeat/kibana vendoring (#897)

Makefile, vendor/vendor.json
- update github.com/elastic/beats/libbeat/kibana vendoring  (#897)
=> [6.2] update github.com/elastic/beats/libbeat/kibana vendoring (#897)

beater/handlers.go, decoder/decoder.go, processor/error/processor.go, processor/transaction/processor.go
Align naming for request errors,
add counters for payload measurements
and remove agent information as it is always set to the latest agent information.
=> Add and align monitoring metrics for APM.

docs/spec/transactions/transaction.json, processor/transaction/schema.go
Update the description of transaction.result to specify the expected format for HTTP transactions.
=> spec: clarify HTTP result format

.backportrc.json
This adds a config for [`backport`](https://github.com/sqren/backport) which removes the need for every user of the tool to create their own config.
=> Add backport config

docs/spec/transactions/transaction.json, processor/transaction/schema.go
- spec: clarify HTTP result format  (#904)
=> [6.x] spec: clarify HTTP result format (#904)

docs/spec/transactions/transaction.json, processor/transaction/schema.go
- spec: clarify HTTP result format  (#904)
=> [6.3] spec: clarify HTTP result format (#904)

decoder/decoder.go, decoder/decoder_test.go, utility/ip.go
When augmenting the decoded payload, only add the remote address if it is a valid IP. Otherwise, the events fail indexing.
Also, make some minor performance improvements to utility.ExtractIP by pulling in some of the "RemoteAddr" function from https://github.com/elastic/apm-agent-go/tree/master/internal/apmhttputil, which has been optimized to eliminate allocations in typical code paths. Missing is the support for the Forwarded header, which is a little bit more involved.
Fixes #920
=>  decoder: only augment with valid IPs

beater/beater.go
- update configuration processing error message  (#919)
=> [6.x] update configuration processing error message (#919)

beater/beater.go
- update configuration processing error message  (#919)
=> [6.3] update configuration processing error message (#919)

CHANGELOG.asciidoc
- Update changelog to include the updated docker image.  (#924)
=> [6.3] Update changelog to include the updated docker image. (#924)

CHANGELOG.asciidoc
- Update changelog to include the updated docker image.  (#924)
=> [6.x] Update changelog to include the updated docker image. (#924)

CHANGELOG.asciidoc, beater/handlers.go, decoder/decoder.go, utility/forwarded.go, utility/forwarded_test.go, utility/ip.go, utility/ip_test.go, utility/remoteaddr.go, utility/remoteaddr_test.go
Copy in the RemoteAddr function from apm-agent-go,
with a small change to how/where the Forwarded
header is parsed. Change ExtractIP to call RemoteAddr
and return net.ParseIP of the result.
=> utility: add RemoteAddr, change ExtractIP sig

decoder/decoder.go, decoder/decoder_test.go, utility/ip.go
- decoder: only augment with valid IPs  (#923)
=> [6.x] decoder: only augment with valid IPs (#923)

decoder/decoder.go, decoder/decoder_test.go, utility/ip.go
- decoder: only augment with valid IPs  (#923)
=> [6.3] decoder: only augment with valid IPs (#923)

CHANGELOG.asciidoc, beater/handlers.go, decoder/decoder.go, utility/forwarded.go, utility/forwarded_test.go, utility/ip.go, utility/ip_test.go, utility/remoteaddr.go, utility/remoteaddr_test.go
- utility: add RemoteAddr, change ExtractIP sig  (#927)
=> [6.x] utility: add RemoteAddr, change ExtractIP sig (#927)

CHANGELOG.asciidoc
- Fix changelog for extracting IP.  (#949)
=> [6.x] Fix changelog for extracting IP. (#949)

CHANGELOG.asciidoc, beater/handlers.go, decoder/decoder.go, utility/forwarded.go, utility/forwarded_test.go, utility/ip.go, utility/ip_test.go, utility/remoteaddr.go, utility/remoteaddr_test.go
- utility: add RemoteAddr, change ExtractIP sig  (#927)
=> [6.3] utility: add RemoteAddr, change ExtractIP sig (#927)

CHANGELOG.asciidoc
- Fix changelog for extracting IP.  (#949)
=> [6.3] Fix changelog for extracting IP. (#949)

beater/handlers.go, beater/handlers_test.go, beater/server_test.go
- add telemetry on waiting time for concurrent requests  (#969)
=> [6.x] add telemetry on waiting time for concurrent requests (#969)

cmd/root.go
a64eb29cce2e0c84074d169534083761f5d3795c introduced replacement of
fields.yml with generated fields.go.  Ensure this is a loaded at
startup.
fixes #985
=> load generated fields

docs/common-problems.asciidoc
- Add clarification on 503 error due to full disk  (#999)
=> [6.x] Add clarification on 503 error due to full disk (#999)

beater/handlers.go, beater/handlers_test.go
- clarify root cause for 403 errors, fixes elastic/apm-server#973  (#974)
=> [6.3] clarify root cause for 403 errors, fixes #973 (#974)

docs/common-problems.asciidoc, docs/index.asciidoc
- document curator tips useful for APM data, fixes #954  (#983)
=> [6.3] document curator tips useful for APM data, fixes #954 (#983)

docs/common-problems.asciidoc
- Add clarification on 503 error due to full disk  (#999)
=> [6.3] Add clarification on 503 error due to full disk (#999)

_meta/kibana/6/dashboard/apm-dashboards.json
unpack_dashboards will now handle it through make update
fixes #1017
=> do not encode some viz attributes

CHANGELOG.asciidoc, docs/index.asciidoc, docs/release-notes.asciidoc
Adds the CHANGELOG.asciidoc (that we're already maintaining) to the docs they will get rendered nicely and so we can link to them from download pages.
=> Add release notes

processor/error/generated/schema/payload.go, processor/error/package_tests/json_schema_test.go, processor/error/processor.go, processor/sourcemap/generated/schema/payload.go, processor/sourcemap/package_tests/json_schema_test.go, processor/sourcemap/processor.go, processor/transaction/generated/schema/payload.go, processor/transaction/package_tests/json_schema_test.go, processor/transaction/processor.go, script/inline_schemas/inline_schemas.go
This moves generated schemas into their own sub-folders in their respective processors.
This is extracted from the work on [intake v2](https://github.com/elastic/apm-server/pull/930). 
Right now, I think it's nice to have auto-generated and human-generated source code separately. 
In the future for intake v2, we'll need to validate entities like errors and transactions separate from the payload, which means we'll need to have the schemas separate for the individual entities.
When we add the individual schemas (errors, transactions) in the future, we'd be putting even more auto-generated files in the same directories as the human-generated code, if we didn't have a sub-folder for it. 
I went ahead and gave the schema constants names (`const PayloadSchema`) instead of using the `Schema()` …
=> Move generated schemas into sub-folders

docs/overview.asciidoc
It's no longer a top level heading:
=> Move "Why is APM Server a separate component?" under "Overview"."

beater/beater_test.go, beater/server_test.go
... and return immediately instead of timing out
(in support for https://github.com/elastic/apm-server/pull/1010, ie: passing a wrong passphrase will cause the beater to fail, and test should fail right away with a descriptive reason)
=> catch errors when starting the beater

docs/overview.asciidoc
- Move "Why is APM Server a separate component?" under "Overview"."  (#1040)
=> [6.x] Move "Why is APM Server a separate component?" under "Overview"." (#1040)

docs/overview.asciidoc
- Move "Why is APM Server a separate component?" under "Overview"."  (#1040)
=> [6.3] Move "Why is APM Server a separate component?" under "Overview"." (#1040)

CHANGELOG.asciidoc
This should put the individual sections "Added", "Bug fixes" on the same page as the headline:
Instead of the current situation:
=> Attempt at making sure "Added", "Bug fixes" etc. stay on the same page.

_meta/beat.yml, apm-server.yml, docs/error-api.asciidoc, docs/frontend.asciidoc, docs/transaction-api.asciidoc
implements elastic/apm-server#1039 
With this PR the docs for _master_ do not show the RUM agent as _experimental_ any more, but the _current_ docs still do. 
cc @jahtalab
=> Remove experimental note for frontend agent.

_meta/beat.yml, apm-server.yml, docs/error-api.asciidoc, docs/frontend.asciidoc, docs/transaction-api.asciidoc
- Remove experimental note for frontend agent.  (#1041)
=> [6.x] Remove experimental note for frontend agent. (#1041)

CHANGELOG.asciidoc
- Attempt at making sure "Added", "Bug fixes" etc. stay on the same page.  (#1047)
=> [6.x] Attempt at making sure "Added", "Bug fixes" etc. stay on the same page. (#1047)

_beats/dev-tools/jenkins_release.sh, script/update_beats.sh
As of #1053, this path is used to trigger package tests on master.  This change wraps the 6.3 version of package tests at the new path so a single jenkins configuration can be used for both versions.
=> [6.3] add jenkins release wrapper

_beats/dev-tools/jenkins_release.sh, script/update_beats.sh
As of #1053, this path is used to trigger package tests on master. This change wraps the 6.2 version of package tests at the new path so a single jenkins configuration can be used for both versions.
=> [6.2] add jenkins release wrapper

docs/storage_management.asciidoc
Bugfix for interpreting variables properly in the docs, which got removed in PR #1036 .
=> Fix doc attributes in example.

CHANGELOG.asciidoc
- Split changelog per patch version and add links for better visualization in docs (#1087)
=> [6.3] Split changelog per patch version (#1087)

CHANGELOG.asciidoc
- Split changelog per patch version and add links for better visualization in docs (#1087)
=> [6.2] Split changelog per patch version (#1087)

_meta/beat.yml, apm-server.yml, beater/beater_test.go, beater/config.go, beater/config_test.go, beater/server.go, beater/server_test.go
- incorporate TLS key passphrase support from beats.  (#1010)
=> [6.x] incorporate TLS key passphrase support from beats. (#1010)

CHANGELOG.asciidoc
- Split changelog per patch version and add links for better visualization in docs  (#1087)
=> [6.x] Split changelog per patch version and add links for better visualization in docs (#1087)

docs/storage_management.asciidoc
- Fix doc attributes in example.  (#1093)
=> [6.x] Fix doc attributes in example. (#1093)

docs/storage_management.asciidoc
- Fix doc attributes in example.  (#1093)
=> [6.3] Fix doc attributes in example. (#1093)

docs/configuration-rum.asciidoc, docs/error-api.asciidoc, docs/rum.asciidoc, docs/transaction-api.asciidoc
The usage of `apm-rum-ref` broke the docs build, so changing back to pointing to the github project for the `6.3` branch for the moment.
=> Fix links to Javascript agent.

docs/configuration-process.asciidoc, docs/configuring.asciidoc
- Describe missing config options.  (#1113)
=> [6.x] Describe missing config options. (#1113)

_meta/beat.yml, apm-server.yml
- Recommend the keystore in the config file, were applicable  (#1118)
=> [6.x] Recommend the keystore in the config file, were applicable (#1118)

_meta/beat.yml, apm-server.yml
Recommend the keystore in the config file, were applicable (#1118)
=> [6.3] Recommend the keystore in the config file, were applicable (#1118)

_meta/beat.yml, apm-server.yml, beater/beater.go, beater/config.go, beater/server_test.go, docs/configuration-process.asciidoc
- Rename tracing configuration to instrumentation  (#1120)
=> [6.x] Rename tracing configuration to instrumentation (#1120)

CODE_OF_CONDUCT.md
- link to Elastic code of conduct  (#1143)
=> [6.x] link to Elastic code of conduct (#1143)

CHANGELOG.asciidoc, docs/data/elasticsearch/transaction.json, docs/data/intake-api/generated/transaction/payload.json, docs/spec/context.json, docs/spec/metrics/metric.json, docs/spec/transactions/mark.json, docs/spec/transactions/transaction.json, processor/error/generated/schema/payload.go, processor/metric/generated/schema/payload.go, processor/transaction/generated/schema/payload.go, processor/transaction/package_tests/TestProcessTransactionFull.approved.json, testdata/transaction/payload.json
Removes requirement that certain fields are valid regexes, as reported in #909.
I introduced at least one of these rules but misunderstood this directive's actual purpose: https://github.com/santhosh-tekuri/jsonschema/blob/v1.2.2/schema.go#L319-L325
closes elastic/apm-server#909
=> remove regexProperties validation

CHANGELOG.asciidoc, docs/data/elasticsearch/transaction.json, docs/data/intake-api/generated/transaction/payload.json, docs/spec/context.json, docs/spec/metrics/metric.json, docs/spec/transactions/mark.json, docs/spec/transactions/transaction.json, processor/error/generated/schema/payload.go, processor/metric/generated/schema/payload.go, processor/transaction/generated/schema/payload.go, processor/transaction/package_tests/TestProcessTransactionFull.approved.json, testdata/transaction/payload.json, tests/system/transaction.approved.json
- remove regexProperties validation  (#1148)
=> [6.x] remove regexProperties validation (#1148)

CHANGELOG.asciidoc
- move changelog line to correct section  (#1151)
=> [6.x] move changelog line to correct section (#1151)

CHANGELOG.asciidoc, _meta/beat.yml, apm-server.yml, beater/beater.go, beater/beater_test.go, beater/config.go, beater/server_test.go, docs/configuration-frontend.asciidoc, docs/configuring-output-after.asciidoc, sourcemap/accessor.go
- add source_mapping.elasticsearch configuration option  (#1114)
=> [6.x] add source_mapping.elasticsearch configuration option (#1114)

docs/index.asciidoc, docs/installing.asciidoc, docs/upgrading.asciidoc
implements elastic/apm-server#1008
related to https://github.com/elastic/stack-docs/pull/81
@dedemorton how can I add APM Server to https://www.elastic.co/products/upgrade_guide?
update:
=> Docs: Add server upgrade instructions.

beater/server_test.go
We had this test disabled for ages because it is flaky. I tried to refactor it but it was still flaky ~10% of times or so, and more complicated. 
I propose to remove it as:
- It is also slow and complicated
- It is actually testing `netutil.LimitListener` which is not our concern, i'm sure that `golang.org/x/net` is exhaustively tested
- Probably no one is using that config anyways
=> remove disabled, flaky test

beater/server_test.go
- remove disabled, flaky test  (#1161)
=> [6.x] remove disabled, flaky test (#1161)

docs/index.asciidoc, docs/installing.asciidoc, docs/upgrading.asciidoc
- Docs: Add server upgrade instructions.  (#1125)
=> [6.x] Docs: Add server upgrade instructions. (#1125)

docs/guide/index.asciidoc, docs/overview.asciidoc
- add new GA agents to index/overview docs  (#1165)
=> [6.x] add new GA agents to index/overview docs (#1165)

CHANGELOG.asciidoc, _meta/beat.yml, apm-server.yml, beater/onboarding.go, beater/onboarding_test.go
Add processor information to onboarding doc and use this to move to its
own index.
implements elastic/apm-server#1158
@graphaelli I wasn't sure if you were going to touch the onboarding docs in any way when working on elastic/apm-server#957 so please let me know if this interferes with your plans. 
@jalvz also brought up that it might make sense to call it `healthcheck` instead of `onboarding`. I am tempted to stick with `onboarding` as it is unrelated to the actual healthcheck endpoint.
=> Move onboarding document to dedicated index.

CHANGELOG.asciidoc, _meta/beat.yml, apm-server.yml, beater/onboarding.go, beater/onboarding_test.go
- Move onboarding document to dedicated index.  (#1159)
=> [6.x] Move onboarding document to dedicated index. (#1159)

_meta/beat.yml, apm-server.yml
=> disable metrics logging by default

_meta/beat.yml, apm-server.yml
- disable metrics logging by default  (#1127)
=> [6.x] disable metrics logging by default (#1127)

CHANGELOG.asciidoc, NOTICE.txt, _meta/beat.yml, apm-server.yml, cmd/root.go, docs/configuring.asciidoc, docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/dashboards.asciidoc, docs/copied-from-beats/dashboardsconfig.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/shared-docker.asciidoc, docs/copied-from-beats/shared-kibana-config.asciidoc, docs/copied-from-beats/shared-ssl-config.asciidoc, docs/copied-from-beats/shared-template-load.asciidoc, docs/copied-from-beats/template-config.asciidoc, docs/dashboards.asciidoc, docs/guide/index.asciidoc, docs/index.asciidoc, docs/setting-up-and-running.asciidoc, vendor/github.com/elastic/beats/libbeat/cmd/setup.go, vendor/github.com/spf13/pflag/bytes.go, vendor/github.com/spf13/pflag/duration_slice.go, vendor/github.com/spf13/pflag/flag.go, vendor/github.com/spf13/pflag/golangflag.go, vendor/github.com/spf13/pflag/string_array.go, vendor/github.com/spf13/pflag/string_slice.go, vendor/vendor.json
From 6.4 on loading the dashboards and Kibana index pattern via the APM Server will be deprecated, in favour of loading them via the Kibana UI. 
The reason behind this is that some features will require an existing APM Kibana Index Pattern. If a missing index pattern is detected the customer can load the Index Pattern directly via Kibana, instead of having to load it via the Server. 
This PR aims to 
* print a deprecated message when the dashboards and index patterns are loaded via the server.
* mark Kibana and dashboard sections as deprecated in `apm-server.yml`.
* mark configuring Kibana endpoint and dashboard settings as deprecated in official docs.
implements elastic/apm-server#1135 
update:
forgot to mention, that once we align on the deprecation docs I'll open a PR in beats to …
=> Docs deprecate setup dashboards

Makefile, _beats/libbeat/tests/system/requirements.txt, script/are_kibana_saved_objects_updated.py
APM dashboards and index pattern are stored in Kibana. Add test to
ensure that those files are kept up-to-date.
implements elastic/apm-server#1042 
Current Differences found by this script:
```
---- Comparing Dashboards
================================
Difference for id '1ffc5e20-7827-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.aggs.id=1.params.customLabel'
"Avg. Resp. Time"
Value in APM Server: Avg. Trans. Time
Value in Kibana: Avg. Resp. Time
---
Difference for id '1ffc5e20-7827-11e7-8c47-65b845b5cfb3' for key 'attributes.visState.aggs.id=3.params.customLabel'
"Resp. Time"
Value in APM Server: Trans. Time
Value in Kibana: Resp. Time
---
Difference for id '1ffc5e20-7827-11e7-8c47-65b845b5cfb3' for key 'attributes.kibanaSavedObjectMeta.searchSourceJSON.index' …
```
=> Check if Kibana files are up-to-date

CHANGELOG.asciidoc, _meta/beat.yml, apm-server.yml, cmd/root.go, docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/dashboards.asciidoc, docs/copied-from-beats/dashboardsconfig.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/shared-docker.asciidoc, docs/copied-from-beats/shared-kibana-config.asciidoc, docs/copied-from-beats/shared-template-load.asciidoc, docs/copied-from-beats/template-config.asciidoc, docs/dashboards.asciidoc, docs/guide/index.asciidoc, docs/index.asciidoc, docs/setting-up-and-running.asciidoc
backporting PR #1142 
* Docs: deprecate loading dashboards and index pattern.
Add deprecation notes to apm-server.yml and docs
for loading dashboards and index patterns via Kibana.
Add deprecation note for setting up Kibana endpoint as it won't be
needed any more.
implements #1135
=> [6.x] Backport/6.x/pr 1142

Makefile, README.md, TESTING.md
- Briefly explain benchmarking in README  (#1147)
=> [6.x] Briefly explain benchmarking in README (#1147)

CHANGELOG.asciidoc, docs/release-notes.asciidoc
- rotate changelog to 6.4  (#1202)
=> [6.x] rotate changelog to 6.4 (#1202)

docs/version.asciidoc
When we started building the 6.4 documentation, we received the following errors:
Bad cross-document links:
html/en/apm/get-started/6.4/install-and-run.html:
- en/apm/server/6.x/index.html
- en/apm/server/6.x/securing-apm-server.html
html/en/apm/get-started/6.4/overview.html:
- en/apm/server/6.x/index.html
This PR fixes the links by updating the branch info.
=> [DOCS] Fix broken links by updating branch

docs/common-problems.asciidoc, docs/configuration-process.asciidoc, docs/configuration-rum.asciidoc, docs/configuring.asciidoc, docs/context.asciidoc, docs/data-ingestion.asciidoc, docs/error-api.asciidoc, docs/error-indices.asciidoc, docs/errors.asciidoc, docs/event-types.asciidoc, docs/exploring-es-data.asciidoc, docs/guide/index.asciidoc, docs/healthcheck-indices.asciidoc, docs/high-availability.asciidoc, docs/installing.asciidoc, docs/intake-api.asciidoc, docs/overview.asciidoc, docs/rum.asciidoc, docs/security.asciidoc, docs/setting-up-and-running.asciidoc, docs/sourcemap-api.asciidoc, docs/sourcemap-indices.asciidoc, docs/span-indices.asciidoc, docs/storage-management.asciidoc, docs/transaction-api.asciidoc, docs/transaction-indices.asciidoc, docs/transactions.asciidoc
- streamline docs a bit, and remove redundant info  (#1169)
=> [6.x] streamline docs a bit, and remove redundant info (#1169)

docs/common-problems.asciidoc, docs/configuration-process.asciidoc, docs/configuration-rum.asciidoc, docs/configuring.asciidoc, docs/context.asciidoc, docs/data-ingestion.asciidoc, docs/error-api.asciidoc, docs/error-indices.asciidoc, docs/errors.asciidoc, docs/event-types.asciidoc, docs/exploring-es-data.asciidoc, docs/guide/index.asciidoc, docs/healthcheck-indices.asciidoc, docs/high-availability.asciidoc, docs/installing.asciidoc, docs/intake-api.asciidoc, docs/overview.asciidoc, docs/rum.asciidoc, docs/security.asciidoc, docs/setting-up-and-running.asciidoc, docs/sourcemap-api.asciidoc, docs/sourcemap-indices.asciidoc, docs/span-indices.asciidoc, docs/storage-management.asciidoc, docs/transaction-api.asciidoc, docs/transaction-indices.asciidoc, docs/transactions.asciidoc
- streamline docs a bit, and remove redundant info  (#1169)
=> [6.4] streamline docs a bit, and remove redundant info (#1169)

script/jenkins/sync.sh
Gopath and environment needs to be set as the script actually runs `make update` which triggers `mage`..
=> Add script for jenkins sync test.

beater/server_test.go
- Add valid error message for bad schema config  (#1206)
=> [6.x] Add valid error message for bad schema config (#1206)

beater/server_test.go
- Add valid error message for bad schema config  (#1206)
=> [6.4] Add valid error message for bad schema config (#1206)

utility/map_str_enhancer.go, utility/map_str_enhancer_test.go
`utility.Add` adds a `val` to a MapStr `m`. However, it can sometimes modify the value given as a `val`. 
If you use `utility.Add` concurrently, to add the same value `val` to two different `m`s, you'll get can risk getting the following error:
```
fatal error: concurrent map iteration and map write
```
=> utility.Add should not modify source value

utility/map_str_enhancer.go, utility/map_str_enhancer_test.go
- utility.Add should not modify source value  (#1222)
=> [6.x] utility.Add should not modify source value (#1222)

CHANGELOG.asciidoc, beater/handlers.go, beater/handlers_test.go, beater/server_test.go, docs/high-availability.asciidoc, docs/intake-api.asciidoc, docs/server-info.asciidoc
provide basic server information at /
* if no secret token is set
* if secret token is set and request is authorized
```
{
"build_date": "2018-07-27T18:49:58Z",
"build_sha": "bc4d9a286a65b4283c2462404add86a26be61dca",
"version": "7.0.0-alpha1"
}
```
returns 200 OK in any case, to replace /healthcheck eventually
closes #957
=> Server information

_beats/dev-tools/packaging/packages.yml, script/update_beats.sh
Up for discussion - build time is insignificant but the dependencies (xcode) are not.
=> don't build unused DMGs

Makefile
we were missing eg. `BenchmarkServer`
=> run benchmarks from top directory instead of only /processor

Makefile
- run benchmarks from top directory instead of only /processor, we were missing eg. `BenchmarkServer`  (#1243)
=> [6.x] run benchmarks from top directory instead of only /processor, we were missing eg. `BenchmarkServer` (#1243)

Makefile
- run benchmarks from top directory instead of only /processor, we were missing eg. `BenchmarkServer`  (#1243)
=> [6.4] run benchmarks from top directory instead of only /processor, we were missing eg. `BenchmarkServer` (#1243)

CHANGELOG.asciidoc, cmd/root.go
Revert printing a deprecation message, as only the `dashboard` part of the setup cmd is deprecated.
=> Revert deprecating setup cmd.

CHANGELOG.asciidoc, cmd/root.go
- Revert deprecating setup cmd.  (#1261)
=> [6.x] Revert deprecating setup cmd. (#1261)

CHANGELOG.asciidoc, cmd/root.go
- Revert deprecating setup cmd.  (#1261)
=> [6.4] Revert deprecating setup cmd. (#1261)

NOTICE.txt, _beats/libbeat/scripts/Makefile, _beats/libbeat/testing/available_port.go, _beats/vendor/vendor.json, beater/beater_test.go, vendor/github.com/elastic/beats/NOTICE.txt, vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go, vendor/github.com/elastic/beats/libbeat/cmd/setup.go, vendor/github.com/elastic/beats/libbeat/conditions/conditions.go, vendor/github.com/elastic/beats/libbeat/conditions/equals.go, vendor/github.com/elastic/beats/libbeat/conditions/extractors.go, vendor/github.com/elastic/beats/libbeat/conditions/matcher.go, vendor/github.com/elastic/beats/libbeat/conditions/range.go, vendor/github.com/elastic/beats/libbeat/logp/core.go, vendor/github.com/elastic/beats/libbeat/monitoring/report/elasticsearch/client.go, vendor/github.com/elastic/beats/libbeat/outputs/backoff.go, vendor/github.com/elastic/beats/libbeat/outputs/console/console.go, vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/api.go, vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go, vendor/github.com/elastic/beats/libbeat/outputs/failover.go, vendor/github.com/elastic/beats/libbeat/outputs/fileout/file.go, vendor/github.com/elastic/beats/libbeat/outputs/kafka/client.go, vendor/github.com/elastic/beats/libbeat/outputs/logstash/async.go, vendor/github.com/elastic/beats/libbeat/outputs/outputs.go, vendor/github.com/elastic/beats/libbeat/outputs/redis/backoff.go, vendor/github.com/elastic/beats/libbeat/outputs/redis/client.go, vendor/github.com/elastic/beats/libbeat/outputs/transport/client.go, vendor/github.com/elastic/beats/libbeat/publisher/pipeline/output.go, vendor/github.com/elastic/beats/libbeat/testing/available_port.go, vendor/vendor.json
* Update beats framework to bf68486 (Needed for https://github.com/elastic/apm-server/pull/1258).
* Adapt APM Server tests to updated libbeat.
=> Master update beats

docs/sourcemap-api.asciidoc
- clarify that is possible to use a secret token when uploading sourcemaps  (#1271)
=> [6.4] clarify that is possible to use a secret token when uploading sourcemaps (#1271)

docs/guide/index.asciidoc, docs/index.asciidoc, docs/overview.asciidoc
=> add release notes for 6.4

docs/guide/index.asciidoc, docs/index.asciidoc, docs/overview.asciidoc
- add release notes for 6.4  (#1277)
=> [6.4] add release notes for 6.4 (#1277)

NOTICE.txt, _beats/dev-tools/mage/clean.go, _beats/dev-tools/mage/crossbuild.go, _beats/dev-tools/mage/pkg.go, _beats/dev-tools/mage/pkgspecs.go, _beats/dev-tools/packaging/packages.yml, _beats/libbeat/tests/system/beat/beat.py, magefile.go, vendor/github.com/elastic/beats/dev-tools/mage/clean.go, vendor/github.com/elastic/beats/dev-tools/mage/crossbuild.go, vendor/github.com/elastic/beats/dev-tools/mage/pkg.go, vendor/github.com/elastic/beats/dev-tools/mage/pkgspecs.go, vendor/vendor.json
Update according to packaging changes in https://github.com/elastic/beats/pull/7783/
=> Update beats framework to 03f7e87

.gitignore, Makefile, script/build_apm_docs.sh
- Pulls elastic/docs instead of remove & clone each time
- Drops maxdepth = 1 so to build guide/index too
_____
not sure if this is the right thing to do, just an attempt to make build docs better for us
=> Own make target to build APM docs

docs/copied-from-beats/security/securing-beats.asciidoc
The page has been renamed by https://github.com/elastic/stack-docs/commit/b2c8b18da347034b07b2851c22d7fa2285a4a379
=> [DOCS] Fix cross doc links to Stack Overview security page

docs/transactions.asciidoc
:wave: Still new here so not sure how the versioning stuff works with PRs like this, but looks like this typo was introduced in the 6.4 docs. I ran across it while reading through the docs. Feel free to close this and fix the one-word typo elsewhere if that makes more sense!
https://www.elastic.co/guide/en/apm/server/6.4/transactions.html#transaction-spans
=> Fixes spans v transactions typo in 6.4 docs

docs/transactions.asciidoc
- Fixes spans v transactions typo in docs  (#1289)
=> [6.4] Fixes spans v transactions typo in docs (#1289)

magefile.go, script/jenkins/ci.ps1, tests/system/apmserver.py, tests/system/test_integration.py
uses new capabilities introduced in elastic/beats#7766
closes #1248
=> use mage in windows test runner

CHANGELOG.asciidoc, docs/release-notes.asciidoc
- rotate changelog to 6.4  (#1202)
=> [6.4] rotate changelog to 6.4 (#1202)

tests/system/apmserver.py, tests/system/test_integration.py
Backports part of the following commit to 6.4:
- use mage in windows test runner  (#1301)
specifically, just backports `remove elasticsearch dependency from non-integration tests`
=> [6.4] use mage in windows test runner (#1301)

.gitignore, Makefile, script/build_apm_docs.sh
- Own make target to build APM docs  (#1279)
=> [6.4] Own make target to build APM docs (#1279)

docs/dashboards.asciidoc, docs/guide/index.asciidoc
- Reference to the Kibana UI.  (#1319)
=> [6.4] Reference to the Kibana UI. (#1319)

docs/upgrading.asciidoc
Remove link to beats breaking changes, as no breaking changes section exists for 6.4.
=> [6.4] Fix broken docs link.

docs/upgrading.asciidoc
Remove link to beats breaking changes, as no breaking changes section exists for 6.4.
=> Fix broken docs link.

docs/guide/index.asciidoc
- docs(node): list support for Restify framework  (#1343)
=> [6.4] docs(node): list support for Restify framework (#1343)

beater/v2_handler.go, beater/v2_handler_test.go
Error responses from intake v2 should have `Content-Type: application/json`.
=> v2Handler: use 'application/json' content-type for error responses

CHANGELOG.asciidoc, changelogs/head.asciidoc, docs/release-notes.asciidoc
Considered removing `CHANGELOG.asciidoc` altogether and doing everything in `docs/release-notes.asciidoc` but I think it's worth it keep around a top-level file for a changelog, even if it just points at other files.
follows on from #1342 and #1361
=> make changelogs more portable between branches

CHANGELOG.asciidoc, docs/data/intake-api/generated/error/payload.json, docs/spec/errors/common_error.json, model/error/event.go, model/error/event_test.go, model/error/generated/schema/error.go, model/error/generated/schema/payload.go, processor/error/package_tests/TestProcessErrorFull.approved.json, processor/error/package_tests/attrs_common.go, testdata/error/payload.json, tests/system/error.approved.json
Make either `message` or `type` required for `error.exception`,
without changing the logic for grouping_key.
implements #1297
=> [Intake] require `message` or `type` for error.exception

docs/spec/errors/common_error.json, model/error/generated/schema/error.go, model/error/generated/schema/payload.go, processor/error/package_tests/TestProcessErrorNullValues.approved.json, processor/error/package_tests/attrs_common.go, testdata/error/null_values.json
fixing https://github.com/elastic/apm-server/pull/1354#issuecomment-420566931
This includes a bugfix for `error.exception` or `error.log` not only be required but also need to be not nil.
@roncohen I don't think we should enforce required strings to have a min length, without discussing this. So far we do not specify what the value looks like when a field is required, we just enforce the key needs to be set and the value must be of the specified type and not nil.
=> [v2] Deny nil values for conditional requirements in Intake API.

beater/route_config.go, beater/v2_handler_test.go, docs/sourcemap-api.asciidoc, tests/system/apmserver.py, tests/system/test_access.py, tests/system/test_requests.py
Closes https://github.com/elastic/apm-server/issues/1336.
=> [v2] update endpoints to separate intake from assets

_meta/beat.yml, apm-server.yml, changelogs/head.asciidoc, cmd/root.go, docs/copied-from-beats/monitoring/monitoring-beats.asciidoc, docs/copied-from-beats/monitoring/shared-monitor-config.asciidoc, docs/copied-from-beats/security/beats-system.asciidoc, docs/copied-from-beats/security/securing-beats.asciidoc, docs/index.asciidoc
closes elastic/apm-server#1378
=> apm-server monitoring

docs/guide/index.asciidoc
- Add APM release notes for 6.4.1  (#1335)
=> [6.4] Add APM release notes for 6.4.1 (#1335)

CHANGELOG.asciidoc, docs/spec/errors/v2_error.json, model/error/generated/schema/error.go
=> Require and change description for `error.id`

docs/guide/index.asciidoc
- docs: fix grammar, overwrite -> override  (#1357)
=> [6.4] docs: fix grammar, overwrite -> override (#1357)

beater/v2_handler.go, beater/v2_handler_test.go
this returns v2 to the behaviour we have for v1
=> [v2] FullQueue returns 503 ServiceUnavailable

_meta/beat.yml, apm-server.yml, beater/beater.go, beater/config.go, beater/server_test.go, beater/tracing_test.go, changelogs/head.asciidoc
Adds `apm-server.instrumentation` configuration directives: `hosts` and `secret_token`.  `hosts` can only contain 1 element at the moment but is an array in anticipation of this restriction being lifted following elastic/apm-agent-go#200.
TODO:
closes elastic/apm-server#1388
=> enable sending instrumentation to another apm-server

CHANGELOG.asciidoc
Update change log in preparation for merging v2 into master.
v2 is a whole new API that we're introducing, so including the changes we've made to v2 separately from the introduction of v2 doesn't seem right to me. Users of the next version of APM Server will just see a new protocol added and shouldn't mind the fact that we've been doing it in iterations between the releases.
So I've gone ahead and removed the individual change log entries that we did for v2 and instead linked to the two meta issues: one for v2 and one for DT. This way, people can still see all the individual work that went into it, but as a change log entry it just shows up as the introduction of v2 with distributed tracing support.
=> [v2] updated changelog

beater/common_handlers.go, processor/stream/stream_processor.go, publish/pub.go
This effectively makes no change for tracing in the v1 api and reduces span count to 1 per request in the v2 api.
for #1385
=> [v2] create span per reporting session

_beats/libbeat/scripts/cmd/stress_pipeline/main.go, _beats/libbeat/testing/mapvaltest/mapvaltest.go, beater/config.go, beater/handlers.go, beater/handlers_test.go, beater/server.go, model/error/event.go, model/error/event_test.go, model/metadata/metadata_test.go, model/metric/event_test.go, model/span/span.go, model/span/span_test.go, model/transaction/event.go, model/transaction/event_test.go, processor/transaction/package_tests/processor_test.go, script/output_data/output_data.go, sourcemap/mapper.go, tests/approvals.go, tests/fields.go, transform/transform.go
simply updated goimports, ran `make fmt` and removed comments from `_beats/libbeat/scripts/cmd/stress_pipeline/main.go` that no longer made sense.
=> new goimports, new rules

_meta/beat.yml, apm-server.yml
This is already documented, eg https://www.elastic.co/guide/en/apm/server/6.4/configure-cloud-id.html.  This change adds commented out defaults to the bundled configuration.
closes elastic/apm-server#1428
=> add Elastic Cloud config

magefile.go, script/jenkins/package.sh, tests/packaging/Dockerfile.deb.install, tests/packaging/Dockerfile.rpm.install, tests/packaging/package_test.go, tests/packaging/test.sh
afterwards, we will need to update package tests to use `script/jenkins/package.sh` instead of `_beats/dev-tools/jenkins_release.sh` directly
=> test rpm and deb installation

model/stacktrace.go, model/stacktrace_frame.go, model/stacktrace_frame_test.go
Also write them once per span instead of once per stackframe.
Something like eg:
```
2018-10-16T14:29:18.106+0200	ERROR	[stacktrace]	model/stacktrace_frame.go:168	failed to apply sourcemap No Sourcemap available for Service Name: 'client', Service Version: '1.0.0' and Path: 'http://localhost:3000/static/js/main.e0dea103.js'.
2018-10-16T14:29:18.106+0200	ERROR	[stacktrace]	model/stacktrace_frame.go:220	No Sourcemap available for Service Name: 'client', Service Version: '1.0.0' and Path: 'http://localhost:3000/static/js/main.e0dea103.js'.
2018-10-16T14:29:18.106+0200	ERROR	[stacktrace]	model/stacktrace_frame.go:168	failed to apply sourcemap No Sourcemap available for Service Name: 'client', Service Version: '1.0.0' and Path: 'http://localhost:3000/static/js/main.e0dea103.js'. …
```
=> Deduplicate sourcemap error logs 

beater/common_handlers_test.go, beater/route_config.go
Always respond with a 200 to OPTIONS requests bypassing any rate limit
or concurrent requests limits.
Closes https://github.com/elastic/apm-server/issues/1434.
=> v1 intake: remove request limits for CORS OPTIONS requests

_meta/beat.yml, apm-server.yml, rally/README.md, rally/_tools/prepare.py, rally/challenges/default.json, rally/operations/default.json, rally/track.json
Add rally challenge to test mapping explosion limits for APM.
implements #1291 
I did some tests using the APM rally challenge `ingest-field-explosion` on ES instances with the following results:
* 1gb ram, 1 node, 1 zone ES instance: read timeouts for more than 200 tags
* 4gb ram, 1node, 1 zone ES instance: read timeouts for more than 750 tags
The amount of fields other than `tags` is roughly 200. My suggestion is to set `1,000` as default value for `total_fields` for `6.5`. Setting it too low would cause errors when trying to write although the ES instance might be able to handle it. Setting the value too high would risk memory issues with the whole ES instance.
=> Set field limit, after testing with rally.

magefile.go, script/jenkins/package.sh, tests/packaging/Dockerfile.deb.install, tests/packaging/Dockerfile.rpm.install, tests/packaging/package_test.go, tests/packaging/test.sh
Jenkins now uses `script/jenkins/package.sh` for all package tests - this change creates that file as a wrapper around what was originally used for package tests. 
- test rpm and deb installation  (#1421)
- restore old package tests  (#1450)
=> [6.4] backport script/jenkins/package.sh

beater/rl_cache.go, beater/rl_cache_test.go, beater/v2_handler.go
`getRateLimiter` can return `nil`, but is not checked at the call point https://github.com/elastic/apm-server/compare/master...jalvz:rl-nil-fix?expand=1#diff-ce6c26e750f0443c52c10a357e08e82aR118
`NewRlCache` prevents that scenario now, but we could break it if eg. we change its implementation - this PR makes it more explicit.
I don't know if this has been discussed before, @simitt lmk if I got something wrong.
=> Add missing nil check

beater/common_handlers.go, beater/rl_cache.go, beater/rl_cache_test.go, beater/route_config.go
- V1 reusable rate limiter  (#1459)
=> [6.x] V1 reusable rate limiter (#1459)

docs/spec/timestamp_rfc3339.json, model/error/generated/schema/payload.go, model/metricset/generated/schema/payload.go, model/transaction/generated/schema/payload.go
- fix timestamp spec definition for v1  (#1464)
=> [6.x] fix timestamp spec definition for v1 (#1464)

tests/system/apmserver.py, tests/system/test_export.py
depends on #1481, which updates libbeat with elastic/beats#8684.
=> Test export subcommands

_meta/beat.yml, apm-server.yml, changelogs/head.asciidoc, cmd/root.go, tests/system/apmserver.py, tests/system/test_export.py
Following up on our discussion of setting defaults in code to match the configuration file.  I'm still not sure if this is appropriate for a minor release, happy to discuss.
=> set more config defaults in code

tests/system/apmserver.py, tests/system/test_export.py
- Test export subcommands  (#1482)
=> [6.5] Test export subcommands (#1482)

tests/system/apmserver.py, tests/system/test_export.py
- Test export subcommands  (#1482)
=> [6.x] Test export subcommands (#1482)

beater/route_config.go, beater/v2_handler.go, decoder/line_reader.go, decoder/line_reader_test.go, decoder/stream_decoder.go, decoder/stream_decoder_test.go, processor/stream/benchmark_test.go, processor/stream/package_tests/error_attrs_test.go, processor/stream/package_tests/metadata_attrs_test.go, processor/stream/package_tests/metricset_attrs_test.go, processor/stream/package_tests/span_attrs_test.go, processor/stream/package_tests/transaction_attrs_test.go, processor/stream/package_tests/v2_test_processor.go, processor/stream/stream_processor.go, processor/stream/stream_processor_test.go
* refactors `v2Handler` into smaller pieces and makes it oblivious to NDJSON reading
* rate limiting is now an explicit argument to `HandleStream` instead of packed in the context
* NewNDJSONStreamReader simplified so it just takes a `LineReader`
* LineReader takes a `bufio.Reader` as an argument instead of creating it, allowing for reuse
=> v2: minor refactor of stream handling

beater/common_handlers.go, beater/v2_handler.go, beater/v2_handler_test.go
fixes #1514 
V2 Endpoints now return proper content-type and content in proper format. On Success no body is returned so no content-type is set. On Failure content type is set to `application/json` if the _Accept_ header specifically requests json or it allows _any_ type. Otherwise it is set to `text/plain; charset=utf-8`.
Details to the bugfix: The `WriteHeader` needs to be called after all other headers have been set, but before the actual `Write` method is called. According to the [WriteHeader](https://golang.org/src/net/http/server.go?s=2977:5840#L83) docs there are two points  to consider:
* Changing the header map after a call to WriteHeader (or Write) has no effect unless the modified headers are trailers.
* If WriteHeader is not called explicitly, the first call to Write will …
=> Bugfix v2: Return proper error content type.

beater/common_handlers.go, beater/v2_handler.go, beater/v2_handler_test.go
- Bugfix v2: Return proper error content type.  (#1516)
=> [6.x] Bugfix v2: Return proper error content type. (#1516)

beater/common_handlers.go, beater/v2_handler.go, beater/v2_handler_test.go
- Bugfix v2: Return proper error content type.  (#1516)
=> [6.5] Bugfix v2: Return proper error content type. (#1516)

docs/guide/apm-data-model.asciidoc
- docs: fix broken hyperlinks in 6.5 docs  (#1557)
=> [6.x] docs: fix broken hyperlinks in 6.5 docs (#1557)

docs/guide/apm-data-model.asciidoc
- docs: fix broken hyperlinks in 6.5 docs  (#1557)
=> [6.5] docs: fix broken hyperlinks in 6.5 docs (#1557)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml
`setup.template.settings` have been listed twice:
https://github.com/elastic/apm-server/compare/master...simitt:remove-duplicate-settings?expand=1#diff-7400bb261a1bc5bd91499ecf67970098L202
and 
https://github.com/elastic/apm-server/compare/master...simitt:remove-duplicate-settings?expand=1#diff-7400bb261a1bc5bd91499ecf67970098R224
=> fix: remove duplicate entries from apm-server.yml

_meta/beat.yml, apm-server.yml
- fix: remove duplicate entries from apm-server.yml  (#1562)
=> [6.5] fix: remove duplicate entries from apm-server.yml (#1562)

changelogs/6.5.asciidoc
needs to be backported to `6.x` and `6.5`.
=> Update release notes for 6.5.1

changelogs/head.asciidoc, script/are_kibana_saved_objects_updated.py
=> kibana: fix sync check for Kibana index pattern.

_meta/beat.yml, apm-server.yml
- fix: remove duplicate entries from apm-server.yml  (#1562)
=> [6.x] fix: remove duplicate entries from apm-server.yml (#1562)

docs/data/intake-api/generated/events.ndjson, testdata/intake-v2/events.ndjson
The NDJSON example on [Example Request Body](https://www.elastic.co/guide/en/apm/server/current/example-intakev2-events.html) currently looks like this:
There's a lot of inconsistent whitespace in this example, and this PR is an attempt to fix that.
As far as I understand, this data is taken from `testdata/intake-v2/events.ndjson` when the docs are generated.
=> docs: fix rendering of Intake API payload data example

docs/intake-api.asciidoc
- docs: fix APM agents casing  (#1592)
=> [6.x] docs: fix APM agents casing (#1592)

changelogs/head.asciidoc, script/are_kibana_saved_objects_updated.py
- kibana: fix sync check for Kibana index pattern.  (#1571)
=> [6.x] kibana: fix sync check for Kibana index pattern. (#1571)

tests/fields.go, tests/fields_test.go, tests/json_schema.go, tests/set.go
- test: increase field load filter flexibility  (#1606)
=> [6.x] test: increase field load filter flexibility (#1606)

docs/data/intake-api/generated/events.ndjson, testdata/intake-v2/events.ndjson
- docs: fix rendering of Intake API payload data example  (#1593)
=> [6.x] docs: fix rendering of Intake API payload data example (#1593)

docs/common-problems.asciidoc, docs/configuration-rum.asciidoc, docs/data-ingestion.asciidoc, docs/upgrading-to-65.asciidoc
This PR adds the additional tuning and configuration updates that weren't covered in #1530.
Data Ingestion
• Added a note about v1 vs v2 (#1537)
• Adding RUM event rate limit (would this make more sense in common problems?) 
• Tuning APM Server using both v1 and v2 (#1537)
Upgrading to 6.5
• Added section on RUM config changes
Common Problems
• Added links where needed
=> docs: WIP tuning and config updates

docs/common-problems.asciidoc, docs/configuration-rum.asciidoc, docs/data-ingestion.asciidoc, docs/events-api.asciidoc, docs/exploring-es-data.asciidoc, docs/guide/apm-data-model.asciidoc, docs/guide/apm-release-notes.asciidoc, docs/guide/install-and-run.asciidoc, docs/guide/overview.asciidoc, docs/overview.asciidoc, docs/redirects.asciidoc, docs/rum.asciidoc, docs/upgrading-to-65.asciidoc, docs/version.asciidoc
Will be opening PRs in other branches as well. This needs to be backported to 6.5. 
Updates master/6.5 docs to point to the following agent versions:
```
:go-branch: 1.x
:java-branch: 1.x
:rum-branch: 2.x
:node-branch: 2.x
:py-branch: 4.x
:ruby-branch: 2.x
```
More info: elastic/apm/issues/19
=> Docs: Fix APM cross document links (master)

docs/configuration-rum.asciidoc, docs/guide/index.asciidoc, docs/overview.asciidoc, docs/rum.asciidoc, docs/version.asciidoc
Updates 6.4 docs to point to the following agent versions:
```
:rum-branch: 1.x
:node-branch: 1.x
:py-branch: 3.x
:ruby-branch: 1.x
```
More info: elastic/apm/issues/19
=> Docs: Fix APM cross document links (6.4)

changelogs/6.5.asciidoc
- Update changelog for 6.5  (#1626)
=> [6.x] Update changelog for 6.5 (#1626)

docs/guide/install-and-run.asciidoc
Per customer comments, updating the install and run page to be more clear about needing to install Kibana
=> Docs: clarify apm setup instructions

Jenkinsfile
* workaround to [JENKINS-41929](https://issues.jenkins-ci.org/browse/JENKINS-41929), params would not be available as environment variables on the first build of a PR/branch.
=> [APM-CI][JENKINS-41929] use params instead environment variables

changelogs/6.5.asciidoc
Needs to be backported to `6.x` and `6.5`
But... None of the "view commit" links work for me. Does anyone know how we might fix them?
=> Docs: Add 6.5.3 release notes

docs/version.asciidoc
See elastic/apm-server#1648 for details. Need to move agent links out of `docs` repo and into `apm-server` repo.
=> Docs: move agent links to server repo

docs/version.asciidoc
See elastic/apm-server#1648 for details. Need to move agent links out of `docs` repo and into `apm-server` repo.
=> [6.5] Docs: move agent links to server repo

docs/version.asciidoc
See elastic/apm-server#1648 for details. Need to move agent links out of `docs` repo and into `apm-server` repo.
=> [6.4] Docs: move agent links to server repo

docs/version.asciidoc
See elastic/apm-server#1648 for details. Need to move agent links out of `docs` repo and into `apm-server` repo.
=> [6.x] Docs update version links

script/update_beats.patch, script/update_beats.sh
Path of least resistance to get this done.  Also attempted to move all of these out of libbeat and into each beat's fields.common.yml but the generated documentation ended up all wrong.
=> automate conflicting libbeat field removals

docs/version.asciidoc
This PR bumps the documentation version to 6.7.0
=> [DOCS] Bump version to 6.7.0

CHANGELOG.asciidoc, changelogs/6.6.asciidoc, changelogs/7.0.asciidoc, changelogs/head.asciidoc, docs/guide/apm-release-notes.asciidoc, docs/release-notes.asciidoc
Start breaking out release notes and changelogs for 7.0.0-alpha2 and 6.6.0, backfilling 7.0.0-alpha1 along the way.  
With 6.6.0 changelog to be remain commented out until the release there is a little space here:
but I think it actually works.
=> start 6.6.0 and 7.0.0-alpha* release notes

beater/client.go, beater/common_handlers.go, beater/route_config.go, beater/server.go, tests/docker-compose.yml, tests/system/test_requests.py
- avoid/fix deprecation warnings  (#1703)
=> [6.6] avoid/fix deprecation warnings (#1703)

beater/client.go, beater/common_handlers.go, beater/route_config.go, beater/server.go, tests/docker-compose.yml, tests/system/test_requests.py
- avoid/fix deprecation warnings  (#1703)
=> [6.x] avoid/fix deprecation warnings (#1703)

beater/beater.go
As per https://github.com/elastic/apm-agent-go/issues/412#issuecomment-452162669
=> [6.6] close default tracer

beater/beater.go
As per https://github.com/elastic/apm-agent-go/issues/412#issuecomment-452162669
=> [6.x] Close default tracer

beater/beater_test.go, beater/config.go, beater/config_test.go, beater/server_test.go, changelogs/head.asciidoc
=> Remove deprecated `frontend` setting namespace in favor of `rum`

changelogs/head.asciidoc, sourcemap/mapper.go, sourcemap/mapper_test.go
fixes #1760
this can happen eg. if the sourcemap file maps to a different version of the code producing a stacktrace, and the starting line number in the sourcemap is higher than the total line count in the code.
=> prevent slice out of bounds error

docs/configuration-process.asciidoc
Goes in hand with https://github.com/elastic/apm-server/pull/1759/commits/125046055650ad6191678686717efba299199a79
=> [6.x] mark metrics.enabled setting as deprecated

changelogs/head.asciidoc, sourcemap/mapper.go, sourcemap/mapper_test.go
- prevent slice out of bounds error  (#1764)
=> [6.6] prevent slice out of bounds error (#1764)

changelogs/head.asciidoc, sourcemap/mapper.go, sourcemap/mapper_test.go
- prevent slice out of bounds error  (#1764)
=> [6.x] prevent slice out of bounds error (#1764)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/beater_test.go, beater/config.go, changelogs/head.asciidoc, docs/configuration-process.asciidoc, docs/redirects.asciidoc, docs/upgrading-to-65.asciidoc
This is not used any more since https://github.com/elastic/apm-server/pull/1731/files#diff-31f9c87c519544cc8f4fbdae985b0d0eL164
As per https://github.com/elastic/apm-server/pull/1737, it doesn't make sense to keep the option around and should be the agent's call whether to enable/disable.
=> Remove metrics setting

docs/upgrading-to-65.asciidoc
- Clarify that metrics.enabled is a noop in v2 (#1759)
=> [6.x] Clarify that metrics.enabled is a noop in v2

docs/upgrading-to-65.asciidoc
- Clarify that metrics.enabled is a noop in v2 (#1759)
=> [6.6] Clarify that metrics.enabled is a noop in v2

docs/upgrading-to-65.asciidoc
- Clarify that metrics.enabled is a noop in v2 (#1759)
=> [6.5] Clarify that metrics.enabled is a noop in v2

beater/common_handler.go, beater/common_handler_test.go, beater/server_test.go, changelogs/head.asciidoc
fixes #1679 
Before and after:
`curl -H "Accept: blabla"  http://localhost:8200`
```
{"build_date":"2019-01-09T10:14:34Z","build_sha":"352dce789ccb9a0237cb5d97d58381ef375ad276","version":"7.0.0"}
```
`curl -H "Accept: blabla"  http://localhost:8200`
```
build_date:"2019-01-09T10:12:19Z"
build_sha:"fe25172f74ba25f58a043bb8685bea2c906ecfb0"
version:"7.0.0"
```
`curl http://localhost:8200`
```
{"ok":{"build_date":"2019-01-09T10:14:34Z","build_sha":"352dce789ccb9a0237cb5d97d58381ef375ad276","version":"7.0.0"}}
```
`curl http://localhost:8200`
```
{
"build_date": "2019-01-09T10:12:19Z",
"build_sha": "fe25172f74ba25f58a043bb8685bea2c906ecfb0",
"version": "7.0.0"
}
```
`curl http://localhost:8200/intake/v2/events`
```
{"accepted":0,"errors":[{"message":"only POST requests are supported"}]}
``` …
=> Change response format of the root handler and prettify JSON response

tests/system/test_integration.py
handle changes implemented for https://github.com/elastic/elasticsearch/issues/35190
alternatively, `include_type_name=false` would have fixed these up but I think we should use this opportunity to just make the 7.0 updates.
=> update integration tests for ES 7.0 

beater/server_test.go
=> [6.6] Skip flaky test (#1799)

beater/server_test.go
=> [6.x] Skip flaky test (#1799)

beater/server_test.go, changelogs/head.asciidoc, model/sourcemap/payload.go, sourcemap/elasticsearch.go, tests/system/apmserver.py, tests/system/test_integration.py, utility/common.go
- index the url path only of the sourcemaps  (#1661)
=> [6.x] index the url path only of the sourcemaps (#1661)

beater/beater_test.go
This should address some of the panics we've seen under test, like:
```
14:34:09 --- FAIL: TestServerOkUnix (2.00s)
14:34:09 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
14:34:09 	panic: runtime error: invalid memory address or nil pointer dereference
14:34:09 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1076c74]
14:34:09 
14:34:09 goroutine 692 [running]:
14:34:09 testing.tRunner.func1(0xc0004ab400)
14:34:09 	/usr/local/go/src/testing/testing.go:792 +0x6a7
14:34:09 panic(0x119a320, 0x1b3b0a0)
14:34:09 	/usr/local/go/src/runtime/panic.go:513 +0x1b9
14:34:09 github.com/elastic/apm-server/beater.(*beater).client(0xc0005b4b10, 0x1366101, 0x0, 0x0, 0x0)
14:34:09 	/go/src/github.com/elastic/apm-server/beater/beater_test.go:334 +0x134 …
```
=> abort if server is never created

beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json, changelogs/head.asciidoc, docs/data/elasticsearch/generated/errors.json, model/error/event.go, model/error/event_test.go, processor/stream/package_tests/error_attrs_test.go, processor/stream/package_tests/span_attrs_test.go, processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationRumErrors.approved.json, tests/fields.go, tests/system/apmserver.py, tests/system/error.approved.json, tests/system/test_integration.py
In order to support chained exceptions in the future,
we store exceptions as an array of objects. For now,
the array (if present) will have a single object.
Later, the array will have multiple elements, with
each exception object in the array corresponding to
the preceding exception object's cause.
Closes #1817
=> Index error.exception as array of objects

Dockerfile, README.md, changelogs/head.asciidoc, docs/version.asciidoc, tests/Dockerfile
This is a security release. For details see [release announcement](https://groups.google.com/forum/#!topic/golang-announce/mVeX35iXuSw).
related to https://github.com/elastic/beats/pull/10304
to be ported to 6.x.
=> Update Go to 1.10.8

Dockerfile, README.md, changelogs/head.asciidoc, docs/version.asciidoc, tests/Dockerfile
This is a security release. For details see [release announcement](https://groups.google.com/forum/#!topic/golang-announce/mVeX35iXuSw).
=> Update Go to 1.11.5

Jenkinsfile
In order to use a stable version of the pipeline shared library we add the setting to use a released version.
=> [APM-CI] Use a released version of the pipeline shared library

tests/system/error.approved.json, tests/system/spans.approved.json, tests/system/test_integration.py, tests/system/transaction.approved.json
The system approval tests did not actually check the whole document, but only everything under the event key, `@timestamp` and `context`. Since we are moving out everything from `context` all the other top level keys have not been tested. 
There are some exceptions:
- `observer`: The information in observer is related to where the apm-server is running, so most of the values cannot be checked. The test only looks at the keys being present. 
- `host`: libbeat does automatically set `host.name` which is considered a bug right now and needs to be removed, see https://github.com/elastic/apm-server/issues/1846
=> [tests] check all keys in events.

changelogs/6.6.asciidoc
=> [docs] Fix 6.6 changelog rendering

docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/shared-docker.asciidoc, docs/copied-from-beats/shared-template-load.asciidoc, docs/index.asciidoc
* Removes remaining references to "dashboards" in the APM docs.
* Removes old `deprecate_dashboard_loading` attribute and replaces with `no_dashboards` (used by xpack and filebeat) where possible, and `no_dashboards_apm` where not possible.
* Cleans up a couple of the conditionals.
* Related to #1715.
Once this is approved I'll open a PR in the beats repo and make the persistent changes there.
=> [docs] Remove dashboard references in beats

docs/events-api.asciidoc, docs/exploring-es-data.asciidoc, docs/guide/apm-data-model.asciidoc, docs/metricset-api.asciidoc, docs/metricset-indices.asciidoc
* ~WIP~
* ~Needs https://github.com/elastic/kibana/pull/28621 to be merged first.~
Adds metrics documentation, and makes the APM Data Model easier to understand. Closes elastic/apm-server#1060
=> [docs] Document metrics

docs/version.asciidoc
Update RUM links to point to `3.x` from APM Server.
Builds locally.
=> [docs] Update RUM links to 3.x

changelogs/head.asciidoc, docs/events-api.asciidoc, docs/exploring-es-data.asciidoc, docs/guide/agent-server-compatibility.asciidoc, docs/guide/apm-data-model.asciidoc, docs/guide/apm-doc-directory.asciidoc, docs/guide/index.asciidoc, docs/guide/install-and-run.asciidoc, docs/guide/overview.asciidoc, docs/metadata-api.asciidoc, docs/metricset-api.asciidoc, docs/metricset-indices.asciidoc, docs/version.asciidoc
Backports the following documentation PRs to `6.x`:
* [docs] Add documentation directory (#1780)
* docs: fix 404 (#1861)
* [docs] Document metrics (#1831)
* docs: update rum links to 3.x (#1867)
* docs: update RUM compatibility (#1858)
* docs: add kubernetes metadata section (#1650)
* docs: fix changelog (#1854) (Backported from `6.6`)
=> [6.x][docs] Backport documentation

docs/events-api.asciidoc, docs/exploring-es-data.asciidoc, docs/guide/agent-server-compatibility.asciidoc, docs/guide/apm-data-model.asciidoc, docs/guide/apm-doc-directory.asciidoc, docs/guide/index.asciidoc, docs/guide/install-and-run.asciidoc, docs/guide/overview.asciidoc, docs/metadata-api.asciidoc, docs/metricset-api.asciidoc, docs/metricset-indices.asciidoc, docs/version.asciidoc
Backports the following documentation PRs to `6.6`:
* [docs] Add documentation directory (#1780)
* docs: fix 404 (#1861)
* [docs] Document metrics (#1831)
* docs: update rum links to 3.x (#1867)
* docs: update RUM compatibility (#1858)
* docs: add kubernetes metadata section (#1650)
* cherry picked a commit from #1868 that includes a few changes
=> [6.6][docs] Backport documentation

docs/guide/index.asciidoc, docs/guide/opentracing.asciidoc
Adds a section on OpenTracing to the APM Overview. I think it makes more sense for the specifics on this to live in the agent docs, so this is really just an arrow pointing there with a small amount of information. @felixbarny, would you mind taking a look at this and letting me know if you think there's anything else that should be included here?
=> [docs] Add OpenTracing bridge

_beats/libbeat/scripts/unpack_dashboards.py, _meta/kibana/7/dashboard/apm-dashboards.json
This lets APM Server start with the (now deprecated) setting `setup.dashboards.enabled: true`:
This is a quick fix while we work on a better long term solution. 
Will look to contribute the beats changes back to beats.
```
019-02-12T13:00:06.557+0100	INFO	instance/beat.go:273	Setup Beat: apm-server; Version: 7.0.0
2019-02-12T13:00:06.557+0100	INFO	elasticsearch/client.go:165	Elasticsearch url: http://localhost:9200
2019-02-12T13:00:06.557+0100	INFO	[publisher]	pipeline/module.go:113	Beat name: Rons-MacBook-Pro-133.local
2019-02-12T13:00:06.557+0100	INFO	[beater]	beater/beater.go:81	No pipeline callback registered
2019-02-12T13:00:06.558+0100	INFO	kibana/client.go:118	Kibana url: http://localhost:5601/fzq
2019-02-12T13:00:06.639+0100	INFO	kibana/client.go:118	Kibana url: …
```
=> add empty dashboard list. Fixes #1905

Makefile, script/are_kibana_saved_objects_updated.py
https://github.com/elastic/kibana/pull/30837 revealed a hole in the sync pattern check - fields that were removed from the index pattern in apm-server but not kibana would not trigger a failure.  This change remedies that.
In addition, `branch` becomes an optional argument to accommodate  `file://` prefixed repo paths, where branch is not needed.  Instead, the generated index pattern is now required, removing the need to persist `apm-server.json` on disk.
=> index pattern sync check symmetry

changelogs/6.6.asciidoc
Cherry picks https://github.com/elastic/apm-server/pull/1943/commits/b1a38b6159b2948fcce3a057abe23716ebee87e3 to `7.x`
=> [docs] Add 6.6.1 release notes

beater/integration_test.go, beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json, docs/spec/metadata.json, model/metadata/generated/schema/metadata.go, testdata/intake-v2/minimal.ndjson
Add testfiles with minimal events on Intake API and run integration tests to create minimal ES documents. Some events have more than one minimal spec.
fixes elastic/apm-server#1812
@elastic/apm-ui you could make use of how [minimal events](https://github.com/elastic/apm-server/compare/master...simitt:1812-minimal-events?expand=1#diff-59a7edd512bcf2b1c3e52e2d785017f7) look like in your automated tests (as discussed with @sqren some time ago). Please be aware that there are some event types (error, span) that have multiple possibilities how a minimal event can look like. E.g. an error event either has a `log` or an `exception` and if it has an `exception` then it either has an `exception.type` or an `exception.message`. All possibilities of how a minimal event can look like are covered with …
=> Specify minimal events on Intake API and ES level.

docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/loggingconfig.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/security/basic-auth.asciidoc, docs/copied-from-beats/security/securing-beats.asciidoc, docs/copied-from-beats/shared-docker.asciidoc, docs/copied-from-beats/shared-logstash-config.asciidoc
Updating Beats documentation. Most of these are small grammar or formatting changes.
I'm curious about the new roles added in the table to the `securing-beats.asciidoc` page. Are these relevant to APM Server:
https://github.com/elastic/apm-server/blob/30ba8f0d9227d331364ee707966c183f35b994bd/docs/copied-from-beats/security/securing-beats.asciidoc#L55-L84
If someone could take a look when they have time, that'd be 🔥
I'd like to backport these to `7.0` (#1954) and `7.x` (#1955)
=> [docs] make update-beats-docs

changelogs/7.0.asciidoc, docs/breaking-changes.asciidoc, docs/context.asciidoc, docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/loggingconfig.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/security/basic-auth.asciidoc, docs/copied-from-beats/security/securing-beats.asciidoc, docs/copied-from-beats/security/user-access.asciidoc, docs/copied-from-beats/shared-docker.asciidoc, docs/copied-from-beats/shared-logstash-config.asciidoc, docs/field-name-changes.asciidoc, docs/guide/apm-breaking-changes.asciidoc, docs/guide/apm-data-model.asciidoc, docs/guide/apm-release-notes.asciidoc, docs/guide/index.asciidoc, docs/guide/opentracing.asciidoc, docs/index.asciidoc, docs/release-notes.asciidoc, docs/upgrading.asciidoc, script/renamed_fields.py
* [Docs] 7.0 Breaking changes, Release highlights, Migration assistant, ECS changes (#1940)
* [docs] Add apm_user role (#1916)
* docs: add opentracing bridge (#1887)
* [docs] make update-beats-docs (#1958)
=> [Docs] Backport docs to 7.0

changelogs/7.0.asciidoc, docs/breaking-changes.asciidoc, docs/context.asciidoc, docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/loggingconfig.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/security/basic-auth.asciidoc, docs/copied-from-beats/security/securing-beats.asciidoc, docs/copied-from-beats/security/user-access.asciidoc, docs/copied-from-beats/shared-docker.asciidoc, docs/copied-from-beats/shared-logstash-config.asciidoc, docs/field-name-changes.asciidoc, docs/guide/apm-breaking-changes.asciidoc, docs/guide/apm-data-model.asciidoc, docs/guide/apm-release-notes.asciidoc, docs/guide/index.asciidoc, docs/guide/opentracing.asciidoc, docs/index.asciidoc, docs/release-notes.asciidoc, docs/upgrading.asciidoc, script/renamed_fields.py
* [Docs] 7.0 Breaking changes, Release highlights, Migration assistant, ECS changes (#1940)
* [docs] Add apm_user role (#1916)
* docs: add opentracing bridge (#1887)
* [docs] make update-beats-docs (#1958)
=> [Docs] Backport docs to 7.x

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/config.go
- Make Ingest pipeline path explicit  (#1963)
=> [7.0] Make Ingest pipeline path explicit (#1963)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/config.go
- Make Ingest pipeline path explicit  (#1963)
=> [7.x] Make Ingest pipeline path explicit (#1963)

beater/integration_test.go, beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json, docs/spec/metadata.json, model/metadata/generated/schema/metadata.go, testdata/intake-v2/minimal.ndjson
- Specify minimal events on Intake API and ES level.  (#1941)
=> [7.x] Specify minimal events on Intake API and ES level. (#1941)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml
- Update config yml to reflect proper default vals.  (#1942)
=> [7.x] Update config yml to reflect proper default vals. (#1942)

cmd/root.go
fixes elastic/apm-server#1983
In 6.6 beats introduced ILM as beta feature. APM Server does not document, nor actively support it, but inherits the logic. This means, someone _could_ configure to run the server with ILM enabled and use the `setup` and `export` cmds for `ilm-policy`. This is not a great experience, for several reasons, one of them is that the implemented beta logic does not work well with current APM index strategies. For 6.x there is currently no way of restricting a users configuration, but we can remove the `ilm-policy` from the `setup` and `export` cmd.
Proposal:
Keep the logic unchanged for 6.6 as it is already released and ILM is in _beta_ in beats, and not documented in APM Server.
Remove the `setup` and `export` cmd for `ilm-policy` in 6.7.
=> [6.7] Remove ilm-policy from export and setup cmd.

Jenkinsfile
In case we want to disable the `Check kibana Obj. Updated` stage
=> [APM-CI] allow disable the kibana update check stage

_meta/kibana/7/dashboard/apm-dashboards.json, beater/beater.go, cmd/root.go
closes #1997 
```
$ ./apm-server test config -E setup.dashboards.enabled=true
Exiting: setting 'setup.dashboards' has been removed
$ ./apm-server test config -E setup.dashboards.enabled=false -e
...
2019-03-15T16:42:28.306-0400	WARN	[beater]	beater/beater.go:72	setting 'setup.dashboards' has been removed
```
related to #1905
=> Fail setup dashboard sooner

docs/storage-management.asciidoc
This PR attempts to document the APM sizing guide. I've also taken this opportunity to clean up the _Storage Management_ section of the documentation (grammar and formatting).
Seeing as Juan is out for a while, I'm hoping one of you can take a look when you have some time.
Closes elastic/apm-server#1855
=> [Docs] Document APM Server sizing

docs/guide/install-and-run.asciidoc
* Adds ESS installation link
* Doesn't require same stack version
* Removes Kibana dashboards info
Related to #2003, https://github.com/elastic/apm/issues/63
Backport to 7.0/7.x
=> [docs] Update install instructions

beater/beater.go, cmd/root.go
Dashboard loading and the corresponding setup.dashboards configuration
have been deprecated since 6.4.  To enable a smoother transition to 7.0,
apm-server will log a warning when the option is set.
very similar to #1999 except does not prevent apm-server from starting since dashboards are still bundled with 6.7.
=> [6.7] help with setup.dashboards deprecation

_beats/libbeat/tests/system/beat/beat.py, beater/beater.go, beater/beater_test.go, beater/config.go, tests/system/apmserver.py, tests/system/test_setup.py
setup pipelines if explicitly directed to or doing `setup --pipelines` and the config is not set at all
fixes #2008
=> enable pipeline registration for setup --pipelines

changelogs/6.6.asciidoc, docs/common-problems.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/guide/install-and-run.asciidoc, docs/storage-management.asciidoc
Backports the following commits to 7.0
* docs: add 6.6.2 release notes (#1991)
* [Docs] Document APM Server sizing (#1921)
* docs: update install instructions (#2009)
=> [docs] Backport docs 7.0

changelogs/6.6.asciidoc, docs/common-problems.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/guide/install-and-run.asciidoc, docs/storage-management.asciidoc
Backports the following commits to 7.x
* docs: add 6.6.2 release notes (#1991)
* [Docs] Document APM Server sizing (#1921)
* docs: update install instructions (#2009)
=> [docs] Backport docs 7.x

changelogs/6.6.asciidoc, docs/common-problems.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/guide/install-and-run.asciidoc
Backports the following commits to 6.7
* docs: add 6.6.2 release notes (#1991)
* docs: update install instructions (#2009)
=> [docs] Backport docs 6.7

docs/common-problems.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/guide/install-and-run.asciidoc
Backports the following commits to 6.6
* docs: update install instructions (#2009)
=> [docs] Backport docs 6.6

docs/common-problems.asciidoc, docs/copied-from-beats/outputconfig.asciidoc
Backports the following commits to 6.5
=> [docs] Backport docs 6.5

idxmgmt/supporter_test.go
Came across this at 21:00 EST / 0100 UTC:
```
--- FAIL: TestIndexSupport_BuildSelector (0.01s)
--- FAIL: TestIndexSupport_BuildSelector/with_meta_information (0.00s)
supporter_test.go:168: 
Error Trace:	supporter_test.go:168
Error:      	Not equal: 
expected: "apm-7.0.0-2019.03.19"
actual  : "apm-7.0.0-2019.03.20"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-apm-7.0.0-2019.03.19
+apm-7.0.0-2019.03.20
Test:       	TestIndexSupport_BuildSelector/with_meta_information
--- FAIL: TestIndexSupport_BuildSelector/meta_information_overwrites_config (0.00s)
supporter_test.go:168: 
Error Trace:	supporter_test.go:168
Error:      	Not equal: 
expected: "apm-7.0.0-2019.03.19"
actual  : "apm-7.0.0-2019.03.20"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-apm-7.0.0-2019.03.19
+apm-7.0.0-2019.03.20
Test: …
```
=> expect UTC indices in test

docs/breaking-changes.asciidoc, docs/guide/apm-breaking-changes.asciidoc, docs/guide/apm-release-notes.asciidoc
Fixes https://github.com/elastic/apm-server/pull/1940
Backport to 7.0
=> [docs] Fix release notes: 7.7.0 -> 7.0.0

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, package-README.md.tmpl
fixes #2016 
also part of #2026
=> Doc clarifications

docs/configuring.asciidoc, docs/ilm-setup.asciidoc
Here's my first crack at manual ILM setup for APM Server. Closes https://github.com/elastic/apm-server/issues/1545.
Huge shoutout to @graphaelli for creating an awesome [walkthrough](https://github.com/elastic/apm-server/issues/1545#issuecomment-446817453) of the process.
Note: The asciidoc for this change is really ugly due to our `//console` tags not jiving with ordered lists.
=> [docs] Add manual ILM instructions

idxmgmt/supporter_test.go
=> [7.0] expect UTC indices (#2027)

changelogs/6.7.asciidoc, docs/version.asciidoc
In preparation for the `6.7` release,this PR updates the release state to "released".  I'll merge this when the time is right. 
@graphaelli / @jalvz  - can you verify the `6.7` release notes below look good to go:
https://github.com/elastic/apm-server/blob/56b4ebe0088c9a15ea5eb5f4d491da19f08c1bc6/changelogs/6.7.asciidoc#L6-L22
=> [docs] 6.7 release-state

docs/copied-from-beats/repositories.asciidoc, docs/index.asciidoc, docs/version.asciidoc
Fixes "Beats" reference in APM Server documentation: https://github.com/elastic/apm-server/issues/2005.
Beats PR to persist these changes: https://github.com/elastic/beats/pull/11436.
This PR also updates `repositories.asciidoc` to the current version, and adds in the `:major-version:` attribute.
=> [docs] Fix confusing beats reference

docs/setting-up-and-running.asciidoc
Fixes #2017.
Note: Decided to link to the directory layout instead of documenting where files live on this page.
=> [docs] Add deb/rpm running instructions

changelogs/6.7.asciidoc, changelogs/7.0.asciidoc, docs/breaking-changes.asciidoc, docs/configuring.asciidoc, docs/copied-from-beats/repositories.asciidoc, docs/guide/apm-breaking-changes.asciidoc, docs/guide/apm-release-notes.asciidoc, docs/ilm-setup.asciidoc, docs/index.asciidoc, docs/setting-up-and-running.asciidoc, docs/version.asciidoc
This PR backports the following commits to 7.0:
* [docs] Add manual ILM instructions (#2033)
* [docs] fix 7.7.0 to 7.0.0 (#2034)
* [docs] fix release note links (#2035)  …
* docs: udpate repositories.asciidoc (#2042)
* [docs] Add deb/rpm running instructions (#2043)
=> [docs][7.0] Backport docs

changelogs/6.7.asciidoc, changelogs/7.0.asciidoc, docs/breaking-changes.asciidoc, docs/configuring.asciidoc, docs/copied-from-beats/repositories.asciidoc, docs/guide/apm-breaking-changes.asciidoc, docs/guide/apm-release-notes.asciidoc, docs/ilm-setup.asciidoc, docs/index.asciidoc, docs/setting-up-and-running.asciidoc, docs/version.asciidoc
This PR backports the following commits to 7.x:
* [docs] Add manual ILM instructions (#2033)
* [docs] fix 7.7.0 to 7.0.0 (#2034)
* [docs] fix release note links (#2035)  …
* docs: udpate repositories.asciidoc (#2042)
* [docs] Add deb/rpm running instructions (#2043)
=> [docs][7.x] Backport docs

docs/configuring.asciidoc, docs/copied-from-beats/repositories.asciidoc, docs/ilm-setup.asciidoc, docs/index.asciidoc, docs/setting-up-and-running.asciidoc, docs/version.asciidoc
This PR backports the following commits to 6.7:
* [docs] Add manual ILM instructions (#2033)
* [docs] fix 7.7.0 to 7.0.0 (#2034)
* [docs] fix release note links (#2035)  …
* docs: udpate repositories.asciidoc (#2042)
* [docs] Add deb/rpm running instructions (#2043)
=> [docs][6.7] Backport docs

packaging/files/linux/deb-post-install.sh.tmpl
With the `apm-server` user change from 6.x to 7.0 in #1833, the default debian install of apm-server can't be restarted without user intervention after upgrading.  By always making perm changes on debian package install, this manual step is removed bringing it in sync with what happens with RPM-installs and with user expectations, based on 7.0 beta feedback.
related to #2022
=> improve debian package upgrade

docs/configuring-ingest.asciidoc, docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/https.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/security/linux-seccomp.asciidoc, docs/copied-from-beats/security/securing-beats.asciidoc, docs/copied-from-beats/shared-configuring.asciidoc, docs/copied-from-beats/shared-ssl-logstash-config.asciidoc, docs/copied-from-beats/shared-template-load.asciidoc, docs/copied-from-beats/step-test-config.asciidoc, docs/copied-from-beats/template-config.asciidoc, docs/index.asciidoc, docs/setting-up-and-running.asciidoc
Removes old documentation attributes and replaces with the [shared](https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc) attributes.
See Beats PR: https://github.com/elastic/beats/pull/10956. Closes https://github.com/elastic/apm-server/issues/1964
=> [docs] Remove old attributes

docs/upgrading-to-70.asciidoc, docs/upgrading.asciidoc
Adds an upgrading to 7.0 guide. Closes elastic/apm-server#2022
=> [docs] Add 7.0 upgrading guide with deb/RPM instructions

NOTICE.txt, _beats/libbeat/docs/version.asciidoc, _beats/libbeat/scripts/generate_fields_docs.py, _beats/testing/environments/args.yml, docs/fields.asciidoc, vendor/vendor.json
applies elastic/beats#11214 despite it not being backported in libbeat
closes elastic/apm-server#1980
=> docs: mark objects as not enabled

docs/sourcemap-api.asciidoc
Fixes https://github.com/elastic/apm-server/issues/2031
Backport to 6.6. and 6.5
=> [docs] Update sourcemaps note

docs/breaking-changes.asciidoc, docs/guide/apm-breaking-changes.asciidoc, docs/guide/apm-release-notes.asciidoc, docs/guide/index.asciidoc, docs/guide/opentracing.asciidoc, docs/release-notes.asciidoc, docs/upgrading.asciidoc
This PR backports the following commits to 6.6:
* [docs] 7.0 Breaking changes, Release highlights, Migration assistant, ECS changes elastic/apm-server#1940
Edit: This PR backports *only* the release highlights portion of that PR
=> [docs][6.6] Backport documentation

docs/breaking-changes.asciidoc, docs/configuring-ingest.asciidoc, docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/https.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/security/linux-seccomp.asciidoc, docs/copied-from-beats/security/securing-beats.asciidoc, docs/copied-from-beats/shared-configuring.asciidoc, docs/copied-from-beats/shared-ssl-logstash-config.asciidoc, docs/copied-from-beats/shared-template-load.asciidoc, docs/copied-from-beats/template-config.asciidoc, docs/guide/apm-breaking-changes.asciidoc, docs/guide/apm-release-notes.asciidoc, docs/guide/index.asciidoc, docs/guide/opentracing.asciidoc, docs/index.asciidoc, docs/release-notes.asciidoc, docs/setting-up-and-running.asciidoc, docs/upgrading.asciidoc
This PR backports the following commits to 6.7:
* [docs] 7.0 Breaking changes, Release highlights, Migration assistant, ECS changes #1940
* [docs] Remove old attributes (#2053)
* [docs] Update ingest node documentation (#2061)
Edit: This PR backports *only* the release highlights portion of elastic/apm-server#1940
=> [docs][6.7] Backport documentation

changelogs/7.0.asciidoc, changelogs/head.asciidoc, docs/configuring-ingest.asciidoc, docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/https.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/security/linux-seccomp.asciidoc, docs/copied-from-beats/security/securing-beats.asciidoc, docs/copied-from-beats/shared-configuring.asciidoc, docs/copied-from-beats/shared-ssl-logstash-config.asciidoc, docs/copied-from-beats/shared-template-load.asciidoc, docs/copied-from-beats/step-test-config.asciidoc, docs/copied-from-beats/template-config.asciidoc, docs/index.asciidoc, docs/setting-up-and-running.asciidoc, docs/upgrading-to-70.asciidoc, docs/upgrading.asciidoc, docs/version.asciidoc
This PR backports the following commits to 7.x:
* [docs] Add 7.0 upgrading guide with deb/RPM instructions (#2054)
* [docs] Remove old attributes (#2053)
* [docs] Update ingest node documentation (#2061)
* [docs] 7.0.0-rc1 release notes (#2051)  …
* docs: changelog and updates rc2 (#2066)
=> [docs][7.x] Backport documentation

docs/guide/apm-breaking-changes.asciidoc
This PR adds a tagged region in the APM Overview > Breaking Changes page (https://www.elastic.co/guide/en/apm/get-started/master/apm-breaking-changes.html), such that content can be re-used in the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/master/elastic-stack-breaking-changes.html).
At least one tagged region must exist to prevent build errors in the Installation and Upgrade Guide, though as is the case now for V8.0.0 it can be an empty tagged region. 
At this time, the Installation and Upgrade Guide for version X only lists the breaking changes specific to that version. Since this APM page contains information about multiple versions, we either need to (1) ensure that only the items that are specific to the appropriate version are tagged as "notable" …
=> [DOCS] Adds tagged region for notable breaking changes

beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json, beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json, beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json, docs/data/elasticsearch/generated/errors.json, docs/data/elasticsearch/generated/transactions.json, model/metadata/system.go, model/metadata/system_test.go, processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json, tests/system/error.approved.json, tests/system/transaction.approved.json
- Align host.hostname with ECS under kubernetes  (#2059)
=> [7.0] Align host.hostname with ECS under kubernetes (#2059)

Makefile, NOTICE.txt, _beats/dev-tools/ecs-migration.yml, _beats/libbeat/scripts/Makefile, _beats/libbeat/tests/system/beat/beat.py, _beats/testing/environments/docker/kafka/Dockerfile, vendor/github.com/elastic/beats/libbeat/cfgfile/glob_manager.go, vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go, vendor/github.com/elastic/beats/libbeat/monitoring/monitoring.go, vendor/github.com/elastic/beats/libbeat/monitoring/report/elasticsearch/client.go, vendor/github.com/elastic/beats/libbeat/monitoring/report/elasticsearch/config.go, vendor/github.com/elastic/beats/libbeat/monitoring/report/elasticsearch/elasticsearch.go, vendor/github.com/elastic/beats/libbeat/monitoring/report/report.go, vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go, vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/elasticsearch.go, vendor/github.com/elastic/beats/libbeat/processors/actions/checks.go, vendor/github.com/elastic/beats/libbeat/processors/actions/truncate_fields.go, vendor/github.com/elastic/beats/libbeat/processors/add_docker_metadata/add_docker_metadata.go, vendor/github.com/elastic/beats/x-pack/libbeat/licenser/elastic_fetcher.go, vendor/github.com/elastic/beats/x-pack/libbeat/licenser/license.go, vendor/github.com/elastic/beats/x-pack/libbeat/licenser/manager.go, vendor/vendor.json
Major changes from libbeat:
* Fix index template always being overwritten - elastic/beats#11671
* Perform Basic license check on Elasticsearch connect - elastic/beats#11296 + elastic/beats#11649
* Support shipping directly to monitoring cluster elastic/beats#9260
and finally address these make warnings:
```
$ make
Makefile:48: warning: overriding commands for target `check-headers'
_beats/libbeat/scripts/Makefile:135: warning: ignoring old commands for target `check-headers'
Makefile:56: warning: overriding commands for target `add-headers'
_beats/libbeat/scripts/Makefile:142: warning: ignoring old commands for target `add-headers'
Makefile:149: warning: overriding commands for target `import-dashboards'
```
=> Update beats framework to 5554677

docs/guide/apm-breaking-changes.asciidoc
Tagged region should not include the section header, otherwise this happens:
=> [docs][7.0] Fix stack docs tagged region

_meta/kibana/7/dashboard/apm-dashboards.json, beater/beater.go, cmd/root.go
* Fail setup dashboard sooner (#1999)
=> Fail setup dashboard sooner (#1999)

changelogs/7.0.asciidoc, docs/version.asciidoc
* Bump `stack-version`
* Bump `release-state`
* Strip `coming[7.0.0]` tag
=> [docs] bump stack-version and release-state for 7.0.0

changelogs/6.7.asciidoc, changelogs/7.0.asciidoc, docs/breaking-changes.asciidoc, docs/guide/apm-breaking-changes.asciidoc, docs/guide/apm-release-notes.asciidoc, docs/release-notes.asciidoc, docs/upgrading-to-70.asciidoc
Adds the following commits to `master`
* docs: 6.7.1 release notes (#2064)
* docs: add 7.0.0 breaking changes and release notes (#2073)
=> [docs] Cherry-picks 6.7.1 and 7.0.0 release notes

docs/guide/apm-data-model.asciidoc
Closes https://github.com/elastic/apm-dev/issues/400.
Related to https://github.com/elastic/apm-dev/issues/302.
I added the note on upper limits for fields to the apm-data-model documentation. It seemed to be the best location, but I'm open to other ideas if anyone has any.
=> [docs] Document upper limit for fields

changelogs/6.7.asciidoc, docs/configuration-rum.asciidoc, docs/guide/agent-server-compatibility.asciidoc, docs/guide/apm-data-model.asciidoc, docs/guide/distributed-tracing.asciidoc, docs/rum.asciidoc, docs/sourcemap-api.asciidoc
Backports the following commits to `7.0`:
* [docs] 6.7.1 Version bump and release notes elastic/apm-server#2064
* docs: update RUM and DT (#2090)
* docs: upper limit for fields (#2093)
=> [docs] 7.0 documentation backports

_beats/dev-tools/packaging/templates/linux/systemd.unit.tmpl, changelogs/7.0.asciidoc
- set user/group under systemd  (#2101)
=> [7.0] set user/group under systemd (#2101)

changelogs/7.0.asciidoc, docs/copied-from-beats/shared-systemd.asciidoc, docs/installing.asciidoc, docs/setting-up-and-running.asciidoc
=> [7.0] add systemd docs (#2102)

Jenkinsfile
allow using comments like the following to trigger the build from GitHub 
* `jenkins run tests`
* `jenkins run the tests`
* `jenkins run the tests please`
=> [APM-CI] trigger build with a GitHub comment

docs/guide/index.asciidoc, docs/guide/redirects.asciidoc
Creates a placeholder landing page/link for https://github.com/elastic/apm-server/issues/2111.
Unblocks the docs from https://github.com/elastic/kibana/pull/35150.
The link from Kibana will be:
```js
// formatted
{config.docs.base_url}guide/en/apm/get-started/{config.docs.version}/metadata.html
// which points here in master
https://www.elastic.co/guide/en/apm/get-started/master/metadata.html
```
The placeholder in master looks like this. It is not public facing, and will not be accessible unless users click on the link from the master branch in Kibana.
Note: I've decided to call the anchor "metadata". If anyone thinks a different name is more appropriate, please say so.
=> [docs] Add metadata landing page

script/are_kibana_saved_objects_updated.py
As the [location of the index pattern file in Kibana has changed](https://github.com/elastic/kibana/pull/34665/files#diff-0a3b685fd8292afc7b7ed6466183ac15) , the test for checking if the index pattern is in sync needs to be adapted.
=> Fix test for syncing Kibana index pattern.

_beats/script/build_docs.sh, _meta/beat.yml, apm-server.docker.yml, apm-server.yml, docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/monitoring/monitoring-beats.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/repositories.asciidoc, docs/copied-from-beats/shared-docker.asciidoc, docs/copied-from-beats/shared-path-config.asciidoc, docs/copied-from-beats/shared-ssl-config.asciidoc, docs/index.asciidoc
Updating some docs copied from beats. Everything is pretty straight forward, though I have two comments:
* ~My main concern is with the changes to `monitoring-beats.asciidoc`. Looks like https://github.com/elastic/beats/pull/9260 introduced a new class of settings named `monitoring.*`, which I can't get to work in APM Server. Can a dev confirm these doc changes should be left out for now?~ edit: Just realized I was trying this in `7.0`, not `master`. This change works in master. Should we also update `apm-server.yml` to use the new settings name?
* A separate build issue was causing my `make update-beats-docs` command to fail. To try and fix it, I updated the build_docs script to use the dockerized build command. This seems to work fine. Might make sense to update now that the `.pl` …
=> [docs] Update documentation copied from beats

beater/intake_handler.go
Request failures for Intake API should be logged on log level `error` instead of log level `info`. 
implements #2124
=> Log errors on error log level.

beater/common_handler.go, beater/intake_handler.go, beater/intake_handler_test.go, beater/route_config.go
Wraps requests to rum endpoint in the log handler to ensure logger is
set and request is counted.
Recover from potential server panics while processing requests and log
them.
implements #2143
=> Fix counters and logs for processing requests.

beater/common_handler.go, beater/intake_handler.go, beater/intake_handler_test.go, beater/route_config.go
Wraps requests to rum endpoint in the log handler to ensure logger is
set and request is counted.
Recover from potential server panics while processing requests and log
them.
implements #2143
=> [7.0] Fix counters and logs for processing requests.

changelogs/6.7.asciidoc, model/metadata/user.go, model/metadata/user_test.go
already allowed by intake spec
backports part of #1783 
closes #2127
=> Fix numeric user id decoding

_beats/libbeat/tests/system/requirements.txt
- bump requirements.txt versions  (#2158)
=> [7.0] bump requirements.txt versions (#2158)

docs/copied-from-beats/outputconfig.asciidoc
Updates the Elasticsearch output config with APM Server fields. Unfortunately, I can't come up with a way to do this without introducing a bunch of new conditionals.
I've swapped out `fields.log_type` with `processor.event`, but open to other ideas, or using regexp if there are better examples.
**APM Issue:** closes https://github.com/elastic/apm-server/issues/2130. 
**Beats PR:** https://github.com/elastic/beats/pull/12034
=> [docs] Update ES output config

docs/guide/install-and-run.asciidoc
All agents have supported technology pages now. APM Overview needed to be updated accordingly.
Related: https://github.com/elastic/apm-dev/issues/425
=> [docs] Link to new supported technology pages

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, changelogs/head.asciidoc, ingest/pipeline/definition.json, tests/system/apmserver.py, tests/system/test_integration.py
Adds two new pipeline definitions without changing the existing `apm_user_agent`:
* `apm_user_geo` - only GeoIP resolution of `client.ip` to `client.geo`
* `apm` - both `apm_user_agent` and `apm_user_geo`
updates the default pipeline suggested in apm-server.yml
closes #1283
=> add geoip + default pipeline definitions

docs/guide/apm-data-model.asciidoc
Closes: https://github.com/elastic/apm-server/issues/2116
* Adds information on how the transaction name and type impact the Kibana UI.
* Adds recommendations for naming and typing transactions to the APM data model.
@watson, since you opened the initial issue, can you take a look? Any recommendations for improvement, especially around L104 & L105, are greatly appreciated.
=> [docs] UI implications of transaction name and type

CHANGELOG.asciidoc, changelogs/6.7.asciidoc, changelogs/6.8.asciidoc, docs/guide/apm-release-notes.asciidoc
A bit mixed on adding 6.8.0 release notes to 7.0 since it was released after 7.0 but went for it as most users would probably expect them to be there.
=> sync changelogs/release notes to 7.0

docs/setting-up-and-running.asciidoc
Clarifies what `-e` flag does in the "setting up and running" section of APM Server documentation.
=> [docs] Clarify -e flag when running APM Server

changelogs/head.asciidoc, idxmgmt/supporter.go, idxmgmt/supporter_test.go
Raise ILM not supported error early before any templates are loaded
to ensure clean state.
fixes elastic/apm-server#2208
=> Check if ILM is supported when configured.

changelogs/7.2.asciidoc, idxmgmt/supporter.go, idxmgmt/supporter_test.go
- Check if ILM is supported when configured.  (#2209)
=> [7.2] Check if ILM is supported when configured. (#2209)

beater/intake_handler.go
- remove duplicated writeHeader call  (#2230)
=> [7.x] remove duplicated writeHeader call (#2230)

Makefile
`apm-server.yml == _meta/beat.yml`, so just use that directly.  Per discussion, in the future we could create another source of truth for configuration settings and generate each of these files but this should address the outstanding issue with apm-server.docker.yml.
fixes elastic/apm-server#2123
=> make apm-server.docker.yml generation consistent with apm-server.yml

changelogs/7.2.asciidoc, idxmgmt/supporter.go, idxmgmt/supporter_test.go
- Check if ILM is supported when configured.  (#2209)
=> [7.x] Check if ILM is supported when configured. (#2209)

docs/guide/apm-data-model.asciidoc
Fixes the broken docs build by using the versioned agent attributes
=> [docs] use correct agent references

docs/guide/apm-data-model.asciidoc
For some reason the location of these pages changed today. I'm unable to figure out why. This should hopefully fix the problem. The jenkins test will fail this
=> docs: fix links to RUM

README.md
Opted for in-repo documentation as these are apm-server developer focused.
closes elastic/apm-server#1543
=> document docker packaging

docs/guide/overview.asciidoc
Hi - I was reading docs on the web site and saw this, happy to start contributing.
From this public page: 
https://www.elastic.co/guide/en/apm/get-started/current/overview.html
=> correct typo for word can cited as 'an'

docs/copied-from-beats/outputconfig.asciidoc
* Removes old statement about APM not being on Cloud yet.
* Closes elastic/apm-server#2178 
* Persisted in the beats repo: https://github.com/elastic/beats/pull/12456
=> [docs] Fix APM on cloud bug

docs/redirects.asciidoc
Adds info about `apm-contrib` to the dashboards redirect page
=> [docs] Update redirect page for dashboards

docs/configuring.asciidoc, docs/copied-from-beats/command-reference.asciidoc, docs/guide/apm-release-notes.asciidoc, docs/ilm-setup.asciidoc, docs/ilm.asciidoc
Closes https://github.com/elastic/apm-server/issues/2136
Needs https://github.com/elastic/apm-server/pull/2228 (xpack security improvements from Beats)
~~Rough draft up for @simitt and I to discuss on Monday. Lot's of work to do here still, don't get too excited 😄~~
Conversation with Silvia on Jun 4:
* Do not document ability to change ILM policy. This is because it can take up to seven days for the changes to take effect.
* Keep the manual ILM instructions around for now. For users that want to customize ILM, point them at this solution.
* Encourage the user to use the setup command
* Privileges required for APM Server:
* cluster: manage_ilm
* indices: manage, manage_ilm
=> [docs] ILM documentation

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/beater_test.go, beater/config.go, changelogs/6.8.asciidoc, tests/system/test_access.py
* Enable overwriting ingest pipelines by default. (#2281)
=> [6.8] Make client_auth optional by default. (#2281)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/beater_test.go, beater/config.go, changelogs/7.2.asciidoc, tests/system/test_access.py
* Enable overwriting ingest pipelines by default. (#2281)
=> [7.2] Make client_auth optional by default. (#2281)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/beater_test.go, beater/config.go, changelogs/head.asciidoc, tests/system/test_access.py
This PR changes `ssl.client_authentication` from `required` to `optional`,  meaning that client certificates are verified if available. 
Client authentication is not considered to be a requirement for secure communication between APM agents and APM server, as an additional _token_ can be configured and provided for authentication. None of the agents currently support client authentication, so enforcing it as default does not seem reasonable. Changing the default would also mean a breaking change.
=> Make client_auth optional by default.

beater/intake_handler_test.go, beater/route_config.go, beater/server.go, beater/server_test.go, changelogs/head.asciidoc
found while working on #2201, it impacts a few operations that may fail:
https://github.com/elastic/apm-server/blob/51942e8429f3073191988e438cd98e31cba99396/beater/route_config.go#L145
https://github.com/elastic/apm-server/blob/51942e8429f3073191988e438cd98e31cba99396/beater/route_config.go#L193
=> abort server startup on sourcemap configuration error

Makefile, _beats/libbeat/scripts/Makefile, _beats/script/build_docs.sh, script/build_apm_docs.sh
Moves `make docs`, `make docs-preview`, and `make apm-docs` to the new docker build script. Updates the help descriptions to be more clear.
Some of this needs to be persisted in the beats repo. Here's the PR for that: https://github.com/elastic/beats/pull/12522
=> [docs] Updates build script and description

_meta/beat.yml, agentcfg/fetch.go, agentcfg/fetch_test.go, agentcfg/model.go, apm-server.docker.yml, apm-server.yml, beater/agent_config_handler.go, beater/agent_config_handler_test.go, beater/beater.go, beater/beater_test.go, beater/config.go, beater/onboarding_test.go, beater/route_config.go, beater/server.go, changelogs/head.asciidoc, convert/convert.go, tests/kibana.go
This introduces a new requirement (Kibana) and setting for it, in the `apm-server` namespace (disabled by default).
It also adds an endpoint `/v1/agent/configs` for agents to poll configuration, requiring them to be authenticated (except RUM).
Supersedes https://github.com/elastic/apm-server/pull/2095/
More info in https://github.com/elastic/apm/issues/4
=> Adds initial support for agent remote configuration

docs/copied-from-beats/outputconfig.asciidoc, docs/guide/overview.asciidoc, docs/redirects.asciidoc
Backports the following documentation commits to `7.1`:
* correct typo for word can cited as 'an' (#2263)
* [docs] Update redirect page for dashboards (#2269)
* [docs] Fix APM on cloud bug (#2270)
=> [docs][7.1] Documentation backports

docs/copied-from-beats/outputconfig.asciidoc, docs/guide/overview.asciidoc, docs/redirects.asciidoc
Backports the following documentation commits to `7.0`:
* correct typo for word can cited as 'an' (#2263)
* [docs] Update redirect page for dashboards (#2269)
* [docs] Fix APM on cloud bug (#2270)
=> [docs][7.0] Documentation backports

docs/brew.asciidoc, docs/copied-from-beats/shared-directory-layout.asciidoc, docs/installing.asciidoc, docs/setting-up-and-running.asciidoc
Adds brew install instructions per https://github.com/elastic/elasticsearch/pull/42915.
Closes https://github.com/elastic/apm-server/issues/2261.
~I can successfully start APM Server and send data to ES with these instructions. However, it seems 
`apm-server setup --pipelines` doesn't work. I get the following error: `Exiting: open /usr/local/Cellar/apm-server-full/7.1.1/libexec/ingest/pipeline/definition.json: no such file or directory`. I can't figure out where the `definition.json` file defaults to.~ (fixed)
=> [docs] Brew install instructions

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/beater.go, beater/beater_test.go, beater/config.go, beater/config_test.go, beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json, beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json, beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json, beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json, beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json, beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json, changelogs/head.asciidoc, docs/configuration-process.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, publish/pub.go, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/error.approved.json, tests/system/test_integration.py, tests/system/test_pipelines.py, tests/system/transaction.approved.json
Register and apply geo-ip and user-agent pipeline by default.
closes elastic/apm-server#1972
=> Enable APM pipeline by default.

docs/common-problems.asciidoc, docs/guide/agent-server-compatibility.asciidoc, docs/guide/apm-data-model.asciidoc, docs/guide/apm-doc-directory.asciidoc, docs/guide/install-and-run.asciidoc, docs/version.asciidoc
Adds the .NET agent to the APM Overview documentation. 
Closes https://github.com/elastic/apm-agent-dotnet/issues/313.
Needs to be backported to `7.x` and `7.2`
=> docs: add .NET agent links and information

docs/common-problems.asciidoc, docs/guide/agent-server-compatibility.asciidoc, docs/guide/apm-data-model.asciidoc, docs/guide/apm-doc-directory.asciidoc, docs/guide/install-and-run.asciidoc, docs/version.asciidoc
Backports the following commits to `7.2`
* docs: add .NET agent links and information #2316
=> [docs][7.2] Add .NET agent links and information (#2316)

docs/common-problems.asciidoc, docs/guide/agent-server-compatibility.asciidoc, docs/guide/apm-data-model.asciidoc, docs/guide/apm-doc-directory.asciidoc, docs/guide/install-and-run.asciidoc, docs/version.asciidoc
Backports the following commits to `7.x`
* docs: add .NET agent links and information #2316
=> [docs][7.x] Add .NET agent links and information (#2316)

Makefile
- make apm-server.docker.yml generation consistent with apm-server.yml  (#2234)
=> [7.x] make apm-server.docker.yml generation consistent with apm-server.yml (#2234)

beater/config.go, beater/config_test.go, changelogs/7.2.asciidoc, tests/system/test_pipelines.py
- Enable overwriting ingest pipelines by default.  (#2273)
=> [7.2] Enable overwriting ingest pipelines by default. (#2273)

beater/config.go, beater/config_test.go, tests/system/test_pipelines.py
- Enable overwriting ingest pipelines by default.  (#2273)
=> [7.x] Enable overwriting ingest pipelines by default. (#2273)

Jenkinsfile
set sync stage unstable in case of failure, the build would be success
=> ci: set sync stage unstable in case of failure

beater/intake_handler_test.go, beater/route_config.go, beater/server.go, beater/server_test.go
- abort server startup on sourcemap configuration error  (#2278)
=> [7.x] abort server startup on sourcemap configuration error (#2278)

_meta/beat.yml, agentcfg/fetch.go, agentcfg/fetch_test.go, agentcfg/model.go, apm-server.docker.yml, apm-server.yml, beater/agent_config_handler.go, beater/agent_config_handler_test.go, beater/beater.go, beater/beater_test.go, beater/config.go, beater/onboarding_test.go, beater/route_config.go, beater/server.go, convert/convert.go, tests/kibana.go
- Adds initial support for agent remote configuration  (#2289)
=> [7.x] Adds initial support for agent remote configuration (#2289)

beater/route_config.go
- rename agent config endpoint  (#2303)
=> [7.x] rename agent config endpoint (#2303)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/config.go, beater/config_test.go, changelogs/head.asciidoc, tests/system/config/apm-server.yml.j2, tests/system/test_access.py
This PR adapts default settings for `client_authentication` when TLS is configured to latest changes in libbeat. It also documents and adds tests for the `verification_mode` setting. 
implements elastic/apm-server#2336
=> [TLS] Align client_auth handling to beats changes and add description for verification_mode

_meta/beat.yml, agentcfg/cache.go, agentcfg/cache_test.go, agentcfg/fetch.go, agentcfg/fetch_test.go, agentcfg/model.go, apm-server.docker.yml, apm-server.yml, beater/agent_config_handler.go, beater/agent_config_handler_test.go, beater/beater_test.go, beater/config.go, beater/route_config.go, convert/convert.go
- Add caching to Agent Remote Configuration handling  (#2337)
=> [7.x] Add caching to Agent Remote Configuration handling (#2337)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, changelogs/head.asciidoc, idxmgmt/feature.go, idxmgmt/ilm/config.go, idxmgmt/ilm/config_test.go, idxmgmt/ilm/supporter_factory.go, idxmgmt/ilm/supporter_factory_test.go, idxmgmt/indices.go, idxmgmt/manager.go, idxmgmt/manager_test.go, idxmgmt/supporter.go, idxmgmt/supporter_factory.go, idxmgmt/supporter_factory_test.go, idxmgmt/supporter_test.go, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_export.py, tests/system/test_integration.py, tests/system/test_pipelines.py, tests/system/test_setup_index_management.py
This PR changes default value for `apm-server.ilm.enabled` from `false` to `auto`.
On startup or setup cmd the server determines if preconditions are fulfilled for enabling ILM.
ILM will be enabled when supported by configured ES, and no custom index and indices settings are configured for `output.elasticsearch`.
When `apm-server.ilm.enabled` is set to `false`, ILM is turned off. 
When `apm-server.ilm.enabled` is set to `true`, the server checks if custom `output.elasticsearch.index` or `output.elasticsearch.indices` configuration is set. If set, the server refuses to start up and fails with according error message. 
Otherwise the server also checks if ES supports ILM. Since the configured ES might not immediately be available (temporary connection loss, currently starting up, ..) the …
=> [ILM] Enable ILM by default when supported by configured ES output.

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, idxmgmt/feature.go, idxmgmt/ilm/config.go, idxmgmt/ilm/config_test.go, idxmgmt/ilm/supporter_factory.go, idxmgmt/ilm/supporter_factory_test.go, idxmgmt/indices.go, idxmgmt/manager.go, idxmgmt/manager_test.go, idxmgmt/supporter.go, idxmgmt/supporter_factory.go, idxmgmt/supporter_factory_test.go, idxmgmt/supporter_test.go, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_export.py, tests/system/test_integration.py, tests/system/test_pipelines.py, tests/system/test_setup_index_management.py
- [ILM] Enable ILM by default when supported by configured ES output.  (#2356)
=> [7.x] [ILM] Enable ILM by default when supported by configured ES output. (#2356)

beater/agent_config_handler.go, beater/beater.go, beater/common_handler.go, beater/intake_handler.go, beater/onboarding.go, beater/onboarding_test.go, beater/route_config.go, beater/server.go, idxmgmt/ilm/supporter_factory.go, ingest/pipeline/register.go, log/selectors.go, model/metricset/event.go, model/sourcemap/payload.go, model/stacktrace.go, sourcemap/accessor.go, sourcemap/cache.go, sourcemap/elasticsearch.go, sourcemap/elasticsearch_test.go, sourcemap/mapper.go, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_integration.py, tests/system/test_integration_logging.py
Extracted some of the logging changes I've been kicking around:
* List all logging selectors in `github.com/elastic/apm-server/log`
* Start reducing logger creations
* Log status code for errored requests
* Propogate error on pipeline registration failure
for elastic/apm-server#2201
=> consolidate logging selectors

tests/system/test_integration.py
- Fix failing system-test  (#2370)
=> [7.x] Fix failing system-test (#2370)

tests/system/test_integration.py
- Fix failing system-test  (#2370)
=> [7.3] Fix failing system-test (#2370)

beater/beater_test.go, beater/config.go, tests/system/test_integration.py, tests/system/test_pipelines.py
* fixing flaky by removing a shorter timeout than default timeout of `10s`.
* remove useless `time.sleep` leftover in tests
* fix agent config cache expiration default from `10s` to `30s`, as stated in `apm-server.yml`.
=> Fix flaky tests, default value for agent config cache.

beater/beater_test.go, beater/config.go, tests/system/test_integration.py, tests/system/test_pipelines.py
- Fix flaky tests, default value for agent config cache.  (#2376)
=> [7.3] Fix flaky tests, default value for agent config cache. (#2376)

beater/beater_test.go, beater/config.go, tests/system/test_integration.py, tests/system/test_pipelines.py
- Fix flaky tests, default value for agent config cache.  (#2376)
=> [7.x] Fix flaky tests, default value for agent config cache. (#2376)

Jenkinsfile
Backport of the same change in the master, it allows completing the build even do the Sync stage fails, and mark the sync stage as unstable.
=> ci: set sync stage to unstable on failure

Jenkinsfile
it adds labels to script commands, this makes you'd show a proper description of the step on the CI UI and in notifications.
related to https://github.com/elastic/apm-server/pull/2268
=> ci: add labels to script commands

Jenkinsfile
enclose `tar` steps into `catchError` to ignore failures when it is not possible to grab test results files because of permissions errors.
=> fix: ignore fails on tar test results files

Jenkinsfile
The release stage is trigger on every branch merge, it is incorrect because the `BEATS_UPDATED` is wrong evaluated. This PR fixes the value check of `BEATS_UPDATED `
related to https://github.com/elastic/apm-server/pull/2268
=> fix: release stage should not be triggered always

agentcfg/fetch.go, beater/agent_config_handler.go, beater/agent_config_handler_test.go, beater/common_handler_test.go, beater/route_config.go, tests/system/config/apm-server.yml.j2, tests/system/test_integration_logging.py
=> Fix config handler

agentcfg/fetch.go, beater/agent_config_handler.go, beater/agent_config_handler_test.go, beater/common_handler_test.go, beater/route_config.go, tests/system/config/apm-server.yml.j2, tests/system/test_integration_logging.py
- Update kibana endpoint and introduce a killer switch to disable the  (#2386)
=> [7.x] Update kibana endpoint and introduce a killer switch to disable the (#2386)

Jenkinsfile
Uses the `isGitRegionMatch` step which it's defined in the shared library.
In the below screesnhot, the left page shows the console output for this particular PR, further details: [here](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/PR-2388/3/pipeline/23) while the right one shows the previous implementation.
=> feat(ci): use isGitRegionMatch step

script/jenkins/package.sh
Discovered in https://github.com/elastic/apm-server/pull/2268#discussion_r297240735, the other platforms aren't valuable for apm-server so skip building them to speed up the build.
=> build just the default packages

beater/agent_config_handler.go, beater/agent_config_handler_test.go, beater/common_handler.go, beater/headers/keys.go, beater/intake_handler.go
Set `nosniff` for all http responses against intake API. Move http header keys as constants to a central file.
=> Refactor http header strings. Add "X-Content-Type-Options: nosniff" header

agentcfg/fetch.go, beater/agent_config_handler.go, beater/agent_config_handler_test.go, beater/common_handler_test.go, beater/route_config.go, tests/system/config/apm-server.yml.j2, tests/system/test_integration_logging.py
- Update kibana endpoint and introduce a killer switch to disable the  (#2386)
=> [7.3] Update kibana endpoint and introduce a killer switch to disable the (#2386)

beater/agent_config_handler.go, beater/agent_config_handler_test.go
fixes elastic/apm-server#2404
needs backport to `7.x` and `7.3`.
=> Enclose etag and IfNoneMatch header in double quotes.

beater/agent_config_handler.go, beater/agent_config_handler_test.go
- Enclose etag and IfNoneMatch header in double quotes.  (#2407)
=> [7.x] Enclose etag and IfNoneMatch header in double quotes. (#2407)

beater/agent_config_handler.go, beater/agent_config_handler_test.go, changelogs/7.3.asciidoc
- Enclose etag and IfNoneMatch header in double quotes.  (#2407)
=> [7.3] Enclose etag and IfNoneMatch header in double quotes. (#2407)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, docs/agent-configuration.asciidoc, docs/configure-kibana-endpoint.asciidoc, docs/configuring.asciidoc, docs/intake-api.asciidoc, docs/redirects.asciidoc
WIP Agent configuration documentation for elastic/apm#86.
**Must be merged and backported simultaneously with https://github.com/elastic/kibana/pull/40084.**
Open questions:
* ~What's the script to sync the yml files?~
* ~Chat about these `apm-server.kibana.*` config options -- not sure they're all correct.~
* Impact of Cloud? Are `apm-server.kibana.*` settings blacklisted/whitelisted?
* tbd in https://github.com/elastic/cloud/issues/35680
* ~Figure out if we want to use the beats `configure-kibana-endpoint.asciidoc` file or maintain our own.~ Going to use this for now. There are too many differences.
* How will different/older server versions impact this?
=> [docs] Agent configuration documentation

CHANGELOG.asciidoc, docs/release-notes.asciidoc
Removes head, adds 7.3 and 7.2 links.
=> [docs][7.x] Fix documentation build errors

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, docs/agent-configuration.asciidoc, docs/configure-kibana-endpoint.asciidoc, docs/configuring.asciidoc, docs/intake-api.asciidoc, docs/redirects.asciidoc
Backports to `7.3`
* [docs] Agent configuration documentation (#2366)
=> [docs][7.3] Agent configuration documentation (#2366)

.ci/check-changelogs.groovy, .ci/jobs/apm-server-check-changelogs-mbp.yml
JJB failed when creating the job
```
16:22:06 2019-07-10 15:22:06,005 [jjbb.jenkins_server] [ERROR] '7d' is an invalid value for attribute name.periodic-folder-trigger
16:22:06 Valid values include: '1m', '2m', '5m', '10m', '15m', '20m', '25m', '30m', '1h', '2h', '4h', '8h', '12h', '1d', '2d', '1w', '2w', '4w'
16:22:06 Traceback (most recent call last):
```
=> ci(jenkins): 7d is not allowed but 1w instead

.ci/docker/golang-mage/Dockerfile
use fixed dependencies on golang Docker container
depends on https://github.com/elastic/apm-server/pull/2395
for elastic/apm-server#2394
=> fix: use fixed dependencies on golang Docker container

agentcfg/cache.go, agentcfg/cache_test.go, agentcfg/fetch.go, agentcfg/fetch_test.go, agentcfg/model.go, beater/agent_config_handler.go, beater/agent_config_handler_test.go, beater/beater.go, beater/common_handler.go, beater/onboarding_test.go, beater/route_config.go, beater/server.go, changelogs/7.3.asciidoc, kibana/connecting_client.go, kibana/connecting_client_test.go, log/selectors.go, tests/kibana.go, tests/system/test_integration_logging.py
Implement Kibana client wrapper that takes care of obtaining a valid
Kibana client, in case client cannot be obtained on startup.
Align returned response body to whether or not the user sends a secret token.
Log full error messages. 
fixes elastic/apm-server#2371
=> Ensure Kibana client reconnects.

agentcfg/cache.go, agentcfg/cache_test.go, agentcfg/fetch.go, agentcfg/fetch_test.go, agentcfg/model.go, beater/agent_config_handler.go, beater/agent_config_handler_test.go, beater/beater.go, beater/common_handler.go, beater/onboarding_test.go, beater/route_config.go, beater/server.go, changelogs/7.3.asciidoc, kibana/connecting_client.go, kibana/connecting_client_test.go, log/selectors.go, tests/kibana.go, tests/system/test_integration_logging.py
- Ensure Kibana client reconnects.  (#2421)
=> [7.3] Ensure Kibana client reconnects. (#2421)

agentcfg/cache.go, agentcfg/cache_test.go, agentcfg/fetch.go, agentcfg/fetch_test.go, agentcfg/model.go, beater/agent_config_handler.go, beater/agent_config_handler_test.go, beater/beater.go, beater/common_handler.go, beater/onboarding_test.go, beater/route_config.go, beater/server.go, changelogs/7.3.asciidoc, kibana/connecting_client.go, kibana/connecting_client_test.go, log/selectors.go, tests/kibana.go, tests/system/test_integration_logging.py
- Ensure Kibana client reconnects.  (#2421)
=> [7.x] Ensure Kibana client reconnects. (#2421)

script/jenkins/package.sh
- build just the default packages  (#2368)
=> [7.x] build just the default packages (#2368)

script/jenkins/package.sh
- build just the default packages  (#2368)
=> [7.3] build just the default packages (#2368)

beater/config.go, beater/config_test.go, changelogs/7.3.asciidoc, tests/system/test_integration_acm.py
- [ACM] Only allow cache expiration values in full seconds.  (#2443)
=> [7.3] [ACM] Only allow cache expiration values in full seconds. (#2443)

beater/config.go, beater/config_test.go, changelogs/7.3.asciidoc, tests/system/test_integration_acm.py
- [ACM] Only allow cache expiration values in full seconds.  (#2443)
=> [7.x] [ACM] Only allow cache expiration values in full seconds. (#2443)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/beater_test.go, beater/config.go, beater/config_test.go, changelogs/7.2.asciidoc, changelogs/7.3.asciidoc, tests/system/test_pipelines.py
fixes elastic/apm-server#2440
Reverting changes from https://github.com/elastic/apm-server/pull/2273.
Needs to be backported until `7.2`
=> Disable overwriting ingest pipelines by default.

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/beater_test.go, beater/config.go, beater/config_test.go, changelogs/7.2.asciidoc, changelogs/7.3.asciidoc, tests/system/test_pipelines.py
- Disable overwriting ingest pipelines by default.  (#2452)
=> [7.3] Disable overwriting ingest pipelines by default. (#2452)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/beater_test.go, beater/config.go, beater/config_test.go, changelogs/7.2.asciidoc, changelogs/7.3.asciidoc, tests/system/test_pipelines.py
- Disable overwriting ingest pipelines by default.  (#2452)
=> [7.x] Disable overwriting ingest pipelines by default. (#2452)

docs/ilm.asciidoc
Documentation for the ILM changes in https://github.com/elastic/apm-server/pull/2356/.
Backport to `7.x` and `7.3`
=> [docs] Update ILM enabled to “auto”

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/beater_test.go, beater/config.go, beater/config_test.go, beater/server_test.go, changelogs/7.2.asciidoc, tests/system/test_pipelines.py
* Disable overwriting ingest pipelines by default. (#2452)
=> [7.2] Disable overwriting ingest pipelines by default. (#2452)

beater/agent_config_handler.go, beater/agent_config_handler_test.go, tests/system/test_integration_acm.py
- [ACM] Return 200 instead of 404 for missing config.  (#2458)
=> [7.3] [ACM] Return 200 instead of 404 for missing config. (#2458)

beater/agent_config_handler.go, beater/agent_config_handler_test.go, tests/system/test_integration_acm.py
- [ACM] Return 200 instead of 404 for missing config.  (#2458)
=> [7.x] [ACM] Return 200 instead of 404 for missing config. (#2458)

idxmgmt/manager.go
ILM auto defaults ot true only for ES >= 7.0. ILM supported by ES in
latest 6.x versions. Change log message for auto disabling ILM to avoid
confusion.
fixes elastic/apm-server#2472
=> [ILM] change auto disabled message

tests/system/apmserver.py, tests/system/test_integration_acm.py
kibana creates that index - when testing without kibana it will not exist.  When testing with kibana, tests that depend on that index will fail if it is missing, no need to fail during setup
=> ignore unavailable agent configuration index during setup.

tests/system/apmserver.py, tests/system/test_integration_acm.py
- ignore unavailable agent configuration index during setup.  (#2475)
=> [7.x] ignore unavailable agent configuration index during setup. (#2475)

tests/system/apmserver.py, tests/system/test_integration_acm.py
- ignore unavailable agent configuration index during setup.  (#2475)
=> [7.3] ignore unavailable agent configuration index during setup. (#2475)

idxmgmt/manager.go
- [ILM] change auto disabled message  (#2473)
=> [7.x] [ILM] change auto disabled message (#2473)

idxmgmt/manager.go
- [ILM] change auto disabled message  (#2473)
=> [7.3] [ILM] change auto disabled message (#2473)

agentcfg/cache_test.go, agentcfg/fetch.go, agentcfg/fetch_test.go, agentcfg/model.go, agentcfg/model_test.go, agentcfg/query.go, beater/agent_config_handler.go, beater/agent_config_handler_test.go, changelogs/7.3.asciidoc, tests/system/test_integration_acm.py
To ensure Etag changes when config settings are updated, include config settings when calculating ID for config object.
fixes elastic/apm-server#2434
backport to `7.x` and `7.3`. 
fyi @felixbarny , @axw
=> [ACM] Create Etag from settings struct.

agentcfg/cache_test.go, agentcfg/fetch.go, agentcfg/fetch_test.go, agentcfg/model.go, agentcfg/model_test.go, agentcfg/query.go, beater/agent_config_handler.go, beater/agent_config_handler_test.go, changelogs/7.3.asciidoc, tests/system/test_integration_acm.py
- [ACM] Create Etag from settings struct.  (#2441)
=> [7.3] [ACM] Create Etag from settings struct. (#2441)

agentcfg/cache_test.go, agentcfg/fetch.go, agentcfg/fetch_test.go, agentcfg/model.go, agentcfg/model_test.go, agentcfg/query.go, beater/agent_config_handler.go, beater/agent_config_handler_test.go, changelogs/7.3.asciidoc, tests/system/test_integration_acm.py
- [ACM] Create Etag from settings struct.  (#2441)
=> [7.x] [ACM] Create Etag from settings struct. (#2441)

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/config.go, beater/route_config.go, changelogs/head.asciidoc, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_integration.py
via `rum.sourcemapping.enabled=false`
closes #2357
=> Disable sourcemapping config

Jenkinsfile
Since the documentation team has elastic-ci/docs build in place for all our PRs, our Documentation stage lose sense, we are doing the same and we have to maintain it. Because of that, we will start to remove this stage from all projects.
=> ci: remove the documentation stage

beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json, docs/data/elasticsearch/generated/spans.json, model/metadata/service.go, model/span/event_test.go, processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json, tests/system/spans.approved.json
- Add service.environment to spans.  (#2500)
=> [7.x] Add service.environment to spans. (#2500)

beater/agent_config_handler.go, beater/agent_config_handler_test.go, beater/asset_handler.go, beater/common_handler.go, beater/common_handler_test.go, beater/handler.go, beater/intake_handler.go, beater/intake_handler_test.go, beater/log_handler.go, beater/mux.go, beater/panicHandler.go, beater/panic_handler_test.go, beater/request/context.go, beater/root_handler.go, beater/route_config.go
This is the first of a series of PRs for refactoring the `beater` handling wrt logging, monitoring and writing response, more infos in the meta issue #2489 . 
This PR introduces a `Context` struct abstracting the `http.ResponseWriter` and the `*http.Request` and a `ContextPool` that takes care of reusing idle `Context` instances. 
This PR aims for minimal changes to keep reviews easier. It contains _TODOs_ that will be addressed in follow up PRs before merging back to `master`. 
Partially implements #2201
=> [beater] Add context handlers and adapt log handling

Jenkinsfile
We start using immutable workers for windows, this makes the change.
=> ci: move to use new windows-2019-immutable workers

Jenkinsfile
Backports the following commits to 6.7:
=> [6.7] ci: move to use new windows-2019-immutable workers (#2503)

Jenkinsfile
=> [6.8] ci: move to use new windows-2019-immutable workers (#2503)

Jenkinsfile
=> [7.0] ci: move to use new windows-2019-immutable workers (#2503)

Jenkinsfile
Backports the following commits to 7.1:
=> [7.1] ci: move to use new windows-2019-immutable workers (#2503)

Jenkinsfile
=> [7.2] ci: move to use new windows-2019-immutable workers (#2503)

Jenkinsfile
=> [7.3] ci: move to use new windows-2019-immutable workers (#2503)

Jenkinsfile
=> [7.x] ci: move to use new windows-2019-immutable workers (#2503)

beater/server.go, tests/system/apmserver.py
- Log warning for RUM allow_origins setting '*'.  (#2499)
=> [7.x] Log warning for RUM allow_origins setting '*'. (#2499)

docs/guide/apm-data-model.asciidoc, docs/version.asciidoc
**Must be merged simultaneously with https://github.com/elastic/docs/pull/1033**
Updates Python Agent links from APM Server & APM Overview to point to `5.x`.
Needs to be backported to `7.x` and `7.3`.
=> [docs] update python agent links to 5.x

docs/guide/apm-data-model.asciidoc, docs/version.asciidoc
* Backports https://github.com/elastic/apm-server/pull/2519.
* Updates Python Agent links from APM Server & APM Overview to point to 5.x.
* It is expected that the docs build will fail on this PR.
=> [docs][7.3] Update python agent version

docs/guide/apm-data-model.asciidoc, docs/version.asciidoc
* Backports https://github.com/elastic/apm-server/pull/2519.
* Updates Python Agent links from APM Server & APM Overview to point to 5.x.
* It is expected that the docs build will fail on this PR.
=> [docs][7.x] Update python agent version

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/config.go, beater/route_config.go, changelogs/7.4.asciidoc, tests/system/apmserver.py, tests/system/config/apm-server.yml.j2, tests/system/test_integration.py
- Disable sourcemapping config  (#2488)
=> [7.x] Disable sourcemapping config (#2488)

docs/guide/apm-data-model.asciidoc
Closes https://github.com/elastic/apm/issues/113
Backport to `7.x` and `7.3`
=> [docs] Update custom context links

Jenkinsfile
Closes #2529
- Retry twice in case of any errors when building or testing
- Sleep between 5-10 seconds for each iteration.
- This is a raw implementation to reduce the build errors which are related to an environmental issue.
- For sure it's not the cleverest way to provide more stability in the CI but it will eventually reduce the manual actions to rebuild when there is a temporary issue with third party systems.
=> ci(jenkins): add more resilience to reduce any temporary glitches

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, docs/configuration-process.asciidoc, docs/copied-from-beats/monitoring/shared-monitor-config.asciidoc, docs/copied-from-beats/outputconfig.asciidoc
Closes #2120. 
* A lot of these changes are consistency related. Specifically, I made the headers the same size, ensured consistent spacing, and added periods where they were forgotten. I think they make the YML file look cleaner, but at the end of the day they aren't _super_ necessary, so I can undo them if you want to make the diff cleaner.
* Fixed some spelling/grammar issues
* Clarifications on what certain settings do.
* Fixed a few inconsistencies between the docs and the YML files. Most of these are also upstream in the Beats repo and will need to be persisted there.
@jalvz - perhaps we can chat about what you have in mind for irrelevant options to be deemphasized.
=> [docs] Config YML updates

docs/configuration-rum.asciidoc, docs/configuring-ingest.asciidoc
Closes https://github.com/elastic/apm-server/issues/2308.
Improves the pipeline documentation here: [Parse data using ingest node pipelines](https://www.elastic.co/guide/en/apm/server/master/configuring-ingest-node.html). Links to [Configure the Elasticsearch output](https://www.elastic.co/guide/en/apm/server/7.3/elasticsearch-output.html#pipelines-option-es) which has information on how to apply pipelines.
---
Closes https://github.com/elastic/apm-server/issues/2155.
I also wrapped this issue into this PR. This issue was opened back before pipelines were enabled by default, but I think it still makes sense to include a blurb on pipelines on the RUM config page. Unfortunately, the APM Server documentation is not using asciidoctor yet, so we can't tag and include paragraphs across pages. …
=> [docs] Update pipeline documentation

docs/version.asciidoc
For: https://github.com/elastic/docs/pull/958
This will need to be backported waaaaaay back.
=> [docs] Update links to APM JS RUM Agent

docs/version.asciidoc
=> [7.3] docs: update rum links (#2355)

docs/version.asciidoc
=> [7.2] docs: update rum links (#2355)

docs/version.asciidoc
Backports the following commits to 7.1:
=> [7.1] docs: update rum links (#2355)

docs/version.asciidoc
=> [7.0] docs: update rum links (#2355)

docs/version.asciidoc
=> [7.x] docs: update rum links (#2355)

docs/version.asciidoc
=> [6.8] docs: update rum links (#2355)

docs/version.asciidoc
Backports the following commits to 6.7:
=> [6.7] docs: update rum links (#2355)

docs/version.asciidoc
=> [6.6] docs: update rum links (#2355)

docs/version.asciidoc
=> [6.5] docs: update rum links (#2355)

docs/version.asciidoc
=> [6.4] docs: update rum links (#2355)

docs/guide/agent-server-compatibility.asciidoc
Updates Agent compatibility matrix for .NET and Python.
Backport to `7.3` and `7.x`.
=> [docs] Update agent compatibility

docs/version.asciidoc
current instructions:
```
[elastic-7.3]
name=Elastic repository for 7.3 packages
baseurl=https://artifacts.elastic.co/packages/7.3/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
```
should be:
```
baseurl=https://artifacts.elastic.co/packages/7.x/yum
```
same deal for apt
=> fix repo install instructions

docs/copied-from-beats/monitoring/monitoring-beats.asciidoc
=> Docs: Asciidoctor compatibility (6.8) (#2567)

docs/copied-from-beats/monitoring/monitoring-beats.asciidoc
=> Docs: Asciidoctor compatibility (6.7) (#2567)

docs/copied-from-beats/monitoring/monitoring-beats.asciidoc
=> Docs: Asciidoctor compatibility (6.6) (#2567)

docs/copied-from-beats/monitoring/monitoring-beats.asciidoc
=> Docs: Asciidoctor compatibility (6.5) (#2567)

script/update_kibana_objects.py
Amends #2545 
The `git rev-parse` trick worked for me because I only had tried it in 7.x and master, where we were out of sync already.
But normally one wants to execute the sync on top of a `elastic/feature-branch`, and as `feature-branch` won't exist in the `kibana` remote, it will fail.
Literally first thing that came to mind this morning when I woke up.
So I suggest to take an explicit `branch` argument instead of git juggling.
=> fix automatic kibana sync

_beats/libbeat/scripts/generate_fields_docs.py, docs/fields.asciidoc
This makes 7.2 build in asciidoctor! Needs to be backported.
Closes https://github.com/elastic/apm-server/issues/2577. Related beats PR: https://github.com/elastic/beats/pull/12242.
=> [docs][7.2] Fix fields.asciidoc for asciidoctor

docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/shared-docker.asciidoc, docs/copied-from-beats/shared-path-config.asciidoc
=> [docs][7.1] Remove arbitrary python expressions

docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/shared-docker.asciidoc, docs/copied-from-beats/shared-path-config.asciidoc
=> [docs][7.0] Remove arbitrary python expressions

docs/configuration-rum.asciidoc
Both the RUM Agent and Cloud link to literal anchors in the APM Server documentation. These links will break on the switch from asciidoc to asciidoctor. This PR adds in anchor tags so we can override the link defaults.
Backport to `7.x`, `7.3`.
Full error log available in https://github.com/elastic/docs/pull/1083#issuecomment-523130974.
For https://github.com/elastic/apm-server/issues/1965.
=> [docs] Add links to rum configs

docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/shared-path-config.asciidoc, docs/index.asciidoc
=> [docs][6.8] Remove arbitrary python expressions

docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/shared-path-config.asciidoc, docs/index.asciidoc
=> [docs][6.7] Remove arbitrary python expressions

docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/shared-path-config.asciidoc, docs/index.asciidoc
=> [docs][6.6] Remove arbitrary python expressions

docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/shared-path-config.asciidoc, docs/index.asciidoc
=> [docs][6.4] Remove arbitrary python expressions

docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/shared-path-config.asciidoc, docs/index.asciidoc
=> [docs][6.3] Remove arbitrary python expressions

docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/shared-path-config.asciidoc, docs/index.asciidoc
=> [docs][6.2] Remove arbitrary python expressions

docs/copied-from-beats/command-reference.asciidoc, docs/copied-from-beats/outputconfig.asciidoc, docs/copied-from-beats/shared-path-config.asciidoc, docs/index.asciidoc
=> [docs][6.5] Remove arbitrary python expressions

.ci/check-changelogs.groovy, Jenkinsfile
- `master` worker could be used but causes bottlenecks in some cases.
- This will allow to use of another worker and get rid of any potential bottlenecks when the build queue is massive.
=> ci(jenkins): avoid builds in the master worker

beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json, beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json, docs/data/elasticsearch/generated/errors.json, docs/data/elasticsearch/generated/transactions.json, model/context.go, model/error/event.go, model/transaction/event.go, processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json, tests/system/error.approved.json, tests/system/transaction.approved.json
- ES fields: Index socket.remote_address as client.ip  (#2588)
=> [7.x] ES fields: Index socket.remote_address as client.ip (#2588)

beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json, docs/data/elasticsearch/generated/errors.json, docs/spec/errors/error.json, model/error/event.go, model/error/event_test.go, model/error/generated/schema/error.go, processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
- auto-generate exception parent and remove property from the intake (#2609)
=> [7.x] auto-generate exception parent and remove property from the intake
