elastic/apm-server

README.md

Added blog post link

---

README.md

Was reading the readme and found a minor typo.

Fix typo in readme and add link for "Loading UI Dashboard"

---

processor/error/event.go
processor/model/common.go
processor/processor.go
processor/transaction/event.go
processor/transaction/trace.go

This PR removes some redundant code that I stumbled upon.

Remove redundant timestamp check and data structure

---

docs/spec/errors/error.json
docs/spec/transactions/transaction.json
processor/error/schema.go
processor/processor.go
processor/transaction/schema.go
tests/data/invalid/error/invalid_timestamp5.json
tests/data/invalid/transaction/invalid_timestamp5.json
tests/json_schema_test.go

Also brings back logging in case we missed other edge cases in the regular expression.

Update timestamp in JSON Spec for edge-case

---

tests/agent/nodejs/Makefile
tests/agent/nodejs/app.js
tests/agent/python/app.py

Some of the code change and now the agent code has to be updated. Fix node.js and python agent.

Fix agents code which is used for manual testing

---

docs/index.asciidoc

This makes it clear the docs are still work in progress. A link to the Github repository was added.

Add experimental title to APM Server docs

---

CHANGELOG.asciidoc
_meta/beat.yml
apm-server.reference.yml
apm-server.yml
beater/config.go
docs/error-api.asciidoc
docs/transaction-api.asciidoc
tests/agent/nodejs/README.md
tests/agent/nodejs/app.js
tests/agent/python/app.py
tests/docker-compose.yml
tests/system/config/apm-server.yml.j2
tests/system/test_access.py
tests/system/test_integration.py
tests/system/test_requests.py

It was previously 8080.
This is a follow up on https://github.com/elastic/apm-server/issues/64.

Change default listen port to 8200.

---

processor/error/event.go
processor/error/payload.go
processor/error/payload_test.go
processor/error/processor.go
processor/processor.go
processor/transaction/event.go
processor/transaction/payload.go
processor/transaction/payload_test.go
processor/transaction/processor.go
processor/transaction/trace.go
processor/validator.go

Unexports payload in error and transaction packages.
@ruflin 
Fixes #75

Unexport payload in error and transaction packages

---

docs/page_header.html

Adds prelim doc banner to pages.

[Docs] Add banner for preliminary docs

---

beater/server.go
processor/error/payload.go
processor/transaction/payload.go

The following things are now logged:
* Size of request
* Agent name + version request coming from
* Number of events in one request
* App name

Add debug logging for events received

---

CHANGELOG.asciidoc
beater/server.go

Needs https://github.com/elastic/apm-server/pull/78 to be merged first

Remove debug handler

---

CHANGELOG.asciidoc
_meta/beat.yml
apm-server.reference.yml
apm-server.yml
beater/beater.go
beater/config.go
beater/server.go
beater/server_test.go

Force HTTP server to close if it doesn't shutdown gracefully.

---

beater/server.go

@ruflin 
This minor change keeps the normal code execution at minimum indentation.

Keep normal flow at minimum indentation

---

beater/server.go
tests/system/apmserver.py

Uppercase log

---

Makefile
NOTICE
_beats/dev-tools/packer/platforms/debian/run.sh.j2
_beats/dev-tools/packer/version.yml
_beats/libbeat/_meta/kibana/default/index-pattern/libbeat.json
_beats/libbeat/docs/version.asciidoc
_beats/libbeat/scripts/Makefile
_beats/libbeat/scripts/migrate_beat_config_1_x_to_5_0.py
cmd/root.go
vendor/github.com/elastic/beats/libbeat/cfgfile/reload.go
vendor/github.com/elastic/beats/libbeat/publisher/pipeline/batch.go
vendor/github.com/elastic/beats/libbeat/publisher/pipeline/controller.go
vendor/github.com/elastic/beats/libbeat/publisher/pipeline/monitoring.go
vendor/github.com/elastic/beats/libbeat/publisher/pipeline/output.go
vendor/github.com/elastic/beats/libbeat/publisher/pipeline/pipeline.go
vendor/github.com/elastic/beats/libbeat/publisher/pipeline/retry.go
vendor/github.com/elastic/beats/libbeat/template/field.go
vendor/github.com/elastic/beats/libbeat/template/fields.go
vendor/github.com/elastic/beats/libbeat/template/template.go
vendor/github.com/elastic/beats/libbeat/version/version.go
vendor/vendor.json

This makes the 6.x branch depend on the 6.x beats branch. Currently 6.x is almost identical to master in beats except with some delay.

Update beats in 6.x to 1ee5c98

---

beater/server.go

@ruflin 
Refactored the handler logic to use handler chaining.I did not move the handlers to separate file assuming that's something being discussed in parallel.
Not sure if I should include this change in #128.

Chain handlers

---

docs/spec/app.json
docs/spec/context.json
docs/spec/errors/error.json
docs/spec/errors/payload.json
docs/spec/request.json
docs/spec/stacktrace_frame.json
docs/spec/transactions/payload.json
docs/spec/transactions/trace.json
processor/error/schema.go
processor/transaction/schema.go

Clean up intake API JSON schema indentation

---

NOTICE
_beats/testing/environments/args.yml
vendor/vendor.json

Gets https://github.com/elastic/beats/pull/5142 in to fix CI builds.

Update beats to most recent version

---

README.md

Added sentence on how and when to use user:pass

Remove user auth from curl on default

---

docs/api.asciidoc
docs/elasticsearch-docs.asciidoc
docs/error-api.asciidoc
docs/high-availability.asciidoc
docs/index.asciidoc
docs/index_pattern.asciidoc
docs/security.asciidoc
docs/transaction-api.asciidoc

Initial attempt at documenting central parts of the APM Server.

WIP on docs.

---

docs/security.asciidoc

SSL setup documentation

---

tests/agent/python/Dockerfile
tests/agent/python/Makefile
tests/agent/python/docker-compose.yml
tests/agent/python/flaskapp/app.py
tests/agent/python/flaskapp/requirements.txt
tests/agent/python/requirements.txt

This also adds services for both flask and django test apps to docker-compose

Fix broken opbeans setup

---

docs/guide/apm-getting-started.asciidoc

Updates a few links, improves chunking and structure.

Update links and typos.

---

docs/api.asciidoc
docs/data/index.asciidocs
docs/error-api.asciidoc
docs/fields.asciidoc
docs/generated-docs.asciidoc
docs/guide/apm-getting-started.asciidoc
docs/high-availability.asciidoc
docs/index.asciidoc
docs/index_pattern.asciidoc
docs/overview.asciidoc
docs/security.asciidoc
docs/transaction-api.asciidoc

This is an attempt to improve the current APM Server doc experience. 
Based on additional attributes in https://github.com/elastic/docs/pull/237

Refactor APM Server docs structure and linking.

---

Makefile
NOTICE.txt
_beats/dev-tools/generate_notice.py
_beats/dev-tools/merge_pr
_beats/libbeat/scripts/Makefile
vendor/github.com/elastic/beats/LICENSE.txt
vendor/github.com/elastic/beats/NOTICE.txt
vendor/github.com/elastic/beats/libbeat/cfgfile/reload.go
vendor/github.com/elastic/beats/libbeat/outputs/logstash/async.go
vendor/github.com/elastic/beats/libbeat/outputs/logstash/sync.go
vendor/github.com/elastic/beats/libbeat/outputs/transport/client.go
vendor/vendor.json

* Rename NOTICE to NOTICE.txt
* Rename LICENSE to LICENSE.txt and make it part of the package

Update beats framework in master

---

docs/guide/apm-getting-started.asciidoc

Merge overview and components section in getting started guide

---

docs/guide/index.asciidoc

Add header to example screenshot for Kibana dashboard.

Fix broken security link.

---

beater/beater.go
beater/onboarding_test.go
beater/server.go
beater/server_test.go

SSL warning

---

docs/guide/index.asciidoc

Update download link

---

README.md

Add note for virtualenv requirement to readme.

---

docs/guide/index.asciidoc

This reverts commit 58b4ed9ff3736ba919b6a5552d638b6d30b59cde.
Update link in docs to use permanent link.

Revert "Change docs for automatic loading of dashboards. (#231)"

---

Makefile

`make update-beats` prints the recommended commit msg

---

beater/handlers.go

this was actually suggested in a code review some time ago

minor renaming

---

beater/server.go

Log frontend status at startup

---

NOTICE.txt
_beats/dev-tools/packer/version.yml
vendor/github.com/elastic/beats/libbeat/version/version.go
vendor/vendor.json

Update beats to 347bc3b

---

processor/error/package_tests/processor_test.go
processor/transaction/package_tests/processor_test.go
tests/approvals.go
tests/scripts/approvals.go

Issue found by running go vent.

Fix passing around mutex by value.

---

docs/guide/index.asciidoc
tests/agent/nodejs/express/app.js

This PR is dependent on the release of https://github.com/elastic/apm-agent-nodejs/pull/71 - **Please do not merge until the new version of the Node agent have been released**

Rename Node.js module to elastic-apm-node

---

docs/index_pattern.asciidoc

This replaces PR #313, as it is now branched away from master.

Note about custom index patterns breaking the UI.

---

docs/guide/index.asciidoc
docs/index_pattern.asciidoc
processor/error/package_tests/processor_test.go
processor/transaction/package_tests/processor_test.go
tests/agent/nodejs/express/app.js
tests/approvals.go
tests/scripts/approvals.go
tests/system/apmserver.py
tests/system/test_requests.py

Manually cherry picked:
```
git cherry-pick 036a6b2a7531bcaeaf9086cb519bb13708149a93..1adab32e8adc731021733db4aa09738a463d797b
```
Should be __merged__ not squashed

Backport to 6.x from master

---

_meta/fields.common.yml
_meta/kibana/5.x/dashboard/37f6fac0-7c6a-11e7-aa55-3b0d52c71c60.json
_meta/kibana/5.x/dashboard/3e3de700-7de0-11e7-b115-df9c90da2df1.json
_meta/kibana/5.x/dashboard/41b5d920-7821-11e7-8c47-65b845b5cfb3.json
_meta/kibana/5.x/dashboard/5f08a870-7c6a-11e7-aa55-3b0d52c71c60.json
_meta/kibana/5.x/dashboard/8d3ed660-7828-11e7-8c47-65b845b5cfb3.json
_meta/kibana/5.x/visualization/8d3ed660-7828-11e7-8c47-65b845b5cfb3.json
_meta/kibana/default/dashboard/apm-dashboards.json
processor/error/_meta/fields.yml
processor/transaction/_meta/fields.yml

This PR removes the time range from the URL Templates which fixes #266 so the user's time range will be honored. This PR also removes the stored time range from the dashboards.

Fixes #266 - Remove time from url_templates

---

docs/guide/index.asciidoc
processor/error/package_tests/processor_test.go
processor/transaction/package_tests/processor_test.go
tests/agent/nodejs/express/app.js
tests/approvals.go
tests/scripts/approvals.go
tests/system/apmserver.py
tests/system/test_requests.py

Manual cherry-pick: 
```
git cherry-pick 036a6b2a7531bcaeaf9086cb519bb13708149a93..5e21bf6e0b0297f0011ed25090585c0ba41bbb0a
```
shoud be __merged__ not squashed.

Backport to 6.1 from 6.x

---

CHANGELOG.asciidoc
processor/transaction/_meta/fields.yml

@jalvz , @roncohen this fixes the dashboards for the changes made in #345 .
This fixes #346

Update dashboards to changed transaction.id.

---

Makefile

set systemd doc url

---

NOTICE.txt
_beats/dev-tools/packer/xgo-scripts/before_build.sh
vendor/github.com/elastic/beats/libbeat/common/docker/watcher.go
vendor/github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata/indexers.go
vendor/vendor.json

* includes `make package` fix from elastic/beats#5756

Update beats framework to fca031f

---

CHANGELOG.asciidoc
docs/data/elasticsearch/span.json
docs/fields.asciidoc
processor/transaction/_meta/fields.yml
processor/transaction/package_tests/TestProcessTransactionFull.approved.json
processor/transaction/package_tests/TestProcessTransactionMinimalSpan.approved.json
processor/transaction/package_tests/TestProcessTransactionNullValues.approved.json
processor/transaction/package_tests/json_schema_test.go
processor/transaction/payload_test.go
processor/transaction/span.go
processor/transaction/span_test.go

span event document before (using generated/transaction/payload.json):
```json
{
"_source": {
"beat": {
"hostname": "local",
"name": "local",
"version": "7.0.0-alpha1"
},
"context": {
"app": {
"agent": {
"name": "elastic-node",
"version": "3.14.0"
},
"name": "1234_app-12a3"
}
},
"processor": {
"event": "span",
"name": "transaction"
},
"span": {
"duration": {
"us": 32592
},
"id": 1,
"name": "GET /api/types",
"parent": 0,
"start": {
"us": 0
},
"transaction": {
"id": "945254c5-67a5-417e-8a4e-aa29efcbfb79"
},
"type": "request"
}
}
}
```
after:
```json
{
"_source": {
"beat": {
"hostname": "local",
"name": "local",
"version": "7.0.0-alpha1"
},
"context": {
"app": {
"agent": {
"name": "elastic-node",
"version": "3.14.0"
},
"name": "1234_app-12a3"
}
},
"processor": {
"event": "span",
"name": …
```

move span.transaction.id to root of span

---

CHANGELOG.asciidoc

Added missing items and removed mention of #250 as it never made it into a release.

Updated change log

---

docs/copied-from-beats/version.asciidoc

Increased the version number for the 6.0.1 release.

[DOCS] Updated version to 6.0.1

---

beater/handlers.go

Log useful data at info level for all requests

---

docs/spec/context.json
docs/spec/service.json
docs/spec/stacktrace_frame.json
docs/spec/user.json
processor/error/schema.go
processor/transaction/schema.go

not super detailed, but better than nothing :)

added some more descriptions to the JSON schema

---

_meta/fields.common.yml
docs/fields.asciidoc
docs/spec/context.json
docs/spec/errors/error.json
docs/spec/request.json
docs/spec/service.json
docs/spec/transactions/transaction.json
docs/spec/user.json
processor/error/_meta/fields.yml
processor/error/schema.go
processor/transaction/_meta/fields.yml
processor/transaction/schema.go

Adding descriptions to fields.yml.

---

README.md

I don't feel the alpha blog posts makes much sense any more. I'm not sure if this is the right alternative though. But it's a good start.

Link to Elastic APM solutions page from README.md

---

docs/security.asciidoc

Backport to 6.1

---

CHANGELOG.asciidoc
Makefile
README.md
beater/server.go
cmd/root.go
docs/security.asciidoc
version/version.go

Backport missing commits to 6.x

Backport to 6.x

---

docs/guide/page_header.html
docs/index.asciidoc
docs/page_header.html

- Change alpha to beta  (#415)

[6.x] Change alpha to beta (#415)

---

docs/guide/page_header.html
docs/index.asciidoc
docs/page_header.html

Backports the following commits to 6.1:
- Change alpha to beta  (#415)

[6.1] Change alpha to beta (#415)

---

CHANGELOG.asciidoc
_meta/kibana/5.x/dashboard/5f08a870-7c6a-11e7-aa55-3b0d52c71c60.json
_meta/kibana/5.x/search/ceefd050-7c6a-11e7-aa55-3b0d52c71c60.json
_meta/kibana/default/dashboard/apm-dashboards.json
docs/data/elasticsearch/error.json
docs/data/intake-api/generated/error/null_values.json
docs/data/intake-api/generated/error/payload.json
docs/fields.asciidoc
docs/spec/errors/error.json
processor/error/_meta/fields.yml
processor/error/event.go
processor/error/event_test.go
processor/error/package_tests/TestProcessErrorFull.approved.json
processor/error/schema.go
tests/data/valid/error/null_values.json
tests/data/valid/error/payload.json

rename/reverse boolean exception.uncaught to exception.handled

---

CHANGELOG.asciidoc
_meta/fields.common.yml
docs/data/elasticsearch/error.json
docs/data/elasticsearch/transaction.json
docs/data/intake-api/generated/error/null_values.json
docs/data/intake-api/generated/error/payload.json
docs/data/intake-api/generated/transaction/null_values.json
docs/data/intake-api/generated/transaction/payload.json
docs/fields.asciidoc
docs/spec/request.json
processor/error/package_tests/TestProcessErrorFull.approved.json
processor/error/package_tests/TestProcessErrorNullValues.approved.json
processor/error/schema.go
processor/transaction/package_tests/TestProcessTransactionFull.approved.json
processor/transaction/package_tests/TestProcessTransactionNullValues.approved.json
processor/transaction/schema.go
tests/data/valid/error/null_values.json
tests/data/valid/error/payload.json
tests/data/valid/transaction/null_values.json
tests/data/valid/transaction/payload.json

 add context.request.url.full

---

CHANGELOG.asciidoc
NOTICE.txt
docs/data/elasticsearch/transaction.json
docs/data/intake-api/generated/transaction/payload.json
docs/fields.asciidoc
docs/spec/transactions/mark.json
docs/spec/transactions/transaction.json
processor/transaction/_meta/fields.yml
processor/transaction/event.go
processor/transaction/package_tests/TestProcessTransactionFull.approved.json
processor/transaction/package_tests/json_schema_test.go
processor/transaction/schema.go
tests/data/invalid/transaction/invalid_mark_asterisk.json
tests/data/invalid/transaction/invalid_mark_dot.json
tests/data/invalid/transaction/invalid_mark_group_asterisk.json
tests/data/invalid/transaction/invalid_mark_group_dot.json
tests/data/invalid/transaction/invalid_mark_group_quote.json
tests/data/invalid/transaction/invalid_mark_group_type.json
tests/data/invalid/transaction/invalid_mark_quote.json
tests/data/invalid/transaction/invalid_mark_type.json
tests/data/valid/transaction/payload.json
tests/fields.go
tests/json_schema_test.go

Support user defined groups of marks in the form of  key:value.
Ensure marks are indexed.
closes #423

Support transaction.marks.

---

CHANGELOG.asciidoc

Also moved the two sourcemap related entries next to each other.

Updated changelog with some missing items.

---

beater/handlers.go
utility/handlers.go

[6.x] Streamline logging (#458)

---

_meta/beat.reference.yml
apm-server.reference.yml
beater/beater_test.go
beater/config.go
beater/config_test.go
beater/handlers.go
model/stacktrace_frame.go
model/stacktrace_frame_test.go
processor/error/package_tests/TestProcessErrorFrontendMinified.approved.json
processor/error/package_tests/TestProcessErrorFrontendNoSmap.approved.json
processor/error/package_tests/processor_test.go
processor/processor.go
tests/system/apmserver.py
tests/system/config/apm-server.yml.j2
tests/system/test_integration.py

Detect library_frames for frontend stacktraces.

---

_meta/beat.reference.yml
_meta/beat.yml
apm-server.reference.yml
apm-server.yml

- Minor changes in config descriptions.  (#504)

[6.x] Minor changes in config descriptions. (#504)

---

_meta/kibana/6/dashboard/apm-dashboards.json

- Make dashboards v6 work with changed index name.  (#494)

[6.x] Make dashboards v6 work with changed index name. (#494)

---

sourcemap/elasticsearch.go

This is a tmp fix for Issue#517,
until the encoder in the beats framework is threadsafe.
@graphaelli I looked into how mutex vars are declared in the golang src code as you suggested.

Lock ES clients for sourcemap fetching.

---

sourcemap/elasticsearch.go

* Lock ES clients for sourcemap fetching. (#525)

[6.2] Lock ES clients for sourcemap fetching. (#525)

---

sourcemap/elasticsearch.go

* Lock ES clients for sourcemap fetching. (#525)

[6.x] Lock ES clients for sourcemap fetching. (#525)

---

script/payload-compare.py

clear up new `make check` issue - https://beats-ci.elastic.co/job/elastic+apm-server+master+beats-update/274/console

make autopep8 happy

---

script/payload-compare.py

[6.2] make autopep8 happy (#541)

---

script/payload-compare.py

[6.x] make autopep8 happy (#541)

---

_meta/fields.common.yml
docs/data/elasticsearch/error.json
docs/data/elasticsearch/transaction.json
docs/data/intake-api/generated/error/payload.json
docs/data/intake-api/generated/transaction/payload.json
docs/fields.asciidoc
docs/spec/process.json
model/process.go
processor/error/package_tests/TestProcessErrorFull.approved.json
processor/error/schema.go
processor/transaction/package_tests/TestProcessTransactionFull.approved.json
processor/transaction/schema.go
tests/data/valid/error/payload.json
tests/data/valid/transaction/payload.json

closes #547 
@elastic/apm-agent-devs fyi

Add `process.ppid` as optional field.

---

CHANGELOG.asciidoc
model/stacktrace_frame.go
model/stacktrace_frame_test.go
processor/error/event.go
processor/error/event_test.go
processor/error/package_tests/TestProcessErrorFrontend.approved.json
processor/error/package_tests/TestProcessErrorFrontendMinifiedSmap.approved.json
processor/error/package_tests/TestProcessErrorFrontendNoSmap.approved.json
processor/error/package_tests/processor_test.go

Change error.culprit after successful source mapping.

---

beater/pub.go

This change adds a stopped flag that signals the publisher to stop
accepting events and waits for the event channel to dran all of the
queued events, only then it will close the event channel.
Resolves #534 
Signed-off-by: Marc Lopez <marc5.12@outlook.com>

Fix panic when exitting under load

---

CHANGELOG.asciidoc
Makefile
docs/data/intake-api/generated/sourcemap/bundle.js.map
docs/frontend.asciidoc
docs/generated-docs.asciidoc
docs/index.asciidoc

- Document experimental sourcemap feature.  (#462)

[6.x] Document experimental sourcemap feature. (#462)

---

CHANGELOG.asciidoc
Makefile
docs/data/intake-api/generated/sourcemap/bundle.js.map
docs/frontend.asciidoc
docs/generated-docs.asciidoc
docs/index.asciidoc

- Document experimental sourcemap feature.  (#462)

[6.2] Document experimental sourcemap feature. (#462)

---

LICENSE.txt

- Update License to 2018  (#558)

[6.2] Update License to 2018 (#558)

---

NOTICE.txt
_beats/libbeat/Makefile
_beats/libbeat/_meta/kibana/default/index-pattern/libbeat.json
_beats/libbeat/docs/version.asciidoc
_beats/libbeat/testing/console.go
_beats/libbeat/testing/console_test.go
_beats/libbeat/testing/null.go
_beats/libbeat/testing/testing.go
vendor/vendor.json

Update beats framework to b6fd072

---

docs/version.asciidoc

Update version to 6.1.3 for the release today.

Update version to 6.1.3

---

docs/copied-from-beats/getting-help.asciidoc
docs/index.asciidoc
docs/troubleshooting.asciidoc

This PR ensures that everything in the `copied-from-beats` section is aligned with beats again,
based on changes in beats https://github.com/elastic/beats/pull/6251

Update docs copied from beats to use variables.

---

docs/guide/index.asciidoc

Fix broken links in apm getting started

---

NOTICE.txt
_beats/dev-tools/packer/version.yml
_beats/libbeat/_meta/config.reference.yml
_beats/libbeat/_meta/config.yml
_beats/libbeat/docs/version.asciidoc
vendor/github.com/elastic/beats/libbeat/outputs/logstash/config.go
vendor/github.com/elastic/beats/libbeat/version/version.go
vendor/vendor.json

[6.2] Update beats framework to c19c461

---

_beats/dev-tools/packer/docker/fpm-image/Dockerfile

provide fpm deps (#638)

---

CHANGELOG.asciidoc
_meta/beat.reference.yml
_meta/beat.yml
apm-server.reference.yml
apm-server.yml
beater/beater.go
beater/beater_test.go
beater/config.go
beater/config_test.go
beater/handlers.go
beater/onboarding_test.go
beater/server_test.go
tests/system/apmserver.py
tests/system/config/apm-server.yml.j2
tests/system/test_integration.py

Enhancement separate smap index

---

sourcemap/elasticsearch.go
sourcemap/mapper.go
tests/system/apmserver.py
tests/system/test_integration.py

Log a warning for sourcemap uploads with duplicated caching keys

---

README.md

APM now generally available

---

docs/guide/index.asciidoc

Fixes elastic/apm-agent-nodejs#237

docs: fix missing app -> service renames

---

CHANGELOG.asciidoc
decoder/decoder.go
decoder/decoder_test.go

accept application/json; charset=UTF-8 as contentType in the request

---

CHANGELOG.asciidoc

[6.x] Update changelog

---

NOTICE.txt
_beats/testing/environments/args.yml
vendor/vendor.json

to fix tests relying on snapshot images

Update beats framework to 82a34a9

---

NOTICE.txt
_beats/dev-tools/packer/docker/xgo-image/base/Dockerfile
vendor/vendor.json

to resolve flakey build issues

Update beats framework to ea0a448

---

docs/copied-from-beats/security/basic-auth.asciidoc
docs/copied-from-beats/security/securing-beats.asciidoc
docs/copied-from-beats/security/tls.asciidoc
docs/copied-from-beats/security/user-access.asciidoc
docs/security.asciidoc

* add X-Pack configuration documentation
* expand on TLS configuration
closes #545

x-pack security docs

---

CHANGELOG.asciidoc
_meta/beat.reference.yml
apm-server.reference.yml
beater/beater_test.go
beater/config.go
beater/handlers.go
decoder/decoder.go
decoder/decoder_test.go

Add a config option to opt out from data augmentation

---

CHANGELOG.asciidoc
_meta/beat.reference.yml
apm-server.reference.yml
beater/beater_test.go
beater/config.go
beater/handlers.go
decoder/decoder.go
decoder/decoder_test.go

- Add a config option to opt out from data augmentation, fixes #694 (#701)

[6.x] Add a config option to opt out from data augmentation, fixes #694

---

model/process.go
model/service.go
model/stacktrace_frame.go
model/system.go
processor/error/event.go
processor/error/package_tests/TestProcessErrorNullValues.approved.json
processor/error/payload.go
processor/error/processor.go
processor/processor.go
processor/sourcemap/payload.go
processor/sourcemap/processor.go
processor/transaction/event.go
processor/transaction/event_test.go
processor/transaction/package_tests/TestProcessTransactionNullValues.approved.json
processor/transaction/payload.go
processor/transaction/payload_test.go
processor/transaction/processor.go
processor/transaction/span.go
utility/doc_mapping.go
utility/map_str_enhancer.go
utility/map_str_enhancer_test.go

- Refactor Event creation and enhancer utility method.  (#673)

[6.x] Refactor Event creation and enhancer utility method. (#673)

---

docs/data/elasticsearch/error.json
docs/data/intake-api/generated/error/payload.json
docs/data/intake-api/generated/transaction/payload.json
processor/error/package_tests/TestProcessErrorFull.approved.json
processor/transaction/package_tests/TestProcessTransactionFull.approved.json
tests/data/valid/error/payload.json
tests/data/valid/transaction/payload.json
tests/system/error.approved.json
tests/system/spans.approved.json
tests/system/test_integration.py
tests/system/transaction.approved.json

Verify ES documents for transactions, spans and errors
against gold documents. Approved files need to be adapted
whenever test files are changed.
@roncohen after adding this I can check that PR #687 does not change ES docs.

Add integration test for ES documents.

---

docs/data/elasticsearch/error.json
docs/data/intake-api/generated/error/payload.json
docs/data/intake-api/generated/transaction/payload.json
processor/error/package_tests/TestProcessErrorFull.approved.json
processor/transaction/package_tests/TestProcessTransactionFull.approved.json
tests/data/valid/error/payload.json
tests/data/valid/transaction/payload.json
tests/system/error.approved.json
tests/system/spans.approved.json
tests/system/test_integration.py
tests/system/transaction.approved.json

- Add integration test for ES documents.  (#709)

[6.x] Add integration test for ES documents. (#709)

---

_meta/beat.yml
apm-server.yml
tests/system/apmserver.py
tests/system/config/apm-server.yml.j2
tests/system/test_integration.py

Push transactions and errors to different indices

---

CHANGELOG.asciidoc
beater/config.go
beater/handlers.go

Follow up on #731

---

README.md

[6.x] generally available (#658)

---

_meta/fields.common.yml
docs/fields.asciidoc
utility/ip.go

[6.x] Add security note (#700)

---

_meta/beat.reference.yml
apm-server.reference.yml
docs/copied-from-beats/dashboardsconfig.asciidoc

- Update docs with new dashboard config properties (#741)
- add new config options to the reference file (#741)

[6.x] Update docs with new dashboard config properties

---

_meta/beat.yml
apm-server.yml

- Change index pattern description.  (#765)

[6.x] Change index pattern description. (#765)

---

docs/sourcemaps.asciidoc

Improve source map docs example

---

CHANGELOG.asciidoc
_meta/beat.reference.yml
apm-server.reference.yml
beater/config.go
beater/server.go
beater/server_test.go
vendor/golang.org/x/net/netutil/listen.go
vendor/vendor.json

Introduce a limit to the number of connections to accept simultaneously.
closes #736

limit number of new connections to accept simultaneously

---

Makefile

- update description used in packaging  (#807)

[6.x] update description used in packaging (#807)

---

utility/ip.go
utility/ip_test.go

```
benchmark                                                                                                                                   old ns/op     new ns/op     delta
BenchmarkExtractIP/extractIP_remote:_10.11.12.13:8080,_X-Real-IP:_54.55.101.102,_X-Forwarded-For:_nil-8                                     187           103           -44.92%
BenchmarkExtractIP/extractIP_remote:_10.11.12.13:8080,_X-Real-IP:_54.55.101.102,_X-Forwarded-For:_54.56.103.104-8                           188           108           -42.55%
BenchmarkExtractIP/extractIP_remote:_10.11.12.13:8080,_X-Real-IP:_nil,_X-Forwarded-For:_54.56.103.104-8                                     301           218           -27.57%
BenchmarkExtractIP/extractIP_remote:_10.11.12.13:8080,_X-Real-IP:_nil,_X-Forwarded-For:_54.56. …
```

reduce ExtractIP allocations

---

docs/troubleshooting.asciidoc

Fixes https://github.com/elastic/apm-server/issues/800

Documents how to handle 503s

---

docs/common-problems.asciidoc
docs/troubleshooting.asciidoc

Common problems should be the first part of the trouble shooting section, so people will see it before they start asking questions in discuss etc.

Move common problems up

---

beater/handlers.go

Currently we only log a verbose request info for every incoming request on log level `info`. 
If the log level is set higher than info, this verbose information would be helpful for investigating request errors.
This PR ensures that the verbose information is also logged on log.level >= info if an error occurs handling a request. The additional log information is not added to the already created error log entry, as this would lead to log duplication in case log.level <= info is used. 
closes #793

Log additional request info in error case.

---

beater/handlers.go

- Log additional request info in error case.  (#811)

[6.x] Log additional request info in error case. (#811)

---

Makefile
docs/copied-from-beats/command-reference.asciidoc
docs/copied-from-beats/keystore.asciidoc
docs/copied-from-beats/outputconfig.asciidoc
docs/copied-from-beats/repositories.asciidoc
docs/copied-from-beats/security/basic-auth.asciidoc
docs/copied-from-beats/security/securing-beats.asciidoc
docs/copied-from-beats/security/tls.asciidoc
docs/copied-from-beats/security/user-access.asciidoc
docs/copied-from-beats/shared-directory-layout.asciidoc
docs/copied-from-beats/shared-docker.asciidoc
docs/copied-from-beats/shared-env-vars.asciidoc
docs/copied-from-beats/shared-path-config.asciidoc
docs/copied-from-beats/shared-ssl-config.asciidoc
docs/copied-from-beats/shared-template-load.asciidoc
docs/copied-from-beats/template-config.asciidoc
docs/setting-up-and-running.asciidoc
script/copy-docs.py

- Update docs copied from beats.  (#820)

[6.x] Update docs copied from beats. (#820)

---

tests/system/apmserver.py
tests/system/test_integration.py
tests/system/test_requests.py

Allow other tests to be run from any directory

---

processor/error/payload.go
processor/error/processor.go
processor/sourcemap/processor.go
processor/transaction/payload.go
processor/transaction/processor.go

Add decoding counter and move transformation
counter to transformation.

Update monitoring data to changed handling.

---

processor/error/payload.go
processor/error/processor.go
processor/sourcemap/processor.go
processor/transaction/payload.go
processor/transaction/processor.go

- Update monitoring data to changed handling.  (#852)

[6.x] Update monitoring data to changed handling. (#852)

---

processor/error/payload.go
processor/transaction/payload.go

Collect information about stacktrace and frames
for transactions and errors.

Add metrics for stacktrace.

---

docs/guide/index.asciidoc

- docs/guide: Added docs  (#770)

[6.x] docs/guide: Added docs (#770)

---

CHANGELOG.asciidoc
_meta/beat.reference.yml
_meta/beat.yml
apm-server.reference.yml
apm-server.yml

This reverts commit c9e5053928f4389a036f2b8a99decce35b66eebb.

Revert "reduce in-memory queue defaults (#791) (DO NOT BACKPORT)"

---

beater/server_test.go

do not start the HTTP server twice in tests

---

beater/server_test.go

- do not start the HTTP server twice in tests  (#879)

[6.3] do not start the HTTP server twice in tests (#879)

---

beater/server_test.go

- do not start the HTTP server twice in tests  (#879)

[6.x] do not start the HTTP server twice in tests (#879)

---

beater/handlers.go
decoder/decoder.go
processor/error/processor.go
processor/transaction/processor.go

- Add and align monitoring metrics for APM.  (#901)

[6.x] Add and align monitoring metrics for APM. (#901)

---

beater/handlers.go
decoder/decoder.go
processor/error/processor.go
processor/transaction/processor.go

- Add and align monitoring metrics for APM.  (#901)

[6.3] Add and align monitoring metrics for APM. (#901)

---

beater/beater.go

update configuration processing error message

---

docs/common-problems.asciidoc

Also fix a couple of minor typos.

Put common problems on the same page.

---

docs/common-problems.asciidoc

- Put common problems on the same page.  (#912)

[6.x] Put common problems on the same page. (#912)

---

docs/common-problems.asciidoc

- Put common problems on the same page.  (#912)

[6.3] Put common problems on the same page. (#912)

---

tests/system/config/apm-server.yml.j2

- reduce time waiting for docs under test  (#922)

[6.x] reduce time waiting for docs under test (#922)

---

tests/system/config/apm-server.yml.j2

- reduce time waiting for docs under test  (#922)

[6.3] reduce time waiting for docs under test (#922)

---

.backportrc.json

[6.3] Add backport config (#908)

---

.backportrc.json

[6.x] Add backport config (#908)

---

docs/guide/index.asciidoc

[6.3] small doc changes (#907)

---

docs/guide/index.asciidoc

[6.x] small doc changes (#907)

---

_meta/beat.yml
apm-server.yml

Ensure the order is as expected for creating docker images.

Move output config options.

---

NOTICE.txt
model/stacktrace_frame.go
model/stacktrace_test.go
processor/error/package_tests/TestProcessErrorFrontend.approved.json
processor/error/package_tests/TestProcessErrorFrontendMinifiedSmap.approved.json
sourcemap/mapper.go
sourcemap/mapper_test.go
vendor/github.com/go-sourcemap/sourcemap/README.md
vendor/github.com/go-sourcemap/sourcemap/consumer.go
vendor/github.com/go-sourcemap/sourcemap/internal/base64vlq/base64vlq.go
vendor/github.com/go-sourcemap/sourcemap/mappings.go
vendor/vendor.json

Read sourcemap content and fill context lines

---

beater/handlers.go
beater/handlers_test.go

- clarify root cause for 403 errors, fixes #973  (#974)

[6.x] clarify root cause for 403 errors, fixes #973 (#974)

---

NOTICE.txt
model/stacktrace_frame.go
model/stacktrace_test.go
processor/error/package_tests/TestProcessErrorFrontend.approved.json
processor/error/package_tests/TestProcessErrorFrontendMinifiedSmap.approved.json
sourcemap/mapper.go
sourcemap/mapper_test.go
vendor/github.com/go-sourcemap/sourcemap/README.md
vendor/github.com/go-sourcemap/sourcemap/consumer.go
vendor/github.com/go-sourcemap/sourcemap/internal/base64vlq/base64vlq.go
vendor/github.com/go-sourcemap/sourcemap/mappings.go
vendor/vendor.json

- Read sourcemap content and fill context lines  (#972)

[6.x] Read sourcemap content and fill context lines (#972)

---

beater/handlers.go
beater/handlers_test.go
beater/server_test.go

add telemetry on waiting time for concurrent requests

---

tests/system/apmserver.py

to not abort on 503 errors
fixes #979

override wait_until function with a try/except block

---

tests/system/apmserver.py

- override wait_until function with a try/except block to not abort on 503 errors  (#981)

[6.x] override wait_until function with a try/except block to not abort on 503 errors (#981)

---

docs/common-problems.asciidoc
docs/index.asciidoc

document curator tips useful for APM data

---

processor/error/package_tests/processor_test.go
processor/sourcemap/package_tests/processor_test.go
processor/transaction/package_tests/processor_test.go
tests/json_schema.go
tests/loader/loader.go

removes `Test*ProcessorValidationFailed` duplicate of a test in the respective `*/package_tests/json_schema_test.go`

remove duplicate json schema tests

---

docs/guide/index.asciidoc
docs/overview.asciidoc

- Move section on APM Server to the APM Server docs folder  (#998)

[6.x] Move section on APM Server to the APM Server docs folder (#998)

---

docs/guide/index.asciidoc
docs/overview.asciidoc

- Move section on APM Server to the APM Server docs folder  (#998)

[6.3] Move section on APM Server to the APM Server docs folder (#998)

---

docs/spec/errors/error.json
processor/error/schema.go
tests/data/invalid/error/invalid_transaction_id.json
tests/json_schema_test.go

 remove superfluous max length on error.transaction.id

---

CHANGELOG.asciidoc

Adds a change log entry for #972.

Add change log entry for #972

---

Makefile

required for https://github.com/elastic/apm-server/pull/1010

Vendor beats transptest

---

tests/json_schema.go

To make writing tests a bit easier.

log payload when test fails

---

vendor/github.com/stretchr/testify/require/doc.go
vendor/github.com/stretchr/testify/require/forward_requirements.go
vendor/github.com/stretchr/testify/require/require.go
vendor/github.com/stretchr/testify/require/require.go.tmpl
vendor/github.com/stretchr/testify/require/require_forward.go
vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
vendor/github.com/stretchr/testify/require/requirements.go
vendor/vendor.json

Required for https://github.com/elastic/apm-server/pull/1046

[6.x] Add testify/require dependency

---

CHANGELOG.asciidoc
docs/index.asciidoc
docs/release-notes.asciidoc

Backports the following commits to 6.1:
- Add release notes (#1022)

[6.1] Add release notes

---

CHANGELOG.asciidoc
docs/index.asciidoc
docs/release-notes.asciidoc

[6.2] Add release notes

---

_meta/kibana/6/dashboard/apm-dashboards.json

When releasing the RUM agent for GA we want the dashboards to be adapted accordingly.
This PR implements necessary changes suggested by @jahtalab in Issue elastic/apm-server#540 .

Adapt dashboards for RUM agent.

---

CHANGELOG.asciidoc
docs/index.asciidoc
docs/release-notes.asciidoc

[6.3] Add release notes

---

_beats/dev-tools/jenkins_release.sh

Co-authored-by: watson w@tson.dk

fix common.bash directory for apm-server

---

_meta/beat.yml
apm-server.yml
beater/beater_test.go
beater/config.go
beater/config_test.go
beater/server.go
beater/server_test.go

Co-authored-by: sterchelen <sterchele.nicolas@gmail.com>

incorporate TLS key passphrase support from beats.

---

_meta/kibana/6/dashboard/apm-dashboards.json

* Preserve same order and indentation as in master for future readability of diffs.
* Backport PR#1055

[6.x] Backport dashboard from master.

---

docs/version.asciidoc

Related to the release of 6.3.1

[DOCS] Updates version to 6.3.1

---

CHANGELOG.asciidoc

Also add links for better visualization in docs

Split changelog per patch version

---

docs/common-problems.asciidoc
docs/data_ingestion.asciidoc
docs/index.asciidoc
docs/storage_management.asciidoc

- Refactor docs and add examples on how to delete and update data.  (#1036)

[6.x] Refactor docs and add examples on how to delete and update data. (#1036)

---

docs/common-problems.asciidoc
docs/data_ingestion.asciidoc
docs/index.asciidoc
docs/storage_management.asciidoc

- Refactor docs and add examples on how to delete and update data.  (#1036)

[6.3] Refactor docs and add examples on how to delete and update data. (#1036)

---

_meta/beat.yml
apm-server.yml

Recommend the keystore in the config file, where applicable

---

docs/configuration-process.asciidoc
docs/configuring.asciidoc

Describe missing config options.

---

_meta/beat.yml
apm-server.yml
beater/beater.go
beater/config.go
beater/server_test.go
docs/configuration-process.asciidoc

(to not be confused with distributed tracing, etc)

Rename tracing configuration to instrumentation

---

docs/exploring-es-data.asciidoc
docs/storage-management.asciidoc

Describe how to use Kibana UI Index Management.
implements elastic/apm-server#1126

Docs: Add Kibana Index Management UI description.

---

docs/exploring-es-data.asciidoc
docs/storage-management.asciidoc

- Docs: Add Kibana Index Management UI description.  (#1124)

[6.x] Docs: Add Kibana Index Management UI description. (#1124)

---

docs/exploring-es-data.asciidoc
docs/storage-management.asciidoc

- Docs: Add Kibana Index Management UI description.  (#1124)

[6.3] Docs: Add Kibana Index Management UI description. (#1124)

---

CODE_OF_CONDUCT.md

(found it in the java agent repo, just copied it over)

link to Elastic code of conduct

---

docs/copied-from-beats/security/securing-beats.asciidoc
docs/copied-from-beats/shared-ssl-config.asciidoc

sync minor doc fixes

---

docs/copied-from-beats/security/securing-beats.asciidoc
docs/copied-from-beats/shared-ssl-config.asciidoc

- sync minor doc fixes  (#1144)

[6.x] sync minor doc fixes (#1144)

---

CHANGELOG.asciidoc
_meta/beat.yml
apm-server.yml
beater/beater.go
beater/beater_test.go
beater/config.go
beater/server_test.go
docs/configuration-frontend.asciidoc
docs/configuring-output-after.asciidoc
sourcemap/accessor.go

closes elastic/apm-server#1104

add source_mapping.elasticsearch configuration option

---

docs/guide/index.asciidoc
docs/overview.asciidoc

depends on: https://github.com/elastic/docs/pull/396

add new GA agents to index/overview docs

---

Makefile
_beats/libbeat/tests/system/requirements.txt
script/are_kibana_saved_objects_updated.py

- Check if Kibana files are up-to-date  (#1168)

[6.x] Check if Kibana files are up-to-date (#1168)

---

script/are_kibana_saved_objects_updated.py

- Testing: fix script to check for Kibana objects.  (#1191)

[6.x] Testing: fix script to check for Kibana objects. (#1191)

---

CHANGELOG.asciidoc

- Rotate 6.3 changelog  (#1199)

[6.4] Rotate 6.3 changelog (#1199)

---

CHANGELOG.asciidoc

- Rotate 6.3 changelog  (#1199)

[6.x] Rotate 6.3 changelog (#1199)

---

vendor/github.com/elastic/beats/libbeat/generator/fields/fields.go
vendor/github.com/elastic/beats/libbeat/generator/fields/module_fields_collector.go
vendor/vendor.json

This reverts commit a94029da935a39e55852c83cde036c598e61fa66.

Revert "clean up github.com/elastic/beats/libbeat/generator/fields"

---

script/jenkins/sync.sh

- Add script for jenkins sync test.  (#1209)

[6.4] Add script for jenkins sync test. (#1209)

---

script/jenkins/sync.sh

- Add script for jenkins sync test.  (#1209)

[6.x] Add script for jenkins sync test. (#1209)

---

utility/map_str_enhancer.go

Depends on https://github.com/elastic/apm-server/pull/1222.

Remove unnecessary type assertions in utility.Add

---

utility/map_str_enhancer.go

- Remove unecessary type assertions in utility.Add  (#1224)

[6.x] Remove unecessary type assertions in utility.Add (#1224)

---

CHANGELOG.asciidoc

(due to cherry-pick adding instead of replacing lines)

[6.x] Fix changelog again

---

.backportrc.json

- Update .backportrc.json  (#1232)

[6.x] Update .backportrc.json (#1232)

---

CHANGELOG.asciidoc
beater/handlers.go
beater/handlers_test.go
beater/server_test.go
docs/high-availability.asciidoc
docs/intake-api.asciidoc
docs/server-info.asciidoc

[6.x] Server information (#1197)

---

NOTICE.txt
_beats/vendor/vendor.json
script/jenkins/ci.sh
script/jenkins/intake.sh
script/jenkins/sync.sh
script/jenkins/update-beats.sh
script/update_beats.sh
vendor/github.com/elastic/beats/NOTICE.txt
vendor/github.com/elastic/beats/libbeat/outputs/redis/backoff.go
vendor/github.com/elastic/beats/libbeat/outputs/redis/client.go
vendor/github.com/elastic/beats/libbeat/outputs/redis/config.go
vendor/github.com/elastic/beats/libbeat/outputs/redis/redis.go
vendor/github.com/klauspost/compress/flate/gen.go
vendor/github.com/klauspost/cpuid/private-gen.go
vendor/vendor.json

- Reuse Beats ci scripts  (#1247)

[6.4] Reuse Beats ci scripts (#1247)

---

docs/sourcemap-api.asciidoc

fixes #1268
@jahtalab is this good enough?

clarify that is possible to use a secret token when uploading sourcemaps

---

docs/common-problems.asciidoc

- complete the common problem section with the failure status codes (#1267)

[6.4] complete the common problem section with the failure status codes

---

CHANGELOG.asciidoc
docs/common-problems.asciidoc
docs/data/elasticsearch/span.json
docs/data/intake-api/generated/transaction/payload.json
docs/spec/context.json
docs/spec/tags.json
docs/spec/transactions/span.json
model/error/generated/schema/payload.go
model/transaction/generated/schema/payload.go
processor/transaction/package_tests/TestProcessTransactionFull.approved.json
processor/transaction/package_tests/attrs_common.go
testdata/transaction/payload.json
tests/fields.go
tests/system/spans.approved.json

implements elastic/apm-server#1152 
cc @felixbarny

Allow `tags` on `span.contexts`

---

docs/spec/transactions/span.json

Pretty sure this path needs to be `../tags.json`.

Fix path to tags file in span spec file

---

docs/version.asciidoc

This PR updates the release-state attribute for the 6.4.0 release.

[DOCS] Updates release-state to released

---

docs/dashboards.asciidoc
docs/guide/index.asciidoc

APM Kibana description needs to be updated before this can be merged. 
Needs to be backported to 6.4.

Reference to the Kibana UI.

---

docs/error-api.asciidoc
docs/transaction-api.asciidoc

We need to do a proper round of fixes on the docs for v2. This just gets them passing for now.

Make docs pass

---

NOTICE.txt
beater/beater_test.go
vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go
vendor/github.com/elastic/beats/libbeat/monitoring/report/elasticsearch/elasticsearch.go
vendor/github.com/elastic/beats/libbeat/publisher/pipeline/module.go
vendor/github.com/elastic/beats/libbeat/publisher/queue/memqueue/broker.go
vendor/github.com/elastic/beats/libbeat/publisher/queue/queue.go
vendor/github.com/elastic/beats/libbeat/publisher/queue/spool/module.go
vendor/vendor.json

* includes minor updates for elastic/beats#8091 NewBroker change

Update beats framework to 8c15e6e

---

docs/guide/index.asciidoc

Add APM release notes for 6.4.1

---

docs/guide/index.asciidoc

- docs(node): update Node.js code snippet  (#1344)

[6.4] docs(node): update Node.js code snippet (#1344)

---

docs/sourcemap-api.asciidoc

include secret token in sourcemap upload example

---

model/error/event_test.go

Cleanup after https://github.com/elastic/apm-server/pull/1354

Remove debug output.

---

changelogs/6.4.asciidoc

add 6.4.1 changelog

---

beater/common_handlers.go
beater/v2_handler.go
beater/v2_handler_test.go
processor/stream/result.go
processor/stream/result_test.go
processor/stream/stream_processor.go
processor/stream/stream_processor_test.go

implements elastic/apm-server#1355

[v2] Increase metrics counter in v2 responses.

---

docs/copied-from-beats/outputconfig.asciidoc

implements elastic/apm-server#1372 
related to https://github.com/elastic/beats/pull/8369

[docs] Note for changing index, adapt dashboard desc.

---

changelogs/6.4.asciidoc

add 6.4.2 changelog

---

beater/common_handlers.go
beater/v2_handler.go

following up on https://github.com/elastic/apm-server/pull/1430#discussion_r225071276

consolidate internal error counters

---

rally/.gitignore
rally/README.md
rally/_tools/fetch_data.py
rally/_tools/prepare.py
rally/_tools/requirements.txt
rally/challenges/default.json
rally/operations/default.json
rally/track.json

Add support for indexing events into daily indices to allow running APM queries on them.
implements elastic/apm-server#1404
cc @danielmitterdorfer

Support daily indices for queries in rally.

---

beater/common_handlers.go
beater/route_config.go
tests/system/apmserver.py
tests/system/test_requests.py

Happy to change the warning to every request if anyone thinks is better

Add a deprecation warning on a first request to V1

---

_meta/beat.yml
apm-server.yml
cmd/root.go
tests/system/test_integration.py

note that `export template` doesn't respect these settings, yet

set default total_fields limit in code

---

_meta/beat.yml
apm-server.yml
cmd/root.go
tests/system/test_integration.py

- set default total_fields limit in code  (#1461)

[6.x] set default total_fields limit in code (#1461)

---

_meta/beat.yml
apm-server.yml
changelogs/6.5.asciidoc
cmd/root.go
tests/system/apmserver.py
tests/system/test_export.py

- set more config defaults in code  (#1494)

[6.5] set more config defaults in code (#1494)

---

docs/spec/metricsets/common_metricset.json
docs/spec/spans/v1_span.json
model/metricset/generated/schema/metricset.go
model/metricset/generated/schema/payload.go
model/transaction/generated/schema/payload.go

started as a tyoo fix for `od`, ended with some rewording too.

clean up some descriptions

---

docs/spec/metricsets/common_metricset.json
docs/spec/spans/v1_span.json
model/metricset/generated/schema/metricset.go
model/metricset/generated/schema/payload.go
model/transaction/generated/schema/payload.go

- clean up some descriptions  (#1508)

[6.5] clean up some descriptions (#1508)

---

beater/route_config.go
beater/v2_handler.go
decoder/line_reader.go
decoder/line_reader_test.go
decoder/stream_decoder.go
decoder/stream_decoder_test.go
processor/stream/benchmark_test.go
processor/stream/package_tests/error_attrs_test.go
processor/stream/package_tests/metadata_attrs_test.go
processor/stream/package_tests/metricset_attrs_test.go
processor/stream/package_tests/span_attrs_test.go
processor/stream/package_tests/transaction_attrs_test.go
processor/stream/package_tests/v2_test_processor.go
processor/stream/stream_processor.go
processor/stream/stream_processor_test.go

- v2: minor refactor of stream handling  (#1473)

[6.x] v2: minor refactor of stream handling (#1473)

---

processor/stream/stream_processor.go

Following up on roncohen/apm-server#4 here are fresh benchmarks:
**ns/op:**
```
benchmark                                                                 old ns/op     new ns/op     delta
BenchmarkStreamProcessor/errors.ndjson/NoRateLimit-4                      244409        170019        -30.44%
BenchmarkStreamProcessor/errors.ndjson/WithRateLimit-4                    264594        201918        -23.69%
BenchmarkStreamProcessor/events.ndjson/NoRateLimit-4                      132161        71012         -46.27%
BenchmarkStreamProcessor/events.ndjson/WithRateLimit-4                    163831        87221         -46.76%
BenchmarkStreamProcessor/heavy.ndjson/NoRateLimit-4                       24840950      21281166      -14.33%
BenchmarkStreamProcessor/heavy.ndjson/WithRateLimit-4 …
```

stream: reuse buffers

---

beater/route_config.go
beater/v2_handler.go
decoder/line_reader.go
decoder/line_reader_test.go
decoder/stream_decoder.go
decoder/stream_decoder_test.go
processor/stream/benchmark_test.go
processor/stream/package_tests/error_attrs_test.go
processor/stream/package_tests/metadata_attrs_test.go
processor/stream/package_tests/metricset_attrs_test.go
processor/stream/package_tests/span_attrs_test.go
processor/stream/package_tests/transaction_attrs_test.go
processor/stream/package_tests/v2_test_processor.go
processor/stream/stream_processor.go
processor/stream/stream_processor_test.go

- v2: minor refactor of stream handling  (#1473)

[6.5] v2: minor refactor of stream handling (#1473)

---

processor/stream/stream_processor.go

- stream: reuse buffers  (#1505)

[6.5] stream: reuse buffers (#1505)

---

_meta/beat.yml
apm-server.yml
changelogs/head.asciidoc
cmd/root.go
tests/system/apmserver.py
tests/system/test_export.py

- set more config defaults in code  (#1494)

[6.x] set more config defaults in code (#1494)

---

docs/spec/metricsets/common_metricset.json
docs/spec/spans/v1_span.json
model/metricset/generated/schema/metricset.go
model/metricset/generated/schema/payload.go
model/transaction/generated/schema/payload.go

- clean up some descriptions  (#1508)

[6.x] clean up some descriptions (#1508)

---

beater/common_handlers.go
beater/v2_handler.go

small refactor to simplify response handling

beater: slightly simplify response handling

---

docs/guide/index.asciidoc

To be used for explaining the feature via the APM UI Traces overview.

[DOCS] Adding section about Distributed tracing

---

docs/guide/index.asciidoc

- [DOCS] Adding section about Distributed tracing (#1526)

[6.x] [DOCS] Adding section about Distributed tracing

---

docs/guide/index.asciidoc

- [DOCS] Adding section about Distributed tracing (#1526)

[6.5] [DOCS] Adding section about Distributed tracing

---

publish/pub.go

Use channel instead of mutex and bool.

Update handling when server is stopped.

---

publish/pub.go

This reverts commit b430e4c9ff4e833b95d428798fb4f8a7bebb3f88.
based on https://github.com/elastic/apm-server/pull/1535#pullrequestreview-174092119

Revert "Update handling when server is stopped. (#1535)"

---

docs/version.asciidoc

This PR updates the release-state attribute for the APM Server Reference.

[DOCS] Updates release-state

---

docs/guide/apm-release-notes.asciidoc

update release notes for 6.5

---

docs/guide/apm-release-notes.asciidoc

- update release notes for 6.5  (#1555)

[6.x] update release notes for 6.5 (#1555)

---

docs/guide/apm-release-notes.asciidoc

- update release notes for 6.5  (#1555)

[6.5] update release notes for 6.5 (#1555)

---

NOTICE.txt
_beats/dev-tools/jenkins_release.sh
_beats/libbeat/docs/version.asciidoc
vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go
vendor/github.com/elastic/beats/libbeat/common/cfgwarn/removed.go
vendor/github.com/elastic/beats/libbeat/common/file/rotator.go
vendor/github.com/elastic/beats/libbeat/common/file/stderr_other.go
vendor/github.com/elastic/beats/libbeat/common/file/stderr_windows.go
vendor/github.com/elastic/beats/libbeat/logp/config.go
vendor/github.com/elastic/beats/libbeat/logp/core.go
vendor/github.com/elastic/beats/libbeat/outputs/output_reg.go
vendor/vendor.json

* removes the default version qualifier

Update beats framework to 122fb93

---

changelogs/6.5.asciidoc

[6.5] update changelog for 6.5.1 

---

docs/common-problems.asciidoc

Added timeout issue (#1585) to `common-problems.asciidoc`

Docs: add timeout issue to common-problems

---

processor/stream/stream_processor.go

- stream: reuse buffers (#1505)

[6.x] stream: reuse buffers (#1505)

---

tests/fields.go
tests/fields_test.go
tests/json_schema.go
tests/set.go

extracted from some work destined for only the 6.x branches.

test: increase field load filter flexibility

---

script/are_kibana_saved_objects_updated.py

Per https://github.com/elastic/kibana/pull/26412

test: update kibana visualization paths

---

docs/common-problems.asciidoc
docs/configuration-rum.asciidoc
docs/data-ingestion.asciidoc
docs/upgrading-to-65.asciidoc

- docs:  tuning and config updates  (#1576)

[6.x] docs:  tuning and config updates (#1576)

---

docs/common-problems.asciidoc
docs/configuration-rum.asciidoc
docs/data-ingestion.asciidoc
docs/upgrading-to-65.asciidoc

- docs:  tuning and config updates  (#1576)

[6.5] docs:  tuning and config updates (#1576)

---

script/are_kibana_saved_objects_updated.py

[6.x] test: update kibana visualization paths (#1613)

---

docs/common-problems.asciidoc
docs/guide/install-and-run.asciidoc
docs/guide/overview.asciidoc

Backports docs PRs:
* Docs: add timeout issue to `common-problems` (#1586)
* Docs: clarify APM setup instructions (#1628)
* Docs: add section on APM Concepts (#1604)

[6.5] Docs: Backport to 6.5

---

_beats/testing/environments/snapshot.yml
sourcemap/elasticsearch.go
tests/system/apmserver.py
tests/system/test_integration.py

While retaining compatibility with 6.x.

Test against latest elasticsearch 7.0.0 snapshot

---

beater/client.go
beater/common_handlers.go
beater/route_config.go
beater/server.go
changelogs/6.5.asciidoc
tests/docker-compose.yml
tests/system/test_requests.py

- avoid/fix deprecation warnings  (#1703)

[6.5] avoid/fix deprecation warnings (#1703)

---

NOTICE.txt
docs/configuring-ingest.asciidoc

- tweak ingest pipeline docs  (#1719)

[6.x] tweak ingest pipeline docs (#1719)

---

docs/configuring-ingest.asciidoc

- tweak ingest pipeline docs  (#1719)

[6.6] tweak ingest pipeline docs (#1719)

---

NOTICE.txt
docs/configuring-ingest.asciidoc

- tweak ingest pipeline docs  (#1719)

[6.5] tweak ingest pipeline docs (#1719)

---

NOTICE.txt
changelogs/head.asciidoc
vendor/go.elastic.co/apm/CHANGELOG.md
vendor/go.elastic.co/apm/Jenkinsfile
vendor/go.elastic.co/apm/tracer.go
vendor/go.elastic.co/apm/version.go
vendor/vendor.json

Upgrade Elastic APM Go Agent to v1.1.2

---

docs/installing.asciidoc
docs/overview.asciidoc

Quick little update to the APM Overview & Installing documentation.
* Matches wording in agent overviews and links to APM Overview
* Minor grammar and formatting fixes

Docs: improve server overview

---

beater/beater.go

As per https://github.com/elastic/apm-agent-go/issues/412#issuecomment-452162669
Thanks @axw !

close default tracer

---

docs/installing.asciidoc
docs/overview.asciidoc

* Docs: improve server overview (#1729)

[6.6] Docs: improve server overview (#1729)

---

docs/installing.asciidoc
docs/overview.asciidoc

* Docs: improve server overview (elastic#1729)

[6.5] Docs: improve server overview (#1729)

---

docs/installing.asciidoc
docs/overview.asciidoc

* Docs: improve server overview (#1729)

[6.x] Docs: improve server overview (#1729)

---

Makefile

will try to also get this changed in libbeat, but until then, here we go.

set default goal now that plain make does not do anything interesting

---

NOTICE.txt
_beats/dev-tools/packaging/packages.yml
_beats/vendor/vendor.json
vendor/github.com/elastic/beats/NOTICE.txt
vendor/github.com/elastic/beats/dev-tools/mage/kibana.go
vendor/github.com/elastic/beats/dev-tools/mage/pkgtypes.go
vendor/github.com/elastic/beats/libbeat/template/processor.go
vendor/github.com/elastic/go-sysinfo/providers/darwin/host_darwin_amd64.go
vendor/github.com/elastic/go-sysinfo/providers/darwin/machineid_darwin_amd64.go
vendor/github.com/elastic/go-sysinfo/providers/darwin/process_darwin_amd64.go
vendor/github.com/elastic/go-sysinfo/providers/linux/process_linux.go
vendor/github.com/elastic/go-sysinfo/providers/windows/arch_windows.go
vendor/github.com/elastic/go-sysinfo/providers/windows/boottime_windows.go
vendor/github.com/elastic/go-sysinfo/providers/windows/host_windows.go
vendor/github.com/elastic/go-sysinfo/providers/windows/kernel_windows.go
vendor/github.com/elastic/go-sysinfo/providers/windows/os_windows.go
vendor/github.com/elastic/go-sysinfo/providers/windows/process_windows.go
vendor/github.com/elastic/go-sysinfo/types/process.go
vendor/vendor.json

includes fix for https://github.com/elastic/beats/issues/9989

[6.6] Update beats framework to 31f7594

---

beater/integration_test.go

namely, for the onboarding document to be published first
fixes #1767

do not rely on event ordering

---

Jenkinsfile

When we are updating the beats framework it is convenient to run the Release stage.

[APM-CI] run release stage on beats frameworks changes

---

NOTICE.txt
_beats/dev-tools/ecs-migration.yml
_beats/vendor/vendor.json
vendor/github.com/elastic/beats/NOTICE.txt
vendor/github.com/elastic/beats/libbeat/asset/registry.go
vendor/github.com/elastic/beats/libbeat/common/version.go
vendor/github.com/elastic/beats/libbeat/metric/system/host/host.go
vendor/github.com/elastic/beats/libbeat/processors/add_host_metadata/add_host_metadata.go
vendor/github.com/elastic/beats/libbeat/processors/add_host_metadata/config.go
vendor/github.com/elastic/beats/libbeat/template/processor.go
vendor/vendor.json

includes fix for https://github.com/elastic/beats/issues/9989

Update beats framework to a5d11aa

---

beater/server_test.go

eg: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/PR-1756/8/pipeline/143

Skip flaky test

---

apm-server.docker.yml

sync bundled docker config

---

_meta/ecs-migration.yml
beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
docs/data/elasticsearch/generated/spans.json
model/span/event.go
model/span/event_test.go
processor/stream/package_tests/span_attrs_test.go
processor/stream/test_approved_es_documents/testIntakeIntegrationRumTransactions.approved.json
processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
tests/system/spans.approved.json

Move context.db and context.http to span

---

Jenkinsfile
script/jenkins/bench.sh
script/jenkins/build.sh
script/jenkins/linux-test.sh
script/jenkins/unit-test.sh
script/jenkins/windows-build.ps1
script/jenkins/windows-test.ps1

It copies the pipeline related files from the master branch

 [APM-CI] Enable pipeline on branch 6.3

---

_meta/ecs-migration.yml
beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
docs/data/elasticsearch/generated/errors.json
docs/data/elasticsearch/generated/transactions.json
model/error/event.go
model/error/event_test.go
model/transaction/event.go
model/transaction/event_test.go
processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
tests/fields.go
tests/system/error.approved.json
tests/system/transaction.approved.json

Move context.custom to event.custom.

---

docs/guide/agent-server-compatibility.asciidoc

Updates the server/agent compatibility matrix with new RUM version released today. All other agent updates are OK. @vigneshshanmugam or @jahtalab - can either of you confirm that the change below is correct?
Also, I alphabetized the list, because why not?

[docs] Update RUM compatibility

---

docs/copied-from-beats/outputconfig.asciidoc
docs/copied-from-beats/shared-ssl-config.asciidoc
docs/copied-from-beats/template-config.asciidoc

https://github.com/elastic/beats/pull/10416 & https://github.com/elastic/beats/pull/10187 have been merged. This PR runs `make update-beats-docs`. A few minor formatting changes as expected. Just need one of you to look over the changes in `shared-ssl-config.asciidoc` and confirm whether those are OK for us or not.

[docs] Update documentation from beats

---

docs/metadata-api.asciidoc

Adds docs for elastic/apm/pull/26 (see also elastic/apm/pull/21 & elastic/apm/pull/22)

Docs: add kubernetes metadata

---

changelogs/6.6.asciidoc

Fix changelog for 6.6

---

docs/guide/apm-doc-directory.asciidoc
docs/guide/install-and-run.asciidoc
docs/metadata-api.asciidoc

Cherry picks a commit from 6.6 (#1868) with documentation feedback from @jalvz

[docs] Grammar fixes

---

CHANGELOG.asciidoc
changelogs/6.6.asciidoc
changelogs/6.7.asciidoc
docs/release-notes.asciidoc

Create changelog for 6.7

---

model/error/event.go
processor/error/package_tests/TestProcessErrorFull.approved.json
processor/error/package_tests/TestProcessErrorMinimalPayloadException.approved.json
processor/error/package_tests/TestProcessErrorMinimalPayloadLog.approved.json
processor/error/package_tests/TestProcessErrorMinimalProcess.approved.json
processor/error/package_tests/TestProcessErrorRum.approved.json
processor/error/package_tests/processor_test.go
processor/transaction/package_tests/TestProcessTransactionAugmented.approved.json
processor/transaction/package_tests/TestProcessTransactionAugmentedMerge.approved.json
processor/transaction/package_tests/TestProcessTransactionFull.approved.json
processor/transaction/package_tests/TestProcessTransactionMinimalPayload.approved.json
processor/transaction/package_tests/TestProcessTransactionMinimalProcess.approved.json
processor/transaction/package_tests/TestProcessTransactionRum.approved.json
processor/transaction/package_tests/processor_test.go
testdata/error/minimal_process.json
testdata/error/payload.json
testdata/error/rum.json
testdata/transaction/minimal_process.json
testdata/transaction/payload.json
tests/system/error.approved.json
tests/system/spans.approved.json
tests/system/test_integration.py
tests/system/transaction.approved.json

Ensure error.@timestamp is set in apm-server

---

model/error/event.go
processor/error/package_tests/TestProcessErrorFull.approved.json
processor/error/package_tests/TestProcessErrorMinimalPayloadException.approved.json
processor/error/package_tests/TestProcessErrorMinimalPayloadLog.approved.json
processor/error/package_tests/TestProcessErrorMinimalProcess.approved.json
processor/error/package_tests/TestProcessErrorRum.approved.json
processor/error/package_tests/processor_test.go
processor/transaction/package_tests/TestProcessTransactionAugmented.approved.json
processor/transaction/package_tests/TestProcessTransactionAugmentedMerge.approved.json
processor/transaction/package_tests/TestProcessTransactionFull.approved.json
processor/transaction/package_tests/TestProcessTransactionMinimalPayload.approved.json
processor/transaction/package_tests/TestProcessTransactionMinimalProcess.approved.json
processor/transaction/package_tests/TestProcessTransactionRum.approved.json
processor/transaction/package_tests/processor_test.go
testdata/error/minimal_process.json
testdata/error/payload.json
testdata/error/rum.json
testdata/transaction/minimal_process.json
testdata/transaction/payload.json
tests/system/error.approved.json
tests/system/spans.approved.json
tests/system/test_integration.py
tests/system/transaction.approved.json

* Ensure error.@timestamp is set in apm-server
fixes #1911

Ensure error.@timestamp is set in apm-server (#1912)

---

beater/beater.go

Fix test panic on tracer.Close

---

NOTICE.txt
_beats/libbeat/docs/version.asciidoc
_beats/script/build_docs.sh
vendor/github.com/elastic/beats/libbeat/autodiscover/providers/kubernetes/kubernetes.go
vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go
vendor/github.com/elastic/beats/libbeat/cmd/test/filebeat_test.yml
vendor/github.com/elastic/beats/libbeat/dashboards/dashboards.go
vendor/github.com/elastic/beats/libbeat/kibana/index_pattern_generator.go
vendor/vendor.json

This PR should fix CI again as Kibana Index Pattern is now generated with a string.

[7.0] Update beats framework to 457aaef

---

Makefile
script/are_kibana_saved_objects_updated.py

- index pattern sync check symmetry  (#1920)

[7.x] index pattern sync check symmetry (#1920)

---

changelogs/7.0.asciidoc
changelogs/head.asciidoc
docs/guide/apm-release-notes.asciidoc
docs/version.asciidoc

We need to update [APM release notes](https://www.elastic.co/guide/en/apm/get-started/7.0/apm-release-notes.html) for the beta-1 release.
@elastic/apm-ui @elastic/apm-agent-devs please let me know what we should add for your sections. 
We should get this out asap.

Update changelog and release state.

---

changelogs/7.0.asciidoc
changelogs/head.asciidoc
docs/guide/apm-release-notes.asciidoc
docs/version.asciidoc

Update changelog and release state. (#1932)

---

Makefile
script/are_kibana_saved_objects_updated.py

- index pattern sync check symmetry  (#1920)

[7.0] index pattern sync check symmetry (#1920)

---

changelogs/6.5.asciidoc
changelogs/6.6.asciidoc

Anything of note to add to these?
(also uncomment 6.5.4 release notes)

[docs] Add 6.6.1 release notes

---

docs/copied-from-beats/security/user-access.asciidoc
docs/index.asciidoc

This will likely change over the next few days as the kinks get worked out in the beats PR: https://github.com/elastic/beats/pull/10683
Closes elastic/apm-server#1874

[docs] Add apm_user role

---

Makefile
apm-server.docker.yml

closes elastic/apm-server#1553

generate apm-server.docker.yml

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml
beater/config.go

Make Ingest pipeline path explicit

---

NOTICE.txt
_beats/libbeat/scripts/unpack_dashboards.py
vendor/github.com/elastic/beats/libbeat/autodiscover/providers/docker/config.go
vendor/github.com/elastic/beats/libbeat/autodiscover/providers/docker/docker.go
vendor/github.com/elastic/beats/libbeat/outputs/kafka/config.go
vendor/github.com/elastic/beats/libbeat/outputs/kafka/kafka.go
vendor/github.com/elastic/beats/libbeat/outputs/logstash/config.go
vendor/github.com/elastic/beats/libbeat/outputs/logstash/logstash.go
vendor/vendor.json

Fix default index for logstash and kafka |  Update beats framework to d7a5a79

---

_meta/kibana/6/dashboard/apm-dashboards.json

Related to https://github.com/elastic/kibana/pull/30036

Update versions to strings in dashboards.

---

NOTICE.txt
_beats/libbeat/docs/version.asciidoc
_beats/libbeat/scripts/Makefile
_beats/script/build_docs.sh
_beats/testing/environments/args.yml
_beats/vendor/vendor.json
vendor/github.com/elastic/beats/NOTICE.txt
vendor/github.com/elastic/beats/dev-tools/mage/settings.go
vendor/github.com/elastic/beats/libbeat/autodiscover/providers/kubernetes/kubernetes.go
vendor/github.com/elastic/beats/libbeat/common/field.go
vendor/github.com/elastic/beats/libbeat/template/template.go
vendor/vendor.json

Update beats framework to 9d5f9a9

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml

Since the configuration yml is not automatically updated on beats updates (as we differ in some sections), I manually compared and updated the config files, especially the default values.

Update config yml to reflect proper default vals.

---

beater/integration_test.go
beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
docs/spec/metadata.json
model/metadata/generated/schema/metadata.go
testdata/intake-v2/minimal.ndjson

- Specify minimal events on Intake API and ES level.  (#1941)

[7.0] Specify minimal events on Intake API and ES level. (#1941)

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml

- Update config yml to reflect proper default vals.  (#1942)

[7.0] Update config yml to reflect proper default vals. (#1942)

---

changelogs/6.6.asciidoc

Anything of note to add to these?

[docs] Add 6.6.2 release notes

---

docs/common-problems.asciidoc

note auto index creation troubleshooting

---

docs/copied-from-beats/outputconfig.asciidoc

Implements https://github.com/elastic/beats/pull/11300

[docs] Update index prefix in output config

---

changelogs/6.6.asciidoc

Cherrypicks to master:
* docs: add 6.6.2 release notes (#1991)

[docs] add 6.6.2 release notes (#1991)

---

_beats/libbeat/tests/system/beat/beat.py
beater/beater.go
beater/beater_test.go
beater/config.go
tests/system/test_setup.py

- enable pipeline registration for setup --pipelines  (#2010)

[7.0] enable pipeline registration for setup --pipelines (#2010)

---

Jenkinsfile

Run the package stage in more files updates

[APM-CI] Run package stage on new conditions

---

NOTICE.txt
_beats/libbeat/scripts/generate_fields_docs.py
docs/fields.asciidoc
vendor/github.com/elastic/beats/libbeat/template/template.go
vendor/vendor.json

[6.7] Update beats framework to 8844f10

---

changelogs/6.5.asciidoc

remove unused 6.5.5 notes

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml
package-README.md.tmpl

[7.0] Doc clarifications (#2032)

---

changelogs/7.0.asciidoc
docs/version.asciidoc

Cleaning up `7.0.0-rc1` release notes

[docs] 7.0.0-rc1 release notes

---

apm-server.docker.yml

I have so far been unable to determine why `make check-full` only caught problems with this on some runs.

sync apm-server.docker.yml

---

NOTICE.txt
_beats/libbeat/autodiscover/providers/README
_beats/libbeat/processors/script/processor.go
_beats/libbeat/tests/system/beat/beat.py
_beats/vendor/vendor.json
apm-server.docker.yml
script/update_beats.sh
vendor/github.com/elastic/beats/NOTICE.txt
vendor/github.com/elastic/beats/libbeat/cfgfile/reload.go
vendor/github.com/elastic/beats/libbeat/generator/fields/fields.go
vendor/github.com/elastic/beats/libbeat/generator/fields/module_fields_collector.go
vendor/github.com/elastic/beats/libbeat/outputs/transport/client.go
vendor/github.com/elastic/beats/libbeat/processors/actions/decode_json_fields.go
vendor/github.com/elastic/beats/libbeat/template/load.go
vendor/github.com/elastic/beats/libbeat/template/processor.go
vendor/github.com/elastic/beats/x-pack/libbeat/management/api/auth_client.go
vendor/github.com/elastic/beats/x-pack/libbeat/management/api/client.go
vendor/github.com/elastic/beats/x-pack/libbeat/management/api/configuration.go
vendor/github.com/elastic/beats/x-pack/libbeat/management/api/doc.go
vendor/github.com/elastic/beats/x-pack/libbeat/management/api/enroll.go
vendor/github.com/elastic/beats/x-pack/libbeat/management/api/event_reporter.go
vendor/github.com/elastic/beats/x-pack/libbeat/management/api/response.go
vendor/github.com/elastic/beats/x-pack/libbeat/management/enroll.go
vendor/github.com/elastic/go-sysinfo/providers/linux/container.go
vendor/github.com/elastic/go-sysinfo/providers/linux/machineid.go
vendor/github.com/elastic/go-sysinfo/providers/linux/os.go
vendor/vendor.json

* ignores newly provided fields from autodiscover providers
* updates missed sync of `apm-server.docker.yml`

Update beats framework to 96e059d

---

beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
docs/data/elasticsearch/generated/errors.json
docs/data/elasticsearch/generated/transactions.json
model/metadata/system.go
model/metadata/system_test.go
processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
tests/system/error.approved.json
tests/system/transaction.approved.json

Align host.hostname with ECS under kubernetes

---

docs/configuring-ingest.asciidoc

Closes https://github.com/elastic/apm-server/issues/2021.
Also took this opportunity to clean up/rewrite the ingest node documentation.

[docs] Update ingest node documentation

---

changelogs/7.0.asciidoc
changelogs/head.asciidoc
docs/version.asciidoc

cherry picks `7.0.0-rc1` and `7.0.0-rc2` release notes to master

[docs] Cherry pick release notes

---

docs/configuring-ingest.asciidoc
docs/copied-from-beats/command-reference.asciidoc
docs/copied-from-beats/https.asciidoc
docs/copied-from-beats/outputconfig.asciidoc
docs/copied-from-beats/security/linux-seccomp.asciidoc
docs/copied-from-beats/security/securing-beats.asciidoc
docs/copied-from-beats/shared-configuring.asciidoc
docs/copied-from-beats/shared-ssl-logstash-config.asciidoc
docs/copied-from-beats/shared-template-load.asciidoc
docs/copied-from-beats/step-test-config.asciidoc
docs/copied-from-beats/template-config.asciidoc
docs/index.asciidoc
docs/setting-up-and-running.asciidoc
docs/upgrading-to-70.asciidoc
docs/upgrading.asciidoc

This PR backports the following commits to 7.0:
* [docs] Add 7.0 upgrading guide with deb/RPM instructions (#2054)
* [docs] Remove old attributes (#2053)
* [docs] Update ingest node documentation (#2061)

[docs][7.0] Backport documentation

---

docs/guide/apm-breaking-changes.asciidoc

Backports https://github.com/elastic/apm-server/pull/2076

[DOCS] Adds tagged region for notable breaking changes

---

NOTICE.txt
_beats/libbeat/docs/version.asciidoc
_beats/libbeat/scripts/Makefile
_beats/testing/environments/args.yml
_beats/testing/environments/snapshot.yml
vendor/github.com/elastic/beats/dev-tools/mage/pytest.go
vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go
vendor/vendor.json

* fixes keystore path loading issues

[6.7] Update beats framework to 78c68fe

---

docs/configuration-rum.asciidoc
docs/guide/agent-server-compatibility.asciidoc
docs/guide/distributed-tracing.asciidoc
docs/rum.asciidoc
docs/sourcemap-api.asciidoc

* Implements the APM Server portion of elastic/apm-server#2087 (fix links, adds note about enabling RUM)
* Fixes distributed tracing badge and removes help links
@jahtalab / @vigneshshanmugam can you confirm the RUM portion of this PR looks good to you?

[docs] Update RUM and DT documentation

---

docs/guide/apm-release-notes.asciidoc

[docs] Add known issue to highlights

---

changelogs/7.0.asciidoc
docs/copied-from-beats/shared-systemd.asciidoc
docs/installing.asciidoc
docs/setting-up-and-running.asciidoc

add systemd docs

---

_beats/dev-tools/packaging/templates/linux/systemd.unit.tmpl
changelogs/head.asciidoc

fixes #2096 
upstream fix in: elastic/beats#11789

set user/group under systemd

---

docs/breaking-changes.asciidoc

related: https://github.com/elastic/beats/pull/11674

[docs] Fix breaking change link

---

docs/breaking-changes.asciidoc

related: https://github.com/elastic/beats/pull/11674

[docs][7.0] fix breaking change link

---

changelogs/head.asciidoc
docs/spec/stacktrace_frame.json
model/error/event.go
model/error/event_test.go
model/error/generated/schema/error.go
model/span/event_test.go
model/span/generated/schema/span.go
model/stacktrace_frame.go
model/stacktrace_frame_test.go
model/stacktrace_test.go
processor/stream/package_tests/error_attrs_test.go
processor/stream/package_tests/span_attrs_test.go

fixes https://github.com/elastic/apm-server/issues/1584

make stacktrace lineno optional

---

docs/upgrading.asciidoc

Can one of you take a look when you have a sec. This is to fix the doc build.

[docs][6.5] fix breaking changes links

---

docs/upgrading.asciidoc

Can one of you take a look when you have a sec. This is to fix the doc build.

[docs][6.4] fix breaking changes links

---

docs/context.asciidoc
docs/guide/apm-data-model.asciidoc
docs/guide/redirects.asciidoc

Closes https://github.com/elastic/apm-server/issues/2111.

[docs] Add labels context and user info

---

docs/context.asciidoc
docs/guide/apm-data-model.asciidoc
docs/guide/redirects.asciidoc

Backports #2129 to `current` (7.0) so links from agent repos will work

[docs] Add labels context and user info (#2129)

---

NOTICE.txt
_beats/testing/environments/args.yml
_beats/testing/environments/docker/kafka/Dockerfile
_beats/testing/environments/snapshot.yml
_beats/vendor/vendor.json
vendor/github.com/elastic/beats/NOTICE.txt
vendor/github.com/elastic/go-sysinfo/providers/linux/container.go
vendor/github.com/elastic/go-sysinfo/providers/linux/machineid.go
vendor/github.com/elastic/go-sysinfo/providers/linux/os.go
vendor/vendor.json

for no real reason other than to satisfy the update-beats tests

[6.7] Update beats framework to 4a78177

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml
cmd/root.go
tests/system/test_export.py

...as the default is needed for the APM UI
fixes #2142

remove setup.template.settings._source setting from configuration

---

docs/common-problems.asciidoc

Closes: https://github.com/elastic/apm/issues/74

[docs] What happens when x is down

---

CHANGELOG.asciidoc
changelogs/6.7.asciidoc
changelogs/6.8.asciidoc
changelogs/7.0.asciidoc
changelogs/7.1.asciidoc
changelogs/head.asciidoc
docs/guide/apm-release-notes.asciidoc
docs/release-notes.asciidoc

update changelogs on master for 6.7.2, 6.8, 7.0.1, 7.1

sync changelogs

---

beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
tests/system/apmserver.py

7.1 CI failure is legit: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/7.1/6/pipeline

run approvals and fix apm-server version in tests

---

docs/common-problems.asciidoc
docs/configuration-rum.asciidoc
docs/guide/agent-server-compatibility.asciidoc
docs/guide/distributed-tracing.asciidoc
docs/rum.asciidoc
docs/setting-up-and-running.asciidoc
docs/sourcemap-api.asciidoc

* [docs] What happens when x is down (#2156)
* docs: update RUM and DT (#2090)

[docs][6.7] doc backports

---

changelogs/6.8.asciidoc
docs/common-problems.asciidoc
docs/configuration-rum.asciidoc
docs/guide/agent-server-compatibility.asciidoc
docs/guide/apm-release-notes.asciidoc
docs/guide/distributed-tracing.asciidoc
docs/rum.asciidoc
docs/setting-up-and-running.asciidoc
docs/sourcemap-api.asciidoc

* [docs] What happens when x is down (#2156)
* docs: update RUM and DT (#2090)

[docs][6.8] doc backports

---

changelogs/7.0.asciidoc
changelogs/head.asciidoc
docs/guide/apm-release-notes.asciidoc

This link is needed in master to sync the 7.0 changelogs across branches

docs: sync 7.0 changelog

---

beater/intake_handler.go

remove duplicated writeHeader call

---

beater/intake_handler.go

- remove duplicated writeHeader call  (#2230)

[7.2] remove duplicated writeHeader call (#2230)

---

docs/copied-from-beats/command-reference.asciidoc

Changes copied from @simitt's PR here: https://github.com/elastic/beats/pull/12583
Closes elastic/apm-server#2288

[docs] updated cmd docs

---

README.md
RELEASES.md
script/check_changelogs.py

First attempt at documenting the release process. Closes https://github.com/elastic/apm-server/issues/2197.

[docs] Add RELEASES.md

---

docs/copied-from-beats/shared-docker.asciidoc

Typo: beats -> APM server

---

docs/brew.asciidoc
docs/copied-from-beats/shared-directory-layout.asciidoc
docs/installing.asciidoc
docs/setting-up-and-running.asciidoc

Backports brew installation instructions

[docs][7.1] Brew install instructions (#2305)

---

docs/brew.asciidoc
docs/copied-from-beats/shared-directory-layout.asciidoc
docs/installing.asciidoc
docs/setting-up-and-running.asciidoc

Backports brew installation instructions

[docs][7.2] Brew install instructions (#2305)

---

docs/brew.asciidoc
docs/copied-from-beats/shared-directory-layout.asciidoc
docs/installing.asciidoc
docs/setting-up-and-running.asciidoc

Backports brew installation instructions

[docs][7.x] Brew install instructions (#2305)

---

README.md

- document docker packaging  (#2233)

[7.x] document docker packaging (#2233)

---

Jenkinsfile

see https://github.com/elastic/apm-server/pull/2254

feat(jenkins): new notifications and reports to Elasticsearch - 7.x

---

Jenkinsfile

see https://github.com/elastic/apm-server/pull/2254

feat(jenkins): new notifications and reports to Elasticsearch - 7.2

---

Jenkinsfile

see https://github.com/elastic/apm-server/pull/2254

feat(jenkins): new notifications and reports to Elasticsearch - 7.1

---

Jenkinsfile

see https://github.com/elastic/apm-server/pull/2254

feat(jenkins): new notifications and reports to Elasticsearch - 7.0

---

.github/pull_request_template.md

- add pull request template  (#2196)

[7.x] add pull request template (#2196)

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml
beater/beater.go
beater/beater_test.go
beater/config.go
beater/config_test.go
beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
docs/configuration-process.asciidoc
docs/copied-from-beats/outputconfig.asciidoc
publish/pub.go
tests/system/apmserver.py
tests/system/config/apm-server.yml.j2
tests/system/error.approved.json
tests/system/test_integration.py
tests/system/test_pipelines.py
tests/system/transaction.approved.json

- Enable APM pipeline by default.  (#2301)

[7.x] Enable APM pipeline by default. (#2301)

---

sourcemap/cache.go

Only a small internal improvement - no changelog necessary.

Sourcemap only log info for correct log level

---

sourcemap/cache.go

- Sourcemap only log info for correct log level  (#2358)

[7.x] Sourcemap only log info for correct log level (#2358)

---

beater/agent_config_handler.go
beater/beater.go
beater/common_handler.go
beater/intake_handler.go
beater/onboarding_test.go
beater/route_config.go
beater/server.go
idxmgmt/ilm/supporter_factory.go
ingest/pipeline/register.go
log/selectors.go
model/metricset/event.go
model/sourcemap/payload.go
model/stacktrace.go
sourcemap/accessor.go
sourcemap/cache.go
sourcemap/elasticsearch.go
sourcemap/elasticsearch_test.go
sourcemap/mapper.go
tests/system/apmserver.py
tests/system/config/apm-server.yml.j2
tests/system/test_integration.py
tests/system/test_integration_logging.py

- consolidate logging selectors  (#2359)

[7.x] consolidate logging selectors (#2359)

---

tests/system/test_integration.py

Remove testing for events with a hardcoded variable daily index to fix system tests.

Fix failing system-test

---

changelogs/7.2.asciidoc
changelogs/7.3.asciidoc
changelogs/head.asciidoc

Needs backport to `7.3` branch.

Fix changelog from 7.2 on.

---

tests/system/apmserver.py
tests/system/test_pipelines.py

- Fix timing issue for pipeline system test  (#2403)

[7.x] Fix timing issue for pipeline system test (#2403)

---

tests/system/apmserver.py
tests/system/test_pipelines.py

- Fix timing issue for pipeline system test  (#2403)

[7.3] Fix timing issue for pipeline system test (#2403)

---

changelogs/7.2.asciidoc
changelogs/7.3.asciidoc

- Fix changelog from 7.2 on.  (#2396)

[7.3] Fix changelog from 7.2 on. (#2396)

---

CHANGELOG.asciidoc
docs/release-notes.asciidoc

Removes head, adds 7.3 and 7.2 links.

[docs][7.3] Fix documentation build errors

---

CHANGELOG.asciidoc
docs/release-notes.asciidoc

Adds 7.3 and 7.2 links in master.

[docs] Add links to release notes

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml
docs/agent-configuration.asciidoc
docs/configure-kibana-endpoint.asciidoc
docs/configuring.asciidoc
docs/intake-api.asciidoc
docs/redirects.asciidoc

Backports to `7.x`
* [docs] Agent configuration documentation (#2366)

[docs][7.x] Agent configuration documentation (#2366)

---

.ci/check-changelogs.groovy
Makefile
script/check_changelogs.py
script/jenkins/check-changelogs.sh

backport pipeline from https://github.com/elastic/apm-server/issues/2260

feat: backport pipeline from #2260 [7.3]

---

beater/agent_config_handler.go
beater/agent_config_handler_test.go
tests/system/test_integration_acm.py

[ACM] Return 200 instead of 404 for missing config.

---

changelogs/7.2.asciidoc

- Update changelog for 7.2.1  (#2464)

[7.x] Update changelog for 7.2.1 (#2464)

---

changelogs/7.2.asciidoc

- Update changelog for 7.2.1  (#2464)

[7.3] Update changelog for 7.2.1 (#2464)

---

changelogs/7.2.asciidoc

- Update changelog for 7.2.1  (#2464)

[7.2] Update changelog for 7.2.1 (#2464)

---

beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
changelogs/head.asciidoc
docs/data/elasticsearch/generated/spans.json
model/metadata/service.go
model/span/event_test.go
processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json
processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
tests/system/spans.approved.json

Add service.environment to spans.

---

changelogs/6.8.asciidoc
docs/version.asciidoc

Do not merge until release day

[docs][6.8] 6.8.2 release notes and version

---

docs/version.asciidoc

Do not merge until release day.

[docs][7.2] 7.2.1 release bump

---

docs/version.asciidoc

Do not merge until release day.

[docs][7.3] 7.3.0 release version bump

---

docs/guide/apm-breaking-changes.asciidoc

This PR adds a section for 7.3.0 breaking changes in the APM Overview (https://www.elastic.co/guide/en/apm/get-started/7.3/apm-breaking-changes.html).

[DOCS] Adds 7.3.0 breaking changes

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml
docs/configuration-process.asciidoc
docs/configuration-rum.asciidoc
docs/configuring-ingest.asciidoc
docs/copied-from-beats/monitoring/shared-monitor-config.asciidoc
docs/copied-from-beats/outputconfig.asciidoc
docs/guide/apm-data-model.asciidoc

* [docs] Config YML updates (#2533)
* docs: update custom context links (#2525)
* [docs] Update pipeline documentation (#2536)

[7.x][docs] Documentation backports

---

docs/configuration-process.asciidoc
docs/configuration-rum.asciidoc
docs/configuring-ingest.asciidoc
docs/copied-from-beats/monitoring/shared-monitor-config.asciidoc
docs/copied-from-beats/outputconfig.asciidoc
docs/guide/apm-data-model.asciidoc

* [docs] Config YML updates (#2533) (partial)
* docs: update custom context links (#2525)
* [docs] Update pipeline documentation (#2536)

[7.3][docs] Documentation backports

---

script/update_kibana_objects.py

automate Kibana index pattern syncs

---

docs/copied-from-beats/monitoring/monitoring-beats.asciidoc
docs/copied-from-beats/shared-ssl-config.asciidoc

Docs: Asciidoctor compatibility

---

docs/copied-from-beats/monitoring/monitoring-beats.asciidoc
docs/copied-from-beats/shared-ssl-config.asciidoc

Docs: Asciidoctor compatibility (7.x) (#2567)

---

docs/copied-from-beats/monitoring/monitoring-beats.asciidoc
docs/copied-from-beats/shared-ssl-config.asciidoc

Docs: Asciidoctor compatibility (7.2) (#2567)

---

docs/copied-from-beats/monitoring/monitoring-beats.asciidoc
docs/copied-from-beats/shared-ssl-config.asciidoc

Docs: Asciidoctor compatibility (7.1) (#2567)

---

docs/copied-from-beats/monitoring/monitoring-beats.asciidoc
docs/copied-from-beats/shared-ssl-config.asciidoc

Docs: Asciidoctor compatibility (7.0) (#2567)

---

docs/copied-from-beats/monitoring/monitoring-beats.asciidoc
docs/copied-from-beats/shared-ssl-config.asciidoc

Docs: Asciidoctor compatibility (7.3) (#2567)

---

README.md
magefile.go

Changed the link Read more about Elastic APM

fix(readme): Changed the link Read more about Elastic APM

---

docs/configuration-rum.asciidoc

Backports https://github.com/elastic/apm-server/pull/2603

[docs] Add links to rum configs

---

changelogs/7.3.asciidoc
docs/version.asciidoc

**Do not merge until release day**

[7.3] Bump version and changelog for 7.3.1

---

Jenkinsfile

Closes https://github.com/elastic/apm-server/issues/2615
-  Warn in case of errors when running the Windows stage.
- Build and Test stages are now merged to run more in parallel and reduce the sequential stages to have a quick cycle.
- When the windows stage failed and other stages are still running 
- When the windows stage failed and the pipeline also failed
- More parallel branches

ci(jenkins): build and test stages are now merged.

---

beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
changelogs/head.asciidoc
docs/data/elasticsearch/generated/errors.json
docs/spec/errors/error.json
model/error/event.go
model/error/event_test.go
model/error/generated/schema/error.go
processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json

auto-generate exception parent and remove property from the intake

---

LICENSE.txt

PR for updating license text in beats: https://github.com/elastic/beats/pull/13347

Update license text for repo.

---

changelogs/6.8.asciidoc

[7.0] update 6.8 changelog

---

changelogs/6.8.asciidoc

[7.1] update 6.8 changelog

---

changelogs/6.8.asciidoc
changelogs/7.3.asciidoc
script/update_kibana_objects.py

Also cherry picks the update kibana objects script

[7.4] Update changelogs

---

tests/system/test_integration_acm.py

[7.x] fix headers (#2720)

---

docs/index.asciidoc
docs/version.asciidoc

This reverts commit aa971e1b46e62ecf3395be5ec8713fc8886095d0.

Revert "docs: fix versioning and attribute references (#2712)"

---

docs/guide/index.asciidoc
docs/guide/obs-integrations.asciidoc

- [docs] APM / Log UI integration documentaiton (#2672)

[7.4] [docs] APM / Log UI integration documentaiton (#2672)

---

docs/guide/index.asciidoc
docs/guide/obs-integrations.asciidoc

- [docs] APM / Log UI integration documentaiton (#2672)

[7.x] [docs] APM / Log UI integration documentaiton (#2672)

---

docs/version.asciidoc

**Do not merge until release day**

[7.4][docs] 7.4.0 release state

---

docs/guide/apm-doc-directory.asciidoc

[7.3] [docs] Fix typos (#2690)

---

docs/guide/agent-server-compatibility.asciidoc

Updates Agent / Server compat. Please confirm this is correct.

[docs] Update agent-server compatibility

---

changelogs/7.4.asciidoc
changelogs/head.asciidoc

Related to backport PR https://github.com/elastic/apm-server/pull/2794

fix changelog entry for PR#2772

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml
idxmgmt/feature.go
idxmgmt/ilm/config.go
idxmgmt/ilm/config_test.go
idxmgmt/ilm/policy.go
idxmgmt/ilm/supporter_factory.go
idxmgmt/ilm/supporter_factory_test.go
idxmgmt/ilm/template.go
idxmgmt/ilm/template_test.go
idxmgmt/manager.go
idxmgmt/manager_test.go
idxmgmt/supporter.go
idxmgmt/supporter_factory.go
idxmgmt/supporter_factory_test.go
idxmgmt/supporter_test.go
tests/system/config/apm-server.yml.j2
tests/system/test_export.py
tests/system/test_setup_index_management.py

- Make ILM policies configurable.  (#2764)

[7.x] Make ILM policies configurable. (#2764)

---

agentcfg/cache.go
agentcfg/cache_test.go
agentcfg/fetch.go
agentcfg/fetch_test.go
agentcfg/model.go
agentcfg/model_test.go
beater/api/config/agent/handler.go
beater/api/config/agent/handler_test.go
beater/api/intake/handler.go
beater/api/intake/handler_test.go
beater/api/mux.go
beater/middleware/cors_middleware.go
beater/middleware/rate_limit_middleware.go
beater/middleware/rum_middleware.go
beater/request/context.go
kibana/connecting_client.go
sourcemap/mapper.go
tests/system/apmserver.py
tests/system/test_integration_acm.py

[7.x] agent config GA

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml
idxmgmt/ilm/config_test.go
idxmgmt/ilm/policy.go
idxmgmt/manager.go
idxmgmt/manager_test.go
tests/system/config/apm-server.yml.j2
tests/system/test_export.py
tests/system/test_setup_index_management.py

- [ILM] Change default policies to 30day rollover  (#2798)

[7.x] [ILM] Change default policies to 30day rollover (#2798)

---

_beats/testing/environments/snapshot-oss.yml
_beats/testing/environments/snapshot.yml

Pin 7.5 in stack versions for integration tests

---

_beats/testing/environments/snapshot-oss.yml
_beats/testing/environments/snapshot.yml

[7.5] Pin 7.5 in stack versions for integration tests

---

CHANGELOG.asciidoc
changelogs/7.5.asciidoc
docs/release-notes.asciidoc

Add 7.5 changelog

---

changelogs/head.asciidoc

Rotated to https://github.com/elastic/apm-server/pull/2817

Clean head changelog for next release.

---

tests/system/test_setup_index_management.py

- [CI] Fix flaky ILM setup system test  (#2816)

[7.x] [CI] Fix flaky ILM setup system test (#2816)

---

tests/system/test_setup_index_management.py

- [CI] Fix flaky ILM setup system test  (#2816)

[7.5] [CI] Fix flaky ILM setup system test (#2816)

---

changelogs/6.8.asciidoc
changelogs/7.0.asciidoc

Add 6.8.4 changelog section.

---

docs/version.asciidoc

[DOCS] Bump docs for 7.4.1 release

---

docs/version.asciidoc

[DOCS] Bump docs for 6.8.4 release

---

beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/OffRum.approved.json
beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/OffSourcemap.approved.json
beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_KillSwitchMiddleware/Off.approved.json
beater/api/intake/test_approved/integration/rum/TestRUMHandler_KillSwitchMiddleware/OffRum.approved.json
beater/api/mux.go
beater/middleware/kill_switch_middleware.go
beater/middleware/kill_switch_middleware_test.go
tests/system/test_integration_acm.py

Clarify messages on 403 errors for each endpoint.

---

docs/configure-kibana-endpoint.asciidoc

little typo in the example code

Update configure-kibana-endpoint.asciidoc - Fix a little typo in the documentation

---

ingest/pipeline/definition.json

- Add failure handling to ingest pipelines.  (#2896)

[7.x] Add failure handling to ingest pipelines. (#2896)

---

docs/copied-from-beats/command-reference.asciidoc
docs/copied-from-beats/outputs/output-logstash.asciidoc
docs/copied-from-beats/repositories.asciidoc
docs/copied-from-beats/shared-docker.asciidoc
docs/copied-from-beats/shared-template-load.asciidoc
docs/guide/apm-data-model.asciidoc
docs/ilm-setup.asciidoc
docs/index.asciidoc
docs/storage-management.asciidoc
docs/version.asciidoc

Backports #2741 and updates it for `7.4`.

[7.4][docs] Use shared docs file (#2741)

---

docs/copied-from-beats/command-reference.asciidoc
docs/copied-from-beats/outputs/output-logstash.asciidoc
docs/copied-from-beats/repositories.asciidoc
docs/copied-from-beats/shared-docker.asciidoc
docs/copied-from-beats/shared-template-load.asciidoc
docs/guide/apm-data-model.asciidoc
docs/ilm-setup.asciidoc
docs/index.asciidoc
docs/storage-management.asciidoc
docs/version.asciidoc

Backports #2741 and updates it for `7.5`.

[7.5][docs] Use shared docs file (#2741)

---

docs/copied-from-beats/command-reference.asciidoc
docs/copied-from-beats/outputs/output-logstash.asciidoc
docs/copied-from-beats/repositories.asciidoc
docs/copied-from-beats/shared-docker.asciidoc
docs/copied-from-beats/shared-template-load.asciidoc
docs/guide/apm-data-model.asciidoc
docs/ilm-setup.asciidoc
docs/index.asciidoc
docs/storage-management.asciidoc
docs/version.asciidoc

Backports #2741 and updates it for `7.x`.

[7.x][docs] Use shared docs file (#2741)

---

docs/guide/apm-breaking-changes.asciidoc

[7.5][docs] Fix documentation tag

---

changelogs/6.8.asciidoc
docs/version.asciidoc

**DO NOT MERGE UNTIL `6.8.5` RELEASE**

[6.8][docs] 6.8.5 release notes and version bump

---

docs/configuring.asciidoc
docs/copied-from-beats/command-reference.asciidoc
docs/copied-from-beats/monitoring/monitoring-internal-collection.asciidoc
docs/copied-from-beats/monitoring/monitoring-metricbeat.asciidoc
docs/copied-from-beats/monitoring/shared-monitor-config.asciidoc
docs/copied-from-beats/outputconfig.asciidoc
docs/copied-from-beats/outputs/output-cloud.asciidoc
docs/copied-from-beats/outputs/output-kafka.asciidoc
docs/copied-from-beats/outputs/output-logstash.asciidoc
docs/copied-from-beats/outputs/output-redis.asciidoc
docs/copied-from-beats/security/beats-system.asciidoc
docs/copied-from-beats/security/securing-beats.asciidoc
docs/copied-from-beats/shared-docker.asciidoc
docs/copied-from-beats/shared-securing-beat.asciidoc
docs/copied-from-beats/shared-ssl-config.asciidoc
docs/copied-from-beats/shared-template-load.asciidoc
docs/copied-from-beats/template-config.asciidoc
docs/getting-started-apm-server.asciidoc
docs/index.asciidoc
docs/setting-up-and-running.asciidoc
docs/template-config.asciidoc

- [docs] Updates to the shared beats docs for 7.5 (#2956)
- [DOCS] Fixes security links (#2966)

[7.x] [docs] Updates to the shared beats docs for 7.5 (#2956)

---

docs/configuring.asciidoc
docs/copied-from-beats/command-reference.asciidoc
docs/copied-from-beats/monitoring/monitoring-internal-collection.asciidoc
docs/copied-from-beats/monitoring/monitoring-metricbeat.asciidoc
docs/copied-from-beats/monitoring/shared-monitor-config.asciidoc
docs/copied-from-beats/outputconfig.asciidoc
docs/copied-from-beats/outputs/output-cloud.asciidoc
docs/copied-from-beats/outputs/output-kafka.asciidoc
docs/copied-from-beats/outputs/output-logstash.asciidoc
docs/copied-from-beats/outputs/output-redis.asciidoc
docs/copied-from-beats/security/beats-system.asciidoc
docs/copied-from-beats/security/securing-beats.asciidoc
docs/copied-from-beats/shared-docker.asciidoc
docs/copied-from-beats/shared-securing-beat.asciidoc
docs/copied-from-beats/shared-ssl-config.asciidoc
docs/copied-from-beats/shared-template-load.asciidoc
docs/copied-from-beats/template-config.asciidoc
docs/getting-started-apm-server.asciidoc
docs/index.asciidoc
docs/setting-up-and-running.asciidoc
docs/template-config.asciidoc

- [docs] Updates to the shared beats docs for 7.5 (#2956)
- [DOCS] Fixes security links (#2966)

[7.5] [docs] Updates to the shared beats docs for 7.5 (#2956)

---

.ci/check-changelogs.groovy
Jenkinsfile

Faster checkout using the cached repos with a shallow clone of 3.

ci(jenkins): use git reference repo

---

changelogs/7.5.asciidoc

[docs] Add bug fix to release notes

---

NOTICE.txt
_beats/CHANGELOG.next.asciidoc
_beats/dev-tools/packaging/packages.yml
changelogs/head.asciidoc
vendor/github.com/elastic/beats/dev-tools/mage/dockerbuilder.go
vendor/github.com/elastic/beats/libbeat/beat/beat.go
vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go
vendor/github.com/elastic/beats/libbeat/cmd/setup.go
vendor/github.com/elastic/beats/libbeat/common/mapstr.go
vendor/github.com/elastic/beats/libbeat/processors/actions/add_fields.go
vendor/github.com/elastic/beats/libbeat/processors/actions/add_labels.go
vendor/github.com/elastic/beats/libbeat/publisher/processing/default.go
vendor/vendor.json

To pull in https://github.com/elastic/beats/pull/14796, for building UBI based images.
Closes #2858

Update beats framework to fa63445

---

changelogs/7.5.asciidoc

- [docs] Add bug fix to release notes (#2993)

[7.x] [docs] Add bug fix to release notes (#2993)

---

changelogs/7.5.asciidoc

- [docs] Add bug fix to release notes (#2993)

[7.5] [docs] Add bug fix to release notes (#2993)

---

Makefile

Add missing phony targets in Makefile

Add missing phony targets

---

NOTICE.txt
_beats/CHANGELOG.next.asciidoc
_beats/dev-tools/packaging/packages.yml
vendor/github.com/elastic/beats/libbeat/autodiscover/providers/kubernetes/config.go
vendor/github.com/elastic/beats/libbeat/autodiscover/providers/kubernetes/kubernetes.go
vendor/github.com/elastic/beats/libbeat/autodiscover/providers/kubernetes/node.go
vendor/github.com/elastic/beats/libbeat/autodiscover/providers/kubernetes/pod.go
vendor/github.com/elastic/beats/libbeat/autodiscover/providers/kubernetes/service.go
vendor/github.com/elastic/beats/libbeat/common/kubernetes/types.go
vendor/github.com/elastic/beats/libbeat/common/kubernetes/watcher.go
vendor/vendor.json

follow on from  #2994 to build ubi images for #2858

Update beats framework to c6b22c5

---

Jenkinsfile

it adds a new parameter to enable detailed diagnostic

feat: enable DIAGNOSTIC_INTERVAL env var

---

Makefile

- Merge pull request #2999 from jmlrt/makefile-phony

[7.x] Merge pull request #2999 from jmlrt/makefile-phony

---

docker-compose.yml
tests/system/apmserver.py
tests/system/config/apm-server.yml.j2
tests/system/error.approved.json
tests/system/spans.approved.json
tests/system/test_access.py
tests/system/test_export.py
tests/system/test_integration.py
tests/system/test_integration_acm.py
tests/system/test_integration_logging.py
tests/system/test_pipelines.py
tests/system/test_requests.py
tests/system/test_setup_index_management.py
tests/system/transaction.approved.json

- Update system tests (#3014)
-  Parts of #2827 and #2984

[7.x] Update system tests (#3014)

---

Makefile
TESTING.md
_beats/libbeat/scripts/Makefile
docker-compose.yml
testing/docker/elasticsearch/roles.yml
testing/docker/elasticsearch/users
testing/docker/elasticsearch/users_roles
tests/system/apmserver.py

- enable xpack security in system tests (#2799)

[7.x] enable xpack security in system tests (#2799)

---

TESTING.md
tests/approvals/approvals.go
tests/system/apmserver.py
tests/system/error.approved.json
tests/system/spans.approved.json
tests/system/test_integration.py
tests/system/transaction.approved.json

- tests: use approvals for system tests  (#3050)

[7.x] tests: use approvals for system tests (#3050)

---

NOTICE.txt
_beats/CHANGELOG.asciidoc
_beats/CHANGELOG.next.asciidoc
_beats/libbeat/docs/version.asciidoc
_beats/script/build_docs.sh
_beats/testing/environments/docker/kafka/run.sh
_beats/vendor/vendor.json
vendor/github.com/Shopify/sarama/broker.go
vendor/github.com/Shopify/sarama/dev.yml
vendor/github.com/elastic/beats/NOTICE.txt
vendor/github.com/elastic/beats/dev-tools/mage/config.go
vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go
vendor/github.com/elastic/beats/libbeat/common/fmtstr/formattimestamp.go
vendor/github.com/elastic/beats/libbeat/idxmgmt/ilm/ilm.go
vendor/github.com/elastic/beats/libbeat/idxmgmt/std.go
vendor/github.com/elastic/beats/libbeat/monitoring/monitoring.go
vendor/github.com/elastic/beats/libbeat/monitoring/report/elasticsearch/client.go
vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/bulkapi.go
vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go
vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/elasticsearch.go
vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/json_read.go
vendor/github.com/elastic/beats/libbeat/outputs/kafka/client.go
vendor/github.com/elastic/beats/libbeat/outputs/kafka/kafka.go
vendor/github.com/elastic/beats/libbeat/outputs/kafka/partition.go
vendor/github.com/elastic/beats/libbeat/publisher/event.go
vendor/vendor.json

This brings in fix for the Kafka output (https://github.com/elastic/beats/issues/14542)

[7.5] Update beats framework to e1b49ce

---

Dockerfile
README.md
changelogs/head.asciidoc
docs/version.asciidoc
tests/Dockerfile

update go to 1.13.5

---

changelogs/6.8.asciidoc
docs/version.asciidoc

**Do not merge until release day**

[docs] 6.8.6 release notes and doc version bump

---

Jenkinsfile

- ci(jenkins): when regexp comparator (#2644)

[7.x] ci(jenkins): when regexp comparator (#2644)

---

script/build_apm_docs.sh

- docs: updates doc script (#3073)

[7.x] docs: updates doc script (#3073)

---

script/build_apm_docs.sh

- docs: updates doc script (#3073)

[7.5] docs: updates doc script (#3073)

---

docs/secure-communication-agents.asciidoc

[docs] clarify apm-server.ssl.certificate example

---

docs/ilm.asciidoc

Closes https://github.com/elastic/apm-server/issues/3043.

[docs] Fix ILM copy pasta bug

---

README.md

Fix for https://github.com/elastic/apm-server/issues/3091

Add note about Python3

---

elasticsearch/config_test.go

Add a test to ensure we don't fall out of sync with libbeat's elasticsearch client config.
Closes #2990

elasticsearch: add libbeat compatibility test

---

elasticsearch/config_test.go

- elasticsearch: add libbeat compatibility test  (#3120)

[7.x] elasticsearch: add libbeat compatibility test (#3120)

---

docs/guide/cross-cluster-search.asciidoc
docs/guide/index.asciidoc
docs/guide/install-and-run.asciidoc

Closes https://github.com/elastic/apm/issues/124.

[docs] Adds APM app cross cluster search documentation

---

beater/api/profile/handler.go
beater/api/profile/handler_test.go

- beater/api/profile: fix pprof Content-Type  (#3144)

[7.x] beater/api/profile: fix pprof Content-Type (#3144)

---

changelogs/7.6.asciidoc
changelogs/head.asciidoc

Please merge and backport to 7.x if you're fine with the changelog.

Add changelog for 7.6

---

script/are_kibana_saved_objects_updated.py

Update are_kibana_saved_objects_updated.py to search through all of the open PRs by following "next" links.

script: fix are_kibana_saved_objects_updated.py

---

beater/beater.go
beater/onboarding.go
beater/onboarding_test.go
beater/server.go
beater/server_test.go

- beater: rewrite flaky test  (#3204)

[7.x] beater: rewrite flaky test (#3204)

---

NOTICE.txt
_beats/CHANGELOG.next.asciidoc
_beats/vendor/vendor.json
script/update_beats.sh
vendor/github.com/elastic/beats/NOTICE.txt
vendor/github.com/elastic/beats/dev-tools/mage/gotool/go.go
vendor/github.com/elastic/beats/libbeat/common/transport/tlscommon/types.go
vendor/github.com/elastic/beats/libbeat/common/transport/tlscommon/versions.go
vendor/github.com/elastic/beats/libbeat/common/transport/tlscommon/versions_default.go
vendor/github.com/elastic/beats/libbeat/common/transport/tlscommon/versions_legacy.go
vendor/github.com/elastic/beats/libbeat/outputs/transport/tls.go
vendor/github.com/elastic/beats/libbeat/processors/convert/convert.go
vendor/vendor.json

* backports script changes for updating beats from https://github.com/elastic/apm-server/pull/3196/files#diff-a9b21d1c3fd029de13f6de7d0d45b7fe
* updates to latest beats changes from `7.x`

[7.x] update beats script

---

changelogs/7.5.asciidoc

Cherry picks https://github.com/elastic/apm-server/pull/3219 to master.

[docs][7.5] 7.5.2 release notes #3219

---

tests/system/apmserver.py
tests/system/test_access.py
tests/system/test_apikey.py
tests/system/test_instrumentation.py

- [test] Improve system tests related to API Keys (#3175)

[7.6] [test] Improve system tests related to API Keys (#3175)

---

NOTICE.txt
_beats/CHANGELOG.next.asciidoc
_beats/testing/environments/latest.yml
_beats/vendor/vendor.json
script/update_beats.sh
vendor/github.com/elastic/beats/NOTICE.txt
vendor/vendor.json

* backports script changes for updating beats from https://github.com/elastic/apm-server/pull/3196/files#diff-a9b21d1c3fd029de13f6de7d0d45b7fe
* updates to latest beats changes from `7.6`

[7.6] update beats script and beats

---

tests/system/apmserver.py
tests/system/test_access.py
tests/system/test_apikey.py
tests/system/test_instrumentation.py

- [test] Improve system tests related to API Keys (#3175)

[7.x] [test] Improve system tests related to API Keys (#3175)

---

tests/system/apmserver.py
tests/system/config/apm-server.yml.j2
tests/system/test_export.py
tests/system/test_instrumentation.py
tests/system/test_integration.py

- tests/system: attempt to speed up tests  (#3202)

[7.x] tests/system: attempt to speed up tests (#3202)

---

NOTICE.txt
vendor/github.com/elastic/go-elasticsearch/v7/internal/version/version.go
vendor/vendor.json

[7.6] update go-elasticsearch client

---

tests/system/apmserver.py
tests/system/config/apm-server.yml.j2
tests/system/es_helper.py
tests/system/helper.py
tests/system/test_access.py
tests/system/test_export.py
tests/system/test_instrumentation.py
tests/system/test_integration.py
tests/system/test_integration_acm.py
tests/system/test_jaeger.py
tests/system/test_monitoring.py
tests/system/test_pipelines.py
tests/system/test_requests.py
tests/system/test_setup_index_management.py

- Improve system tests (#3217)

[7.x] Improve system tests (#3217)

---

tests/system/apmserver.py
tests/system/config/apm-server.yml.j2
tests/system/es_helper.py
tests/system/helper.py
tests/system/test_access.py
tests/system/test_export.py
tests/system/test_instrumentation.py
tests/system/test_integration.py
tests/system/test_integration_acm.py
tests/system/test_jaeger.py
tests/system/test_monitoring.py
tests/system/test_pipelines.py
tests/system/test_requests.py
tests/system/test_setup_index_management.py

- Improve system tests (#3217)

[7.6] Improve system tests (#3217)

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml

Add experimental flag to API Key feature

---

script/are_kibana_saved_objects_updated.py
script/update_kibana_objects.py

APM index-pattern.json in Kibana has moved with https://github.com/elastic/kibana/pull/54910/. Update path accordingly in APM Server.
fixes elastic/apm-server#3246

Update Kibana index-pattern path

---

script/are_kibana_saved_objects_updated.py
script/update_kibana_objects.py

- Update Kibana index-pattern path (#3247)

[7.x] Update Kibana index-pattern path (#3247)

---

tests/system/test_access.py
tests/system/test_instrumentation.py

- [test] Fix flaky self instrumentation system test (#3243)

[7.6] [test] Fix flaky self instrumentation system test (#3243)

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml

- Add experimental flag to API Key feature (#3240)

[7.x] Add experimental flag to API Key feature (#3240)

---

tests/system/test_access.py
tests/system/test_instrumentation.py

- [test] Fix flaky self instrumentation system test (#3243)

[7.x] [test] Fix flaky self instrumentation system test (#3243)

---

cmd/apikey.go
elasticsearch/security_api.go
tests/system/test_access.py
tests/system/test_apikey.py

As per https://github.com/elastic/apm-server/issues/2987#issuecomment-577717543

Remove creation of APM provileges.

---

cmd/apikey.go
elasticsearch/security_api.go
tests/system/test_access.py
tests/system/test_apikey.py

- Remove creation of APM provileges.  (#3251)

[7.x] Remove creation of APM provileges. (#3251)

---

elasticsearch/config.go

backports the fix for TLS configuration using the go-elasticsearch client and custom TLS config options via a proxy

[7.6] backport update tls configuration 

---

beater/api/mux.go
beater/api/mux_config_agent_test.go
beater/config/config.go
beater/config/config_test.go
kibana/connecting_client.go
kibana/connecting_client_test.go

closes #2647 
Can remove some duplication / risk of getting out of sync with beats framework if  elastic/beats#16042 is accepted

strip trailing slashes from kibana host configuration

---

.github/pull_request_template.md
CONTRIBUTING.md

We want to improve the experience of contributing to this repo, for that reason we created a more structured format for the existing template, moving some bullet points from the CONTRIBUTING guide to a checklist that will be present on each PR submission.
The format will consist in H2 headers and HTML comments, apart from a checklist for items that must be addressed by sender & reviewer during the review process.
Closes #3214

chore: update PR template for contributions (#3214)

---

docs/guide/apm-data-model.asciidoc

Correction to small documentation typo

---

docs/configuration-process.asciidoc

[bug fix] Wrong hosts parameter in example

---

Makefile
magefile.go
script/jenkins/windows-build.ps1
script/jenkins/windows-test.ps1

- magefile: use mage to build fields assets (#3372)

[7.x] magefile: use mage to build fields assets (#3372)

---

NOTICE.txt
_beats/CHANGELOG.next.asciidoc
_beats/libbeat/tests/system/requirements.txt
_beats/vendor/vendor.json
vendor/github.com/elastic/beats/NOTICE.txt
vendor/github.com/elastic/beats/libbeat/common/config.go
vendor/github.com/elastic/beats/libbeat/common/event.go
vendor/github.com/elastic/beats/libbeat/common/file/helper_aix.go
vendor/github.com/elastic/beats/libbeat/kibana/client.go
vendor/github.com/elastic/beats/libbeat/outputs/redis/redis.go
vendor/github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata/kubernetes.go
vendor/github.com/elastic/beats/x-pack/libbeat/autodiscover/providers/aws/elb/provider.go
vendor/github.com/elastic/go-ucfg/CHANGELOG.md
vendor/github.com/elastic/go-ucfg/merge.go
vendor/github.com/elastic/go-ucfg/opts.go
vendor/vendor.json

Update beats framework to 9c8d5c7
This vendors in the required changes for https://github.com/elastic/apm-server/pull/3359
~- [ ] I have rebased my changes on top of the latest master branch~
only automated tests required

Update beats framework to 9c8d5c7

---

NOTICE.txt
_beats/CHANGELOG.next.asciidoc
_beats/vendor/vendor.json
vendor/github.com/elastic/beats/NOTICE.txt
vendor/github.com/elastic/beats/libbeat/common/config.go
vendor/github.com/elastic/beats/libbeat/common/kubernetes/metadata/pod.go
vendor/github.com/elastic/beats/libbeat/kibana/client.go
vendor/github.com/elastic/beats/libbeat/outputs/redis/redis.go
vendor/github.com/elastic/beats/x-pack/libbeat/autodiscover/providers/aws/elb/provider.go
vendor/github.com/elastic/go-ucfg/CHANGELOG.md
vendor/github.com/elastic/go-ucfg/merge.go
vendor/github.com/elastic/go-ucfg/opts.go
vendor/vendor.json

Update beats framework to 7ab6d23 to get latest changes from Kibana client, precondition for https://github.com/elastic/apm-server/pull/3386.
Related to #3386

[7.x] Update beats framework to 7ab6d23

---

tests/system/test_apikey_cmd.py
tests/system/test_auth.py
tests/system/test_instrumentation.py
tests/system/test_integration_sourcemap.py
tests/system/test_tls.py

- Attempt to fix flaky API Key test (#3367)

[7.x] Attempt to fix flaky API Key test (#3367)

---

changelogs/7.6.asciidoc
changelogs/head.asciidoc

Update changelog to reflect `7.6.1` changes.

Update changelog to 7.6.1 changes

---

changelogs/6.8.asciidoc
docs/version.asciidoc

[docs] 6.8.7 release notes and doc version bump

---

Jenkinsfile
magefile.go
script/jenkins/windows-build.ps1
script/jenkins/windows-test.ps1

This is a cherry-pick of:
- https://github.com/elastic/apm-server/pull/2890
- partially https://github.com/elastic/apm-server/pull/3357
No more issues with python3, the `system test` stage report can be seen in:
- https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/PR-3428/23/testReport/
__NOTE__: I'm running a whole build after playing quite a bit with different configurations.

ci(jenkins): Fix issues with python3 in branch 6.8

---

.ci/docker/golang-mage/Dockerfile

Since switching to go modules there is no vendor folder,
adapt go get commands accordingly for CI Dockerfile.
This is supposed to fix failing CI on `master`
[failing tests in master](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp/detail/master/382/pipeline)

Fix CI Dockerfile paths for go get

---

tests/system/test_tls.py

- Update client cert auth tests to TLS 1.3 (#3474)

[7.x] Update client cert auth tests to TLS 1.3 (#3474)

---

tests/system/test_tls.py

We are forcing the "Connection: close" HTTP header for the test, so that it is not reused.
besides that, we raise the stored HTTPError, if one ocurred
~~- [ ] I have made corresponding changes to the documentation~~
Please run:
```shell
$ make docker-system-tests SYSTEM_TEST_TARGET=./tests/system/test_tls.py:TestSSLEnabledNoClientAuthenticationTest.test_http_fails
```
- Closes #3420

Fix TLS flaky system test

---

tests/system/test_tls.py

Backport of #3484
~~- [ ] I have made corresponding changes to the documentation~~
Backports #3484

Backport flaky test

---

docs/copied-from-beats/docs/command-reference.asciidoc
docs/copied-from-beats/docs/https.asciidoc
docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
docs/copied-from-beats/docs/monitoring/shared-monitor-config-legacy.asciidoc
docs/copied-from-beats/docs/output-cloud.asciidoc
docs/copied-from-beats/docs/outputconfig.asciidoc
docs/copied-from-beats/docs/outputs-list.asciidoc
docs/copied-from-beats/docs/repositories.asciidoc
docs/copied-from-beats/docs/security/api-keys.asciidoc
docs/copied-from-beats/docs/security/basic-auth.asciidoc
docs/copied-from-beats/docs/security/users.asciidoc
docs/copied-from-beats/docs/shared-ssl-config.asciidoc
docs/copied-from-beats/docs/shared-systemd.asciidoc
docs/copied-from-beats/docs/template-config.asciidoc
docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc
docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
docs/copied-from-beats/outputs/redis/docs/redis.asciidoc

- docs: Update documentation from Beats (#3459)

[7.6] docs: Update documentation from Beats (#3459)

---

docs/copied-from-beats/docs/command-reference.asciidoc
docs/copied-from-beats/docs/https.asciidoc
docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
docs/copied-from-beats/docs/monitoring/shared-monitor-config-legacy.asciidoc
docs/copied-from-beats/docs/output-cloud.asciidoc
docs/copied-from-beats/docs/outputconfig.asciidoc
docs/copied-from-beats/docs/outputs-list.asciidoc
docs/copied-from-beats/docs/repositories.asciidoc
docs/copied-from-beats/docs/security/api-keys.asciidoc
docs/copied-from-beats/docs/security/basic-auth.asciidoc
docs/copied-from-beats/docs/security/users.asciidoc
docs/copied-from-beats/docs/shared-ssl-config.asciidoc
docs/copied-from-beats/docs/shared-systemd.asciidoc
docs/copied-from-beats/docs/template-config.asciidoc
docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc
docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
docs/copied-from-beats/outputs/redis/docs/redis.asciidoc

- docs: Update documentation from Beats (#3459)

[7.x] docs: Update documentation from Beats (#3459)

---

.ci/docker/golang-mage/Dockerfile
Jenkinsfile
Makefile
script/jenkins/build.sh
script/jenkins/package.sh
script/jenkins/test-install-packages.sh

Adapt to golang-mage Dockerfile to install modules into build directory and use accordingly in Jenkinsfile. 
~- [ ] I have rebased my changes on top of the latest master branch~
CI tests need to pass
follow up on https://github.com/elastic/apm-server/pull/3454/files#r390167891

Install modules into build directory for CI

---

docs/getting-started-apm-server.asciidoc
docs/guide/install-and-run.asciidoc

This PR switches trial sign-up links over to the standard attribute we're introducing that should provide some metrics for how effective these links are.﻿
Details for the attribute are in https://github.com/elastic/docs/pull/1737, if you want to know more. 
@bmorelli25 if you could review this PR, I would be grateful. I'd also appreciate any pointers you have for getting these changes into all the right branches.

Switch to standard ESS trial links

---

processor/stream/benchmark_test.go

- processor/stream: fix panic in benchmarks (#3517)

[7.x] processor/stream: fix panic in benchmarks (#3517)

---

.gitignore
decoder/line_reader.go
decoder/req_decoder.go
decoder/stream_decoder.go
decoder/stream_decoder_test.go
processor/stream/package_tests/intake_test_processor.go
processor/stream/package_tests/metadata_attrs_test.go
processor/stream/processor.go

- processor/stream optimisations (#3523)

[7.x] processor/stream optimisations (#3523)

---

docs/secure-communication-agents.asciidoc

- Update secure-communication-agents.asciidoc (#3538)

[7.x] Update secure-communication-agents.asciidoc (#3538)

---

NOTICE.txt
go.mod
go.sum

Upgrade go-elasticsearch library to `7.7` branch

[7.7] Update to go-elasticsearch 7.7 branch

---

tests/system/test_integration_acm.py
tests/system/test_jaeger.py

Fixes broken system tests for changed Kibana API for creating agent config settings. 

Fix system tests for agent config mgmt

---

tests/system/test_integration_acm.py
tests/system/test_jaeger.py

- Fix system tests for agent config mgmt (#3557)

[7.x] Fix system tests for agent config mgmt (#3557)

---

tests/system/test_integration_acm.py
tests/system/test_jaeger.py

- Fix system tests for agent config mgmt (#3557)

[7.7] Fix system tests for agent config mgmt (#3557)

---

changelogs/head.asciidoc
docs/spec/transactions/rum_v3_mark.json
docs/spec/transactions/rum_v3_transaction.json
model/transaction/event.go
model/transaction/event_test.go
model/transaction/generated/schema/rum_v3_transaction.go
processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json

Closes elastic/apm-server#3473

Spec out transaction marks for RUM V3

---

cmd/root.go
tests/system/test_export.py
tests/system/test_integration_logging.py

Ensure logging overwrites do not cause logging to stdout to fail
fixes #3576

[fix] fix logging overwrite values

---

cmd/root.go
tests/system/test_export.py
tests/system/test_integration_logging.py

- [fix] fix logging overwrite values (#3577)

[7.x] [fix] fix logging overwrite values (#3577)

---

cmd/root.go
tests/system/test_export.py
tests/system/test_integration_logging.py

- [fix] fix logging overwrite values (#3577)

[7.7] [fix] fix logging overwrite values (#3577)

---

changelogs/6.8.asciidoc
docs/version.asciidoc

**DO NOT MERGE UNTIL RELEASED**

[6.8] docs: 6.8.8 version bump and release notes

---

NOTICE.txt
go.mod
go.sum

Update to latest changes in the go-elasticsearch client.

Update go-elasticsearch dependency

---

beater/api/mux.go

As per https://github.com/elastic/apm-server/pull/3518#issuecomment-607665914

Remove reference to release version

---

beater/api/mux.go
beater/api/mux_intake_rum_test.go

Asked in https://github.com/elastic/apm-server/pull/3513#issuecomment-601772896

Revert "Require a minimum version in the RUM V3 handler."

---

docs/configuring-output-after.asciidoc

- docs: improvements for APM fields (#3608)

[7.x] docs: improvements for APM fields (#3608)

---

docs/guide/apm-doc-directory.asciidoc

This PR updates three links in the APM overview. These link changes are required for the changes proposed in https://github.com/elastic/kibana/pull/63280.

docs: update links to APM app documentation

---

Jenkinsfile

We already build the docker images when using the `hey-apm` comment trigger, so a similar approach will be done for building the docker images for every commit.
This will help us to move to CD when required.
Run build manually with the parameter: `Run_As_Master_Branch`
- When running the Hey-Apm stage, this can happen when using the GH comment `hey-apm....` then it will push the image twice (one in each stage). I could potentially avoid it, but it might make the Jenkinsfile a bit spaghetti code, so I'd rather prefer the duplicity for simplicity.
_NOTE_: https://github.com/elastic/apm-server/pull/3637#issuecomment-610918458 didn't cause any issues at all.

ci(jenkins): generate docker images for every commit

---

docs/breaking-changes.asciidoc
docs/guide/apm-breaking-changes.asciidoc
docs/guide/apm-doc-directory.asciidoc
docs/guide/apm-release-notes.asciidoc

This PR adds the tagged regions needed for release highlights and breaking changes in the stack documentation https://github.com/elastic/stack-docs/pull/993. A follow-up PR will be opened to add content to each section.

docs: 7.7.0 release highlights and breaking changes

---

docs/breaking-changes.asciidoc
docs/guide/apm-breaking-changes.asciidoc
docs/guide/apm-doc-directory.asciidoc
docs/guide/apm-release-notes.asciidoc

- docs: 7.7 release highlights and changes outline (#3653)

[7.x] docs: 7.7 release highlights and changes outline (#3653)

---

docs/breaking-changes.asciidoc
docs/guide/apm-breaking-changes.asciidoc
docs/guide/apm-doc-directory.asciidoc
docs/guide/apm-release-notes.asciidoc

- docs: 7.7 release highlights and changes outline (#3653)

[7.7] docs: 7.7 release highlights and changes outline (#3653)

---

model/span.go

model: fix span.transformations metric name

---

beater/beater.go
beater/beater_test.go
beater/config/rum.go
beater/http.go
beater/integration_test.go
beater/onboarding.go
beater/onboarding_test.go
beater/server.go
beater/server_test.go
beater/tracing.go
beater/tracing_test.go
main.go
x-pack/apm-server/cmd/root.go
x-pack/apm-server/cmd/root_test.go
x-pack/apm-server/main.go

- beater: introduce NewCreator and RunServer(Func) (#3668)

[7.x] beater: introduce NewCreator and RunServer(Func) (#3668)

---

magefile.go

suggest make instead

---

docs/data/elasticsearch/generated/errors.json
docs/data/elasticsearch/generated/metricsets.json
docs/data/elasticsearch/generated/spans.json
docs/data/elasticsearch/generated/transactions.json
tests/approvals/approvals.go
tests/system/apmserver.py
tests/system/error.approved.json
tests/system/jaeger_batch_0.approved.json
tests/system/jaeger_batch_0_auth_tag_removed.approved.json
tests/system/jaeger_batch_0_authorization.approved.json
tests/system/jaeger_span.approved.json
tests/system/metricset.approved.json
tests/system/spans.approved.json
tests/system/transaction.approved.json

Minimize diffs by enforcing consistent (alphabetized by key) json encoding.
- ~[ ] I have made corresponding changes to the documentation~
- ~[ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~

Consistent encoding for approval system tests

---

docs/data/elasticsearch/generated/errors.json
docs/data/elasticsearch/generated/metricsets.json
docs/data/elasticsearch/generated/spans.json
docs/data/elasticsearch/generated/transactions.json
tests/approvals/approvals.go
tests/system/apmserver.py
tests/system/error.approved.json
tests/system/jaeger_batch_0.approved.json
tests/system/jaeger_batch_0_auth_tag_removed.approved.json
tests/system/jaeger_batch_0_authorization.approved.json
tests/system/jaeger_span.approved.json
tests/system/metricset.approved.json
tests/system/spans.approved.json
tests/system/transaction.approved.json

- sort system test approvals (#3682)

[7.x] sort system test approvals (#3682)

---

beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
model/batch.go
model/modeldecoder/error.go
model/modeldecoder/error_test.go
model/modeldecoder/metricset.go
model/modeldecoder/metricset_test.go
model/modeldecoder/span.go
model/modeldecoder/span_test.go
model/modeldecoder/transaction.go
model/modeldecoder/transaction_test.go
model/transaction.go
processor/otel/consumer.go
processor/stream/package_tests/intake_test_processor.go
processor/stream/processor.go
processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
processor/stream/test_approved_es_documents/testIntakeIntegrationMinimalService.approved.json
processor/stream/test_approved_stream_result/testIntegrationResultRUMV3Events.approved.json
testdata/jaeger/batch_1.approved.json
tests/system/kibana.py

Refactor model as per https://github.com/elastic/apm-server/pull/3648#discussion_r408547367
Note re. golden files: I hope/expect diff exists due to change of order of events, but it is quite hard to read.

Refactor: decode events into batches

---

beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
model/batch.go
model/modeldecoder/error.go
model/modeldecoder/error_test.go
model/modeldecoder/metricset.go
model/modeldecoder/metricset_test.go
model/modeldecoder/span.go
model/modeldecoder/span_test.go
model/modeldecoder/transaction.go
model/modeldecoder/transaction_test.go
model/transaction.go
processor/otel/consumer.go
processor/stream/package_tests/intake_test_processor.go
processor/stream/processor.go
processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
processor/stream/test_approved_es_documents/testIntakeIntegrationMinimalService.approved.json
processor/stream/test_approved_stream_result/testIntegrationResultRUMV3Events.approved.json
testdata/jaeger/batch_1.approved.json

- Refactor: decode events into batches (#3724)

[7.x] Refactor: decode events into batches (#3724)

---

model/modeldecoder/field/rum_v3_mapping.go
processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json

fix typo in subtype

---

model/modeldecoder/field/rum_v3_mapping.go

Some changes got lost when backporting https://github.com/elastic/apm-server/pull/3634/files (compared to changes in master https://github.com/elastic/apm-server/pull/3619/files).

[7.x] Fix backport from master for RUMv3 field mapping

---

RELEASES.md
changelogs/7.8.asciidoc
changelogs/head.asciidoc

* Create changelog for `7.8`
* Update todo notes for preparing releases

Release update

---

NOTICE.txt
go.mod
go.sum

Update to latest `7.x` commit for go-elasticsearch dependency.
`make test`
part of branching out `7.8`.

[7.8] Update go-elasticsearch client dependency

---

changelogs/7.8.asciidoc

backport: Update changelog for `7.8`.

[7.8] Update changelog for 7.8

---

changelogs/7.8.asciidoc

backport: Update changelog for `7.8`. 
<!--
Please explain the motivation behind this PR, along with a summary of the major changes involved. Replace this comment with a description of what is being changed by this PR and why.

[7.x] Update changelog for 7.8

---

Makefile
NOTICE.txt
docs/version.asciidoc
go.mod
go.sum

Update beats framework to 2c4c2432da71
<!--
Please explain the motivation behind this PR, along with a summary of the major changes involved. Replace this comment with a description of what is being changed by this PR and why.
Major changes require a number of considerations including impact on:

[7.8] Update beats framework to ~2c4c2432da71~ b1fdd94c7a16

---

model/batch.go
model/modeldecoder/error.go
model/modeldecoder/error_test.go
model/modeldecoder/metricset.go
model/modeldecoder/metricset_test.go
model/modeldecoder/span.go
model/modeldecoder/span_test.go
model/modeldecoder/transaction.go
model/modeldecoder/transaction_test.go
processor/otel/consumer.go
processor/stream/processor.go

- Fix performance degradation (#3755)

[7.x] Fix performance degradation (#3755)

---

model/batch.go
model/modeldecoder/error.go
model/modeldecoder/error_test.go
model/modeldecoder/metricset.go
model/modeldecoder/metricset_test.go
model/modeldecoder/span.go
model/modeldecoder/span_test.go
model/modeldecoder/transaction.go
model/modeldecoder/transaction_test.go
processor/otel/consumer.go
processor/stream/processor.go

- Fix performance degradation (#3755)

[7.8] Fix performance degradation (#3755)

---

agentcfg/fetch.go
beater/api/config/agent/handler.go
beater/api/config/agent/handler_test.go

Clarify error message when unauthorized Kibana connection

---

NOTICE.txt
beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
go.mod
go.sum
tests/system/es_helper.py

Update beats framework, which includes a version update to `7.9`
`make test`

[7.x] update beats for bumping version to 7.9

---

docs/data-ingestion.asciidoc

[7.x] docs: minor fix (#3767)

---

docs/data-ingestion.asciidoc

[7.7] docs: minor fix (#3767)

---

docs/data-ingestion.asciidoc

[7.6] docs: minor fix (#3767)

---

docs/data-ingestion.asciidoc

[7.8] docs: minor fix (#3767)

---

NOTICE.txt
cmd/root.go
go.mod
go.sum
testing/environments/latest.yml
testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

Update beats framework and remove tracer changes
cc @jalvz

[7.8] update beats + tracer changes from @jalvz

---

NOTICE.txt
cmd/root.go
go.mod
go.sum
testing/environments/latest.yml

[7.x] Update beats

---

changelogs/6.8.asciidoc
docs/version.asciidoc

**Do not merge until release day**

[6.8] docs: 6.8.9 docs version and add release notes

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml
docs/copied-from-beats/docs/loggingconfig.asciidoc
docs/copied-from-beats/docs/shared-kerberos-config.asciidoc
docs/copied-from-beats/docs/shared-ssl-config.asciidoc
docs/copied-from-beats/docs/shared-systemd.asciidoc
docs/copied-from-beats/docs/shared-template-load.asciidoc
docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
docs/copied-from-beats/outputs/redis/docs/redis.asciidoc

- docs: Update documentation copied from Beats (#3793)

[7.8] docs: Update documentation copied from Beats (#3793)

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml
docs/copied-from-beats/docs/loggingconfig.asciidoc
docs/copied-from-beats/docs/shared-kerberos-config.asciidoc
docs/copied-from-beats/docs/shared-ssl-config.asciidoc
docs/copied-from-beats/docs/shared-systemd.asciidoc
docs/copied-from-beats/docs/shared-template-load.asciidoc
docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
docs/copied-from-beats/outputs/redis/docs/redis.asciidoc

- docs: Update documentation copied from Beats (#3793)

[7.x] docs: Update documentation copied from Beats (#3793)

---

beater/beater.go
beater/beater_test.go
beater/server.go
beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
beater/tracing_test.go
main.go
x-pack/apm-server/cmd/root_test.go
x-pack/apm-server/main.go

- beater: CreatorParams.RunServer -> WrapRunServer (#3803)

[7.8] beater: CreatorParams.RunServer -> WrapRunServer (#3803)

---

docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc

For https://github.com/elastic/beats/pull/18672.

docs: update links to logstash getting started

---

changelogs/7.7.asciidoc

This PR adds release notes for the 7.7.1 release of APM Server

docs: add 7.7.1 release notes

---

changelogs/6.8.asciidoc
changelogs/7.7.asciidoc
script/check_changelogs.py

This PR syncs the changelog in master with the changelog in `6.8` and `7.7`.

docs: Sync changelogs

---

docs/data/elasticsearch/generated/errors.json
docs/data/elasticsearch/generated/transactions.json
tests/system/drop_unsampled_transactions.approved.json
tests/system/error.approved.json
tests/system/keep_unsampled_transactions.approved.json
tests/system/transaction.approved.json

Fixes test suite. This was missed in https://github.com/elastic/apm-server/pull/3857 (sorry)
Follow up from https://github.com/elastic/apm-server/pull/3857

Update approval files

---

NOTICE.txt
beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
go.mod
go.sum
tests/system/es_helper.py

Update beats framework to pull in `7.8.1` version.

7.8 update version

---

NOTICE.txt
beater/config/aggregation.go
beater/config/config_test.go
go.mod
go.sum
model/error_test.go
model/metadata.go
model/metadata_test.go
model/modeldecoder/context.go
model/modeldecoder/context_test.go
model/modeldecoder/error_test.go
model/modeldecoder/metadata.go
model/modeldecoder/metadata_test.go
model/modeldecoder/transaction_test.go
model/modeldecoder/user.go
model/modeldecoder/user_test.go
model/transaction_test.go
model/user.go
model/useragent.go
model/useragent_test.go
tests/system/rum_transaction_histogram_metrics.approved.json
tests/system/test_aggregation.py
x-pack/apm-server/aggregation/txmetrics/aggregator.go
x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
x-pack/apm-server/aggregation/txmetrics/useragent.go
x-pack/apm-server/main.go

- aggregation/txmetrics: aggregate user_agent.name (#3886)

[7.x] aggregation/txmetrics: aggregate user_agent.name (#3886)

---

processor/otel/consumer.go
processor/otel/consumer_test.go
processor/otel/test_approved/span_jaeger_messaging.approved.json
processor/otel/test_approved/transaction_jaeger_type_messaging.approved.json

- Support for message_bus.destination in the Jaeger processor (#3884)

[7.x] Support for message_bus.destination in the Jaeger processor (#3884)

---

processor/otel/consumer.go
processor/otel/test_approved/span_jaeger_http.approved.json

- Support for peer.service in the Jaeger processor (#3897)

[7.x] Support for peer.service in the Jaeger processor (#3897)

---

model/context.go
model/modeldecoder/transaction.go
model/modeldecoder/transaction_test.go
model/transaction.go
model/transaction_test.go
processor/otel/consumer.go
processor/otel/test_approved/consume_span.approved.json
processor/otel/test_approved/metadata_jaeger-no-language.approved.json
processor/otel/test_approved/metadata_jaeger-version.approved.json
processor/otel/test_approved/metadata_jaeger.approved.json
processor/otel/test_approved/metadata_jaeger_full-traceid.approved.json
processor/otel/test_approved/metadata_jaeger_minimal.approved.json
processor/otel/test_approved/metadata_minimal.approved.json
processor/otel/test_approved/transaction_jaeger_custom.approved.json
processor/otel/test_approved/transaction_jaeger_no_attrs.approved.json
processor/otel/test_approved/transaction_jaeger_type_component.approved.json
processor/otel/test_approved/transaction_jaeger_type_messaging.approved.json
processor/otel/test_approved/transaction_jaeger_type_request.approved.json
processor/otel/test_approved/transaction_jaeger_type_request_result.approved.json
processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
x-pack/apm-server/aggregation/txmetrics/aggregator.go
x-pack/apm-server/aggregation/txmetrics/aggregator_test.go

- model: more depointering, decoder refactoring (#3894)

[7.x] model: more depointering, decoder refactoring (#3894)

---

agentcfg/fetch.go
agentcfg/model.go
docs/common-problems.asciidoc
tests/fields.go
tests/fields_test.go

- Use more inclusive language (#3903)

[7.x] Use more inclusive language (#3903)

---

docs/guide/obs-integrations.asciidoc

- Change links to refactored Beats getting started docs (#3939)

[7.x] Change links to refactored Beats getting started docs (#3939)

---

beater/config/config_test.go

- beater/config: fix TLS config tests (#3962)

[7.x] beater/config: fix TLS config tests (#3962)

---

NOTICE.txt
cmd/root.go
go.sum
script/common.bash
script/gimme/LICENSE
script/gimme/gimme

- script: vendor gimme (#3965)

[7.x] script: vendor gimme (#3965)

---

NOTICE.txt
beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
go.mod
go.sum
tests/system/es_helper.py

Update beats framework to f5f1f7de6c8d

start 7.10

---

docs/common-problems.asciidoc

- docs: add troubleshooting (#3978)

[7.x] docs: add troubleshooting (#3978)

---

docs/configuring.asciidoc
docs/copied-from-beats/docs/command-reference.asciidoc
docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
docs/copied-from-beats/docs/monitoring/monitoring-internal-collection-legacy.asciidoc
docs/copied-from-beats/docs/monitoring/monitoring-metricbeat.asciidoc
docs/copied-from-beats/docs/monitoring/shared-monitor-config-legacy.asciidoc
docs/copied-from-beats/docs/outputs-list.asciidoc
docs/copied-from-beats/docs/shared-instrumentation.asciidoc
docs/copied-from-beats/docs/shared-kerberos-config.asciidoc
docs/copied-from-beats/docs/shared-systemd.asciidoc
docs/copied-from-beats/docs/template-config.asciidoc
docs/copied-from-beats/outputs/console/docs/console.asciidoc
docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc
docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc

- docs: Update documentation from Beats for 7.9 (#3977)

[7.x] docs: Update documentation from Beats for 7.9 (#3977)

---

docs/common-problems.asciidoc

- docs: add troubleshooting (#3978)

[7.9] docs: add troubleshooting (#3978)

---

docs/configuring.asciidoc
docs/copied-from-beats/docs/command-reference.asciidoc
docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
docs/copied-from-beats/docs/monitoring/monitoring-internal-collection-legacy.asciidoc
docs/copied-from-beats/docs/monitoring/monitoring-metricbeat.asciidoc
docs/copied-from-beats/docs/monitoring/shared-monitor-config-legacy.asciidoc
docs/copied-from-beats/docs/outputs-list.asciidoc
docs/copied-from-beats/docs/shared-instrumentation.asciidoc
docs/copied-from-beats/docs/shared-kerberos-config.asciidoc
docs/copied-from-beats/docs/shared-systemd.asciidoc
docs/copied-from-beats/docs/template-config.asciidoc
docs/copied-from-beats/outputs/console/docs/console.asciidoc
docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc
docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc

- docs: Update documentation from Beats for 7.9 (#3977)

[7.9] docs: Update documentation from Beats for 7.9 (#3977)

---

docs/common-problems.asciidoc

- docs: add troubleshooting (#3978)

[7.8] docs: add troubleshooting (#3978)

---

.ci/check-packages.groovy

This is an attempt to try the job on a Linux worker to see if it runs. It also fixes a possible problem with the cleanup step.

Try immutable and wrap clean step with goenv

---

.ci/check-packages.groovy

Another quick change to debug the packaging pipeline.

Specify specific branch name in packaging job

---

tests/system/test_pipelines.py

- tests/system: update user-agent pipline test (#4018)

[7.x] tests/system: update user-agent pipline test (#4018)

---

cmd/root.go
cmd/version.go
go.sum
magefile.go
tests/system/es_helper.py
tests/system/helper.py

- take ownership of version (#4028)

[7.x] take ownership of version (#4028)

---

CHANGELOG.asciidoc
changelogs/7.9.asciidoc
changelogs/head.asciidoc
docs/breaking-changes.asciidoc
docs/guide/apm-breaking-changes.asciidoc
docs/guide/apm-release-notes.asciidoc
docs/release-notes.asciidoc

This PR updates release notes and breaking changes for 7.9. It also adds a placeholder tagged region for release highlights.

[docs] 7.9 release notes and breaking changes

---

CHANGELOG.asciidoc
changelogs/7.9.asciidoc
docs/breaking-changes.asciidoc
docs/guide/apm-breaking-changes.asciidoc
docs/guide/apm-release-notes.asciidoc
docs/release-notes.asciidoc

- [docs] 7.9 release notes and breaking changes (#4033)

[7.9] [docs] 7.9 release notes and breaking changes (#4033)

---

docs/guide/apm-release-notes.asciidoc

SIEM has been renamed to Elastic Security. This PR updates the terminology.

[Docs]Replaces SIEM terminology

---

changelogs/7.9.asciidoc
docs/guide/apm-release-notes.asciidoc
docs/guide/opentelemetry-elastic.asciidoc

- Merge pull request #4042 from bmorelli25/7.9-release-highlights (#4042)

[7.9][docs] Add 7.9 release highlights (#4042)

---

publish/acker.go
publish/pub_test.go

Fix the ACKer implementation to immediately unblock Wait on Close, when there are no active events.
I found that while running system tests some of them were taking surprisingly long to complete. Turned out that they were waiting for the full shutdown timeout to complete, due to there being no events published during the tests.
~- [ ] Elasticsearch Service …

publish: fix shutdown timeout handling

---

docs/guide/apm-release-notes.asciidoc

- [DOCS] Fixes broken link in Release Notes (#4073)

[7.9] [DOCS] Fixes broken link in Release Notes (#4073)

---

docs/guide/apm-release-notes.asciidoc

- [DOCS] Fixes broken link in Release Notes (#4073)

[7.x] [DOCS] Fixes broken link in Release Notes (#4073)

---

x-pack/apm-server/aggregation/spanmetrics/aggregator.go
x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go

Fix a data race between ProcessTransformables and the
aggregation loop by adding a read lock when updating
the active metrics.
A couple of other fixes:
- Add missing docs to exported methods.
- The benchmark was effectively a no-op, as there was no service
destination resource defined. Introduce a "makeSpan" function
which is used by both the benchmark and functional test.
~- …

aggregator/spanmetrics: fix data race

---

changelogs/7.9.asciidoc

[7.9][docs] 7.9.1 release notes

---

NOTICE.txt
beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
go.mod
go.sum
testing/environments/latest.yml
testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml
tests/system/es_helper.py

Update beats framework for version bump to 7.9.2
make test

7.9.2 version bump

---

model/stacktrace.go

- Change sourcemap logging (#4132)

[7.x] Change sourcemap logging (#4132)

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml

Fix indentation in instrumentation section of config

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml

- Fix indentation in instrumentation section of config (#4147)

[7.x] Fix indentation in instrumentation section of config (#4147)

---

script/are_kibana_saved_objects_updated.py
script/update_kibana_objects.py

- Update index pattern path (#3822)

[7.x] Update index pattern path (#3822)

---

systemtest/aggregation_test.go
systemtest/apmservertest/config.go
systemtest/approvals/TestRUMXForwardedFor.approved.json
systemtest/estest/search.go
systemtest/instrumentation_test.go
systemtest/jaeger_test.go
systemtest/monitoring_test.go
systemtest/onboarding_test.go
systemtest/rum_test.go
systemtest/sampling_test.go

- systemtest: add test for RUM & X-Forwarded-For (#4208)

[7.x] systemtest: add test for RUM & X-Forwarded-For (#4208)

---

.ci/check-packages.groovy

Adds missing params which contains vars used in the packaging job.

[ci] Add params for packaging job

---

script/update_kibana_objects.py

Allow reusing an existing locally cloned repo, rather than cloning kibana into temp every time. Speeds up the update when you live in a faraway land. I have not attempted to make this perfect or fool proof, e.g. if the local branch exists, the script will fail.
Also, pass `--strict.perms=false` to the `apm-server` command to avoid warnings on a clean checkout where `apm-server.yml` has mode 0660.
~- [ ] metrics and monitoring (create issue for Kibana team to add metrics to visualizations, e.g. [Kibana#44001](https://github.com/elastic/kibana/issues/44001)) …

scripts/update_kibana_objects.py: enable reusing existing kibana checkout

---

script/update_kibana_objects.py

- Add update_kibana_objects options to reuse clone (#4243)

[7.x] Add update_kibana_objects options to reuse clone (#4243)

---

x-pack/apm-server/sampling/eventstorage/storage_test.go

- sampling/eventstorage: fix flaky test (#4255)

[7.x] sampling/eventstorage: fix flaky test (#4255)

---

docs/data/elasticsearch/generated/errors.json
docs/data/elasticsearch/generated/transactions.json
systemtest/approvals/TestRUMXForwardedFor.approved.json
tests/system/drop_unsampled_transactions.approved.json
tests/system/error.approved.json
tests/system/keep_unsampled_transactions.approved.json
tests/system/transaction.approved.json

- Update to elastic/beats@ef6274d0d1e3 (#4249)

[7.x] Update to elastic/beats@ef6274d0d1e3 (#4249)

---

model/modeldecoder/modeldecodertest/populator.go
model/modeldecoder/modeldecodertest/stream_decoder.go
model/modeldecoder/modeldecodertest/testdata.go
model/modeldecoder/rumv3/metadata_test.go
model/modeldecoder/rumv3/model_test.go
model/modeldecoder/rumv3/transaction_test.go
model/modeldecoder/v2/decoder.go
model/modeldecoder/v2/metadata_test.go
model/modeldecoder/v2/model.go
model/modeldecoder/v2/model_generated.go
model/modeldecoder/v2/model_test.go
model/modeldecoder/v2/transaction_test.go

[7.x] Decoder v2 tests (#4259)

---

Jenkinsfile

[CI] GH comment fix for hey-apm and package testing

---

.backportrc.json

update versions to backport

---

CHANGELOG.asciidoc
changelogs/7.10.asciidoc
docs/release-notes.asciidoc

Forward-port 7.10 changelog to 7.x (#4276)

---

changelogs/head.asciidoc

Reset head changelog

---

NOTICE.txt
go.mod
go.sum

update elasticsearch client versions

---

docs/guide/obs-integrations.asciidoc

- Merge pull request #4288 from EamonnTP/update-logs-link (#4288)

[7.10] Merge pull request #4288 from EamonnTP/update-logs-link (#4288)

---

docs/guide/obs-integrations.asciidoc

- Merge pull request #4288 from EamonnTP/update-logs-link (#4288)

[7.x] Merge pull request #4288 from EamonnTP/update-logs-link (#4288)

---

NOTICE.txt
docs/fields.asciidoc
go.mod
go.sum
testing/environments/docker/kafka/Dockerfile
testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

* Update to latest changes for `7.9.3`
* Updating snapshots
~- [ ] metrics and monitoring (create issue for Kibana team to add metrics to visualizations, e.g. [Kibana#44001]~(https://github.com/elastic/kibana/issues/44001)) …

[7.9] Update beats framework to e8f1cef65256

---

Jenkinsfile

Branches and tags will run all the stages even when the merged changes are only related to docs

[CI] run everything for branches/tags

---

NOTICE.txt
go.mod
go.sum

Update beats to bring in new `libbeat/logp.Logger.WithOptions` method.
`make test`
None.

Update to elastic/beats@9ab0a9182373

---

Jenkinsfile

- [CI] run everything for branches/tags (#4308)

[7.x] [CI] run everything for branches/tags (#4308)

---

Jenkinsfile

- [CI] run everything for branches/tags (#4308)

[7.10] [CI] run everything for branches/tags (#4308)

---

docs/spec/spans/span.json
model/span/generated/schema/span.go

Add missing type information to `span.context.service` in JSON schema.  …

fix: add type information to span.context.service

---

beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
model/modeldecoder/generator/cmd/main.go
model/modeldecoder/generator/map.go
model/modeldecoder/modeldecodertest/populator.go
model/modeldecoder/modeldecodertest/testdata.go
model/modeldecoder/v2/decoder.go
model/modeldecoder/v2/metricset_test.go
model/modeldecoder/v2/model.go
model/modeldecoder/v2/model_generated.go
model/modeldecoder/v2/model_test.go
processor/stream/processor.go
testdata/intake-v2/minimal.ndjson

This PR adds and enables the updated modeldecoder for v2 metricsets. 
sending valid and invalid metricset docs against APM Server v2 backend + RUM and observing behavior …

decoder v2: add metricset

---

beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
model/modeldecoder/generator/cmd/main.go
model/modeldecoder/generator/map.go
model/modeldecoder/modeldecodertest/populator.go
model/modeldecoder/modeldecodertest/testdata.go
model/modeldecoder/v2/decoder.go
model/modeldecoder/v2/metricset_test.go
model/modeldecoder/v2/model.go
model/modeldecoder/v2/model_generated.go
model/modeldecoder/v2/model_test.go
processor/stream/processor.go
testdata/intake-v2/minimal.ndjson

- decoder v2: add metricset (#4333)

[7.x] decoder v2: add metricset (#4333)

---

changelogs/6.8.asciidoc

[6.8] docs: 6.8.13 release notes

---

beater/api/profile/handler.go
docs/spec/errors/rum_v3_error.json
docs/spec/spans/rum_v3_span.json
model/error/generated/schema/rum_v3_error.go
model/modeldecoder/generator/cmd/main.go
model/modeldecoder/modeldecoder.go
model/modeldecoder/rumv3/decoder.go
model/modeldecoder/rumv3/error_test.go
model/modeldecoder/rumv3/metadata_test.go
model/modeldecoder/rumv3/metricset_test.go
model/modeldecoder/rumv3/model.go
model/modeldecoder/rumv3/model_generated.go
model/modeldecoder/rumv3/model_test.go
model/modeldecoder/rumv3/transaction_test.go
model/modeldecoder/v2/decoder.go
model/modeldecoder/v2/model_test.go
model/span/generated/schema/rum_v3_span.go
model/transaction/generated/schema/rum_v3_transaction.go
processor/stream/processor.go
processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json

- Decoder rumv3 errors (#4358)

[7.x] Decoder rumv3 errors (#4358)

---

NOTICE.txt
go.mod
go.sum

Update to elastic/beats@633285e75a03

Update to elastic/beats@633285e75a03

---

systemtest/approvals/TestServiceDestinationAggregation.approved.json
tests/system/jaeger_batch_0.approved.json
x-pack/apm-server/aggregation/spanmetrics/aggregator.go
x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go

Add agent name to span/edge metrics.

---

Jenkinsfile

* Trigger package stage on master and release branches
* Trigger package stage on PRs that updates libbeat
* Trigger package stage on PRS when there is a comment like `jenkins run package tests`

fix: correct package stage when condition

---

Jenkinsfile

- fix: correct package stage when condition (#4398)

[7.10] fix: correct package stage when condition (#4398)

---

Jenkinsfile

- fix: correct package stage when condition (#4398)

[7.x] fix: correct package stage when condition (#4398)

---

Jenkinsfile

- Use commit id and pr subfolder in the bucket (#4400)

[7.x] Use commit id and pr subfolder in the bucket (#4400)

---

Jenkinsfile

- Use commit id and pr subfolder in the bucket (#4400)

[7.10] Use commit id and pr subfolder in the bucket (#4400)

---

Jenkinsfile

It backports some environment variables not defined in the 7.10 pipeline, this causes the following error in the CI
```
[2020-11-11T11:41:09.684Z] [INFO] getVaultSecret: Getting secrets
httpRequest: Failure connecting to the service https://secrets.elastic.co:8200/v1/null : httpRequest: Failure connecting to the service https://secrets.elastic.co:8200/v1/null : 
Code: 403
Error: {"errors":["1 error occurred:\n\t* permission denied\n\n"]}
```

ci: backport undefined variables

---

.ci/check-packages.groovy

Unfortunately the original PR didn't validate this particular pipeline, so that's the reason it was not detected in the CI previously

[CI] fix missing script closure

---

.ci/check-packages.groovy
.ci/jobs/apm-server-check-packages-mbp.yml
Jenkinsfile
Makefile

- Support check packages for release and master branches (#4401)
- [CI] fix missing script closure (#4423)

[7.x] Support check packages for release and master branches (#4401)(#4423)

---

.ci/check-packages.groovy
.ci/jobs/apm-server-check-packages-mbp.yml
Jenkinsfile
Makefile

- Support check packages for release and master branches (#4401)
- [CI] fix missing script closure (#4423)

[7.10] Support check packages for release and master branches (#4401)(#4423)

---

NOTICE.txt
beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
go.mod
go.sum
testing/environments/snapshot-oss.yml
testing/environments/snapshot.yml

Pull in latest libbeat commit, to upgrade libbeat version to `7.10.1`

beats update: upgrade to version 7.10.1

---

beater/beater.go

- Add initial support for beats central management (#4228)

[7.x] Add initial support for beats central management (#4228)

---

NOTICE.txt
beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
cmd/version.go
go.mod
go.sum
testing/environments/latest.yml

- Update to beats `7.10` branch
- Update APM Server version to `7.10.2`
- Update approval tests

Bump version to 7.10.2

---

beater/config/config_test.go
beater/config/sampling.go
systemtest/apmservertest/config.go
systemtest/sampling_test.go
x-pack/apm-server/main.go
x-pack/apm-server/sampling/config.go
x-pack/apm-server/sampling/config_test.go
x-pack/apm-server/sampling/groups.go
x-pack/apm-server/sampling/groups_test.go
x-pack/apm-server/sampling/processor.go
x-pack/apm-server/sampling/processor_test.go

- sampling: introduce policies (#4320)

[7.x] sampling: introduce policies (#4320)

---

apmpackage/README.md
apmpackage/apm/0.1.0/docs/README.md
apmpackage/docs/README.template.md

Includes developer docs and another iteration of user facing docs before handing them to the professionals.
#4494

Package documentation

---

approvaltest/approvals.go
beater/beater.go
beater/config/config.go
beater/config/data_streams_test.go
idxmgmt/datastreams.go
idxmgmt/supporter.go
idxmgmt/supporter_factory.go
idxmgmt/supporter_factory_test.go
systemtest/apmservertest/config.go
systemtest/apmservertest/filter.go
systemtest/approvals/TestDataStreamsEnabled/false.approved.json
systemtest/approvals/TestDataStreamsEnabled/true.approved.json
systemtest/datastreams_test.go
systemtest/elasticsearch.go
systemtest/estest/search.go
tests/system/apmserver.py
tests/system/test_pipelines.py

- Data streams improvements (#4449)

[7.x] Data streams improvements (#4449)

---

apmpackage/README.md
apmpackage/apm/0.1.0/docs/README.md
apmpackage/docs/README.template.md

- Package documentation (#4499)

[7.x] Package documentation (#4499)

---

_meta/beat.yml
apm-server.docker.yml
apm-server.yml

fix:accidentially removed a logger config line

[7.x] fix:accidentially removed a logger config line

---

NOTICE.txt
go.mod
go.sum

Update to beats commit 5a813648879f

Update to elastic/beats@5a813648879f

---

apmpackage/cmd/gen-package/main.go
cmd/version.go

bump version to 7.12

---

NOTICE.txt
go.mod
go.sum

Pull in beats version upgrade to `7.12` to be in sync again.

[7.x] Update to elastic/beats@4d1c891ebf75

---

Jenkinsfile

Run `package` tests on `7.x` (treat it the same as `master`).

Run package tests on 7.x branch

---

CONTRIBUTING.md
README.md
magefile.go

This PR updates APM Server's `README` and `CONTRIBUTING` files:
* Add link to Elastic Contributor Program
* Clarify code contributions
* Update example from 6.2 --> 7.10
* Grammar
Closes https://github.com/elastic/apm-server/issues/4404.

docs: update contributing

---

NOTICE.txt
go.mod
go.sum

Update the go-elasticsearch client dependencies to `7.10` and  `master`. 
There is no `7.11` branch yet, but there hasn't been any critical changes since `7.10` so this should be fine. 
no special testing required
none

Update go-elasticsearch client

---

CHANGELOG.asciidoc
changelogs/7.11.asciidoc

Changelog for `7.11` backporting https://github.com/elastic/apm-server/pull/4561

[7.x] Add changelog for 7.11

---

NOTICE.txt
_meta/beat.yml
apm-server.docker.yml
apm-server.yml
cmd/root.go
systemtest/export_test.go
tests/system/config/apm-server.yml.j2
tests/system/test_integration_acm.py
tests/system/test_jaeger.py

- Switch to JSON logging by default (#4590)

[7.11] Switch to JSON logging by default (#4590)

---

cmd/version.go

Bump version to 7.10.3

---

NOTICE.txt
go.mod
go.sum

See https://github.com/elastic/beats/pull/21705
Non-functional change, just run the tests.
None.

go.mod: use upstream badger

---

beater/beater.go
beater/tracing.go

When instrumentation is enabled and the the server is
configured to receive its own trace events, it starts a
`beater.traceServer`. To enable reloadable config we
need to support changing the `publish.Reporter` function
used by the `traceServer` at runtime, as the server may
be reconfigured in such a way as to alter event process.
e.g. namespace may be updated, or aggregation may be
enabled/disabled.
We update `traceServer` to send events to another
channel, and then separate running `traceServer` from
serving the event publication requests. Even when we
enable reloadable config there will be a single `traceServer`
running, but the `publish.Reporter` will be changed at
runtime.
Non-functional change, just run the tests.
Required for #4376

beater: refactor tracerServer

---

script/generate_notice.py

The build has a dependency checker that relies on the header being present.

write notice csv header row

---

changelogs/head.asciidoc

Fix placeholder changelog entry.

Fix changelog for Go update

---

apmpackage/apm/0.1.0/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
apmpackage/apm/0.1.0/data_stream/app_metrics/manifest.yml
model/metricset.go
model/metricset_test.go
processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
processor/stream/test_approved_es_documents/testIntakeIntegrationMinimalService.approved.json
processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json

Solves the issue described in https://github.com/elastic/kibana/issues/88307#issuecomment-770913428
While we could maybe find a way out with priority ordering, that would introduce unnecessary complexity. 
Happy to replace "user" with something more appropriate if there are better ideas. 
Wait for package 0.5.0 release

Rename dataset to avoid ambiguous index pattern generation

---

docs/guide/opentelemetry-elastic.asciidoc

Refresh documentation, bump Otel examples to otel-java-agent 0.15.0 and otel-collector-contrib 0.19.0
- [NA ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)
- [ x] Documentation has been updated
Documentation changes tested with https://github.com/cyrille-leclerc/my-shopping-cart/tree/otel-java-agent-0.15.0

Bump Otel examples to otel-java-agent 0.15.0 and otel-collector-contrib 0.19.0

---

cmd/version.go

bump version

---

NOTICE.txt
go.mod
go.sum

Bring https://github.com/elastic/beats/pull/23960

Update to elastic/beats@5475407dcdb0

---

apmpackage/apm/0.1.0/agent/input/template.yml.hbs
apmpackage/apm/0.1.0/docs/README.md
apmpackage/apm/0.1.0/manifest.yml
apmpackage/docs/README.template.md

- [apmpackage] Add config options supported in ESS (#4690)

[7.x] [apmpackage] Add config options supported in ESS (#4690)

---

docs/secure-communication-agents.asciidoc

This PR fixes a bad link that breaks the build.

[DOCS] Fixes URLs on Secure communication with APM Agents page

---

docs/secure-communication-agents.asciidoc

[7.9] docs: readds .NET link (#4764)

---

docs/secure-communication-agents.asciidoc

[7.8] docs: readds .NET link (#4764)

---

docs/secure-communication-agents.asciidoc

[7.7] docs: readds .NET link (#4764)

---

docs/secure-communication-agents.asciidoc

[7.6] docs: readds .NET link (#4764)

---

docs/secure-communication-agents.asciidoc

[7.5] docs: readds .NET link (#4764)

---

docs/secure-communication-agents.asciidoc

[7.4] docs: readds .NET link (#4764)

---

docs/secure-communication-agents.asciidoc

[7.3] docs: readds .NET link (#4764)

---

beater/beater.go
beater/tracing.go

- beater: refactor tracerServer (#4628)

[7.x] beater: refactor tracerServer (#4628)

---

apmpackage/apm/0.1.0/data_stream/app_metrics/elasticsearch/ilm/default_policy.json
apmpackage/apm/0.1.0/data_stream/app_metrics/manifest.yml
apmpackage/apm/0.1.0/data_stream/error_logs/elasticsearch/ilm/default_policy.json
apmpackage/apm/0.1.0/data_stream/error_logs/manifest.yml
apmpackage/apm/0.1.0/data_stream/internal_metrics/elasticsearch/ilm/default_policy.json
apmpackage/apm/0.1.0/data_stream/internal_metrics/manifest.yml
apmpackage/apm/0.1.0/data_stream/profile_metrics/elasticsearch/ilm/default_policy.json
apmpackage/apm/0.1.0/data_stream/profile_metrics/manifest.yml
apmpackage/apm/0.1.0/data_stream/traces/elasticsearch/ilm/default_policy.json
apmpackage/apm/0.1.0/data_stream/traces/manifest.yml

- add ilm policiy to apm data streams (#4620)

[7.x] add ilm policiy to apm data streams (#4620)

---

apmpackage/cmd/gen-package/main.go
cmd/version.go

[7.x] bump 7.x version

---

apmpackage/apm/0.1.0/_dev/docs/README.template.md
apmpackage/apm/0.1.0/docs/README.md
apmpackage/apm/0.1.0/img/logo_apm.svg
apmpackage/apm/0.1.0/manifest.yml

- Add package settings and icon (#4542)

[7.x] Add package settings and icon (#4542)

---

processor/otel/consumer_test.go

- processor/otel: add unit test for span status (#4734)

[7.x] processor/otel: add unit test for span status (#4734)

---

processor/otel/consumer_test.go

- processor/otel: add unit test for span status (#4734)

[7.12] processor/otel: add unit test for span status (#4734)

---

docs/secure-communication-agents.asciidoc
docs/version.asciidoc

[7.2] Update documentation links to .NET agent #4871

---

docs/version.asciidoc

[7.1] Update documentation links to .NET agent #4871 

---

docs/version.asciidoc

[7.0] Update documentation links to .NET agent #4871 

---

processor/otel/consumer_test.go

- processor/otel: test service.version handling (#4853)

[7.x] processor/otel: test service.version handling (#4853)

---

systemtest/containers.go

Fix enrollment due to https://github.com/elastic/beats/pull/24220
Run the system tests.
None.

systemtest: fix Elastic Agent enrollment

---

apmpackage/apm/0.1.0/_dev/docs/README.template.md
apmpackage/apm/0.1.0/changelog.yml
apmpackage/apm/0.1.0/docs/README.md
apmpackage/apm/0.1.0/manifest.yml

- Minor updates to package (#4841)

[7.x] Minor updates to package (#4841)

---

apmpackage/apm/0.1.0/_dev/docs/README.template.md
apmpackage/apm/0.1.0/changelog.yml
apmpackage/apm/0.1.0/docs/README.md
apmpackage/apm/0.1.0/manifest.yml

- Minor updates to package (#4841)

[7.12] Minor updates to package (#4841)

---

script/copy_package.py

Makes the script work 
Run `python copy_package.py`

Exclude png files from find command

---

NOTICE.txt
magefile.go
script/run_agent.sh

- Script for faster development workflow (#4731)

[7.x] Script for faster development workflow (#4731)

---

apmpackage/apm/0.1.0/manifest.yml

It will show up as `Elastic Stack`, more accurate than `Monitoring`.

Update packate category

---

NOTICE.txt
magefile.go
script/run_agent.sh

- Script for faster development workflow (#4731)

[7.12] Script for faster development workflow (#4731)

---

apmpackage/apm/0.1.0/manifest.yml

- Update packate category (#4908)

[7.12] Update packate category (#4908)

---

apmpackage/apm/0.1.0/manifest.yml

- Update packate category (#4908)

[7.x] Update packate category (#4908)

---

apmpackage/apm/0.1.0/manifest.yml

backports https://github.com/elastic/apm-server/pull/4931
--- 
fixes #https://github.com/elastic/package-storage/issues/1011

[7.x] [fleet] Fix apm package types

---

apmpackage/apm/0.1.0/manifest.yml

backports https://github.com/elastic/apm-server/pull/4931
--- 
fixes #https://github.com/elastic/package-storage/issues/1011

[7.12][fleet] Fix apm package types

---

NOTICE.txt
go.mod
go.sum
testing/environments/snapshot-oss.yml

Update to elastic/beats@21d02a3ab3b8

---

changelogs/head.asciidoc

Update the changelog for #4918

update changelog for #4918

---

apmpackage/apm/0.1.0/_dev/docs/README.template.md
apmpackage/apm/0.1.0/docs/README.md
docs/apm-package/apm-input-settings.asciidoc
docs/apm-package/apm-integration.asciidoc
docs/apm-package/data-streams.asciidoc
docs/apm-package/input-apm.asciidoc
docs/index.asciidoc

- docs: APM integration (#4928)

[7.x] docs: APM integration (#4928)

---

apmpackage/apm/0.1.0/_dev/docs/README.template.md
apmpackage/apm/0.1.0/docs/README.md
docs/apm-package/apm-input-settings.asciidoc
docs/apm-package/apm-integration.asciidoc
docs/apm-package/data-streams.asciidoc
docs/apm-package/input-apm.asciidoc
docs/index.asciidoc

- docs: APM integration (#4928)

[7.12] docs: APM integration (#4928)

---

docs/guide/apm-breaking-changes.asciidoc

For https://github.com/elastic/stack-docs/pull/1613.

[7.12] docs: Add include for stack-docs

---

idxmgmt/supporter_factory.go
idxmgmt/supporter_factory_test.go
systemtest/datastreams_test.go

- idxmgmt: fix config merging (#4950)

[7.x] idxmgmt: fix config merging (#4950)

---

idxmgmt/supporter_factory.go
idxmgmt/supporter_factory_test.go
systemtest/datastreams_test.go

- idxmgmt: fix config merging (#4950)

[7.11] idxmgmt: fix config merging (#4950)

---

CHANGELOG.asciidoc
changelogs/7.12.asciidoc
docs/breaking-changes.asciidoc
docs/guide/apm-breaking-changes.asciidoc
docs/release-notes.asciidoc

This PR backports #4858 and #4959.

[7.12] docs: 7.12 release notes

---

Jenkinsfile

Since there are ephemeral ARM workers then we can enable the stage on PR basis.

[CI] enable ARM builds on a PR basis

---

changelogs/6.8.asciidoc

[6.8] Add 6.8.15 release notes

---

model/batch.go
model/error.go
model/error_test.go
model/metricset.go
model/metricset_test.go
model/profile.go
model/profile_test.go
model/span.go
model/span_test.go
model/transaction.go
model/transaction_test.go

- model: append events on transformation (#4926)

[7.x] model: append events on transformation (#4926)

---

model/context.go
model/modeldecoder/rumv3/decoder.go
model/modeldecoder/rumv3/error_test.go
model/modeldecoder/rumv3/transaction_test.go
model/modeldecoder/v2/decoder.go
model/modeldecoder/v2/error_test.go
model/modeldecoder/v2/transaction_test.go
model/span.go
model/span_test.go
processor/otel/builder.go
processor/otel/consumer.go
processor/otel/consumer_test.go

- model: de-pointer several integer fields (#4924)

[7.x] model: de-pointer several integer fields (#4924)

---

script/copy_package.py

Do not copy the template file for the Readme

---

docs/configuring-ingest.asciidoc
docs/guide/data-security.asciidoc
docs/guide/features.asciidoc

- docs: data security, filtering, and obfuscation (#5068)

[7.12] docs: data security, filtering, and obfuscation (#5068)

---

docs/configuring-ingest.asciidoc
docs/guide/data-security.asciidoc
docs/guide/features.asciidoc

- docs: data security, filtering, and obfuscation (#5068)

[7.x] docs: data security, filtering, and obfuscation (#5068)

---

systemtest/containers.go

Enable TLS for fleet-server so it listens on non-loopback addresses.
This removes the need to set FLEET_SERVER_HOST and FLEET_SERVER_PORT.
Also, update the WaitingFor to wait for the fleet-server /api/status response to indicate the API status is "HEALTHY".
The server responds 200 OK when the status is either "HEALTHY" or "DEGRADED", the latter of which we don't want.
None.

systemtest: enable TLS for fleet-server

---

changelogs/7.12.asciidoc

Adds release notes for 7.12.1.
* Includes the Go upgrade from #5100

docs: add 7.12.1 release notes

---

.backportrc.json
.mergify.yml
CHANGELOG.asciidoc
changelogs/7.13.asciidoc
changelogs/head.asciidoc
docs/release-notes.asciidoc

Update backport files and changelog with 7.13 branch

---

.ci/bump-stack-version.sh

PR got merged but there was a typo so the automation cannot happen as expected

automation: use the right variable name

---

docker-compose.yml

Update docker images to 7.14-SNAPSHOT on the 7.x branch.

docker-compose: update images to 7.14 on 7.x

---

.mergify.yml

Since https://github.com/Mergifyio/mergify-engine/issues/2419 has been solved we can now change the title to use the target branch

[mergify] use variable for the target branch

---

.mergify.yml

- feat: add support for auto-backports (#4990)

[7.x] feat: add support for auto-backports (#4990)

---

.mergify.yml

- feat: add support for auto-backports (#4990)

[7.13] feat: add support for auto-backports (#4990)

---

.mergify.yml

- [mergify] run the check after the PR gets merged (#5055)

[7.13] [mergify] run the check after the PR gets merged (#5055)

---

.mergify.yml

- [mergify] run the check after the PR gets merged (#5055)

[7.x] [mergify] run the check after the PR gets merged (#5055)

---

.mergify.yml

Check that the name of "head" matches, rather than "base".

mergify: fix delete_head_branch condition

---

elasticsearch/backoff_test.go

`TestBackoff` has been using a hardcoded host of "localhost:9200", causing it to fail if elasticsearch is running locally. Update the test to use the httptest.Server's listening address. Note that the host in the URL passed to "Perform" is always ignored, and replaced with the host(s) in the configured Elasticsearch transport/client.
N/A
None.

elasticsearch: fix TestBackoff

---

NOTICE.txt
cmd/version.go
go.mod
go.sum

[7.13] Update to 7.13.1

---

docs/guide/agent-server-compatibility.asciidoc

- Fixing broken box for RUM (#5295)

[master] Fixing broken box for RUM (#5295)

---

changelogs/7.13.asciidoc
changelogs/head.asciidoc

This PR adds release notes for 7.13.1. Please double-check to ensure I picked the right commits. https://github.com/elastic/apm-server/commits/7.13

docs: 7.13.1 release notes

---

NOTICE.txt
changelogs/7.13.asciidoc
cmd/version.go
go.mod
go.sum

7.13.1 update

---

changelogs/7.13.asciidoc

7.13.2 release notes. No significant changes.

docs: 7.13.2 release notes

---

systemtest/approvals/TestNoMatchingSourcemap.approved.json
systemtest/approvals/TestRUMSpanSourcemapping.approved.json
systemtest/sourcemap_test.go

Update approvals to fix system tests.

systemtest: fix approvals

---

agentcfg/reporter.go
agentcfg/reporter_test.go

TestReportFetch is intermittently failing due to multiple applied agent config metrics batches being processed concurrently, leading to the order being non-deterministic. Check the etag values without requiring them to be in a specific order.
While we're in the area, make sure goroutines have exited before Run returns.
Non-functional change. Reproduce with `go test -v -failfast -count=100 -run TestReportFetch`
None

agentcfg: fix flaky test

---

sourcemap/store_test.go

it's flaky and will be addressed in a separate
issue
Non-functional change
Issue to re-enable test https://github.com/elastic/apm-server/issues/5571

disable TestFetchTimeout

---

docs/secure-communication-agents.asciidoc

- Update secure-communication-agents.asciidoc (#5379)

[7.13] Update secure-communication-agents.asciidoc (#5379)
