elastic/apm-server

docker-compose.yml
[start_time:Mon, 29 Nov 2021 17:25:42 GMT, release_branch:7.15, prefix:, end_time:Mon, 29 Nov 2021 23:15:32 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-c7a19acd, build_duration_seconds:20990]
=> [automation] update elastic stack version for testing 7.15.3-c7a19acd

docker-compose.yml
[start_time:Mon, 29 Nov 2021 00:25:10 GMT, release_branch:master, prefix:, end_time:Mon, 29 Nov 2021 06:29:08 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-3e9afa2a, build_duration_seconds:21838]
=> [automation] update elastic stack version for testing 8.1.0-3e9afa2a

docker-compose.yml
[start_time:Mon, 29 Nov 2021 00:18:49 GMT, release_branch:8.0, prefix:, end_time:Mon, 29 Nov 2021 12:48:33 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-5dc82a0c, build_duration_seconds:44984]
=> [automation] update elastic stack version for testing 8.0.0-5dc82a0c

apmpackage/apm/data_stream/rum_traces/manifest.yml
Fixes a bug where the RUM traces data stream was referencing the wrong
ILM policy, causing the RUM index to reference an invalid ILM policy.
1. `docker-compose up -d`
2. `make`
3. `./apm-server -E output.elasticsearch.username=admin -E output.elasticsearch.password=changeme -E apm-server.rum.enabled=true -e`
4. Install the APM Integration via Kibana (8.1.0)
5. ` curl -H "Content-type: application/x-ndjson" --data-binary @testdata/intake-v2/transactions.ndjson …
=> apmpackage: Fix rum traces ILM name

docker-compose.yml
[start_time:Tue, 30 Nov 2021 05:15:42 GMT, release_branch:7.16, prefix:, end_time:Tue, 30 Nov 2021 11:21:10 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-046aeba5, build_duration_seconds:21928]
=> [automation] update elastic stack version for testing 7.16.0-046aeba5

docker-compose.yml
[start_time:Tue, 30 Nov 2021 00:16:15 GMT, release_branch:8.0, prefix:, end_time:Tue, 30 Nov 2021 06:28:18 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-df873dde, build_duration_seconds:22323]
=> [automation] update elastic stack version for testing 8.0.0-df873dde

docker-compose.yml
[start_time:Tue, 30 Nov 2021 12:24:19 GMT, release_branch:master, prefix:, end_time:Tue, 30 Nov 2021 18:26:10 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-274c36a2, build_duration_seconds:21711]
=> [automation] update elastic stack version for testing 8.1.0-274c36a2

.mergify.yml
It changes merge action to queue in .mergify.yml
The configuration uses the deprecated strict mode of the merge action.
A brownout is planned for the whole December 6th, 2021 day.
This option will be removed on January 10th, 2022.
For more information: https://blog.mergify.io/strict-mode-deprecation/
=> changed .mergify.yml to use queue instead of merge actions

docker-compose.yml
[start_time:Wed, 1 Dec 2021 00:15:51 GMT, release_branch:8.0, prefix:, end_time:Wed, 1 Dec 2021 06:31:58 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-aab6301c, build_duration_seconds:22567]
=> [automation] update elastic stack version for testing 8.0.0-aab6301c

docker-compose.yml
[start_time:Wed, 1 Dec 2021 05:14:21 GMT, release_branch:7.16, prefix:, end_time:Wed, 1 Dec 2021 10:51:15 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-80ab1dd0, build_duration_seconds:20214]
=> [automation] update elastic stack version for testing 7.16.0-80ab1dd0

apmpackage/apm/agent/input/template.yml.hbs, apmpackage/apm/changelog.yml, apmpackage/apm/manifest.yml
- support setting the java agent download version field
- fix the config value for `discover-rules`
=> Java attacher update integration

systemtest/apmservertest/config.go, systemtest/estest/search.go
Removes `setup` and `queue` settings from the `systemtest` config since
they've been removed and have no effect on the APM Server.
N/A
None
=> systemtest: Remove setup and output config

docker-compose.yml
[start_time:Thu, 2 Dec 2021 05:17:48 GMT, release_branch:7.16, prefix:, end_time:Thu, 2 Dec 2021 15:02:31 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-f17274e7, build_duration_seconds:35083]
=> [automation] update elastic stack version for testing 7.16.0-f17274e7

docker-compose.yml
[start_time:Thu, 2 Dec 2021 17:23:07 GMT, release_branch:7.15, prefix:, end_time:Thu, 2 Dec 2021 23:29:35 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-2191b0f7, build_duration_seconds:21988]
=> [automation] update elastic stack version for testing 7.15.3-2191b0f7

docker-compose.yml
[start_time:Thu, 2 Dec 2021 00:26:19 GMT, release_branch:8.0, prefix:, end_time:Thu, 2 Dec 2021 15:39:08 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-eda77a0f, build_duration_seconds:54769]
=> [automation] update elastic stack version for testing 8.0.0-eda77a0f

docker-compose.yml
[start_time:Thu, 2 Dec 2021 00:23:46 GMT, release_branch:master, prefix:, end_time:Fri, 3 Dec 2021 02:37:14 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-58719e16, build_duration_seconds:94408]
=> [automation] update elastic stack version for testing 8.1.0-58719e16

docker-compose.yml
[start_time:Sun, 5 Dec 2021 05:14:11 GMT, release_branch:7.16, prefix:, end_time:Sun, 5 Dec 2021 11:24:06 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-ef210289, build_duration_seconds:22195]
=> [automation] update elastic stack version for testing 7.16.0-ef210289

docker-compose.yml
[start_time:Sun, 5 Dec 2021 12:17:20 GMT, release_branch:master, prefix:, end_time:Sun, 5 Dec 2021 18:25:37 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-30a394f1, build_duration_seconds:22097]
=> [automation] update elastic stack version for testing 8.1.0-30a394f1

docker-compose.yml
[start_time:Sun, 5 Dec 2021 17:25:40 GMT, release_branch:7.15, prefix:, end_time:Sun, 5 Dec 2021 23:29:23 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-70c2e21f, build_duration_seconds:21823]
=> [automation] update elastic stack version for testing 7.15.3-70c2e21f

docs/legacy/sourcemap-api.asciidoc
Cherry-pick of https://github.com/elastic/apm-server/commit/c6c6088f30b96ec4b3950c65661686a76bdb203b.
=> [8.0][docs] Update RUM source map absolute path logic (#6786) (forward-port)

docs/legacy/sourcemap-api.asciidoc
Cherry-pick of https://github.com/elastic/apm-server/commit/c6c6088f30b96ec4b3950c65661686a76bdb203b.
=> [7.16][docs] Update RUM source map absolute path logic (#6786) (forward-port)

docker-compose.yml
[start_time:Mon, 6 Dec 2021 17:23:14 GMT, release_branch:7.15, prefix:, end_time:Mon, 6 Dec 2021 23:34:19 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-9e171938, build_duration_seconds:22265]
=> [automation] update elastic stack version for testing 7.15.3-9e171938

.ci/scripts/linux-test.sh, Makefile
- Increase the timeout for the system tests to 20 minutes (hardcoded)
- Introduce a `make system-test` target which runs the system tests
- Add an overrideable GOTESTFLAGS var to Makefile, used by `make test` and `make system-test`
- Update CI script to use the new target/var
Closes https://github.com/elastic/apm-server/issues/6811
=> Increase system tests timeout

systemtest/otlp_test.go
This test fails occasionally in CI, and I can reproduce the failure by running the test locally in a loop with `-race`. The issue is that the rate limit may be replenished before the third IP sends events, hence there is no error.
I've changed the test to be less specific: rather than checking what happens when the IP limit is reached, just check that rate limiting works generally with OTLP. Unit tests can cover more specific scenarios.
=> systemtest: fix TestOTLPRateLimit

docker-compose.yml
[start_time:Mon, 6 Dec 2021 05:13:18 GMT, release_branch:7.16, prefix:, end_time:Mon, 6 Dec 2021 11:12:15 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-f2941f42, build_duration_seconds:21537]
=> [automation] update elastic stack version for testing 7.16.0-f2941f42

beater/beater_test.go, beater/integration_test.go
- Speed up TestPublishIntegration tests, which were each waiting for
one second to gather events. Instead, we now decode the HTTP response
body to identify the number of events received; and then we wait for
that many events to be published.
- Tidy up the monitoring registry in TestQueryClusterUUID* tests, so
they can be run multiple times (i.e. with `go test -count=N`)
=> beater: improve tests

docker-compose.yml
[start_time:Tue, 7 Dec 2021 05:13:29 GMT, release_branch:7.16, prefix:, end_time:Tue, 7 Dec 2021 11:04:54 GMT, manifest_version:2.0.0, version:7.16.0-SNAPSHOT, branch:7.16, build_id:7.16.0-eaf40d57, build_duration_seconds:21085]
=> [automation] update elastic stack version for testing 7.16.0-eaf40d57

docker-compose.yml
[start_time:Tue, 7 Dec 2021 00:18:38 GMT, release_branch:8.0, prefix:, end_time:Tue, 7 Dec 2021 07:18:23 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-4535d287, build_duration_seconds:25185]
=> [automation] update elastic stack version for testing 8.0.0-4535d287

docker-compose.yml
[start_time:Tue, 7 Dec 2021 17:14:23 GMT, release_branch:7.15, prefix:, end_time:Tue, 7 Dec 2021 23:18:27 GMT, manifest_version:2.0.0, version:7.15.3-SNAPSHOT, branch:7.15, build_id:7.15.3-984b6e42, build_duration_seconds:21844]
=> [automation] update elastic stack version for testing 7.15.3-984b6e42

docker-compose.yml
[start_time:Wed, 8 Dec 2021 05:15:14 GMT, release_branch:7.16, prefix:, end_time:Wed, 8 Dec 2021 11:17:04 GMT, manifest_version:2.0.0, version:7.16.1-SNAPSHOT, branch:7.16, build_id:7.16.1-53c0de77, build_duration_seconds:21710]
=> [automation] update elastic stack version for testing 7.16.1-53c0de77

docker-compose.yml
[start_time:Thu, 9 Dec 2021 21:39:50 GMT, release_branch:7.16, prefix:, end_time:Fri, 10 Dec 2021 03:52:15 GMT, manifest_version:2.0.0, version:7.16.1-SNAPSHOT, branch:7.16, build_id:7.16.1-1d21f78b, build_duration_seconds:22345]
=> [automation] update elastic stack version for testing 7.16.1-1d21f78b

docker-compose.yml
[start_time:Thu, 9 Dec 2021 00:18:45 GMT, release_branch:master, prefix:, end_time:Thu, 9 Dec 2021 06:58:58 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-3cacb07d, build_duration_seconds:24013]
=> [automation] update elastic stack version for testing 8.1.0-3cacb07d

docker-compose.yml
[start_time:Thu, 9 Dec 2021 00:20:55 GMT, release_branch:8.0, prefix:, end_time:Thu, 9 Dec 2021 06:27:24 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-a8855495, build_duration_seconds:21989]
=> [automation] update elastic stack version for testing 8.0.0-a8855495

docker-compose.yml
[start_time:Fri, 10 Dec 2021 00:13:56 GMT, release_branch:8.0, prefix:, end_time:Fri, 10 Dec 2021 06:36:30 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-3c6e08ba, build_duration_seconds:22954]
=> [automation] update elastic stack version for testing 8.0.0-3c6e08ba

docker-compose.yml
[start_time:Fri, 10 Dec 2021 05:22:27 GMT, release_branch:7.16, prefix:, end_time:Fri, 10 Dec 2021 10:59:40 GMT, manifest_version:2.0.0, version:7.16.1-SNAPSHOT, branch:7.16, build_id:7.16.1-2ceb4af4, build_duration_seconds:20233]
=> [automation] update elastic stack version for testing 7.16.1-2ceb4af4

docker-compose.yml
[start_time:Fri, 10 Dec 2021 12:22:25 GMT, release_branch:master, prefix:, end_time:Fri, 10 Dec 2021 18:38:42 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-b6e7e1f3, build_duration_seconds:22577]
=> [automation] update elastic stack version for testing 8.1.0-b6e7e1f3

beater/config/java_attacher.go, beater/config/java_attacher_test.go, beater/java_attacher/java_attacher.go, beater/java_attacher/java_attacher_test.go
The bundled version of the java-attacher currently
uses -vmargs, but in the future will support
-vmarg. Externally accept -vmarg to remain
consisten, and convert it to -vmargs. When the
java-attacher version is upgraded, this conversion
can be removed.
Start apm-server using a java attacher config that includes `--include-vmarg`, and `log.level: debug`. Verify that the java-attacher starts, and that the debug output showing the command line executed has `--include-vmargs`.
Verify that the server complains when started with `--include-vmargs`.
=> [java-attacher] convert -vmarg to -vmargs

docker-compose.yml
[start_time:Mon, 13 Dec 2021 22:47:27 GMT, release_branch:7.16, prefix:, end_time:Tue, 14 Dec 2021 04:27:25 GMT, manifest_version:2.0.0, version:7.16.2-SNAPSHOT, branch:7.16, build_id:7.16.2-926bc45c, build_duration_seconds:20398]
=> [automation] update elastic stack version for testing 7.16.2-926bc45c

docker-compose.yml
[start_time:Tue, 14 Dec 2021 12:13:51 GMT, release_branch:master, prefix:, end_time:Tue, 14 Dec 2021 18:15:57 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-f02e597e, build_duration_seconds:21726]
=> [automation] update elastic stack version for testing 8.1.0-f02e597e

docker-compose.yml
[start_time:Tue, 14 Dec 2021 00:14:28 GMT, release_branch:8.0, prefix:, end_time:Tue, 14 Dec 2021 06:39:25 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-6b5f794c, build_duration_seconds:23097]
=> [automation] update elastic stack version for testing 8.0.0-6b5f794c

docker-compose.yml
[start_time:Wed, 15 Dec 2021 21:46:17 GMT, release_branch:7.16, prefix:, end_time:Thu, 16 Dec 2021 03:55:02 GMT, manifest_version:2.0.0, version:7.16.2-SNAPSHOT, branch:7.16, build_id:7.16.2-e7a873d4, build_duration_seconds:22125]
=> [automation] update elastic stack version for testing 7.16.2-e7a873d4

docker-compose.yml
[start_time:Wed, 15 Dec 2021 00:16:46 GMT, release_branch:8.0, prefix:, end_time:Wed, 15 Dec 2021 06:47:06 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-9fb1bbae, build_duration_seconds:23420]
=> [automation] update elastic stack version for testing 8.0.0-9fb1bbae

docker-compose.yml
[start_time:Fri, 17 Dec 2021 00:14:40 GMT, release_branch:master, prefix:, end_time:Fri, 17 Dec 2021 06:44:14 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-befff95a, build_duration_seconds:23374]
=> [automation] update elastic stack version for testing 8.1.0-befff95a

docker-compose.yml
[start_time:Sat, 18 Dec 2021 00:15:52 GMT, release_branch:8.0, prefix:, end_time:Sat, 18 Dec 2021 06:05:50 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-002bf944, build_duration_seconds:20998]
=> [automation] update elastic stack version for testing 8.0.0-002bf944

docker-compose.yml
[start_time:Thu, 16 Dec 2021 05:13:19 GMT, release_branch:7.16, prefix:, end_time:Thu, 16 Dec 2021 10:49:50 GMT, manifest_version:2.0.0, version:7.16.2-SNAPSHOT, branch:7.16, build_id:7.16.2-682993ae, build_duration_seconds:20191]
=> [automation] update elastic stack version for testing 7.16.2-682993ae

changelogs/6.8.asciidoc, changelogs/7.16.asciidoc
7.16.2 and 6.8.22 were released today. Release notes were published to the 7.16 and 6.8 branches in https://github.com/elastic/apm-server/commit/449fbe37aee7c35079b236713c4ee6c51af4cc7d and https://github.com/elastic/apm-server/commit/0de688a74ad046d717acce10742d7c5fb0dd5833, respectively. This PR cherry-picks the changes to master for backporting.
~- [ ] There's no backport label for 7.17 yet, so this needs to be manually backported to that branch~
=> Cherry pick release notes

docker-compose.yml
[start_time:Mon, 20 Dec 2021 00:16:05 GMT, release_branch:8.0, prefix:, end_time:Mon, 20 Dec 2021 06:16:43 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-7b79b556, build_duration_seconds:21638]
=> [automation] update elastic stack version for testing 8.0.0-7b79b556

.ci/check-packages.groovy
https://github.com/elastic/beats-tester has switched to `main` branch. APM Server needs to update dependencies accordingly.
=> Update to main branch when using beats-tester

Makefile, docker-compose.yml
Updates branches to point ot beats `7.17` and updates the Docker compose
images.
=> [7.17] Fix CI build

docker-compose.yml
[start_time:Wed, 22 Dec 2021 00:13:31 GMT, release_branch:7.17, prefix:, end_time:Wed, 22 Dec 2021 05:48:01 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-e76712ab, build_duration_seconds:20070]
=> [automation] update elastic stack version for testing 7.17.0-e76712ab

docker-compose.yml
[start_time:Wed, 22 Dec 2021 12:15:30 GMT, release_branch:master, prefix:, end_time:Wed, 22 Dec 2021 18:06:40 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-76902d39, build_duration_seconds:21070]
=> [automation] update elastic stack version for testing 8.1.0-76902d39

docker-compose.yml
[start_time:Wed, 22 Dec 2021 00:19:48 GMT, release_branch:8.0, prefix:, end_time:Wed, 22 Dec 2021 13:21:20 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-52f8db06, build_duration_seconds:46892]
=> [automation] update elastic stack version for testing 8.0.0-52f8db06

docker-compose.yml
[start_time:Thu, 23 Dec 2021 00:16:24 GMT, release_branch:master, prefix:, end_time:Thu, 23 Dec 2021 06:11:38 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-dbc834fd, build_duration_seconds:21314]
=> [automation] update elastic stack version for testing 8.1.0-dbc834fd

docker-compose.yml
[start_time:Mon, 27 Dec 2021 00:15:34 GMT, release_branch:7.17, prefix:, end_time:Mon, 27 Dec 2021 05:53:19 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-09b71949, build_duration_seconds:20265]
=> [automation] update elastic stack version for testing 7.17.0-09b71949

.ci/scripts/linux-test.sh
Downloads all the systemtest modules before running the tests so the
download time doesn't count towards the systemtest test timeout.
N/A
N/A
=> ci: Run `go mod download` before systemtest

docker-compose.yml
[start_time:Tue, 28 Dec 2021 00:16:29 GMT, release_branch:7.17, prefix:, end_time:Tue, 28 Dec 2021 05:50:52 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-c02e8773, build_duration_seconds:20063]
=> [automation] update elastic stack version for testing 7.17.0-c02e8773

Makefile, beater/java_attacher/java_attacher.go, beater/java_attacher/java_attacher_test.go
Remove internal conversion to `vmargs` when constructing java-attacher command
1. download the java-attacher and place it alongside the apm-server binary
```
make build/apm-agent-attach-cli-1.28.3-slim.jar
cp build/java-attacher.jar .
```
2. add the following to `apm-server.yml` nested under `apm-server`
```
java_attacher:
enabled: true
download-agent-version: 1.28.3
discovery-rules:
- include-vmarg: "elastic.apm.attach=true"
- include-main: opbeans
- exclude-main: ".*"
config:
server_url: "http://localhost:8200"
```
3. start apm-server: `./apm-server -e -E logging.level=debug`
4. check for the debug output with the constructed java-attacher commandline invocation:
```
starting java attacher with command: /bin/java -jar ./java-attacher.jar --continuous --log-level debug …
```
=> Java attacher remove vmarg conversion

docker-compose.yml
[start_time:Wed, 29 Dec 2021 00:13:14 GMT, release_branch:7.17, prefix:, end_time:Wed, 29 Dec 2021 06:07:26 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-a34e30fc, build_duration_seconds:21252]
=> [automation] update elastic stack version for testing 7.17.0-a34e30fc

docker-compose.yml
[start_time:Thu, 30 Dec 2021 00:15:51 GMT, release_branch:7.17, prefix:, end_time:Thu, 30 Dec 2021 06:54:12 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-53d9a9d2, build_duration_seconds:23901]
=> [automation] update elastic stack version for testing 7.17.0-53d9a9d2

.mergify.yml
Adds the missing configuration for the `backport-7.17` label to work.
=> mergify: Add `backport-7.17` config

docker-compose.yml
[start_time:Sun, 2 Jan 2022 00:19:17 GMT, release_branch:7.17, prefix:, end_time:Sun, 2 Jan 2022 06:12:12 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-343e3146, build_duration_seconds:21175]
=> [automation] update elastic stack version for testing 7.17.0-343e3146

docker-compose.yml
[start_time:Tue, 4 Jan 2022 00:13:01 GMT, release_branch:7.17, prefix:, end_time:Tue, 4 Jan 2022 05:47:31 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-b402b9a8, build_duration_seconds:20070]
=> [automation] update elastic stack version for testing 7.17.0-b402b9a8

docs/span-compression.asciidoc
Removes previously hard-coded links now that the Go Agent documentation includes span compression.
Closes https://github.com/elastic/observability-docs/issues/1285.
=> docs: update span compression links

docker-compose.yml
[start_time:Wed, 5 Jan 2022 00:16:11 GMT, release_branch:7.17, prefix:, end_time:Wed, 5 Jan 2022 05:34:33 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-32e424af, build_duration_seconds:19102]
=> [automation] update elastic stack version for testing 7.17.0-32e424af

beater/config/config.go, beater/config/config_test.go
Currently, an invalid java-attacher config prevents the server from starting up. Server operation should not depend on the java-attacher having a valid config. Log the error if it exists, and move along.
QUESTION:
Currently, this is being logged as an error. Do we want to use a different log level for this?
1. start `apm-server` with the following added to the config:
```yaml
apm-server:
java_attacher:
enabled: true
discovery-rules:
- disallowed-flag: opbeans
```
2. Check the error logs for a message about the invalid flag
3. The apm-server should not …
=> [java-attacher] invalid config fails open

docker-compose.yml
[start_time:Thu, 6 Jan 2022 00:13:28 GMT, release_branch:7.17, prefix:, end_time:Thu, 6 Jan 2022 06:26:58 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-fe65ce80, build_duration_seconds:22410]
=> [automation] update elastic stack version for testing 7.17.0-fe65ce80

systemtest/sampling_test.go
Skips the `TestTailSampling` systemtest until elastic/fleet-server#1048
is resolved.
N/A
See referenced issue.
=> systemtest: Skip `TestTailSampling` for now

.ci/jobs/apm-server-check-changelogs-mbp.yml, .ci/jobs/apm-server-check-packages-mbp.yml, .ci/jobs/apm-server-mbp.yml
`7.16` was in theory the last branch so we put in place some changes to simplify the regex. But `7.17` is now the next minor for the 7 line. Let's support `7.18` and so on just in case
Otherwise, the CI won't run builds for the 7.17 branch!
=> jjbb: enable 7.17 branch

docker-compose.yml
[start_time:Mon, 10 Jan 2022 00:13:26 GMT, release_branch:7.17, prefix:, end_time:Mon, 10 Jan 2022 06:09:18 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-9b8314f9, build_duration_seconds:21352]
=> [automation] update elastic stack version for testing 7.17.0-9b8314f9

docker-compose.yml
Updates the `proxy_dep` in `docker-compose.yml` to wait until the `fleet-server`
is healthy before exiting. This will most likely cause the
systemtest to fail less on `context.DeadlineExceeded` since the wait
won't count towards the systemtest timeout.
N/A
N/A
N/A
=> compose: Wait until `fleet-server` is healthy

Makefile
Update the patch-level version of the java
attacher for security updates.
closes https://github.com/elastic/apm-server/issues/6887
=> [java-attacher] update to v1.28.4

apmpackage/README.md
Follow up to https://github.com/elastic/apm-server/pull/7042: update localhost Kibana URL to use `http`, not `https`, and drop `-k` flag.
=> apmpackage: fix Kibana URL in README

docker-compose.yml
[start_time:Wed, 12 Jan 2022 00:13:17 GMT, release_branch:7.17, prefix:, end_time:Wed, 12 Jan 2022 05:46:31 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-049bcf23, build_duration_seconds:19994]
=> [automation] update elastic stack version for testing 7.17.0-049bcf23

docs/legacy/guide/opentelemetry-elastic.asciidoc, docs/open-telemetry.asciidoc
Update OpenTelemetry limitations with a link to https://github.com/elastic/apm-server/issues/7001, remove outdated link.
N/A
https://github.com/elastic/apm-server/issues/7001
=> docs: update OTel messaging spans limitation

docker-compose.yml
Fixes an issue with elastic-agent setting up service account tokens.
`elastic-agent container` recognises `ELASTICSEARCH_{USERNAME,PASSWORD}` as fallbacks to `KIBANA_FLEET_{USERNAME,PASSWORD}`. It also suggests `KIBANA_{USERNAME,PASSWORD}` can be used (which we have been), but they are not recognised. See also https://github.com/elastic/beats/issues/29831
N/A
None
=> docker-compose: use KIBANA_FLEET_* env vars

docker-compose.yml
[start_time:Thu, 13 Jan 2022 00:12:24 GMT, release_branch:7.17, prefix:, end_time:Thu, 13 Jan 2022 05:42:43 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-560490e9, build_duration_seconds:19819]
=> [automation] update elastic stack version for testing 7.17.0-560490e9

docker-compose.yml
[start_time:Sun, 16 Jan 2022 00:18:34 GMT, release_branch:7.17, prefix:, end_time:Sun, 16 Jan 2022 06:05:07 GMT, manifest_version:2.0.0, version:7.17.0-SNAPSHOT, branch:7.17, build_id:7.17.0-079761a0, build_duration_seconds:20793]
=> [automation] update elastic stack version for testing 7.17.0-079761a0

docker-compose.yml
[start_time:Mon, 24 Jan 2022 00:15:35 GMT, release_branch:8.0, prefix:, end_time:Mon, 24 Jan 2022 04:55:37 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-6ce456eb, build_duration_seconds:16802]
=> [automation] update elastic stack version for testing 8.0.0-6ce456eb

docker-compose.yml
[start_time:Fri, 21 Jan 2022 05:15:54 GMT, release_branch:7.16, prefix:, end_time:Fri, 21 Jan 2022 10:50:26 GMT, manifest_version:2.0.0, version:7.16.4-SNAPSHOT, branch:7.16, build_id:7.16.4-206b88b5, build_duration_seconds:20072]
=> [automation] update elastic stack version for testing 7.16.4-206b88b5

apmpackage/apm/changelog.yml, apmpackage/apm/data_stream/error_logs/fields/ecs.yml
Add the `error.id` field to `logs-apm.error-*` data streams mapping. This field was accidentally omitted when migrating from beats fields.yml to the integration package.
1. Install APM integration
2. Send error events, e.g. using the Go agent's API
3. Navigate to the errors page in the APM UI, click on an error instance, and click the "metadata" tab
Error metadata tab should open without any issues.
Closes https://github.com/elastic/apm-server/issues/7122
=> Map `error.id` in error_logs data stream

docs/api-info.asciidoc, docs/legacy/server-info.asciidoc
Fixes the APM Server info API response by removing the enclosing `"ok": {...}` object. I've also update the example to use a secret token.
Thanks to @trentm for spotting this. It has apparently been wrong since https://github.com/elastic/apm-server/pull/1748.
=> docs: fix info API response

docs/upgrading-to-717.asciidoc
Adds upgrading content to the 7.17 documentation. This PR is mostly a clone of the content added in https://github.com/elastic/apm-server/pull/7103. There are some changes:
* Self-managed standalone doesn't require the APM integration and includes running the `setup` command for custom indices/dashboards.
* No extra ECE TLS step when upgrading the APM integration on Cloud (is this correct?)
=> docs: add 7.17 upgrading instructions

docker-compose.yml
[start_time:Wed, 26 Jan 2022 05:13:33 GMT, release_branch:7.16, prefix:, end_time:Wed, 26 Jan 2022 10:51:23 GMT, manifest_version:2.0.0, version:7.16.4-SNAPSHOT, branch:7.16, build_id:7.16.4-1b320a84, build_duration_seconds:20270]
=> [automation] update elastic stack version for testing 7.16.4-1b320a84

docker-compose.yml
[start_time:Thu, 27 Jan 2022 00:16:25 GMT, release_branch:8.0, prefix:, end_time:Thu, 27 Jan 2022 04:56:04 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-e2e78bad, build_duration_seconds:16779]
=> [automation] update elastic stack version for testing 8.0.0-e2e78bad

beater/beater.go, beater/server_test.go, systemtest/fleet_test.go
Fix a race between apm-server and libbeat code replacing the `libbeat.output.events` metrics registries. When the output is reloaded, libbeat clears the `libbeat` registry, undoing any replacement made by apm-server code. Because the libbeat code caches the `libbeat` metrics registry at init time, we can remove it and replace it with a new `libbeat` metrics registry under our own control.
~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)~ (not yet released)
1. Run apm integration
2. Ingest some events
3. Check libbeat metrics in …
=> Fix libbeat metrics replacement

docker-compose.yml
[start_time:Thu, 27 Jan 2022 05:13:38 GMT, release_branch:7.16, prefix:, end_time:Thu, 27 Jan 2022 10:50:41 GMT, manifest_version:2.0.0, version:7.16.4-SNAPSHOT, branch:7.16, build_id:7.16.4-42a1f428, build_duration_seconds:20223]
=> [automation] update elastic stack version for testing 7.16.4-42a1f428

docker-compose.yml
[start_time:Sat, 29 Jan 2022 05:14:09 GMT, release_branch:7.16, prefix:, end_time:Sat, 29 Jan 2022 10:47:13 GMT, manifest_version:2.0.0, version:7.16.4-SNAPSHOT, branch:7.16, build_id:7.16.4-047be5da, build_duration_seconds:19984]
=> [automation] update elastic stack version for testing 7.16.4-047be5da

docker-compose.yml
[start_time:Sun, 30 Jan 2022 00:16:02 GMT, release_branch:8.0, prefix:, end_time:Sun, 30 Jan 2022 05:13:26 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-f8220c88, build_duration_seconds:17844]
=> [automation] update elastic stack version for testing 8.0.0-f8220c88

docker-compose.yml
[start_time:Tue, 1 Feb 2022 00:14:42 GMT, release_branch:8.0, prefix:, end_time:Tue, 1 Feb 2022 04:58:46 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-09bea260, build_duration_seconds:17044]
=> [automation] update elastic stack version for testing 8.0.0-09bea260

systemtest/containers.go
Update systemtest to address fleet-server by hostname ("fleet-server"), rather than by IP.
I don't recall why we were using the IP for fleet-server in the first place, but should be able to rely on the container's hostname being resolvable, and it allows us to verify TLS without relying on IP SANs.
=> systemtest: don't use fleet-server IP

docker-compose.yml
[start_time:Tue, 1 Feb 2022 21:32:28 GMT, release_branch:7.17, prefix:, end_time:Wed, 2 Feb 2022 01:59:53 GMT, manifest_version:2.0.0, version:7.17.1-SNAPSHOT, branch:7.17, build_id:7.17.1-7ef8bcb5, build_duration_seconds:16045]
=> [automation] update elastic stack version for testing 7.17.1-7ef8bcb5

systemtest/cmd/runapm/main.go, systemtest/containers.go, systemtest/fleet_test.go
Start copying logs as soon as the container has started, in case container startup fails; otherwise the container logs are lost and we cannot tell why the container failed to start.
=> systemtest: fix elastic-agent log copying

docker-compose.yml
[start_time:Tue, 1 Feb 2022 03:19:05 GMT, release_branch:master, prefix:, end_time:Tue, 1 Feb 2022 13:29:39 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:master, build_id:8.1.0-1cb1f3ad, build_duration_seconds:36634]
=> [automation] update elastic stack version for testing 8.1.0-1cb1f3ad

docker-compose.yml
[start_time:Wed, 2 Feb 2022 05:16:21 GMT, release_branch:7.17, prefix:, end_time:Wed, 2 Feb 2022 09:47:17 GMT, manifest_version:2.0.0, version:7.17.1-SNAPSHOT, branch:7.17, build_id:7.17.1-aa300c4a, build_duration_seconds:16256]
=> [automation] update elastic stack version for testing 7.17.1-aa300c4a

docker-compose.yml
[start_time:Wed, 2 Feb 2022 00:14:16 GMT, release_branch:8.0, prefix:, end_time:Thu, 3 Feb 2022 01:20:03 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-56a14b95, build_duration_seconds:90347]
=> [automation] update elastic stack version for testing 8.0.0-56a14b95

.ci/jobs/apm-server-schedule-daily.yml, .ci/schedule-daily.groovy, .ci/update-beats.groovy
Dynamically trigger jobs related to the update-beats automation. This approach uses the active branches detection, therefore we won't need to do much as older branches won't trigger any extra builds.
I'll wait for the renaming branch that happens today
=> ci: schedule daily job

systemtest/cmd/runapm/main.go
Fix runapm's `-var` flag: initialise the map, so using the flag doesn't panic.
=> systemtest: fix runapm -var flag

docker-compose.yml
[start_time:Thu, 3 Feb 2022 01:32:54 GMT, release_branch:8.0, prefix:, end_time:Thu, 3 Feb 2022 06:27:23 GMT, manifest_version:2.0.0, version:8.0.0-SNAPSHOT, branch:8.0, build_id:8.0.0-1018d5a4, build_duration_seconds:17669]
=> [automation] update elastic stack version for testing 8.0.0-1018d5a4

systemtest/cmd/runapm/main.go, systemtest/kibana.go
Make the policy name configurable, and make reinstallation of the APM integration package optional, through additional CLI flags.
This makes it possible to run multiple agents, each with their own integration policy. This can be useful when multiple APM Servers are required, e.g. for tail-based sampling.
=> runapm: make policy name and reinstall flags

systemtest/sampling_test.go
Unskip systemtest.TestTailSampling, as the privileges issue (https://github.com/elastic/fleet-server/issues/1048) has been fixed.
=> systemtest: unskip TestTailSampling

docker-compose.yml
[start_time:Sun, 6 Feb 2022 05:16:53 GMT, release_branch:7.17, prefix:, end_time:Sun, 6 Feb 2022 09:43:26 GMT, manifest_version:2.0.0, version:7.17.1-SNAPSHOT, branch:7.17, build_id:7.17.1-f7e4bfc6, build_duration_seconds:15993]
=> [automation] update elastic stack version for testing 7.17.1-f7e4bfc6

.ci/scripts/update-beats.sh
Slight variation on https://github.com/elastic/apm-server/pull/7178 (keeps include/fields.go)
=> Fix update-beats CI job for 7.17

docker-compose.yml
[start_time:Mon, 7 Feb 2022 05:13:40 GMT, release_branch:7.17, prefix:, end_time:Mon, 7 Feb 2022 09:43:01 GMT, manifest_version:2.0.0, version:7.17.1-SNAPSHOT, branch:7.17, build_id:7.17.1-48ecd1f2, build_duration_seconds:16161]
=> [automation] update elastic stack version for testing 7.17.1-48ecd1f2

docker-compose.yml
[start_time:Tue, 8 Feb 2022 12:17:02 GMT, release_branch:master, prefix:, end_time:Tue, 8 Feb 2022 18:05:51 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-ff5ac1e4, build_duration_seconds:20929]
=> [automation] update elastic stack version for testing 8.2.0-ff5ac1e4

docs/legacy/copied-from-beats/docs/shared-directory-layout.asciidoc, docs/legacy/getting-started-apm-server.asciidoc
Removes Homebrew documentation. A breaking change has been added to https://github.com/elastic/apm-server/pull/7202.
=> docs: remove Homebrew

systemtest/containers.go
Elasticsearch downloads the geoIP database after starting up, and then refreshes it periodically. In CI the cluster will always be fresh, so we wait for the database to be downloaded before running any tests which may depend on the database being available.
N/A
N/A
Closes #7260
=> systemtest: wait for geoIP database availability

docs/legacy/getting-started-apm-server.asciidoc
One part of https://github.com/elastic/apm-server/issues/7219. Updates https://www.elastic.co/guide/en/apm/guide/master/apm-server-configuration.html.
=> docs: link to air-gap instructions

docker-compose.yml
[start_time:Mon, 14 Feb 2022 05:14:22 GMT, release_branch:7.17, prefix:, end_time:Mon, 14 Feb 2022 09:40:28 GMT, manifest_version:2.0.0, version:7.17.1-SNAPSHOT, branch:7.17, build_id:7.17.1-d1501547, build_duration_seconds:15966]
=> [automation] update elastic stack version for testing 7.17.1-d1501547

docker-compose.yml
[start_time:Mon, 14 Feb 2022 12:17:14 GMT, release_branch:master, prefix:, end_time:Mon, 14 Feb 2022 17:25:40 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-c75da523, build_duration_seconds:18506]
=> [automation] update elastic stack version for testing 8.2.0-c75da523

docker-compose.yml
[start_time:Mon, 14 Feb 2022 12:14:03 GMT, release_branch:8.1, prefix:, end_time:Mon, 14 Feb 2022 17:04:39 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:8.1, build_id:8.1.0-9063dd89, build_duration_seconds:17436]
=> [automation] update elastic stack version for testing 8.1.0-9063dd89

beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json, beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json, beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json, changelogs/head.asciidoc, model/modeldecoder/rumv3/decoder.go, model/modeldecoder/v2/decoder.go, processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
For metricsets the `service.version` is only overwritten if also `service.name` is given (see https://github.com/elastic/apm-server/pull/6407#issuecomment-950973237). It should be the same for transactions, errors, ...
Ingest a transaction that only contains a `service.version`, but no `service.name`
=> Only overwrite service.version if service.name is also set

.ci/schedule-daily.groovy
7 major branch is only about `7.17`, while the `8` major branch supports now:
- 8.0
- 8.1
Update the daily jobs to use the right aliases since 7 major won't have any further minor releases.
Requires https://github.com/elastic/apm-pipeline-library/pull/1548
=> ci: support for next patch release branch 8

docker-compose.yml
[start_time:Tue, 15 Feb 2022 12:14:05 GMT, release_branch:8.1, prefix:, end_time:Tue, 15 Feb 2022 17:24:33 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:8.1, build_id:8.1.0-c6173806, build_duration_seconds:18628]
=> [automation] update elastic stack version for testing 8.1.0-c6173806

apmpackage/apm/changelog.yml, apmpackage/apm/data_stream/traces/fields/fields.yml, changelogs/head.asciidoc, go.mod, model/modeldecoder/rumv3/transaction_test.go, model/modeldecoder/v2/span_test.go, model/span.go, model/span_test.go, model/spanlink.go, model/spanlink_test.go, processor/otel/traces.go, processor/otel/traces_test.go, systemtest/otlp_test.go
This PR adds support for span links to our data model, enabling a span/transaction to be associated with zero or more other spans/transactions. We use `span.links` and `span.links.span.id` regardless of whether the linked entities are spans or transactions.
The PR also adds support for capturing OpenTelemetry span links.
1. Using an OpenTelemetry SDK, send a span with links to APM Server.
2. Check that the trace ID and span ID of the link are stored. Any attributes or trace-state associated with the link should not be stored.
3. Ensure the trace can be find when searching `traces-apm*` and querying by `span.links.trace.id`
Closes https://github.com/elastic/apm-server/issues/7171
=> Add support for span links

magefile.go
This reverts commit 7a3edfdba03e5fa2e448fa92cbab401b42a08150.
`mage.DMG` is not defined (edit: removed in https://github.com/elastic/beats/pull/30097 and pulled into main since then).  I'm not sure if this was pushed by accident but it doesn't seem to have come via a pull request.  
@stuartnelson3
=> Revert "[mage] filter .dmg package creation"

changelogs/head.asciidoc, processor/otel/metrics.go, processor/otel/metrics_test.go
Drop OpenTelemetry histograms that have no explicit bounds defined.
See https://github.com/elastic/apm-server/issues/7282
Closes https://github.com/elastic/apm-server/issues/7282
=> processor/otel: drop histograms without bounds

docker-compose.yml
[start_time:Wed, 16 Feb 2022 05:15:36 GMT, release_branch:7.17, prefix:, end_time:Wed, 16 Feb 2022 09:41:41 GMT, manifest_version:2.0.0, version:7.17.1-SNAPSHOT, branch:7.17, build_id:7.17.1-9bbee73a, build_duration_seconds:15965]
=> [automation] update elastic stack version for testing 7.17.1-9bbee73a

docker-compose.yml
[start_time:Wed, 16 Feb 2022 12:16:36 GMT, release_branch:master, prefix:, end_time:Wed, 16 Feb 2022 17:17:56 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-74785f8b, build_duration_seconds:18080]
=> [automation] update elastic stack version for testing 8.2.0-74785f8b

changelogs/head.asciidoc, cmd/root.go, cmd/root_test.go, systemtest/export_test.go
disable seccomp (linux-only) to allow fork/exec'ing the java attacher
0. ensure `java-attacher.jar` is in the same directory as the `apm-server` binary
1. add the following to `apm-server.yml`
```yml
logging.level: debug
apm-server:
java_attacher:
enabled: true
download-agent-version: 1.28.4
discovery-rules:
- include-main: opbeans
- exclude-main: ".*"
config:
server_url: "http://localhost:8200"
```
2. start the apm-server, check that there's no seccomp error message:
```
{"log.level":"error","@timestamp":"2022-02-16T12:34:54.385+0100","log.logger":"beater","log.origin":{"file.name":"beater/beater.go","file.line":447},"message":"failed to run java attacher: fork/exec /bin/java: operation not permitted","service.name":"apm-server","ecs.version":"1.6.0"}
```
closes …
=> disable seccomp by default

Makefile
https://github.com/elastic/apm-server/pull/7328 moved evaluation of
environment variables down below the target definitions breaking the
target dependencies causing the attacher to never download
Will need to be forward ported to `main` as well.
=> Fixes sourcing of java-attacher.jar

docker-compose.yml
[start_time:Thu, 17 Feb 2022 00:14:30 GMT, release_branch:8.1, prefix:, end_time:Thu, 17 Feb 2022 05:13:31 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:8.1, build_id:8.1.0-732c5a10, build_duration_seconds:17941]
=> [automation] update elastic stack version for testing 8.1.0-732c5a10

docker-compose.yml
[start_time:Thu, 17 Feb 2022 05:14:06 GMT, release_branch:7.17, prefix:, end_time:Thu, 17 Feb 2022 09:41:54 GMT, manifest_version:2.0.0, version:7.17.1-SNAPSHOT, branch:7.17, build_id:7.17.1-598c7994, build_duration_seconds:16068]
=> [automation] update elastic stack version for testing 7.17.1-598c7994

_meta/beat.yml, apm-server.docker.yml, apm-server.yml, beater/beater.go, beater/config/config_test.go, beater/config/data_streams.go, changelogs/head.asciidoc
using `apm-server.data_streams.namespace`
closes #7313 
Start an unmanaged apm-server with `apm-server.data_streams.namespace` set and inspect the trace data streams created.
=> allow data stream namespace configuration for standalone

Makefile
Make sure we build the python venv that is required to build dependencies.csv.
=> Makefile: dependencies.csv dependends on $PYTHON

changelogs/head.asciidoc, processor/otel/logs.go, processor/otel/logs_test.go
Make sure we call `initEventLabels` on every log event, to clone any shared labels produced from resource attributes. If we don't call that, then we end up updating the shared label map for each log record in a payload.
See https://github.com/elastic/apm-server/issues/7311
Fixes #7311
=> processor/otel: clone shared labels for log events

changelogs/head.asciidoc, model/modelindexer/indexer.go, model/modelindexer/indexer_test.go
If the background timer goroutine was started, but had not yet added to the errgroup, then Close could return before events enqueued by ProcessEvents were flushed.
We fix this by ensuring the errgroup.Go call is made before ProcessEvents returned. If the timer is stopped (e.g. because Close is called), then we signal to the timer goroutine to flush immediately, instead of calling flushActive(Locked) from multiple code paths.
This should fix the `TestTransactionAggregationShutdown` failures we occasionally see in CI.
This is not likely to happen in a real setup. Run …
=> modelindexer: fix flush-on-close timing issues

docker-compose.yml
[start_time:Mon, 21 Feb 2022 12:20:51 GMT, release_branch:master, prefix:, end_time:Mon, 21 Feb 2022 18:04:10 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-ba537863, build_duration_seconds:20599]
=> [automation] update elastic stack version for testing 8.2.0-ba537863

docker-compose.yml
[start_time:Mon, 21 Feb 2022 12:13:44 GMT, release_branch:8.1, prefix:, end_time:Mon, 21 Feb 2022 17:02:41 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:8.1, build_id:8.1.0-6dfec5b9, build_duration_seconds:17337]
=> [automation] update elastic stack version for testing 8.1.0-6dfec5b9

model/modelindexer/indexer_test.go
Fix intermittent test failure, due to goroutines started by the mock Elasticsearch server stopping during the test.
=> Allow for goroutines to stop during test

apmpackage/apm/changelog.yml, apmpackage/apm/data_stream/internal_metrics/fields/fields.yml, x-pack/apm-server/aggregation/txmetrics/aggregator.go, x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Add `faas.id` to the transaction metrics aggregation key. This is used by the UI to display the function name.
1. Send some FaaS transactions to APM Server
2. Check the `faas.id` field shows up in the transaction metrics
Fixes #7344
=> txmetrics: add `faas.id` to aggregation key

docker-compose.yml
[start_time:Tue, 22 Feb 2022 12:13:54 GMT, release_branch:8.1, prefix:, end_time:Tue, 22 Feb 2022 16:54:54 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:8.1, build_id:8.1.0-3aaf806b, build_duration_seconds:16860]
=> [automation] update elastic stack version for testing 8.1.0-3aaf806b

.gitignore, NOTICE.txt, go.mod, go.sum
While testing out go 1.18's workspace support, this mismatch in replacements was identified by `go work`:
```
go: conflicting replacements for github.com/Shopify/sarama:
github.com/elastic/sarama@v1.19.1-0.20210120173147-5c8cb347d877
github.com/elastic/sarama@v1.19.1-0.20210823122811-11c3ef800752
use "go work edit -replace github.com/Shopify/sarama=[override]" to resolve
go: conflicting replacements for github.com/fsnotify/fsnotify:
github.com/adriansr/fsnotify@v0.0.0-20180417234312-c9bbe1f46f1d
github.com/adriansr/fsnotify@v1.4.8-0.20211018144411-a81f2b630e7c
use "go work edit -replace github.com/fsnotify/fsnotify=[override]" to resolve
```
This performs a one time sync of those replacements from beats.
With these changes in place, this `go.work` did the trick:
```
go 1.18
use .
use …
```
=> update beats transitive module replacements 

docker-compose.yml
[start_time:Thu, 24 Feb 2022 12:17:26 GMT, release_branch:8.1, prefix:, end_time:Thu, 24 Feb 2022 17:30:59 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:8.1, build_id:8.1.0-6704585f, build_duration_seconds:18813]
=> [automation] update elastic stack version for testing 8.1.0-6704585f

docker-compose.yml
[start_time:Thu, 24 Feb 2022 12:14:35 GMT, release_branch:master, prefix:, end_time:Thu, 24 Feb 2022 17:19:00 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-c2195520, build_duration_seconds:18265]
=> [automation] update elastic stack version for testing 8.2.0-c2195520

docker-compose.yml
[start_time:Sun, 27 Feb 2022 12:16:44 GMT, release_branch:8.1, prefix:, end_time:Sun, 27 Feb 2022 17:13:21 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:8.1, build_id:8.1.0-f6199768, build_duration_seconds:17797]
=> [automation] update elastic stack version for testing 8.1.0-f6199768

docker-compose.yml
[start_time:Sun, 27 Feb 2022 12:19:56 GMT, release_branch:master, prefix:, end_time:Sun, 27 Feb 2022 17:35:35 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-4a677e18, build_duration_seconds:18939]
=> [automation] update elastic stack version for testing 8.2.0-4a677e18

docker-compose.yml
[start_time:Sun, 27 Feb 2022 05:13:41 GMT, release_branch:7.17, prefix:, end_time:Sun, 27 Feb 2022 09:46:12 GMT, manifest_version:2.0.0, version:7.17.1-SNAPSHOT, branch:7.17, build_id:7.17.1-952e96f1, build_duration_seconds:16351]
=> [automation] update elastic stack version for testing 7.17.1-952e96f1

.github/workflows/add-to-apm-project.yml
https://github.com/elastic/apm-server/actions/runs/1909820154 is suddenly failing with:
```
Type mismatch on variable $projectid and argument projectId (String! / ID!)
```
=>  Update APM Add to Project Parameter Types

docker-compose.yml
[start_time:Mon, 28 Feb 2022 12:14:29 GMT, release_branch:master, prefix:, end_time:Mon, 28 Feb 2022 17:07:27 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-bdf2ad74, build_duration_seconds:17578]
=> [automation] update elastic stack version for testing 8.2.0-bdf2ad74

docker-compose.yml
[start_time:Mon, 28 Feb 2022 05:13:38 GMT, release_branch:7.17, prefix:, end_time:Mon, 28 Feb 2022 09:41:48 GMT, manifest_version:2.0.0, version:7.17.1-SNAPSHOT, branch:7.17, build_id:7.17.1-bf42f386, build_duration_seconds:16090]
=> [automation] update elastic stack version for testing 7.17.1-bf42f386

docker-compose.yml
[start_time:Tue, 1 Mar 2022 12:17:14 GMT, release_branch:master, prefix:, end_time:Tue, 1 Mar 2022 17:42:51 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-43df679f, build_duration_seconds:19537]
=> [automation] update elastic stack version for testing 8.2.0-43df679f

docker-compose.yml
[start_time:Wed, 2 Mar 2022 05:13:39 GMT, release_branch:7.17, prefix:, end_time:Wed, 2 Mar 2022 09:41:01 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-e8098595, build_duration_seconds:16042]
=> [automation] update elastic stack version for testing 7.17.2-e8098595

docker-compose.yml
[start_time:Thu, 3 Mar 2022 00:14:05 GMT, release_branch:8.0, prefix:, end_time:Thu, 3 Mar 2022 04:52:31 GMT, manifest_version:2.0.0, version:8.0.2-SNAPSHOT, branch:8.0, build_id:8.0.2-ae36dda7, build_duration_seconds:16706]
=> [automation] update elastic stack version for testing 8.0.2-ae36dda7

docker-compose.yml
[start_time:Thu, 3 Mar 2022 00:17:14 GMT, release_branch:master, prefix:, end_time:Thu, 3 Mar 2022 05:11:32 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-190af159, build_duration_seconds:17658]
=> [automation] update elastic stack version for testing 8.2.0-190af159

docker-compose.yml
[start_time:Fri, 4 Mar 2022 14:54:03 GMT, release_branch:master, prefix:, end_time:Fri, 4 Mar 2022 20:48:39 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-a12f7069, build_duration_seconds:21276]
=> [automation] update elastic stack version for testing 8.2.0-a12f7069

docker-compose.yml
[start_time:Fri, 4 Mar 2022 12:15:04 GMT, release_branch:8.0, prefix:, end_time:Fri, 4 Mar 2022 16:57:23 GMT, manifest_version:2.0.0, version:8.0.2-SNAPSHOT, branch:8.0, build_id:8.0.2-901e2b50, build_duration_seconds:16939]
=> [automation] update elastic stack version for testing 8.0.2-901e2b50

docker-compose.yml
[start_time:Fri, 4 Mar 2022 12:13:26 GMT, release_branch:8.1, prefix:, end_time:Fri, 4 Mar 2022 17:11:44 GMT, manifest_version:2.0.0, version:8.1.0-SNAPSHOT, branch:8.1, build_id:8.1.0-52a8d1d4, build_duration_seconds:17898]
=> [automation] update elastic stack version for testing 8.1.0-52a8d1d4

apmpackage/apm/changelog.yml
I'm working on adding changelogs to integration documentation. This PR escapes our doc build reserved chars, `{` and `}` by moving them to code snippets so that the changelog can build.
Here's what it looks like (for now). Unfortunately, it's a bit ugly until we have the ability to customize table column widths.
For https://github.com/elastic/wordlake/pull/18.
=> Clean up apmpackage changelog.yml

docs/apm-components.asciidoc, docs/input-apm.asciidoc, docs/legacy/guide/apm-doc-directory.asciidoc, docs/legacy/guide/distributed-tracing.asciidoc, docs/legacy/guide/trace-sampling.asciidoc, docs/secure-agent-communication.asciidoc
Closes https://github.com/elastic/apm-server/issues/7443.
Closes https://github.com/elastic/observability-docs/issues/1288.
=> [docs] Fix images and link to input settings

CHANGELOG.asciidoc, changelogs/8.0.asciidoc, changelogs/8.1.asciidoc, changelogs/head.asciidoc, docs/apm-breaking.asciidoc, docs/release-notes.asciidoc
Adds release notes and breaking changes for 8.1.0.
* A link to TBS docs will be added in the TBS PR.
* Needs to be cherrypicked to `main`.
=> [8.1] 8.1.0 release notes

docs/legacy/common-problems.asciidoc
This PR adds documentation explaining the following APM logs:
```
.../api/apm/settings/agent-configuration/search": context canceled
.../api/apm/settings/agent-configuration/search": net/http: TLS handshake timeout
```
Closes https://github.com/elastic/observability-docs/issues/1573.
=> docs: document central config troubleshooting

docker-compose.yml
[start_time:Fri, 11 Mar 2022 00:14:19 GMT, release_branch:8.1, prefix:, end_time:Fri, 11 Mar 2022 04:57:23 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-b9a6c108, build_duration_seconds:16984]
=> [automation] update elastic stack version for testing 8.1.1-b9a6c108

docker-compose.yml
[start_time:Thu, 10 Mar 2022 18:52:36 GMT, release_branch:master, prefix:, end_time:Thu, 10 Mar 2022 23:38:30 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-63265ec9, build_duration_seconds:17154]
=> [automation] update elastic stack version for testing 8.2.0-63265ec9

docker-compose.yml
[start_time:Sun, 13 Mar 2022 12:16:42 GMT, release_branch:8.1, prefix:, end_time:Sun, 13 Mar 2022 17:20:33 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-da392dcd, build_duration_seconds:18231]
=> [automation] update elastic stack version for testing 8.1.1-da392dcd

docker-compose.yml
[start_time:Sun, 13 Mar 2022 05:13:32 GMT, release_branch:7.17, prefix:, end_time:Sun, 13 Mar 2022 09:49:30 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-c18736fc, build_duration_seconds:16558]
=> [automation] update elastic stack version for testing 7.17.2-c18736fc

docker-compose.yml
[start_time:Sun, 13 Mar 2022 12:16:37 GMT, release_branch:master, prefix:, end_time:Sun, 13 Mar 2022 17:22:42 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-d02c907a, build_duration_seconds:18365]
=> [automation] update elastic stack version for testing 8.2.0-d02c907a

docker-compose.yml
[start_time:Mon, 14 Mar 2022 12:13:26 GMT, release_branch:8.1, prefix:, end_time:Mon, 14 Mar 2022 16:59:13 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-2d188131, build_duration_seconds:17147]
=> [automation] update elastic stack version for testing 8.1.1-2d188131

docker-compose.yml
[start_time:Mon, 14 Mar 2022 00:16:35 GMT, release_branch:master, prefix:, end_time:Mon, 14 Mar 2022 05:21:24 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-fee3b8d2, build_duration_seconds:18289]
=> [automation] update elastic stack version for testing 8.2.0-fee3b8d2

docker-compose.yml
[start_time:Mon, 14 Mar 2022 05:13:19 GMT, release_branch:7.17, prefix:, end_time:Mon, 14 Mar 2022 09:39:37 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-8be09371, build_duration_seconds:15978]
=> [automation] update elastic stack version for testing 7.17.2-8be09371

go.mod, model/modelindexer/indexer_test.go
Fix the modelindexer benchmarks, which were failing due to the mock Elasticsearch server not returning the appropriate X-Elastic-Product header.
=> Fix modelindexer benchmarks

NOTICE.txt, beater/beater.go, beater/server_test.go, go.mod, go.sum
Update with libbeat and beats packaging.
=> [automation] update libbeat and beats packaging

docker-compose.yml
[start_time:Tue, 15 Mar 2022 05:15:49 GMT, release_branch:7.17, prefix:, end_time:Tue, 15 Mar 2022 09:42:02 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-2208f979, build_duration_seconds:15973]
=> [automation] update elastic stack version for testing 7.17.2-2208f979

docker-compose.yml
[start_time:Tue, 15 Mar 2022 12:14:02 GMT, release_branch:8.1, prefix:, end_time:Tue, 15 Mar 2022 17:12:05 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-31faf00b, build_duration_seconds:17883]
=> [automation] update elastic stack version for testing 8.1.1-31faf00b

docker-compose.yml
[start_time:Tue, 15 Mar 2022 12:16:35 GMT, release_branch:master, prefix:, end_time:Tue, 15 Mar 2022 16:54:57 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-9bac538c, build_duration_seconds:16702]
=> [automation] update elastic stack version for testing 8.2.0-9bac538c

docker-compose.yml
[start_time:Wed, 16 Mar 2022 15:42:35 GMT, release_branch:8.1, prefix:, end_time:Wed, 16 Mar 2022 22:24:13 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-9bb65a23, build_duration_seconds:24098]
=> [automation] update elastic stack version for testing 8.1.1-9bb65a23

docker-compose.yml
[start_time:Wed, 16 Mar 2022 05:13:53 GMT, release_branch:7.17, prefix:, end_time:Wed, 16 Mar 2022 13:13:06 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-8f7db3a8, build_duration_seconds:28753]
=> [automation] update elastic stack version for testing 7.17.2-8f7db3a8

changelogs/head.asciidoc, docs/spec/v2/span.json, docs/spec/v2/transaction.json, model/modeldecoder/v2/decoder.go, model/modeldecoder/v2/model.go, model/modeldecoder/v2/model_generated.go, model/modeldecoder/v2/model_test.go, model/modeldecoder/v2/span_test.go, model/modeldecoder/v2/transaction_test.go, processor/stream/processor_test.go, processor/stream/test_approved_es_documents/testIntakeIntegrationSpanLinks.approved.json, testdata/intake-v2/span-links.ndjson
Add support for span links to intake v2, for spans and transactions. I have intentionally not added support to the RUM v3 intake, as there is no need for span links there at present.
1. Send `testdata/intake-v2/span-links.ndjson` to apm-server
2. Check the spans and transactions indexed in Elasticsearch have `span.links` fields populated accordingly
Closes https://github.com/elastic/apm-server/issues/7304
=> Add span links to intake v2

docker-compose.yml
[start_time:Thu, 17 Mar 2022 12:13:54 GMT, release_branch:8.1, prefix:, end_time:Thu, 17 Mar 2022 17:04:13 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-da22c151, build_duration_seconds:17419]
=> [automation] update elastic stack version for testing 8.1.1-da22c151

docker-compose.yml
[start_time:Fri, 18 Mar 2022 00:16:30 GMT, release_branch:master, prefix:, end_time:Fri, 18 Mar 2022 04:22:19 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-82b803a1, build_duration_seconds:14749]
=> [automation] update elastic stack version for testing 8.2.0-82b803a1

Jenkinsfile
The integration tests do not pay their weight. They take 30-40 minutes, intermittently fail due to test flakiness, and I cannot remember the last time they failed due to a change in the server. We have coverage in our system tests, so let's take back some time.
Rather than the server running tests for all agents, agents should run their own integration tests. In the rare event that the server breaks for a specific agent (i.e. not covered by system tests which just use the Go agent), agent developers can report issues to us. …
=> ci: remove APM Integration Tests stage

docker-compose.yml
[start_time:Thu, 17 Mar 2022 05:13:20 GMT, release_branch:7.17, prefix:, end_time:Thu, 17 Mar 2022 19:23:04 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-15b5bc7a, build_duration_seconds:50984]
=> [automation] update elastic stack version for testing 7.17.2-15b5bc7a

.ci/scripts/release-manager.sh
fixes: '/artifacts/build/distributions/dependencies-8.2.0-SNAPSHOT.csv' specified for property '' does not exist.
=> ci: -SNAPSHOT suffix is required

docker-compose.yml
[start_time:Sun, 20 Mar 2022 05:13:32 GMT, release_branch:7.17, prefix:, end_time:Sun, 20 Mar 2022 09:40:07 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-3b3b663d, build_duration_seconds:15995]
=> [automation] update elastic stack version for testing 7.17.2-3b3b663d

docker-compose.yml
[start_time:Sun, 20 Mar 2022 00:16:27 GMT, release_branch:8.1, prefix:, end_time:Sun, 20 Mar 2022 04:55:02 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-0d572bb7, build_duration_seconds:16715]
=> [automation] update elastic stack version for testing 8.1.1-0d572bb7

.ci/scripts/release-manager.sh
`docker.elastic.co` might not be available, so let's rely on the cached docker images by default, but let's try to pull the recent docker image too.
Reduce the environmental issues
=> dra: retry docker pull

changelogs/8.1.asciidoc
Note: 8.1.2 release notes were added in https://github.com/elastic/apm-server/commit/f1be74a473090bee3208722f3578616850a8c7c5. Based on the [BC2 commit hash](https://github.com/elastic/apm-server/commits/c28d7e2d938e46066ea80b31b8161d28be0ecd63), I've moved #7428 to 8.1.1 and commented out 8.1.2 to avoid user confusion.
=> docs: add 8.1.1 release notes

docker-compose.yml
[start_time:Mon, 21 Mar 2022 05:13:35 GMT, release_branch:7.17, prefix:, end_time:Mon, 21 Mar 2022 09:40:36 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-81597e21, build_duration_seconds:16021]
=> [automation] update elastic stack version for testing 7.17.2-81597e21

.ci/packaging.groovy
GitHub PR comments are created to help with debugging, since the `packaging` pipeline is not running for PRs, then it should not notify anything.
=> ci: packaging pipeline should not notify build status in github comments

docker-compose.yml
[start_time:Mon, 21 Mar 2022 12:13:28 GMT, release_branch:8.1, prefix:, end_time:Mon, 21 Mar 2022 17:20:59 GMT, manifest_version:2.0.0, version:8.1.1-SNAPSHOT, branch:8.1, build_id:8.1.1-c72e1d1e, build_duration_seconds:18451]
=> [automation] update elastic stack version for testing 8.1.1-c72e1d1e

changelogs/head.asciidoc, model/modelindexer/bulk_indexer.go, model/modelindexer/indexer_test.go
While updating #6731 I saw some errors in the cat_bulk.py Python server:
> EOFError: Compressed file ended before the end-of-stream marker was reached                                                              
This happens because the gzip writer was never closed, only flushed, so there was never an end-of-stream marker written to the Elasticsearch bulk request body. I've fixed that and added a unit test for compression level. While adding the test I noticed that the "BytesTotal" statistic is incorrect when compression is enabled; I will open an issue for that.
I don't know what the …
=> model/modelindexer: close gzip writer

model/modelindexer/bulk_indexer.go, model/modelindexer/indexer_test.go
This will backport the following commits from `main` to `8.1`:
- [Add X-Elastic-Product-Origin header to es requests (#7442)](https://github.com/elastic/apm-server/pull/7442)
=> [8.1] Add X-Elastic-Product-Origin header to es requests (#7442)

changelogs/head.asciidoc, model/modelindexer/bulk_indexer.go, model/modelindexer/indexer_test.go
This will backport the following commits from `main` to `8.1`:
- [model/modelindexer: close gzip writer (#7624)](https://github.com/elastic/apm-server/pull/7624)
=> [8.1] model/modelindexer: close gzip writer (#7624)

docker-compose.yml
[start_time:Thu, 24 Mar 2022 00:13:50 GMT, release_branch:8.1, prefix:, end_time:Thu, 24 Mar 2022 04:54:25 GMT, manifest_version:2.0.0, version:8.1.2-SNAPSHOT, branch:8.1, build_id:8.1.2-2393b0c1, build_duration_seconds:16835]
=> [automation] update elastic stack version for testing 8.1.2-2393b0c1

docker-compose.yml
[start_time:Wed, 23 Mar 2022 05:17:15 GMT, release_branch:7.17, prefix:, end_time:Wed, 23 Mar 2022 09:45:14 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-1941719d, build_duration_seconds:16079]
=> [automation] update elastic stack version for testing 7.17.2-1941719d

.ci/scripts/release-manager.sh
Enforce the version to be the one in this project rather than the one in the Unified Release.
Product teams might update the version earlier than the version in the unified release, so therefore this will reduce the changes of non-up-to-date versions.
> version (optional) is the version of the artifacts to expect, for example 8.0.1. This is useful so that asynchronous builds can bump their versions before the version number inside of the release manager container is bumped.
Fixes
```
/artifacts/build/distributions/apm-server-8.1.1-SNAPSHOT-i386.deb'
```
while artifacts are pointing to 8.1.2:
```
build/distributions/apm-server-8.1.2-SNAPSHOT-i386.deb
```
See https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-package-mbp/detail/8.1/26/pipeline
=> dra: enforce version

Makefile
Left trim spaces in the version
### Why
Otherwise
```
mv build/distributions/dependencies.csv build/distributions/dependencies- 7.17.2-SNAPSHOT.csv
```
### Issue
Use partial changes from https://github.com/elastic/apm-server/pull/6802/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R28
=> make: fix get-version with space

.ci/packaging.groovy
Stop publishing staging/snapshot images for an old release branch but keep building them.
For instance, `8.0` is not available anymore therefore the `DRA` stage in the `packaging` pipeline failed with:
```
The specified build file '/vagrant/release/8.0.gradle' does not exist.
```
This approach will allow us to only run for the available branch if any
Requires https://github.com/elastic/apm-pipeline-library/pull/1618
=> dra: run release-manager if branch is available

changelogs/head.asciidoc, model/modelindexer/indexer.go
This patch unlocks the `i.activeMu` mutex in flushActive as soon as the
`i.active` reference has been set to `nil`. This severely minimizes the
lock contention and achives similar or higher indexing throughput when
comparing the benchmarks before #7352 was introduced.
The microbenchmark results seem to indicate that we're back to the
previous indexing performance with this change:
```console
$ go test -bench ... # Current main
goos: darwin
goarch: arm64
pkg: github.com/elastic/apm-server/model/modelindexer
BenchmarkModelIndexer/NoCompression-8        4653790    2527 ns/op
BenchmarkModelIndexer/BestSpeed-8            2909288	4051 ns/op
BenchmarkModelIndexer/DefaultCompression-8   1691677	6674 ns/op
BenchmarkModelIndexer/BestCompression-8      1234953    8334 ns/op
PASS
ok …
```
=> modelindexer: Reduce locking on flushActive

docker-compose.yml
[start_time:Fri, 25 Mar 2022 00:16:28 GMT, release_branch:8.1, prefix:, end_time:Fri, 25 Mar 2022 04:59:50 GMT, manifest_version:2.0.0, version:8.1.2-SNAPSHOT, branch:8.1, build_id:8.1.2-5d446358, build_duration_seconds:17002]
=> [automation] update elastic stack version for testing 8.1.2-5d446358

docker-compose.yml
[start_time:Thu, 24 Mar 2022 14:05:21 GMT, release_branch:master, prefix:, end_time:Thu, 24 Mar 2022 18:23:25 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:master, build_id:8.2.0-dcff22d7, build_duration_seconds:15484]
=> [automation] update elastic stack version for testing 8.2.0-dcff22d7

CONTRIBUTING.md
Update backporting docs to explain the use of `backport-<branch>` labels.
=> Update backporting docs

docker-compose.yml
[start_time:Sun, 27 Mar 2022 00:16:59 GMT, release_branch:8.1, prefix:, end_time:Sun, 27 Mar 2022 05:40:39 GMT, manifest_version:2.0.0, version:8.1.2-SNAPSHOT, branch:8.1, build_id:8.1.2-d0bc828f, build_duration_seconds:19420]
=> [automation] update elastic stack version for testing 8.1.2-d0bc828f

docker-compose.yml
[start_time:Sat, 26 Mar 2022 05:16:10 GMT, release_branch:7.17, prefix:, end_time:Sat, 26 Mar 2022 09:42:10 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-cf7cf1eb, build_duration_seconds:15960]
=> [automation] update elastic stack version for testing 7.17.2-cf7cf1eb

docker-compose.yml
[start_time:Mon, 28 Mar 2022 12:14:19 GMT, release_branch:8.1, prefix:, end_time:Mon, 28 Mar 2022 17:45:46 GMT, manifest_version:2.0.0, version:8.1.2-SNAPSHOT, branch:8.1, build_id:8.1.2-e94d7716, build_duration_seconds:19887]
=> [automation] update elastic stack version for testing 8.1.2-e94d7716

docker-compose.yml
[start_time:Mon, 28 Mar 2022 05:13:42 GMT, release_branch:7.17, prefix:, end_time:Mon, 28 Mar 2022 09:41:14 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-99f889e2, build_duration_seconds:16052]
=> [automation] update elastic stack version for testing 7.17.2-99f889e2

NOTICE.txt, beater/api/mux.go, beater/api/root/handler.go, beater/api/root/handler_test.go, beater/server.go, beater/tracing_test.go, changelogs/head.asciidoc, go.mod, go.sum
Use gorilla/mux for HTTP request routing, so we can take advantage of its unknown route handling and avoid producing high-cardinality transaction names.
1. Enable self-instrumentation
2. Send a request to `/foo`
3. Check for a "404 page not found" response
4. Check that a transaction is recorded with the name "GET unknown route"
Closes #6085
=> Use gorilla/mux

apmpackage/apm/changelog.yml, apmpackage/apm/data_stream/app_logs/fields/ecs.yml, apmpackage/apm/data_stream/error_logs/fields/ecs.yml, apmpackage/apm/data_stream/traces/fields/ecs.yml
Add the `url.original` field to data streams where it may be indexed. We missed this in the original translation to the integration package.
1. Install the integration package
2. Ensure `traces-apm-*`, `traces-apm.rum-*`, `traces.apm.app-*`, and `traces-apm.error-*` index templates each have `url.original` defined.
Closes #7697
=> apmpackage: add `url.original` field back in

docker-compose.yml
[start_time:Tue, 29 Mar 2022 05:14:03 GMT, release_branch:7.17, prefix:, end_time:Tue, 29 Mar 2022 09:39:22 GMT, manifest_version:2.0.0, version:7.17.2-SNAPSHOT, branch:7.17, build_id:7.17.2-a218ac35, build_duration_seconds:15919]
=> [automation] update elastic stack version for testing 7.17.2-a218ac35

.ci/packaging.groovy, .ci/packer_cache.sh
Faster builds with:
1) less duplicated checkout
The first step is not required since we use stash/unstash to copy the workspace between stages and workers.
2) cached docker images
=> ci: speed up packaging and DRA

.ci/packaging.groovy
### What
DRA failures are different than package failures, therefore, let's add who to contact with if further analysis is required.
DRA is a black box so only the system owners know about it, therefore the product teams need to care only for the package generation in case something fails, otherwise, redirect the failures to the system owners.
Do we want to notify to the system owners by email/slack?
=> dra: add who to contact with if a DRA or package failure

NOTICE.txt, go.mod, go.sum
Updates the `go-elasticsearch` client to the latest published.
=> mod: Update `elastic/go-elasticsearch/v8@v8.1.0`

.ci/jobs/apm-server-check-changelogs-mbp.yml, .ci/jobs/apm-server-check-packages-mbp.yml, .ci/jobs/apm-server-mbp.yml, .ci/jobs/update-beats-mbp.yml, Jenkinsfile
Remove tags from the CI builds
Remove 6.8 and =< 7.16 branch references
Tags are coming from a particular commit from any release branch therefore they are already verified in the CI. 
If some flakiness then those errors will remain forever in the build dashboards.
Reduce the cost for building commits that have been already verified in the CI.
=> jjbb: remove tags and update branches

docker-compose.yml
[start_time:Thu, 31 Mar 2022 12:15:08 GMT, release_branch:master, prefix:, end_time:Fri, 1 Apr 2022 02:36:15 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-1ecd9720, build_duration_seconds:51667]
=> [automation] update elastic stack version for testing 8.3.0-1ecd9720

docker-compose.yml
[start_time:Fri, 1 Apr 2022 00:14:24 GMT, release_branch:8.2, prefix:, end_time:Fri, 1 Apr 2022 04:48:29 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-5d1042d1, build_duration_seconds:16445]
=> [automation] update elastic stack version for testing 8.2.0-5d1042d1

docker-compose.yml
[start_time:Thu, 31 Mar 2022 05:14:06 GMT, release_branch:8.1, prefix:, end_time:Thu, 31 Mar 2022 10:03:46 GMT, manifest_version:2.0.0, version:8.1.2-SNAPSHOT, branch:8.1, build_id:8.1.2-ed029c28, build_duration_seconds:17380]
=> [automation] update elastic stack version for testing 8.1.2-ed029c28

docker-compose.yml
[start_time:Thu, 31 Mar 2022 23:59:41 GMT, release_branch:7.17, prefix:, end_time:Fri, 1 Apr 2022 04:14:55 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-22be2d34, build_duration_seconds:15314]
=> [automation] update elastic stack version for testing 7.17.3-22be2d34

docs/features.asciidoc, docs/legacy/guide/opentracing.asciidoc
For https://github.com/elastic/apm-aws-lambda/pull/158#issuecomment-1078409137.
=> docs: Update anchor link to new AWS Lambda docs

docker-compose.yml
[start_time:Mon, 4 Apr 2022 00:16:03 GMT, release_branch:8.2, prefix:, end_time:Mon, 4 Apr 2022 04:36:18 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-f531236e, build_duration_seconds:15615]
=> [automation] update elastic stack version for testing 8.2.0-f531236e

docker-compose.yml
[start_time:Fri, 1 Apr 2022 12:14:43 GMT, release_branch:master, prefix:, end_time:Fri, 1 Apr 2022 16:30:17 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-4cd86339, build_duration_seconds:15334]
=> [automation] update elastic stack version for testing 8.3.0-4cd86339

docker-compose.yml
[start_time:Sun, 3 Apr 2022 05:15:58 GMT, release_branch:7.17, prefix:, end_time:Sun, 3 Apr 2022 09:36:08 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-42e5086c, build_duration_seconds:15610]
=> [automation] update elastic stack version for testing 7.17.3-42e5086c

docker-compose.yml
[start_time:Mon, 4 Apr 2022 17:09:42 GMT, release_branch:8.1, prefix:, end_time:Mon, 4 Apr 2022 23:29:35 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-4eb9bf7f, build_duration_seconds:22793]
=> [automation] update elastic stack version for testing 8.1.3-4eb9bf7f

docker-compose.yml
[start_time:Mon, 4 Apr 2022 15:09:13 GMT, release_branch:master, prefix:, end_time:Mon, 4 Apr 2022 21:39:53 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-657f2d50, build_duration_seconds:23440]
=> [automation] update elastic stack version for testing 8.3.0-657f2d50

docker-compose.yml
[start_time:Mon, 4 Apr 2022 05:13:27 GMT, release_branch:7.17, prefix:, end_time:Mon, 4 Apr 2022 09:40:51 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-206df1ed, build_duration_seconds:16044]
=> [automation] update elastic stack version for testing 7.17.3-206df1ed

.ci/packer_cache.sh
Fix permissions to help with tearing down the workspace
The `packer-cache` process fails when deleting the workspace to move forward to the next caching repository.
```
INFO:     googlecompute: TASK [packer_cache : run the packer_cache.sh script from apm-server.git repo] ***
INFO:     googlecompute: changed: [default]
INFO:     googlecompute:
INFO:     googlecompute: TASK [packer_cache : remove the apm-server.git reference repository shallow clone] ***
INFO:     googlecompute: fatal: [default]: FAILED! => {"changed": false, "msg": "rmtree failed: [Errno 13] Permission denied: '/tmp/apm-server.git/x-pack/apm-server.git/build/golang-crossbuild'"}
INFO:     googlecompute:
INFO:     googlecompute: PLAY RECAP *********************************************************************
INFO: …
```
=> packer_cache: restore permissions and ownership

docker-compose.yml
[start_time:Tue, 5 Apr 2022 05:17:15 GMT, release_branch:8.1, prefix:, end_time:Tue, 5 Apr 2022 11:40:01 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-c3f4b7e6, build_duration_seconds:22966]
=> [automation] update elastic stack version for testing 8.1.3-c3f4b7e6

docker-compose.yml
[start_time:Wed, 6 Apr 2022 00:18:20 GMT, release_branch:8.2, prefix:, end_time:Wed, 6 Apr 2022 04:10:23 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-fdfc79e3, build_duration_seconds:13923]
=> [automation] update elastic stack version for testing 8.2.0-fdfc79e3

docker-compose.yml
[start_time:Tue, 5 Apr 2022 05:14:45 GMT, release_branch:7.17, prefix:, end_time:Tue, 5 Apr 2022 10:51:34 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-60b577ee, build_duration_seconds:20209]
=> [automation] update elastic stack version for testing 7.17.3-60b577ee

docker-compose.yml
[start_time:Tue, 5 Apr 2022 22:51:10 GMT, release_branch:master, prefix:, end_time:Wed, 6 Apr 2022 02:52:40 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-00f4f855, build_duration_seconds:14490]
=> [automation] update elastic stack version for testing 8.3.0-00f4f855

beater/api/mux.go, beater/server_test.go
Fix `/debug/pprof` routes, which were broken in https://github.com/elastic/apm-server/pull/7679.
~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)~ (fixes unreleased code)
1. Run apm-server with `apm-server.pprof.enabled: true`
2. Open browser, navigate to `<base-url>/debug/pprof`
3. Click the links, check they all work
None
=> beater: fix pprof endpoints

docker-compose.yml
[start_time:Wed, 6 Apr 2022 17:14:24 GMT, release_branch:8.1, prefix:, end_time:Wed, 6 Apr 2022 23:18:37 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-6f211282, build_duration_seconds:21853]
=> [automation] update elastic stack version for testing 8.1.3-6f211282

docker-compose.yml
[start_time:Thu, 7 Apr 2022 00:14:34 GMT, release_branch:master, prefix:, end_time:Thu, 7 Apr 2022 04:42:19 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-5bb6f468, build_duration_seconds:16065]
=> [automation] update elastic stack version for testing 8.3.0-5bb6f468

docker-compose.yml
[start_time:Thu, 7 Apr 2022 00:14:27 GMT, release_branch:8.2, prefix:, end_time:Thu, 7 Apr 2022 04:19:11 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-c56d8262, build_duration_seconds:14684]
=> [automation] update elastic stack version for testing 8.2.0-c56d8262

docker-compose.yml
[start_time:Wed, 6 Apr 2022 05:13:42 GMT, release_branch:7.17, prefix:, end_time:Wed, 6 Apr 2022 10:15:41 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-0bbada2a, build_duration_seconds:18119]
=> [automation] update elastic stack version for testing 7.17.3-0bbada2a

docker-compose.yml
[start_time:Thu, 7 Apr 2022 12:18:03 GMT, release_branch:8.2, prefix:, end_time:Thu, 7 Apr 2022 16:58:01 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-4df380a5, build_duration_seconds:16798]
=> [automation] update elastic stack version for testing 8.2.0-4df380a5

docker-compose.yml
[start_time:Thu, 7 Apr 2022 17:14:25 GMT, release_branch:8.1, prefix:, end_time:Thu, 7 Apr 2022 22:02:39 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-25093d2a, build_duration_seconds:17294]
=> [automation] update elastic stack version for testing 8.1.3-25093d2a

docker-compose.yml
[start_time:Thu, 7 Apr 2022 12:14:18 GMT, release_branch:master, prefix:, end_time:Thu, 7 Apr 2022 16:41:59 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-76e0128f, build_duration_seconds:16061]
=> [automation] update elastic stack version for testing 8.3.0-76e0128f

docker-compose.yml
[start_time:Thu, 7 Apr 2022 05:13:51 GMT, release_branch:7.17, prefix:, end_time:Thu, 7 Apr 2022 09:37:56 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-2d046908, build_duration_seconds:15845]
=> [automation] update elastic stack version for testing 7.17.3-2d046908

docker-compose.yml
[start_time:Mon, 11 Apr 2022 17:16:15 GMT, release_branch:8.1, prefix:, end_time:Mon, 11 Apr 2022 22:18:25 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-9689383f, build_duration_seconds:18130]
=> [automation] update elastic stack version for testing 8.1.3-9689383f

docker-compose.yml
[start_time:Mon, 11 Apr 2022 05:13:53 GMT, release_branch:7.17, prefix:, end_time:Mon, 11 Apr 2022 09:37:04 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-860249fc, build_duration_seconds:15791]
=> [automation] update elastic stack version for testing 7.17.3-860249fc

docker-compose.yml
[start_time:Mon, 11 Apr 2022 00:14:24 GMT, release_branch:8.2, prefix:, end_time:Mon, 11 Apr 2022 04:46:29 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-bcbc1a13, build_duration_seconds:16325]
=> [automation] update elastic stack version for testing 8.2.0-bcbc1a13

changelogs/8.1.asciidoc
This will backport the following commits from `8.1` to `main`:
- [[8.1] Add `8.1.3` release notes (#7857)](https://github.com/elastic/apm-server/pull/7857)
=> [main] [8.1] Add `8.1.3` release notes (#7857)

docker-compose.yml
[start_time:Tue, 12 Apr 2022 13:46:39 GMT, release_branch:8.2, prefix:, end_time:Tue, 12 Apr 2022 18:03:38 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-a99722cc, build_duration_seconds:15419]
=> [automation] update elastic stack version for testing 8.2.0-a99722cc

docker-compose.yml
[start_time:Tue, 12 Apr 2022 17:15:08 GMT, release_branch:8.1, prefix:, end_time:Tue, 12 Apr 2022 22:06:07 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-f8a17b61, build_duration_seconds:17459]
=> [automation] update elastic stack version for testing 8.1.3-f8a17b61

docker-compose.yml
[start_time:Tue, 12 Apr 2022 05:14:19 GMT, release_branch:7.17, prefix:, end_time:Tue, 12 Apr 2022 09:40:43 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-b688e1c0, build_duration_seconds:15984]
=> [automation] update elastic stack version for testing 7.17.3-b688e1c0

changelogs/7.17.asciidoc
Adds 7.17.3 release notes based on https://github.com/elastic/apm-server/commits/7.17.
There are a few PRs that made it into this version, but none include changelog entries.
=> [7.17] 7.17.3 release notes

docker-compose.yml
[start_time:Thu, 14 Apr 2022 00:15:10 GMT, release_branch:8.2, prefix:, end_time:Thu, 14 Apr 2022 04:33:43 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-39d3fe7f, build_duration_seconds:15513]
=> [automation] update elastic stack version for testing 8.2.0-39d3fe7f

docker-compose.yml
[start_time:Wed, 13 Apr 2022 17:14:22 GMT, release_branch:8.1, prefix:, end_time:Wed, 13 Apr 2022 22:07:19 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-bb164e02, build_duration_seconds:17577]
=> [automation] update elastic stack version for testing 8.1.3-bb164e02

docker-compose.yml
[start_time:Thu, 14 Apr 2022 00:14:21 GMT, release_branch:master, prefix:, end_time:Thu, 14 Apr 2022 04:44:55 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-4be61f32, build_duration_seconds:16234]
=> [automation] update elastic stack version for testing 8.3.0-4be61f32

docker-compose.yml
[start_time:Wed, 13 Apr 2022 05:18:04 GMT, release_branch:7.17, prefix:, end_time:Wed, 13 Apr 2022 09:40:55 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-d599ee07, build_duration_seconds:15771]
=> [automation] update elastic stack version for testing 7.17.3-d599ee07

dev_docs/tbs.md
Add initial document describing how tail-based sampling works.
Closes #7646
=> dev_docs: add tail-based sampling doc

docker-compose.yml
[start_time:Fri, 15 Apr 2022 00:14:25 GMT, release_branch:8.2, prefix:, end_time:Fri, 15 Apr 2022 04:41:47 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-edf55ea1, build_duration_seconds:16042]
=> [automation] update elastic stack version for testing 8.2.0-edf55ea1

docker-compose.yml
[start_time:Thu, 14 Apr 2022 17:14:17 GMT, release_branch:8.1, prefix:, end_time:Thu, 14 Apr 2022 22:27:58 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-5c80e943, build_duration_seconds:18821]
=> [automation] update elastic stack version for testing 8.1.3-5c80e943

docker-compose.yml
[start_time:Thu, 14 Apr 2022 05:13:25 GMT, release_branch:7.17, prefix:, end_time:Thu, 14 Apr 2022 09:41:47 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-a0d290fb, build_duration_seconds:16102]
=> [automation] update elastic stack version for testing 7.17.3-a0d290fb

docker-compose.yml
[start_time:Sun, 17 Apr 2022 00:14:24 GMT, release_branch:8.2, prefix:, end_time:Sun, 17 Apr 2022 03:54:27 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-c65cb8e3, build_duration_seconds:13203]
=> [automation] update elastic stack version for testing 8.2.0-c65cb8e3

docker-compose.yml
[start_time:Sun, 17 Apr 2022 05:15:42 GMT, release_branch:8.1, prefix:, end_time:Sun, 17 Apr 2022 09:59:44 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-28740185, build_duration_seconds:17042]
=> [automation] update elastic stack version for testing 8.1.3-28740185

docker-compose.yml
[start_time:Mon, 18 Apr 2022 00:16:09 GMT, release_branch:master, prefix:, end_time:Mon, 18 Apr 2022 04:26:43 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-c655cda8, build_duration_seconds:15034]
=> [automation] update elastic stack version for testing 8.3.0-c655cda8

docker-compose.yml
[start_time:Sun, 17 Apr 2022 05:15:36 GMT, release_branch:7.17, prefix:, end_time:Sun, 17 Apr 2022 09:36:49 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-feda78d8, build_duration_seconds:15673]
=> [automation] update elastic stack version for testing 7.17.3-feda78d8

docker-compose.yml
[start_time:Tue, 19 Apr 2022 00:14:07 GMT, release_branch:8.2, prefix:, end_time:Tue, 19 Apr 2022 04:50:58 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-3a7e2f99, build_duration_seconds:16611]
=> [automation] update elastic stack version for testing 8.2.0-3a7e2f99

docker-compose.yml
[start_time:Mon, 18 Apr 2022 17:13:56 GMT, release_branch:8.1, prefix:, end_time:Mon, 18 Apr 2022 22:15:30 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-2a8b1f31, build_duration_seconds:18094]
=> [automation] update elastic stack version for testing 8.1.3-2a8b1f31

docker-compose.yml
[start_time:Tue, 19 Apr 2022 05:14:50 GMT, release_branch:8.1, prefix:, end_time:Tue, 19 Apr 2022 10:13:34 GMT, manifest_version:2.0.0, version:8.1.3-SNAPSHOT, branch:8.1, build_id:8.1.3-0c4e7b42, build_duration_seconds:17924]
=> [automation] update elastic stack version for testing 8.1.3-0c4e7b42

docker-compose.yml
[start_time:Wed, 20 Apr 2022 00:15:12 GMT, release_branch:8.2, prefix:, end_time:Wed, 20 Apr 2022 04:28:47 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-a7e9513d, build_duration_seconds:15215]
=> [automation] update elastic stack version for testing 8.2.0-a7e9513d

docker-compose.yml
[start_time:Tue, 19 Apr 2022 05:13:48 GMT, release_branch:7.17, prefix:, end_time:Tue, 19 Apr 2022 09:34:18 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-b148b9ca, build_duration_seconds:15630]
=> [automation] update elastic stack version for testing 7.17.3-b148b9ca

docker-compose.yml
[start_time:Wed, 20 Apr 2022 12:14:52 GMT, release_branch:8.2, prefix:, end_time:Wed, 20 Apr 2022 17:25:38 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-000e1c18, build_duration_seconds:18646]
=> [automation] update elastic stack version for testing 8.2.0-000e1c18

docker-compose.yml
[start_time:Wed, 20 Apr 2022 05:14:24 GMT, release_branch:7.17, prefix:, end_time:Wed, 20 Apr 2022 09:46:03 GMT, manifest_version:2.0.0, version:7.17.3-SNAPSHOT, branch:7.17, build_id:7.17.3-e9aee937, build_duration_seconds:16299]
=> [automation] update elastic stack version for testing 7.17.3-e9aee937

docs/legacy/copied-from-beats/docs/loggingconfig.asciidoc
Updates the `logging.files.permissions` examples to `0640` and `0600` and explains that the most permissive mask allowed is `0640` per https://github.com/elastic/beats/pull/28347.
* Closes https://github.com/elastic/apm-server/issues/5899.
=> docs: Update `logging.files.permissions` to consider umask

docs/data-model.asciidoc, docs/data-streams.asciidoc
This PR updates the [Data model](https://www.elastic.co/guide/en/apm/guide/current/data-model.html) documentation to include:
Note: I chose to ~minimize~ collapse the sample documents in collapsable blocks as some of them are quite long.
* Closes https://github.com/elastic/apm-server/issues/7431.
=> docs: Add sample APM documents

docker-compose.yml
[start_time:Fri, 22 Apr 2022 00:17:53 GMT, release_branch:8.2, prefix:, end_time:Fri, 22 Apr 2022 04:06:59 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-c47183cf, build_duration_seconds:13746]
=> [automation] update elastic stack version for testing 8.2.0-c47183cf

docker-compose.yml
[start_time:Thu, 21 Apr 2022 17:14:13 GMT, release_branch:8.1, prefix:, end_time:Thu, 21 Apr 2022 22:02:49 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-4911e5d4, build_duration_seconds:17316]
=> [automation] update elastic stack version for testing 8.1.4-4911e5d4

docker-compose.yml
[start_time:Thu, 21 Apr 2022 13:49:29 GMT, release_branch:7.17, prefix:, end_time:Thu, 21 Apr 2022 18:20:44 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-51efa5cc, build_duration_seconds:16275]
=> [automation] update elastic stack version for testing 7.17.4-51efa5cc

docker-compose.yml
[start_time:Mon, 25 Apr 2022 00:16:18 GMT, release_branch:8.2, prefix:, end_time:Mon, 25 Apr 2022 04:48:40 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-14a8abdc, build_duration_seconds:16342]
=> [automation] update elastic stack version for testing 8.2.0-14a8abdc

docker-compose.yml
[start_time:Sun, 24 Apr 2022 05:16:18 GMT, release_branch:8.1, prefix:, end_time:Sun, 24 Apr 2022 10:04:19 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-bc369beb, build_duration_seconds:17281]
=> [automation] update elastic stack version for testing 8.1.4-bc369beb

.ci/packaging.groovy
Cosmetic change to visualise the `DRA` stage in two stages:
- DRA snapshot
- DRA staging
=> ci: split dra meta-stage in two stages

docker-compose.yml
[start_time:Mon, 25 Apr 2022 17:13:58 GMT, release_branch:8.1, prefix:, end_time:Mon, 25 Apr 2022 23:03:47 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-96de35ab, build_duration_seconds:20989]
=> [automation] update elastic stack version for testing 8.1.4-96de35ab

docker-compose.yml
[start_time:Mon, 25 Apr 2022 18:54:34 GMT, release_branch:7.17, prefix:, end_time:Mon, 25 Apr 2022 23:36:22 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-073e030e, build_duration_seconds:16908]
=> [automation] update elastic stack version for testing 7.17.4-073e030e

docker-compose.yml
[start_time:Tue, 26 Apr 2022 00:14:18 GMT, release_branch:8.2, prefix:, end_time:Tue, 26 Apr 2022 04:06:52 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-63f66f47, build_duration_seconds:13954]
=> [automation] update elastic stack version for testing 8.2.0-63f66f47

docker-compose.yml
[start_time:Tue, 26 Apr 2022 05:14:12 GMT, release_branch:8.1, prefix:, end_time:Tue, 26 Apr 2022 10:33:45 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-483e60fd, build_duration_seconds:19173]
=> [automation] update elastic stack version for testing 8.1.4-483e60fd

docker-compose.yml
[start_time:Tue, 26 Apr 2022 12:14:51 GMT, release_branch:8.2, prefix:, end_time:Tue, 26 Apr 2022 16:38:24 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-bdd1c93d, build_duration_seconds:15813]
=> [automation] update elastic stack version for testing 8.2.0-bdd1c93d

docker-compose.yml
[start_time:Tue, 26 Apr 2022 05:13:44 GMT, release_branch:7.17, prefix:, end_time:Tue, 26 Apr 2022 09:41:06 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-a30db1f9, build_duration_seconds:16042]
=> [automation] update elastic stack version for testing 7.17.4-a30db1f9

docker-compose.yml
[start_time:Thu, 28 Apr 2022 00:14:27 GMT, release_branch:8.2, prefix:, end_time:Thu, 28 Apr 2022 04:56:07 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-8b4cfac3, build_duration_seconds:16900]
=> [automation] update elastic stack version for testing 8.2.0-8b4cfac3

.ci/packaging.groovy, Jenkinsfile
Use the downstream pattern to run the packaging pipeline and then pass over the Git commit to be used.
The parentstream pattern does not support the Git commit approach by default and therefore it requires further changes to accomplish the same.
In the CI.
When the `packaging` pipeline runs there is a chance that a new commit has been pushed to the `main` branch before the `packaging` has even get triggered, therefore the `packaging` pipeline will run but it will not use the original commit.
While using the downtream pattern, then we can orchestrate what builds to run from the `main pipeline` and the pass the sha commit to those jobs. 
I can set the commit to be used:
JJBB to be configured with 
```yaml
property-strategies:
all-branches:
- suppress-scm-triggering: true
```
In a follow up, …
=> ci: use downstream pattern

.ci/packaging.groovy
Parentstream pattern didn't work well with https://github.com/elastic/apm-pipeline-library/blob/main/vars/isGitRegionMatch.groovy#L39 
Since a previous build for the same commit was triggered (git push event) but the following build if the main pipeline was built successfully used the same commit therefore it didn't work as expected.
Let's use the native support in jenkins instead in addition to remove the jjbb: scm integration in https://github.com/elastic/apm-server/pull/7996
=> ci: use changeset

apmpackage/apm/agent/input/template.yml.hbs, apmpackage/apm/changelog.yml, apmpackage/apm/manifest.yml
Allow easier debugging by having an option to dynamically set pprof_enabled config for the APM server.
To be tested in combination with the required UI work done for displaying and toggling the `pprof_enabled` toggle from UI.
#7733
=> Add pprof_enabled config option

docker-compose.yml
[start_time:Thu, 28 Apr 2022 12:14:16 GMT, release_branch:8.2, prefix:, end_time:Thu, 28 Apr 2022 16:53:35 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-2c25c9de, build_duration_seconds:16759]
=> [automation] update elastic stack version for testing 8.2.0-2c25c9de

docker-compose.yml
[start_time:Thu, 28 Apr 2022 17:17:45 GMT, release_branch:8.1, prefix:, end_time:Thu, 28 Apr 2022 21:57:18 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-7b3e4fd0, build_duration_seconds:16773]
=> [automation] update elastic stack version for testing 8.1.4-7b3e4fd0

docker-compose.yml
[start_time:Thu, 28 Apr 2022 10:32:38 GMT, release_branch:7.17, prefix:, end_time:Thu, 28 Apr 2022 15:33:56 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-40d3b33d, build_duration_seconds:18078]
=> [automation] update elastic stack version for testing 7.17.4-40d3b33d

docker-compose.yml
[start_time:Sun, 1 May 2022 17:14:24 GMT, release_branch:8.1, prefix:, end_time:Sun, 1 May 2022 21:57:49 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-76569f3d, build_duration_seconds:17005]
=> [automation] update elastic stack version for testing 8.1.4-76569f3d

docker-compose.yml
[start_time:Mon, 2 May 2022 00:16:36 GMT, release_branch:8.2, prefix:, end_time:Mon, 2 May 2022 04:26:56 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-e7ad9ef0, build_duration_seconds:15020]
=> [automation] update elastic stack version for testing 8.2.0-e7ad9ef0

docker-compose.yml
[start_time:Sat, 30 Apr 2022 05:17:17 GMT, release_branch:7.17, prefix:, end_time:Sat, 30 Apr 2022 09:48:12 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-ed667030, build_duration_seconds:16255]
=> [automation] update elastic stack version for testing 7.17.4-ed667030

docs/common-problems.asciidoc, docs/legacy/common-problems.asciidoc, docs/troubleshoot-apm.asciidoc
Fixes attributes in the documentation.
Follow-up to https://github.com/elastic/apm-server/pull/7901.
=> docs: fix attributes

docker-compose.yml
[start_time:Mon, 2 May 2022 17:14:27 GMT, release_branch:8.1, prefix:, end_time:Mon, 2 May 2022 22:11:28 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-1cdc80b6, build_duration_seconds:17821]
=> [automation] update elastic stack version for testing 8.1.4-1cdc80b6

docker-compose.yml
[start_time:Tue, 3 May 2022 00:14:07 GMT, release_branch:8.2, prefix:, end_time:Tue, 3 May 2022 04:22:51 GMT, manifest_version:2.0.0, version:8.2.0-SNAPSHOT, branch:8.2, build_id:8.2.0-56396fd0, build_duration_seconds:14924]
=> [automation] update elastic stack version for testing 8.2.0-56396fd0

docker-compose.yml
[start_time:Mon, 2 May 2022 05:13:36 GMT, release_branch:7.17, prefix:, end_time:Mon, 2 May 2022 20:26:46 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-9ca33e9a, build_duration_seconds:54790]
=> [automation] update elastic stack version for testing 7.17.4-9ca33e9a

docker-compose.yml
[start_time:Tue, 3 May 2022 17:14:34 GMT, release_branch:8.1, prefix:, end_time:Tue, 3 May 2022 21:52:16 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-86899ed7, build_duration_seconds:16662]
=> [automation] update elastic stack version for testing 8.1.4-86899ed7

docker-compose.yml
[start_time:Wed, 4 May 2022 00:14:21 GMT, release_branch:master, prefix:, end_time:Wed, 4 May 2022 04:11:39 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-7f585873, build_duration_seconds:14238]
=> [automation] update elastic stack version for testing 8.3.0-7f585873

docker-compose.yml
[start_time:Wed, 4 May 2022 17:14:07 GMT, release_branch:8.1, prefix:, end_time:Wed, 4 May 2022 21:55:27 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-37d447ec, build_duration_seconds:16880]
=> [automation] update elastic stack version for testing 8.1.4-37d447ec

.ci/packaging.groovy, .ci/scripts/Makefile
Changes in the packaging.groovy should not trigger the apmpackage stage. Additionally if no changes to be applied then do nothing, otherwise `gh` will fail if creating a PR without changes.
Given the changes in this particular PR and the below patch:
```diff
diff --git a/.ci/scripts/Makefile b/.ci/scripts/Makefile
index e6853614f..c3c17ebbb 100644
--- a/.ci/scripts/Makefile
+++ b/.ci/scripts/Makefile
@@ -42,6 +42,7 @@ create-package-storage-pull-request:
--label automation \
--base snapshot \
--head $(PACKAGE_STORAGE_BRANCH) \
+			--repo v1v/package-storage \
--reviewer elastic/apm-server || true ; \
```
A branch was created:
```
make -C .ci/scripts create-package-storage-pull-request
INFO: create branch
Switched to a new branch 'update-apm-20220505092108'
INFO: add files if any
INFO: any …
```
=> packaging: exclude the pipeline

docker-compose.yml
[start_time:Thu, 5 May 2022 05:15:40 GMT, release_branch:8.1, prefix:, end_time:Thu, 5 May 2022 10:14:39 GMT, manifest_version:2.0.0, version:8.1.4-SNAPSHOT, branch:8.1, build_id:8.1.4-6c818705, build_duration_seconds:17939]
=> [automation] update elastic stack version for testing 8.1.4-6c818705

docker-compose.yml
[start_time:Fri, 6 May 2022 00:14:54 GMT, release_branch:master, prefix:, end_time:Fri, 6 May 2022 04:20:36 GMT, manifest_version:2.0.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-6ba9f710, build_duration_seconds:14742]
=> [automation] update elastic stack version for testing 8.3.0-6ba9f710

docker-compose.yml
[start_time:Thu, 5 May 2022 05:15:38 GMT, release_branch:7.17, prefix:, end_time:Thu, 5 May 2022 09:50:15 GMT, manifest_version:2.0.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-2fe5353f, build_duration_seconds:16477]
=> [automation] update elastic stack version for testing 7.17.4-2fe5353f

beater/beater.go, changelogs/head.asciidoc
make the number of bulk requests in the
modelindexer configurable via
`output.elasticsearch.max_requests`
Configure `output.elasticsearch.max_requests` and set `http.enabled=true`. Start the apm-server, curl the stats endpoint, and confirm that the number of available bulk requests matches the amount configured:
```
{
"available": 25,
"completed": 0
}
```
closes #7719
=> support `output.elasticsearch.max_requests`

docker-compose.yml
[start_time:Mon, 9 May 2022 00:15:37 GMT, release_branch:master, prefix:, end_time:Mon, 9 May 2022 04:31:25 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-5c1ff35f, build_duration_seconds:15348]
=> [automation] update elastic stack version for testing 8.3.0-5c1ff35f

docker-compose.yml
[start_time:Sat, 7 May 2022 05:15:45 GMT, release_branch:7.17, prefix:, end_time:Sat, 7 May 2022 09:42:44 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-1ffd290e, build_duration_seconds:16019]
=> [automation] update elastic stack version for testing 7.17.4-1ffd290e

systemtest/apikeycmd_test.go, systemtest/apmservertest/command.go, systemtest/apmservertest/server.go, systemtest/export_test.go
Attempting to short-circuit cleaning up the apm-server when the system gets stuck waiting
from https://github.com/elastic/apm-server/issues/7564:
```
[2022-03-17T06:33:38.633Z] goroutine 1885 [syscall, 17 minutes]:
[2022-03-17T06:33:38.633Z] syscall.Syscall6(0xf7, 0x1, 0x90ce, 0xc000247bd0, 0x1000004, 0x0, 0x0)
[2022-03-17T06:33:38.633Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-7561/.gvm/versions/go1.17.6.linux.amd64/src/syscall/asm_linux_amd64.s:43 +0x5
[2022-03-17T06:33:38.633Z] os.(*Process).blockUntilWaitable(0xc0024cdc80)
[2022-03-17T06:33:38.633Z] 	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-7561/.gvm/versions/go1.17.6.linux.amd64/src/os/wait_waitid.go:33 +0x9c
[2022-03-17T06:33:38.633Z] os.(*Process).wait(0xc0024cdc80)
[2022-03-17T06:33:38.633Z] …
```
=> cancel server process context after timeout

docker-compose.yml
[start_time:Tue, 10 May 2022 00:14:18 GMT, release_branch:master, prefix:, end_time:Tue, 10 May 2022 04:17:54 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-d380914f, build_duration_seconds:14616]
=> [automation] update elastic stack version for testing 8.3.0-d380914f

docker-compose.yml
[start_time:Tue, 10 May 2022 00:14:30 GMT, release_branch:8.2, prefix:, end_time:Tue, 10 May 2022 03:56:53 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-d6d75d75, build_duration_seconds:13343]
=> [automation] update elastic stack version for testing 8.2.1-d6d75d75

docker-compose.yml
[start_time:Mon, 9 May 2022 05:13:19 GMT, release_branch:7.17, prefix:, end_time:Mon, 9 May 2022 09:41:04 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-37e626ca, build_duration_seconds:16065]
=> [automation] update elastic stack version for testing 7.17.4-37e626ca

docker-compose.yml
[start_time:Tue, 10 May 2022 12:14:03 GMT, release_branch:8.2, prefix:, end_time:Tue, 10 May 2022 17:09:44 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-2eb01953, build_duration_seconds:17741]
=> [automation] update elastic stack version for testing 8.2.1-2eb01953

docker-compose.yml
[start_time:Tue, 10 May 2022 12:14:28 GMT, release_branch:master, prefix:, end_time:Tue, 10 May 2022 19:41:55 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-53513548, build_duration_seconds:26847]
=> [automation] update elastic stack version for testing 8.3.0-53513548

beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json, beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json, beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json, beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json, changelogs/head.asciidoc, processor/stream/processor.go, processor/stream/processor_test.go, processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationOpenTelemetryBridge.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json, processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json, systemtest/approvals/TestApprovedMetrics.approved.json
Fixes a bug introduced in #6682 by performing a copy of the `baseEvent`
before each of the events is decoded. The event was being shallow copied
and it was reusing the same maps between batches.
The linked PR changed the behavior (although not in a very obviously)
and was instead merging the labels onto the passed `APMEvent`. This
patch reintroduces the previous behavior in a more obvious manner.
1. `docker-compose up -d` and install the APM Integration
2. `make && ./apm-server -E output.elasticsearch.username=admin -E output.elasticsearch.password=changeme -E …
=> processor: Avoid leaking labels between batches

docker-compose.yml
[start_time:Wed, 11 May 2022 12:17:18 GMT, release_branch:8.2, prefix:, end_time:Wed, 11 May 2022 16:33:31 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-91d7a53f, build_duration_seconds:15373]
=> [automation] update elastic stack version for testing 8.2.1-91d7a53f

docker-compose.yml
[start_time:Thu, 12 May 2022 00:16:52 GMT, release_branch:master, prefix:, end_time:Thu, 12 May 2022 04:33:47 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-8ee1196f, build_duration_seconds:15415]
=> [automation] update elastic stack version for testing 8.3.0-8ee1196f

docker-compose.yml
[start_time:Fri, 13 May 2022 00:14:17 GMT, release_branch:8.2, prefix:, end_time:Fri, 13 May 2022 04:35:01 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-05a5ca87, build_duration_seconds:15644]
=> [automation] update elastic stack version for testing 8.2.1-05a5ca87

docker-compose.yml
[start_time:Thu, 12 May 2022 05:13:48 GMT, release_branch:7.17, prefix:, end_time:Thu, 12 May 2022 09:49:56 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-153c53bf, build_duration_seconds:16568]
=> [automation] update elastic stack version for testing 7.17.4-153c53bf

docker-compose.yml
[start_time:Mon, 16 May 2022 00:17:45 GMT, release_branch:8.2, prefix:, end_time:Mon, 16 May 2022 04:48:36 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-3d12787c, build_duration_seconds:16251]
=> [automation] update elastic stack version for testing 8.2.1-3d12787c

docker-compose.yml
[start_time:Mon, 16 May 2022 00:17:33 GMT, release_branch:master, prefix:, end_time:Mon, 16 May 2022 04:25:53 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-19aba912, build_duration_seconds:14900]
=> [automation] update elastic stack version for testing 8.3.0-19aba912

docker-compose.yml
[start_time:Sun, 15 May 2022 05:16:19 GMT, release_branch:7.17, prefix:, end_time:Sun, 15 May 2022 09:41:05 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-191b5600, build_duration_seconds:15886]
=> [automation] update elastic stack version for testing 7.17.4-191b5600

beater/server_test.go
go1.18 changes the error output message slightly,
which causes the regexp to fail.
update the regexp so it passes for both the old
and new message formats.
example failure:
```
go version go1.18.1 linux/amd64
--- FAIL: TestServerConfigReload (0.06s)
server_test.go:505: 
Error Trace:	server_test.go:505
Error:      	Expect "listen tcp: lookup testing.invalid on 127.0.0.53:53: no such host" to match "listen tcp: lookup testing.invalid: .*"
Test:       	TestServerConfigReload
```
=> update failing regexp for 1.18

docker-compose.yml
[start_time:Tue, 17 May 2022 00:14:25 GMT, release_branch:8.2, prefix:, end_time:Tue, 17 May 2022 04:25:16 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-736d131e, build_duration_seconds:15051]
=> [automation] update elastic stack version for testing 8.2.1-736d131e

docker-compose.yml
[start_time:Mon, 16 May 2022 05:15:27 GMT, release_branch:7.17, prefix:, end_time:Mon, 16 May 2022 09:47:14 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-16fc7c23, build_duration_seconds:16307]
=> [automation] update elastic stack version for testing 7.17.4-16fc7c23

docker-compose.yml
[start_time:Mon, 16 May 2022 12:14:04 GMT, release_branch:master, prefix:, end_time:Mon, 16 May 2022 16:39:55 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-4149272f, build_duration_seconds:15951]
=> [automation] update elastic stack version for testing 8.3.0-4149272f

systemtest/apmservertest/command.go
This fixes system tests on Ubuntu 22.04, where the glibc version is too new for the elastic-agent container image. Without this change, the `apm-server` program cannot be executed; it fails with errors like:
> ```/usr/share/elastic-agent/data/elastic-agent-bd86cc/install/apm-server-8.3.0-SNAPSHOT-linux-x86_64/apm-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/share/elastic-agent/data/elastic-agent-bd86cc/install/apm-server-8.3.0-SNAPSHOT-linux-x86_64/apm-server)```
=> systemtest: build apm-server with cgo disabled

docker-compose.yml
[start_time:Wed, 18 May 2022 00:13:55 GMT, release_branch:master, prefix:, end_time:Wed, 18 May 2022 04:22:31 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-e4aa1f83, build_duration_seconds:14916]
=> [automation] update elastic stack version for testing 8.3.0-e4aa1f83

docker-compose.yml
[start_time:Tue, 17 May 2022 05:13:44 GMT, release_branch:7.17, prefix:, end_time:Tue, 17 May 2022 09:44:39 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-3585da41, build_duration_seconds:16255]
=> [automation] update elastic stack version for testing 7.17.4-3585da41

docker-compose.yml
[start_time:Tue, 17 May 2022 12:16:05 GMT, release_branch:8.2, prefix:, end_time:Tue, 17 May 2022 19:10:52 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-8d9ffca9, build_duration_seconds:24887]
=> [automation] update elastic stack version for testing 8.2.1-8d9ffca9

systemtest/agentconfig_test.go
the client was never timing out, causing it to
sometimes hang forever. add a timeout so the retry
logic can actually be executed.
potentially closes #7243
I've run this successfully ~200 times, with two unique non-timeout failures:
```
fleet_test.go:183:
Error Trace:	fleet_test.go:183
agentconfig_test.go:49
Error:      	Received unexpected error:
failed to start container
Test:       	TestAgentConfig
fleet_test.go:169: elastic-agent logs:
server.go:206: log file: /home/ubuntu/workspace/apm-server/systemtest/logs/TestAgentConfig/apm-server
--- FAIL: TestAgentConfig (16.01s)
```
And then another error when making the agent config request to the container, which the retry handles now:
```
=== RUN   TestAgentConfig
2022/05/17 22:38:35 Building image …
```
=> add timeout to http client

TESTING.md, systemtest/cmd/buildapm/main.go, systemtest/containers.go
Adds a new `-cloud` boolean flag, allowing `systemtest/cmd/buildapm` to
package an `apm-server` with local changes into the Elastic Agent for
cloud docker image.
N/A
Read the updated `TESTING.md` and run `buildapm` with the `-cloud` flag set.
Part of #7986
=> buildapm: Add `-cloud` bool flag

docker-compose.yml
[start_time:Wed, 18 May 2022 00:14:22 GMT, release_branch:8.2, prefix:, end_time:Wed, 18 May 2022 09:50:13 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-93582d09, build_duration_seconds:34551]
=> [automation] update elastic stack version for testing 8.2.1-93582d09

docker-compose.yml
[start_time:Wed, 18 May 2022 05:16:05 GMT, release_branch:7.17, prefix:, end_time:Wed, 18 May 2022 09:43:59 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-16f62393, build_duration_seconds:16074]
=> [automation] update elastic stack version for testing 7.17.4-16f62393

docs/legacy/storage-management.asciidoc, docs/manage-storage.asciidoc
This PR updates our legacy and current `_delete_by_query` and `_update_by_query` examples. More delete by query examples are coming in https://github.com/elastic/apm-server/pull/8043. 
* Closes https://github.com/elastic/apm-server/issues/7823.
* Related to https://github.com/elastic/apm-server/pull/8145.
=> docs: Update delete and update by query examples

docs/legacy/ssl-input-settings.asciidoc
This is a small PR that adds the Java agent to the list of agents that support sending client certificates.
* Closes https://github.com/elastic/apm-server/issues/8057.
=> docs: add and link to java agent cert docs

docker-compose.yml
[start_time:Thu, 19 May 2022 12:14:10 GMT, release_branch:master, prefix:, end_time:Thu, 19 May 2022 16:51:05 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-d754f94f, build_duration_seconds:16615]
=> [automation] update elastic stack version for testing 8.3.0-d754f94f

docker-compose.yml
[start_time:Thu, 19 May 2022 12:14:07 GMT, release_branch:8.2, prefix:, end_time:Thu, 19 May 2022 16:42:43 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-54274789, build_duration_seconds:16116]
=> [automation] update elastic stack version for testing 8.2.1-54274789

docker-compose.yml
[start_time:Thu, 19 May 2022 05:13:11 GMT, release_branch:7.17, prefix:, end_time:Thu, 19 May 2022 09:41:16 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-60cd01b1, build_duration_seconds:16085]
=> [automation] update elastic stack version for testing 7.17.4-60cd01b1

docker-compose.yml
[start_time:Fri, 20 May 2022 00:14:54 GMT, release_branch:8.2, prefix:, end_time:Fri, 20 May 2022 05:17:46 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-539cf6f5, build_duration_seconds:18172]
=> [automation] update elastic stack version for testing 8.2.1-539cf6f5

docker-compose.yml
[start_time:Fri, 20 May 2022 05:13:43 GMT, release_branch:7.17, prefix:, end_time:Fri, 20 May 2022 09:41:34 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-1170b674, build_duration_seconds:16071]
=> [automation] update elastic stack version for testing 7.17.4-1170b674

x-pack/apm-server/sampling/processor_test.go
Speed up `TestStorageGC` to avoid failures in CI (and just for faster tests in general). Write events in smaller batches, and wait for more than 2 value log files to be created before we wait for garbage collection to trigger.
N/A
Closes https://github.com/elastic/apm-server/issues/8178
=> sampling: speed up TestStorageGC

docker-compose.yml
[start_time:Mon, 23 May 2022 21:11:48 GMT, release_branch:master, prefix:, end_time:Tue, 24 May 2022 01:53:25 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-bf0ad929, build_duration_seconds:16897]
=> [automation] update elastic stack version for testing 8.3.0-bf0ad929

docker-compose.yml
[start_time:Mon, 23 May 2022 12:01:37 GMT, release_branch:7.17, prefix:, end_time:Mon, 23 May 2022 17:12:48 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-1572020b, build_duration_seconds:18671]
=> [automation] update elastic stack version for testing 7.17.4-1572020b

docker-compose.yml
[start_time:Mon, 23 May 2022 20:52:44 GMT, release_branch:8.2, prefix:, end_time:Tue, 24 May 2022 01:04:12 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-e97da867, build_duration_seconds:15088]
=> [automation] update elastic stack version for testing 8.2.1-e97da867

docker-compose.yml
[start_time:Tue, 24 May 2022 02:05:24 GMT, release_branch:master, prefix:, end_time:Tue, 24 May 2022 06:33:23 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:master, build_id:8.3.0-a2430aec, build_duration_seconds:16079]
=> [automation] update elastic stack version for testing 8.3.0-a2430aec

docker-compose.yml
[start_time:Tue, 24 May 2022 02:15:00 GMT, release_branch:8.2, prefix:, end_time:Tue, 24 May 2022 06:37:00 GMT, manifest_version:2.1.0, version:8.2.1-SNAPSHOT, branch:8.2, build_id:8.2.1-f86dca4c, build_duration_seconds:15720]
=> [automation] update elastic stack version for testing 8.2.1-f86dca4c

docker-compose.yml
[start_time:Tue, 24 May 2022 05:13:32 GMT, release_branch:7.17, prefix:, end_time:Tue, 24 May 2022 09:52:11 GMT, manifest_version:2.1.0, version:7.17.4-SNAPSHOT, branch:7.17, build_id:7.17.4-d3844d00, build_duration_seconds:16719]
=> [automation] update elastic stack version for testing 7.17.4-d3844d00

changelogs/head.asciidoc, x-pack/apm-server/sampling/config.go, x-pack/apm-server/sampling/config_test.go, x-pack/apm-server/sampling/processor.go
Allow 100% tail-based sampling. We shouldn't disallow it, even if it's not optimal.
1. Install Elastic Agent, add the APM integration
2. Send a steady rate of transactions
3. In the integration policy, enable tail-based sampling and set `sample_rate: 1.0`
4. Check that the transaction document throughput does not drop
Closes https://github.com/elastic/apm-server/issues/8222
=> sampling: allow 100% tail-based sampling

docker-compose.yml
[start_time:Mon, 30 May 2022 05:13:42 GMT, release_branch:7.17, prefix:, end_time:Mon, 30 May 2022 09:57:56 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-366dc66d, build_duration_seconds:17054]
=> [automation] update elastic stack version for testing 7.17.5-366dc66d

docker-compose.yml
[start_time:Wed, 1 Jun 2022 00:14:15 GMT, release_branch:8.2, prefix:, end_time:Wed, 1 Jun 2022 04:41:56 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-e78add13, build_duration_seconds:16061]
=> [automation] update elastic stack version for testing 8.2.3-e78add13

docker-compose.yml
[start_time:Tue, 31 May 2022 05:14:09 GMT, release_branch:7.17, prefix:, end_time:Tue, 31 May 2022 09:49:43 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-7c990f83, build_duration_seconds:16534]
=> [automation] update elastic stack version for testing 7.17.5-7c990f83

systemtest/cmd/apmbench/main.go
Adds a new benchmark `BenchmarkAgentAll`, which matches all `*.ndjson`
files. The objective of this benchmark is to have different goroutines
send data from different agents at the same time.
1. `cd systemtest/cmd/apmbench && go build .`
2. `./apmbench -run BenchmarkAgent`
Part of #7540
=> apmbench: Add `BenchmarkAgentAll` benchmark

docker-compose.yml
[start_time:Wed, 1 Jun 2022 12:15:15 GMT, release_branch:8.2, prefix:, end_time:Wed, 1 Jun 2022 17:06:27 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-656a5d89, build_duration_seconds:17472]
=> [automation] update elastic stack version for testing 8.2.3-656a5d89

docker-compose.yml
[start_time:Thu, 2 Jun 2022 00:14:17 GMT, release_branch:master, prefix:, end_time:Thu, 2 Jun 2022 04:55:25 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-df27a645, build_duration_seconds:16868]
=> [automation] update elastic stack version for testing 8.4.0-df27a645

docker-compose.yml
[start_time:Wed, 1 Jun 2022 05:17:20 GMT, release_branch:7.17, prefix:, end_time:Wed, 1 Jun 2022 10:05:38 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-a303ce60, build_duration_seconds:17298]
=> [automation] update elastic stack version for testing 7.17.5-a303ce60

apmpackage/apm/changelog.yml, apmpackage/apm/data_stream/internal_metrics/fields/ecs.yml
Documents added to `metrics-apm.internal-<namespace>` may have `client.ip`, and may require geoIP enrichment. If the geoip ingest processor cannot download the database, it will add a tag to the document. As we do not have the `tags` field defined, and we use strict mapping for this data stream, this leads to an indexing error.
1. Modify docker-compose.yml's Elasticsearch service, adding `ingest.geoip.downloader.enabled=false` to its environment and removing the ingest-geoip volume.
2. Send some metrics to the RUM events endpoint with a public IP set. e.g. `curl -H "X-Real-Ip: 8.8.8.8" -X POST -H Content-Type:application/x-ndjson …
=> Add tags field to internal_metrics data stream

docker-compose.yml
[start_time:Thu, 2 Jun 2022 17:14:59 GMT, release_branch:8.2, prefix:, end_time:Thu, 2 Jun 2022 21:30:17 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-f986a1ff, build_duration_seconds:15318]
=> [automation] update elastic stack version for testing 8.2.3-f986a1ff

docker-compose.yml
[start_time:Fri, 3 Jun 2022 00:14:13 GMT, release_branch:8.3, prefix:, end_time:Fri, 3 Jun 2022 04:06:58 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-378ebcca, build_duration_seconds:13965]
=> [automation] update elastic stack version for testing 8.3.0-378ebcca

docker-compose.yml
[start_time:Thu, 2 Jun 2022 12:14:55 GMT, release_branch:master, prefix:, end_time:Thu, 2 Jun 2022 16:37:25 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-3525aaf7, build_duration_seconds:15750]
=> [automation] update elastic stack version for testing 8.4.0-3525aaf7

docker-compose.yml
[start_time:Thu, 2 Jun 2022 05:14:06 GMT, release_branch:7.17, prefix:, end_time:Thu, 2 Jun 2022 10:20:43 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-f01fee6a, build_duration_seconds:18397]
=> [automation] update elastic stack version for testing 7.17.5-f01fee6a

docker-compose.yml
[start_time:Mon, 6 Jun 2022 00:14:17 GMT, release_branch:8.3, prefix:, end_time:Mon, 6 Jun 2022 04:12:39 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-9596ee28, build_duration_seconds:14302]
=> [automation] update elastic stack version for testing 8.3.0-9596ee28

docker-compose.yml
[start_time:Sun, 5 Jun 2022 05:13:10 GMT, release_branch:7.17, prefix:, end_time:Sun, 5 Jun 2022 10:05:27 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-572a2baf, build_duration_seconds:17537]
=> [automation] update elastic stack version for testing 7.17.5-572a2baf

docker-compose.yml
[start_time:Sun, 5 Jun 2022 12:14:04 GMT, release_branch:master, prefix:, end_time:Sun, 5 Jun 2022 16:34:07 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-42ce0eef, build_duration_seconds:15603]
=> [automation] update elastic stack version for testing 8.4.0-42ce0eef

docker-compose.yml
[start_time:Sun, 5 Jun 2022 05:14:10 GMT, release_branch:8.2, prefix:, end_time:Sun, 5 Jun 2022 09:13:20 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-def79f93, build_duration_seconds:14350]
=> [automation] update elastic stack version for testing 8.2.3-def79f93

apmpackage/apm/changelog.yml, apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.yml, apmpackage/apm/data_stream/app_metrics/manifest.yml, beater/otlp/grpc_test.go, beater/otlp/http_test.go, changelogs/head.asciidoc, model/metricset.go, model/metricset_test.go, processor/otel/metrics.go, processor/otel/metrics_test.go, systemtest/approvals/TestOTLPGRPCMetrics.approved.json, systemtest/otlp_test.go
Add support for summary metrics: a combined count and sum of aggregated measurements, a la Prometheus summaries. We also add partial support for OpenTelemetry summary kind metrics; we store the count and sum, but drop quantiles.
1. Instrument an application with a Prometheus summary metric
1. Using opentelemetry-collector-contrib, scrape Prometheus endpoint with the [prometheus receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver), and export to APM Server as OTLP
1. Check that summary metric is indexed into `metrics-apm.app.*-default` as an `aggregate_metric_double` field type
Closes https://github.com/elastic/apm-server/issues/5359
=> Add support for summary metrics

docker-compose.yml
[start_time:Mon, 6 Jun 2022 13:14:20 GMT, release_branch:8.3, prefix:, end_time:Mon, 6 Jun 2022 17:41:54 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-f530a93f, build_duration_seconds:16054]
=> [automation] update elastic stack version for testing 8.3.0-f530a93f

docker-compose.yml
[start_time:Mon, 6 Jun 2022 05:14:44 GMT, release_branch:7.17, prefix:, end_time:Mon, 6 Jun 2022 09:55:53 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-1c762894, build_duration_seconds:16869]
=> [automation] update elastic stack version for testing 7.17.5-1c762894

docs/upgrading-to-integration.asciidoc
This PR changes our dialog from "upgrade to the APM integration" to "switch to the APM integration". This change is based on feedback linked in https://github.com/elastic/apm-server/issues/8252.
Closes https://github.com/elastic/apm-server/issues/8252.
We don't usually backport doc changes to EOL branches, but I'll take this one back to 7.16.
=> docs: it’s a switch, not an upgrade

docker-compose.yml
[start_time:Wed, 8 Jun 2022 17:14:46 GMT, release_branch:8.2, prefix:, end_time:Wed, 8 Jun 2022 21:22:41 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-a46e98e9, build_duration_seconds:14875]
=> [automation] update elastic stack version for testing 8.2.3-a46e98e9

docker-compose.yml
[start_time:Thu, 9 Jun 2022 00:14:31 GMT, release_branch:master, prefix:, end_time:Thu, 9 Jun 2022 04:45:33 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-3a09e26c, build_duration_seconds:16262]
=> [automation] update elastic stack version for testing 8.4.0-3a09e26c

docker-compose.yml
[start_time:Thu, 9 Jun 2022 00:14:24 GMT, release_branch:8.3, prefix:, end_time:Thu, 9 Jun 2022 04:38:16 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-3c22a7f7, build_duration_seconds:15832]
=> [automation] update elastic stack version for testing 8.3.0-3c22a7f7

docker-compose.yml
[start_time:Tue, 7 Jun 2022 05:13:37 GMT, release_branch:7.17, prefix:, end_time:Tue, 7 Jun 2022 10:32:29 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-dae6f87e, build_duration_seconds:19132]
=> [automation] update elastic stack version for testing 7.17.5-dae6f87e

docker-compose.yml
[start_time:Fri, 10 Jun 2022 00:19:05 GMT, release_branch:8.3, prefix:, end_time:Fri, 10 Jun 2022 04:08:13 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-158b3cba, build_duration_seconds:13748]
=> [automation] update elastic stack version for testing 8.3.0-158b3cba

docker-compose.yml
[start_time:Thu, 9 Jun 2022 05:14:59 GMT, release_branch:8.2, prefix:, end_time:Thu, 9 Jun 2022 09:19:20 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-303333da, build_duration_seconds:14661]
=> [automation] update elastic stack version for testing 8.2.3-303333da

docker-compose.yml
[start_time:Sun, 12 Jun 2022 17:15:28 GMT, release_branch:8.2, prefix:, end_time:Sun, 12 Jun 2022 21:10:17 GMT, manifest_version:2.1.0, version:8.2.3-SNAPSHOT, branch:8.2, build_id:8.2.3-4b95b897, build_duration_seconds:14089]
=> [automation] update elastic stack version for testing 8.2.3-4b95b897

changelogs/8.2.asciidoc
Removes extra space in external doc link.
I've already made this change in the 8.2 and 8.3 backports, so it does not need to be backported.
=> docs: Remove extra space in link

changelogs/head.asciidoc, processor/otel/traces.go, processor/otel/traces_test.go
In some cases, when certain OTel attributes are passed together the results can be indeterministic due to processing inter-dependent fields while ranging over the OTel attribute map.
The following cases have been fixed:
- messaging.system and peer.service for messaging spans
- (net.peer.name OR peer.hostname) and peer.addresss
1. Run the unit test `TestMessagingSpan_DestinationResource` multiple times
```go test processor/otel/traces_test.go -run TestMessagingSpan_DestinationResource -count 15 -v```
2. Observe that they are not flaky
Closes #8351
=> Fix race condition while reading attributes in translate span

docker-compose.yml
[start_time:Tue, 14 Jun 2022 00:14:26 GMT, release_branch:master, prefix:, end_time:Tue, 14 Jun 2022 04:50:43 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-7e67f5d9, build_duration_seconds:16577]
=> [automation] update elastic stack version for testing 8.4.0-7e67f5d9

docker-compose.yml
[start_time:Tue, 14 Jun 2022 00:18:07 GMT, release_branch:8.3, prefix:, end_time:Tue, 14 Jun 2022 04:30:39 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-e4e76686, build_duration_seconds:15152]
=> [automation] update elastic stack version for testing 8.3.0-e4e76686

docker-compose.yml
[start_time:Wed, 15 Jun 2022 00:18:08 GMT, release_branch:8.3, prefix:, end_time:Wed, 15 Jun 2022 04:39:23 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-460dc667, build_duration_seconds:15675]
=> [automation] update elastic stack version for testing 8.3.0-460dc667

Makefile, changelogs/head.asciidoc
Is there anything else required in order to package the Java agent CLI?
=> Upgrading Java agent attacher CLI to 1.32.0

docker-compose.yml
[start_time:Wed, 15 Jun 2022 21:03:18 GMT, release_branch:8.2, prefix:, end_time:Thu, 16 Jun 2022 01:23:46 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-d8d37990, build_duration_seconds:15628]
=> [automation] update elastic stack version for testing 8.2.4-d8d37990

docker-compose.yml
[start_time:Thu, 16 Jun 2022 05:14:05 GMT, release_branch:8.2, prefix:, end_time:Thu, 16 Jun 2022 09:18:56 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-4cc4fbfd, build_duration_seconds:14691]
=> [automation] update elastic stack version for testing 8.2.4-4cc4fbfd

docker-compose.yml
[start_time:Thu, 16 Jun 2022 17:19:33 GMT, release_branch:8.2, prefix:, end_time:Thu, 16 Jun 2022 21:15:53 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-01ccaf06, build_duration_seconds:14180]
=> [automation] update elastic stack version for testing 8.2.4-01ccaf06

docker-compose.yml
[start_time:Fri, 17 Jun 2022 00:14:23 GMT, release_branch:master, prefix:, end_time:Fri, 17 Jun 2022 04:19:18 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-da5a1c6d, build_duration_seconds:14695]
=> [automation] update elastic stack version for testing 8.4.0-da5a1c6d

changelogs/head.asciidoc, model/modeldecoder/v2/span_test.go, processor/otel/test_approved/span_jaeger_db.approved.json, processor/otel/test_approved/span_jaeger_http.approved.json, processor/otel/test_approved/span_jaeger_http_status_code.approved.json, processor/otel/test_approved/span_jaeger_https_default_port.approved.json, processor/otel/test_approved/span_jaeger_messaging.approved.json, processor/otel/traces.go, processor/otel/traces_test.go, processor/stream/test_approved_es_documents/testIntakeIntegrationOpenTelemetryBridge.approved.json
Infer `service.target.{type, name}` from OTLP events.
Observe that each span type the `service.target.{type, name}` in the output doc are populated as per the corresponding tables with the appropriate inputs.
1. DB spans:
| [in]peer.service | [in]db.system | [in]db.name | [out]target.type | [out]target.name |
|---------------|---------------|-------------|------------------|------------------|
| testsvc | postgresql    | testdb      | postgresql       | testdb           |
| testsvc | postgresql    | <nil>      | postgresql       | testsvc           |
| <nil> | <nil>         | testdb …
=> Support service.target.{type, name} for OTLP events

.ci/benchmarks.groovy, .ci/schedule-daily.groovy
Creates scheduled benchmark execution every night on the `main` branch
Fixes `SSH_KEY` variable
https://github.com/elastic/apm-server/issues/7846
=> chore: Nightly schedule for benchmarks

docker-compose.yml
[start_time:Sun, 19 Jun 2022 17:14:23 GMT, release_branch:8.2, prefix:, end_time:Sun, 19 Jun 2022 21:07:17 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-698e06ec, build_duration_seconds:13974]
=> [automation] update elastic stack version for testing 8.2.4-698e06ec

docker-compose.yml
[start_time:Sun, 19 Jun 2022 12:14:06 GMT, release_branch:8.3, prefix:, end_time:Sun, 19 Jun 2022 16:33:08 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-75d7500e, build_duration_seconds:15542]
=> [automation] update elastic stack version for testing 8.3.0-75d7500e

docker-compose.yml
[start_time:Tue, 21 Jun 2022 00:14:30 GMT, release_branch:8.3, prefix:, end_time:Tue, 21 Jun 2022 04:10:56 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-6d4bb852, build_duration_seconds:14186]
=> [automation] update elastic stack version for testing 8.3.0-6d4bb852

docker-compose.yml
[start_time:Mon, 20 Jun 2022 17:14:26 GMT, release_branch:8.2, prefix:, end_time:Mon, 20 Jun 2022 21:08:40 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-b657c8f5, build_duration_seconds:14054]
=> [automation] update elastic stack version for testing 8.2.4-b657c8f5

docker-compose.yml
[start_time:Tue, 21 Jun 2022 12:14:37 GMT, release_branch:8.3, prefix:, end_time:Tue, 21 Jun 2022 17:33:10 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-e0057e17, build_duration_seconds:19113]
=> [automation] update elastic stack version for testing 8.3.0-e0057e17

docker-compose.yml
[start_time:Tue, 21 Jun 2022 05:17:37 GMT, release_branch:8.2, prefix:, end_time:Tue, 21 Jun 2022 14:49:50 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-589bdf37, build_duration_seconds:34333]
=> [automation] update elastic stack version for testing 8.2.4-589bdf37

docker-compose.yml
[start_time:Tue, 21 Jun 2022 17:14:26 GMT, release_branch:8.2, prefix:, end_time:Tue, 21 Jun 2022 23:01:19 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-a34570b4, build_duration_seconds:20813]
=> [automation] update elastic stack version for testing 8.2.4-a34570b4

docker-compose.yml
[start_time:Wed, 22 Jun 2022 00:14:11 GMT, release_branch:master, prefix:, end_time:Wed, 22 Jun 2022 04:24:31 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-4fe26f2a, build_duration_seconds:15020]
=> [automation] update elastic stack version for testing 8.4.0-4fe26f2a

docker-compose.yml
[start_time:Wed, 22 Jun 2022 12:14:08 GMT, release_branch:8.3, prefix:, end_time:Wed, 22 Jun 2022 17:26:40 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-47d97929, build_duration_seconds:18752]
=> [automation] update elastic stack version for testing 8.3.0-47d97929

docker-compose.yml
[start_time:Wed, 22 Jun 2022 17:14:18 GMT, release_branch:8.2, prefix:, end_time:Wed, 22 Jun 2022 21:23:40 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-b5aa40e4, build_duration_seconds:14962]
=> [automation] update elastic stack version for testing 8.2.4-b5aa40e4

docker-compose.yml
[start_time:Fri, 24 Jun 2022 00:14:40 GMT, release_branch:8.3, prefix:, end_time:Fri, 24 Jun 2022 04:58:09 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-3b390c7b, build_duration_seconds:17009]
=> [automation] update elastic stack version for testing 8.3.0-3b390c7b

docker-compose.yml
[start_time:Thu, 23 Jun 2022 05:13:50 GMT, release_branch:7.17, prefix:, end_time:Thu, 23 Jun 2022 10:01:15 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-781a81f2, build_duration_seconds:17245]
=> [automation] update elastic stack version for testing 7.17.5-781a81f2

Jenkinsfile
This will help us to generate a report with [bench](https://pkg.go.dev/golang.org/x/perf/cmd/benchstat) so we can enable the APM Server micro-benchmarks on PRs  and report back the diff.
The archive already happens within the `sendBenchmark` but it uses the [BASE_DIR](https://github.com/elastic/apm-pipeline-library/blob/fcbe07578ae42d3a5c63b2dacecf5a982cc7268b/vars/sendBenchmarks.groovy#L37-L39) relative path.
To help with, let's archive the file in the root directory instead
=> ci: archive bench output from the base_dir folder

Makefile
Adds two new variables `BENCH_BENCHTIME` and `BENCH_COUNT` to the bench
make target. This allows us to run the micro-benchmarks with different
parameters.
N/A
=> make: Add BENCH_BENCHTIME and BENCH_COUNT to bench

magefile.go, systemtest/apmservertest/command.go
Fix `Build` mage target to build `x-pack/apm-server`. Also, use `make apm-server` to build the binary in system tests, to ensure there are no discrepancies between what we test and what we package.
Create an ESS deployment with Integrations Server, ensure APM Server becomes healthy.
Closes https://github.com/elastic/apm-server/issues/8426
Closes https://github.com/elastic/fleet-server/issues/1574
=> magefile: build x-pack/apm-server

docker-compose.yml
[start_time:Sat, 25 Jun 2022 00:18:11 GMT, release_branch:8.3, prefix:, end_time:Sat, 25 Jun 2022 04:28:19 GMT, manifest_version:2.1.0, version:8.3.0-SNAPSHOT, branch:8.3, build_id:8.3.0-fdf97a2e, build_duration_seconds:15008]
=> [automation] update elastic stack version for testing 8.3.0-fdf97a2e

docker-compose.yml
[start_time:Fri, 24 Jun 2022 17:14:23 GMT, release_branch:8.2, prefix:, end_time:Fri, 24 Jun 2022 21:16:07 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-b7bb3a0c, build_duration_seconds:14504]
=> [automation] update elastic stack version for testing 8.2.4-b7bb3a0c

docker-compose.yml
[start_time:Sat, 25 Jun 2022 05:13:50 GMT, release_branch:7.17, prefix:, end_time:Sat, 25 Jun 2022 09:41:38 GMT, manifest_version:2.1.0, version:7.17.5-SNAPSHOT, branch:7.17, build_id:7.17.5-3896ff07, build_duration_seconds:16068]
=> [automation] update elastic stack version for testing 7.17.5-3896ff07

.ci/scripts/bench.sh
As discussed in https://github.com/elastic/apm-pipeline-library/pull/1748
let's honour the BENCH_COUNT variable as it was added in https://github.com/elastic/apm-server/pull/8472/files
It ran as expected in the CI
=> ci: honour BENCH_COUNT with 5 for the benchmark

testing/benchmark/main.tf, testing/infra/terraform/modules/ec_deployment/.gitignore, testing/infra/terraform/modules/ec_deployment/deployment.tf, testing/infra/terraform/modules/ec_deployment/outputs.tf, testing/infra/terraform/modules/ec_deployment/scripts/secret_token.tftpl, testing/infra/terraform/modules/ec_deployment/terraform.tf
After #8376 got merged, the `ec_deployment` was broken if `integrations_
server=true` wasn't set on the module. Reading a local file that is
created during a terraform run for an output value didn't work. Instead,
use the "external" resource to run a program that returns a JSON output
and parse the secret_token from the APM Integration policy that way.
1. `cd testing/benchmark`
2. `make`
3. `terraform output -raw apm_secret_token` returns a valid secret token
The benchmarks couldn't be …
=> testing/ec_deployment: Fix apm_secret_token

.ci/jobs/apm-server-smoketests-mbp.yml, .ci/smoke-tests.groovy
Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
* Implementation of smoke tests within the CI.
Ref #8303
=> Add initial support of smoketests in CI

changelogs/8.3.asciidoc
Adds 8.3.1 release notes. No significant changes.
~NOTE: https://github.com/elastic/apm-server/pull/8407 is the only commit marked with `8.3.1`, but the backport (https://github.com/elastic/apm-server/pull/8442) still hasn't been merged (cc @marclop) so it didn't make it in—this was probably on purpose?~
EDIT: I see the thread on Slack now. This was left out of 8.3.1 on purpose.
=> docs: add 8.3.1 release notes

docker-compose.yml
[start_time:Fri, 1 Jul 2022 05:17:49 GMT, release_branch:7.17, prefix:, end_time:Fri, 1 Jul 2022 10:09:57 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-63d4a205, build_duration_seconds:17528]
=> [automation] update elastic stack version for testing 7.17.6-63d4a205

docker-compose.yml
[start_time:Wed, 29 Jun 2022 05:14:48 GMT, release_branch:8.2, prefix:, end_time:Wed, 29 Jun 2022 09:39:00 GMT, manifest_version:2.1.0, version:8.2.4-SNAPSHOT, branch:8.2, build_id:8.2.4-e7c42e26, build_duration_seconds:15852]
=> [automation] update elastic stack version for testing 8.2.4-e7c42e26

docker-compose.yml
[start_time:Tue, 5 Jul 2022 00:14:19 GMT, release_branch:8.3, prefix:, end_time:Tue, 5 Jul 2022 04:22:13 GMT, manifest_version:2.1.0, version:8.3.2-SNAPSHOT, branch:8.3, build_id:8.3.2-d34285fd, build_duration_seconds:14874]
=> [automation] update elastic stack version for testing 8.3.2-d34285fd

.ci/benchmarks.groovy
Some low % of benchmark executions suffer of cloud connectivity issues.
The entire benchmark stage will be retried in event of any error
ESS and executor(EC2) instances will be recreated. 
TL;DR Added retry option to the benchmark job. If it's failed once - it will be retried. 
run it in jenkins
=> Chore: retry benchmarks once when failed

Jenkinsfile
- Enable micro-benchmark on a PR basis
- Run on bare metals only
- Cleanup afterwards
Discussed in https://github.com/elastic/apm-server/pull/8471
=> ci: use baremetal for the microbenchmarking

docker-compose.yml
[start_time:Wed, 6 Jul 2022 00:15:45 GMT, release_branch:8.3, prefix:, end_time:Wed, 6 Jul 2022 04:35:35 GMT, manifest_version:2.1.0, version:8.3.2-SNAPSHOT, branch:8.3, build_id:8.3.2-56253b46, build_duration_seconds:15590]
=> [automation] update elastic stack version for testing 8.3.2-56253b46

docker-compose.yml
[start_time:Tue, 5 Jul 2022 05:14:10 GMT, release_branch:7.17, prefix:, end_time:Tue, 5 Jul 2022 10:03:06 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-1e4f9cbf, build_duration_seconds:17336]
=> [automation] update elastic stack version for testing 7.17.6-1e4f9cbf

docs/input-apm.asciidoc, docs/secure-agent-communication.asciidoc
There are two methods for setting/resetting the APM secret token:
A "reset token" button exists in the Elasticsearch Service UI on the APM & Fleet page:
This is documented [here](https://www.elastic.co/guide/en/apm/guide/8.3/secret-token-legacy.html#set-secret-token) and AFAICT doesn't need to be updated.
The APM secret token cannot be reset from the Elasticsearch Service UI—it must be reset in the integration settings. This PR updates the [APM integration docs](https://www.elastic.co/guide/en/apm/guide/8.3/secret-token.html#create-secret-token) to the following.
* Closes https://github.com/elastic/apm/issues/656.
=> docs: clarify secret token create/update

docker-compose.yml
[start_time:Wed, 6 Jul 2022 12:14:54 GMT, release_branch:8.3, prefix:, end_time:Wed, 6 Jul 2022 17:32:26 GMT, manifest_version:2.1.0, version:8.3.2-SNAPSHOT, branch:8.3, build_id:8.3.2-97fdd78b, build_duration_seconds:19052]
=> [automation] update elastic stack version for testing 8.3.2-97fdd78b

docker-compose.yml
[start_time:Wed, 6 Jul 2022 05:14:13 GMT, release_branch:7.17, prefix:, end_time:Wed, 6 Jul 2022 10:09:50 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-94c92680, build_duration_seconds:17737]
=> [automation] update elastic stack version for testing 7.17.6-94c92680

Jenkinsfile
Reverts elastic/apm-server#8561 so the CI can run normally.
=> Revert "ci: use the microbenchmarks-pool"

Jenkinsfile
Reverts elastic/apm-server#8564
For some reason https://apm-ci.elastic.co/label/x86_64/ was removed from the baremetals and that's required
=> Revert "Revert "ci: use the microbenchmarks-pool""

docker-compose.yml
[start_time:Sun, 10 Jul 2022 05:14:05 GMT, release_branch:7.17, prefix:, end_time:Sun, 10 Jul 2022 10:05:46 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-38278486, build_duration_seconds:17501]
=> [automation] update elastic stack version for testing 7.17.6-38278486

docker-compose.yml
[start_time:Tue, 12 Jul 2022 00:14:47 GMT, release_branch:8.3, prefix:, end_time:Tue, 12 Jul 2022 04:33:00 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-46b07667, build_duration_seconds:15493]
=> [automation] update elastic stack version for testing 8.3.3-46b07667

docker-compose.yml
[start_time:Mon, 11 Jul 2022 05:13:45 GMT, release_branch:7.17, prefix:, end_time:Mon, 11 Jul 2022 10:06:34 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-cff0caa9, build_duration_seconds:17569]
=> [automation] update elastic stack version for testing 7.17.6-cff0caa9

docker-compose.yml
[start_time:Tue, 12 Jul 2022 12:15:59 GMT, release_branch:8.3, prefix:, end_time:Tue, 12 Jul 2022 16:36:36 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-0264aa15, build_duration_seconds:15637]
=> [automation] update elastic stack version for testing 8.3.3-0264aa15

docker-compose.yml
[start_time:Tue, 12 Jul 2022 05:17:09 GMT, release_branch:7.17, prefix:, end_time:Tue, 12 Jul 2022 10:06:36 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-5c77e057, build_duration_seconds:17367]
=> [automation] update elastic stack version for testing 7.17.6-5c77e057

testing/infra/terraform/modules/ec_deployment/README.md, testing/infra/terraform/modules/ec_deployment/outputs.tf, testing/smoke/basic_upgrade/basic-upgrade.sh, testing/smoke/basic_upgrade/legacy-managed.sh, testing/smoke/basic_upgrade/main.tf, testing/smoke/basic_upgrade/standalone-major-managed.sh, testing/smoke/lib.sh
Adds the remaining assertions for the assets which are created by fleet
from the APM Integration (or APM package). It includes:
- Component templates and ILM Policies (these two are performed together
since they are very closely tied).
- Ingest pipelines.
It also fixes the smoke tests which were previously broken since the
elastic artifacts API only returns the last few previous versions and
doesn't provide a comprehensive directory for all the released versions.
We now use a regex expression to match the previous minor latest patch
version (if 8.3.2 is the latest, then `8.2.latest` will be used).
~- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpa …
=> smoketest: Add APM Integration assertions

systemtest/benchtest/main.go
Fixes the `-benchtime` flag which has no effect currently (benchmarks
are currently only running for 1s, regardless of what is set in the
benchtime flag).
Run apmbench with a -benchtime of 1m and verify it runs for at least 1m. (set -warmup-events to 0 so there's no warmup).
Fixes the regression introduced by #8440.
=> apmbench: Fix broken `-benchtime`

.ci/jobs/apm-server-schedule-everyday.yml, .ci/schedule-daily.groovy, .ci/schedule-everyday.groovy
Adds a new `schedule-everyday` job that is run every day (weekends too)
which is now responsible for scheduling the benchmarks. This is to allow
more data points for performance tracking purposes.
??
=> ci: Introduce schedule-everyday job for benchmarks

systemtest/benchtest/main.go, systemtest/benchtest/main_test.go, testing/benchmark/Makefile
Adds a new `BENCHMARK_MAX_RATE` variable which defaults to `0eps` or
disabled max rate, tunes the `BENCHMARK_WARMUP` to `40,000` events to be
sent as the warmup to the APM Server (`10,000` was enough, but `40,000`
ensures that the CPU credts have been exhausted for a 1g deployment).
Also, modifies the warmup functon to not return an error on warmup
should the error be `context.DeadlineExceeded`, and adds more weight to
the number of agents specified.
0. (export ess credentials)
1. `cd …
=> benchmark: Add `BENCHMARK_MAX_RATE` tune warmup

docker-compose.yml
[start_time:Thu, 14 Jul 2022 05:13:59 GMT, release_branch:7.17, prefix:, end_time:Thu, 14 Jul 2022 10:07:25 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-75df96d4, build_duration_seconds:17606]
=> [automation] update elastic stack version for testing 7.17.6-75df96d4

README.md, TESTING.md
Adds the apm-ci link in the `TESTING.md` and `README.md` build badge.
=> smoketest: Add apm-ci link in docs

docker-compose.yml
[start_time:Mon, 18 Jul 2022 00:14:58 GMT, release_branch:master, prefix:, end_time:Mon, 18 Jul 2022 05:00:16 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-a324b98b, build_duration_seconds:17118]
=> [automation] update elastic stack version for testing 8.4.0-a324b98b

docker-compose.yml
[start_time:Mon, 18 Jul 2022 00:14:17 GMT, release_branch:8.3, prefix:, end_time:Mon, 18 Jul 2022 04:33:35 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-99553f72, build_duration_seconds:15558]
=> [automation] update elastic stack version for testing 8.3.3-99553f72

docker-compose.yml
[start_time:Sun, 17 Jul 2022 05:14:56 GMT, release_branch:7.17, prefix:, end_time:Sun, 17 Jul 2022 10:01:40 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-0aa797e4, build_duration_seconds:17204]
=> [automation] update elastic stack version for testing 7.17.6-0aa797e4

.github/workflows/add-to-docs-project.yml
Per conversation with Silvia, this PR adds issues labeled, `Team:Docs` to the Observability Docs project board.
One thing we might want to discuss is whether you still want documentation issues to be added to the APM Server team board. If no changes are made to the other workflow, `Team:Docs` issues will be added to both.
=> Add “Team:Docs” issues to obs-docs project

docker-compose.yml
[start_time:Mon, 18 Jul 2022 12:14:36 GMT, release_branch:8.3, prefix:, end_time:Mon, 18 Jul 2022 16:38:07 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-302be7c1, build_duration_seconds:15811]
=> [automation] update elastic stack version for testing 8.3.3-302be7c1

docker-compose.yml
[start_time:Tue, 19 Jul 2022 00:18:08 GMT, release_branch:master, prefix:, end_time:Tue, 19 Jul 2022 04:40:25 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-31315ca3, build_duration_seconds:15737]
=> [automation] update elastic stack version for testing 8.4.0-31315ca3

model/apmevent_test.go, model/labels.go
If an agent sends global labels, then events without event-specific labels will share the same map of global labels. If those global labels need sanitisation, then the server may panic due to concurrently modifying/reading the map. To prevent this, clone the labels map if sanitisation is required.
~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)~ to be added at release time, to avoid updating live docs
Send a continuous stream of events with global labels that require sanitisation (e.g. a label key with a dot in it), and no …
=> model: clone labels before sanitizing

docker-compose.yml
[start_time:Wed, 20 Jul 2022 00:15:17 GMT, release_branch:8.3, prefix:, end_time:Wed, 20 Jul 2022 04:42:43 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-e5bc7e69, build_duration_seconds:16046]
=> [automation] update elastic stack version for testing 8.3.3-e5bc7e69

docker-compose.yml
[start_time:Tue, 19 Jul 2022 12:14:18 GMT, release_branch:master, prefix:, end_time:Tue, 19 Jul 2022 16:59:58 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:master, build_id:8.4.0-31269fd2, build_duration_seconds:17140]
=> [automation] update elastic stack version for testing 8.4.0-31269fd2

changelogs/8.3.asciidoc
This PR adds a missing jump link to the 8.3.3 release notes.
=> docs: add 8.3.3 jump link

.ci/smoke-tests.groovy, Makefile
Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
Correct the smoke tests Jenkins job to be able to run smoke tests in // in the CI.
* Run the associated Jenkins job.
#8638
=> Correct smoketests running in the CI

docker-compose.yml
[start_time:Thu, 21 Jul 2022 05:14:05 GMT, release_branch:7.17, prefix:, end_time:Thu, 21 Jul 2022 10:07:27 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-9675035b, build_duration_seconds:17602]
=> [automation] update elastic stack version for testing 7.17.6-9675035b

.ci/Jenkinsfile, .github/workflows/macos.yml
Use GitHub actions for MacOS.
GitHub actions are SaaS so we don't need to worry about the MacOS workers but just use them
A similar issue was done for beats in https://github.com/elastic/beats/pull/29032 and also disabled in the default CI controller in https://github.com/elastic/beats/pull/30591
To export the telemetry data with -> https://github.com/elastic/beats/pull/32267 but to be done in the near future
=> ci: enable github actions for macos

docker-compose.yml
[start_time:Sun, 24 Jul 2022 05:13:46 GMT, release_branch:7.17, prefix:, end_time:Sun, 24 Jul 2022 10:09:03 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-964edfea, build_duration_seconds:17717]
=> [automation] update elastic stack version for testing 7.17.6-964edfea

go.mk, magefile.go
Revert back to reading apm-server version from a file, to fix the Windows build.
N/A
None
=> Fix Windows build

docker-compose.yml
[start_time:Tue, 26 Jul 2022 00:14:32 GMT, release_branch:8.3, prefix:, end_time:Tue, 26 Jul 2022 04:44:23 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-d520d440, build_duration_seconds:16191]
=> [automation] update elastic stack version for testing 8.3.3-d520d440

docker-compose.yml
[start_time:Tue, 26 Jul 2022 05:13:59 GMT, release_branch:7.17, prefix:, end_time:Tue, 26 Jul 2022 10:06:22 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-3f4b9bc6, build_duration_seconds:17543]
=> [automation] update elastic stack version for testing 7.17.6-3f4b9bc6

Makefile
Bump `BEATS_VERSION` to `8.4` after branching out.
=> 8.4 branch creation version bump

Makefile
`make clean` is expected to remove a directory and files, the `-r` flag was missing from the command. 
run `make clean`
=> fix: minor fix in make clean command

CHANGELOG.asciidoc, changelogs/8.4.asciidoc, changelogs/head.asciidoc
Changelogs for 8.4.0, to be backported to 8.4 branch.
~The `changelogs/head.asciidoc` will be added by separate PR since it doesn't require backporting~ The elasticsearch-ci/docs step fails with missing head.asciidoc file
=> Add 8.4.0 changelog

.ci/packaging.groovy
Don't send notifications if packaging fails in a PR. Notifications are only relevant for branch builds; developers should check PR status directly.
N/A
N/A
=> .ci: don't notify of packaging failure on PRs

systemtest/cmd/apmsoak/main.go
Context cancel is a normal exit for `apmsoak`.
N/A
N/A
=> Handle ctx canceled as non fatal in apmsoak

NOTICE.txt, go.mod, go.sum
Update go-elasticsearch to the latest version of 8.3
N/A
N/A
=> Update go-elasticsearch version to 8.3

docker-compose.yml
[start_time:Thu, 28 Jul 2022 12:16:26 GMT, release_branch:8.4, prefix:, end_time:Thu, 28 Jul 2022 19:05:54 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-fb724a71, build_duration_seconds:24568]
=> [automation] update elastic stack version for testing 8.4.0-fb724a71

docker-compose.yml
[start_time:Thu, 28 Jul 2022 00:16:16 GMT, release_branch:8.3, prefix:, end_time:Thu, 28 Jul 2022 10:10:15 GMT, manifest_version:2.1.0, version:8.3.3-SNAPSHOT, branch:8.3, build_id:8.3.3-326db639, build_duration_seconds:35639]
=> [automation] update elastic stack version for testing 8.3.3-326db639

changelogs/head.asciidoc, internal/beater/server_test.go, internal/elasticsearch/client.go, internal/elasticsearch/client_test.go
Add the apm server version in the user agent and
a small test to verify the user agent is being used.
Closes https://github.com/elastic/apm-server/issues/8711
=> feat: set a default User-Agent field value when making HTTP requests

docker-compose.yml
[start_time:Sun, 31 Jul 2022 12:17:51 GMT, release_branch:8.4, prefix:, end_time:Sun, 31 Jul 2022 17:04:55 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-d88c8a44, build_duration_seconds:17224]
=> [automation] update elastic stack version for testing 8.4.0-d88c8a44

docker-compose.yml
[start_time:Fri, 29 Jul 2022 05:15:28 GMT, release_branch:7.17, prefix:, end_time:Fri, 29 Jul 2022 10:17:24 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-74b6df3e, build_duration_seconds:18116]
=> [automation] update elastic stack version for testing 7.17.6-74b6df3e

docker-compose.yml
[start_time:Mon, 1 Aug 2022 12:16:15 GMT, release_branch:master, prefix:, end_time:Mon, 1 Aug 2022 17:55:48 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-c54c3404, build_duration_seconds:20373]
=> [automation] update elastic stack version for testing 8.5.0-c54c3404

docker-compose.yml
[start_time:Mon, 1 Aug 2022 00:17:44 GMT, release_branch:8.4, prefix:, end_time:Mon, 1 Aug 2022 05:27:02 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-5954f776, build_duration_seconds:18558]
=> [automation] update elastic stack version for testing 8.4.0-5954f776

docker-compose.yml
[start_time:Tue, 2 Aug 2022 00:18:09 GMT, release_branch:8.3, prefix:, end_time:Tue, 2 Aug 2022 04:56:14 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-9c50d4cb, build_duration_seconds:16685]
=> [automation] update elastic stack version for testing 8.3.4-9c50d4cb

docker-compose.yml
[start_time:Tue, 2 Aug 2022 00:15:42 GMT, release_branch:master, prefix:, end_time:Tue, 2 Aug 2022 05:41:40 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-7dbc10f8, build_duration_seconds:19558]
=> [automation] update elastic stack version for testing 8.5.0-7dbc10f8

internal/beater/java_attacher/java_attacher.go
The `java --version` command was ran properly as the target user, however not the actual attacher command 🤦‍♂️ 
Probably dropped when this part was refactored.
=> Actually running attacher as another user

.ci/packaging.groovy
The version file was recently moved from `cmd/version.go` to `internal/version/version.go`. We need to update the Jenkins pipeline to trigger packaging on changes to this file.
N/A
N/A
=> .ci: fix apmpackage trigger condition

docker-compose.yml
[start_time:Tue, 2 Aug 2022 15:16:53 GMT, release_branch:7.17, prefix:, end_time:Tue, 2 Aug 2022 20:05:56 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-02b91d00, build_duration_seconds:17343]
=> [automation] update elastic stack version for testing 7.17.6-02b91d00

docs/legacy/guide/quick-start-overview.asciidoc
Fixes a broken link found in the "Bump version to 8.4" PR: https://github.com/elastic/docs/pull/2484
```
18:39:21 INFO:build_docs:Bad cross-document links:
18:39:21 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/8.4/quick-start-overview.html contains broken links to:
18:39:21 INFO:build_docs:   - en/elastic-stack-get-started/8.4/get-started-docker.html
18:39:21 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/guide/current/quick-start-overview.html contains broken links to:
18:39:21 INFO:build_docs:   - en/elastic-stack-get-started/8.4/get-started-docker.html
```
I'm not sure if I've got the labels right so I'd appreciate any help. 🙏
=> Fix broken link to Docker getting started

docs/legacy/guide/quick-start-overview.asciidoc
This is a redo of #8791 because I botched it up the first time around (sorry!). :-)
Rel: https://github.com/elastic/apm-server/pull/8502
=> Fix link to Docker getting started

docker-compose.yml
[start_time:Wed, 3 Aug 2022 05:15:11 GMT, release_branch:7.17, prefix:, end_time:Wed, 3 Aug 2022 10:41:27 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-308858b9, build_duration_seconds:19576]
=> [automation] update elastic stack version for testing 7.17.6-308858b9

docker-compose.yml
[start_time:Wed, 3 Aug 2022 17:30:29 GMT, release_branch:8.4, prefix:, end_time:Wed, 3 Aug 2022 22:37:06 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-b5074ef3, build_duration_seconds:18397]
=> [automation] update elastic stack version for testing 8.4.0-b5074ef3

docker-compose.yml
[start_time:Thu, 4 Aug 2022 12:15:38 GMT, release_branch:8.4, prefix:, end_time:Thu, 4 Aug 2022 17:41:18 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-43c061d1, build_duration_seconds:19540]
=> [automation] update elastic stack version for testing 8.4.0-43c061d1

docker-compose.yml
[start_time:Thu, 4 Aug 2022 12:16:07 GMT, release_branch:8.3, prefix:, end_time:Thu, 4 Aug 2022 16:32:47 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-73c9af3c, build_duration_seconds:15400]
=> [automation] update elastic stack version for testing 8.3.4-73c9af3c

docker-compose.yml
[start_time:Thu, 4 Aug 2022 05:15:39 GMT, release_branch:7.17, prefix:, end_time:Thu, 4 Aug 2022 10:00:06 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-39f8da8e, build_duration_seconds:17067]
=> [automation] update elastic stack version for testing 7.17.6-39f8da8e

packaging.mk
`date` on MacOS doesn't support `--iso-8601` flag. Behaviour of changes in this PR:
```
$ gdate -u --iso-8601=seconds                                             
2022-08-04T12:00:47+00:00
$ date -u +"%Y-%m-%dT%H:%M:%S%z"                                          
2022-08-04T12:01:24+0000
```
N/A
N/A
=> Fix usage of date cmd for unix systems in packaging

docker-compose.yml
[start_time:Sun, 7 Aug 2022 00:17:42 GMT, release_branch:8.4, prefix:, end_time:Sun, 7 Aug 2022 05:40:11 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-4b3e8f6e, build_duration_seconds:19349]
=> [automation] update elastic stack version for testing 8.4.0-4b3e8f6e

docker-compose.yml
[start_time:Mon, 8 Aug 2022 00:15:48 GMT, release_branch:8.3, prefix:, end_time:Mon, 8 Aug 2022 04:55:10 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-9c6c318b, build_duration_seconds:16762]
=> [automation] update elastic stack version for testing 8.3.4-9c6c318b

docker-compose.yml
[start_time:Sat, 6 Aug 2022 05:15:07 GMT, release_branch:7.17, prefix:, end_time:Sat, 6 Aug 2022 10:06:25 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-49d2f2df, build_duration_seconds:17478]
=> [automation] update elastic stack version for testing 7.17.6-49d2f2df

systemtest/cmd/apmsoak/main.go
Context cancel is a normal exit for apmsoak.
=> Handle wrapped ctx canceled errors for apmsoak

Makefile, internal/glog/go.mod
Use Go 1.17-compatible module pruning (https://go.dev/ref/mod#graph-pruning). Without this, `make update-beats` fails.
N/A
None
=> Makefile: use -compat=1.17 in go mod tidy

packaging.mk
Fix docker-image.tar.gz targets to gzip the tarballs, not just name them gzipped tarballs.
1. `make package-docker`
2. `cat build/distributions/apm-server-ubi8-8.5.0-docker-image.tar.gz | gunzip | docker load`
Closes https://github.com/elastic/apm-server/issues/8823
=> packaging: actually gzip docker tarballs

docker-compose.yml
[start_time:Mon, 8 Aug 2022 12:15:06 GMT, release_branch:8.4, prefix:, end_time:Mon, 8 Aug 2022 17:58:03 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-96568c7b, build_duration_seconds:20577]
=> [automation] update elastic stack version for testing 8.4.0-96568c7b

docker-compose.yml
[start_time:Tue, 9 Aug 2022 00:16:04 GMT, release_branch:8.3, prefix:, end_time:Tue, 9 Aug 2022 04:43:07 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-fd43be48, build_duration_seconds:16023]
=> [automation] update elastic stack version for testing 8.3.4-fd43be48

docker-compose.yml
[start_time:Mon, 8 Aug 2022 05:14:50 GMT, release_branch:7.17, prefix:, end_time:Mon, 8 Aug 2022 10:09:06 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-a65acb36, build_duration_seconds:17656]
=> [automation] update elastic stack version for testing 7.17.6-a65acb36

docker-compose.yml
[start_time:Tue, 9 Aug 2022 12:17:46 GMT, release_branch:8.4, prefix:, end_time:Tue, 9 Aug 2022 17:58:06 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-9adc8090, build_duration_seconds:20420]
=> [automation] update elastic stack version for testing 8.4.0-9adc8090

docker-compose.yml
[start_time:Tue, 9 Aug 2022 12:15:59 GMT, release_branch:master, prefix:, end_time:Tue, 9 Aug 2022 18:53:08 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-41aadc32, build_duration_seconds:23829]
=> [automation] update elastic stack version for testing 8.5.0-41aadc32

docker-compose.yml
[start_time:Tue, 9 Aug 2022 12:15:41 GMT, release_branch:8.3, prefix:, end_time:Tue, 9 Aug 2022 17:00:53 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-b4aa6143, build_duration_seconds:17112]
=> [automation] update elastic stack version for testing 8.3.4-b4aa6143

docker-compose.yml
[start_time:Tue, 9 Aug 2022 05:14:44 GMT, release_branch:7.17, prefix:, end_time:Tue, 9 Aug 2022 09:46:29 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-e11a9305, build_duration_seconds:16305]
=> [automation] update elastic stack version for testing 7.17.6-e11a9305

docker-compose.yml
[start_time:Wed, 10 Aug 2022 12:17:48 GMT, release_branch:master, prefix:, end_time:Wed, 10 Aug 2022 18:36:28 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-60a4c029, build_duration_seconds:22720]
=> [automation] update elastic stack version for testing 8.5.0-60a4c029

docker-compose.yml
[start_time:Thu, 11 Aug 2022 00:18:58 GMT, release_branch:8.3, prefix:, end_time:Thu, 11 Aug 2022 04:58:12 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-a5e24e15, build_duration_seconds:16754]
=> [automation] update elastic stack version for testing 8.3.4-a5e24e15

docker-compose.yml
[start_time:Thu, 11 Aug 2022 12:17:23 GMT, release_branch:8.3, prefix:, end_time:Thu, 11 Aug 2022 16:55:27 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-adc3e57f, build_duration_seconds:16684]
=> [automation] update elastic stack version for testing 8.3.4-adc3e57f

docker-compose.yml
[start_time:Sun, 14 Aug 2022 12:15:35 GMT, release_branch:8.4, prefix:, end_time:Sun, 14 Aug 2022 17:35:57 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-fea9abbe, build_duration_seconds:19222]
=> [automation] update elastic stack version for testing 8.4.0-fea9abbe

docker-compose.yml
[start_time:Sun, 14 Aug 2022 12:23:06 GMT, release_branch:8.3, prefix:, end_time:Sun, 14 Aug 2022 18:07:08 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-6d6eaf28, build_duration_seconds:20642]
=> [automation] update elastic stack version for testing 8.3.4-6d6eaf28

docker-compose.yml
[start_time:Fri, 12 Aug 2022 05:14:52 GMT, release_branch:7.17, prefix:, end_time:Fri, 12 Aug 2022 10:07:22 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-efe703c7, build_duration_seconds:17550]
=> [automation] update elastic stack version for testing 7.17.6-efe703c7

docker-compose.yml
[start_time:Mon, 15 Aug 2022 12:18:10 GMT, release_branch:8.4, prefix:, end_time:Mon, 15 Aug 2022 18:08:58 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-9bd354a1, build_duration_seconds:21048]
=> [automation] update elastic stack version for testing 8.4.0-9bd354a1

docker-compose.yml
[start_time:Mon, 15 Aug 2022 00:15:30 GMT, release_branch:8.3, prefix:, end_time:Mon, 15 Aug 2022 05:10:35 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-58ddca7b, build_duration_seconds:17705]
=> [automation] update elastic stack version for testing 8.3.4-58ddca7b

docker-compose.yml
[start_time:Mon, 15 Aug 2022 05:15:02 GMT, release_branch:7.17, prefix:, end_time:Mon, 15 Aug 2022 10:08:14 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-03b746cb, build_duration_seconds:17592]
=> [automation] update elastic stack version for testing 7.17.6-03b746cb

docker-compose.yml
[start_time:Tue, 16 Aug 2022 05:16:47 GMT, release_branch:7.17, prefix:, end_time:Tue, 16 Aug 2022 11:09:30 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-202119fd, build_duration_seconds:21163]
=> [automation] update elastic stack version for testing 7.17.6-202119fd

docker-compose.yml
[start_time:Wed, 17 Aug 2022 12:18:02 GMT, release_branch:master, prefix:, end_time:Wed, 17 Aug 2022 20:19:44 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-6b9f92c0, build_duration_seconds:28902]
=> [automation] update elastic stack version for testing 8.5.0-6b9f92c0

docker-compose.yml
[start_time:Wed, 17 Aug 2022 00:15:47 GMT, release_branch:8.4, prefix:, end_time:Wed, 17 Aug 2022 05:18:36 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-b95305c2, build_duration_seconds:18169]
=> [automation] update elastic stack version for testing 8.4.0-b95305c2

docker-compose.yml
[start_time:Wed, 17 Aug 2022 05:15:42 GMT, release_branch:7.17, prefix:, end_time:Wed, 17 Aug 2022 10:13:30 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-091e6fb1, build_duration_seconds:17868]
=> [automation] update elastic stack version for testing 7.17.6-091e6fb1

docs/apm-mutating-webhook.asciidoc, docs/features.asciidoc, docs/integrations-index.asciidoc
Adds APM mutating webhook documentation to the APM Guide. If you have content suggestions, please add them to https://github.com/elastic/apm-mutating-webhook/issues/37.
**[Preview this PR here](https://apm-server_8889.docs-preview.app.elstc.co/guide/en/apm/guide/master/apm-mutating-admission-webhook.html)**
* For https://github.com/elastic/apm-mutating-webhook/issues/37.
=> docs: add tech preview mutating webhook docs

docker-compose.yml
[start_time:Sun, 21 Aug 2022 12:22:02 GMT, release_branch:8.4, prefix:, end_time:Sun, 21 Aug 2022 17:48:21 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-910fe5e1, build_duration_seconds:19579]
=> [automation] update elastic stack version for testing 8.4.0-910fe5e1

docker-compose.yml
[start_time:Sun, 21 Aug 2022 00:18:06 GMT, release_branch:8.3, prefix:, end_time:Sun, 21 Aug 2022 05:20:42 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-70c0b53c, build_duration_seconds:18156]
=> [automation] update elastic stack version for testing 8.3.4-70c0b53c

docker-compose.yml
[start_time:Sun, 21 Aug 2022 05:18:55 GMT, release_branch:7.17, prefix:, end_time:Sun, 21 Aug 2022 10:08:51 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-b8ca5a33, build_duration_seconds:17396]
=> [automation] update elastic stack version for testing 7.17.6-b8ca5a33

docker-compose.yml
[start_time:Sat, 20 Aug 2022 00:15:57 GMT, release_branch:master, prefix:, end_time:Sat, 20 Aug 2022 05:58:58 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-0616acda, build_duration_seconds:20581]
=> [automation] update elastic stack version for testing 8.5.0-0616acda

systemtest/containers.go
I stumbled across this issue where APM-Server logs were not shown on an error of some systemtest even when the code expects them to be printed. After debugging, the root cause was that the docker container is using `UTC` timezone whereas the code which fetches the logs uses the machine's current local time.
I was also thinking maybe we can make APM-Server logs to be visible in `docker-logs` (maybe by configuring APM-Server run by elastic-agent to log to `stderr`?). Let me know what other @elastic/apm-server folks think about this. I can create an issue in the backlog if required.
=> systemtest: Fix apm-server log getter from test container

docker-compose.yml
[start_time:Mon, 22 Aug 2022 12:16:45 GMT, release_branch:master, prefix:, end_time:Mon, 22 Aug 2022 17:41:17 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-dd6f2bb0, build_duration_seconds:19472]
=> [automation] update elastic stack version for testing 8.5.0-dd6f2bb0

docker-compose.yml
[start_time:Mon, 22 Aug 2022 12:16:01 GMT, release_branch:8.4, prefix:, end_time:Mon, 22 Aug 2022 17:06:07 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-7f4eb04b, build_duration_seconds:17406]
=> [automation] update elastic stack version for testing 8.4.0-7f4eb04b

docker-compose.yml
[start_time:Mon, 22 Aug 2022 05:14:59 GMT, release_branch:7.17, prefix:, end_time:Mon, 22 Aug 2022 10:05:44 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-a9c53531, build_duration_seconds:17445]
=> [automation] update elastic stack version for testing 7.17.6-a9c53531

docker-compose.yml
[start_time:Tue, 23 Aug 2022 00:15:33 GMT, release_branch:8.3, prefix:, end_time:Tue, 23 Aug 2022 04:46:48 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-45336fec, build_duration_seconds:16275]
=> [automation] update elastic stack version for testing 8.3.4-45336fec

changelogs/7.17.asciidoc
Removes a space so the PR link renders.
=> docs: fix rendering of 7.17.6 rns link

docker-compose.yml
[start_time:Tue, 23 Aug 2022 12:17:54 GMT, release_branch:master, prefix:, end_time:Tue, 23 Aug 2022 18:36:47 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-feb644de, build_duration_seconds:22733]
=> [automation] update elastic stack version for testing 8.5.0-feb644de

docker-compose.yml
[start_time:Tue, 23 Aug 2022 12:16:12 GMT, release_branch:8.4, prefix:, end_time:Tue, 23 Aug 2022 18:23:50 GMT, manifest_version:2.1.0, version:8.4.0-SNAPSHOT, branch:8.4, build_id:8.4.0-fa661330, build_duration_seconds:22058]
=> [automation] update elastic stack version for testing 8.4.0-fa661330

docker-compose.yml
[start_time:Tue, 23 Aug 2022 05:16:12 GMT, release_branch:7.17, prefix:, end_time:Tue, 23 Aug 2022 10:04:03 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-4816e9ef, build_duration_seconds:17271]
=> [automation] update elastic stack version for testing 7.17.6-4816e9ef

docker-compose.yml
[start_time:Tue, 23 Aug 2022 12:15:44 GMT, release_branch:8.3, prefix:, end_time:Tue, 23 Aug 2022 16:47:14 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-97a7bb79, build_duration_seconds:16290]
=> [automation] update elastic stack version for testing 8.3.4-97a7bb79

docs/release-notes.asciidoc
https://github.com/elastic/apm-aws-lambda/pull/280 changed the file hierarchy, therefore the link to `CHANGELOGS` needs to be adapted.
=> fix: link to apm-aws-lambda changelog changed

docker-compose.yml
[start_time:Wed, 24 Aug 2022 12:16:09 GMT, release_branch:master, prefix:, end_time:Wed, 24 Aug 2022 17:36:28 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-7783a03c, build_duration_seconds:19219]
=> [automation] update elastic stack version for testing 8.5.0-7783a03c

docker-compose.yml
[start_time:Wed, 24 Aug 2022 12:21:51 GMT, release_branch:8.3, prefix:, end_time:Wed, 24 Aug 2022 16:38:44 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-5621f166, build_duration_seconds:15413]
=> [automation] update elastic stack version for testing 8.3.4-5621f166

docker-compose.yml
[start_time:Wed, 24 Aug 2022 05:15:58 GMT, release_branch:7.17, prefix:, end_time:Wed, 24 Aug 2022 10:16:56 GMT, manifest_version:2.1.0, version:7.17.6-SNAPSHOT, branch:7.17, build_id:7.17.6-c5d77a20, build_duration_seconds:18058]
=> [automation] update elastic stack version for testing 7.17.6-c5d77a20

docker-compose.yml
[start_time:Thu, 25 Aug 2022 12:18:21 GMT, release_branch:8.4, prefix:, end_time:Thu, 25 Aug 2022 16:38:40 GMT, manifest_version:2.1.0, version:8.4.1-SNAPSHOT, branch:8.4, build_id:8.4.1-74c5d538, build_duration_seconds:15619]
=> [automation] update elastic stack version for testing 8.4.1-74c5d538

docker-compose.yml
[start_time:Fri, 26 Aug 2022 00:16:02 GMT, release_branch:8.3, prefix:, end_time:Fri, 26 Aug 2022 04:54:20 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-22a90cba, build_duration_seconds:16698]
=> [automation] update elastic stack version for testing 8.3.4-22a90cba

docker-compose.yml
[start_time:Thu, 25 Aug 2022 12:15:45 GMT, release_branch:master, prefix:, end_time:Thu, 25 Aug 2022 18:17:20 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-17b8a62d, build_duration_seconds:21695]
=> [automation] update elastic stack version for testing 8.5.0-17b8a62d

.ci/scripts/Makefile
Set `PACKAGE_STORAGE_BRANCH` value only once.
Solves the issue with the automation for the package-store.
```
Creating pull request for update-apm-20220825154830 into snapshot in elastic/package-storage
pull request create failed: GraphQL: Head sha can't be blank, Base sha can't be blank, No commits between snapshot and update-apm-20220825154830, Head ref must be a branch (createPullRequest)
```
https://github.com/elastic/package-storage/pull/5414 was automatically created.
=> fix update-apm package-storage

docker-compose.yml
[start_time:Sun, 28 Aug 2022 12:15:39 GMT, release_branch:master, prefix:, end_time:Sun, 28 Aug 2022 17:38:38 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-9aed3b11, build_duration_seconds:19379]
=> [automation] update elastic stack version for testing 8.5.0-9aed3b11

docker-compose.yml
[start_time:Mon, 29 Aug 2022 00:15:35 GMT, release_branch:8.4, prefix:, end_time:Mon, 29 Aug 2022 04:51:50 GMT, manifest_version:2.1.0, version:8.4.1-SNAPSHOT, branch:8.4, build_id:8.4.1-14f69e2b, build_duration_seconds:16575]
=> [automation] update elastic stack version for testing 8.4.1-14f69e2b

docker-compose.yml
[start_time:Fri, 26 Aug 2022 12:16:27 GMT, release_branch:8.3, prefix:, end_time:Fri, 26 Aug 2022 16:48:58 GMT, manifest_version:2.1.0, version:8.3.4-SNAPSHOT, branch:8.3, build_id:8.3.4-6089c81a, build_duration_seconds:16351]
=> [automation] update elastic stack version for testing 8.3.4-6089c81a

docker-compose.yml
[start_time:Sun, 28 Aug 2022 05:15:53 GMT, release_branch:7.17, prefix:, end_time:Sun, 28 Aug 2022 10:03:03 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-a3635a2e, build_duration_seconds:17230]
=> [automation] update elastic stack version for testing 7.17.7-a3635a2e

docker-compose.yml
[start_time:Mon, 29 Aug 2022 12:16:25 GMT, release_branch:master, prefix:, end_time:Mon, 29 Aug 2022 17:59:37 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-440e0896, build_duration_seconds:20592]
=> [automation] update elastic stack version for testing 8.5.0-440e0896

docker-compose.yml
[start_time:Mon, 29 Aug 2022 12:15:48 GMT, release_branch:8.4, prefix:, end_time:Mon, 29 Aug 2022 16:57:06 GMT, manifest_version:2.1.0, version:8.4.1-SNAPSHOT, branch:8.4, build_id:8.4.1-b72ec52c, build_duration_seconds:16878]
=> [automation] update elastic stack version for testing 8.4.1-b72ec52c

docker-compose.yml
[start_time:Mon, 29 Aug 2022 05:15:01 GMT, release_branch:7.17, prefix:, end_time:Mon, 29 Aug 2022 09:43:17 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-18723602, build_duration_seconds:16096]
=> [automation] update elastic stack version for testing 7.17.7-18723602

systemtest/cmd/fleetctl/README.md, systemtest/cmd/fleetctl/main.go
1. Create a cloud deployment, note down the Kibana URL and `elastic` user's password
2. Run `fleetctl -u https://elastic:<password>@<kibana-host> set-policy-config elastic-cloud-apm apm-server.expvar.enabled=true`
3. Check that the server starts responding to `GET /debug/vars` requests after a little while
None
=> fleetctl: add command for setting arbitrary config

.ci/packaging.groovy
This PR fixes a bug in the `packaging.groovy`.
Unpublished package revisions should be signed before publishing.
=> Fix: trigger signing if there is an unsigned revision

docs/legacy/tab-widgets/install-agents-widget.asciidoc, docs/open-telemetry.asciidoc
This PR adds an OpenTelemetry tab to [Step 4: Install APM agents](http://localhost:8000/guide/deploy-agent-to-send-data.html#add-apm-integration-agents) of our getting started guide:
The content of the new OpenTelemetry tab is single-sourced directly from our [OpenTelemetry instrumentation docs](https://www.elastic.co/guide/en/apm/guide/current/open-telemetry.html#instrument-apps-otel). I reworked the docs a bit to be useful in both locations and better match the in-product tutorial added in https://github.com/elastic/kibana/issues/133383.
* Closes https://github.com/elastic/observability-docs/issues/2061.
=> docs: add oTel to getting started

docker-compose.yml
[start_time:Tue, 30 Aug 2022 00:16:33 GMT, release_branch:8.4, prefix:, end_time:Tue, 30 Aug 2022 05:46:34 GMT, manifest_version:2.1.0, version:8.4.1-SNAPSHOT, branch:8.4, build_id:8.4.1-65181fd0, build_duration_seconds:19801]
=> [automation] update elastic stack version for testing 8.4.1-65181fd0

docker-compose.yml
[start_time:Tue, 30 Aug 2022 12:16:13 GMT, release_branch:master, prefix:, end_time:Tue, 30 Aug 2022 17:32:20 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-fedc3e60, build_duration_seconds:18967]
=> [automation] update elastic stack version for testing 8.5.0-fedc3e60

systemtest/approvals.go
Fix TestServiceMetricsAggregation by adding service.name and transaction.type fields to the approvals document sorting. Without this, service metrics may be inconsistently ordered, which leads to the test failing randomly.
Run the `TestServiceMetricsAggregation` test a bunch of times.
None
=> systemtest: add dimensions to approval sorting

testing/benchmark/main.tf, testing/benchmark/terraform.tfvars.example, testing/benchmark/variables.tf, testing/infra/terraform/modules/ec_deployment/README.md, testing/infra/terraform/modules/ec_deployment/deployment.tf, testing/infra/terraform/modules/ec_deployment/variables.tf
Adds a new variable (`elasticsearch_dedicated_masters`) to control the
use of Elasticsearch dedicated masters in an Elasticsearch cluster. In
general, once a certain number of total Elasticsearch instances has been
reached, the cloud API will respond with an error which asks the user to
set dedicated masters. The new boolean variable allows doing just that.
In general, this issue will only be experienced when the deployments are
large.
~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)`~
Create a large deployment spanning 3 zones and >= `116g` size for Elasticsearch.
Part of …
=> ec_deployment: Add var to control ES masters

docker-compose.yml
[start_time:Wed, 31 Aug 2022 21:50:45 GMT, release_branch:8.4, prefix:, end_time:Thu, 1 Sep 2022 04:12:18 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-30e0a703, build_duration_seconds:22893]
=> [automation] update elastic stack version for testing 8.4.2-30e0a703

docker-compose.yml
[start_time:Wed, 31 Aug 2022 21:49:47 GMT, release_branch:7.17, prefix:, end_time:Thu, 1 Sep 2022 03:04:09 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-cf1ac8b8, build_duration_seconds:18862]
=> [automation] update elastic stack version for testing 7.17.7-cf1ac8b8

docker-compose.yml
[start_time:Wed, 31 Aug 2022 14:16:09 GMT, release_branch:master, prefix:, end_time:Wed, 31 Aug 2022 19:59:26 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-b5001a6d, build_duration_seconds:20597]
=> [automation] update elastic stack version for testing 8.5.0-b5001a6d

docker-compose.yml
[start_time:Thu, 1 Sep 2022 12:15:39 GMT, release_branch:8.4, prefix:, end_time:Thu, 1 Sep 2022 17:55:24 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-48cedf17, build_duration_seconds:20385]
=> [automation] update elastic stack version for testing 8.4.2-48cedf17

docker-compose.yml
[start_time:Thu, 1 Sep 2022 12:16:07 GMT, release_branch:master, prefix:, end_time:Thu, 1 Sep 2022 18:48:19 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-de69302b, build_duration_seconds:23532]
=> [automation] update elastic stack version for testing 8.5.0-de69302b

docker-compose.yml
[start_time:Thu, 1 Sep 2022 05:16:19 GMT, release_branch:7.17, prefix:, end_time:Thu, 1 Sep 2022 10:21:19 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-b0c2ed0e, build_duration_seconds:18300]
=> [automation] update elastic stack version for testing 7.17.7-b0c2ed0e

docker-compose.yml
[start_time:Sun, 4 Sep 2022 12:16:03 GMT, release_branch:8.4, prefix:, end_time:Sun, 4 Sep 2022 17:44:19 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-c37a1f37, build_duration_seconds:19696]
=> [automation] update elastic stack version for testing 8.4.2-c37a1f37

docker-compose.yml
[start_time:Sun, 4 Sep 2022 05:14:57 GMT, release_branch:7.17, prefix:, end_time:Sun, 4 Sep 2022 10:02:53 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-d187f943, build_duration_seconds:17276]
=> [automation] update elastic stack version for testing 7.17.7-d187f943

docker-compose.yml
[start_time:Sun, 4 Sep 2022 12:15:33 GMT, release_branch:master, prefix:, end_time:Sun, 4 Sep 2022 18:22:39 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-1bd77fc1, build_duration_seconds:22026]
=> [automation] update elastic stack version for testing 8.5.0-1bd77fc1

docker-compose.yml
[start_time:Mon, 5 Sep 2022 12:15:52 GMT, release_branch:master, prefix:, end_time:Mon, 5 Sep 2022 20:01:59 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-167dfc80, build_duration_seconds:27967]
=> [automation] update elastic stack version for testing 8.5.0-167dfc80

docker-compose.yml
[start_time:Mon, 5 Sep 2022 05:19:36 GMT, release_branch:7.17, prefix:, end_time:Mon, 5 Sep 2022 09:50:02 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-9bf11b3d, build_duration_seconds:16226]
=> [automation] update elastic stack version for testing 7.17.7-9bf11b3d

docker-compose.yml
[start_time:Tue, 6 Sep 2022 12:18:14 GMT, release_branch:master, prefix:, end_time:Tue, 6 Sep 2022 18:55:27 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-6b7dda2d, build_duration_seconds:23833]
=> [automation] update elastic stack version for testing 8.5.0-6b7dda2d

docker-compose.yml
[start_time:Tue, 6 Sep 2022 12:16:15 GMT, release_branch:8.4, prefix:, end_time:Tue, 6 Sep 2022 17:44:35 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-b244ddfa, build_duration_seconds:19700]
=> [automation] update elastic stack version for testing 8.4.2-b244ddfa

docker-compose.yml
[start_time:Wed, 7 Sep 2022 05:15:32 GMT, release_branch:7.17, prefix:, end_time:Wed, 7 Sep 2022 10:04:39 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-2f72b236, build_duration_seconds:17347]
=> [automation] update elastic stack version for testing 7.17.7-2f72b236

docker-compose.yml
[start_time:Thu, 8 Sep 2022 12:15:56 GMT, release_branch:8.4, prefix:, end_time:Thu, 8 Sep 2022 17:53:42 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-7c2154f4, build_duration_seconds:20266]
=> [automation] update elastic stack version for testing 8.4.2-7c2154f4

docker-compose.yml
[start_time:Thu, 8 Sep 2022 05:15:21 GMT, release_branch:7.17, prefix:, end_time:Thu, 8 Sep 2022 10:04:30 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-e363ab2a, build_duration_seconds:17349]
=> [automation] update elastic stack version for testing 7.17.7-e363ab2a

Makefile
Trying to fix packaging, which still uses beats/dev-tools in 7.17.
N/A
None
=> Make: download Go modules before "mage package"

x-pack/apm-server/sampling/processor.go
`RunValueLogGC` returns `ErrNoRewrite` when there are no changes to be made for GC, and should be called in a loop until it returns an error. Doing this should lead to value logs being garbage collected more quickly, as otherwise we'll wait for another tick before repeating.
See https://github.com/dgraph-io/dgraph/blob/832ebb9766f1732186eaecbf3792aff9e3766c6c/x/x.go#L1089-L1127 for how dgraph itself uses the method.
:tipping_hand_man: :tophat: @marclop 
N/A
None
=> sampling: call RunValueLogGC in a loop

testing/benchmark/variables.tf
Updates the default region and deployment template so that we make use of the Belgium CFT region which does have the CPU optimized hardware profile. This should give us a better benchmarking environment where the APM Server isn't being throttled all the time.
N/A
Use the right hardware profile for benchmarks.
=> benchmark: Use GCP Belgium (CPU optimized profile)

testing/benchmark/variables.tf
Reverts elastic/apm-server#9105. It turns out that GCP Belgium is not truly a CFT region and as such the `docker_image` cannot be overridden.
```
│ Error: failed creating deployment: 2 errors occurred:
│ 	* api error: clusters.cluster_plan_change_prohibited: The requested cluster configuration change is not permitted. Value of field 'elasticsearch.docker_image' cannot be changed to [docker.elastic.co/cloud-release/elasticsearch-cloud-ess:8.5.0-6b7dda2d-SNAPSHOT]. (resources.elasticsearch[0].elasticsearch.docker_image)
```
=> Revert "benchmark: Use GCP Belgium (CPU optimized profile)"

docker-compose.yml
[start_time:Wed, 14 Sep 2022 00:16:00 GMT, release_branch:8.4, prefix:, end_time:Wed, 14 Sep 2022 04:59:09 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-4457f478, build_duration_seconds:16989]
=> [automation] update elastic stack version for testing 8.4.2-4457f478

systemtest/approvals.go
Fix `TestIngestPipelineDataStreamMigration` flakiness.
`cd systemtest && go test -v -run TestIngestPipelineDataStreamMigration -count=100 .`
Flaky systemtest.
=> systemtest: Add `span.type` as sortable field

.ci/packer_cache.sh
This script is used by the CI automation to cache some of the artifacts, to help with faster builds.
Unfortunately, the `WORKSPACE` env variable is not set properly by the automation. This should fix the problem we have found for the last month or so
```bash
.ci/packer_cache.sh
WARN: WORKSPACE env variable is empty, hence creating a temporary dir
INFO: WORKSPACE=/var/folders/hn/j6gds1qx1f5bysfn0qp0t03c0000gn/T/tmp.miMkCfme
...
```
```bash
WORKSPACE=/tmp .ci/packer_cache.sh
latest: Pulling from infra/release-manager
405f018f9d1d: Waiting 
...
```
=> packer: if no WORKSPACE then set a new path

docker-compose.yml
[start_time:Sun, 18 Sep 2022 00:15:56 GMT, release_branch:8.4, prefix:, end_time:Sun, 18 Sep 2022 04:51:52 GMT, manifest_version:2.1.0, version:8.4.2-SNAPSHOT, branch:8.4, build_id:8.4.2-b98b12f1, build_duration_seconds:16556]
=> [automation] update elastic stack version for testing 8.4.2-b98b12f1

docker-compose.yml
[start_time:Sun, 18 Sep 2022 05:15:14 GMT, release_branch:7.17, prefix:, end_time:Sun, 18 Sep 2022 10:24:38 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-377031d2, build_duration_seconds:18564]
=> [automation] update elastic stack version for testing 7.17.7-377031d2

Makefile
Signed-off-by: Florian Lehner <florian.lehner@elastic.co>
Make sure Go does not pull in or update dependencies when compiling or running tests. Unintended changes to go.[mod|sum] can be a security risk and therefore should be avoided.
This PR makes sure compilation or tests will fail if changes to go.[mod|sum] are needed.
No user-facing change.
No changes to `apmpackage`
No relevant code changes.
=> build: prevent unintended go.[mod|sum] mutation

docker-compose.yml
[start_time:Mon, 19 Sep 2022 05:16:08 GMT, release_branch:7.17, prefix:, end_time:Mon, 19 Sep 2022 09:54:04 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-73e6ed48, build_duration_seconds:16676]
=> [automation] update elastic stack version for testing 7.17.7-73e6ed48

.ci/benchmarks.groovy, .ci/scripts/download-png-from-kibana.sh, testing/benchmark/README.md
Send slack messages to apm-server channel about benchmark results
https://github.com/elastic/apm-server/issues/7846
=> chore: CI: Benchmark slack notifications

apmpackage/apm/agent/input/template.yml.hbs, apmpackage/apm/changelog.yml, apmpackage/apm/manifest.yml
This will allow managed users to actually try the new experimental feature. 
Relates to: #8607
=> Add package settings for service metrics

docker-compose.yml
[start_time:Tue, 20 Sep 2022 12:16:54 GMT, release_branch:master, prefix:, end_time:Tue, 20 Sep 2022 18:40:35 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:master, build_id:8.5.0-7dc445a0, build_duration_seconds:23021]
=> [automation] update elastic stack version for testing 8.5.0-7dc445a0

docker-compose.yml
[start_time:Tue, 20 Sep 2022 05:15:03 GMT, release_branch:7.17, prefix:, end_time:Tue, 20 Sep 2022 09:54:47 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-a2d4ea28, build_duration_seconds:16784]
=> [automation] update elastic stack version for testing 7.17.7-a2d4ea28

apmpackage/apm/changelog.yml
Fix the apmpackage changelog
cc @elastic/observablt-robots this probably requires a change in the branch creation automation to not create a placeholder entry for release branches.
=> fix apmpackage changelog

docker-compose.yml
[start_time:Wed, 21 Sep 2022 05:20:29 GMT, release_branch:7.17, prefix:, end_time:Wed, 21 Sep 2022 10:25:35 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-86b6ff03, build_duration_seconds:18306]
=> [automation] update elastic stack version for testing 7.17.7-86b6ff03

apmpackage/apm/changelog.yml
Fix 8.5 snapshot package build.
The top-most version must be "generated", which is replaced at package generation/build time. For `make build-package-snapshot`, the version includes a timestamp.
Make sure 8.5 DRA succeeds.
None
=> apmpackage: fix changelog

docker-compose.yml
[start_time:Fri, 23 Sep 2022 00:15:40 GMT, release_branch:8.4, prefix:, end_time:Fri, 23 Sep 2022 04:56:22 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-24191b6e, build_duration_seconds:16842]
=> [automation] update elastic stack version for testing 8.4.3-24191b6e

docker-compose.yml
[start_time:Thu, 22 Sep 2022 05:24:41 GMT, release_branch:7.17, prefix:, end_time:Thu, 22 Sep 2022 10:23:35 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-f08d978f, build_duration_seconds:17934]
=> [automation] update elastic stack version for testing 7.17.7-f08d978f

docker-compose.yml
[start_time:Sun, 25 Sep 2022 00:16:20 GMT, release_branch:master, prefix:, end_time:Sun, 25 Sep 2022 04:42:27 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-21651da3, build_duration_seconds:15967]
=> [automation] update elastic stack version for testing 8.6.0-21651da3

docker-compose.yml
[start_time:Sun, 25 Sep 2022 00:18:09 GMT, release_branch:8.5, prefix:, end_time:Sun, 25 Sep 2022 05:49:46 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-d04a8a8e, build_duration_seconds:19897]
=> [automation] update elastic stack version for testing 8.5.0-d04a8a8e

docker-compose.yml
[start_time:Sun, 25 Sep 2022 05:17:08 GMT, release_branch:7.17, prefix:, end_time:Sun, 25 Sep 2022 10:07:40 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-a7e2fef6, build_duration_seconds:17432]
=> [automation] update elastic stack version for testing 7.17.7-a7e2fef6

apmpackage/apm/data_stream/app_logs/fields/fields.yml, apmpackage/apm/data_stream/app_metrics/fields/fields.yml, apmpackage/apm/data_stream/error_logs/fields/fields.yml, apmpackage/apm/data_stream/internal_metrics/fields/fields.yml, apmpackage/apm/data_stream/traces/fields/fields.yml
Flatten `fields.yml` files, making them a bit easier to navigate. Rather than having to track indentation, we can grep for field names, prefixes, etc. This may also be necessary for [`subobjects: false`](https://www.elastic.co/guide/en/elasticsearch/reference/current/subobjects.html), when we get to it.
The changes is mechanical, using https://gist.github.com/axw/bba69ae5bc34179abc5e19744949f7bc
N/A, this is a non-functional change.
None
=> apmpackage: flatten fields.yml files

docker-compose.yml
[start_time:Mon, 26 Sep 2022 00:18:40 GMT, release_branch:8.4, prefix:, end_time:Mon, 26 Sep 2022 06:27:02 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-3f1f47b9, build_duration_seconds:22102]
=> [automation] update elastic stack version for testing 8.4.3-3f1f47b9

docker-compose.yml
[start_time:Mon, 26 Sep 2022 12:16:45 GMT, release_branch:master, prefix:, end_time:Mon, 26 Sep 2022 16:24:21 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-326f84b0, build_duration_seconds:14856]
=> [automation] update elastic stack version for testing 8.6.0-326f84b0

docker-compose.yml
[start_time:Mon, 26 Sep 2022 00:16:11 GMT, release_branch:8.5, prefix:, end_time:Mon, 26 Sep 2022 05:43:31 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-d6bc1fd7, build_duration_seconds:19640]
=> [automation] update elastic stack version for testing 8.5.0-d6bc1fd7

docker-compose.yml
[start_time:Mon, 26 Sep 2022 05:15:14 GMT, release_branch:7.17, prefix:, end_time:Mon, 26 Sep 2022 09:55:02 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-3d172834, build_duration_seconds:16788]
=> [automation] update elastic stack version for testing 7.17.7-3d172834

changelogs/head.asciidoc, internal/beater/api/intake/handler.go, internal/beater/request/context.go, internal/beater/request/context_test.go
These are not used by stack monitoring, and I don't think they have ever been useful for supportability, so let's remove them.
N/A
Closes #9079
=> Remove `apm-server.decoder.*` metrics

apmpackage/apm/changelog.yml, apmpackage/apm/data_stream/app_metrics/manifest.yml, apmpackage/apm/data_stream/internal_metrics/manifest.yml, changelogs/head.asciidoc, systemtest/approvals.go, systemtest/approvals/TestAgentConfig.approved.json, systemtest/approvals/TestApprovedMetrics.approved.json, systemtest/approvals/TestIngestPipelineDataStreamMigration.approved.json, systemtest/approvals/TestOTLPGRPCMetrics.approved.json, systemtest/approvals/TestRUMXForwardedFor.approved.json, systemtest/approvals/TestServiceDestinationAggregation.approved.json, systemtest/approvals/TestServiceMetricsAggregation.approved.json, systemtest/approvals/TestTransactionAggregation.approved.json, systemtest/approvals/TestTransactionAggregationShutdown.approved.json, systemtest/approvals/TestTransactionDroppedSpansStatsMetrics.approved.json, systemtest/metrics_test.go
Enable synthetic source by default for APM's metrics data streams. See https://github.com/elastic/apm-server/issues/9010 for motiviation.
It is possible to disable synthetic source by modifying the `@custom` component template, e.g.
```
PUT /_component_template/metrics-apm.app@custom
{
"template": {
"mappings": {
"_source": {}
}
}
}
```
1. Send some transactions, spans with `service.target.*`, and custom application metrics
2. Confirm that synthetic source is enabled for the APM metrics data streams (internal & …
=> Enable synthetic source for metrics data streams

docs/open-telemetry.asciidoc
Links were pointing to wrong location, so https://www.elastic.co/guide/en/apm/guide/7.16/open-telemetry.html was not showing  images.
=> 7.16-docs: Fixed image links in opentelemetry doc

testing/smoke/basic-upgrade/test.sh, testing/smoke/legacy-managed/test.sh, testing/smoke/legacy-standalone-major-managed/test.sh, testing/smoke/lib.sh, testing/smoke/main.tf
Removes the usage of the Elastic artifacts API, in favor of using the Elastic Cloud API to obtain all the stack pack versions available in the configured ESS region.
This approach is better than using the artifacts API for two reasons:
1. Artifacts API and ESS regions may have different stack packs
2. Unused artifacts are removed after 30 days.
By using the ESS API, we no longer will see failures due to a missing BC or old versions removed (or the `7.17.x` older versions).
Last, it also adds the `SKIP_DESTROY` conditional to all the `test.sh` scripts.
~- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to …
=> smoke: Remove usage of artifacts API
