elastic/apm-server

- testing/benchmark/main.tf
- testing/cloud/main.tf
- testing/infra/terraform/modules/ec_deployment/README.md
- testing/infra/terraform/modules/ec_deployment/deployment.tf
- testing/infra/terraform/modules/ec_deployment/variables.tf
- testing/smoke/main.tf
Updates the `ec_deployment` terraform module variables defaults to match the default variables in an ESS deployment.
- `integrations_server`: `false` => `true`
- `apm_server_expvar`: `true` => `false`
- `apm_server_pprof`: `true` => `false`
N/A
Closes #9123
> tf/ec_deployment: Match ESS defaults

- docker-compose.yml
[start_time:Thu, 29 Sep 2022 00:19:36 GMT, release_branch:8.4, prefix:, end_time:Thu, 29 Sep 2022 06:25:42 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-0900b129, build_duration_seconds:21966]
> [automation] update elastic stack version for testing 8.4.3-0900b129

- docker-compose.yml
[start_time:Fri, 30 Sep 2022 00:15:45 GMT, release_branch:master, prefix:, end_time:Fri, 30 Sep 2022 04:40:25 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-158a13db, build_duration_seconds:15880]
> [automation] update elastic stack version for testing 8.6.0-158a13db

- docker-compose.yml
[start_time:Thu, 29 Sep 2022 00:15:42 GMT, release_branch:8.5, prefix:, end_time:Thu, 29 Sep 2022 05:36:58 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-b22c068f, build_duration_seconds:19276]
> [automation] update elastic stack version for testing 8.5.0-b22c068f

- x-pack/apm-server/main.go
- x-pack/apm-server/main_test.go
- x-pack/apm-server/profiling/collector.go
Profiling sends host-agent metrics into Elasticsearch for debugging purposes.
To improve our troubleshooting process in Cloud, we add in every metrics document the cluster ID.
- Is it observable through the addition of either **logging** or **metrics**? ✅ 
- Is its use being published in **telemetry** to enable product improvement? ⛔ 
- Have system tests been added to avoid regression? ✅ 
You can configure the metrics endpoint in the apm-server Fleet policy with the same endpoint where data are sent (apm-server.profiling.metrics.elasticsearch.hosts`) and you'll see the additional field in the documents in the `profiling-metrics` data stream.
> Profiling: add cluster id in metrics docs

- docs/apm-mutating-webhook.asciidoc
- docs/aws-lambda-extension.asciidoc
- docs/integrations-index.asciidoc
Removes included content for the Lambda extension and APM attacher.
For https://github.com/elastic/observability-docs/issues/2207.
Blocked by:
~- [ ] https://github.com/elastic/docs/pull/2535~
> docs: remove included extension content

- docs/aws-lambda-extension.asciidoc
- docs/integrations-index.asciidoc
A follow-up to https://github.com/elastic/apm-server/pull/9246. This PR removes AWS includes from the 8.3 branch.
> docs: remove aws includes

- docs/aws-lambda-extension.asciidoc
- docs/features.asciidoc
- docs/integrations-index.asciidoc
This will backport the following commits from `8.3` to `7.17`:
> [7.17] docs: remove aws includes (#9253)

- testing/infra/terraform/modules/ec_deployment/scripts/index_shards.tftpl
- testing/smoke/lib.sh
Reverts elastic/apm-server#9238 since the CI seems to use an old version of curl that doesn't have that flag.
> Revert "smoke: Use cURL `--fail-with-body` option"

- docker-compose.yml
[start_time:Mon, 3 Oct 2022 12:16:03 GMT, release_branch:8.4, prefix:, end_time:Mon, 3 Oct 2022 17:19:22 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-5e0dd488, build_duration_seconds:18199]
> [automation] update elastic stack version for testing 8.4.3-5e0dd488

- docker-compose.yml
[start_time:Mon, 3 Oct 2022 16:39:13 GMT, release_branch:8.5, prefix:, end_time:Mon, 3 Oct 2022 21:30:10 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-49b2dce3, build_duration_seconds:17457]
> [automation] update elastic stack version for testing 8.5.0-49b2dce3

- docker-compose.yml
[start_time:Tue, 4 Oct 2022 12:15:44 GMT, release_branch:8.4, prefix:, end_time:Tue, 4 Oct 2022 17:28:31 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-ff95b7c5, build_duration_seconds:18767]
> [automation] update elastic stack version for testing 8.4.3-ff95b7c5

- docker-compose.yml
[start_time:Tue, 4 Oct 2022 05:15:08 GMT, release_branch:7.17, prefix:, end_time:Tue, 4 Oct 2022 10:09:11 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-70d4ef7d, build_duration_seconds:17643]
> [automation] update elastic stack version for testing 7.17.7-70d4ef7d

- docs/aws-lambda-extension.asciidoc
- docs/integrations-index.asciidoc
This will backport the following commits from `8.3` to `8.2`:
> [8.2] docs: remove aws includes (#9253)

- docs/aws-lambda-extension.asciidoc
- docs/features.asciidoc
- docs/integrations-index.asciidoc
This will backport the following commits from `8.3` to `8.0`:
> [8.0] docs: remove aws includes (#9253)

- apmpackage/apm/changelog.yml
- cmd/intake-receiver/version.go
- internal/version/version.go
Prepare for `8.4.3` release. To be merged after `8.4.3` is cut.
> Bump version to 8.4.4

- docs/aws-lambda-extension.asciidoc
- docs/integrations-index.asciidoc
This will backport the following commits from `8.3` to `8.1`:
> [8.1] docs: remove aws includes (#9253)

- docs/aws-lambda-extension.asciidoc
- docs/features.asciidoc
- docs/integrations-index.asciidoc
This will backport the following commits from `8.3` to `7.16`:
> [7.16] docs: remove aws includes (#9253)

- docker-compose.yml
[start_time:Wed, 5 Oct 2022 00:18:04 GMT, release_branch:8.4, prefix:, end_time:Wed, 5 Oct 2022 05:43:24 GMT, manifest_version:2.1.0, version:8.4.3-SNAPSHOT, branch:8.4, build_id:8.4.3-83e508e5, build_duration_seconds:19520]
> [automation] update elastic stack version for testing 8.4.3-83e508e5

- docker-compose.yml
[start_time:Thu, 6 Oct 2022 05:19:34 GMT, release_branch:7.17, prefix:, end_time:Thu, 6 Oct 2022 10:04:50 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-f9849b81, build_duration_seconds:17116]
> [automation] update elastic stack version for testing 7.17.7-f9849b81

- docker-compose.yml
[start_time:Sun, 9 Oct 2022 12:16:02 GMT, release_branch:8.4, prefix:, end_time:Sun, 9 Oct 2022 17:16:03 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-17ce02d0, build_duration_seconds:18001]
> [automation] update elastic stack version for testing 8.4.4-17ce02d0

- docker-compose.yml
[start_time:Sun, 9 Oct 2022 00:16:22 GMT, release_branch:master, prefix:, end_time:Sun, 9 Oct 2022 05:40:47 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-7c9f25a9, build_duration_seconds:19465]
> [automation] update elastic stack version for testing 8.6.0-7c9f25a9

- docker-compose.yml
[start_time:Sun, 9 Oct 2022 05:15:03 GMT, release_branch:7.17, prefix:, end_time:Sun, 9 Oct 2022 09:34:40 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-3947c049, build_duration_seconds:15577]
> [automation] update elastic stack version for testing 7.17.7-3947c049

- docker-compose.yml
[start_time:Mon, 10 Oct 2022 18:58:59 GMT, release_branch:master, prefix:, end_time:Mon, 10 Oct 2022 23:29:50 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-c49fac70, build_duration_seconds:16251]
> [automation] update elastic stack version for testing 8.6.0-c49fac70

- docker-compose.yml
[start_time:Mon, 10 Oct 2022 05:19:17 GMT, release_branch:7.17, prefix:, end_time:Mon, 10 Oct 2022 09:38:59 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-32fc38cc, build_duration_seconds:15582]
> [automation] update elastic stack version for testing 7.17.7-32fc38cc

- testing/benchmark/main.tf
- testing/benchmark/variables.tf
- testing/infra/terraform/modules/ec_deployment/.gitignore
- testing/infra/terraform/modules/ec_deployment/README.md
- testing/infra/terraform/modules/ec_deployment/deployment.tf
- testing/infra/terraform/modules/ec_deployment/scripts/drop_pipeline.tftpl
- testing/infra/terraform/modules/ec_deployment/variables.tf
- testing/infra/terraform/modules/rally_workers/README.md
Introduces a new `drop_pipeline` variable which can be used to measure the theoretical maximum output from the APM Server.
Enable `drop_pipeline` in `testing/benchmark`.
Seemed from #9180
> ec_deployment: Add `drop_pipeline` variable

- docker-compose.yml
[start_time:Wed, 12 Oct 2022 00:16:08 GMT, release_branch:8.4, prefix:, end_time:Wed, 12 Oct 2022 04:58:52 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-5fbb5bd0, build_duration_seconds:16964]
> [automation] update elastic stack version for testing 8.4.4-5fbb5bd0

- docker-compose.yml
[start_time:Tue, 11 Oct 2022 00:20:39 GMT, release_branch:master, prefix:, end_time:Tue, 11 Oct 2022 06:28:26 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-5a8d757d, build_duration_seconds:22067]
> [automation] update elastic stack version for testing 8.6.0-5a8d757d

- docker-compose.yml
[start_time:Tue, 11 Oct 2022 00:22:09 GMT, release_branch:8.5, prefix:, end_time:Tue, 11 Oct 2022 07:37:10 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-09886b6e, build_duration_seconds:26101]
> [automation] update elastic stack version for testing 8.5.0-09886b6e

- docker-compose.yml
[start_time:Tue, 11 Oct 2022 05:15:43 GMT, release_branch:7.17, prefix:, end_time:Tue, 11 Oct 2022 09:56:33 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-8081bbcb, build_duration_seconds:16850]
> [automation] update elastic stack version for testing 7.17.7-8081bbcb

- docker-compose.yml
[start_time:Wed, 12 Oct 2022 12:16:08 GMT, release_branch:master, prefix:, end_time:Wed, 12 Oct 2022 16:34:46 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-40086bc7, build_duration_seconds:15518]
> [automation] update elastic stack version for testing 8.6.0-40086bc7

- docker-compose.yml
[start_time:Wed, 12 Oct 2022 12:15:59 GMT, release_branch:8.4, prefix:, end_time:Wed, 12 Oct 2022 17:17:33 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-1129f33b, build_duration_seconds:18094]
> [automation] update elastic stack version for testing 8.4.4-1129f33b

- docker-compose.yml
[start_time:Wed, 12 Oct 2022 00:16:08 GMT, release_branch:8.5, prefix:, end_time:Wed, 12 Oct 2022 05:39:36 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-fe2e6147, build_duration_seconds:19408]
> [automation] update elastic stack version for testing 8.5.0-fe2e6147

- docker-compose.yml
[start_time:Wed, 12 Oct 2022 05:15:12 GMT, release_branch:7.17, prefix:, end_time:Wed, 12 Oct 2022 10:31:21 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-a44998d0, build_duration_seconds:18969]
> [automation] update elastic stack version for testing 7.17.7-a44998d0

- docker-compose.yml
[start_time:Thu, 13 Oct 2022 05:16:44 GMT, release_branch:7.17, prefix:, end_time:Thu, 13 Oct 2022 10:00:38 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-40d7eba9, build_duration_seconds:17034]
> [automation] update elastic stack version for testing 7.17.7-40d7eba9

- changelogs/7.17.asciidoc
Closes https://github.com/elastic/apm-server/issues/9080.
I followed the lead of Beats and added this as a breaking change ([link](https://github.com/elastic/beats/blame/b69d3f0695088ccfa32ebb14f6c24df028c2eb0b/CHANGELOG.next.asciidoc#L9-L13)).
> docs: add 7.17.7 breaking change

- docker-compose.yml
[start_time:Sun, 16 Oct 2022 00:15:37 GMT, release_branch:8.5, prefix:, end_time:Sun, 16 Oct 2022 05:34:22 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-f8c98e5d, build_duration_seconds:19125]
> [automation] update elastic stack version for testing 8.5.0-f8c98e5d

- docker-compose.yml
[start_time:Sun, 16 Oct 2022 12:16:14 GMT, release_branch:8.4, prefix:, end_time:Sun, 16 Oct 2022 17:02:55 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-2db0c963, build_duration_seconds:17201]
> [automation] update elastic stack version for testing 8.4.4-2db0c963

- docker-compose.yml
[start_time:Sun, 16 Oct 2022 05:16:04 GMT, release_branch:7.17, prefix:, end_time:Sun, 16 Oct 2022 09:52:19 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-e7a47621, build_duration_seconds:16575]
> [automation] update elastic stack version for testing 7.17.7-e7a47621

- internal/beatcmd/beat.go
- internal/beatcmd/maxprocs.go
- internal/beatcmd/maxprocs_test.go
TestAdjustMaxProcs* tests have been failing intermittently, particularly on the macOS GitHub action. The tests assume that the timer will run at least 10 times, with a ticker duration of 1ms and total duration of 50ms. This is not guaranteed, and is causing failures on slow CI machines.
The two tests are replaced with one test which checks that duplicate logs are suppressed, and that changes to the GOMAXPROCS environment variable are picked up and trigger a log message. The latter implictly tests that the ticker is effective. The code-under-test is simple enough that we can rely on manual code inspection to ensure the correct duration is used.
~- [ ] Update [package …
> beatcmd: make GOMAXPROCS test more robust

- changelogs/head.asciidoc
- internal/model/modeldecoder/nullable/nullable.go
- internal/model/modeldecoder/nullable/nullable_test.go
Add support for string formatted timestamp.
See [this comment 
](https://github.com/elastic/apm-server/pull/9349#issuecomment-1278968410)
1. Create a request body for the `log` event type:
```json
{"metadata":{"process":{"pid":1234,"title":"/usr/lib/jvm/java-10-openjdk-amd64/bin/java","ppid":1,"argv":["-v"]},"system":{"architecture":"amd64","detected_hostname":"8ec7ceb99074","configured_hostname":"host1","platform":"Linux","container":{"id":"8ec7ceb990749e79b37f6dc6cd3628633618d6ce412553a552a0fa6b69419ad4"},"kubernetes":{"namespace":"default","pod":{"uid":"b17f231da0ad128dc6c6c0b2e82f …
```
> Support string format for timestamp

- docker-compose.yml
[start_time:Mon, 17 Oct 2022 12:16:24 GMT, release_branch:8.4, prefix:, end_time:Mon, 17 Oct 2022 17:30:17 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-93b2bfdf, build_duration_seconds:18833]
> [automation] update elastic stack version for testing 8.4.4-93b2bfdf

- docker-compose.yml
[start_time:Mon, 17 Oct 2022 00:17:28 GMT, release_branch:8.5, prefix:, end_time:Mon, 17 Oct 2022 05:59:35 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-7c74e950, build_duration_seconds:20527]
> [automation] update elastic stack version for testing 8.5.0-7c74e950

- docker-compose.yml
[start_time:Mon, 17 Oct 2022 05:15:13 GMT, release_branch:7.17, prefix:, end_time:Mon, 17 Oct 2022 09:50:51 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-f82fb944, build_duration_seconds:16538]
> [automation] update elastic stack version for testing 7.17.7-f82fb944

- docker-compose.yml
[start_time:Tue, 18 Oct 2022 00:15:53 GMT, release_branch:8.4, prefix:, end_time:Tue, 18 Oct 2022 06:14:56 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-e97ba82f, build_duration_seconds:21543]
> [automation] update elastic stack version for testing 8.4.4-e97ba82f

- docker-compose.yml
[start_time:Tue, 18 Oct 2022 00:16:10 GMT, release_branch:8.5, prefix:, end_time:Tue, 18 Oct 2022 05:44:24 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-792499b4, build_duration_seconds:19694]
> [automation] update elastic stack version for testing 8.5.0-792499b4

- docker-compose.yml
[start_time:Wed, 19 Oct 2022 05:14:59 GMT, release_branch:7.17, prefix:, end_time:Wed, 19 Oct 2022 10:00:21 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-55166c00, build_duration_seconds:17122]
> [automation] update elastic stack version for testing 7.17.7-55166c00

- docker-compose.yml
[start_time:Fri, 21 Oct 2022 00:15:47 GMT, release_branch:master, prefix:, end_time:Fri, 21 Oct 2022 04:31:51 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-baf193e8, build_duration_seconds:15364]
> [automation] update elastic stack version for testing 8.6.0-baf193e8

- docker-compose.yml
[start_time:Thu, 20 Oct 2022 12:15:32 GMT, release_branch:8.4, prefix:, end_time:Thu, 20 Oct 2022 18:55:40 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-4edb5c6b, build_duration_seconds:24008]
> [automation] update elastic stack version for testing 8.4.4-4edb5c6b

- docker-compose.yml
[start_time:Thu, 20 Oct 2022 13:32:18 GMT, release_branch:8.5, prefix:, end_time:Thu, 20 Oct 2022 20:19:57 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-754ef325, build_duration_seconds:24459]
> [automation] update elastic stack version for testing 8.5.0-754ef325

- docker-compose.yml
[start_time:Thu, 20 Oct 2022 05:14:45 GMT, release_branch:7.17, prefix:, end_time:Thu, 20 Oct 2022 10:18:24 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-60386d02, build_duration_seconds:18219]
> [automation] update elastic stack version for testing 7.17.7-60386d02

- docker-compose.yml
[start_time:Sun, 23 Oct 2022 12:16:00 GMT, release_branch:8.4, prefix:, end_time:Sun, 23 Oct 2022 18:09:57 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-9b801d60, build_duration_seconds:21237]
> [automation] update elastic stack version for testing 8.4.4-9b801d60

- docker-compose.yml
[start_time:Sun, 23 Oct 2022 12:16:04 GMT, release_branch:master, prefix:, end_time:Sun, 23 Oct 2022 16:44:33 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-22d60ec9, build_duration_seconds:16109]
> [automation] update elastic stack version for testing 8.6.0-22d60ec9

- docker-compose.yml
[start_time:Sat, 22 Oct 2022 05:15:49 GMT, release_branch:7.17, prefix:, end_time:Sat, 22 Oct 2022 09:55:39 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-e6ce36d2, build_duration_seconds:16790]
> [automation] update elastic stack version for testing 7.17.7-e6ce36d2

- docker-compose.yml
[start_time:Mon, 24 Oct 2022 00:18:19 GMT, release_branch:8.4, prefix:, end_time:Mon, 24 Oct 2022 08:07:26 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-46f2f222, build_duration_seconds:28147]
> [automation] update elastic stack version for testing 8.4.4-46f2f222

- docker-compose.yml
[start_time:Mon, 24 Oct 2022 12:15:56 GMT, release_branch:master, prefix:, end_time:Mon, 24 Oct 2022 16:17:06 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-b8b35931, build_duration_seconds:14470]
> [automation] update elastic stack version for testing 8.6.0-b8b35931

- docker-compose.yml
[start_time:Mon, 24 Oct 2022 05:14:57 GMT, release_branch:7.17, prefix:, end_time:Mon, 24 Oct 2022 10:06:02 GMT, manifest_version:2.1.0, version:7.17.7-SNAPSHOT, branch:7.17, build_id:7.17.7-0a02d958, build_duration_seconds:17465]
> [automation] update elastic stack version for testing 7.17.7-0a02d958

- docker-compose.yml
[start_time:Tue, 25 Oct 2022 00:15:35 GMT, release_branch:8.4, prefix:, end_time:Tue, 25 Oct 2022 06:42:27 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-1ee39d03, build_duration_seconds:23212]
> [automation] update elastic stack version for testing 8.4.4-1ee39d03

- docker-compose.yml
[start_time:Tue, 25 Oct 2022 00:16:03 GMT, release_branch:8.5, prefix:, end_time:Tue, 25 Oct 2022 08:36:17 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-bdb74671, build_duration_seconds:30014]
> [automation] update elastic stack version for testing 8.5.0-bdb74671

- docker-compose.yml
[start_time:Wed, 26 Oct 2022 15:48:54 GMT, release_branch:master, prefix:, end_time:Wed, 26 Oct 2022 21:14:19 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-a892f234, build_duration_seconds:19525]
> [automation] update elastic stack version for testing 8.6.0-a892f234

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 27 Oct 2022 12:15:57 GMT, release_branch:master, prefix:, end_time:Thu, 27 Oct 2022 21:32:41 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-89d224d2, build_duration_seconds:33404]
> [automation] update elastic stack version for testing 8.6.0-89d224d2

- docker-compose.yml
[start_time:Thu, 27 Oct 2022 21:30:37 GMT, release_branch:8.5, prefix:, end_time:Fri, 28 Oct 2022 04:13:48 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-4028b295, build_duration_seconds:24191]
> [automation] update elastic stack version for testing 8.5.0-4028b295

- docker-compose.yml
[start_time:Thu, 27 Oct 2022 13:12:21 GMT, release_branch:8.4, prefix:, end_time:Thu, 27 Oct 2022 17:47:34 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-6eb63640, build_duration_seconds:16513]
> [automation] update elastic stack version for testing 8.4.4-6eb63640

- docker-compose.yml
[start_time:Thu, 27 Oct 2022 05:15:13 GMT, release_branch:7.17, prefix:, end_time:Thu, 27 Oct 2022 10:58:23 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-d89bf16d, build_duration_seconds:20590]
> [automation] update elastic stack version for testing 7.17.8-d89bf16d

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Sat, 29 Oct 2022 12:15:30 GMT, release_branch:master, prefix:, end_time:Sat, 29 Oct 2022 16:00:26 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-949a38d2, build_duration_seconds:13496]
> [automation] update elastic stack version for testing 8.6.0-949a38d2

- docker-compose.yml
[start_time:Sat, 29 Oct 2022 12:15:37 GMT, release_branch:8.4, prefix:, end_time:Sat, 29 Oct 2022 17:42:22 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-f3b8851a, build_duration_seconds:19605]
> [automation] update elastic stack version for testing 8.4.4-f3b8851a

- docker-compose.yml
[start_time:Sat, 29 Oct 2022 04:07:22 GMT, release_branch:8.5, prefix:, end_time:Sat, 29 Oct 2022 09:13:48 GMT, manifest_version:2.1.0, version:8.5.0-SNAPSHOT, branch:8.5, build_id:8.5.0-f48cdca0, build_duration_seconds:18386]
> [automation] update elastic stack version for testing 8.5.0-f48cdca0

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Mon, 31 Oct 2022 14:45:15 GMT, release_branch:master, prefix:, end_time:Mon, 31 Oct 2022 19:08:41 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-26dc1164, build_duration_seconds:15806]
> [automation] update elastic stack version for testing 8.6.0-26dc1164

- docker-compose.yml
[start_time:Mon, 31 Oct 2022 12:16:05 GMT, release_branch:8.4, prefix:, end_time:Mon, 31 Oct 2022 18:30:49 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-55734bd7, build_duration_seconds:22484]
> [automation] update elastic stack version for testing 8.4.4-55734bd7

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Wed, 2 Nov 2022 00:15:58 GMT, release_branch:master, prefix:, end_time:Wed, 2 Nov 2022 04:57:55 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-4765d2b0, build_duration_seconds:16917]
> [automation] update elastic stack version for testing 8.6.0-4765d2b0

- docker-compose.yml
[start_time:Wed, 2 Nov 2022 00:16:22 GMT, release_branch:8.4, prefix:, end_time:Wed, 2 Nov 2022 05:57:50 GMT, manifest_version:2.1.0, version:8.4.4-SNAPSHOT, branch:8.4, build_id:8.4.4-dcd4a95f, build_duration_seconds:20488]
> [automation] update elastic stack version for testing 8.4.4-dcd4a95f

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Wed, 2 Nov 2022 12:17:07 GMT, release_branch:master, prefix:, end_time:Wed, 2 Nov 2022 16:53:57 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-8a615646, build_duration_seconds:16610]
> [automation] update elastic stack version for testing 8.6.0-8a615646

- docker-compose.yml
[start_time:Thu, 3 Nov 2022 21:35:24 GMT, release_branch:8.5, prefix:, end_time:Fri, 4 Nov 2022 02:17:02 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-7fd6ffae, build_duration_seconds:16898]
> [automation] update elastic stack version for testing 8.5.1-7fd6ffae

- docker-compose.yml
[start_time:Thu, 3 Nov 2022 05:15:37 GMT, release_branch:7.17, prefix:, end_time:Thu, 3 Nov 2022 09:59:11 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-1d146f89, build_duration_seconds:17014]
> [automation] update elastic stack version for testing 7.17.8-1d146f89

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Fri, 4 Nov 2022 14:42:08 GMT, release_branch:master, prefix:, end_time:Fri, 4 Nov 2022 22:58:50 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-f20b7179, build_duration_seconds:29802]
> [automation] update elastic stack version for testing 8.6.0-f20b7179

- docker-compose.yml
[start_time:Sun, 6 Nov 2022 12:15:33 GMT, release_branch:8.5, prefix:, end_time:Sun, 6 Nov 2022 17:43:52 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-2ceb7fad, build_duration_seconds:19699]
> [automation] update elastic stack version for testing 8.5.1-2ceb7fad

- docker-compose.yml
[start_time:Fri, 4 Nov 2022 13:53:36 GMT, release_branch:7.17, prefix:, end_time:Fri, 4 Nov 2022 20:38:56 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-a281a566, build_duration_seconds:24320]
> [automation] update elastic stack version for testing 7.17.8-a281a566

- .ci/scripts/download-png-from-kibana.sh
Due to incorrect time zone and version request parameters we had wrong PNG screenshot in slack report
Ideally wait for the next benckmark execution
> Benchmark reporting: fixed Kibana request timezone and stack version

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 8 Nov 2022 12:16:12 GMT, release_branch:master, prefix:, end_time:Tue, 8 Nov 2022 19:54:15 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-da453972, build_duration_seconds:27483]
> [automation] update elastic stack version for testing 8.6.0-da453972

- docker-compose.yml
[start_time:Tue, 8 Nov 2022 12:16:08 GMT, release_branch:8.5, prefix:, end_time:Wed, 9 Nov 2022 04:55:08 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-2041424b, build_duration_seconds:59940]
> [automation] update elastic stack version for testing 8.5.1-2041424b

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Wed, 9 Nov 2022 00:18:40 GMT, release_branch:master, prefix:, end_time:Wed, 9 Nov 2022 05:07:05 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:master, build_id:8.6.0-c9d1a5e9, build_duration_seconds:17305]
> [automation] update elastic stack version for testing 8.6.0-c9d1a5e9

- docker-compose.yml
[start_time:Thu, 10 Nov 2022 00:15:49 GMT, release_branch:8.5, prefix:, end_time:Thu, 10 Nov 2022 04:24:22 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-6bdef2c7, build_duration_seconds:14913]
> [automation] update elastic stack version for testing 8.5.1-6bdef2c7

- docker-compose.yml
[start_time:Wed, 9 Nov 2022 05:16:53 GMT, release_branch:7.17, prefix:, end_time:Wed, 9 Nov 2022 10:44:22 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-e6d29314, build_duration_seconds:19649]
> [automation] update elastic stack version for testing 7.17.8-e6d29314

- .ci/benchmarks.groovy
Populate the date when the resources are created and fixed some linting and cosmetic changes in the pipeline
In the CI
> populate date label/tag in terraform

- docker-compose.yml
[start_time:Thu, 10 Nov 2022 12:15:45 GMT, release_branch:8.5, prefix:, end_time:Thu, 10 Nov 2022 17:34:17 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-1f91140d, build_duration_seconds:19112]
> [automation] update elastic stack version for testing 8.5.1-1f91140d

- docker-compose.yml
[start_time:Mon, 14 Nov 2022 00:15:30 GMT, release_branch:8.5, prefix:, end_time:Mon, 14 Nov 2022 04:51:59 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-d7343c55, build_duration_seconds:16589]
> [automation] update elastic stack version for testing 8.5.1-d7343c55

- docker-compose.yml
[start_time:Sun, 13 Nov 2022 05:15:09 GMT, release_branch:7.17, prefix:, end_time:Sun, 13 Nov 2022 11:12:07 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-8be7042c, build_duration_seconds:21418]
> [automation] update elastic stack version for testing 7.17.8-8be7042c

- changelogs/head.asciidoc
- internal/beater/config/agentconfig.go
- internal/beater/config/agentconfig_test.go
- internal/beater/config/config.go
- internal/beater/config/config_test.go
Allow a null `config` attribute in `agent_config` entries, treating it the same as an empty config map.
When no attributes are specified in an APM Agent central config entry, it will be added by APM UI to the APM integration policies as `{}`. Somewhere along the way to APM Server this is translated to `null`.
See https://github.com/elastic/apm-server/issues/9545
Closes https://github.com/elastic/apm-server/issues/9545
> beater/config: treat null agent config as empty

- .ci/benchmarks.groovy
Populates the empty variable `USER` with `bench-ci-<build_id>` to avoid jobs from running into collisions should any of the previous jobs fail to clean up the resources properly.
N/A
Failing nightly benchmarks
> ci: Populate `USER` variable with build id

- docker-compose.yml
[start_time:Mon, 14 Nov 2022 12:15:55 GMT, release_branch:8.5, prefix:, end_time:Mon, 14 Nov 2022 16:21:00 GMT, manifest_version:2.1.0, version:8.5.1-SNAPSHOT, branch:8.5, build_id:8.5.1-49e04c16, build_duration_seconds:14705]
> [automation] update elastic stack version for testing 8.5.1-49e04c16

- docker-compose.yml
[start_time:Mon, 14 Nov 2022 05:15:11 GMT, release_branch:7.17, prefix:, end_time:Mon, 14 Nov 2022 11:11:46 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-581ea684, build_duration_seconds:21395]
> [automation] update elastic stack version for testing 7.17.8-581ea684

- .ci/benchmarks.groovy
Split the post build to run the `cleanup` for the tearing down process only
> cleanup
Run the steps in this post condition after every other post condition has been evaluated, regardless of the Pipeline or stage’s status.
> bench: tear down the environment within the post-cleanup stage

- docker-compose.yml
[start_time:Tue, 15 Nov 2022 05:15:13 GMT, release_branch:7.17, prefix:, end_time:Tue, 15 Nov 2022 10:45:07 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-e4279e1a, build_duration_seconds:19794]
> [automation] update elastic stack version for testing 7.17.8-e4279e1a

- .ci/benchmarks.groovy
Disables the Kibana PNG download and reporting to Slack. Main reason is that it causes the build to fail unnecessarily.
> ci: Disable failing benchmark report

- .mergify.yml
- apmpackage/apm/changelog.yml
- cmd/intake-receiver/version.go
- internal/version/version.go
Merge as soon as 8.6 branch was created. Auto-merge is not yet supported, see https://github.com/Mergifyio/mergify-engine/discussions/2821
> backport: Add 8.6 branch

- x-pack/apm-server/profiling/collector.go
`Error` was being called with a format string, switched to `Errorf`.
> Universal Profiling: Fix error logging

- x-pack/apm-server/sampling/eventstorage/badger.go
- x-pack/apm-server/sampling/eventstorage/sharded.go
- x-pack/apm-server/sampling/eventstorage/storage.go
- x-pack/apm-server/sampling/eventstorage/storage_test.go
- x-pack/apm-server/sampling/pubsub/pubsub.go
Discards the badger transaction when the soft limit has reached. This fixes a problem where each of the sharded readWriters would accumulate events in the `badger.Tx` until the transaction is full. This led to ouf of memory issues when the storage soft limit is reached.
Additionally, reduce the number of sharded readWriters to `GOMAXPROCS` rather than using the `NumCPU()`, since the latter causes containerized workloads to have (mostly) greater number of sharded readWriters than it most likely has access to, which will also reduce the memory usage for TBS.
Last, modifies the options which are used to open the Badger database:
- `Truncate=true`: Allows space reclamationfor vlog unreadable files.
- `NumMemtables=4`: From 5.
- `NumLevelZeroTables=4`: From 5.
- `NumLevelZeroTablesStall=12`: …
> sampling: Discard writes on full badger storage

- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
Updates the resource "limits" and "requests" for fleet-server, the ECK operator and the apm-server so memory is allocated a bit better in machines with limited RAM.
Non functional changes
None
> testing/k8s: Set memory limit, deployment strategy

- Makefile
- testing/docker/elastic-agent/build.sh
Avoid requirements to install `coreutils` on macOS by using `readlink` rather than `realpath`.  
Could a reviewer with linux test this change please.
> fix: replace _realpath_ with _readlink -f_

- docker-compose.yml
[start_time:Thu, 17 Nov 2022 12:21:14 GMT, release_branch:8.5, prefix:, end_time:Thu, 17 Nov 2022 16:55:27 GMT, manifest_version:2.1.0, version:8.5.2-SNAPSHOT, branch:8.5, build_id:8.5.2-733d317b, build_duration_seconds:16453]
> [automation] update elastic stack version for testing 8.5.2-733d317b

- docker-compose.yml
[start_time:Thu, 17 Nov 2022 05:15:21 GMT, release_branch:7.17, prefix:, end_time:Thu, 17 Nov 2022 11:15:49 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-ca244ec8, build_duration_seconds:21628]
> [automation] update elastic stack version for testing 7.17.8-ca244ec8

- systemtest/profiling_test.go
Use a wildcard search so search doesn't fail immediately if the index does not exist. Append "-next*", as just "*" would include
the "-next" indices.
Without this change, we get intermittent failures like this:
```
=== RUN   TestProfiling
2022/11/18 13:42:50 Starting container id: 44bcb8ce19a5 image: elastic-agent-systemtest:8.7.0-eb092238-SNAPSHOT
2022/11/18 13:42:50 Waiting for container id 44bcb8ce19a5 image: elastic-agent-systemtest:8.7.0-eb092238-SNAPSHOT
2022/11/18 13:42:57 Container is ready id: 44bcb8ce19a5 image: elastic-agent-systemtest:8.7.0-eb092238-SNAPSHOT
profiling_test.go:176: [404 Not Found] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [profiling-executables]","resource.type":"index_or_alias","resource.id":"profiling-executables","ind …
```
> systemtest: fix flaky TestProfiling test

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Mon, 21 Nov 2022 00:14:45 GMT, release_branch:master, prefix:, end_time:Mon, 21 Nov 2022 03:45:52 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-84b6e00d, build_duration_seconds:12667]
> [automation] update elastic stack version for testing 8.7.0-84b6e00d

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Sun, 20 Nov 2022 00:14:39 GMT, release_branch:8.6, prefix:, end_time:Sun, 20 Nov 2022 05:58:13 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-afa9010f, build_duration_seconds:20614]
> [automation] update elastic stack version for testing 8.6.0-afa9010f

- docker-compose.yml
[start_time:Sun, 20 Nov 2022 12:15:17 GMT, release_branch:8.5, prefix:, end_time:Sun, 20 Nov 2022 16:52:33 GMT, manifest_version:2.1.0, version:8.5.2-SNAPSHOT, branch:8.5, build_id:8.5.2-13a22054, build_duration_seconds:16636]
> [automation] update elastic stack version for testing 8.5.2-13a22054

- docker-compose.yml
[start_time:Fri, 18 Nov 2022 05:15:15 GMT, release_branch:7.17, prefix:, end_time:Fri, 18 Nov 2022 11:05:19 GMT, manifest_version:2.1.0, version:7.17.8-SNAPSHOT, branch:7.17, build_id:7.17.8-c416a4cb, build_duration_seconds:21004]
> [automation] update elastic stack version for testing 7.17.8-c416a4cb

- testing/benchmark/main.tf
- testing/infra/terraform/modules/rally_workers/README.md
- testing/infra/terraform/modules/rally_workers/main.tf
- testing/infra/terraform/modules/soaktest_workers/README.md
- testing/infra/terraform/modules/soaktest_workers/main.tf
- testing/infra/terraform/modules/tags/README.md
- testing/infra/terraform/modules/tags/header.md
- testing/infra/terraform/modules/tags/output.tf
- testing/infra/terraform/modules/tags/vars.tf
Introduces a new `tags` in `testing/infra/terraform/modules/tags` which defines the default CSP tags and accepts a `project` variable, to define the purpose of each importing module.
Also re-formats a few files, and updates the default values for a couple of unknown variables if unset.
N/A
CSP tagging policy.
> compliance: Tag CSP resources according to policy

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 22 Nov 2022 00:14:30 GMT, release_branch:8.6, prefix:, end_time:Tue, 22 Nov 2022 04:45:32 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-e72cd235, build_duration_seconds:16262]
> [automation] update elastic stack version for testing 8.6.0-e72cd235

- docker-compose.yml
[start_time:Mon, 21 Nov 2022 12:15:56 GMT, release_branch:8.5, prefix:, end_time:Mon, 21 Nov 2022 16:49:51 GMT, manifest_version:2.1.0, version:8.5.2-SNAPSHOT, branch:8.5, build_id:8.5.2-c2e5a3f4, build_duration_seconds:16435]
> [automation] update elastic stack version for testing 8.5.2-c2e5a3f4

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Wed, 23 Nov 2022 00:14:43 GMT, release_branch:8.6, prefix:, end_time:Wed, 23 Nov 2022 04:52:03 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-3747fc18, build_duration_seconds:16640]
> [automation] update elastic stack version for testing 8.6.0-3747fc18

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 22 Nov 2022 12:14:37 GMT, release_branch:master, prefix:, end_time:Tue, 22 Nov 2022 15:47:57 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-c5c709bf, build_duration_seconds:12800]
> [automation] update elastic stack version for testing 8.7.0-c5c709bf

- docker-compose.yml
[start_time:Tue, 22 Nov 2022 12:15:35 GMT, release_branch:8.5, prefix:, end_time:Tue, 22 Nov 2022 16:54:26 GMT, manifest_version:2.1.0, version:8.5.2-SNAPSHOT, branch:8.5, build_id:8.5.2-98bdbc90, build_duration_seconds:16731]
> [automation] update elastic stack version for testing 8.5.2-98bdbc90

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Wed, 23 Nov 2022 12:14:56 GMT, release_branch:master, prefix:, end_time:Wed, 23 Nov 2022 16:05:51 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-11ac5926, build_duration_seconds:13855]
> [automation] update elastic stack version for testing 8.7.0-11ac5926

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 24 Nov 2022 00:14:39 GMT, release_branch:8.6, prefix:, end_time:Thu, 24 Nov 2022 04:27:29 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-742fd135, build_duration_seconds:15170]
> [automation] update elastic stack version for testing 8.6.0-742fd135

- docker-compose.yml
[start_time:Wed, 23 Nov 2022 12:16:16 GMT, release_branch:8.5, prefix:, end_time:Wed, 23 Nov 2022 16:51:33 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-760caed9, build_duration_seconds:16517]
> [automation] update elastic stack version for testing 8.5.3-760caed9

- go.mod
- go.sum
Remove the elastic-agent dependency, which we should not require. This is pulled in by elastic-agent-client/v7, which only requires it for some test program. Let's exclude it for now, and fix up elastic-agent-client.
N/A
https://github.com/elastic/elastic-agent-client/pull/48
> go.mod: exclude elastic-agent

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 24 Nov 2022 21:21:39 GMT, release_branch:8.6, prefix:, end_time:Fri, 25 Nov 2022 01:13:02 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-94ebec53, build_duration_seconds:13883]
> [automation] update elastic stack version for testing 8.6.0-94ebec53

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 24 Nov 2022 00:14:58 GMT, release_branch:master, prefix:, end_time:Thu, 24 Nov 2022 05:19:06 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-d050210c, build_duration_seconds:18248]
> [automation] update elastic stack version for testing 8.7.0-d050210c

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Sun, 27 Nov 2022 00:14:50 GMT, release_branch:8.6, prefix:, end_time:Sun, 27 Nov 2022 03:48:26 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-3e06249e, build_duration_seconds:12816]
> [automation] update elastic stack version for testing 8.6.0-3e06249e

- internal/beatcmd/reloader.go
- internal/beater/beater.go
If `fleet.hosts` isn't set in ESS, assume Fleet Server is co-located and use "https://localhost:8220". This is a workaround, and may alternatively be fixed by https://github.com/elastic/elastic-agent/pull/1802.
If the runner stops with an error, log the error immediately, rather than when reloading. Otherwise the error cannot be observed unless there is an input or output change.
1. Create a deployment in ESS
2. Check that the APM endpoint is accessible
3. Make sure source maps still …
> Fixes for Elastic Agent v2 changes

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 29 Nov 2022 00:14:54 GMT, release_branch:8.6, prefix:, end_time:Tue, 29 Nov 2022 03:42:55 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-c163a6d5, build_duration_seconds:12481]
> [automation] update elastic stack version for testing 8.6.0-c163a6d5

- testing/benchmark/Makefile
to report errors if pipes in the makefile, as there are hidden errors when running the `run-benchmark`
```
[2022-11-27T05:00:10.351Z] --- FAIL: BenchmarkOTLPTraces-512
[2022-11-27T05:00:10.351Z] 2022/11/27 05:00:10 benchmark "BenchmarkOTLPTraces-512" failed
[2022-11-27T05:00:10.351Z] make[1]: Leaving directory '/var/lib/jenkins/workspace/apm-server_benchmarks_main/src/github.com/elastic/apm-server/testing/benchmark'
```
It fails as expected now
While it was not failing in `main`:
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fbenchmarks/detail/main/163/pipeline
> apmbench: makefile with shellflags

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Wed, 30 Nov 2022 00:14:37 GMT, release_branch:8.6, prefix:, end_time:Wed, 30 Nov 2022 03:40:29 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-ecfefdaf, build_duration_seconds:12352]
> [automation] update elastic stack version for testing 8.6.0-ecfefdaf

- .github/workflows/macos.yml
Use the `setup-go` action with the `go-version-file` input so it reads the file `.go-version`
Avoid the logic to read and create env variables and use the undocumented `.go-version-file` 
See https://github.com/actions/setup-go/pull/295
> actions: use go-version-file: .go-version

- docker-compose.yml
[start_time:Thu, 1 Dec 2022 12:15:51 GMT, release_branch:8.5, prefix:, end_time:Thu, 1 Dec 2022 16:11:54 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-1625ae9f, build_duration_seconds:14163]
> [automation] update elastic stack version for testing 8.5.3-1625ae9f

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Fri, 2 Dec 2022 00:15:08 GMT, release_branch:master, prefix:, end_time:Fri, 2 Dec 2022 04:30:28 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-1b0dc867, build_duration_seconds:15320]
> [automation] update elastic stack version for testing 8.7.0-1b0dc867

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 1 Dec 2022 20:00:57 GMT, release_branch:8.6, prefix:, end_time:Fri, 2 Dec 2022 01:32:22 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-f96862e0, build_duration_seconds:19885]
> [automation] update elastic stack version for testing 8.6.0-f96862e0

- .ci/packaging.groovy
Package changes aren't being published on branches other than main; we may need to push fixes after feature freeze. We already have a check to filter out PRs.
Backport to 8.6, make sure changes to apmpackage result in a new package being published to EPR.
None
> .ci: don't only publish packages on main

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Sun, 4 Dec 2022 12:15:05 GMT, release_branch:master, prefix:, end_time:Sun, 4 Dec 2022 16:28:20 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-1fff43d4, build_duration_seconds:15195]
> [automation] update elastic stack version for testing 8.7.0-1fff43d4

- docker-compose.yml
[start_time:Mon, 5 Dec 2022 00:15:25 GMT, release_branch:8.5, prefix:, end_time:Mon, 5 Dec 2022 04:43:34 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-0a7c209d, build_duration_seconds:16089]
> [automation] update elastic stack version for testing 8.5.3-0a7c209d

- apmpackage/apm/data_stream/traces/fields/fields.yml
Add `unit: byte` to `http.response.decoded_body_size`. Found to be missing in https://github.com/elastic/apm-server/pull/9429#issuecomment-1337695145
Check the field mapping for unit in field metadata
None
> apmpackage: add unit for decoded_body_size

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Mon, 5 Dec 2022 12:14:24 GMT, release_branch:master, prefix:, end_time:Mon, 5 Dec 2022 16:03:39 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-7fe23b13, build_duration_seconds:13755]
> [automation] update elastic stack version for testing 8.7.0-7fe23b13

- docker-compose.yml
[start_time:Mon, 5 Dec 2022 12:15:33 GMT, release_branch:8.5, prefix:, end_time:Mon, 5 Dec 2022 16:55:18 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-55d94167, build_duration_seconds:16785]
> [automation] update elastic stack version for testing 8.5.3-55d94167

- internal/beater/beater.go
This is no longer needed, with https://github.com/elastic/elastic-agent/pull/1802, and it triggers a panic in ESS after upgrading from 7.x deployments.
1. Create a 7.17.x ESS deployment
2. Upgrade to 8.6
3. Make sure APM Server comes up and is accessible
None
> Revert workaround for missing `fleet.hosts`

- .ci/benchmarks.groovy
Increase timeouts for benchmarks. Corrects failures such as: 
https://apm-ci.elastic.co/job/apm-server/job/benchmarks/job/main/172/
I believe this problem may have been introduced here: https://github.com/elastic/apm-server/pull/8649
The benchmarks take around 98 minutes to run. However, the timeout was not adjusted to accommodate a retry which would push the runtime over 3 hours.
This increases the timeout to 4 hours which should provide enough allowable runtime to accommodate a single retry.
> Increase benchmark timeout to 4 hours

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 8 Dec 2022 00:14:56 GMT, release_branch:8.6, prefix:, end_time:Thu, 8 Dec 2022 04:09:41 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-7c9fd7a8, build_duration_seconds:14085]
> [automation] update elastic stack version for testing 8.6.0-7c9fd7a8

- docker-compose.yml
[start_time:Wed, 7 Dec 2022 12:16:19 GMT, release_branch:8.5, prefix:, end_time:Wed, 7 Dec 2022 16:51:43 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-ec242734, build_duration_seconds:16524]
> [automation] update elastic stack version for testing 8.5.3-ec242734

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 8 Dec 2022 00:17:45 GMT, release_branch:master, prefix:, end_time:Thu, 8 Dec 2022 04:32:18 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-188e6a3a, build_duration_seconds:15273]
> [automation] update elastic stack version for testing 8.7.0-188e6a3a

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Sun, 11 Dec 2022 00:17:33 GMT, release_branch:8.6, prefix:, end_time:Sun, 11 Dec 2022 05:26:16 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-febebae1, build_duration_seconds:18523]
> [automation] update elastic stack version for testing 8.6.0-febebae1

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 13 Dec 2022 00:15:13 GMT, release_branch:master, prefix:, end_time:Tue, 13 Dec 2022 03:51:41 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-08cd8ac3, build_duration_seconds:12988]
> [automation] update elastic stack version for testing 8.7.0-08cd8ac3

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 13 Dec 2022 00:15:02 GMT, release_branch:8.6, prefix:, end_time:Tue, 13 Dec 2022 04:17:34 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-6538107d, build_duration_seconds:14552]
> [automation] update elastic stack version for testing 8.6.0-6538107d

- docker-compose.yml
[start_time:Thu, 8 Dec 2022 00:15:29 GMT, release_branch:8.5, prefix:, end_time:Thu, 8 Dec 2022 05:18:52 GMT, manifest_version:2.1.0, version:8.5.3-SNAPSHOT, branch:8.5, build_id:8.5.3-91bdfab4, build_duration_seconds:18203]
> [automation] update elastic stack version for testing 8.5.3-91bdfab4

- apmpackage/apm/changelog.yml
- apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
- apmpackage/apm/data_stream/internal_metrics/manifest.yml
- changelogs/head.asciidoc
- internal/model/modeldecoder/v2/transaction_test.go
- internal/model/transaction.go
- systemtest/approvals/TestServiceMetricsAggregation.approved.json
- x-pack/apm-server/aggregation/servicemetrics/aggregator.go
- x-pack/apm-server/aggregation/servicemetrics/aggregator_test.go
For service metrics, use field `transaction.success_count` to store the transaction success and failure counts for easier avg aggregation on the field.
1. Ensure that service metrics `transaction.success_count` is populated correctly
2. Try an avg aggregation on `transaction.success_count`
Related to #5243
> Store outcome values in servicemetrics `transaction.success_count`

- internal/beater/java_attacher/java_attacher.go
- internal/beater/java_attacher/java_attacher_nonwindows_test.go
- internal/beater/java_attacher/java_attacher_windows_test.go
for https://github.com/elastic/apm-agent-java/issues/2878 (part of https://github.com/elastic/apm/issues/725)
When a Java application has the Java agent attached by the APM server, running the agent at DEBUG log_level should produce a line similar to
```
2022-12-13 14:30:56,147 [elastic-apm-remote-config-poller] DEBUG co.elastic.apm.agent.configuration.ActivationType - findType() returning FLEET
```
with the critical point being that `FLEET` is logged as the value returned
https://github.com/elastic/apm-agent-java/issues/2878
https://github.com/elastic/apm/issues/725
> add 'fleet' activation method to the Java attacher (for telemetry)

- .gitattributes
- internal/beatcmd/beat.go
- internal/beatcmd/beat_test.go
- internal/beatcmd/cmd.go
- internal/beatcmd/logging.go
- internal/beatcmd/logging_test.go
- internal/beatcmd/run.go
- Disable logging to files in beatcmd tests, since the log files are kept open by logp and thus the temp dir can't be removed. This requires replacing logp/configure with some custom code.
- Perform Windows Service event handling in the beatcmd cobra command code, rather than in Beat.Run. This is necessary since the service functions can only be called once per process, as they create and close a global channel.
- Ensure *.ndjson testdata files have LF (not CRLF) line endings on Windows.
~- [ ] Documentation has been …
> Fix tests on Windows

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 13 Dec 2022 12:15:20 GMT, release_branch:master, prefix:, end_time:Tue, 13 Dec 2022 15:44:47 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-04d5f080, build_duration_seconds:12567]
> [automation] update elastic stack version for testing 8.7.0-04d5f080

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Wed, 14 Dec 2022 00:16:09 GMT, release_branch:8.6, prefix:, end_time:Wed, 14 Dec 2022 04:17:14 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-6aa72183, build_duration_seconds:14465]
> [automation] update elastic stack version for testing 8.6.0-6aa72183

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 15 Dec 2022 00:16:06 GMT, release_branch:master, prefix:, end_time:Thu, 15 Dec 2022 04:09:50 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-4441fcfd, build_duration_seconds:14024]
> [automation] update elastic stack version for testing 8.7.0-4441fcfd

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 15 Dec 2022 00:15:00 GMT, release_branch:8.6, prefix:, end_time:Thu, 15 Dec 2022 03:29:53 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-919399a0, build_duration_seconds:11693]
> [automation] update elastic stack version for testing 8.6.0-919399a0

- .ci/Jenkinsfile
Skipping certain stages if only asciidoc files were changed did not work as expected. The reason is that environment variables defined in the `environment {}` block cannot be overridden. Therefore, `env.ONLY_DOCS` always stayed `"false"`.
Also see: https://github.com/elastic/apm-server/issues/9704#issuecomment-1352450206
- Is its use being published in **telemetry** to enable …
> ci: fix ONLY_DOCS condition

- packaging/docker/Dockerfile
Disable strict permission checks in Docker and make the config file world-readable and data directory world-writeable. This permits running the image with arbitrary UIDs and GIDs.
```bash
make package-docker
docker run --rm --user 123:456 $(cat build/docker/apm-server-ubi8-8.7.0.txt) /usr/share/apm-server/apm-server keystore create
```
https://github.com/elastic/cloud-on-k8s/issues/6227
> packaging: disable --strict.perms for Docker

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Fri, 16 Dec 2022 00:15:04 GMT, release_branch:master, prefix:, end_time:Fri, 16 Dec 2022 03:52:36 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-319a9bee, build_duration_seconds:13052]
> [automation] update elastic stack version for testing 8.7.0-319a9bee

- docker-compose.yml
[start_time:Thu, 15 Dec 2022 20:06:21 GMT, release_branch:7.17, prefix:, end_time:Fri, 16 Dec 2022 03:36:03 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-90a80afe, build_duration_seconds:26982]
> [automation] update elastic stack version for testing 7.17.9-90a80afe

- testing/smoke/lib.sh
Order of redirection matters, but this is a bit simpler.
> testing/smoke: fix stderr redirection

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Fri, 16 Dec 2022 00:17:39 GMT, release_branch:8.6, prefix:, end_time:Fri, 16 Dec 2022 06:05:25 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-d5c0a6be, build_duration_seconds:20866]
> [automation] update elastic stack version for testing 8.6.0-d5c0a6be

- Makefile
Make sure `docs/spec` is writable, so a subsequent `make docs/spec` doesn't fail.
N/A
None
> Makefile: make docs/spec writable

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Mon, 19 Dec 2022 22:55:35 GMT, release_branch:master, prefix:, end_time:Tue, 20 Dec 2022 03:27:00 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-bb19a9d1, build_duration_seconds:16285]
> [automation] update elastic stack version for testing 8.7.0-bb19a9d1

- Makefile
`make docs/spec` was failing in macos with the below error. The PR attempts to fix this (hopefully for all cases).
```
$ make docs/spec                                                                                                                                                [15:12:34]
rsync -v --delete --chmod=D755 --chmod=F644 -r $(/opt/homebrew/Cellar/go/1.19.3/libexec/bin/go list -m -f {{.Dir}} github.com/elastic/apm-data)/input/elasticapm/docs/spec ./docs
rsync: Invalid argument passed to --chmod (D755)
rsync error: syntax or usage error (code 1) at /AppleInternal/Library/BuildRoots/a0876c02-1788-11ed-b9c4-96898e02b808/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(1337) [client=2.6.9]
make: *** [docs/spec] Error 1
```
~~- [ ] Update …
> Fix rsync command to not fail on macos

- docker-compose.yml
[start_time:Mon, 19 Dec 2022 16:18:03 GMT, release_branch:8.5, prefix:, end_time:Mon, 19 Dec 2022 20:31:22 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-9a613070, build_duration_seconds:15199]
> [automation] update elastic stack version for testing 8.5.4-9a613070

- docker-compose.yml
[start_time:Mon, 19 Dec 2022 23:58:34 GMT, release_branch:7.17, prefix:, end_time:Tue, 20 Dec 2022 04:47:43 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-8dd51aad, build_duration_seconds:17349]
> [automation] update elastic stack version for testing 7.17.9-8dd51aad

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Mon, 19 Dec 2022 12:59:34 GMT, release_branch:8.6, prefix:, end_time:Mon, 19 Dec 2022 22:12:32 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-a85d8f17, build_duration_seconds:33178]
> [automation] update elastic stack version for testing 8.6.0-a85d8f17

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 20 Dec 2022 12:18:01 GMT, release_branch:master, prefix:, end_time:Tue, 20 Dec 2022 19:53:27 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-19f30181, build_duration_seconds:27326]
> [automation] update elastic stack version for testing 8.7.0-19f30181

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Wed, 21 Dec 2022 00:17:09 GMT, release_branch:8.6, prefix:, end_time:Wed, 21 Dec 2022 04:18:42 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-734df845, build_duration_seconds:14493]
> [automation] update elastic stack version for testing 8.6.0-734df845

- docker-compose.yml
[start_time:Tue, 20 Dec 2022 05:16:47 GMT, release_branch:7.17, prefix:, end_time:Tue, 20 Dec 2022 09:46:47 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-ab98c430, build_duration_seconds:16200]
> [automation] update elastic stack version for testing 7.17.9-ab98c430

- .ci/benchmarks.groovy
Allow PR builds to run even if another build ID failed and left dangling resources.
> ci: Include branch in benchmark prefix

- docker-compose.yml
[start_time:Thu, 22 Dec 2022 00:16:50 GMT, release_branch:8.5, prefix:, end_time:Thu, 22 Dec 2022 04:16:35 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-880022a5, build_duration_seconds:14385]
> [automation] update elastic stack version for testing 8.5.4-880022a5

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 22 Dec 2022 01:27:43 GMT, release_branch:8.6, prefix:, end_time:Thu, 22 Dec 2022 04:36:36 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-55d181cf, build_duration_seconds:11333]
> [automation] update elastic stack version for testing 8.6.0-55d181cf

- docker-compose.yml
[start_time:Wed, 21 Dec 2022 05:17:15 GMT, release_branch:7.17, prefix:, end_time:Wed, 21 Dec 2022 10:12:17 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-dea3eaf3, build_duration_seconds:17702]
> [automation] update elastic stack version for testing 7.17.9-dea3eaf3

- systemtest/benchtest/main.go
the benchmark function can panic or call runtime.Goexit under the hood (FailNow/SkipNow) stopping the goroutine. That will cause the benhmark executor to report the benchmark as a failure which is a big if the test was skipped.
Closes https://github.com/elastic/apm-server/issues/9844
> test: fix BenchmarkOTLPTraces consistently failing

- docker-compose.yml
[start_time:Thu, 22 Dec 2022 12:15:47 GMT, release_branch:8.5, prefix:, end_time:Thu, 22 Dec 2022 16:21:04 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-9612e66a, build_duration_seconds:14717]
> [automation] update elastic stack version for testing 8.5.4-9612e66a

- docker-compose.yml
[start_time:Thu, 22 Dec 2022 05:16:35 GMT, release_branch:7.17, prefix:, end_time:Thu, 22 Dec 2022 10:06:58 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-89f6cb7d, build_duration_seconds:17423]
> [automation] update elastic stack version for testing 7.17.9-89f6cb7d

- internal/beater/config/aggregation.go
- internal/beater/config/config_test.go
- systemtest/approvals/TestServiceMetricsAggregation.approved.json
- x-pack/apm-server/aggregation/servicemetrics/aggregator.go
- x-pack/apm-server/aggregation/servicemetrics/aggregator_test.go
- x-pack/apm-server/main.go
Add histograms to service metrics.
Add histogram significant digit setting. (default 5)
Update tests.
Closes https://github.com/elastic/apm-server/issues/9656
> feat: add histogram support to service metrics

- internal/beater/beater.go
I couldn't find any issue in the cgroup reading logic that would explain the bug in https://github.com/elastic/apm-server/pull/9868
On the other hand, it looks like `9223372036854771712` is the default value for cgroup v1 for unlimited memory (no limit).
I was able to reproduce the content of the limit_in_bytes file by creating a fedora 30 instance in aws and running a docker container inside of it. Then reading the memory limit inside the container:
```
9223372036854771712
```
Note: fedora 30 is important as later versions are using cgroup v2
The PR is adding a fall back to system memory if cgroup returns a value that exceeds the total memory.
- Is its use being published in …
> fix: fall back to system memory if cgroup exceeds the available memory

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Sun, 25 Dec 2022 12:18:04 GMT, release_branch:master, prefix:, end_time:Sun, 25 Dec 2022 15:22:59 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-0f74a2e9, build_duration_seconds:11095]
> [automation] update elastic stack version for testing 8.7.0-0f74a2e9

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Mon, 26 Dec 2022 00:17:39 GMT, release_branch:8.6, prefix:, end_time:Mon, 26 Dec 2022 04:28:15 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-f6d7d537, build_duration_seconds:15036]
> [automation] update elastic stack version for testing 8.6.0-f6d7d537

- docker-compose.yml
[start_time:Mon, 26 Dec 2022 00:15:42 GMT, release_branch:8.5, prefix:, end_time:Mon, 26 Dec 2022 04:59:16 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-09ced402, build_duration_seconds:17014]
> [automation] update elastic stack version for testing 8.5.4-09ced402

- docker-compose.yml
[start_time:Sun, 25 Dec 2022 05:17:01 GMT, release_branch:7.17, prefix:, end_time:Sun, 25 Dec 2022 10:11:23 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-917139ef, build_duration_seconds:17662]
> [automation] update elastic stack version for testing 7.17.9-917139ef

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 27 Dec 2022 00:17:52 GMT, release_branch:8.6, prefix:, end_time:Tue, 27 Dec 2022 03:33:58 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-a026c2fe, build_duration_seconds:11766]
> [automation] update elastic stack version for testing 8.6.0-a026c2fe

- docker-compose.yml
[start_time:Tue, 27 Dec 2022 00:16:05 GMT, release_branch:8.5, prefix:, end_time:Tue, 27 Dec 2022 04:42:49 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-53cae6e0, build_duration_seconds:16004]
> [automation] update elastic stack version for testing 8.5.4-53cae6e0

- docker-compose.yml
[start_time:Mon, 26 Dec 2022 05:17:03 GMT, release_branch:7.17, prefix:, end_time:Mon, 26 Dec 2022 10:12:29 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-0c41c515, build_duration_seconds:17726]
> [automation] update elastic stack version for testing 7.17.9-0c41c515

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 27 Dec 2022 12:17:19 GMT, release_branch:master, prefix:, end_time:Tue, 27 Dec 2022 15:53:15 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-b3da67ae, build_duration_seconds:12956]
> [automation] update elastic stack version for testing 8.7.0-b3da67ae

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Wed, 28 Dec 2022 00:17:28 GMT, release_branch:8.6, prefix:, end_time:Wed, 28 Dec 2022 04:40:37 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-7e55dcb1, build_duration_seconds:15789]
> [automation] update elastic stack version for testing 8.6.0-7e55dcb1

- docker-compose.yml
[start_time:Tue, 27 Dec 2022 12:20:45 GMT, release_branch:8.5, prefix:, end_time:Tue, 27 Dec 2022 16:20:38 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-b44284e8, build_duration_seconds:14393]
> [automation] update elastic stack version for testing 8.5.4-b44284e8

- docker-compose.yml
[start_time:Tue, 27 Dec 2022 05:16:51 GMT, release_branch:7.17, prefix:, end_time:Tue, 27 Dec 2022 09:54:24 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-590749d6, build_duration_seconds:16653]
> [automation] update elastic stack version for testing 7.17.9-590749d6

- apmpackage/apm/changelog.yml
- apmpackage/cmd/genpackage/pipelines.go
- systemtest/approvals/TestOTLPGRPCTraces.approved.json
- systemtest/otlp_test.go
The otel span start/end dates are used to compute the event
duration of the APM event, stored as a time.Duration.
The duration is converted to nanoseconds stored in an int64
field, however the values is casted to int in the event_duration
pipeline leading to an overflow if the original 64 bit value
cannot be casted safely to the 32-bit int.
Closes https://github.com/elastic/apm-server/issues/9780
> fix: cast event.duration to long in event_duration pipeline 

- x-pack/apm-server/sampling/processor_test.go
the batch slice can get really big. In this case allocation is costly both in terms of cpu and memory.
Allocate the slice with an explicit size and capacity to improve performance.
The test time decreases significantly but posting numbers is difficult because the test depends on the number of CPUs on the host machine.
On my machine `go test -run=TestStorageLimit ./x-pack/apm-server/sampling/processor_test.go` went from 9.5s to 2.5s
> test: preallocate batch slice in TestStorageLimit

- docs/legacy/configuration-process.asciidoc
- docs/upgrading-to-datastreams.asciidoc
> The idea is to:
> 
> Add a warning in the config option and link to the actual migration guide.
> Update the Data Streams considerations section to also contain a link to the upgrade guide.
* Closes https://github.com/elastic/apm-server/issues/9278.
> [7.17] Better links to ESS data stream migration guide

- docs/ilm-how-to.asciidoc
> https://www.elastic.co/guide/en/apm/guide/7.17/ilm-how-to.html indicates that data streams created by 7.17 have a delete phase. This is not true - we added the delete phase in 8.0: https://github.com/elastic/apm-server/pull/6480
>
> We have no intention to change the ILM policy in 7.17, so we should update the docs.
* Closes https://github.com/elastic/apm-server/issues/9741.
> [7.17] docs: remove ILM delete phase

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 29 Dec 2022 00:17:11 GMT, release_branch:8.6, prefix:, end_time:Thu, 29 Dec 2022 04:01:07 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-08909b84, build_duration_seconds:13436]
> [automation] update elastic stack version for testing 8.6.0-08909b84

- docker-compose.yml
[start_time:Thu, 29 Dec 2022 00:16:26 GMT, release_branch:8.5, prefix:, end_time:Thu, 29 Dec 2022 04:51:03 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-63dd32c9, build_duration_seconds:16477]
> [automation] update elastic stack version for testing 8.5.4-63dd32c9

- docker-compose.yml
[start_time:Wed, 28 Dec 2022 05:16:23 GMT, release_branch:7.17, prefix:, end_time:Wed, 28 Dec 2022 09:45:25 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-fb6ed84b, build_duration_seconds:16142]
> [automation] update elastic stack version for testing 7.17.9-fb6ed84b

- cmd/intake-receiver/main.go
According to the doc: It is the caller's responsibility to call Close on the ReadCloser when done.
> fix: close zlib/gzip reader after use in intake-receiver

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Fri, 30 Dec 2022 00:22:46 GMT, release_branch:master, prefix:, end_time:Fri, 30 Dec 2022 04:16:19 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-d6e7f5ec, build_duration_seconds:14013]
> [automation] update elastic stack version for testing 8.7.0-d6e7f5ec

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Fri, 30 Dec 2022 00:18:05 GMT, release_branch:8.6, prefix:, end_time:Fri, 30 Dec 2022 03:48:37 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-2d1af9b1, build_duration_seconds:12632]
> [automation] update elastic stack version for testing 8.6.0-2d1af9b1

- docker-compose.yml
[start_time:Thu, 29 Dec 2022 05:16:31 GMT, release_branch:7.17, prefix:, end_time:Thu, 29 Dec 2022 10:06:25 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-9b93f6c8, build_duration_seconds:17394]
> [automation] update elastic stack version for testing 7.17.9-9b93f6c8

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Sun, 1 Jan 2023 00:16:32 GMT, release_branch:master, prefix:, end_time:Sun, 1 Jan 2023 03:24:44 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-2320c424, build_duration_seconds:11292]
> [automation] update elastic stack version for testing 8.7.0-2320c424

- docker-compose.yml
[start_time:Sun, 1 Jan 2023 05:17:56 GMT, release_branch:7.17, prefix:, end_time:Sun, 1 Jan 2023 10:07:48 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-b6edf494, build_duration_seconds:17392]
> [automation] update elastic stack version for testing 7.17.9-b6edf494

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Mon, 2 Jan 2023 00:17:16 GMT, release_branch:8.6, prefix:, end_time:Mon, 2 Jan 2023 04:05:16 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-4e169a4a, build_duration_seconds:13680]
> [automation] update elastic stack version for testing 8.6.0-4e169a4a

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 3 Jan 2023 00:17:48 GMT, release_branch:8.6, prefix:, end_time:Tue, 3 Jan 2023 03:58:10 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-39d183e3, build_duration_seconds:13222]
> [automation] update elastic stack version for testing 8.6.0-39d183e3

- docker-compose.yml
[start_time:Mon, 2 Jan 2023 12:15:39 GMT, release_branch:8.5, prefix:, end_time:Mon, 2 Jan 2023 16:07:08 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-d318ceb8, build_duration_seconds:13889]
> [automation] update elastic stack version for testing 8.5.4-d318ceb8

- docker-compose.yml
[start_time:Mon, 2 Jan 2023 05:17:10 GMT, release_branch:7.17, prefix:, end_time:Mon, 2 Jan 2023 10:13:23 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-2f2234f0, build_duration_seconds:17773]
> [automation] update elastic stack version for testing 7.17.9-2f2234f0

- docker-compose.yml
[start_time:Wed, 4 Jan 2023 00:15:42 GMT, release_branch:8.5, prefix:, end_time:Wed, 4 Jan 2023 04:40:16 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-24b41202, build_duration_seconds:15874]
> [automation] update elastic stack version for testing 8.5.4-24b41202

- docker-compose.yml
[start_time:Tue, 3 Jan 2023 05:16:32 GMT, release_branch:7.17, prefix:, end_time:Tue, 3 Jan 2023 10:05:41 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-a047e337, build_duration_seconds:17349]
> [automation] update elastic stack version for testing 7.17.9-a047e337

- x-pack/apm-server/profiling/collector.go
- x-pack/apm-server/profiling/collecttraces.go
- x-pack/apm-server/profiling/common/constants.go
- x-pack/apm-server/profiling/common/encode.go
- x-pack/apm-server/profiling/common/rle.go
- x-pack/apm-server/profiling/common/rle_test.go
- x-pack/apm-server/profiling/common/timestamp.go
- x-pack/apm-server/profiling/ilm.go
- x-pack/apm-server/profiling/libpf/libpf.go
This PR synchronizes (for the most part) `pf-elastic-collector` and the collector code in `apm-server` and should make further development and porting code between the two repositories easier.
- Moved `constants.go`, `encode.go`, `rle.go`, `rle_test.go` and `timestamp.go` into `common` package
- Moved `libpf` logic into `libpf` package
**Note:** This PR includes the #9828 commit, I will rebase on top of main once #9828 is merged.
> Universal Profiling: Refactor code into 'common' and 'libpf' packages

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 5 Jan 2023 00:17:41 GMT, release_branch:8.6, prefix:, end_time:Thu, 5 Jan 2023 04:34:28 GMT, manifest_version:2.1.0, version:8.6.0-SNAPSHOT, branch:8.6, build_id:8.6.0-91e609be, build_duration_seconds:15407]
> [automation] update elastic stack version for testing 8.6.0-91e609be

- docker-compose.yml
[start_time:Wed, 4 Jan 2023 12:15:42 GMT, release_branch:8.5, prefix:, end_time:Wed, 4 Jan 2023 16:22:00 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-1b0ccb68, build_duration_seconds:14778]
> [automation] update elastic stack version for testing 8.5.4-1b0ccb68

- docker-compose.yml
[start_time:Wed, 4 Jan 2023 05:16:46 GMT, release_branch:7.17, prefix:, end_time:Wed, 4 Jan 2023 09:53:03 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-8459499d, build_duration_seconds:16577]
> [automation] update elastic stack version for testing 7.17.9-8459499d

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 5 Jan 2023 12:17:19 GMT, release_branch:master, prefix:, end_time:Thu, 5 Jan 2023 23:02:49 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-129a645f, build_duration_seconds:38730]
> [automation] update elastic stack version for testing 8.7.0-129a645f

- .ci/Jenkinsfile
- .ci/benchmarks.groovy
- .ci/packaging.groovy
Use secrets in the `observability` namespace instead of the `apm` namespace.
> fix: use observability namespace secrets

- docker-compose.yml
[start_time:Sun, 8 Jan 2023 00:16:10 GMT, release_branch:8.5, prefix:, end_time:Sun, 8 Jan 2023 05:08:58 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-fb007f04, build_duration_seconds:17568]
> [automation] update elastic stack version for testing 8.5.4-fb007f04

- docker-compose.yml
[start_time:Sat, 7 Jan 2023 05:18:01 GMT, release_branch:7.17, prefix:, end_time:Sat, 7 Jan 2023 10:07:38 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-de96bcaf, build_duration_seconds:17377]
> [automation] update elastic stack version for testing 7.17.9-de96bcaf

- .github/workflows/ci-docs.yml
- .github/workflows/ci.yml
Follows GitHub's guidance on how to create a step with the same name as the required action so that a status check may be set as required in a protected branch.
see: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
> ci: Allow system-tests check to be set as required

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Mon, 9 Jan 2023 12:17:52 GMT, release_branch:master, prefix:, end_time:Mon, 9 Jan 2023 15:56:00 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-61c35791, build_duration_seconds:13088]
> [automation] update elastic stack version for testing 8.7.0-61c35791

- changelogs/head.asciidoc
- internal/beater/server.go
There is a possible panic related to gmux. It is due to the order we shutdown httpServer and grpcServer. Occasionally when a new grpc connection comes in after grpcServer shutdown and before httpServer shutdown, the program panics.
See https://github.com/elastic/gmux/issues/13
> Fix a panic caused by accepting new grpc connections during shutdown

- docker-compose.yml
[start_time:Wed, 11 Jan 2023 00:17:01 GMT, release_branch:8.5, prefix:, end_time:Wed, 11 Jan 2023 04:27:47 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-6280647c, build_duration_seconds:15046]
> [automation] update elastic stack version for testing 8.5.4-6280647c

- docker-compose.yml
[start_time:Tue, 10 Jan 2023 05:17:03 GMT, release_branch:7.17, prefix:, end_time:Tue, 10 Jan 2023 19:20:22 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-432b7acb, build_duration_seconds:50599]
> [automation] update elastic stack version for testing 7.17.9-432b7acb

- docker-compose.yml
[start_time:Wed, 11 Jan 2023 12:15:40 GMT, release_branch:8.5, prefix:, end_time:Wed, 11 Jan 2023 16:29:53 GMT, manifest_version:2.1.0, version:8.5.4-SNAPSHOT, branch:8.5, build_id:8.5.4-1969ac34, build_duration_seconds:15253]
> [automation] update elastic stack version for testing 8.5.4-1969ac34

- docker-compose.yml
[start_time:Wed, 11 Jan 2023 05:16:43 GMT, release_branch:7.17, prefix:, end_time:Wed, 11 Jan 2023 10:06:02 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-dae00897, build_duration_seconds:17359]
> [automation] update elastic stack version for testing 7.17.9-dae00897

- x-pack/apm-server/main.go
Fix typo in xpack main about servicemetrics aggregator name
N/A
> Fix servicemetrics aggregator name typo

- apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
- apmpackage/apm/data_stream/service_destination_interval_metrics/elasticsearch/ingest_pipeline/default.yml
- apmpackage/apm/data_stream/service_interval_metrics/elasticsearch/ingest_pipeline/default.yml
- apmpackage/apm/data_stream/service_interval_metrics/fields/fields.yml
- apmpackage/apm/data_stream/transaction_interval_metrics/elasticsearch/ingest_pipeline/default.yml
- apmpackage/apm/data_stream/transaction_interval_metrics/fields/fields.yml
Between conflicting PRs where the datastream for aggregation metrics was changed from `metrics-internal` to `metrics-apm.{transaction, service, service_destination}-*` it seems that the changes for aggregation overflow buckets were not ported correctly. This PR moves the required fields to the correct package definitions and also fixes the ingest pipelines to remove `_metric_descriptions`.
NA
#9703 and #9648
> Fix fields def and ingest pipelines for agg templates

- NOTICE.txt
- go.mod
- go.sum
Contains memory and CPU consumption improvements and is used by Universal Profiling.
As previously discussed in #9684. I built and tested the profiling code with both apm-server current and apm-server v8.6.0.
> Update go-elasticsearch to v8.6.0 (#9684)

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Mon, 16 Jan 2023 00:17:31 GMT, release_branch:8.6, prefix:, end_time:Mon, 16 Jan 2023 04:30:38 GMT, manifest_version:2.1.0, version:8.6.1-SNAPSHOT, branch:8.6, build_id:8.6.1-436ca0d1, build_duration_seconds:15187]
> [automation] update elastic stack version for testing 8.6.1-436ca0d1

- docker-compose.yml
[start_time:Sun, 15 Jan 2023 05:16:22 GMT, release_branch:7.17, prefix:, end_time:Sun, 15 Jan 2023 09:46:44 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-55a2d7ab, build_duration_seconds:16222]
> [automation] update elastic stack version for testing 7.17.9-55a2d7ab

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 17 Jan 2023 00:18:02 GMT, release_branch:8.6, prefix:, end_time:Tue, 17 Jan 2023 04:19:06 GMT, manifest_version:2.1.0, version:8.6.1-SNAPSHOT, branch:8.6, build_id:8.6.1-cc0796ca, build_duration_seconds:14464]
> [automation] update elastic stack version for testing 8.6.1-cc0796ca

- docker-compose.yml
[start_time:Mon, 16 Jan 2023 05:17:05 GMT, release_branch:7.17, prefix:, end_time:Mon, 16 Jan 2023 10:10:10 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-0ee22981, build_duration_seconds:17585]
> [automation] update elastic stack version for testing 7.17.9-0ee22981

- .github/workflows/ci-docs.yml
- .github/workflows/opentelemetry.yml
Back in the days we built the Jenkins OTEL integration, so let's use the same approach for the GH actions, so every workflow and step will be tracked as traces/spans.
See traces in the Elastic deployment
This has been already tested for quite sometime in some other projects
https://github.com/elastic/apm-pipeline-library/blob/main/.github/workflows/opentelemetry.yml
> action: export traces with the OTEL GH action

- systemtest/profiling_test.go
- x-pack/apm-server/profiling/collector.go
If this import does not exist, the backend will drop compressed RPCs as `Unimplemented`.
Was previously removed in:
https://github.com/elastic/apm-server/commit/06b1a97767942ce52e65cd07a80980679c1198ba
```
internal/otel_collector/config/configgrpc/gzip.go:19:	_ "google.golang.org/grpc/encoding/gzip"
internal/otel_collector/config/configgrpc/configgrpc.go:34:	"google.golang.org/grpc/encoding/gzip"
```
**TODO:**
- ~Looking into updating tests~ DONE
> Universal Profiling: Fix for GRPC compression not being enabled

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 17 Jan 2023 12:17:31 GMT, release_branch:master, prefix:, end_time:Tue, 17 Jan 2023 16:00:19 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-88fbfe89, build_duration_seconds:13368]
> [automation] update elastic stack version for testing 8.7.0-88fbfe89

- docker-compose.yml
[start_time:Tue, 17 Jan 2023 05:16:58 GMT, release_branch:7.17, prefix:, end_time:Tue, 17 Jan 2023 10:05:39 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-a4381da5, build_duration_seconds:17321]
> [automation] update elastic stack version for testing 7.17.9-a4381da5

- docker-compose.yml
[start_time:Wed, 18 Jan 2023 05:17:17 GMT, release_branch:7.17, prefix:, end_time:Wed, 18 Jan 2023 10:04:14 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-62814092, build_duration_seconds:17217]
> [automation] update elastic stack version for testing 7.17.9-62814092

- docs/legacy/configuration-anonymous.asciidoc
Anonymous settings are considered only if at least one authentication method is enabled
Users might be misled into thinking that `apm-server.auth.anonymous.allow_...` setting is also taken into account.
Without any authentication method (https://www.elastic.co/guide/en/apm/guide/current/secure-communication-agents.html), the `apm-server.auth.anonymous.allow_...` are ignored.
> [DOCS] Specific callout to anonymous settings & auth in APM Server legacy

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 19 Jan 2023 16:21:18 GMT, release_branch:master, prefix:, end_time:Thu, 19 Jan 2023 19:56:51 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-304110fc, build_duration_seconds:12933]
> [automation] update elastic stack version for testing 8.7.0-304110fc

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Sun, 22 Jan 2023 12:17:28 GMT, release_branch:master, prefix:, end_time:Sun, 22 Jan 2023 15:45:22 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-909f3a86, build_duration_seconds:12474]
> [automation] update elastic stack version for testing 8.7.0-909f3a86

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Sun, 22 Jan 2023 00:17:11 GMT, release_branch:8.6, prefix:, end_time:Sun, 22 Jan 2023 05:03:17 GMT, manifest_version:2.1.0, version:8.6.1-SNAPSHOT, branch:8.6, build_id:8.6.1-8f6887b9, build_duration_seconds:17166]
> [automation] update elastic stack version for testing 8.6.1-8f6887b9

- internal/beater/memlimit_cgroup.go
Closes https://github.com/elastic/apm-server/issues/10097
> fix: make sure the memory subsystem is available before accessing the memory limit

- systemtest/aggregation_test.go
- systemtest/apmservertest/config.go
As the config option is removed, remove relevant systemtest config.
Part of #10048
> Remove service aggregation config in systemtest

- changelogs/8.6.asciidoc
Adds 8.6.1 release notes. No significant changes: https://github.com/elastic/apm-server/commits/74050838488eedf105c0bc794dfb72ec5f81d548
> docs: add 8.6.1 release notes

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 24 Jan 2023 12:18:15 GMT, release_branch:master, prefix:, end_time:Tue, 24 Jan 2023 16:03:09 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-ba9bcc38, build_duration_seconds:13494]
> [automation] update elastic stack version for testing 8.7.0-ba9bcc38

- docs/data-streams.asciidoc
Following #10095, fix an overlooked entry that should be renamed.
> Rename service metrics to service transaction metrics

- systemtest/instrumentation_test.go
Add meaningful assertion message to TestAPMServerInstrumentation so that we can understand the reason the next time it fails on GH actions
> Add meaningful assertion message to TestAPMServerInstrumentation

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Sat, 28 Jan 2023 00:18:13 GMT, release_branch:8.6, prefix:, end_time:Sat, 28 Jan 2023 03:39:29 GMT, manifest_version:2.1.0, version:8.6.2-SNAPSHOT, branch:8.6, build_id:8.6.2-a887b34c, build_duration_seconds:12076]
> [automation] update elastic stack version for testing 8.6.2-a887b34c

- systemtest/apmservertest/config.go
- systemtest/profiling_test.go
Reduce fleet dependency in test and improve test time.
TestProfiling time went from 32s to 10s
> test: move TestProfiling to standalone APM Server

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Sun, 29 Jan 2023 00:17:39 GMT, release_branch:master, prefix:, end_time:Sun, 29 Jan 2023 04:38:33 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-975fd02f, build_duration_seconds:15654]
> [automation] update elastic stack version for testing 8.7.0-975fd02f

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Mon, 30 Jan 2023 12:17:57 GMT, release_branch:master, prefix:, end_time:Mon, 30 Jan 2023 15:52:05 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-4687ed94, build_duration_seconds:12848]
> [automation] update elastic stack version for testing 8.7.0-4687ed94

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Mon, 30 Jan 2023 00:18:06 GMT, release_branch:8.6, prefix:, end_time:Mon, 30 Jan 2023 17:25:42 GMT, manifest_version:2.1.0, version:8.6.2-SNAPSHOT, branch:8.6, build_id:8.6.2-6e25dbb4, build_duration_seconds:61656]
> [automation] update elastic stack version for testing 8.6.2-6e25dbb4

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Wed, 1 Feb 2023 00:18:07 GMT, release_branch:master, prefix:, end_time:Wed, 1 Feb 2023 04:06:50 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-87b130b2, build_duration_seconds:13723]
> [automation] update elastic stack version for testing 8.7.0-87b130b2

- docker-compose.yml
[start_time:Wed, 1 Feb 2023 05:18:05 GMT, release_branch:7.17, prefix:, end_time:Wed, 1 Feb 2023 10:41:37 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-663e90b2, build_duration_seconds:19412]
> [automation] update elastic stack version for testing 7.17.9-663e90b2

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Fri, 3 Feb 2023 00:18:00 GMT, release_branch:master, prefix:, end_time:Fri, 3 Feb 2023 03:16:52 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-a8bf765b, build_duration_seconds:10732]
> [automation] update elastic stack version for testing 8.7.0-a8bf765b

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Thu, 2 Feb 2023 12:17:48 GMT, release_branch:8.6, prefix:, end_time:Thu, 2 Feb 2023 18:02:14 GMT, manifest_version:2.1.0, version:8.6.2-SNAPSHOT, branch:8.6, build_id:8.6.2-b5f10a44, build_duration_seconds:20666]
> [automation] update elastic stack version for testing 8.6.2-b5f10a44

- docker-compose.yml
[start_time:Thu, 2 Feb 2023 05:16:54 GMT, release_branch:7.17, prefix:, end_time:Thu, 2 Feb 2023 10:36:17 GMT, manifest_version:2.1.0, version:7.17.9-SNAPSHOT, branch:7.17, build_id:7.17.9-f3ee8926, build_duration_seconds:19163]
> [automation] update elastic stack version for testing 7.17.9-f3ee8926

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Mon, 6 Feb 2023 00:17:45 GMT, release_branch:master, prefix:, end_time:Mon, 6 Feb 2023 04:40:24 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-1ef3b708, build_duration_seconds:15759]
> [automation] update elastic stack version for testing 8.7.0-1ef3b708

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Mon, 6 Feb 2023 00:17:21 GMT, release_branch:8.6, prefix:, end_time:Mon, 6 Feb 2023 03:24:16 GMT, manifest_version:2.1.0, version:8.6.2-SNAPSHOT, branch:8.6, build_id:8.6.2-9fa37b7d, build_duration_seconds:11215]
> [automation] update elastic stack version for testing 8.6.2-9fa37b7d

- changelogs/head.asciidoc
- x-pack/apm-server/aggregation/servicetxmetrics/aggregator.go
- x-pack/apm-server/aggregation/servicetxmetrics/aggregator_test.go
Fix a bug where `event.success_count.sum` is not rounded, causing >100% success rate.
- Ensure event.success_count.sum is rounded under sampling setup.
> Round servicetxmetrics event.success_count.sum

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 7 Feb 2023 00:18:11 GMT, release_branch:master, prefix:, end_time:Tue, 7 Feb 2023 04:27:22 GMT, manifest_version:2.1.0, version:8.7.0-SNAPSHOT, branch:master, build_id:8.7.0-dd1a1621, build_duration_seconds:14951]
> [automation] update elastic stack version for testing 8.7.0-dd1a1621

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Tue, 7 Feb 2023 00:17:50 GMT, release_branch:8.6, prefix:, end_time:Tue, 7 Feb 2023 03:38:05 GMT, manifest_version:2.1.0, version:8.6.2-SNAPSHOT, branch:8.6, build_id:8.6.2-74b1938c, build_duration_seconds:12015]
> [automation] update elastic stack version for testing 8.6.2-74b1938c

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/fleet-server.yaml
- testing/infra/k8s/base/stack/kibana.yaml
- testing/infra/k8s/overlays/local/kustomization.yaml
[start_time:Wed, 8 Feb 2023 00:17:50 GMT, release_branch:8.6, prefix:, end_time:Wed, 8 Feb 2023 03:25:29 GMT, manifest_version:2.1.0, version:8.6.2-SNAPSHOT, branch:8.6, build_id:8.6.2-7c4539d9, build_duration_seconds:11259]
> [automation] update elastic stack version for testing 8.6.2-7c4539d9

- systemtest/approvals/TestProfiling/stackframes.approved.json
- x-pack/apm-server/profiling/collector.go
This PR synchronizes with the changes in the profiling mapping for the frame metadata.
We dropped the field `SourceType`. Here we avoid writing into this field.
[Remove unused field from the profiling-stackframes index](https://github.com/elastic/prodfiler/issues/2944)
> profiling: do not store obsolete SourceType in frame metadata

- CHANGELOG.asciidoc
Fixes a failing 8.7 doc build.
> [8.7] docs: remove head.asciidoc

- .github/workflows/bump-elastic-stack.yml
Release branches might have a different set of files to be updated. Hence it's required to checkout the given branch to run the `updatecli`
https://github.com/elastic/apm-server/pull/10222
> action: avoid fail fast and checkout branch

- .github/workflows/bump-elastic-stack.yml
Use GitHub composite action
Reuse code and solve the existing issue with Workflows won't be enabled for PRs created on behalf of `GitHub actions [bot]`, see https://github.com/elastic/ecs-logging-java/pull/200
Similar to https://github.com/elastic/ecs-logging-java/pull/201
Requires https://github.com/elastic/apm-pipeline-library/pull/2076
> action: use composite updatecli

- systemtest/aggregation_test.go
- systemtest/apmservertest/server.go
- systemtest/apmservertest/server_test.go
- systemtest/huge_traces_test.go
- systemtest/jaeger_test.go
- systemtest/logging_test.go
Trying to run system tests if there is a compile error will result in the error being printed to stderr followed by a nil pointer dereference:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4b50f9]
goroutine 98 [running]:
os.(*Process).signal(0xc0004aab60?, {0x15a7998?, 0x1f0e850?})
/usr/lib/go/src/os/exec_unix.go:63 +0x39
os.(*Process).Signal(...)
/usr/lib/go/src/os/exec.go:138
github.com/elastic/apm-server/systemtest/apmservertest.interruptProcess(...)
/apm-server/systemtest/apmservertest/server_unix.go:31
github.com/elastic/apm-server/systemtest/apmservertest.(*Server).Close(0xc0004aab60)
/apm-server/systemtest/apmservertest/server.go:434 +0x5a …
```
> test: fix system test panic on compile error and avoid double close

- .github/workflows/update-beats.yml
Stop spamming Slack with `update-beats` messages on every commit.
N/A
None
> CI: only notify Slack of update-beats on failure

- systemtest/logging_test.go
More goroutine leaks in logging tests:
```
Goroutine 100 in state select, with go.elastic.co/apm/v2.(*Tracer).loop on top of the stack:
goroutine 100 [select]:
go.elastic.co/apm/v2.(*Tracer).loop(0xc000392820)
/go/pkg/mod/go.elastic.co/apm/v2@v2.1.1-0.20220810211444-b8542dccafec/tracer.go:1019 +0xd1f
created by go.elastic.co/apm/v2.newTracer
/go/pkg/mod/go.elastic.co/apm/v2@v2.1.1-0.20220810211444-b8542dccafec/tracer.go:540 +0xd6a
[originating from goroutine 46]:
go.elastic.co/apm/v2.newTracer(...)
/go/pkg/mod/go.elastic.co/apm/v2@v2.1.1-0.20220810211444-b8542dccafec/tracer.go:541 +0xd6a
go.elastic.co/apm/v2.NewTracerOptions(...)
/go/pkg/mod/go.elastic.co/apm/v2@v2.1.1-0.20220810211444-b8542dccafec/tracer.go:446 +0x98
go.elastic.co/apm/v2/apmtest.NewRecordingTracer(...) …
```
> test: close tracer in logging test and avoid goroutine leak

- apmpackage/apm/data_stream/service_summary_interval_metrics/elasticsearch/ingest_pipeline/default.yml
- systemtest/aggregation_test.go
- systemtest/apmservertest/config.go
- systemtest/approvals.go
- systemtest/approvals/TestServiceSummaryMetricsAggregationOverflow.approved.json
Fix regression introduced in #10061 where service summary overflow bucket did not work.
- Retest #10061: Ensure that service summary overflow bucket works
Related to #9654
> Fix service summary overflow bucket regression

- internal/beater/server_test.go
Similar to other PRs.
There was another gourine leak:
```
Goroutine 203 in state select, with net/http.(*persistConn).readLoop on top of the stack:
goroutine 203 [select]:
net/http.(*persistConn).readLoop(0xc0001245a0)
/usr/lib/go/src/net/http/transport.go:2227 +0xd85
created by net/http.(*Transport).dialConn
/usr/lib/go/src/net/http/transport.go:1765 +0x16ea
[originating from goroutine 201]:
net/http.(*Transport).dialConn(...)
/usr/lib/go/src/net/http/transport.go:1766 +0x16ea
net/http.(*Transport).dialConnFor(...)
/usr/lib/go/src/net/http/transport.go:1456 +0xb0
created by net/http.(*Transport).queueForDial
/usr/lib/go/src/net/http/transport.go:1425 +0x3ea
[originating from goroutine 86]:
net/http.(*Transport).queueForDial(...)
/usr/lib/go/src/net/http/transport.go:1426 +0x3ea …
```
> test: close response body in TestServerRoot and fix goroutine leak

- .github/workflows/update-beats.yml
Redo https://github.com/elastic/apm-server/pull/10294, which seems to have been reverted in a merge.
> .github: unrevert notification change

- systemtest/benchtest/expvar/metrics.go
Another goroutine leak in benchtest:
```
--- FAIL: TestWatchMetricNonBlocking (1.51s)
leaks.go:78: found unexpected goroutines:
[Goroutine 29 in state chan send, with github.com/elastic/apm-server/systemtest/benchtest/expvar.run.func1 on top of the stack:
goroutine 29 [chan send]:
github.com/elastic/apm-server/systemtest/benchtest/expvar.run.func1()
/apm-server/systemtest/benchtest/expvar/metrics.go:251 +0x105
created by github.com/elastic/apm-server/systemtest/benchtest/expvar.run
/apm-server/systemtest/benchtest/expvar/metrics.go:231 +0x110
[originating from goroutine 35]:
github.com/elastic/apm-server/systemtest/benchtest/expvar.run(...)
/apm-server/systemtest/benchtest/expvar/metrics.go:255 +0x110
github.com/elastic/apm-server/systemtest/benchtest/expvar.(*Collector).start(...) …
```
> benchtest: break out of infinite loop and fix goroutine leak

- .ci/schedule-everyday.groovy
Changes the benchmark schedule so it is run a couple of hours after the stack bump is scheduled to happen.
Some relief to problems outlined in #10315
> benchmark: Run 2-3h after stack bump is run

- .ci/bump-golang.yml
- .github/workflows/bump-golang.yml
- .github/workflows/opentelemetry.yml
Automate the golang bump within the project itself using [updatecli](https://www.updatecli.io/) and github actions
Remove the dependency with Jenkins and the definition of what to do in [apm-pipeline-library](https://github.com/elastic/apm-pipeline-library/blob/a3850732518748f2e71815c093d58cb071d0d8a3/.ci/.bump-go-release-version.yml#L33-L40)
Use updatecli that provide the tooling for bumping versions
Similar to https://github.com/elastic/beats/pull/34458
Requires https://github.com/elastic/apm-pipeline-library/pull/2076
https://github.com/v1v/apm-server/pull/20 was created to test these changes on my forked repo using `1.19.4` for testing purposes
> golang: bump automation with updatecli and GH actions 

- .ci/schedule-daily.groovy
Update Beats is not anymore a Jenkins specific task but an updatecli CI agnostic running on GitHub actions.
Leftover from https://github.com/elastic/apm-server/pull/10179
> ci: remove update-beats daily from Jenkins

- internal/beatcmd/beat.go
_Recalling the exact syntax for the built-in stab() function, you make a sane assumption and call shoot(GUN, FOOT); The foot shoots your gun_
> fix: invert args order for prefix check in deprecation notice

- apmpackage/apm/changelog.yml
- apmpackage/apm/data_stream/service_destination_interval_metrics/fields/ecs.yml
- apmpackage/apm/data_stream/service_destination_interval_metrics/fields/fields.yml
- docs/data-model.asciidoc
- systemtest/aggregation_test.go
- systemtest/approvals/TestServiceDestinationAggregation.approved.json
Fix regression introduced by #10056 where service destination labels are not stored successfully.
- Ensure that service destination labels are stored
Related to #10045
> Fix service destination labels regression

- systemtest/fleet_test.go
The `copyLogs` goroutine was leaking along with the agent docker container.
The goroutine would block reading the container logs: 
https://github.com/elastic/apm-server/blob/95a10bf326c6982bd19a89f2654a8b0a5c1ee59b/systemtest/containers.go#L409
Note the usage of `Follow: true` in the log options.
Stacktrace of the leaking goroutine:
```
Goroutine 117 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
goroutine 117 [IO wait]:
internal/poll.runtime_pollWait(0x7fc6e880f190, 0x72)
/usr/lib/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0002cbe00?, 0xc0005f5000?, 0x0)
/usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
/usr/lib/go/src/internal/poll/fd_poll_runtime.go:89 …
```
> test: always close agent container, even if the test did not fail

- .ci/update-beats.yml
Set `disablesourceinput: true` on the update-beats branch condition to stop the commit hash being added to the command line.
> .ci: fix update-beats branch condition

- .ci/update-beats.yml
Remove `sourceid`, incompatible with `disablesourceinput`.
> .ci: fix update-beats branch condition, take 2

- .ci/update-beats.yml
Remove the condition altogether. The Github Action already checks which branches are active releases. If we should still have this check, I think it should be a separate Github Action step, and not an updatecli condition.
> .ci: fix update-beats branch condition, take 3

- .mergify.yml
Automatically squash and merge updatecli PRs (`update-beats` and `bump-elastic-stack-snapshot`).
> mergify: auto squash/merge updatecli PRs

- magefile.go
Like https://github.com/elastic/beats/pull/34614, but for the apm-server directory. Works around strict directory ownership checks that fail in the Docker crossbuild image. Only relevant to the 7.17 branch.
`SNAPSHOT=true PLATFORMS=darwin/amd64 TYPES=docker mage package`
None
> mage: set safe.directory for crossbuild

- apm-server.docker.yml
- apm-server.yml
- docs/legacy/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
There have been config changes but not all the changes were reflected in `apm-server.yml` so it needed to be brought up to date.
- `queue.*`
- `max_procs`
- `output.elasticsearch.parameters`, `output.elasticsearch.worker`, `output.elasticsearch.bulk_max_size`, `output.elasticsearch.kerberos`
- `monitoring.elasticsearch.parameters`, `monitoring.elasticsearch.bulk_max_size`, `monitoring.elasticsearch.kerberos`
- `output.elasticsearch.flush_bytes`
- `output.elasticsearch.flush_interval`
In addition to that, as [requested](https://github.com/elastic/apm-server/issues/10150#issuecomment-1435938582), I've tested whether `cloud.id` and `cloud.auth` still works or not. I verified that it still works since I was able to send data to Elasticsearch from my local apm-server using those credentials. …
> chore: bring up to date `apm-server.yml` 

- testing/benchmark/main.tf
- testing/cloud/main.tf
- testing/infra/terraform/modules/ec_deployment/terraform.tf
- testing/rally-cloud/main.tf
- testing/smoke/main.tf
- testing/smoke/supported-os/main.tf
Avoid a bunch of automated failures due to a breaking 0.6.0 version of the provider being available
> Terraform: Pin version to `0.5.1` for now

- apm-server.docker.yml
- apm-server.yml
Re-add `max-procs` to the yml file. 
Addressing https://github.com/elastic/apm-server/issues/10150#issuecomment-1451277028
> fix: re-add max-procs to config options

- apmpackage/apm/data_stream/service_destination_interval_metrics/elasticsearch/ilm/default_policy.10m.json
- apmpackage/apm/data_stream/service_destination_interval_metrics/elasticsearch/ilm/default_policy.60m.json
- apmpackage/apm/data_stream/service_summary_interval_metrics/elasticsearch/ilm/default_policy.10m.json
- apmpackage/apm/data_stream/service_summary_interval_metrics/elasticsearch/ilm/default_policy.60m.json
- apmpackage/apm/data_stream/service_transaction_interval_metrics/elasticsearch/ilm/default_policy.10m.json
- apmpackage/apm/data_stream/service_transaction_interval_metrics/elasticsearch/ilm/default_policy.60m.json
- apmpackage/apm/data_stream/transaction_interval_metrics/elasticsearch/ilm/default_policy.10m.json
- apmpackage/apm/data_stream/transaction_interval_metrics/elasticsearch/ilm/default_policy.60m.json
Updates the 10m and 60m delete phase for all the "rolled up" aggregated metrics to 180d and 390d respectively:
- service_destination
- service_summary
- service_transaction
- transaction
Install the APM package and validate that the ILM policies delete phase are correct.
> 10m,60m metrics: Update delete phase to 180d, 390d

- Makefile
Remove the `-u` flag, which instructs `go get` to update other dependencies too. These should be updated explicitly and intentionally, not as a byproduct of updating libbeat.
N/A
https://github.com/elastic/apm-server/actions/runs/4365568437/jobs/7634381785
> update-beats: only update beats module

- NOTICE.txt
- apmpackage/apm/changelog.yml
- apmpackage/apm/data_stream/app_logs/manifest.yml
- changelogs/head.asciidoc
- docs/data-streams.asciidoc
- go.mod
- go.sum
- systemtest/approvals/TestIntakeLog/with_faas.approved.json
- systemtest/approvals/TestIntakeLog/with_flat_ecs_fields.approved.json
- systemtest/approvals/TestIntakeLog/with_nested_ecs_fields.approved.json
- systemtest/approvals/TestIntakeLog/with_nested_ecs_fields_overrides_flat_fields.approved.json
- systemtest/approvals/TestIntakeLog/with_timestamp.approved.json
- systemtest/approvals/TestIntakeLog/with_timestamp_as_str.approved.json
- systemtest/approvals/TestIntakeLog/without_timestamp.approved.json
- systemtest/approvals/TestJaeger/batch_0.approved.json
- systemtest/approvals/TestJaeger/batch_1.approved.json
- systemtest/approvals/TestOTLPGRPCLogs.approved.json
- systemtest/approvals/TestOTLPGRPCTraces.approved.json
- systemtest/intake_log_test.go
As described in #10291, we want to store app logs per service to follow best practices for the data stream naming convention.
1. Spin up tilt
2. Fire some events to intake endpoints
example:
```
curl --request POST \
--url http://localhost:8200/intake/v2/events \
--header 'content-type: application/x-ndjson' \
--data '{"metadata":{"service":{"name":"test-service-1","version":"4.3.0","environment":"production", "language":{"name":"Java","version":"10.0.2"},"agent":{"version":"1.10.0","name":"java"}}, …
```
> feat: stores app logs in service-specific data stream

- docs/empty.yml
- docs/legacy/configuration-anonymous.asciidoc
- docs/legacy/configuration-rum.asciidoc
- docs/legacy/secure-communication-agents.asciidoc
- docs/secure-agent-communication.asciidoc
> The docs should be updated to better reflect that, by default, RUM related auth handling is disabled, but enabled as soon as auth handling is generally enabled.
The goal of this PR is to better clarify when and why anonymous requests to the APM Server are accepted or rejected. Here's the thought process—and please correct me if I'm wrong:
We have two anonymous authentication pages in the docs. One is for the [APM integration](https://www.elastic.co/guide/en/apm/guide/master/anonymous-auth.html) and one is for [standalone APM Server](https://www.elastic.co/guide/en/apm/guide/master/secure-communication-unauthenticated.html). This PR updates these pages to clarify that the APM Server’s default response to anonymous requests depends on whether an API key or Secret Token has been …
> docs: Clarify anonymous authentication details

- docs/empty2.yml
- docs/log-correlation.asciidoc
Document service-level correlation for logs
part of https://github.com/elastic/apm/issues/765
> Document service log correlation

- apm-server.docker.yml
- apm-server.yml
- docs/empty.yml
- docs/empty2.yml
- docs/legacy/configuration-agent-config.asciidoc
- docs/legacy/configure-kibana-endpoint.asciidoc
- docs/legacy/configuring.asciidoc
- docs/legacy/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
- docs/legacy/tab-widgets/jaeger-sampling.asciidoc
* For https://github.com/elastic/apm-server/issues/9982
* Closes https://github.com/elastic/apm-server/issues/9350
* Closes https://github.com/elastic/apm-server/issues/10046
The following tasks remain for https://github.com/elastic/apm-server/issues/9982.
All APM agent documentation currently links to our [Kibana docs on Central config](https://www.elastic.co/guide/en/kibana/8.6/agent-configuration.html). In addition, the following agents mention `kibana.enabled`, which should be removed:
> docs: APM agent config

- .ci/Jenkinsfile
Simplify the parallel stages since UTs are already running on GH actions
So I removed the parallel meta-stage and execute in sequential steps since `Downstream - Package - PR` does nothing but triggering another build, hence there is no need to run in parallel.
Report test-coverage similarly done in https://github.com/elastic/elastic-serverless-forwarder/pull/294
> ci: remove all the stages that run in GH actions

- apm-server.docker.yml
- apm-server.yml
- docs/legacy/configuration-agent-config.asciidoc
- docs/legacy/configure-kibana-endpoint.asciidoc
- docs/legacy/configuring.asciidoc
- docs/legacy/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
- docs/legacy/tab-widgets/jaeger-sampling.asciidoc
- [docs: APM agent config (#10471)](https://github.com/elastic/apm-server/pull/10471)
> [8.7] docs: APM agent config (#10471)

- docs/empty.yml
- docs/legacy/configuration-anonymous.asciidoc
- docs/legacy/configuration-rum.asciidoc
- docs/legacy/secure-communication-agents.asciidoc
- docs/secure-agent-communication.asciidoc
This will backport the following commits from `main` to `8.6`:
- [docs: Clarify anonymous authentication details (#10227)](https://github.com/elastic/apm-server/pull/10227)
> [8.6] docs: Clarify anonymous authentication details (#10227)

- docs/empty.yml
- docs/legacy/configuration-anonymous.asciidoc
- docs/legacy/configuration-rum.asciidoc
- docs/legacy/secure-communication-agents.asciidoc
- docs/secure-agent-communication.asciidoc
- [docs: Clarify anonymous authentication details (#10227)](https://github.com/elastic/apm-server/pull/10227)
> [8.7] docs: Clarify anonymous authentication details (#10227)

- docs/empty2.yml
- docs/log-correlation.asciidoc
- [Document service log correlation (#10454)](https://github.com/elastic/apm-server/pull/10454)
> [8.7] Document service log correlation (#10454)

- systemtest/benchtest/clients.go
- systemtest/loadgen/config/config.go
- systemtest/loadgen/eventhandler.go
- systemtest/loadgen/eventhandler/handler.go
- systemtest/loadgen/eventhandler/handler_test.go
- systemtest/soaktest/soaktest.go
Add an option to `apmsoak` and `apmbench` to rewrite `trace.id`, `transaction.id`, `span.id`, `parent.id`, and `error.id`. These are rewritten only if their contents are entirely hex digits.
For each iteration (each call to `Handler.SendBatches`) we will calculate a random number and use it to mutate the IDs. IDs are mutated consistently to ensure relationships between events are maintained, e.g. to ensure `parent.id` will match a `span.id` value.
1. Run `apmsoak` for 1-2 minutes
2. …
> systemtest/loadgen: support ID randomisation

- systemtest/benchtest/clients.go
- systemtest/loadgen/config/config.go
- systemtest/loadgen/eventhandler.go
- systemtest/loadgen/eventhandler/handler_test.go
- systemtest/loadgen/eventhandler/transport.go
- systemtest/soaktest/soaktest.go
Adds support adding arbitrary headers to the `apmsoak` binary via a new `header` flag which can be set multiple times.
N/A
> apmsoak: Support arbitrary headers via `-header`

- docs/a.yml
- docs/apm-breaking.asciidoc
This is a small PR that duplicates the breaking changes described in the release notes to our breaking changes page. This is required so we can automatically propagate all Stack breaking changes to the Elastic Stack Installation and Upgrade guide.
> docs: duplicate breaking changes

- docs/a.yml
- docs/apm-breaking.asciidoc
- [docs: duplicate breaking changes (#10559)](https://github.com/elastic/apm-server/pull/10559)
> [8.7] docs: duplicate breaking changes (#10559)

- .github/workflows/ci-docs.yml
`lint` check is mandatory regardless of the changes, so `ci-docs.yml` is workaround to skip checks when the CI does. not run for docs changes.
Otherwise, it might mislead contributors since the lint check will not allow merging docs only PRs.
cc @bmorelli25
> action: lint is mandatory but doc changes don't need it

- .github/workflows/ci-docs.yml
- [action: lint is mandatory but doc changes don't need it (#10564)](https://github.com/elastic/apm-server/pull/10564)
> [8.7] action: lint is mandatory but doc changes don't need it (#10564)

- dev_docs/TESTING.md
- systemtest/benchtest/main.go
- systemtest/gencorpora/gencorpora.go
- systemtest/loadgen/config/config.go
- systemtest/loadgen/eventhandler/handler.go
- systemtest/loadgen/eventhandler/handler_test.go
- systemtest/loadgen/limiter.go
- systemtest/soaktest/soaktest.go
- testing/apmsoak/main.tf
- testing/apmsoak/terraform.tfvars.example
- testing/apmsoak/variables.tf
- testing/benchmark/Makefile
- testing/infra/terraform/modules/soaktest_workers/README.md
- testing/infra/terraform/modules/soaktest_workers/main.tf
- testing/infra/terraform/modules/soaktest_workers/systemd.tpl
- testing/infra/terraform/modules/soaktest_workers/variables.tf
Support for configuring the burst size and interval to verify the server's ability to handle sustained bursty workloads. 
closes #10444
> feat: steady rate load generation for loadgen

- systemtest/loadgen/config/config.go
- systemtest/loadgen/eventhandler.go
- systemtest/loadgen/eventhandler/handler.go
- systemtest/loadgen/eventhandler/handler_test.go
- systemtest/soaktest/soaktest.go
Add flags for apmsoak to rewrite name fields:
```
-rewrite-service-names service.name
replace service.name in events
-rewrite-service-node-names service.node.name
replace service.node.name in events
-rewrite-service-target-names service.target.name
replace service.target.name in events
-rewrite-span-names span.name
replace span.name in events
-rewrite-transaction-names transaction.name
replace transaction.name in events
```
If any of these flags are specified, then the corresponding fields will be rewritten by replacing ASCII letters and digits with a random rune of the same category.
These flags are intended for testing the impacts of high cardinality.
~- [ ] Update [package …
> systemtest/loadgen: add `-rewrite-*-names` flags

- .mergify.yml
Use the same implementation as https://github.com/elastic/fleet-server/pull/168 so automated backports that are generated by mergify will be auto-merged if they passed in the CI.
It uses a few conditions:
- generated by `mergify`
- with a `backport` label
- without conflicts
I also added a few more conditions in the queue rule to reflect the change to GitHub actions, since it used Jenkins commit status checks only
> mergify: auto-merge backports from mergify

- .mergify.yml
It's not allowed to use the same user to create PRs and approve them
https://github.com/elastic/apm-server/pull/10544/checks?check_run_id=12420261076
> mergify: cannot create and auto-approve the same user

- changelogs/8.7.asciidoc
- x-pack/apm-server/aggregation/spanmetrics/aggregator.go
- x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
Use the correct outcome when creating the aggregation keys: use the outcome from dropped span stats instead of the current event outcome
Closes https://github.com/elastic/apm-server/issues/10543
> fix: use dropped spans outcome in spanmetrics aggregation

- systemtest/profiling_test.go
- x-pack/apm-server/profiling/auth.go
- x-pack/apm-server/profiling/collector.go
- x-pack/apm-server/profiling/grpcext.go
Added checks for RPC protocol version mismatches. 
I tested with HA v2.4.1 and v2.5.2. HAs older than v2.4.1 (AFAIK we never made any such older version available to beta customers) that do not send RPC protocol version will error on startup. 
This should be part of the upcoming 8.7.1 release.
> Universal Profiling: Versioned RPC protocol

- changelogs/8.7.asciidoc
- internal/beater/middleware/timeout_middleware.go
- internal/beater/middleware/timeout_middleware_test.go
Fixes the response.errors.timeout counter.
See fixed issue
Fixes #10593
> metrics: Count context.DeadlineExceeded as timeout

- changelogs/8.7.asciidoc
- internal/beater/interceptors/metrics.go
- internal/beater/interceptors/metrics_test.go
- internal/beater/request/result.go
Updates the GRPC metrics interceptor to increment the timeout counter for requests with `code.Canceled`.
See related issue.
Related to #10593
> metrics: Count GRPC codes.Canceled as timeout

- systemtest/benchtest/main.go
- systemtest/loadgen/eventhandler/handler.go
- systemtest/loadgen/eventhandler/handler_test.go
- systemtest/soaktest/soaktest.go
if event rate is `n/t`,
Send a burst of `n` data every `t` rather than spread the load over duration `t`
TBC
closes #10575
> feat: wait for interval and sends events at once

- changelogs/8.7.asciidoc
- systemtest/aggregation_test.go
- x-pack/apm-server/aggregation/labels/labels.go
Remove global labels for RUM services to avoid explosion of metric groups to track for servicetxmetrics. For consistency, this will remove labels for other aggregated metrics as well. Agent name "rum-js", "js-base", "android/java", "iOS/swift" are considered as RUM in this case.
- Send RUM events with global different labels, verify that they are aggregated into the same group, and that the resulting aggregation document does not contain global labels.
Closes #10532
> Remove global labels from agg key for RUM services

- changelogs/8.7.asciidoc
- systemtest/aggregation_test.go
- systemtest/approvals/TestTransactionAggregation.approved.json
- x-pack/apm-server/aggregation/txmetrics/aggregator.go
- x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Remove redundant aggregation groups on `faas.coldstart` in transaction metrics by introducing a nullable bool for `faas.coldstart` in transaction metrics aggregation key comparable.
- Send 2 non-nil faas.coldstart and make sure they correctly group and aggregate into 1 metric document per interval
Closes #10621
> Remove redundant aggregation groups on `faas.coldstart` in transaction metrics

- docs/monitor.asciidoc
Fleet and Agent documentation has moved to ingest-docs. This quick lil PR changes where the APM Guide sources this content from. For https://github.com/elastic/docs/pull/2662.
> docs: move location of included content

- NOTICE.txt
- go.mod
- go.sum
> Update go-elasticsearch to v8.7.0

- docs/monitor.asciidoc
- [docs: move location of included content (#10646)](https://github.com/elastic/apm-server/pull/10646)
> [8.7] docs: move location of included content (#10646)

- docs/monitor.asciidoc
This will backport the following commits from `main` to `8.6`:
- [docs: move location of included content (#10646)](https://github.com/elastic/apm-server/pull/10646)
> [8.6] docs: move location of included content (#10646)

- docs/monitor.asciidoc
This will backport the following commits from `main` to `8.5`:
- [docs: move location of included content (#10646)](https://github.com/elastic/apm-server/pull/10646)
> [8.5] docs: move location of included content (#10646)

- docs/monitor.asciidoc
This will backport the following commits from `main` to `8.4`:
- [docs: move location of included content (#10646)](https://github.com/elastic/apm-server/pull/10646)
> [8.4] docs: move location of included content (#10646)

- internal/beatcmd/logging.go
Properly set the logging environment and leave the fallback to the agent-libs library.
Do not overwrite logging options with the stderr config.
`logp.Configure` should default to stderr if no other options is passed in container/systemd environments
This should fix the options for smoke test, allowing us to retrieve the apm-server log.
- Is its use being published in …
> fix: do not overwrite logging options in containers or systemd environment

- systemtest/loadgen/config/config.go
- systemtest/loadgen/eventhandler.go
- systemtest/loadgen/eventhandler/handler.go
- systemtest/loadgen/eventhandler/handler_test.go
- systemtest/soaktest/soaktest.go
apmsoak: Add option to rewrite transaction type to simulate high cardinality service transaction groups.
> apmsoak: Add option to rewrite transaction type

- docs/log-correlation.asciidoc
Adds `container.id` to the list of fields used for log correlation.
Logs correlation logic on the service overview tab ([Kibana code](https://github.com/elastic/kibana/blob/0a120ab8ffb218a7c177a399ad456190aada49cf/x-pack/plugins/apm/public/components/app/service_logs/index.tsx#L79)):
- If the environment selector is set to 'All' in the UI we correlate on service name. KQL: `service.name: "my-service"`. If an environment is selected we correlate by service name and environment, if it exists. KQL: `(service.name: "my-service" and service.environment: "my-environment") or (service.name: "my-service" and not service.environment: *`)
- If there are container IDs we add (combine) a KQL statement to target logs with container IDs but no service.name: `or (container.id: "my-container-id" and not …
> [Docs] Add 'container.id' to the list of fields used for log correlation

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.0-2a83168d
---
<Actions>
<action id="74ae3c45e80bbfc88a52d21408fa1ad6897c610b3c77e08f691a809fc6263746">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.0-2a83168d

- Makefile
Fix build issues like https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-package-mbp/detail/7.17/668/pipeline/. In recent versions of Go's os/exec, executing a program that resolves relative to the working directory will result in an error. We fix this by ensuring the addition to $PATH is absolute.
N/A
None
> Makefile: ensure $PATH for mage is absolute

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.0-4903e450
---
<Actions>
<action id="c206a0b4dc863d7c87e25c0070065a4ce0023129c84b2bc7cc713f2dffa3f95e">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.0-4903e450

- .mergify.yml
- apmpackage/apm/changelog.yml
- cmd/intake-receiver/version.go
- internal/version/version.go
Merge as soon as 8.8 branch was created. Auto-merge is not yet supported, see https://github.com/Mergifyio/mergify-engine/discussions/2821
> backport: Add 8.8 branch

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.0-ebff07ec
---
<Actions>
<action id="f3477000c9aaf3b48b2684c65c2eb5ef7af62e0755ba0091bb334cc3decf9cf4">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.0-ebff07ec

- apmpackage/apm/changelog.yml
- apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.yml
- changelogs/head.asciidoc
- systemtest/approvals/TestCompressedSpans.approved.json
- systemtest/approvals/TestIntake/Events.approved.json
- systemtest/approvals/TestIntake/MinimalEvents.approved.json
- systemtest/approvals/TestIntake/Spans.approved.json
- systemtest/approvals/TestIntake/UnknownSpanType.approved.json
- systemtest/approvals/TestJaeger/batch_1.approved.json
The mobile ui wants to filter data based on host.os.version & service.version. Http spans are a key part of the mobile ui, and when filters are added for either of these attributes all http related charts will be empty.
https://github.com/elastic/apm-agent-ios/issues/145
> Add support for mobile UI filtering

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.0-de6751d7
---
<Actions>
<action id="969ba318a86a006cd0837017a4164efa4006f3cd406b2cbb0164f3a6cd45bdda">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.0-de6751d7

- NOTICE.txt
- go.mod
- go.sum
- internal/beater/beatertest/output.go
- internal/beater/beatertest/server.go
Update tests to always set a libbeat output, avoiding changing libbeat behaviour when we update. See https://github.com/elastic/apm-server/pull/10675#issuecomment-1530757576
I have also updated go-sysinfo to the latest release, as I was observing errors about the signature changing. Not sure why, maybe the v1.10.0 tag was recreated?
N/A
None
> beatertest: configure a no-op output

- internal/publish/pub_test.go
Adapt the test to breaking changes in newer
versions of libbeat, where an output client
is required.
See https://github.com/elastic/apm-server/pull/10731
N/A
None
> internal/publish: adapt TestPublisherStop

- internal/beatcmd/logging.go
- internal/beatcmd/logging_test.go
This is the automated test-plan for #10666.
It introduces a new `buildLoggingConfig` method, which doesn't rely on anything global, so we can test its content, and `configureLogging` can just call it.
Test failure before the changes made in the linked PR:
```
=== RUN   TestBuildLoggingConfigPerEnvironment
=== RUN   TestBuildLoggingConfigPerEnvironment/with_an_empty_config_and_default_environment
=== RUN   TestBuildLoggingConfigPerEnvironment/with_an_logging_config_specified_and_default_environment
=== RUN   TestBuildLoggingConfigPerEnvironment/when_logging_to_stderr_and_default_environment
=== RUN   TestBuildLoggingConfigPerEnvironment/with_debug_selectors_and_default_environment
=== RUN   TestBuildLoggingConfigPerEnvironment/with_options_and_default_environment
=== RUN …
```
> Test beatcmd logging configuration

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.9.0-23370c3a
---
<Actions>
<action id="fac99318c32cd87eec2ba163d8c2f377403759891813764a1ea1bc4aa3a88fb1">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.9.0-23370c3a

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.9.0-c595c7d9
---
<Actions>
<action id="a6434bedf4966765b70ae2fb953a5a1821319683dfdefdefe2b8700577d5c6db">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.9.0-c595c7d9

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.0-8d0a4918
---
<Actions>
<action id="21473e8a7b2348cbcff2196bc76d2ea0047992851227fe651caaa9c719744ed4">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.0-8d0a4918

- .github/workflows/ci.yml
Add no-op 'system-test' and 'lint' jobs so the Mergify merge queue passes. These tasks are run by Jenkins at the moment.
> .github/workflows: add fake CI jobs

- systemtest/aggregation_test.go
- systemtest/apmservertest/config.go
`labels` should be inside `metadata` rather than at the same level as `metadata`:
```
{
"metadata": {
"service": {...},
"labels": {...},
...
}
}
```
> Fix incorrect labels definition for systemtest

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.9.0-2dbf1e1f
---
<Actions>
<action id="4a4c08c633cccc47620bcaeee205572abb5d878085fe953e34c87aecfa9e0846">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.9.0-2dbf1e1f

- docker-compose.yml
<Actions>
<action id="8daf80583fbe86c8d3a923c0812d6fec20e7fb9c246e08b493e8f04fe3875b73">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
> [updatecli] Bump elastic stack version to 7.17.11-4961dcd0

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.0-c26f78b8
---
<Actions>
<action id="aece911fd7b79993084b21ed41cf4ab06798ede5828d20924160ff371e85f41e">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.0-c26f78b8

- apmpackage/apm/changelog.yml
- apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.yml
- apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.yml
- apmpackage/apm/data_stream/service_destination_interval_metrics/elasticsearch/ingest_pipeline/default.yml
- apmpackage/apm/data_stream/service_summary_interval_metrics/elasticsearch/ingest_pipeline/default.yml
- apmpackage/apm/data_stream/service_transaction_interval_metrics/elasticsearch/ingest_pipeline/default.yml
- apmpackage/apm/data_stream/transaction_interval_metrics/elasticsearch/ingest_pipeline/default.yml
- apmpackage/cmd/genpackage/pipelines.go
Metrics produced by apm-server (apm-data)
will soon change. Update the ingest pipelines
to cater for this change. There is no change
to how metrics are indexed; the ingest pipeline
takes care of restructuring things.
N/A non-functional change until we update apm-data
https://github.com/elastic/apm-server/issues/3565
> apmpackage: prepare for metrics output schema change

- docker-compose.yml
<Actions>
<action id="c851f072e45619073c4405095049ea7bdb445bd73e0f643ed7043a9d0ac6700a">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
> [updatecli] Bump elastic stack version to 7.17.11-ad2a1253

- go.mod
- go.sum
- internal/beater/server_test.go
- internal/beater/tracing_test.go
We only use gjson in tests in a couple of places and it can easily be replaced with `assert.Contains`
> feat: drop gjson dependency

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.0-49c28bdb
---
<Actions>
<action id="f1bcbcf5c94d156b02d810f9fdf3bb065dccd495969fe62ece9bc26eb9861c59">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.0-49c28bdb

- apm-server.docker.yml
- apm-server.yml
The default shutdown timeout is 30s, not 5s.
N/A
None
> apm-server.yml: fix comment for shutdown_timeout

- internal/beater/api/mux.go
- internal/beater/api/mux_test.go
- internal/beater/beater.go
- internal/beater/otlp/http_test.go
- internal/beater/server.go
- internal/beater/tracing.go
- x-pack/apm-server/main_test.go
We no longer need to propagate throughout APM Server whether it is Fleet-managed, so remove this field.
N/A
None
> beater: remove ServerParams.Managed

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.9.0-9682eb9d
---
<Actions>
<action id="bcb87129a624e1e82cf33f15d38a11e80ecda014ddfded855b0c5e1c59c033a9">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.9.0-9682eb9d

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.0-cc834a5d
---
<Actions>
<action id="7ac9b86b3bdd038dc545596f5aafd5d656bfeb41596287b14f6fbe7fc6a24f4a">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.0-cc834a5d

- docker-compose.yml
<Actions>
<action id="4ab822138328d57d914cafc274e6f8880f1a6943c5418a7ab3e4ed41560a7b38">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
> [updatecli] Bump elastic stack version to 7.17.11-874490f1

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.9.0-b8c97a52
---
<Actions>
<action id="e76756fccce8e4903ea0e31339cc3465dbd042e3b57ab3dd01a61438d791944a">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.9.0-b8c97a52

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.0-9524d701
---
<Actions>
<action id="74894c414b6d95c0890eecacdb7688bd2c47f1ce6abbaa36418a9ef8640ca6e4">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.0-9524d701

- docker-compose.yml
<Actions>
<action id="e7b15d7621f18f4f5d7e346e637973c496f7dd2755e718f15b909d23a1a8076f">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
> [updatecli] Bump elastic stack version to 7.17.11-b843b253

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.0-4abaa07c
---
<Actions>
<action id="af5359ae98260a69e6b2579af0ba1ad4ad3de8c6664d64360ddcb7f5697121f1">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.0-4abaa07c

- docker-compose.yml
<Actions>
<action id="d1fa26aeb88a4112e0ea0e57a978b6b686bf4c39baa4d1cb2b940f00771054bb">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
> [updatecli] Bump elastic stack version to 7.17.11-0c2fb1a0

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.0-1b82ff0f
---
<Actions>
<action id="8b7568fed4d4b7a79db5fbbde7af14d8b4ad2c7ccef62d124ed703c48f80ab1f">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.0-1b82ff0f

- docker-compose.yml
<Actions>
<action id="1b54349d83be6724d2a37a38838439a190e0857f27f8002901c69e644a4b9cf2">
</details>
</action>
</Actions>
---
<ul>
</ul>
</details>
--- …
> [updatecli] Bump elastic stack version to 7.17.11-835d340b

- docs/legacy/copied-from-beats/docs/shared-docker.asciidoc
This updates the legacy [Run APM Server on Docker](https://www.elastic.co/guide/en/apm/guide/current/running-on-docker.html) page with a step to validate the Docker image. I'm not sure if we update these legacy docs anymore, but based on the issue linked below I think this is an important addition.
Rel: https://github.com/elastic/dev/issues/2002
Preview
---
> [docs] Add instructions for Docker image verification

- docs/configure/sampling.asciidoc
We support `sample_rate` range `[0, 1]`, update the docs to reflect the same.
> docs: fix range of sample_rate for TBS

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.0-e7f7cdfa
---
<Actions>
<action id="2f18c52f369cee86114ea56beadd382bddb3fb3bc6db4676558ab3bae57dd75b">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.0-e7f7cdfa

- .ci/packaging.groovy
Rerun automatically when DRA failed regardless of the failure in a any CI runner
This will with the known issue related to the ephemeral tokens which some times cause issues.
A similar approach has been done for Beats, see https://github.com/elastic/beats/pull/35506
Additionally, I bumped the version from 18 to 22.
> ci: retry if DRA failed

- .ci/benchmarks.groovy
- .gitignore
- testing/benchmark/.gitignore
- testing/benchmark/Makefile
- testing/benchmark/README.md
The APM macro Benchmarks currently use the last committed Elastic Agent docker image for the APM Server's daily benchmarks. This introduce a dependency on all other components to be built correctly to use the latest `apm-server` code: in case a dependant build fails, the Elastic Agent docker image is not updated. The result of this behaviour is that macro benchmarks may target a older-than-main version of `apm-server`, delaying the feedback loop on recent code changes.
This PR aims at removing this dependency by always building an Elastic Agent docker container that contains the latest `apm-server` code from the `main` branch of this repository. As macro benchmarks target `apm-server` performances, we don't care too much about the version of the Elastic Agent (as long as is reasonably new …
> Use apm-server latest for macro benchmarks

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.9.0-95ded584
---
<Actions>
<action id="4b7f7310f6074ee88053f9e15fa443f8adf6e92eaebcd3137c7e8aeb698944a9">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.9.0-95ded584

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.9.0-0b9c4000
---
<Actions>
<action id="aa94b8e36a19cad2d83aa0ec227322d9a91620eecb9967d4f54fe01466530d9c">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.9.0-0b9c4000

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.9.0-3cc641a9
---
<Actions>
<action id="412403b22c3504c9b3126b87fd1bef8c9116de399b5da113796d41c237b8d71f">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.9.0-3cc641a9

- .github/workflows/smoke-tests-ess.yml
- .github/workflows/smoke-tests-schedule.yml
* Add build status notification on Slack for Smoke tests.
* We migrate from Jenkins to GitHub Actions.
* Before, we had a notification after each build on Slack.
* This PR re-introduce the same mechanism on GitHub Actions.
* The workflow has been triggered using `gh workflow run smoke-tests-schedule.yml --ref feature/build-status`
* The result can be found [here](https://github.com/elastic/apm-server/actions/runs/5126180964).
> ci: notify build status on slack

- .github/workflows/smoke-tests-ess.yml
* Disable fail fast on smoke tests ESS
* All ESS smoke test jobs are canceled when an ESS smoke test fails.
* It's difficult to isolate failure and fix an ESS smoke test issue.
> ci: disable fail fast on smoke tests ESS

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.1-951ef2b6
---
<Actions>
<action id="e61cd51439ff08981f1faa548c714f8f002684a55de1dd394acabb68f599f889">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.1-951ef2b6

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.9.0-f1fa1d73
---
<Actions>
<action id="d6a1f4aad06d3bb7fad6e9c01fd4a611a9f9261ddf801dda1ae401074202510d">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.9.0-f1fa1d73

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.9.0-45019001
---
<Actions>
<action id="f076d03bb511dc36b93aebc80841159e8782c8808e8733b2ea3c1769efe9c3d2">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.9.0-45019001

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.1-afb32ff1
---
<Actions>
<action id="0934261a5978b05f9e99d16795db3aa29d52d11b91ebeb3468abb298931614e5">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.1-afb32ff1

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.1-67054589
---
<Actions>
<action id="4fef5ee97fd750779e64e86d6e9c7a54df61ca7b14056af8e23bce2d80f63cce">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.1-67054589

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.1-bc8f9ea4
---
<Actions>
<action id="fc5feedad6ff4b71fff000444476a9173776207fbd513fe4d0de1c825158552e">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.1-bc8f9ea4

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.1-e731bb3f
---
<Actions>
<action id="5b378609db21fb03ae5c036e06a066888799d15d00372d8d57f823016b9ecd40">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.1-e731bb3f

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.1-d9afcd4f
---
<Actions>
<action id="782a49aea0e6837959199e108ad0d7068a78dd1c676d9a4c6f33e995e4af5146">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.1-d9afcd4f

- Tiltfile
- script/wait_for_kibana.sh
- systemtest/apmservertest/config.go
- systemtest/kibana.go
Closes https://github.com/elastic/apm-dev/issues/937.
In short:
- if `--local-kibana` is set, checks port 5601 to see if there is a service running
- if it is, see if it is a Docker container or Kibana running locally in development mode
- if it's Kibana running locally, spawn a wait script that checks whether ES is available. this allows the user to start Kibana locally, without a working ES connection, and wait with installing the package until Kibana is available
- if there is no local Kibana, start the Kibana container
- Wait until either the local Kibana or the Kibana container is available when installing the package
I've added `KIBANA_BASE_PATH` to apm-server because in development mode, Kibana is often running on a different path rather than just the root.
> Use local Kibana in Tiltfile if available

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.9.0-f766627c
---
<Actions>
<action id="5fd16675998a67739e91460e123986b70f6b485f6376bbdae5c64d499c1c9100">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.9.0-f766627c

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.2-009f3608
---
<Actions>
<action id="71774f46fc947e2eacda0a5fa23e2cbefce356d4867f96835d4cde9e0b88a264">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.2-009f3608

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.9.0-37a365f9
---
<Actions>
<action id="f540f6f523ce8c1740829767745db7935e3a6eb1a9079ebefecd81ba08b20660">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.9.0-37a365f9

- .ci/benchmarks.groovy
- testing/benchmark/Makefile
Updates the failed benchmarks Slack notification to point to the newly created runbook.
> ci: Update failed benchmarks Slack notification

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.8.2-157bf445
---
<Actions>
<action id="6e58ee8f4ca0185c9100eb59fb7ba3f5572d10678f0e4a6d272876902eda4ebb">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.8.2-157bf445

- x-pack/apm-server/sampling/pubsub/pubsub.go
Small fix that can be reviewed in parallel with the rest of the protobuf work
> feat: remove old model usage from sampling package

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.9.0-fefa3eb8
---
<Actions>
<action id="e82c1c038bc66b59f6d8cdbc71811f80b2b502f8f1ee4d9d1cc0d571ca2b3d8a">
</details>
</details>
</action>
</Actions>
---
<ul> …
> [updatecli] Bump elastic stack version to 8.9.0-fefa3eb8

- NOTICE.txt
- go.mod
- go.sum
- systemtest/aggregation_test.go
- systemtest/huge_traces_test.go
- x-pack/apm-server/aggregation/txmetrics/aggregator.go
This is a small PR to fix an issue with aggregation tests.
Also bump the apm-data library and reenable the broke tests.
Related to https://github.com/elastic/apm-data/issues/52
Blocked by https://github.com/elastic/apm-data/pull/63
> feat: migrate decoders to protobuf

- NOTICE.txt
- go.mod
- go.sum
- internal/beater/api/intake/handler.go
- internal/beater/api/intake/handler_test.go
- internal/beater/api/mux.go
- internal/beater/api/mux_test.go
- internal/sourcemap/processor_test.go
Last "big" change related to the protobuf work:
- migrate metadata decoding to protobuf
- update leftover tests to use modelpb
Blocked by https://github.com/elastic/apm-data/pull/67
Blocked by https://github.com/elastic/apm-server/pull/11013
Related …
> feat: migrate metadata decoding to protobuf

- internal/r8/deobfuscator.go
- internal/r8/deobfuscator_test.go
Required to completely remove `model` package
No effect on production code since the class is unused
Related to https://github.com/elastic/apm-data/issues/52
> feat: migrate r8 deobfuscator to protobuf

- NOTICE.txt
- changelogs/head.asciidoc
- go.mod
- go.sum
See https://github.com/elastic/apm-data/pull/53
1. Send OTel spans with a combination of `db.*`, `messaging.*`, `rpc.*`, and `http.*` attributes
2. Ensure that span type is based on the descending order of preference `db --> messaging --> rpc --> http --> anything else`
https://github.com/elastic/apm-data/issues/43
> Fix OTel span type determinism

- Makefile
I accidentally merged a beats update to 7.17 that broke packaging, related to python requirements.
We don't need a virtualenv for packaging, just use the system python3 installation.
N/A
https://apm-ci.elastic.co/job/apm-server/job/apm-server-package-mbp/job/7.17/713/
> Don't use Python venv for packaging

- NOTICE.txt
- go.mod
- go.sum
Bump apm-data for structpb conversion fixes
`map[string]any` to modelpb conversion should be more robust now and avoid losing data because of unsupported types
Should be backported to 8.9 but I'll probably do it manually because of conflict in go.mod/notice
- Have system tests been added to avoid …
> fix: bump apm-data for structpb conversion

- testing/smoke/lib.sh
We can't convert x.y.z-SNAPSHOT to numbers so we strip the suffix. This only affect the supported-os smoke test which is currently broken because of the previous PR.
> test: strip snapshot suffix and fix supported-os smoke test

- changelogs/8.8.asciidoc
Adds the 8.8.2 release notes. I didn't notice anything noteworthy in the [commits](https://github.com/elastic/apm-server/commits/8.8). Please double-check and **merge** this PR if everything looks good (because I can't merge).
> Add 8.8.2 release notes

- internal/agentcfg/elasticsearch.go
As I am looking into adding instrumentation for this code path, I found this logic to be a bit obscure, especially as it shares variables between the main thread and an anonymous function.
So this refactor removes the anonymous function, so we explicitly pass the values we need.
This refactor has unit tests. There should be no behavior changes.
I'm doing this while working on #1014, but not directly related to it either.
> Refactor refreshCache to remove anonymous func

- systemtest/go.mod
- systemtest/go.sum
- systemtest/monitoring_test.go
- systemtest/sampling_test.go
Make the test a little more lenient to changes in the number of Elasticsearch bulk requests. Use `assert.Eventually` to wait until the server has indexed the expected number of events.
N/A
None
> systemtest: fix TestMonitoring flakiness

- systemtest/benchtest/main_test.go
- systemtest/loadgen/eventhandler/handler_test.go
Found a few race conditions while investigation flaky tests
run systemtests with the `-race` flag
> test: use atomic values to resolve race condition in systemtests

- .github/workflows/ci.yml
https://github.com/elastic/apm-server/pull/11194 is not mergable because it's waiting for the status check `system-test`. However, this check does not exist on `7.17`. 
This PR fixes it by creating a job named `system-test` that depends on the outcome of `go-system-tests` and `python-system-tests`.
> Fix mergify 7.17 status checks

- NOTICE.txt
- go.mod
- go.sum
- internal/beater/api/mux.go
- internal/beater/api/mux_test.go
- internal/beater/otlp/clientmetadata.go
- internal/beater/otlp/clientmetadata_test.go
Update apm-data. IPs now have a structured type, switch over to that.
N/A
https://github.com/elastic/apm-data/pull/110
> Update apm-data, use modelpb.IP

- docs/redirects.asciidoc
This will backport the following commits from `8.8` to `main`:
- [docs: redirects for removed pages (#10894)](https://github.com/elastic/apm-server/pull/10894)
> [main] docs: redirects for removed pages (#10894)

- docs/redirects.asciidoc
This will backport the following commits from `8.8` to `8.9`:
- [docs: redirects for removed pages (#10894)](https://github.com/elastic/apm-server/pull/10894)
> [8.9] docs: redirects for removed pages (#10894)

- testing/infra/terraform/modules/standalone_apm_server/latest_apm_server.sh
- testing/infra/terraform/modules/standalone_apm_server/latest_elastic_agent.sh
- testing/infra/terraform/modules/standalone_apm_server/main.tf
Smoketests on older branches are failing because thhey are installing the latest apm-server/elastic-agent version, leading to an ingestion in elasticsearch which is refusing because of the version check (8.10.0 vs 8.8.0).
This PR update the script to fetch the correct version 
Related to https://github.com/elastic/apm-server/issues/11281
> smoketest: install the specific apm-server and elastic-agent version instead of latest

- .ci/Jenkinsfile
- .ci/scripts/bench.sh
- .github/workflows/microbenchmark.yml
* Migrate microbenchmarks away from Jenkins.
* Use microbenchmark bridge running in Buildkite from GitHub Actions.
* Jenkins is deprecated and will be shut down by the end of the year.
Ref: https://github.com/elastic/apm-server/actions/runs/5680035679
> ci: migrate away from jenkins

- .github/workflows/benchmarks.yml
Only notify benchmarks failure via Slack on Nightly scheduled run
Closes: #11293
> ci: Only notify benchmarks failure via Slack on Nightly scheduled run

- docs/apm-breaking.asciidoc
With https://github.com/elastic/stack-docs/pull/2495 merged, we no longer need tags to reuse breaking changes in the Stack Install/Upgrade guide.
https://github.com/elastic/platform-docs-team/issues/143
> docs: remove breaking change tags

- internal/beater/processors.go
In docappender batch processor, grow the index string builder to the desired capacity in one go for better performance.
> Grow docappender indexBuilder to desired capacity for performance

- .github/workflows/microbenchmark.yml
- .github/workflows/opentelemetry.yml
microbenchmarks were enabled for all the branches and also for PRs, see https://github.com/elastic/apm-server/pull/8533
I'll enable it only for the active branches, when a push event happens.
> action: run microbenchmark on branches

- .buildkite/package.yml
- catalog-info.yaml
Add Buildkite pipeline definition in the catalog-info.json.
So we can start migrating the Jenkins packaging.
This pipeline will eventually run using https://github.com/elastic/apm-pipeline-library/tree/main/.github/actions/buildkite but for now we will enable the PRs from the origin only. So I can test https://github.com/elastic/apm-server/pull/11374 in isolation.
Cannot test these changes on a PR at the moment. `Terrazzo` uses this file then a Buildkite pipeline will be created.
Notifies https://github.com/elastic/apm-server/pull/11374
> buildkite: package definition

- changelogs/8.9.asciidoc
Adds the 8.9.1 release notes. I don't see anything worth mentioning in the commit history. Reviewers, please verify.
> add 8.9.1 release notes

- CHANGELOG.asciidoc
- changelogs/8.10.asciidoc
- docs/release-notes.asciidoc
Manual backport of https://github.com/elastic/apm-server/pull/11419/commits without `head.asciidoc`
> Update 8.10 changelogs

- apmpackage/apm/changelog.yml
- apmpackage/apm/data_stream/app_logs/fields/fields.yml
- apmpackage/apm/data_stream/app_metrics/fields/fields.yml
- apmpackage/apm/data_stream/error_logs/fields/fields.yml
- apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
- apmpackage/apm/data_stream/service_destination_interval_metrics/fields/fields.yml
- apmpackage/apm/data_stream/service_summary_interval_metrics/fields/fields.yml
- apmpackage/apm/data_stream/service_transaction_interval_metrics/fields/fields.yml
- apmpackage/apm/data_stream/traces/fields/fields.yml
- apmpackage/apm/data_stream/transaction_interval_metrics/fields/fields.yml
- docs/otel-metrics.asciidoc
- systemtest/approvals/TestAgentConfig.approved.json
- systemtest/approvals/TestApprovedMetrics.approved.json
- systemtest/approvals/TestIntake/Events.approved.json
- systemtest/approvals/TestIntake/Metricsets.approved.json
- systemtest/approvals/TestIntake/MinimalEvents.approved.json
- systemtest/approvals/TestOTLPGRPCMetrics_counter.approved.json
- systemtest/approvals/TestOTLPGRPCMetrics_histogram.approved.json
- systemtest/approvals/TestOTLPGRPCMetrics_summary.approved.json
- systemtest/approvals/TestRUMXForwardedFor.approved.json
- systemtest/approvals/TestServiceDestinationAggregation.approved.json
- systemtest/approvals/TestServiceSummaryMetricsAggregation.approved.json
- systemtest/approvals/TestServiceSummaryMetricsAggregationOverflow.approved.json
- systemtest/approvals/TestServiceTransactionMetricsAggregation.approved.json
- systemtest/approvals/TestTransactionAggregation.approved.json
- systemtest/approvals/TestTransactionAggregationShutdown.approved.json
- systemtest/approvals/TestTransactionDroppedSpansStatsMetrics.approved.json
This field is not used by the UI, and is redundant; its value can always be inferred from `data_stream.dataset`.
See https://github.com/elastic/kibana/issues/161718#issuecomment-1638294156
Verify that apm-server 8.9.0 can still index into an 8.11.0 deployment
https://github.com/elastic/kibana/issues/161718
> apmpackage: remove `processor.name` field

- changelogs/8.10.asciidoc
- changelogs/8.9.asciidoc
Fixes `View commits` link for `8.9` and `8.10`
> (docs): Fix commits link for released versions

- .ci/scripts/prepare-release-manager.sh
Copy will help running the two different DRA workflows sequentially using the same set of binaries.
Otherwise, it will fail since the file was already renamed in the previous DRA workflow.
> dra: support two workflows in the same context

- .buildkite/scripts/dra.sh
- .ci/scripts/prepare-release-manager.sh
Running the two DRA workflows with mv will make the second attempt fail.
I tried in the CI by creating a feature branch and [comment out ](https://github.com/elastic/apm-server/pull/11477/commits/86979d983e169ab5aa146baebc0c9e3d9423e4c5) some part of the pipeline
then It worked
> dra: only move if file does not exist

- .github/workflows/benchmarks.yml
- testing/benchmark/README.md
Since benchmarks moves to GH Actions, we lost some customization possibilities. This allows setting some attributes (the ones I need for #7842), while keeping the same defaults for the cronjobs.
This can be tested by manually running the workflow.
A test run: https://github.com/elastic/apm-server/actions/runs/5973256723/job/16205170670
> Customization for benchmarks manual runs

- NOTICE.txt
- go.mod
- internal/beater/beater.go
- internal/telemetry/metric_exporter.go
- internal/telemetry/metric_exporter_config.go
- internal/telemetry/metric_exporter_config_test.go
- internal/telemetry/metric_exporter_test.go
This sets up an OpenTelemetry exporter to collect internal metrics, export them as internal APM events and send them to the processor.
It is the boilerplate for #10623, yet no metrics are emitted yet. So this code isn't used at the moment.
This PR is unit-tested.
* #10623
> Otel exporter for internal telemetry

- catalog-info.yaml
Enable what to run for the apm-server-package buildkite pipeline explicitly. For some reason, default parameters are not honoured...
In the CI
> catalog-info: support main, release branches or feature branches

- changelogs/8.10.asciidoc
- internal/beater/beater.go
- systemtest/apmservertest/config.go
- systemtest/go.mod
- systemtest/go.sum
- systemtest/logstash_test.go
Unpack and pass `queue.*` config to libbeat. We were ignoring `queue.*` config when using libbeat outputs, such as logstash and kafka.
See reproduction steps in https://github.com/elastic/apm-server/issues/11533
Closes https://github.com/elastic/apm-server/issues/11533
> Handle queue.* config for libbeat outputs

- docs/getting-started-apm-server.asciidoc
`xpack.fleet.packages` requires a version for each installed package. This should be set to "latest" to use the bundled package.
Run through the getting started instructions.
None
> docs: fix getting started instructions

- .buildkite/hooks/pre-command
- .buildkite/hooks/pre-exit
this should help with environmental issues when accessing docker.hub
Docker login so no issues with quota limit in Dockerhub.
Fixes
```
ERROR: failed to solve: golang:1.20.7: failed to copy: httpReadSeeker: failed open: unexpected status code 
https://registry-1.docker.io/v2/library/golang/manifests/sha256:7fcc2684ef0de5f7730be51a493d26289756356a3c385ce6374b86d31d0be446: 429 Too Many Requests - Server message: toomanyrequests: 
You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
--
| make: *** [packaging.mk:42: build/docker/apm-server-8.10.0-SNAPSHOT.txt] Error 1
```
- Is its use being …
> buildkite: docker login

- internal/beater/api/mux.go
- internal/beater/beater.go
- internal/beater/interceptors/metrics.go
- internal/beater/interceptors/metrics_test.go
- internal/beater/middleware/monitoring_middleware.go
- internal/beater/middleware/monitoring_middleware_test.go
- internal/beater/monitoringtest/opentelemetry.go
- internal/beater/otlp/grpc_test.go
This modifies the HTTP and gRPC metrics middlewares to expose data to OpenTelemetry as well, so we can expose those metrics to the local exporter.
This is unit-tested. It can also be tested manually by running apm-server with Tilt and self instrumentation enabled.
> Expose HTTP/gRPC metrics to OpenTelemetry as well

- NOTICE.txt
- go.mod
- go.sum
*Changeset*
* https://github.com/elastic/beats/commit/c723290c2d3a
---
<Actions>
<action id="8d18d36a706ebf2fc800cc6c4fa82b4b68e544bd4390a823427d3fe9299b5493">
<summary>Update to elastic/beats@c723290c2d3a</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh c723290c2d3a&#34;</p>
</details>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br />
<ul> …
> [updatecli] Update to elastic/beats@c723290c2d3a

- changelogs/head.asciidoc
- docs/monitoring/monitoring-beats.asciidoc
- docs/monitoring/monitoring-local-collection.asciidoc
- internal/beater/beater.go
This is the last PR meant to expose local metrics to the batch processor, #10623.
It adds the HTTP and gRPC metrics to the allow list, so they are exposed to Kibana.
This can be tested by booting the stack with `tilt up` and triggering a batch send with OTLP.
> Expose local metrics to the batch processor

- changelogs/8.10.asciidoc
Update changelog to include a bug fix for `transaction.dropped_spans_stats.duration` that is now able to accept an empty object
> CHANGELOG: add bug fix entry for dropped_spans_stats.duration

- changelogs/8.10.asciidoc
- docs/apm-breaking.asciidoc
* There are no deprecations in the 8.10 release notes. This PR removes the deprecations heading.
* This PR adds the two breaking changes in 8.10 to our breaking changes page.
> Remove empty deprecations and add breaking changes [8.10]

- changelogs/head.asciidoc
- docs/monitoring/monitoring-local-collection.asciidoc
- internal/beater/beater.go
- internal/beater/interceptors/metrics.go
- internal/beater/interceptors/metrics_test.go
- internal/beater/middleware/monitoring_middleware.go
- internal/beater/middleware/monitoring_middleware_test.go
- internal/beater/monitoringtest/opentelemetry.go
This introduces the `(http|grpc).request.duration` metrics, and exports them with the local exporter.
This can be tested by running apm-server with tilt.
> Add request duration local metrics

- apmpackage/apm/changelog.yml
- apmpackage/cmd/genpackage/pipelines.go
- systemtest/errorgrouping_test.go
- systemtest/ingest_test.go
These are some of the changes needed for the system tests to pass when using the x-pack-apm ES plugin templates and pipelines (https://github.com/elastic/elasticsearch/pull/97546), rather than the Fleet integration package ones. There will be more changes needed, which we'll add later when we remove the data streams from the integration package.
N/A
https://github.com/elastic/elasticsearch/pull/97546
> Minor changes to support running system tests with x-pack-apm

- changelogs/head.asciidoc
- x-pack/apm-server/sampling/groups.go
- x-pack/apm-server/sampling/groups_test.go
- x-pack/apm-server/sampling/processor_test.go
In tail-based sampling, use math.ceil instead of math.Round when computing desired total such that on low throughput and low sample rate traces e.g. throughput=1, sample rate = 0.4, desired total = math.Ceil(1 * 0.4) = 1 as opposed to 0 when using math.Round. This will fix cases where these traces were missing before the fix.
Enable TBS, set sample rate to 0.4, send 1 trace. Check if the trace shows up.
Closes #11372
> Fix tail-based sampling discarding low throughput and low sample rate traces

- docs/configure/sampling.asciidoc
Document sampling behavior on TBS storage limit reached.
Closes #11126
> docs: Document sampling behavior on TBS storage limit reached

- changelogs/head.asciidoc
- docs/data-model.asciidoc
- internal/beater/beater.go
> Scale service destination based on available memory

- apmpackage/apm/data_stream/app_logs/elasticsearch/ilm/default_policy.json
- apmpackage/apm/data_stream/app_metrics/elasticsearch/ilm/default_policy.json
- apmpackage/apm/data_stream/error_logs/elasticsearch/ilm/default_policy.json
- apmpackage/apm/data_stream/internal_metrics/elasticsearch/ilm/default_policy.json
- apmpackage/apm/data_stream/rum_traces/elasticsearch/ilm/default_policy.json
- apmpackage/apm/data_stream/service_destination_interval_metrics/elasticsearch/ilm/default_policy.10m.json
- apmpackage/apm/data_stream/service_destination_interval_metrics/elasticsearch/ilm/default_policy.1m.json
- apmpackage/apm/data_stream/service_destination_interval_metrics/elasticsearch/ilm/default_policy.60m.json
- apmpackage/apm/data_stream/service_summary_interval_metrics/elasticsearch/ilm/default_policy.10m.json
- apmpackage/apm/data_stream/service_summary_interval_metrics/elasticsearch/ilm/default_policy.1m.json
- apmpackage/apm/data_stream/service_summary_interval_metrics/elasticsearch/ilm/default_policy.60m.json
- apmpackage/apm/data_stream/service_transaction_interval_metrics/elasticsearch/ilm/default_policy.10m.json
- apmpackage/apm/data_stream/service_transaction_interval_metrics/elasticsearch/ilm/default_policy.1m.json
- apmpackage/apm/data_stream/service_transaction_interval_metrics/elasticsearch/ilm/default_policy.60m.json
- apmpackage/apm/data_stream/traces/elasticsearch/ilm/default_policy.json
- apmpackage/apm/data_stream/transaction_interval_metrics/elasticsearch/ilm/default_policy.10m.json
- apmpackage/apm/data_stream/transaction_interval_metrics/elasticsearch/ilm/default_policy.1m.json
- apmpackage/apm/data_stream/transaction_interval_metrics/elasticsearch/ilm/default_policy.60m.json
- changelogs/head.asciidoc
- testing/smoke/lib.sh
In the Kibana UI, when looking at ILM policies related to apm-server, I see warnings:
**Maximum index size is deprecated and will be removed in a future version. Use maximum primary shard size instead.**
To avoid confusion for the end-user, I recommend that the same changes which were done in elasticsearch's default ILM policies be done for apm-server:
Related to:
*  https://github.com/elastic/elasticsearch/issues/63026
* https://github.com/elastic/elasticsearch/pull/69995 by @joegallo
Fixes: #11728
> Switch built-in ILM rollover policies from max_size to max_primary_shard_size

- packaging/ironbank/Dockerfile
> The Container Hardening Team (CHT) has identified a few of the Elastic images with UBI 8.7 as a base image.  This image is now EOL and 8.8 is the latest but will be EOL in the first quarter of 2024, so the CHT is recommending moving to UBI 9.x, which is being updated more often by Red Hat with security fixes.
In the CI and with the unified release automation
I'd propose to bump the version to the next minor and then work around supporting 9.x in a follow up
> ironbank: bump version to 8.8

- .github/workflows/ci.yml
Trying to fix disk space issues with the github runners:
```
/usr/local/go/pkg/tool/linux_amd64/link: mapping output file failed: no space left on device
Error: error compiling magefiles
make: *** [Makefile:264: build/linux/mage] Error 1
```
See https://github.com/elastic/apm-server/actions/runs/6484410856/job/17608183039?pr=11830
> action: free disk space in python-system-tests

- docs/api-info.asciidoc
Discussed in [case 01501264](https://support.elastic.co/cases/5008X00002UnA9UQAV)
Signed-off-by: Craig Rodrigues <rodrigc@crodrigues.org>
I found the existing documentation for the server information endpoint to be a bit confusing.
I didn't understand that GET and POST behave differently.
> docs: clarify the usage of the server information endpoint

- packaging/ironbank/Dockerfile
- packaging/ironbank/hardening_manifest.yaml
The path for the UBI 8.x and UBI 9.x Docker images is different. This PR corrects the name of the Docker images.
https://repo1.dso.mil/dsop/elastic/apm-server/apm-server/-/merge_requests/92
> fix: correct base Docker image names

- docs/sampling.asciidoc
For https://github.com/elastic/staging-serverless-observability-docs/issues/153.
Related to https://github.com/elastic/staging-serverless-observability-docs/pull/178.
This PR updates our OpenTelemetry head-based sampling documentation based on the fantastic overview provided by @gregkalapos in https://github.com/elastic/staging-serverless-observability-docs/pull/178.
> Update OTel head-based sampling limitation

- .buildkite/scripts/dra.sh
APM Server in `7.17` uses the packaging system from `elastic/beats` but `elastic/beats` has not been updated to use `ubi9` yet.
This is the workaround until the upstream project moves to ubi9
Create some files and run the script locally
```
$ mkdir -p build/distributions
$ touch "build/distributions/apm-server-7.17.15-aarch64.rpm"
touch "build/distributions/apm-server-ubi8-7.17.15-linux-amd64.docker.tar.gz"
touch "build/distributions/apm-server-oss-7.17.15-linux-arm64.docker.tar.gz"
touch "build/distributions/apm-server-oss-7.17.15-SNAPSHOT-linux-arm64. …
```
> dra: rename ubi8 for ubi9

- .github/workflows/smoke-tests-ess.yml
- .github/workflows/smoke-tests-schedule.yml
* Only trigger one notification for the whole GitHub Workflow instead of one per sub-workflow.
The change has been tested [here](https://github.com/elastic/apm-server/actions/runs/6708035039/attempts/1).
> feat: unified notification for smoke tests

- testing/smoke/lib.sh
Updates the legacy smoke test ILM policy size field name. It appears to have changed recently from `max_primary_shard_size` to `max_size`.
```
-> Invalid ILM policy apm-rollover-30-days; expected hot phase max_primary_shard_size 50gb got null
{
"min_age": "0ms",
"actions": {
"set_priority": {
"priority": 100
},
"rollover": {
"max_size": "50gb",
"max_age": "30d"
}
}
}
```
Full log: https://github.com/elastic/apm-server/actions/runs/6765796976/job/18385971031
Closes #11872
> smoke: Rename max_primary_shard_size to max_size

- changelogs/8.10.asciidoc
- docs/configure/outputs/logstash.asciidoc
- docs/data-model.asciidoc
- docs/otel-metrics.asciidoc
Removes references to `processor.event`, which was removed in v8.10.0. A couple notes:
* In [#11989](https://github.com/elastic/apm-server/issues/11989), @marclop mentioned users who use `[processor][event]` in Logstash for routing purposes in [Logstash configuration pipeline](https://www.elastic.co/guide/en/apm/guide/current/logstash-output.html#ls-config-pipeline), but I found a few other references that I _think_ should be removed (but let me know if not).
* I _think_ for `[data_stream][type]` you would have to be `metrics` (plural) instead of `metric`. Is that right?
* I guessed this would be considered a breaking change, but I wasn't completely sure.
Closes https://github.com/elastic/apm-server/issues/11989
> docs: Remove references to `processor.event`

- .github/workflows/benchmarks.yml
Add the APM Server header in the slack message to help identifying what's the benchmark about since some other projects are also running some benchmarks and use a similar kind of slack notifications.
> chore: add APM Server in the slack message

- docs/configure/outputs/logstash.asciidoc
Update the [logstash guide](https://www.elastic.co/guide/en/apm/guide/current/logstash-output.html#ls-config-pipeline) to remove the mutate filter since it's not necessary anymore.
Closes https://github.com/elastic/apm-server/issues/11917
> docs: Remove references to the mutate filter

- apmpackage/apm/data_stream/error_logs/fields/fields.yml
- apmpackage/apm/data_stream/traces/fields/fields.yml
- systemtest/approvals/TestIntake/Errors.approved.json
- systemtest/approvals/TestIntake/ErrorsTxID.approved.json
- systemtest/approvals/TestIntake/Events.approved.json
- systemtest/approvals/TestIntake/Transactions.approved.json
- systemtest/approvals/TestIntake/TransactionsHugeTraces.approved.json
- systemtest/approvals/TestIntake/UnknownSpanType.approved.json
- systemtest/approvals/TestRUMRoutingIntegration.approved.json
Revert some fields from flattened back to object to align with how we will dynamically map those fields in the future. We keep a few APM-specific fields that may cause mapping conflicts as flattened for now.
Object-type fields:
- `http.request.env.*`
- `http.request.cookies.*`
- `http.request.headers.*`
- `http.response.headers.*`
- `span.message.headers.*`
- `transaction.message.headers.*`
Flattened-type fields:
- `error.custom` (APM-specific arbitrary object structure)
- `error.exception.attributes` (APM-specific arbitrary object structure)
- `error.exception.stacktrace` (APM-specific structured stack trace)
- `error.log.stacktrace` (APM-specific structured stack trace)
- `http.request.body` (may be either a string or object, and object fields are arbitrary so therefore may cause …
> Revert some flattened fields to object type

- .mergify.yml
- apmpackage/apm/changelog.yml
- cmd/intake-receiver/version.go
- internal/version/version.go
Merge as soon as 8.12 branch was created. Auto-merge is not yet supported, see https://github.com/Mergifyio/mergify-engine/discussions/2821
> backport: Add 8.12 branch

- docs/otel-direct.asciidoc
While reading through https://www.elastic.co/guide/en/apm/guide/current/open-telemetry-direct.html#connect-open-telemetry-collector, I noticed that the link to the `hostmetrics` receiver was broken.  This is likely due to the fact that the `hostmetrics` receiver was part of the vanilla OTel Collector distribution up through `v0.33.0` but was then moved to the `opentelemetry-collector-contrib` repository.
This PR updates the link for the `hostmetrics` receiver to point to its new location, in the `opentelemetry-collector-contrib` repository.
> [Docs][OTel] Fix link to hostmetrics receiver

- changelogs/8.11.asciidoc
Adds 8.11.3 release notes. I don't think there's a single new commit. BC: https://github.com/elastic/apm-server/commits/cba21e88bd0d376ec77dc77fccccfdc0c27206ac.
> Add 8.11.3 release notes

- NOTICE.txt
- go.mod
- go.sum
*Changeset*
* https://github.com/elastic/beats/commit/5c256faa5821
---
<Actions>
<summary>Update to elastic/beats@ce367ff5456d</summary>
<p>ran shell command &#34;.ci/scripts/update-beats.sh ce367ff5456d&#34;</p>
</details>
<a href="https://github.com/elastic/apm-server/actions/runs/7210651806">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
> [updatecli] Update to elastic/beats@5c256faa5821

- docker-compose.yml
- testing/infra/k8s/base/stack/apm-server.yaml
- testing/infra/k8s/base/stack/elasticsearch.yaml
- testing/infra/k8s/base/stack/kibana.yaml
Bump elastic stack version to 8.13.0-h30gube9
---
<Actions>
<p>1 file(s) updated with &#34;$1:8.13.0-h30gube9-SNAPSHOT&#34;:&#xA;&#x9;* docker-compose.yml&#xA;</p>
</details>
<p>3 file(s) updated with &#34;version: 8.13.0-h30gube9-SNAPSHOT&#34;:&#xA;&#x9;* testing/infra/k8s/base/stack/apm-server.yaml&#xA;&#x9;* testing/infra/k8s/base/stack/elasticsearch.yaml&#xA;&#x9;* …
> [updatecli] Bump elastic stack version to 8.13.0-h30gube9

- internal/beater/beater.go
- internal/beater/beatertest/server.go
- internal/beater/checkintegration.go
- internal/beater/server_test.go
- internal/beater/waitready.go
Revert https://github.com/elastic/apm-server/pull/12150 -- see https://github.com/elastic/apm-server/issues/12239
> Revert "Revise wait_for_integration ES implementation (#12150)"

- packaging/ironbank/hardening_manifest.yaml
> Remove Nassim Kammah from list of ironbank maintainers

- systemtest/otlp_test.go
We recently introduced OTLP partial success response support in #11883. This PR adds a test case for OTLP metrics to ensure we are responding using a PartialSuccess.
Note that this test rely on triggering a partial response from the server by sending malformed Exponential Histogram data.
Run systemtests, verify that `TestOTLPGRPCMetrics_partialSuccess` passes.
Ref: https://github.com/elastic/apm-server/issues/12226
> add test for OTLP metrics partial success response

- docs/getting-started-apm-server.asciidoc
After 8.5.0, the file name was changed from install-service-apm-server.ps1 to install-service.ps1, but it was not modified in the document. I corrected an incorrect filename in the documentation for Windows.
> docs: fix incorrect filenames in a document for Windows

- script/update_go_version.sh
Recent changes in the docs removed the versions.asciidoc. 
Let's support it only if the file exists.
> auto-bump: docs/version.asciidoc does not exist

- Makefile
Recent changes in the docs removed the versions.asciidoc.
Let's support it only if the file exists.
> updatecli: 7.17 uses a different approach

- changelogs/head.asciidoc
- internal/beater/middleware/log_middleware.go
- internal/beater/middleware/log_middleware_test.go
- internal/beater/request/context.go
- internal/beater/request/context_test.go
If Content-Length is not -1, report that in http.request.body.bytes, otherwise report the number of bytes read from the body. This can be useful for monitoring the rate of bytes ingested, even when agents use chunked encoding to stream data to the server.
1. Using `curl` send some requests to `/intake/v2/events`, with and without `Tranfer-Encoding: chunked`
2. Verify that the HTTP request logs report the request body size is reported correctly
None
> Log number of bytes read from HTTP request body

- x-pack/apm-server/sampling/eventstorage/storage.go
Tail-based sampling: Fix a case where entry TTL was not set after encountering badger.TxnTooBig.
This is an edge case which is hard to test. The change should be easy enough to reason.
Closes #12449
> TBS: Fix missing TTL after badger.ErrTxnTooBig

- release.mk
Update-docs was not enabled in the patch releases.
> release(patch): support for docs updates

- .github/workflows/run-patch-release.yml
* patch releases should use the `release.mk` file  in the `release` branch
* minor releases should use the makefile in the `main` branch, there is a caveat that the make goals might differ between branches defined in `release.mk`
For the latter, I need to figure out whether to use a cloned repository in a different location, but for now, any changes in the `release.mk` should be backported to any of the active branches.
> release(patch): use the makefile defined in the release branch

- apmpackage/apm/changelog.yml
- apmpackage/apm/data_stream/sampled_traces/fields/base-fields.yml
- apmpackage/apm/data_stream/service_destination_interval_metrics/fields/fields.yml
- apmpackage/apm/data_stream/service_summary_interval_metrics/fields/fields.yml
- apmpackage/apm/data_stream/service_transaction_interval_metrics/fields/fields.yml
- apmpackage/apm/data_stream/transaction_interval_metrics/fields/fields.yml
Define value for all `constant_keyword` fields in apmpackage to workaround Fleet upgrade bug. Under certain conditions, it is possible that apmpackage upgrade creates a lot of indices if constant_keyword does not have a value.
Targeting 8.12 branch because apmpackage has been moved to https://github.com/elastic/integrations/tree/main/packages/apm/data_stream on main.
- Ingest APM data, upgrade package to a version that contains the fix, and verify that DS rollover is successful and mapping contains a value for constant keyword fields.
Closes #12159
> Define value for all constant_keyword fields in apmpackage

- release.mk
Simplify the patch releases for the `7.17` branch a bit, so it uses the input parameter from the GitHub action, and the input parameter should match the latest available `7.17` release rather than the upcoming new version!
I also enabled `BASE_BRANCH` so I can override the base branch when running the script locally.
If `7.17.18` was hypothetically the new release then:
```bash
$ make patch-release RELEASE_VERSION=7.17.18 PROJECT_OWNER=v1v BASE_BRANCH=fix/avoid-crrent-latest-release
```
Produced: https://github.com/v1v/apm-server/pull/40
When running https://github.com/elastic/apm-server/actions/workflows/run-patch-release.yml then use the release version.
- Is its use being …
> release(patch): use RELEASE_VERSION that points to the latest release

- catalog-info.yaml
Leverage the tags and consumesApi to help with knowing what services are consumed by the Buildkite pipeline for the DRA.
> backstage: add tags and consumesApi

- catalog-info.yaml
Reverts elastic/apm-server#12497
Unfortunately the current backstage implementation does not support all the YAML syntax in https://backstage.io/docs/features/software-catalog/descriptor-format/
so `consumesApis` is not supported in resources but in components.
Hence I'll revert this
> Revert "backstage: add tags and consumesApi"

- .github/workflows/update-dependabot-pr.yml
Dependabot Pull Requests are not updating the NOTICE.txt file, which causes the lint job to fail.
This workflow will checkout the dependabot PR, update the NOTICE.txt file, and push the changes back to the PR.
> Fix dependabot PRs

- .github/workflows/update-dependabot-pr.yml
It's actually not needed. Updating the PR with main was enough to trigger the workflow in existing PRs.
> Remove workflow_dispatch trigger from update-dependabot-pr workflow

- changelogs/8.12.asciidoc
See https://github.com/elastic/kibana/issues/175254
Part of #12498
> changelog: add fleet ingest pipeline breaking change

- .ci/update-beats.yml
The backport automation somehow added an extra condition:
- https://github.com/elastic/apm-server/pull/12277/
Likely a missing backport, see https://github.com/elastic/apm-server/commits/main/.ci/update-beats.yml
> updatecli: remove duplicated condition

- .ci/packaging.groovy
Enable the apmpackage v2 and support for manual UI interactions
> jenkins: support apmpackage when running a build through the UI

- .github/workflows/check-docker-compose.yml
Run `check-docker-compose` for all the active branches in the APM Server (`main`, `7.17` and `8.12` now)
See this [build](https://github.com/elastic/apm-server/actions/runs/7888014145) that ran this PR to validate it works as expected
> ci(check-docker-compose): run for all the active branches

- release.mk
> As of 8.12, most documentation source files have moved to the [elastic/observability-docs](https://github.com/elastic/observability-docs) repo and been integrated into the Observability guide ([docs/en/observability/apm/](https://github.com/elastic/observability-docs/tree/main/docs/en/observability/apm)).
Hence, the automation for creating a new minor does not need to support the docs.
> ci(minor): docs are not in this repository anymore

- changelogs/8.12.asciidoc
Pull apmpackage constant_keyword entry from 8.12.1 changelog. The fix did not go into 8.12.1 due to automation issues. See #12219
> changelog: Remove apmpackage constant_keyword fix from 8.12.1

- x-pack/apm-server/sampling/eventstorage/storage_whitebox_test.go
Add a whitebox test for ErrTxnTooBig handling in TBS storage. Existing storage_test.go is in a separate package, making it unable to access private fields under ReadWriter.
Useful to verify https://github.com/elastic/apm-server/pull/12509
> test: Add TBS whitebox test for ErrTxnTooBig handling

- x-pack/apm-server/sampling/processor.go
Return a better error for clearer "tail sampler aborted" log
- start apm-server with tbs enabled
- go into data directory, truncate the subscriber position file
- start apm-server again
- expect to see `{"log.level":"error","@timestamp":"2024-03-04T11:31:57.906Z","log.logger":"beater","log.origin":{"function":"main.runServerWithProcessors.func1","file.name":"apm-server/main.go","file.line":207},"message":"tail sampler aborted","service.name":"apm-server","error":{"message":"error parsing subscriber position file: unexpected end of JSON …
> Better logs on reading TBS subscriber position

- .github/workflows/benchmarks.yml
I ran the benchmarks workflow on a branch, and noticed that it did not build a custom Docker image, despite me not checking the "Run the benchmarks on the latest stable version" box. On the other hand, the scheduled runs do build a custom Docker image.
After digging, I found this in the Github Actions docs (https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs):
> The workflow will also receive the inputs in the github.event.inputs context. **The information in the inputs context and github.event.inputs context is identical except that the inputs context preserves Boolean values as Booleans instead of converting them to strings.** The choice type resolves to a string and is a single selectable option.
We …
> .github: fix benchmark workflow

- changelogs/7.17.asciidoc
Adds changelogs for new release `v7.17.19` ([no significant changes found](https://github.com/elastic/apm-server/compare/v7.17.18...7.17))
Adds missing changelogs for `v7.17.18` ([no significant changes found](https://github.com/elastic/apm-server/compare/v7.17.17...v7.17.18))
> [7.17.19] Add release notes

- cmd/intake-receiver/version.go
- internal/version/version.go
Not entirely sure if this should have been done by automation or if I needed to trigger a job. I have created an issue for documenting how to use the automation/CI steps: https://github.com/elastic/apm-server/issues/12864
> Bump up version to 8.13.1

- changelogs/head.asciidoc
* https://github.com/elastic/apm-data/issues/200:
* spin up any test application with any OTel-agent
* Add `telemetry.distro.name` and `telemetry.distro.version` as resource-attributes. E.g. use the environment variable `OTEL_RESOURCE_ATTRIBUTES=telemetry.distro.name=mydistro,telemetry.distro.version=myversion`
* Verify that the resulting traces (or metrics) have `agent.name` set to `opentelemetry/<language>/mydistro` and `agent.version` is `myversion`
* Alternative: Directly send dummy data to the OTLP intake with those resource attributes set
* https://github.com/elastic/apm-data/issues/187
* Use existing dummy data for an IntakeV2 request for generating a transaction
* Add [system.host_id](https://github.com/elastic/apm-server/blob/main/docs/spec/v2/metadata.json#L444) with a value …
> Added changelog for apm-data upgrade to 1.1

- .ci/bump-golang.yml
- .github/workflows/ci.yml
- go.mk
- packaging.mk
- packaging/docker/Dockerfile
Avoid an explicit hardcoded value in the `Dockerfile` but honour the `.go-version` content. For such, the `GOLANG_VERSION` is created on the fly when running `make package*`
This helps reduce the steps when bumping the Golang version and the chances that something goes side-ways like it happened to me recently, and I needed to create a new follow-up:
- https://github.com/elastic/apm-server/pull/12969
I also enabled `make package-snapshot` as part of the CI to help detect breaking changes before merging. Otherwise, we only detect them when the DRA runs in Buildkite.
- Have system tests been added to …
> package: honour `.go-version` content when creating docker images

- .mergify.yml
- CHANGELOG.asciidoc
- changelogs/8.14.asciidoc
- changelogs/head.asciidoc
- cmd/intake-receiver/version.go
- internal/version/version.go
Merge as soon as the GitHub checks are green.
> 8.14: update docs, mergify, versions and changelogs

- .github/workflows/run-minor-release.yml
- .github/workflows/run-patch-release.yml
User finer-grained token to create a new minor branch or raise a Pull Request.
Use the GitHub action token with the correct scope, but any PRs won't trigger any build. So reviewers will need to close and re-open the PR. @elastic/obs-ds-intake-services , what do you think?
Pros:
- Fully supported with GitHub actions.
- No need to maintain a finer-grained token that needs to be rotated every X days/weeks 
Cons:
- Reopen PRs.
> github-action: use finer-grained token

- cmd/intake-receiver/version.go
- internal/version/version.go
- systemtest/approvals/TestOTLPGRPCLogsClientIP.approved.json
I had to change the assertions for geoip due to failures of the test case. I have opened an issue to take a look at how we can deal with this flakiness: https://github.com/elastic/apm-server/issues/13073
> Bump up version to 8.13.4

- .github/workflows/run-patch-release.yml
Leftover only in `main`. GitHub does not support signed pushes.
> github-action: gpg sign for push is not supported

- .ci/bump-elastic-stack-snapshot.yml
- .github/workflows/bump-elastic-stack.yml
Leverage https://github.com/updatecli/updatecli/issues/1914 and support [commit signature verifications](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification)
I tested it in a playground:
- https://github.com/v1v/updatecli-demo/pull/43/commits
And also in my fork, for such I used this set of changes and tweaked a [bit](https://github.com/v1v/apm-server/pull/42) my main branch,
Then https://github.com/v1v/apm-server/pull/43/commits was created
Then if it works as expected in the CI, changes …
> updatecli: verify commits

- .ci/bump-golang.yml
- .ci/update-beats.yml
- .github/workflows/bump-elastic-stack.yml
- .github/workflows/bump-golang.yml
- .github/workflows/update-beats.yml
Leverage https://github.com/updatecli/updatecli/issues/1914 and support [commit signature verifications](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification)
Similar to https://github.com/elastic/apm-server/pull/13103
> updatecli: verify commits for golang and beats

- docker-compose.yml
> docker-compose: remove xpack.apm_data.enabled

- cmd/intake-receiver/version.go
- internal/version/version.go
Bump `8.14` to `8.14.` to prepare for the next release as required by release docs.
> Bump 8.14 to 8.14.1

- .github/workflows/ci.yml
This should help with PRs coming from dependabot. Otherwise, the CI will fail, see https://github.com/elastic/apm-server/pull/13322
> ci: exclude github secret access if dependabot

- .github/workflows/prepare-release/action.yml
- .github/workflows/run-minor-release.yml
- .github/workflows/run-patch-release.yml
`RELEASE_TYPE` is an env variable required when running the release steps. Defaulted to `minor` and that's the reason it didn't work with the `run-patch-release`.
> ci: fix type of release

- cmd/intake-receiver/version.go
- internal/version/version.go
Bump `8.14` branch to `8.14.2`
To be merged after `8.14.1` release.
> Bump 8.14 to 8.14.2

- .github/workflows/smoke-tests-schedule.yml
permissions need to be set explicitly when calling other workflows even if those workflows already have got the permissions set.
Fixes
```
[Invalid workflow file: .github/workflows/smoke-tests-schedule.yml#L27](https://github.com/elastic/apm-server/actions/runs/9672905228/workflow)
The workflow is not valid. .github/workflows/smoke-tests-schedule.yml (Line: 27, Col: 3): Error calling workflow 'elastic/apm-server/.github/workflows/smoke-tests-os.yml@4cf627cb98d0624f5206dfbfa30f88f64794c739'. The nested job 'smoke-tests-os' is requesting 'id-token: write', but is only allowed 'id-token: none'.
```
See https://github.com/elastic/apm-server/actions/runs/9672905228
- Is its use being …
> ci(smoke-tests): set id-token when running other workflows

- .github/workflows/prepare-release/action.yml
- .github/workflows/run-minor-release.yml
- .github/workflows/run-patch-release.yml
- dev_docs/RELEASES.md
* Use `v1` version for `oblt-actions`
* Use `oblt-actions` rather than `apm-pipeline-library` <-- it's now deprecated
* Update the description so it explicitly explains the expected input parameter.
The `release.mk` is the one in charge of doing the `auto-bump`:
- for the patch release: https://github.com/elastic/apm-server/blob/0e77c56738a559900f37b8f37e1ec02e43239d36/release.mk#L45
- for the minor release: https://github.com/elastic/apm-server/blob/0e77c56738a559900f37b8f37e1ec02e43239d36/release.mk#L44
* `.github/workflows/run-patch-release.yml` should be run using the `main` branch and the version to be released.
* `.github/workflows/run-minor-release.yml`  should be run using the `main` branch and the current version in `main`.
- Is it observable …
> ci(release): update descriptions and use oblt-actions@v1

- x-pack/apm-server/sampling/eventstorage/storage.go
Slightly reduce allocs in WriteTraceEvent and DeleteTraceEvent. Perf gain is insignificant.
```
goos: linux
goarch: amd64
pkg: github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage
cpu: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
│  before.out  │              after.out              │
│    sec/op    │    sec/op     vs base               │
ShardedWriteTransactionUncontended-16          152.1n ± 13%   152.0n ±  9%        ~ (p=0.729 n=6)
ShardedWriteTransactionContended-16            903.4n ±  2%   888.8n ±  1%   -1.62% (p=0.015 n=6)
WriteTransaction/proto_codec-16                672.4n ±  6%   613.6n ±  2%   -8.74% (p=0.002 n=6)
WriteTransaction/proto_codec_big_tx-16         1.728µ ±  6%   1.643µ ±  1%   -4.95% (p=0.002 n=6)
WriteTransaction/nop_codec-16 …
```
> TBS: perf: Reduce allocs slightly in write and delete

- x-pack/apm-server/sampling/eventstorage/storage.go
- x-pack/apm-server/sampling/processor.go
- x-pack/apm-server/sampling/processor_test.go
Pool APMEvent struct in ReadTraceEvents for ~20% perf gain.
Benchmarks (with uncommitted benchmark change):
```
diff --git a/x-pack/apm-server/sampling/eventstorage/storage_bench_test.go b/x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
index 3c5bafcf1..c86898bc8 100644
--- a/x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
+++ b/x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
@@ -128,6 +128,9 @@ func BenchmarkReadEvents(b *testing.B) {
count, len(batch),
))
}
+					for i := range batch {
+						batch[i].ReturnToVTPool()
+					}
}
})
}
```
Benchstat:
```
goos: linux
goarch: amd64
pkg: github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage
cpu: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
│ before-pool.out │           after-pool.out …
```
> TBS: perf: Pool APMEvent in sampling decision handler

- .ci/bump-golang.yml
- .github/workflows/bump-golang.yml
7.17 branch uses a different go-version, let's enable the auto-bump
Locally using the `updatecli` or in the CI using a feature branch:
- https://github.com/elastic/apm-server/actions/runs/9779430585
But it requires to checkout the 7.17 branch too, so we need to test it out after merging it
> udpatecli: support bump golang for 7.17

- changelogs/head.asciidoc
- internal/beater/beater.go
- internal/beater/beater_test.go
Updates the `FlushBytes` setting to default to 1 mib and only override to 24kb if the user has explicitly set it to 24kb.
1. Spin up an APM Server and send data to it (without this fix).
2. Look at the request length for Elasticsearch requests and verify they're smaller than 50kb and very close to 24kb (26kb)
3. Now start apm sever with the code in this PR and send data to it
4. Verify that the flush size is significantly higher than before and if you sent enough data it should be ~1MB.
Fixes #13024
> fix: Update `FlushBytes` parsing/defaults

- .ci/bump-golang.yml
`7.17` uses https://github.com/elastic/golang-crossbuild
https://github.com/elastic/golang-crossbuild/pull/420# was not merged therefore the packaging pipeline failed.
I added the feature branch in the name of the updatecli pipeline to help with creating a branch staring with `feature/` in the upstream, then the buidlkite pipeline should be triggered automatically, see https://github.com/elastic/apm-server/blob/44004265ef5825ada0ccd5f5365789943a7266e7/catalog-info.yaml#L44
> updatecli(golang): use golang-crossbuild

- .github/workflows/benchmarks.yml
Should fix the token duration expiration issues: https://github.com/elastic/apm-server/actions/runs/9797871743/attempts/1
> benchmarks: Increase AWS token duration to `5h`

- changelogs/head.asciidoc
- internal/beater/beater.go
- internal/beater/beater_test.go
Updates the APM Server to automatically retry document-level `429`s from Elasticsearch to avoid dropping data. It can be configured/overwritten by `output.elasticsearch.max_retries`, and defaults to `3`.
It uses the default backoff configuration, which could wait up to 1m if enough retries are configured, but can be overwritten as well.
This reduces data loss whenever Elasticsearch is overhelmed and reduces the chances of data loss due to ES push-back.
This may need a bit of setup. It's thoroughly tested in the `go-docappender`, but we may want to verify that retries happen when document-level 429s happen.
I'd suggest writing a small "proxy" that returns 429s randomly and test that things are indexed (as duplicates).
Closes #13619
> output: Retry document-level `429`s by default

- testing/benchmark/Makefile
Benchmark fails with the following error message:
```
go: open tools/go.mod: no such file or directory
cat: write error: Broken pipe
```
This is caused by specifying the wrong path for the target file; the working directory is `apm-server/testing/apmbenech` and the target file is in `apm-server/tools/go.mod`
```
make[1]: Entering directory '/home/runner/work/apm-server/apm-server/testing/benchmark'
```
fix it by specifying the correct path for the `tools/go.mod` file by using `GITROOT`:
https://github.com/elastic/apm-server/blob/ab4b728811ea24923064b8a6d9218cdc7acbb0d9/go.mk#L6
- Have system tests been …
> fix: specify correct path for tools/go.mod when running benchmark 

- cmd/intake-receiver/version.go
- internal/version/version.go
Release of 8.14.3 today requires a new patch version to be prepared.
> Bump up version to 8.14.4

- .github/workflows/update-dependabot-pr.yml
dependabot PRs still are getting empty commits when merging the main branch into it.
From what I understand `git diff` behaves differently if it's a merge commit. But I could not get it working with `git diff`.
Hence, I'm replacing the command with `git status --porcelain` + `grep`. I was able to reproduce and test it in my fork https://github.com/reakaleek/apm-server/actions/runs/10290457526/workflow?pr=22#L31. 
> dependabot: use git-status instead of git-diff

- cmd/intake-receiver/version.go
- internal/version/version.go
Release of 8.15.0 today requires bumping the versions to 8.15.1
> Bump up version to 8.15.1

- changelogs/8.15.asciidoc
APM-Server switched from Index Lifecycle Management(ILM) to Datastream Lifecycle (DSL) in v8.15.0. This switch was done when we moved from APM integration (which used ILM) to APM-data plugin (which uses DSL) in ES for managing APM datastreams. As a result of the switch, any old datastreams created before the switch would be `Unmanaged` because the datastream will never be updated with the DSL lifecycle -- this has to be done manually by using the [PUT API](https://www.elastic.co/guide/en/elasticsearch/reference/current/tutorial-manage-existing-data-stream.html).
1. Create a stack (ES, Kibana, APM-Server) with data-persistence enabled for ES using `8.14.3` version. We use the `8.14.3` as that is the latest available version which uses APM integration package and thus configures ILM …
> Add changelog for fallback to ILM if DSL not present

- internal/agentcfg/elasticsearch.go
- Fixed broken APM Agents configuration cache
APM Agents configuration cache appears to be broken, resulting frequent invalid requests made by APM Server to Elasticsearch cluster.
1. Deploy Elastic Stack: Elasticsearch, Kibana, APM Server.
2. Configure self-instrumentation for APM Server
3. Open Kibana/APM
4. Check APM Server has no failed operations of type "Elasticsearch: POST .apm-agent-configuration/_search" for Elasticsearch dependency
closes [#13957](https://github.com/elastic/apm-server/issues/13957)
> Fix ScrollID used for retrieval of APM Agents configuration

- apmpackage/apm/changelog.yml
- apmpackage/apm/manifest.yml
- cmd/version.go
> Bump version to 7.17.25

- .github/workflows/smoke-tests-ess.yml
- .github/workflows/smoke-tests-os.yml
for such it requires to listen for workflow_dispatch and then use the inputs
As requested, team need to run the smoke tests in isolation in the CI to validate if changes work as expected.
The current pattern didn't allow to do so... this should help them
> ci: support running smoke tests using the GitHub UI

- .github/workflows/run-minor-release.yml
- .github/workflows/run-patch-release.yml
Use ephemeral tokens , similarly done in https://github.com/elastic/apm-server/pull/14010
> ci: use ephemeral tokens instead of APM_SERVER_RELEASE_TOKEN

- systemtest/cmd/apmbench/main.go
In benchmarks workflow apm-perf occasionally goes OOM, this change sets memory limit to 90% of host memory to prevent OOM happening again. 
> benchmarks: add SetMemoryLimit to apmbench so it doesn't go OOM

- .github/workflows/benchmarks.yml
- systemtest/benchtest/profiles.go
- testing/benchmark/Makefile
This PR addresses the issue https://github.com/elastic/apm-server/issues/14255, by applying some quick optimization to how CPU profiles are collected for PGO. It reduces total collection time to 5% and strips unnecessary data such as tags and profile memory addresses that don't affect PGO. 
https://github.com/elastic/apm-server/issues/14255
https://github.com/elastic/apm-server/pull/13884
> PGO: optimize collected profile file size

- .github/workflows/benchmarks.yml
- .github/workflows/smoke-tests-ess.yml
Trying to solve 'partially' the below error:
```
api error: root.unauthenticated: The supplied authentication is invalid
```
The benchmarks ran, but the API token was rotated during the execution. This can help with refreshing it since benchmarks can take 4 hours or so... so we don't know if the secret is rotated meanwhile.
> ci(benchmarks): read secrets for running the tear-down immediately after

- .github/workflows/benchmarks.yml
The benchmarks workflow does not clean up all the resources it's creating.
In this [workflow run](https://github.com/elastic/apm-server/actions/runs/11183981002) you can see that the [Spin up benchmark environment](https://github.com/elastic/apm-server/actions/runs/11183981002/job/31093763569#step:15:729) step creates 22 resources.
But the [Teardown benchmark environment](https://github.com/elastic/apm-server/actions/runs/11183981002/job/31093763569#step:30:381) only deletes 9 resources.
The reason for it is the differently passed `TF_VAR_*` environment variables in both steps.
This change fixes it and aligns the passed tf vars to both apply and destroy.
- Is its use being …
> ci: fix benchmarks cleanup

- internal/beater/middleware/monitoring_middleware_test.go
This PR adds concurrency test for the fix from https://github.com/elastic/apm-server/pull/14335.
Test results from v8.15.2
```
=== RUN   TestMonitoringHandler
=== RUN   TestMonitoringHandler/Parallel
==================
WARNING: DATA RACE
Read at 0x00c000127050 by goroutine 24:
runtime.mapassign_fast64ptr()
...
...
...
Previous write at 0x00c000127050 by goroutine 23:
runtime.mapaccess2_faststr()
...
...
...
Goroutine 24 (running) created at:
...
...
...
Goroutine 23 (finished) created at:
...
...
...
==================
```
Test results from main
``` …
```
> tests: Add parallel monitoring middleware test

- testing/benchmark/variables.tf
The old `gcp-compute-optimized-v3` template seems to be deprecated according to [doc](https://www.elastic.co/guide/en/cloud/current/ec-regions-templates-instances.html) and no longer supported see the [run](https://github.com/elastic/apm-server/actions/runs/11633239770/job/32397978828). This PR updates the benchmarks ESS template to use `gcp-cpu-optimized` instead.
> benchmarks: move to gcp-cpu-optimized template

- changelogs/8.15.asciidoc
Changelog entry for upcoming 8.15.4
> changelog for 8.15.4

- changelogs/8.15.asciidoc
Align changelog entries that were not backported, as they were only added to 8.x but not 8.15 branch.
> changelog: add missing 8.x entries

- dev_docs/RELEASES.md
documentation release docs says the PR should be merged the day before release
align the docs
> docs: update release doc around documentation PR

- testing/benchmark/main.tf
- testing/infra/terraform/modules/rally_workers/main.tf
- testing/infra/terraform/modules/soaktest_workers/main.tf
- testing/infra/terraform/modules/soaktest_workers/provider.tf
Adds the apm-server prefix to the benchmarks project tag to facilitate filtering for project.
> terraform: add apm-server prefix to benchmarks

- CHANGELOG.asciidoc
In https://github.com/elastic/apm-server/pull/14929, the 8.17 changelog was added to the `main` branch, but it is not referenced in the `CHANGELOG.asciidoc` file, so it's not being built in [the docs](https://www.elastic.co/guide/en/observability/master/apm-release-notes.html).  
This is blocking https://github.com/elastic/observability-docs/pull/4667. 
View the docs preview after it's done building:
https://github.com/elastic/apm-server/pull/14929
> [docs] Add references to the 8.17 changelog in CHANGELOG.asciidoc

- .github/workflows/benchmarks.yml
- testing/benchmark/main.tf
- testing/benchmark/variables.tf
- testing/infra/terraform/modules/ec_deployment/README.md
- testing/infra/terraform/modules/ec_deployment/deployment.tf
- testing/infra/terraform/modules/ec_deployment/scripts/enable_expvar.tftpl
- testing/infra/terraform/modules/ec_deployment/scripts/enable_features.tftpl
- testing/infra/terraform/modules/ec_deployment/variables.tf
Update testing/benchmark terraform and github workflow to add an option to enable TBS.
Run testing/benchmark terraform locally
Related to #11346 . This should enable reproducible benchmarks on cloud.
> Add option to enable TBS in benchmark terraform

- systemtest/approvals/TestRUMXForwardedFor.approved.json
- systemtest/rum_test.go
Mark client.geo.{city_name,location,region_iso_code,region_name} as dynamic in TestRUMXforwardedFor. This will make it consistent with other systemtest approvals.
Fix failing test:
```
=== Failed
=== FAIL: systemtest TestRUMXForwardedFor (1.54s)
rum_test.go:73:   []any{
map[string]any{
... // 2 identical entries
"agent.name.text":             []any{string("rum-js")},
"agent.version":               []any{string("5.5.0")},
- 		"client.geo.city_name":        []any{string("Perth")},
+ 		"client.geo.city_name":        []any{string("Melbourne")},
"client.geo.continent_name":   []any{string("Oceania")},
"client.geo.country_iso_code": []any{string("AU")},
"client.geo.country_name":     []any{string("Australia")},
"client.geo.location":         []any{string("dynamic")},
- …
```
> Mark most client.geo.* as dynamic in TestRUMXForwardedFor approvals

- systemtest/benchtest/expvar/expvar.go
- systemtest/benchtest/expvar/metrics.go
- systemtest/benchtest/main.go
- systemtest/benchtest/main_test.go
Record TBS lsm size and vlog size in benchtest to facilitate TBS improvements when running benchmarks using gh actions following #14985 
Meta issue #14931
> Record tbs disk usage stats in benchtest

- .github/workflows/benchmarks.yml
A regression from #14985 causing nightly benchmark to fail.
The root cause of regression was that scheduled GH actions ignore `workflow_dispatch` defaults.
> Fix TF_VAR_apm_server_tail_sampling for scheduled gh actions

- internal/beater/monitoringtest/monitoring.go
Current CompareMonitoringInt is missing assertions on IDRequestCount, IDResponseCount, IDResponseErrorsCount, IDResponseValidCount. Add them back.
Discovered while working on https://github.com/elastic/apm-server/pull/15123
> test: Fix missing assertions for default result IDs in monitoringtest

- packaging/files/windows/install-service.ps1
Update the installer script to use PROGRAMFILES placeholder.
* deploy APM Server installation on a Windows host
* verify the installation directory is `C:\Program Files`
> Win: install APM Server in Program Files directory

- docs/spec/v2/span.json
`make check-full` is failing on 8.17 and 8.16 branch due to `docs/spec/v2/span.json`. The `docs/spec/v2/span.json` in 8.16 and 8.17 branch is actually newer than what it should be.
> [8.17] Fix CI failure due to docs/spec/v2/span.json

- .github/workflows/mergify-labels-copier.yml
Help with copying the GitHub labels for the backported PRs created by Mergify.
Requires https://github.com/elastic/oblt-actions/pull/207
> github-actions: support for copying the backport labels

- .buildkite/scripts/dra.sh
https://github.com/elastic/apm-server/pull/15274 introduced the regression, but it seems the DRA does not honour those variables when using the `list` instead of `collect` action, hence the BK Pipelien that got triggered didn't catch that error.
They should be masked, so we are good to use `set -x`. Unfortunately we need to use the suffix SECRET to mask and then the name of the variables cannot be changed
> ci(dra): fix Vault variables

- .buildkite/scripts/dra.sh
- Makefile
When introducing the `qualifier`, the version changed. This should help keep the expected behaviour and use a new target goal to avoid the qualifier in the name.
In the CI:
1) `dry-run mode` without `qualifier` -> https://buildkite.com/elastic/apm-server-package/builds/3707
2) `dry-run mode` with `qualifier` -> https://buildkite.com/elastic/apm-server-package/builds/3708
> ci(dra): version should not include the qualifier

- functionaltests/TestUpgrade_8_15_4_to_8_16_0/main.tf
- testing/cloud/main.tf
The current CI integration with the Terraform `ec_deployment` uses OIDC; hence, it uses the robots automation, but unfortunately, if `ephemeral:true` is not set and the `tear-down` steps fail in the CI, those resources are not deleted automatically but manually.
We want to enforce using `ephemeral:true` in all the Terraform resources using `ec`, the `ephemeral:true` was added as part of https://github.com/elastic/apm-server/pull/14179
But I didn't see the `tags` to be set for the `cloud` and `functional tests` that run in the CI or can run.
> terraform: add tags module

- testing/benchmark/main.tf
- testing/benchmark/terraform.tfvars.example
- testing/benchmark/variables.tf
- testing/infra/terraform/modules/standalone_apm_server/README.md
- testing/infra/terraform/modules/standalone_apm_server/apm-server.yml.tftpl
- testing/infra/terraform/modules/standalone_apm_server/elastic-agent.yml.tftpl
- testing/infra/terraform/modules/standalone_apm_server/main.tf
- testing/infra/terraform/modules/standalone_apm_server/variables.tf
Support TBS in testing/infra/terraform/modules/standalone_apm_server
Run `testing/benchmark` with tfvars
```
apm_server_tail_sampling = true
apm_server_tail_sampling_storage_limit = "30GB"
run_standalone = true
standalone_apm_server_instance_size = "c6id.2xlarge"
worker_instance_type = "c6i.4xlarge"
standalone_apm_server_volume_type = "gp3"
standalone_apm_server_volume_size = 40
```
Output should contain a non-zero tbs_lsm_size e.g.
```
BenchmarkAgentAll-512        871         163274501 ns/op                 0 error_responses/sec        2205 errors/sec …
```
> terraform: support TBS in standalone_apm_server

- testing/infra/terraform/modules/ec_deployment/outputs.tf
A followup PR to https://github.com/elastic/apm-server/pull/15349 to fix ec_deployment data.local_sensitive_file access.
> tf: fix ec_deployment terraform module

- testing/benchmark/Makefile
As the old apm-perf dependency in apm-server systemtest defaults to
disable rewriting while the latest apm-perf defaults to true, do not
rely on the defaults and always specify -rewrite-timestamps and
-rewrite-ids in make run-benchmark.
Required to correctly benchmark #15235
> Always rewrite timestamps and IDs in run-benchmark

- testing/benchmark/variables.tf
Change default benchmark standalone apm server volume type to gp3, as gp2's burstiness makes it unreliable for benchmarks.
> tf: default volume type to gp3

- internal/beater/api/mux.go
- x-pack/apm-server/main.go
- x-pack/apm-server/sampling/config.go
- x-pack/apm-server/sampling/config_test.go
- x-pack/apm-server/sampling/eventstorage/rw.go
- x-pack/apm-server/sampling/eventstorage/rw_test.go
- x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
- x-pack/apm-server/sampling/eventstorage/storage_manager.go
- x-pack/apm-server/sampling/eventstorage/storage_manager_bench_test.go
- x-pack/apm-server/sampling/eventstorage/storage_manager_test.go
- x-pack/apm-server/sampling/processor.go
- x-pack/apm-server/sampling/processor_test.go
Fix a regression from #15235 where storage_limit does not follow processor lifecycle.
Remove storage limit from processor config.
Add storage to processor config validation.
~~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)~~ Fixing a regression from an unreleased change
Should be tested along #15235 . Ensure that EA hot reload applies the new storage limit by changing the integration policy.
> TBS: make storage_limit follow processor lifecycle; update TBS processor config

- x-pack/apm-server/sampling/processor.go
Log a warning with an error field on processing trace failed.
> TBS: log a warning with error field on processing trace failed

- x-pack/apm-server/sampling/eventstorage/rw.go
Fix a missing colon in logs (typo from #15235 ), and remove "storage" in "configured storage limit reached" message to make way for #15467 to avoid confusion
> TBS: fix log formatting

- internal/kibana/client.go
- internal/kibana/client_test.go
This PR adds `x-elastic-product-origin` to Kibana API client similarly to how it's done for Elasticsearch client in https://github.com/elastic/apm-server/blob/1ea24d2176b2c09abeb5be24d5deabc67da94445/internal/elasticsearch/client.go#L94
> kibana: add x-elastic-product-origin header to the client

- testing/benchmark/main.tf
- testing/infra/terraform/modules/standalone_apm_server/main.tf
Fix a regression where benchmarking standalone apm server does not find a matching x86_64 AMI for c6i instance types.
Fixes #15604
> tf: fix benchmarking standalone apm to use x86_64 AMI by default

- testing/benchmark/system-profiles/8GBx1zone.tfvars
Doubles the worker instance size to see if it stabilizes the benchmark. The worker is currently running out of memory after 3h of running the benchmark.
> benchmark: increase worker instance size

- .github/workflows/functional-tests.yml
Functional tests have not been reliable in the last weeks. Either QA or Prod tests are failing due to https://github.com/elastic/apm-server/issues/15531
A stable resolution is not ready yet, and we are being notified of failures that are not actionable. To prevent alert fatigue, disable the scheduled run while we work on a complete resolution.
https://github.com/elastic/apm-server/issues/14100
> functionaltests: disable scheduled run

- testing/smoke/basic-upgrade/test.sh
- testing/smoke/lib.sh
Fixing smoke tests `basic-upgrade` that is failing fetching a negative minor version from the ECH API.
```
-> unspecified version, using 9.0
-> Running basic upgrade smoke test for version 9.0.0
-> Adding tfvar stack_version="9.-1.0"
```
Introduce a new function in smoke tests `lib.sh` to fetch the full latest version of a given prefix.
Use that function to populate the previous major latest minor.patch.
> CI(smoketest): fetch previous version on first minor

- packaging/docker/Dockerfile
Similar to https://github.com/elastic/apm-server/pull/15788 but different kerberos lib
we don't need/use it. Remove it to avoid noisy alerts
> feat: purge more noisy kerberos libs from docker image 

- internal/beater/server_test.go
I resolved conflict wrongly in backport PR: https://github.com/elastic/apm-server/pull/15978.
> Fix Backport 8.18 PR 15948

- internal/beater/server_test.go
I resolved conflict wrongly in backport PR: https://github.com/elastic/apm-server/pull/15979.
> Fix Backport 8.17 PR 15948 

- internal/beater/server_test.go
I resolved conflict wrongly in backport PR: https://github.com/elastic/apm-server/pull/15980.
> Fix Backport 8.16 PR 15948

- testing/smoke/main.tf
Fix terraform changes introduced in https://github.com/elastic/apm-server/pull/15884.
See error in smoke test: https://github.com/elastic/apm-server/actions/runs/13645441445/job/38143422753
```
-> Running ./testing/smoke/basic-upgrade smoke tests for version 8.18...
Error: Unreadable module directory
Unable to evaluate directory symlink: lstat ../infra: no such file or
directory
Error: Unreadable module directory
The directory  could not be read for module "tags" at main.tf:13.
make: *** [Makefile:[31](https://github.com/elastic/apm-server/actions/runs/13649528881/job/38154767277#step:8:32)1: smoketest/run-version] Error 1
```
Run smoke test again.
> fix: Wrong source in newly added Terraform tags

- testing/benchmark/system-profiles/8GB_NVMe-x1zone.tfvars
- testing/benchmark/system-profiles/8GB_io2_6000iops-x1zone.tfvars
8GBx1zone.tfvars already uses c6i.2xlarge. Update the corresponding 8GB
NVMe and io2 profiles to use c6i.2xlarge to avoid OOM.
Follow up on #15733
> benchmark: Align 8GB profiles worker size

- docker-compose.yml
- systemtest/benchtest/main.go
Fix benchmark failure due to warmup, by reverting the change done to use `errgroup` for agents `SendBatchesInLoop`.
> bench: Don't return error for agents SendBatchesInLoop

- testing/smoke/legacy-standalone-major-managed/test.sh
- testing/smoke/lib.sh
Caused by https://github.com/elastic/apm-server/pull/16131.
Smoke test failed, missing patch:
```
-> Running 7.17. standalone to 8.18.0 standalone to 9.0.0 standalone to 9.0.0 managed
```
Run `smoke-test-ess` with this branch: https://github.com/elastic/apm-server/actions/runs/13849821727.
> smoke: Add missing patch in legacy major test

- internal/beater/interceptors/metrics.go
- internal/beater/interceptors/metrics_test.go
- internal/beater/middleware/monitoring_middleware.go
Closes https://github.com/elastic/apm-server/issues/16178.
Run `go test -run=TestMetrics_ConcurrentMapSafe -race -v -count=10 -failfast ./...` and see that there are no fatal errors.
> fix: metrics interceptor concurrent map read write

- testing/smoke/legacy-standalone-major-managed/test.sh
Closes https://github.com/elastic/apm-server/issues/16180.
Unfortunately, tests for legacy 9.x are failing and it's unlikely we will be able to fix them using the current smoke tests. Disabling the upgrade for now. Instead of 7.x -> 8.x -> 9.x, we will simply do 7.x -> 8.x for now.
We will follow up with https://github.com/elastic/apm-server/issues/16199, by using functional tests to perform the test instead.
> smoke: Temporarily disable failing 9.0 smoke test upgrade in legacy major

- functionaltests/infra/terraform/main.tf
- functionaltests/infra/terraform/tags.tf
The terraform source currently points to nowhere. After copying, it is one level up as compared to when its in `infra/terraform`.
Run functionaltests with this branch: https://github.com/elastic/apm-server/actions/runs/13899696031.
> functionaltests: Fix terraform source being wrong after copy

- testing/smoke/basic-upgrade/test.sh
- testing/smoke/legacy-standalone-major-managed/test.sh
Resolves https://github.com/elastic/apm-server/issues/16179.
Also fixes a typo in `legacy-standalone-major-managed` causing assertion failure.
Follow up: https://github.com/elastic/apm-server/issues/16277.
Run `smoke-test-ess` with this branch: https://github.com/elastic/apm-server/actions/runs/13917697551.
> smoke: Fix 9.0.0 assertion fail and legacy major typo

- docs/release-notes/breaking-changes.md
- docs/release-notes/deprecations.md
- docs/release-notes/index.md
- docs/release-notes/known-issues.md
Copies over recent release note edits from https://github.com/elastic/docs-content/pull/827 (which snuck in before I could merge https://github.com/elastic/docs-content/pull/820).
cc @KOTungseth
> [docs] Copy recent release note edits

- .github/workflows/functional-tests.yml
The functional tests in CI has been failing intermittently in QA multiple times. We should disable it for now, since running on production CFT should good enough.
```
Received unexpected error:
cannot run generator: Post "<url>": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
```
Received unexpected error:
cannot retrieve APM doc count: status: 404, failed: [shard_not_found_exception], reason: no shard copies found [.ds-metrics-apm.service_destination.1m-default-2025.03.19-000001][0]
```
```
Received unexpected error:
cannot run generator: unexpected server error: 502
```
```
failed tracking create progress: 2 errors occurred:
* found deployment plan errors: deployment [1b2206bb351a68259c067fa2e3a9277e] - …
```
> functionaltests: Disable QA env in functional tests

- functionaltests/8_16_test.go
- functionaltests/9_0_test.go
- functionaltests/basic_upgrade_test.go
- functionaltests/main_test.go
- functionaltests/single_upgrade_test.go
- functionaltests/utils_test.go
This PR introduces functional tests for build candidate (BC) versions. The previous idea of using a single `TestUpgradeBC` test to run tests for all BC versions does not work, as each version may have their own caveats, e.g. DSL vs ILM, lazy rollover, different ignored APM error logs etc.
Note: `TestUpgrade_8_14_to_8_16_Reroute` is not changed since subsequent PR to introduce reroute tests for all versions will replace it.
Run functionaltests workflow with this branch: https://github.com/elastic/apm-server/actions/runs/13989686769.
> functionaltests: Add BC tests

- go.mod
Replace directive for `goja` no longer required after [this PR](https://github.com/elastic/apm-server/pull/16344/files#r2009436501).
> Remove goja replace

- functionaltests/basic_upgrade_test.go
- functionaltests/internal/esclient/client.go
- functionaltests/main_test.go
- functionaltests/single_upgrade_test.go
Fix post-upgrade document count assertion, previously it was checking before-ingestion count vs before-upgrade count, it should be before-upgrade vs after-upgrade.
Also makes the following rename changes:
- `Datastream` -> `DataStream` for consistency
- `ApmDocCount` -> `DocCount` and `APMDataStreamsDocCount` -> `DataStreamsDocCount` since there's nothing APM related in there
- `ApmDocCount()` -> `APMDocCount` for consistency
Run functionaltests with this branch: https://github.com/elastic/apm-server/actions/runs/14060343893.
> functionaltests: Fix post-upgrade assertion

- testing/smoke/basic-upgrade/test.sh
Closes https://github.com/elastic/apm-server/issues/16277.
Latest 9.0.0 build no longer has `rc1` suffix.
> smoke: Remove temp hack

- systemtest/monitoring_test.go
the assertion was checking N >= total which only happens if N==total
the intended check was to pass if total >= N (expected).
Closes https://github.com/elastic/apm-server/issues/16517
> test(TestMonitoring): swap assertion args to fix flaky test

- docs/release-notes/index.md
- docs/release-notes/known-issues.md
Related to https://github.com/elastic/docs-content/pull/1069
Updates links to APM, Synthetics, and Uptime pages in elastic/docs-content.
> [docs] Update APM, Synthetics, Uptime links

- .mergify.yml
- release.mk
`8.x` has been renamed to `8.19`
Use default values for the backport actions/rules.
> mergify: support 8.19 and remove support 8.x

- testing/infra/terraform/modules/ec_deployment/deployment.tf
The existing implementation creates local scripts in the Terraform module directory i.e. `ec_deployment/scripts`. This means that if we were to have multiple deployments at once (for example in [functionaltests](https://github.com/elastic/apm-server/blob/main/functionaltests/utils_test.go#L54-L70) which [references `ec_deployment`](https://github.com/elastic/apm-server/blob/main/functionaltests/infra/terraform/main.tf#L2)), the scripts from each deployment would overwrite one another.
Fixed by using `path.cwd` instead of `path.module` for `ec_deployment` scripts. Closes https://github.com/elastic/apm-server/issues/16636.
Run functionaltests and benchmark workflow with this branch, to ensure they are working properly.
> Fix ec_deployment local exec provisioner error

- .github/workflows/functional-tests.yml
- functionaltests/9_x_test.go
- functionaltests/internal/gen/generator.go
- functionaltests/internal/kbclient/client.go
- functionaltests/internal/kbclient/upgrade_assist.go
- functionaltests/main_test.go
- functionaltests/steps_test.go
- functionaltests/steps_v7_test.go
Add 7.x to 8.x to 9.x test, for standalone to managed.
- 7.x standalone -> 8.x standalone -> 9.x standalone -> 9.x managed
- 7.x standalone -> 7.x managed -> 8.x managed -> 9.x managed
Closes https://github.com/elastic/apm-server/issues/16199. Requires all other functionaltests PR to be merged first.
Run functionaltest workflow with this branch: https://github.com/elastic/apm-server/actions/runs/14465245943.
> functionaltests: Add test for 7x to 8x to 9x

- x-pack/apm-server/sampling/processor_test.go
Remove meaningless line in TestReadSubscriberPositionFile to align 8.x branches and 9.x branches after backporting https://github.com/elastic/apm-server/pull/16736
> chore: minor refactor of TestReadSubscriberPositionFile

- .buildkite/package.yml
- .buildkite/scripts/package.sh
remove crossbuild for arm4 on amd64
See https://github.com/elastic/golang-crossbuild/pull/560
> fix: golang-crossbuild requires host specific for arm

- internal/publish/pub_test.go
Fix panic when benchmarking
```
[2025-05-08T12:21:20Z] panic: runtime error: invalid memory address or nil pointer dereference
[2025-05-08T12:21:20Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeb3d57]
[2025-05-08T12:21:20Z] 
[2025-05-08T12:21:20Z] goroutine 50 [running]:
[2025-05-08T12:21:20Z] github.com/elastic/elastic-agent-libs/logp.(*Logger).Named(0xc0001799c0?, {0x192d7d0?, 0x251f680?})
[2025-05-08T12:21:20Z] 	/var/lib/buildkite-agent/go/pkg/mod/github.com/elastic/elastic-agent-libs@v0.19.4/logp/logger.go:150 +0x17
[2025-05-08T12:21:20Z] github.com/elastic/beats/v7/libbeat/idxmgmt.DefaultSupport.MakeDefaultSupport.func1(...)
[2025-05-08T12:21:20Z] 	/var/lib/buildkite-agent/go/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20250505142450-af0a5dad0d45/libbeat/id …
```
> fix: properly initiate logger

- .github/workflows/integration-server-test.yml
- .github/workflows/smoke-tests-os.yml
- Makefile
- integrationservertest/internal/ech/version.go
Previous PR to remove some old smoke tests stuff failed to remove one of the steps that reference a deleted file: https://github.com/elastic/apm-server/pull/17085.
This PR removes that unnecessary step, and also fixes some workflow typo.
Run `smoke-tests-os`: https://github.com/elastic/apm-server/actions/runs/15560510766.
Run `integration-server-tests`: https://github.com/elastic/apm-server/actions/runs/15561173496.
> smoke: Fix steps using deleted action & workflow typo

- testing/smoke/os_matrix.sh
Smoke test for 8.x versions have been consistently failing because the ubuntu 18.04 OS is no longer available on AWS. 
1. Ran smoke-testd-os workflow on new branch 
Closes https://github.com/elastic/apm-server/issues/17171
> smoke: Remove ubuntu 18.04 from os_matrix.sh since it is no longer available

- internal/beatcmd/version.go
This PR enhances the output of the `version` CLI sub-command to include whether the binary is FIPS-capable or not.  FIPS-capable binaries will report `FIPS-distribution: true` in the `version` sub-command's output.
This output is consistent with the output of the `version` sub-command for Beats and Elastic Agent.
Build a non-FIPS-capable binary and check that the `version` sub-command output contains `(FIPS-distribution: false)`.
```
$ make apm-server
$ ./apm-server version
```
Build a FIPS-capable binary and check that the `version` sub-command output contains `(FIPS-distribution: true)`.
```
$ make apm-server-fips
$ ./apm-server-fips version
```
> Include FIPS distribution information in version command output

- integrationservertest/upgrade-config.yaml
8.19 and 9.1 no longer have the same apm-data resource version after https://github.com/elastic/elasticsearch/pull/130478 and https://github.com/elastic/elasticsearch/pull/130477 have been merged. So, it is expected that they will have lazy rollover across upgrades.
Run workflow: https://github.com/elastic/apm-server/actions/runs/16112715129.
> iserver-test: Fix upgrade config lazy rollover

- docs/release-notes/known-issues.md
Fix an unintended nested known issue entry in https://www.elastic.co/docs/release-notes/apm/known-issues
> docs: Fix known issues unintended nested entries

- integrationservertest/upgrade-config.yaml
PR https://github.com/elastic/elasticsearch/pull/131296 made changes to apm-data plugin for 9.2, so 9.1 and 9.2 no longer share resource version.
Run workflow.
> iserver-test: Remove 9.1 from 9.2 lazy rollover exception

- .github/workflows/update-compose.yml
Keep our CI ecosystem secured.
Test the `merge-queues` too :)
In the CI, see https://github.com/elastic/apm-server/actions/runs/16646856007
> updatecli: use the new gh token action, and remove experimental

- internal/beatcmd/beat.go
- internal/beater/beater.go
- internal/beater/beater_test.go
replace remaining `NewRegistry` with `GetOrCreateRegistry`
those calls should not panic but replace them with a safer alternative to prevent future issues
Closes https://github.com/elastic/apm-server/issues/17905
> refactor: replace NewRegistry with safer GetOrCreateRegistry

- packaging/docker/Dockerfile
Fix /etc/pki created with file mod 0644 instead of 0755, causing ca-bundle to be inaccessible. This is a regression from #16956 
Fix to be backported to all active 8.x.
changelog: "Fix a 8.18.1 and 8.19.0 regression in docker image causing permission denied when accessing /etc/pki/tls/certs/ca-bundle.crt due to incorrect directory permissions"
Ubuntu:
UBI:
```
carson@carson-elastic-t:~/issues/apm-server-18092$ docker run -it --rm elastic/apm-server:8.18.0 /bin/sh -c 'ls -al /etc/pki/tls/certs/ca-bundle.crt'
-rw-r--r-- 1 root root 215902 Apr 10 15:18 …
```
> Fix docker image permission denied on ca-bundle.crt

- Makefile
Long random generated upgrade path (e.g. https://github.com/elastic/apm-server/actions/runs/17197438603/job/48781699439) causes test to hit 1h timeout. This PR increases the timeout so this doesn't happen.
> iserver-test: Increase timeout

- .github/workflows/backport-active.yml
Support backports after a PR has been merged and labelled with `backport-active-*`.
Fixes a corner case when the PRs have been labeled after being merged with the supported list of active branches.
> github-actions: support backport labels after being merged

- docs/release-notes/breaking-changes.md
- docs/release-notes/deprecations.md
- docs/release-notes/index.md
- docs/release-notes/known-issues.md
Adds ` applies_to` metadata for cumulative docs. See https://docs-v3-preview.elastic.dev/elastic/docs-builder/tree/main/syntax/applies
Contributes to https://github.com/elastic/docs-content-internal/issues/253
> Add applies_to statements

- dev_docs/RELEASES_8x.md
I ran the patch-release workflow yesterday against the `main` branch by mistake. This resulted in the automation create no PRs. 
Updating the docs to specify that the patch release workflow needs to be ran against the base branch i.e `8.18` for the `8.18.7` patch release.
Release note PRs should also target the relevant base branch.
> Update instructions for 8.x patch releases
